### ISSUE TITLE
Analyzer of Last Resort

### ISSUE THREAD

**Issue by ahgit1** [zeek/zeek#1000]
The old communitybro used to have a "analyzer of last resort"  for tcp & udp connections. ie if a connection didn't have an analyzer attached then an event was generated which could allow the packets contents to be logged. Would it be possible to add this functionality to zeek ?

https://github.com/llinsky/communitybro/blob/master/src/analyzer/protocol/tcp/TCP.cc line 1618
& https://github.com/llinsky/communitybro/tree/master/scripts/base/protocols/tcp
https://github.com/llinsky/communitybro/tree/master/scripts/base/protocols/udp

**Comment by 0xxon** [comment]
Hi,

it is in obviously possible to implement this in Zeek. Note that we cannot pull the changes from the other repository due to license incompatibilities. So - someone has to reimplement this.

**Comment by rsmmr** [comment]
I'll close the ticket but if someone contributed  a PR for this feature, I imagine we'd merge it (assuming no license trouble)
