### ISSUE TITLE
Ja3s is being added to ssl.log but ja3 info not added to ssl.log.

### ISSUE THREAD

**Issue by pussinboots1992** [zeek/zeek#1008]
I have this weird issue in Zeek where only the ja3s information is being added to my ssl.log file, not sign of any ja3 information...How should I start troubleshooting this ?

I installed using zkg an have the following in my local.zeek file, I had no errors when starting on installing anything (Zeek included):

@load packages

Zeek is installed on my proxy server (running Squid) so it should see all SSL traffic going back and forth.

**Comment by jsiwek** [comment]
You could look to see if `reporter.log` or `weird.log` have any suspicious entries that may be relevant (e.g. might indicate scripting errors or packet capture problems).  Or manually add `print` or other logging statements to the ja3 scripts to try to understand if it's even running.

If you provide explicit steps one could use to reproduce the behavior: ideally what version of Zeek, pcap file, and/or other step-by-step commands to set up some environment that shows the issue, that would make it easier for others to help in the troubleshooting process.

Also, a better place to ask for general help/ideas might be the Zeek mailing list or slack: https://zeek.org/connect/

You might also ask the authors of the plugin if they have advice/ideas: https://github.com/salesforce/ja3
