### ISSUE TITLE
Service VLAN tag identifier (S-Tag) on Q-in-Q tunnel

### ISSUE THREAD

**Issue by ahgit1** [zeek/zeek#1012]
Could support be added for QinQ VLAN identifier 0x88A8. I've modifed Packet.cc in iosource as below and it appears to work but I'm not sure that it takes account of all scenarios correctly

line 176 while ( protocol == 0x8100 || protocol == 9100 || protocol == 0x8864 || protocol == 0x88A8 )
line 184 add - case 0x88A8: in the VLAN over ethernet case

Sample pcap below
https://www.cloudshark.org/captures/e4fa464563d2

**Comment by rsmmr** [comment]
Will be implemented with #1046.
