### ISSUE TITLE
Option to maintain original DNS query case

### ISSUE THREAD

**Issue by rvictory** [zeek/zeek#1013]
In the same vein as https://github.com/zeek/zeek/issues/854 I think it would be helpful to provide access to the original DNS query case in both the DNS log and in all related DNS events. Query case could be a distinguishing factor for various detections and currently all DNS queries are downcased when they are parsed/processed in the DNS analyzer.

**Comment by stevesmoot** [comment]
Perhaps only when it is not the same as the downcased.
-s

**Comment by rvictory** [comment]
I was thinking perhaps a new param on the end of the existing events and also a new optional field that you could turn on in dns.log. Unlike the MIME and HTTP header events, the DNS query isn't in a record so we can't just add a new field to the record like in issue 854. 

If I understand things right, we can now add new params to the end of events without breaking existing event handlers that don't include it, right?

If so, seems like a pretty simple solution.

**Comment by jsiwek** [comment]
> If I understand things right, we can now add new params to the end of events without breaking existing event handlers that don't include it, right?

Yes, you can change event parameters in non-breaking ways now (and new params don't necessarily have to come at the end of the parameter list).

> the DNS query isn't in a record so we can't just add a new field to the record like in issue 854.

For #854, it was actually a combo of extending a record and extending an event, so could still use that as an example of how to do the later if planning to make a PR related to DNS queries:

https://github.com/zeek/zeek/commit/5032993b94b0ef6ce587337b3156701a9da92bba#diff-978a30a2ac40a10fbf3c8b5500d3a9f3R1675
https://github.com/zeek/zeek/commit/5032993b94b0ef6ce587337b3156701a9da92bba#diff-c67af0acc6a4244f7c1bb4f312ea50c6R69

The docs that generally describe "alternate event prototype declarations" are here:

https://docs.zeek.org/en/master/script-reference/types.html#type-event

**Comment by rvictory** [comment]
I made the changes and opened a PR: https://github.com/zeek/zeek/pull/1015

Hopefully I covered everything I should have, first time working on Zeek's source in this sort of capacity!

**Comment by rsmmr** [comment]
This has been merged.
