### ISSUE TITLE
TTL field (hlim) in icmp_echo_reply icmp event shows TTL of request, not reply.

### ISSUE THREAD

**Issue by benjeems** [zeek/zeek#1019]
The TTL field of the icmp_echo_reply icmp record doesn't show the response TTL, instead it shows the request TTL. eg when both the request and response are together in the same pcap, the below response should be TTL of 250, not 64. Note the orig and resp are also not reversed as you might expect.

**Request**, contents of [icmp_echo_request]([url](url)) icmp record
[orig_h=192.168.20.13, resp_h=142.250.66.174, itype=8, icode=0, len=56, hlim=64, v6=F]
**Response**, contents of icmp_echo_reply icmp record
[orig_h=192.168.20.13, resp_h=142.250.66.174, itype=8, icode=0, len=56, **hlim=64**, v6=F]

If you run this with only the reply packet, it does works ok.
**Response**, contents of icmp_echo_reply icmp record
[orig_h=142.250.66.174, resp_h=192.168.20.13, itype=0, icode=0, len=56, **hlim=250**, v6=F]

**Comment by 0xxon** [comment]
I kind of wonder if this was originally desired behavior - for all of the other fields in icmp_conn it is specified that they are filled out based on the original request that created the connection, not the one one is currently observing.

That being said - this clearly is not really great - and I agree that changing this makes sense. I would be tempted to say that it also might make sense to update len based on the current packet too.

**Comment by rsmmr** [comment]
Guess the main question here is if we can change this without causing trouble. I'd say that's fine.
