### ISSUE TITLE
system call does not reap children and wait not exposed

### ISSUE THREAD

**Issue by traetox** [zeek/zeek#1030]
## What I am doing

1. Executing zeek directly inside a docker container `zeek -W -C -i p1p1 /main.zeek`

## What I am seeing

1. many defunct processes as a result of file rotation

## Core problem

The default ascii logger rotates files using a `system` call but does not reap child prcesses.  There is no system to `wait` on the result of a `system`.  As a result any preprocessors or external scripts are not reaped and zombie processes just pile up.

## Proposal

Expose a wait call so that callers can wait child processes to finish and reap the PID.

## Version

I am working on version 3.0.7

## extra info

main.zeek file is as follows:
```
redef Log::default_rotation_interval = 600 secs;
redef Log::default_rotation_postprocessor_cmd = "/log-export.sh";
```

The `/log-export.sh` script is also left un-reaped, leaking additional PIDs.

**Comment by jsiwek** [comment]
Not too sure what you're really seeing, as mentioned in #1029, we we shouldn't need to expose a `wait` for this since `system` does it already.  Are you really seeing zombies?  Or possibly an overloaded system where those child post-processes don't actually get scheduled enough to actually finish?

**Comment by traetox** [comment]
I see additional defunct processes after each log rotation.

**Comment by jsiwek** [comment]
As mentioned in #1029, running some form of `init` at PID 1 in Docker rather than `zeek` would be the general answer.

**Comment by floren** [comment]
To be clear, the official Zeek method for cleaning up Zeek's leaked system resources is to periodically kill & restart it? As far as I know, a process cannot reap grandchild processes unless the *child* process has exited.
