### ISSUE TITLE
API backwards compatibiliy; return type for vector & set ->type changed

### ISSUE THREAD

**Issue by 0xxon** [zeek/zeek#1032]
The return type of the type member of vector/set types changed from TypeTag to zeek::TypeTag. This will break code that expects it to be a TypeTag.

example code that breaks:
```
TypeTag type = vals[i]->type; // (with vals being val->val.vector_val.vals)
```

In sourcecode: https://github.com/0xxon/zeek-postgresql/blob/fb72b41140094ec8795cd7aaecbb3997c28ff202/src/PostgresWriter.cc#L350

I understand that we might not want to do anything about this one - but I thought I would raise it, at least for documentation purposes. This one also seems like it might be slightly more common - iterating over the types like this might be commonly needed in input readers/writers.

**Comment by jsiwek** [comment]
Didn't look closely at this, but might be a general issue with how enum deprecations are handled and just an idea to explore may be more like this (need help thinking more critically about it and also chose to test on function_flavor, not TypeTag, since there's so much less to do to get a toy example running):

```diff
diff --git a/src/Type.h b/src/Type.h
index c123eb397..481c5ab24 100644
--- a/src/Type.h
+++ b/src/Type.h
@@ -51,12 +51,6 @@ enum [[deprecated("Remove in v4.1. Use zeek::TypeTag instead.")]] TypeTag {
 #define NUM_TYPES (int(TYPE_ERROR) + 1)
 };

-enum [[deprecated("Remove in v4.1. Use zeek::FunctionFlavor instead.")]] function_flavor {
-	FUNC_FLAVOR_FUNCTION,
-	FUNC_FLAVOR_EVENT,
-	FUNC_FLAVOR_HOOK
-};
-
 enum [[deprecated("Remove in v4.1. Use zeek::InternalTypeTag instead.")]] InternalTypeTag : uint16_t {
	TYPE_INTERNAL_VOID,
	TYPE_INTERNAL_INT, TYPE_INTERNAL_UNSIGNED, TYPE_INTERNAL_DOUBLE,
@@ -110,6 +104,18 @@ enum FunctionFlavor {
	FUNC_FLAVOR_EVENT,
	FUNC_FLAVOR_HOOK
 };
+}
+
+using function_flavor [[deprecated("Remove in v4.1. Use zeek::FunctionFlavor instead.")]] = zeek::FunctionFlavor;
+
+[[deprecated("Remove in v4.1.	Use zeek::FUNC_FLAVOR_FUNCTION.")]]
+constexpr auto FUNC_FLAVOR_FUNCTION = zeek::FUNC_FLAVOR_FUNCTION;
+[[deprecated("Remove in v4.1.	Use zeek::FUNC_FLAVOR_EVENT.")]]
+constexpr auto FUNC_FLAVOR_EVENT = zeek::FUNC_FLAVOR_EVENT;
+[[deprecated("Remove in v4.1.	Use zeek::FUNC_FLAVOR_HOOK.")]]
+constexpr auto FUNC_FLAVOR_HOOK = zeek::FUNC_FLAVOR_HOOK;
+
+namespace zeek {

 enum InternalTypeTag : uint16_t {
	TYPE_INTERNAL_VOID,
@@ -532,14 +538,6 @@ public:
	FuncType(IntrusivePtr<RecordType> args, IntrusivePtr<Type> yield,
		 FunctionFlavor f);

-#pragma GCC diagnostic push
-#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
-	[[deprecated("Remove in v4.1. Use the version that takes zeek::FunctionFlavor instead.")]]
-	FuncType(IntrusivePtr<RecordType> args, IntrusivePtr<Type> yield, ::function_flavor f)
-		: FuncType(args, yield, static_cast<FunctionFlavor>(f))
-		{}
-#pragma GCC diagnostic pop
-
	IntrusivePtr<Type> ShallowClone() override;

	~FuncType() override;
@@ -561,13 +559,6 @@ public:
	void ClearYieldType(FunctionFlavor arg_flav)
		{ yield = nullptr; flavor = arg_flav; }

-#pragma GCC diagnostic push
-#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
-	[[deprecated("Remove in v4.1. Use the version that takes zeek::FunctionFlavor instead.")]]
-	void ClearYieldType(::function_flavor arg_flav)
-		{ yield = nullptr; flavor = static_cast<FunctionFlavor>(arg_flav); }
-#pragma GCC diagnostic pop
-
	int MatchesIndex(zeek::detail::ListExpr* index) const override;
	bool CheckArgs(const type_list* args, bool is_init = false) const;
	bool CheckArgs(const std::vector<IntrusivePtr<Type>>& args,
```

**Comment by rsmmr** [comment]
Using `constexpr auto` for the labels is a nice thought.

Just so that I undertand the original problem: Are the labels the reason why we can't use create a type alias?

**Comment by timwoj** [comment]
C++ (or C for that matter) can't assign one enum type to another, and there's no way to add assignment operators for enums, so you get the error that @0xxon got above. `Var` already had the type of `type` changed to the namespaced version of `TypeTag` so her code tried to assign a value from `zeek::TypeTag` to `::TypeTag`.

I'm a little concerned about removing the global version of an enum and whether that will cause other build failures along the line if the code can't see the namespaced version of it. I'll find one that I haven't converted yet and play with it.

**Comment by timwoj** [comment]
Yep, the way that @jsiwek suggested above works. PR above that fixes the current state of master. I'll fix the follow-on namespacing PR once this one is merged.
