### ISSUE TITLE
should Zeek script logging be consistently current time or network time ?

### ISSUE THREAD

**Issue by simonhf** [zeek/zeek#1036]
I'm a Zeek script newbie and I'm trying to log while reading PCAP packets.

If my Zeek script logs via `Reporter::info()` then the log line is preceded with network time:

```
event new_packet(c: connection, p: pkt_hdr) {
    Reporter::info(fmt("packet %d: %s, %s", packet_count, c$id, to_json(p)));
}
```

Example output:

```
$ cat reporter.log 
...
1305147113.275324       Reporter::INFO  packet 1: [orig_h=1.2.3.4, orig_p=1234/udp, resp_h=4.3.2.1, resp_p=4321/udp], {"ip":{"hl":20,"tos":0,"len":32,"id":4660,"ttl":128,"p":17,"src":"1.2.3.4","dst":"4.3.2.1"},"udp":{"sport":{"port":1234,"proto":"udp"},"dport":{"port":4321,"proto":"udp"},"ulen":12}}    ./../../pcap-sample.zeek, line 12
...
```

But if my Zeek script logs via `print` then the log line is preceded with current time:

```
redef Log::print_to_log = Log::REDIRECT_STDOUT;

event new_packet(c: connection, p: pkt_hdr) {
    print(fmt("packet %d: %s, %s", packet_count, c$id, to_json(p)));
}
```

Example output:

```
$ cat print.log
...
1593218479.189438       packet 1: [orig_h=1.2.3.4\x2c orig_p=1234/udp\x2c resp_h=4.3.2.1\x2c resp_p=4321/udp]\x2c {"ip":{"hl":20\x2c"tos":0\x2c"len":32\x2c"id":4660\x2c"ttl":128\x2c"p":17\x2c"src":"1.2.3.4"\x2c"dst":"4.3.2.1"}\x2c"udp":{"sport":{"port":1234\x2c"proto":"udp"}\x2c"dport":{"port":4321\x2c"proto":"udp"}\x2c"ulen":12}}
...
```

I noticed that the C++ function `print_log()` has `current_time()` hard-coded [1].

Should both logging functions log time consistently? And if so, should it be current time or network time? (I'm assuming it should be network time... and at least consistent...)

On a side note, the `Reporter::info()` output (examine the commas) seems cleaner than the `print()` output (shown as `\x2c` ?!) too...

[1] https://github.com/zeek/zeek/blob/master/src/Stmt.cc#L218

**Comment by jsiwek** [comment]
> Should both logging functions log time consistently? And if so, should it be current time or network time? (I'm assuming it should be network time... and at least consistent...)

I agree: #1037

> On a side note, the `Reporter::info()` output (examine the commas) seems cleaner than the `print()` output (shown as `\x2c` ?!) too...

The difference is that `reporter.log` is logging a single, pre-formatted `string`:

https://github.com/zeek/zeek/blob/eb1a408b6aa3bb0f53d07be097ba6ad77fe4a846/scripts/base/frameworks/reporter/main.zeek#L31

and `print.log` is a variable number of strings:

https://github.com/zeek/zeek/blob/eb1a408b6aa3bb0f53d07be097ba6ad77fe4a846/scripts/base/frameworks/logging/main.zeek#L86

Your example passes only one argument, but it's still going to use a full `vector of string` to log it consistently with other print statements which may have any number of arguments.  In a default ASCII log, you'll see a `set_separator` defined in the first few lines with default value of comma `,`, which is used to delimit members of various composite types (vector/set).  The output of `to_json()` is a string containing comma `,` characters which would make parsing of the `vector of string` field ambiguous, so they're escaped as `\x2c`.

If it's not the most readable format for your workflow/debugging, you might customize the set separator to be something that occurs less frequently:

```zeek
event zeek_init()
	{
	local df = Log::get_filter(Log::PRINTLOG, "default");
	df$config["set_separator"] = "|";
	Log::add_filter(Log::PRINTLOG, df);
	}
```

Or if you're working all locally (i.e. no cluster / remote logging), this may be simpler:

```zeek
# (The default setting, just showing it for clarity)
redef Log::print_to_log=Log::REDIRECT_NONE;

event new_packet(c: connection, p: pkt_hdr) {
    print network_time(), fmt("packet %d: %s, %s", packet_count, c$id, to_json(p));
}
```

and redirect stdout if you'd like: `zeek -r a.pcap > out`

**Comment by simonhf** [comment]
> > Should both logging functions log time consistently? And if so, should it be current time or network time? (I'm assuming it should be network time... and at least consistent...)
> 
> I agree: #1037

FYI in retrospect, I'm not sure that I agree that network time is always the best for the the initial prefix for log output. So I created this ticket [1] to express why, and ask if there's a why to dynamically choose at run-time?

The time conflict seems to be that if you want to use logging to debug code then current time is useful and network time does not seem useful at all. And if you want to have a single log to debug code *and* debug timestamps from PCAP / trace files, then current time and network time don't mix very well for those two purposes.

Therefore, I'm wondering if it makes more sense to always try to use current time as the log line prefix, and only use network time if available elsewhere in the log line? This way we can clearly see *both* the current time and network time used, e.g. a few packets might have 1ms current time elapsed but many minutes or hours network time elapsed...

[1] https://github.com/zeek/zeek/issues/1054
