### ISSUE TITLE
How could I get tcp reassembly result with timestamp of packet?

### ISSUE THREAD

**Issue by liutianchen** [zeek/zeek#1038]
Hi, I am new to use zeek, I look through the content about Tcp Reassembly in Zeek doc and I found API set_contents_file which helps a lot to me to get byte stream from the Pcap file full of unordered and vacant tcp packets. But I cannot figure out how to obtain the timestamp of packet with a certain piece of tcp payload data from original packet. Is there any simple config to make it out? Or it means I need to write some plugin for the Zeek? Because I think a certain Tcp payload could be separated into several Tcp packet and If I need the timestamp I have to give a rule to determine the belonging of payload.
Thank you.

**Comment by 0xxon** [comment]
Hi,

We don't use GitHub issues for support questions. Questions like this are best answered using our  mailing list, which is followed by Zeek developers and professional users. You can join here:

http://mailman.icsi.berkeley.edu/mailman/listinfo/zeek

Once you receive confirmation you’ve been added to the list, send this question there.

 Johanna

**Comment by 0xxon** [comment]
Or - for this kind of question - zeek-dev might be better. http://mailman.icsi.berkeley.edu/mailman/listinfo/zeek-dev.

If you prefer it you also can try our Slack, which also has a development channel - https://zeek.org/connect/

**Comment by liutianchen** [comment]
Thank you, it’s really nice of you to inform this, I will goto the slack to ask the problem.
