### ISSUE TITLE
str_split always returns a vector with the first element missing

### ISSUE THREAD

**Issue by vpax** [zeek/zeek#1040]
`str_split` goes out of its way to ensure that the vector it returns has an empty first element. It's hard to see why this is desired behavior, and the minimal documentation for the BiF ("Splits a string into substrings with the help of an index vector of cutting points") doesn't make mention of it.  I'm guessing this is vestigial from when something was 1-based rather than 0-based.  It's a pity that fixing this would be a breaking change.

**Comment by jsiwek** [comment]
Not too bad to deprecate and add an alternate 0-based version for people to migrate to, say named `split_string_indices()`.  Did do that in the past with several BIFs doing the confusing 1-based logic, just maybe missed this one.

**Comment by vpax** [comment]
That sounds good to me, thanks!
