### ISSUE TITLE
compress_path() doesn't normalize some paths correctly

### ISSUE THREAD

**Issue by jsiwek** [zeek/zeek#1041]
Probably related to what @dopheide-esnet reported on Slack:

```zeek
print compress_path("./../foo");
print compress_path("././../foo");
```

Yields the wrong results:

```
foo
./foo
```

We already have path normalization implemented in C++ here:

https://github.com/zeek/zeek/blob/a5a51de3c469c44a6d88a337c3486ecedd6a42a3/src/util.cc#L1603

And think it works correctly in this case, so would suggest not bothering to fix the script-layer version of `compress_path()`: just change it to a BIF calling `normalize_path()`.

**Comment by dopheide-esnet** [comment]
Here's an example from a cluster:   
loaded_scripts.log:
...
        /usr/local/zeek/spool/installed-scripts-do-not-touch/site/react/__load__.bro
          /usr/local/zeek/spool/installed-scripts-do-not-touch/site/react/main.bro
          /usr/local/zeek/spool/installed-scripts-do-not-touch/site/react/gridftp.bro
          /usr/local/zeek/spool/installed-scripts-do-not-touch/site/react/conn-bulk.bro
            /usr/local/zeek/spool/installed-scripts-do-not-touch/site/react/conn-bulk.zeek
          /usr/local/zeek/spool/installed-scripts-do-not-touch/site/react/ssh.bro
          /usr/local/zeek/spool/installed-scripts-do-not-touch/site/react/arista.bro
...
(Note that it does get the ident 'level' correct in this case.)

[zeek@bro-east1 site]$ ls conn-bulk.zeek
conn-bulk.zeek
[zeek@bro-east1 site]$ head -n 2 react/conn-bulk.bro
@load ./main
@load ../conn-bulk.zeek

**Comment by timwoj** [comment]
@dopheide-esnet I just added https://github.com/zeek/zeek/commit/560ee0c05e32e068ca59f9110f45a0413dc751f3, do you want to see if that fixes your issue?

**Comment by dopheide-esnet** [comment]
Yeah, initial test looks great.
