### ISSUE TITLE
HTTP on non-standard port not recognized

### ISSUE THREAD

**Issue by klsdfgi4l223** [zeek/zeek#1059]
Hi all,

I noticed that many http requests don't get recognized if they're not on a standard port (80). 

Here is a minimal sanitized sample:
https://we.tl/t-QqrjFZYoom

The http decoder is only run, when I change my config to something like this:

```
global post_ports: set[port] = { 28659/tcp } &redef;

event zeek_init()
{
  Analyzer::register_for_ports(Analyzer::ANALYZER_HTTP, post_ports);
}
```

**Comment by JustinAzoff** [comment]
Hi,  this sounds like another case of https://github.com/zeek/zeek/issues/343

can you see if

```
redef dpd_buffer_size=8192;
```

also fixes it?  alternatively can you try using  this signature:

```
signature dpd_http_client_only {
  ip-proto == tcp
  payload /^[[:space:]]*(OPTIONS|GET|HEAD|POST|PUT|DELETE|TRACE|CONNECT|PROPFIND|PROPPATCH|MKCOL|COPY|MOVE|LOCK|UNLOCK|VERSION-CONTROL|REPORT|CHECKOUT|CHECKIN|UNCHECKOUT|MKWORKSPACE|UPDATE|LABEL|MERGE|BASELINE-CONTROL|MKACTIVITY|ORDERPATCH|ACL|PATCH|SEARCH|BCOPY|BDELETE|BMOVE|BPROPFIND|BPROPPATCH|NOTIFY|POLL|SUBSCRIBE|UNSUBSCRIBE|X-MS-ENUMATTS|RPC_OUT_DATA|RPC_IN_DATA)[[:space:]]*/
  tcp-state originator
  enable "http"
}
```

put that in a file called http.sig and do

```
@load-sigs ./http.sig
```

**Comment by klsdfgi4l223** [comment]
Hey!
Changing the dpd_buffer_size does indeed work! Are there any drawbacks to keeping it at this high value or making this the default?

**Comment by JustinAzoff** [comment]
increasing the dpd buffer size has the potential to increase memory usage (upwards of 7168 additional  bytes per active connection).  It's also not a 100% fix.. increasing it likely causes the majority of requests to fit in the buffer, but there's still the potential for a  request to be larger than 8k.  Changing the dpd signatures to avoid this problem entirely is probably the better way forward.
