### ISSUE TITLE
Compiling release/3.1 with --enable-static-broker and extra CXXFLAGS fails linking caf-generate-rst

### ISSUE THREAD

**Issue by awelzel** [zeek/zeek#1060]
Hello,

I'm attempting to compile the `release/3.1` branch as follows:
```
$ git rev-parse HEAD
63a403f3d6f8c660528cd38b2c61d5ca32965eab
$ CFLAGS="-fno-omit-frame-pointer"  CXXFLAGS="-fno-omit-frame-pointer" ./configure --disable-python --enable-static-binpac --enable-static-broker  --disable-broker-tests
```
This fails with an error linking `caf-generate-rst`.
```
$ make -j$(nproc)
...
[ 38%] Building CXX object src/analyzer/protocol/krb/CMakeFiles/plugin-Zeek-KRB.dir/Plugin.cc.o
[100%] Linking CXX executable ../bin/caf-generate-rst
/usr/bin/ld: /home/awelzel/oss/zeek/build/aux/broker/lib/libcaf_core_static.a(actor_system.cpp.o): undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'                                                                                                                   
/usr/bin/ld: //lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[6]: *** [doc/CMakeFiles/caf-generate-rst.dir/build.make:91: bin/caf-generate-rst] Error 1

```

This appears to only happen when passing extra CXXFLAGS and using `--enable-static-broker`.

Is this just an unusual thing to do or maybe something on my end?

Let me know if you need any more information.
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

$ gcc --version
gcc (Debian 8.3.0-6) 8.3.0
```

**Comment by awelzel** [comment]
> Is this just an unusual thing to do or maybe something on my end?

This doesn't seem to happen with master. I don't have a strict requirement for `--enable-static-broker` either, so feel free to close - maybe fixing in `3.1` is more trouble than it's worth.

**Comment by jsiwek** [comment]
Thanks for checking master, too.  Possibly a duplicate observation of #826 and ultimately patched via https://github.com/zeek/broker/pull/94/commits/357e060284b5bfea769b526202ee908872c5c2e3

Guess it got left out or forgotten in 3.1.x and may not ever since the 3.2.x branch will start soon-ish.
