### ISSUE TITLE
Add "zeek/" link to include directory

### ISSUE THREAD

**Issue by rsmmr** [zeek/zeek#1068]
From Slack:

[Robin] As part of #266, there was the idea of putting a symlink for headers in place inside the source directory, so that people can start including Zeek APIs through #include <zeek/...>. Do we want to do that?

[Johanna] Seems like a good idea.

[Jon] makes sense to me, and maybe just worrying about the obvious, but such an #include <zeek/…> would need to work against install-tree as well, so that likely means teaching zeek-config --include_dir to output $prefix/include:$prefix/include/zeek (keep the old path in there for backwards compat) and teaching ZeekPluginDynamic.cmake to expand out an include path that has : chars

**Comment by rsmmr** [comment]
Re/ the install path: eventually we'd probably want it to return just `$prefix/include` but for the transition doing both sounds right.

**Comment by jsiwek** [comment]
> eventually we'd probably want it to return just `$prefix/include` but for the transition doing both sounds right.

Is there a particular deprecation strategy in mind to phase `$prefix/include/zeek` out of `zeek-config --include_dir` output?  

Is that just informing people in `NEWS` that they should start using `#include <zeek/Foo.h>` in their plugins?  Or would it be creating an additional set of redirecting-headers that contain only a pragma warning and auto-redirect?

What's the underlying reason we're wanting to do this again?  If it's only helping solve the problem of potential header name collisions, it could be fine to just allow plugins to resolve via either `<Foo.h>` or `<zeek/Foo.h>`, with the later being the suggested way (and helpful way in the case anyone does encounter a collision/ambiguity), but not sure there's anything "wrong" with the original way?

The other next step to this is going ahead to change all Zeek source files to the `#include "zeek/Foo.h"` style?  Or is that for later?

**Comment by rsmmr** [comment]
A NEWS entry sounds most reasonable to me. A complete set of redirecting headers would be pretty extreme. It's an easy change to make.  If we deprecate now and remove with 4.1, that should give people plenty time to make it.

The "original way" is very non-standard, pretty much everybody puts their stuff into `myprog/*` headers these days. That avoids conflicts, it is much more readable (what does `#include <Func.h>` actually include?), and it also matches well with our new namespacing (`zeek::*` is pulled from `zeek/`).

We can change the Zeek source files later (next cycle), for now I'd primarily like to have external code be able to start using the new scheme.

**Comment by albert-github** [comment]
Having the same files in 2 different path is not a good thing and having a symbolic link looks like a nice solution but it has also some drawbacks, a.o. all files will be accessible through both paths and one is actually creating an endless loop here (`zeek->.`). It would be much better to place the files in the right directories and adjust the paths in the code or, in my opinion an even better solution, use the include option (most of the times `-I`) for this.
