### ISSUE TITLE
enum names can clash without warning

### ISSUE THREAD

**Issue by vpax** [zeek/zeek#1080]
I think we can all agree that in the following:
```
    type a: enum { RED, BLUE };
    type b: enum { BLUE, GREEN };
    print BLUE == GREEN;
```
we'd like it to print `F`, but `T` is what we get.  (Or we'd like an error when the name is reintroduced in the first place.)
In practical terms, this screws up NetControl, where `DROP` is both a `RuleType` enum and a `CatchReleaseActions` enum.

**Comment by jsiwek** [comment]
Any opinions on which route to go or memories of historical intent?  The enum docs say they're not intended to have values/ordering, only for use in (in)equality comparison, so it will likely work as expected if changed to additionally compare enum name strings.

1. Error on enum name redefinition
  * May be the behavior people expect by instinct anyway
  * Technically a "breaking change": for sure need to at least rename a `DROP`, also possible that a custom script has came to rely on enum-name-sharing (in practice, maybe those aren't too likely/worrying that anyone will care)

2. Allow enums to share names (fix the bug in how they're currently compared)
  * May not be expected/instinctual behavior, but ultimately more "user friendly" -- if a name is a Good Fit for multiple enum types, don't get in the way of that
  * More "costly" to compare (doubt it would be noticeable in practice, just measure afterward to verify)

**Comment by rsmmr** [comment]
These are namespaced relative to module name, right? Then the impact of (1) should pretty small, and I would vote for that. 

(What I'd actually prefer doing is require scoping: `a::RED`, but that would be a major breaking change).

**Comment by vpax** [comment]
I think there's a way to have (2) w/o cost, which is that every time you encounter a name in an enum definition, if it already has an internal value, fine, keep that; but if it doesn't, give it the next free such value.  So above, RED would be given 0, BLUE would be given 1, and GREEN would be given 2.  This gives the expected behavior on-the-cheap.

That said, (1) is probably best, because without it the readability of the code diminishes.
