### ISSUE TITLE
Support Input Framework with Sets and Events

### ISSUE THREAD

**Issue by cgiraldo** [zeek/zeek#1083]
I can´t configure Input Framework to use a `Set` and `event change notifications` at the same time.

With the following script I get a `error in <params>, line 1: Input stream known_macs: Table event must take 4 arguments`:

```
type Idx: record {
   entry: string;
};

global entries: set[string] = set();

event entry_notify(description: Input::TableDescription, tpe: Input::Event, left: Idx ) {
        print fmt("%s", left);
}

event zeek_init()
{
    Input::add_table([$source="entries.file", $name="entries",
                          $idx=Idx, $destination=entries, $mode=Input::REREAD, $ev=entry_notify]);

}
```
If I modify entry_notify args to be 4 (adding a right: any arg), I get the  `error in <params>, line 1: Encountered a null value when creating a table stream`.

**Comment by 0xxon** [comment]
On a first glance, this looks like this is just broken for sets.

I am happy to take a look at this - but I am unavailable for the rest of this week. If anyone else feels like doing this - please just reassign it to yourself.
