### ISSUE TITLE
Zeek MySQL Protocol parsing exceptions

### ISSUE THREAD

**Issue by Canon88** [zeek/zeek#1084]
Hi,
    I am testing using Zeek to log MySQL database operations.However, I found that Zeek can only log two events, user login and logout. No more database operations can be logged, and I have disabled tls on the database.
    Zeek: version 3.1.1
    Zeek: version 3.1.4
    Both versions exist

**MySQL Server**
```
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 8
Server version: 8.0.21 MySQL Community Server - GPL
```

**MySQL Client**
```
$ mysql -V
mysql  Ver 14.14 Distrib 5.7.30, for Linux (x86_64) using  EditLine wrapper
```

   Here is my Sample PCAP with my logs attached.
    **Sample PCAP**: [https://files.slack.com/files-pri/TSXGCHZE1-F0176CR3HBR/download/conn_mysql.pcap](url)

**dpd.log**
```
{
    "ts": 1595519112.584508,
    "uid": "CEp6u03IM3e841uj0k",
    "id.orig_h": "192.168.205.133",
    "id.orig_p": 47752,
    "id.resp_h": "47.98.114.44",
    "id.resp_p": 3306,
    "proto": "tcp",
    "analyzer": "MYSQL",
    "failure_reason": "Binpac exception: binpac exception: out_of_bound: LengthEncodedIntegerLookahead:i4: 8 > 6"
}  
```

**mysql.log**
```
{
    "ts": 1595519112.556686,
    "uid": "CEp6u03IM3e841uj0k",
    "id.orig_h": "192.168.205.133",
    "id.orig_p": 47752,
    "id.resp_h": "47.98.114.44",
    "id.resp_p": 3306,
    "cmd": "login",
    "arg": "root",
    "success": true,
    "rows": 0
}
{
    "ts": 1595519112.570164,
    "uid": "CEp6u03IM3e841uj0k",
    "id.orig_h": "192.168.205.133",
    "id.orig_p": 47752,
    "id.resp_h": "47.98.114.44",
    "id.resp_p": 3306,
    "cmd": "query",
    "arg": "select @@version_comment limit 1"
}
```

**Comment by 0xxon** [comment]
Could you perhaps also let us know the mysql version of the server and the client?

Also - pinging @grigorescu

**Comment by Canon88** [comment]
@0xxon 
yes, update

**MySQL Server**

```
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 8
Server version: 8.0.21 MySQL Community Server - GPL
```

**MySQL Client**

```
$ mysql -V
mysql  Ver 14.14 Distrib 5.7.30, for Linux (x86_64) using  EditLine wrapper
```

**Comment by grigorescu** [comment]
Thanks, I'm testing a fix now.

**Comment by grigorescu** [comment]
Fixed in topic/vlad/gh-1084. Can I use the PCAP for a unit test?

**Comment by Canon88** [comment]
> Fixed in topic/vlad/[gh-1084](https://github.com/zeek/zeek/issues/1084). Can I use the PCAP for a unit test?

Of course,
