### ISSUE TITLE
Missing DNS response data

### ISSUE THREAD

**Issue by taosecurity** [zeek/zeek#1085]
Hello,

The attached soa.pcap generates the following dns.log entry:

{
  "ts": 1591367999.306059,
  "uid": "CMdzit1AMNsmfAIiQc",
  "id.orig_h": "192.168.4.76",
  "id.orig_p": 36844,
  "id.resp_h": "192.168.4.1",
  "id.resp_p": 53,
  "proto": "udp",
  "trans_id": 8555,
  "query": "testmyids.com",
  "qclass": 1,
  "qclass_name": "C_INTERNET",
  "qtype": 28,
  "qtype_name": "AAAA",
  "rcode": 0,
  "rcode_name": "NOERROR",
  "AA": false,
  "TC": false,
  "RD": true,
  "RA": false,
  "Z": 0,
  "rejected": false
}

Tshark, however, sees the following:

    2 192.168.4.76 → 192.168.4.1  DNS 73 Standard query 0x216b AAAA testmyids.com
    3  192.168.4.1 → 192.168.4.76 DNS 136 Standard query response 0x216b AAAA testmyids.com SOA ns59.1and1.co.uk

Justin noticed the following:

1591367999.306059 dns_message
                  [1] is_orig: bool      = T
                  [2] msg: dns_msg       = [id=8555, opcode=0, rcode=0, QR=F, AA=F, TC=F, RD=T, RA=F, Z=0, num_queries=1, num_answers=0, num_auth=0, num_addl=0]
                  [3] len: count         = 31
1591367999.306059 dns_request
                  [1] msg: dns_msg       = [id=8555, opcode=0, rcode=0, QR=F, AA=F, TC=F, RD=T, RA=F, Z=0, num_queries=1, num_answers=0, num_auth=0, num_addl=0]
                  [2] query: string      = testmyids.com
                  [3] qtype: count       = 28
                  [4] qclass: count      = 1
1591367999.306059 protocol_confirmation
                  [1] atype: enum        = Analyzer::ANALYZER_DNS
                  [2] aid: count         = 3
1591367999.306059 dns_end
                  [1] msg: dns_msg       = [id=8555, opcode=0, rcode=0, QR=F, AA=F, TC=F, RD=T, RA=F, Z=0, num_queries=1, num_answers=0, num_auth=0, num_addl=0]
1591367999.354577 dns_message
                  [1] is_orig: bool      = F
                  [2] msg: dns_msg       = [id=8555, opcode=0, rcode=0, QR=T, AA=F, TC=F, RD=T, RA=T, Z=0, num_queries=1, num_answers=0, num_auth=1, num_addl=0]
                  [3] len: count         = 94

Justin said "so it sees the packet, but only raises the generic dns_message event."

I was using:

$ zeek -h
zeek version 3.0.7

Yacin noted an additional issue with a different pcap, saying " this google-addl.pcap too that shows the additional records are also not included."

I've included both pcaps in a .zip file.

[dns-pcap.zip](https://github.com/zeek/zeek/files/4967678/dns-pcap.zip)

Thank you!

**Comment by jsiwek** [comment]
By default, the Authority and Additional sections of DNS messages are not parsed due to "performance concerns", however, there's the `policy/protocols/dns/auth-addl.zeek` script to automatically configure it to do that as well as add that info to `dns.log`

```
$ zeek -C -r soa.pcap LogAscii::use_json=T protocols/dns/auth-addl
$ jq '.' dns.log
{
  "ts": 1591367999.306059,
  "uid": "ChtjJZDKSbmxTuvij",
  "id.orig_h": "192.168.4.76",
  "id.orig_p": 36844,
  "id.resp_h": "192.168.4.1",
  "id.resp_p": 53,
  "proto": "udp",
  "trans_id": 8555,
  "query": "testmyids.com",
  "qclass": 1,
  "qclass_name": "C_INTERNET",
  "qtype": 28,
  "qtype_name": "AAAA",
  "rcode": 0,
  "rcode_name": "NOERROR",
  "AA": false,
  "TC": false,
  "RD": true,
  "RA": false,
  "Z": 0,
  "rejected": false,
  "auth": [
    "ns59.1and1.co.uk"
  ]
}
```

```
$ zeek -C -r google-addl.pcap LogAscii::use_json=T protocols/dns/auth-addl
$ jq '.' dns.log
{
  "ts": 1595520028.583892,
  "uid": "CLFVVk11FAPVUBLcc",
  "id.orig_h": "192.168.1.50",
  "id.orig_p": 58775,
  "id.resp_h": "192.5.6.30",
  "id.resp_p": 53,
  "proto": "udp",
  "trans_id": 29971,
  "query": "google.com",
  "qclass": 1,
  "qclass_name": "C_INTERNET",
  "qtype": 2,
  "qtype_name": "NS",
  "rcode": 0,
  "rcode_name": "NOERROR",
  "AA": false,
  "TC": false,
  "RD": true,
  "RA": false,
  "Z": 2,
  "rejected": false,
  "auth": [
    "ns4.google.com",
    "ns1.google.com",
    "ns2.google.com",
    "ns3.google.com"
  ],
  "addl": [
    "2001:4860:4802:32::a",
    "2001:4860:4802:38::a",
    "216.239.38.10",
    "2001:4860:4802:34::a",
    "216.239.36.10",
    "216.239.34.10",
    "216.239.32.10",
    "2001:4860:4802:36::a"
  ]
}
```

So can we close this out as working as intended/documented, or are there suggestions to change/improve the default behavior?

**Comment by taosecurity** [comment]
Thanks Jon! I appreciate your response.
