### ISSUE TITLE
Build Zeek binary packages with libmaxminddb

### ISSUE THREAD

**Issue by philrz** [zeek/zeek#1086]
After some [discussion on Zeek Slack](https://zeekorg.slack.com/archives/CSZBXF6TH/p1594235715230000), I recently put together the Zeek package [geoip-conn](https://github.com/brimsec/geoip-conn) to easily populate Zeek `conn` records with [GeoLocation](https://docs.zeek.org/en/current/frameworks/geoip.html) details. The package includes a recent [GeoLite2 database](https://dev.maxmind.com/geoip/geoip2/geolite2/) and I intend to keep that current as MaxMind updates it weekly, to give Zeek users the benefit of always having current data at the time of install.

There's one snag, however: I found the package could be installed on top of the [Binary Packages for Zeek Releases](https://old.zeek.org/download/packages.html) (i.e. when doing the smoke test of `zeek -e "print lookup_location(8.8.8.8);"` the error response is `Zeek was not configured for GeoIP support`). This seems to imply that the only Zeek users that could currently benefit from this out-of-the-box GeoLocation package are those who have compiled their own Zeek with libmaxminddb, which seems like a bummer. While I completely understand/respect why Zeek maintainers don't care to bundle/distribute a geolocation _database_, would it be feasible to just ensure the Zeek binaries going forward are compiled on systems that have the libmaxminddb present so that the base support would be enabled?

**Comment by 0xxon** [comment]
I am in principle not opposed - assuming that this is just "add libmaxminddb as a requirement of the OS".

Let me try a bit if that is easily possible for the distributions that we support.

**Comment by 0xxon** [comment]
When the next rebuild finished (aka in a few hours), libmaxminddb will be part of the nighly builds for most platforms.

The exception is SLE, which does not contain the libmaxminddb package in the system repositories.

After this, if no one complains, I will pull this change over to the release builds.

**Comment by philrz** [comment]
Thanks @0xxon!

**Comment by rsmmr** [comment]
I assume this done?

**Comment by philrz** [comment]
@rsmmr: I just checked and it's not completely done. In line with the most recent update from @0xxon, I've just confirmed that the nightly build appears to be linked against libmaxminddb, as I was able to install the geoip-conn package on top of such a binary install and the smoke test gave me valid geolocation data. However, the same test with the recently-built v3.2.0 binary package still fails with the `Zeek was not configured for GeoIP support` error. @0xxon's last comment implied there was a wait to see if anyone complained after doing it on just the nightlies. I don't know what the expected time span was on that, but to get the full benefit of the change it would be great for the stable releases to have the benefit of this also.

**Comment by 0xxon** [comment]
I just added it to Zeek - since no one complained.

I do currently not plan adding this to zeek-lts. The reasoning is that some of the older distributions that we still compile for for zeek-lts (especially on the deb side) do not package libmaxminddb. Due to the setup of OBS, it is... let's say quite hard to only selectively include this for debian packages.

It will be included for zeek-lt too the moment we release Zeek 4.0.

So - current status (after the next build finished):
zeek-nightly: yes, except SLE
zeek: yes, except SLE
zeek-lts: no

**Comment by philrz** [comment]
Thanks @0xxon. That sounds like a fine plan! 👍

**Comment by philrz** [comment]
Update: I've confirmed that today's Zeek v3.2.1 binaries linked from [here](https://github.com/zeek/zeek/wiki/Binary-Packages) have the libmaxminddb support working out of the box. Thanks again!
