### ISSUE TITLE
Extend HTTP policy script to support logging header names and values

### ISSUE THREAD

**Issue by dspruell-s01** [zeek/zeek#1099]
Have found https://gist.github.com/sethhall/6153428 (http-header-logs.bro) useful as we do a lot of analysis on HTTP traffic. Would it be possible to extend the HTTP related policy scripts to include this functionality, or to move it out to Zeek package manager land, to make it a supported and easily enabled extension to functionality? HTTP is crucial today and there are a lot of threat use cases that call for logging and inspection of HTTP header data, so hoping to find ways to streamline.

**Comment by rsmmr** [comment]
@sethhall want to turn this into a package?

**Comment by sethhall** [comment]
Yeah, i could do that

**Comment by sethhall** [comment]
https://github.com/sethhall/zeek-log-all-http-headers

You can install from there for now, I'll get it into the package manager list soon
