### ISSUE TITLE
HTTP POST uploads unexpected request_body_len

### ISSUE THREAD

**Issue by dspruell-s01** [zeek/zeek#1100]
Observed in Bro 2.6, tested in Zeek 3.1.4 and 3.1.5
Linux and macOS

Seeing what seems like incorrect values for `resp_body_len` in http.log for connections where a client is doing a form-data file upload to responder host.

In this example, the subject file is 77772442 bytes on disk. When the file is downloaded, `response_body_len` gives a matching size value. When it is uploaded, `request_body_len` results in a value nearly 2x that: 155545102. (Looking at a set of form-data uploads from historical logs, the discrepancy was typically about 1.99 times larger, with cases being 1.6 times the size. The conn.log in this sample indicates that retransmissions occurred (TT in history), but expected values are given for `orig_bytes` and `resp_bytes` in the conn log.

Upload:

```
ts                1596409067.048839
uid               C73...zLc
id.orig_h         10.1.1.5
id.orig_p         33012
id.resp_h         x.x.219.95
id.resp_p         5000
trans_depth       1
method            POST
host              x.x.219.95
uri               /uploader
referrer          -
version           1.1
user_agent        curl/7.52.1
origin            -
request_body_len  155545102
response_body_len 26
status_code       200
status_msg        OK
info_code         100
info_msg          Continue
tags              (empty)
username          -
password          -
proxied           -
orig_fuids        FLgba23WA9BO46hE26
orig_filenames    archived-unencrypted.rar
orig_mime_types   application/x-rar
resp_fuids        F3MUOOTN0vopsroJc
resp_filenames    -
resp_mime_types   text/plain
```

Download:

```
ts                1596409110.625512
uid               C7Z...5dk
id.orig_h         10.1.1.5
id.orig_p         33014
id.resp_h         x.x.219.95
id.resp_p         5000
trans_depth       1
method            GET
host              x.x.219.95
uri               /downloads/archived-unencrypted.rar
referrer          -
version           1.0
user_agent        curl/7.52.1
origin            -
request_body_len  0
response_body_len 77772442
status_code       200
status_msg        OK
info_code         -
info_msg          -
tags              (empty)
username          -
password          -
proxied           -
orig_fuids        -
orig_filenames    -
orig_mime_types   -
resp_fuids        Fdi1Gt3Q0BEVFgTFo6
resp_filenames    -
resp_mime_types   application/x-rar
```

[conn.log.txt](https://github.com/zeek/zeek/files/5013265/conn.log.txt)
[http.log.txt](https://github.com/zeek/zeek/files/5013266/http.log.txt)

**Comment by jsiwek** [comment]
Thanks, looked like a bug to me and there's a patch in #1107 if you'd like to test -- I'm surprised this went unnoticed so long and wonder if I'm just missing an obvious reason for wanting the sub-entity lengths to be counted twice toward the total length that gets reported.
