### ISSUE TITLE
zeek:multiple entries with PF_RING-7.6.0

### ISSUE THREAD

**Issue by shuaidonga** [zeek/zeek#1101]
I'm currently using zeek-3.1.5 and pf_ring 7.6.0 (compiled on CentOS Linux release 7.8.2003). Run zeek every log is multiplied by 10. It is the same as my lb_procs (zeek node.cfg) number.

The following is pf_ring information when zeek is running

root@EM-GJJ8D53: /opt# more /proc/net/pf_ring/* |cat

*** /proc/net/pf_ring/dev: directory ***

::::::::::::::
/proc/net/pf_ring/info
::::::::::::::
PF_RING Version : 7.6.0 (unknown)
Total rings : 0

Standard (non ZC) Options
Ring slots : 4096
Slot version : 17
Capture TX : Yes [RX+TX]
IP Defragment : No
Socket Mode : Standard
Cluster Fragment Queue : 0
Cluster Fragment Discard : 0

*** /proc/net/pf_ring/stats: directory ***

The following is zeek's node.cfg configuration information
[logger]
type=logger
host=localhost

[manager]
type=manager
host=localhost

[proxy-1]
type=proxy
host=localhost

[worker-1]
type=worker
host=localhost
interface=com6
lb_method=pf_ring
lb_procs=10
pin_cpus=2,3,4,5,6,7,8,9,10,11

The following is zeek's zeekctl.cfg configuration information
```
## Global ZeekControl configuration file.

###############################################
# Mail Options
env_vars=PCAP_PF_RING_CLUSTER_ID=99
#env_vars=PCAP_PF_RING_CLUSTER_ID=99
PFRINGClusterID=99

# Recipient address for all emails sent out by Zeek and ZeekControl.
MailTo = root@localhost

# Mail connection summary reports each log rotation interval.  A value of 1
# means mail connection summaries, and a value of 0 means do not mail
# connection summaries.  This option has no effect if the trace-summary
# script is not available.
MailConnectionSummary = 1
```

**Comment by AspirePig** [comment]
how do you fix it.
