### ISSUE TITLE
typo in strftime

### ISSUE THREAD

**Issue by duffy-corelight** [zeek/zeek#1104]
On page https://docs.zeek.org/en/current/examples/logs/index.html at the line just prior to section
`Using UIDs` there is reference to external documentation but it calls it: man strfime

**Comment by rsmmr** [comment]
Want to try make a PR for this?

**Comment by duffy-corelight** [comment]
Yes, I'll do that. And in undertaking that, I realized zeek/zeek-docs has its own Issues tracker. Moving this to there.

**Comment by duffy-corelight** [comment]
It is closed here, and now open at https://github.com/zeek/zeek-docs/issues/31 and https://github.com/duffy-corelight/zeek-docs/pull/1
