### ISSUE TITLE
Track code coverage for testing in CI

### ISSUE THREAD

**Issue by rsmmr** [zeek/zeek#1116]

**Comment by grigorescu** [comment]
Code coverage for C++ code or for Zeek scripts?

**Comment by JustinAzoff** [comment]
This was for C++ using https://clang.llvm.org/docs/SourceBasedCodeCoverage.html

**Comment by timwoj** [comment]
I got started on this using https://coveralls.io to display the output and keep track between builds. We actually have most of the underlying stuff we need via the existing coverage scripts in `testing/coverage`. Once that's running, there's a ruby gem that will upload the data to coveralls at https://github.com/okkez/coveralls-lcov.

It still needs a bit of working with lcov to prune some of the extras files that we might not want, but a first build is there if you want to take a look at it: https://coveralls.io/github/zeek/zeek.
