### ISSUE TITLE
Backscatter/single RST behavior is wrong ("successful" connection inconsistencies)

### ISSUE THREAD

**Issue by grigorescu** [zeek/zeek#1119]
[single_rst.pcap](https://github.com/esnet-security/curated-pcaps/blob/master/tcp/control/single_rst.pcap) is an example PCAP that only has a single RST packet. We'd expect to see this in backscatter.

When [running that PCAP in Zeek v3.2.0](https://try.zeek.org/#/tryzeek/saved/444899), it sets `conn_state` to `RSTOS0`, which is documented as:

> Originator sent a SYN followed by a RST, we never saw a SYN-ACK from the responder.

This is incorrect, as there never was a SYN.

Additionally, this is considered a "successful connection," by the `connection_successful` and `successful_connection_remove` events, which matches the documentation, but seems logically incorrect:

> For TCP, this event is raised... if the originator host ever sends a packet that is not a SYN (i.e. the “success” status of a connection can be useful to help weed out SYN scans).

I believe that this bug led to Slack being blocked for a large national lab, due to backscatter that was mischaracterized.

**Comment by grigorescu** [comment]
I can take a stab at this, but I'd like to get some other thoughts on what the intended behavior should be.

- I don't view a single RST as a successful connection. The smallest change that makes sense to me would be "if the originator host sends a SYN, followed by a packet that is not a SYN." I could also see the argument of "successful" requiring a three-way handshake, for TCP.

- Technically, I think that `conn_state` should be `OTH`: "No SYN seen, just midstream traffic (a 'partial connection' that was not later closed)." I might also update that documentation to indicate that a partial connection is just one example.

**Comment by rsmmr** [comment]
(FWIW, the "connection_successful" goes away if I set `partial_connection_ok=F` (but no change on conn_state).)

Changing conn_state to `OTH` makes sense to me. 

For `connection_successful`, there indeed seems to be a bug. The commit message where it was introduced says:

>  "successful_connection_remove" excludes TCP connections that were never established (just SYN packets). [...] There's also a new event called ``connection_successful`` and a new ``connection`` record field named "successful" to help indicate this new property of connections.  

But running with this script:

```
event connection_established(c: connection) { print "connection_established", c$id; }
event connection_successful(c: connection) { print "connection_successful", c$id; }
event connection_state_remove(c: connection) { print "connection_state_remove", c$id; }
event successful_connection_remove(c: connection) { print "successful_connection_remove", c$id; }
```

reports (with `partial_connection_ok=T`):

```
connection_successful, [orig_h=10.0.0.10, orig_p=48777/tcp, resp_h=10.0.0.80, resp_p=80/tcp]
connection_state_remove, [orig_h=10.0.0.10, orig_p=48777/tcp, resp_h=10.0.0.80, resp_p=80/tcp]
successful_connection_remove, [orig_h=10.0.0.10, orig_p=48777/tcp, resp_h=10.0.0.80, resp_p=80/tcp]
```

So, there's `successful` but no `established`, which seems wrong indeed. Fixing this in whatever way leaves it consistent with `connection_established` seems the way to go.

**Comment by grigorescu** [comment]
Thanks, Robin. I'll work on this when I get back from vacation next week.

**Comment by initconf** [comment]
Thanks for handling this one Vlad! +1

**Comment by jsiwek** [comment]
> So, there's `successful` but no `established`, which seems wrong indeed. Fixing this in whatever way leaves it consistent with `connection_established` seems the way to go.

From the backstory in https://github.com/zeek/zeek/pull/677#issuecomment-551239957, it's intentionally not aligned with `connection_established` -- if it were, it would have been called `established_connection_remove` instead of "successful" (there was also generally no strong candidates for what to name it besides "successful").

I agree "successful" isn't intuitive in this instance, but there's no bug if our usage matches the documented behavior of "TCP originator has sent a non-SYN".  Renaming it is one option, if there's any ideas.  Otherwise, Vlad's proposal to change the meaning to "TCP originator has sent a SYN followed by non-SYN" may also be fine, though warrants checking whether usages of that event do rely on the documented behavior or hope that the test suite will point out discrepancies upon changing it.

(Also just noting the `RSTOS0` issue seems independent and dates back to even Bro 2.5).

**Comment by rsmmr** [comment]
Ah, thanks for the reminder on history here, @jsiwek, I had checked only the commit mesasge. I have say, though, that in hindsight the semantics do feel a bit surprising / hard to remember if we one doesn't have the specific use case in mind that it was originally added for. So I'm wondering if it's worth reconsidering aligning this with connection_established, even if it makes it less of a fit for that specific use case (but maybe still good enough?

**Comment by grigorescu** [comment]
The commit 31f60853c9f189a976ddd69c30149a5b503afa92 that introduced this says the following:

> The difference between the two is that "connection_state_remove" is raised for all events while "successful_connection_remove" excludes TCP connections that were never established (just SYN packets).

The documentation on `connection$successful` has this to say:

> This is always true for protocols other than TCP.  For TCP, this is true if the responder host ever sent a packet or if the originator host ever sends a packet that is not a SYN.

(As an side, the documentation is at odds about what happens when A sends a SYN, and B replies with a SYN. That is "just SYN packets," but the responder host sent a packet. Testing it, `successful_connection_remove` does fire in that case, though it's unclear to me if that's a bug.)

I propose that we stick with the original intent ("exclude TCP connections that were never established"), but rather than scope it to connections that only consist of SYNs, we bring it more in line with "established" in the context of TCP. For example:

> Non-TCP connections are considered "successful," as well as TCP connections where the responder sent a SYN-ACK, or the originator sent a SYN followed by an ACK.

I think this maintains the original intent, continues to work even if tapping/load-balancing is broken and only half of the connection is observed, and does a good job of not firing for backscatter traffic.

**Comment by JustinAzoff** [comment]
> scope it to connections that only consist of SYNs

I'd expect successful_connection_remove to also not be raised for connections where history=Sr.

**Comment by jsiwek** [comment]
> The commit [31f6085](https://github.com/zeek/zeek/commit/31f60853c9f189a976ddd69c30149a5b503afa92) that introduced this says the following:
> 
> > The difference between the two is that "connection_state_remove" is raised for all events while "successful_connection_remove" excludes TCP connections that were never established (just SYN packets).
> 
> The documentation on `connection$successful` has this to say:
> 
> > This is always true for protocols other than TCP.  For TCP, this is true if the responder host ever sent a packet or if the originator host ever sends a packet that is not a SYN.
> 
> (As an aside, the documentation is at odds about what happens when A sends a SYN, and B replies with a SYN. That is "just SYN packets," but the responder host sent a packet. Testing it, `successful_connection_remove` does fire in that case, though it's unclear to me if that's a bug.)

The commit message could have been more precise, but the two locations where the behavior is described in the documentation and one location in https://github.com/zeek/zeek/pull/677#issuecomment-551239957 say "originator sent a non-SYN || responder sent anything" which sounds consistent with reality and the result of your test.

> I propose that we stick with the original intent ("exclude TCP connections that were never established"), but rather than scope it to connections that only consist of SYNs, we bring it more in line with "established" in the context of TCP. For example:
> 
> > Non-TCP connections are considered "successful," as well as TCP connections where the responder sent a SYN-ACK, or the originator sent a SYN followed by an ACK.
> 
> I think this maintains the original intent, continues to work even if tapping/load-balancing is broken and only half of the connection is observed, and does a good job of not firing for backscatter traffic.

My view of "original intent" is "provide some event that helps decrease load that results from SYN scans".  If the meaning of "successful" is narrowed to align more closely with "TCP established" and accomplishes the same intent, that does sound better.  However, I have doubt about that result being found since narrowing the usefulness of "successful" (like if it no longer triggers for "partial TCP connections" where the initial handshake is dropped/missed) could mean more reliance on `connection_state_remove` to cover those cases and that's exactly where the undesired performance overhead came from originally.

Not that the exploration of potential improvements is entirely discouraged -- just saying the original motivation was performance-oriented, so the acceptability of any changes depends on the results of a performance comparison.

**Comment by grigorescu** [comment]
Thanks, Jon. I made the smallest possible change in 76772b847bf4d3a3fc80c89bbe4644bd10c84dc3 to enable testing. My results show that it's comparable to the existing behavior, if not marginally faster. I ran it on the external test suite, and on a [TCP SYN scan with masscan of ports 0-1000](https://github.com/esnet-security/curated-pcaps/tree/master/attacks/scanners/masscan).

**Comment by grigorescu** [comment]
Ok, I made the rest of the changes in topic/vlad/gh-1119 (and in zeek-docs:topic/vlad/gh-1119).

All the btests pass. SMTP and FTP required some updates. There's an SMTP btest where we only saw half the traffic. In addition to `successful_connection_remove`, I handled `connection_half_finished`. I think performance-wise this is ok, since I believe that `connection_half_finished` would always fire with the previous `successful_connection_remove` behavior.

FTP was a bit more involved, where instead of `successful_connection_remove`, I handle `connection_finished`, `connection_pending`, `connection_reset`, and `connection_half_finished`. Again, I think that all these are actually a subset of `successful_connection_remove`, and because it ignores UDP and ICMP, these events should fire less often.

**Comment by jsiwek** [comment]
> Ok, I made the rest of the changes in topic/vlad/[gh-1119](https://github.com/zeek/zeek/issues/1119) (and in zeek-docs:topic/vlad/[gh-1119](https://github.com/zeek/zeek/issues/1119)).
> 
> All the btests pass

I still see failures in `external/zeek-testing` and `external/zeek-testing-private` with that branch.

> SMTP and FTP required some updates

It's not yet clear if those changes are chasing down particular baseline differences or if there's a general combination of events that could/should be used everywhere. I.e. for what reason can SMTP get away with only using `connection_half_finished`, but FTP needs more?  For what reason do other protocol-specific scripts besides FTP/SMTP not need to care about handling a similar combination of events?  When someone goes to write a new protocol-specific script, how much more complex is their decision-tree for choosing these "finalizing events" ?

Can we go back to clearly defining what the problem with `successful_connection` is?  From what I remember/see, the behavior is deliberately chosen for use in a generalized way, improves performance for a particular scenario, and works as documented/intended.  If the problem is only that the name is confusing/misleading, the direct solution is to change the name rather than the behavior.  Like `non_syn_probe_connection` or `orig_sent_non_syn_or_resp_sent_anything_connection`.

**Comment by grigorescu** [comment]
> Can we go back to clearly defining what the problem with successful_connection is? From what I remember/see, the behavior is deliberately chosen for use in a generalized way, improves performance for a particular scenario, and works as documented/intended. If the problem is only that the name is confusing/misleading, the direct solution is to change the name rather than the behavior. Like non_syn_probe_connection or orig_sent_non_syn_or_resp_sent_anything_connection.

Yeah, I think that's a good idea.

The event does not work as documented. What the documentation says is:

> For TCP, this event is raised if the responder host ever sends a packet or if the originator host ever sends a packet that is not a SYN (i.e. the “success” status of a connection can be useful to help weed out SYN scans).

I tested this with PCAPs that just had a single packet. In this case, we should see this event for anything that's not a SYN. The behavior is very inconsistent. Here are my results as to whether `successful_connection_remove` fires or not. I hope this ad-hoc table makes sense. I'm essentially adding the flags on the left to the flags across the top. I only looked at these 4 flags because I don't believe URG, PSH, etc. have a big role to play here, but I can re-run the tests with those too.

| Flags | (None)  | A | F | R | S |
|-------|---|---|---|---|---|
| (None)      | Y | Y | Y | Y | N |
| AF    | Y | - | - | Y | Y |
| AR    | Y | - | Y | - | Y |
| AS    | N | - | Y | Y | - |
| FR    | Y | Y | - | - | Y |
| FS    | Y | Y | - | Y | - |
| RS    | Y | Y | Y | - | - |
| AFR   | - | - | - | - | Y |
| AFS   | - | - | - | Y | - |
| FRS   | - | Y | - | - | - |

The documentation is a bit unclear about what a packet that is a SYN means. Does a SYN-ACK count, or not? In any case, a SYN-ACK packet will cause this even not to fire, while a SYN-ACK-FIN packet will, along with other inconsistencies you can see above.

Additionally, I'm not sure that this does work as intended. The intent was to provide a split between an event that you can handle if you're writing a script to detect SYN scans, versus an event that you can handle to perform any cleanup/logging when a connection ends. However, the "successful" characterization doesn't accurately detect SYN scans. It works in the one very specific use-case that Justin initially discussed, which is a PCAP with only SYN packets. However, real traffic will have the victims sending `RST` packets in response. In this case, the connection is marked as "successful."

I agree that this improves performance for a particular scenario, but I think that that scenario is too artificial to be of much use, and the confusion that it leads to in developers doesn't outweigh the benefits. Additionally, I think we could actually make the performance better. By being more restrictive about what "successful" means, assuming that most scripts handle that event and not `connection_state_remove`, we actually improve the performance even further.

I'll circle back with specific thoughts about FTP and SMTP, but wanted to get these thoughts down while I had some time.

**Comment by grigorescu** [comment]
Sorry, one more thought on this. I circled back to my PCAP results, and while it's true that PSH and URG don't really affect things, they do confuse matters more.

Per the above, the event is not raised for a `SYN` or `SYN-ACK` (I believe because just a single `SYN-ACK` will reverse the roles). As I mentioned, a `SYN-ACK-FIN` will cause the event to not be generated. However, a `SYN-ACK-URG` or `SYN-ACK-PSH` does generate the event. So we're left in a state where the addition of `FIN` and `RST` does alter the behavior of the event, but `URG` and `PSH` do not.

**Comment by grigorescu** [comment]
> I still see failures in external/zeek-testing and external/zeek-testing-private with that branch.

Sorry about that, you're right. I'll take care of those if this proceeds.

> It's not yet clear if those changes are chasing down particular baseline differences or if there's a general combination of events that could/should be used everywhere. I.e. for what reason can SMTP get away with only using connection_half_finished, but FTP needs more? For what reason do other protocol-specific scripts besides FTP/SMTP not need to care about handling a similar combination of events?

I'm not sure that this behavior is correct yet, which is why I'm hoping for a discussion in here versus just making a pull-request.

FTP is an odd-ball, due to the command channel. The logic is there because the state of the command channel connection is separate from the state of the data channel connections. So, we could end up in a state where the command channel gets torn down in a strange way, but we have pending commands that we want to log. In "normal" protocols, if the connection got torn down because the responder sent a RST instead of a response, we don't need to handle that because there was no response. In FTP, if the control channel got torn down with a RST, the commands may or may not have actually occurred.

Part of the issue here is that Zeek behavior has never been particularly well defined in terms of missing traffic. The SMTP analyzer has specific logic to deal with gaps, whereas most other analyzers don't. Do we expect analyzers to work with only one half of the connection? SMTP is the only analyzer that tests this, AFAICT.

> When someone goes to write a new protocol-specific script, how much more complex is their decision-tree for choosing these "finalizing events" ?

Yeah, I share your concerns there. I don't want to scope creep this too much, but I'm wondering if there are some events missing. If we care about performance, the more specific we can make the events, the better. At the same time, it needs to be very clear to the developer which event(s) they need to handle.

At the far end of the spectrum, we could introduce a standard for having a`$protocol_connection_done` event, e.g. `smtp_connection_done`, `sip_connection_done`. When I write scripts, I don't really care how the TCP session got torn down. What I really care about is "was any data transferred?" Having these events fire whenever an analyzer is done with a connection that saw data flowing would achieve that. This would be the best option for performance, as those events would fire only when strictly needed. Looking over the existing uses of `successful_connection_remove`, I think using the protocol-specific events would cover most use-cases (all the `protocol/*` scripts, excluding `conn`).

A less extreme option might be `tcp_connection_done` and `udp_connection_done`. Perhaps there needs to be some additional verbiage here to indicate that data was transferred.

**Comment by jsiwek** [comment]
> The documentation is a bit unclear about what a packet that is a SYN means. Does a SYN-ACK count, or not? In any case, a SYN-ACK packet will cause this even not to fire, while a SYN-ACK-FIN packet will, along with other inconsistencies you can see above.

Thanks, charting it out is helpful.  If we're going by what's documented (just for now to understand current situation), I didn't follow what other inconsistencies you see besides SYN-ACK behavior?  For SYN-ACK, the motivation was likely for `connection_successful` to be mutually exclusive with `connection_attempt` (the later is defined as being generated for "unsuccessful" connection attempts, so seems strange if they could overlap).  I.e. rectifying this inconsistency may just be a documentation change, but also may be moot if we go along a behavior-changing path that you're currently exploring.

> However, real traffic will have the victims sending `RST` packets in response. In this case, the connection is marked as "successful."

That's definitely an issue to warrant change in behavior of `connection_successful` -- not sure exactly what that behavior should be yet though.  A direct approach may be preventing `RST` from mattering one way or the other for purpose of this classification.

> When I write scripts, I don't really care how the TCP session got torn down. What I really care about is "was any data transferred?"

This orientation also makes sense to me, so a separate path might be renaming the event to something like `connection_with_data` or `connection_productive` and for the TCP-specific implementation of that, move away from looking at control-bits/state-machine combinations and just look to see if any data ever got sent.

Part of the friction with trying to align `connection_successful` with the concept of "established" is that Zeek's TCP "established" state requires witnessing the handshake -- if that part is missed/dropped, but further data is exchanged, the connection is still not "established", it's "partial".  Meanwhile, it's always possible for some higher-level analyzer to be made that works regardless of whether it's only "partial" -- we actually may not have any currently, but these seem like gory complexities worth hiding from users.

> At the far end of the spectrum, we could introduce a standard for having a`$protocol_connection_done` event, e.g. `smtp_connection_done`, `sip_connection_done`. ... Having these events fire whenever an analyzer is done with a connection that saw data flowing would achieve that. This would be the best option for performance, as those events would fire only when strictly needed.

This line of thinking seems worth exploring more, especially if we want to address the root of the performance problems in a generalized way.  If the problem we have is that calling an event can be expensive, but the only way we can currently do some things is to write an event handler (e.g. `connection_state_remove`) and then filter out uninteresting calls of that event after the fact inside handlers, then that structuring itself is the fundamental source of inefficiencies.

An alternative structure could be relying more on explicit function callback registration.  Roughly this idea:

```zeek
function http_cleanup(c: connection)
    { Log::write(HTTP::LOG, c$http); }

event http_request(c: connection, ...)
    { register_conn_cleanup_callback(c, http_cleanup); }

# This handler would come w/ standard Zeek, not written per-user.
event connection_state_remove(c: connection)
    {
    for ( cb in c$cleanup_callbacks )
        cb(c);
    }
```

Maybe priorities/ordering between callbacks are also still desired, but that's possible to add.

**Comment by grigorescu** [comment]
I'm in agreement. Let me try to summarize this, and I'll answer the more specific questions below.

I think I now see three issues kind of intertwined here (in my order of priority):

1. SYN-RST is marked as successful
2. Zeek behavior on only seeing half of the connection is poorly defined. Some analyzers work, but those that do don't have btests for this case. This and issue (1) causes the original problem here, namely that a single RST gets marked as "successful." It'd be nice to add some additional btests for the analyzers we expect to work in this situation.
3. There's room for additional performance improvements in more fine-grained events that fire when a connection is done (for some definition of done).

Perhaps (2) and (3) need to be split off into separate issues.

>  If we're going by what's documented (just for now to understand current situation), I didn't follow what other inconsistencies you see besides SYN-ACK behavior?

Sorry, I ended up splitting this over two separate comments. Part of the confusion is that you have flags which are significant (i.e. their value will affect whether or not the connection is successful), and other flags which are not significant. Here's a better attempt:

| Flags |   | F | P | R | U |
|-------|---|---|---|---|---|
| S     | N | Y | N | Y | N |
| SA    | N | Y | N | Y | N |

> If the problem we have is that calling an event can be expensive, but the only way we can currently do some things is to write an event handler (e.g. connection_state_remove) and then filter out uninteresting calls of that event after the fact inside handlers, then that structuring itself is the fundamental source of inefficiencies.

I'm still trying to figure out where the performance penalty comes from. I think that raising an event is relatively cheap, I think the issue is simply in building the connection record.

**Comment by rsmmr** [comment]
I like the idea of registering callbacks, that seems like a nice general mechanism to really fine-tune when exactly you want your code to run. That way it'll be tied directly to the event/logic that created the state originally, and not left up to a generic notion of "all connections that have X". Such a callback could also be used for other stuff than state management: everything that one ones want to run at the end of specific connections could be triggered that way (which is why I'd name it something like `register_connection_termination_callback`, or some shorter version of that). I'm not quite sure about performance, but it should be too bad, given that all callbacks will take the same arguments, so it's not so different from triggering an event.

**Comment by grigorescu** [comment]
Just for the sake of completeness, I did a test of one packet from the originator, one packet from the responder. The only connections which are NOT successful are: 

- orig sends SYN, resp sends a packet with no flags
- orig sends SYN, resp sends ACK

As mentioned before, the URG and PSH flags are inconsequential to this, so stuff like orig sends SYN-URG, resp sends ACK-PSH will also be considered unsuccessful.

**Comment by jsiwek** [comment]
> I'm still trying to figure out where the performance penalty comes from. I think that raising an event is relatively cheap, I think the issue is simply in building the connection record.

Yeah, would guess building `connection` records is an expensive part, but not sure how avoidable/optimizable that part of it is (w/o an internal state-management overhaul and/or backwards-incompatible decisions): IIRC anyone using the `new_connection` event will cause a `connection` object to get built on observing the first SYN (tunnel framework scripts currently have such an event handler).  We also still have an "inevitable" `connection_state_remove` that will build a `connection` as part of the base `conn.log` functionality, even if it's a connection consisting of a single SYN packet.

Here's a progression of benchmarks to approximate worst-case behavior of all cleanup events being no-ops:

```zeek
# cat a.zeek && gtime -f "# %esecs" zeek -b ./a.zeek
event myev() {}
local i = 50000000;
while ( i != 0 ) { event myev(); --i; }
# 26.67secs

# cat a.zeek && gtime -f "# %esecs" zeek -b ./a.zeek
event myev() {}
event myev() {}
event myev() {}
event myev() {}
event myev() {}
event myev() {}
event myev() {}
event myev() {}
event myev() {}
event myev() {}
event myev() {}
event myev() {}
event myev() {}
event myev() {}
event myev() {}
event myev() {}
event myev() {}
event myev() {}
event myev() {}
event myev() {}
local i = 50000000;
while ( i != 0 ) { event myev(); --i; }
# 34.48secs

# cat a.zeek && gtime -f "# %esecs" zeek -b ./a.zeek
event myev() { if ( T ) {} }
event myev() { if ( T ) {} }
event myev() { if ( T ) {} }
event myev() { if ( T ) {} }
event myev() { if ( T ) {} }
event myev() { if ( T ) {} }
event myev() { if ( T ) {} }
event myev() { if ( T ) {} }
event myev() { if ( T ) {} }
event myev() { if ( T ) {} }
event myev() { if ( T ) {} }
event myev() { if ( T ) {} }
event myev() { if ( T ) {} }
event myev() { if ( T ) {} }
event myev() { if ( T ) {} }
event myev() { if ( T ) {} }
event myev() { if ( T ) {} }
event myev() { if ( T ) {} }
event myev() { if ( T ) {} }
event myev() { if ( T ) {} }
local i = 50000000;
while ( i != 0 ) { event myev(); --i; }
# 53.34secs

# cat a.zeek && gtime -f "# %esecs" zeek -b ./a.zeek
type mycb: function();
global callbacks: vector of mycb = vector();
event myev() { for ( i in callbacks ) callbacks[i](); }
local i = 50000000;
while ( i != 0 ) { event myev(); --i; }
# 30.59secs
```

I chose 20 event handlers because that's roughly how many protocols are currently supported by default, but expect that to grow over time as new protocols find support.  The inefficient scaling property is clear even with the most trivial conditional branch in each handler.  Also shows the promise of the connection-termination-callback approach -- if that turns out to better in practice in every way, don't think the "successful connection" categorization is worth any further effort to fix/improve and can be removed entirely.

**Comment by grigorescu** [comment]
Interesting, thanks for that data, Jon.

I have a slightly alternate proposal. What about a new attribute, `&on_destroy`? My thought is something that's analogous to `&on_change`, but that gets called as the Val is about to be destroyed. So, for the conn example:

```
redef record connection += {
	conn: Info &optional &on_destroy=finish_conn;
};

function finish_conn(c: Info) {
        Log::write(Conn::LOG, c);
}
```

`&on_change` is limited to being a function. I *think* that that also makes sense here, but perhaps this should be an event. Right now, we have many patterns that handle the "destructor" events at different priorities, but I think that's a limitation of the current state rather than a desired feature. That is, scripts have to handle the base events, and interleave their logic because they don't have a good way to handle when "their" objects are finished.

Performance-wise, I think this would be very efficient. Because this is an attribute of the Val itself, whatever handles calling this function should already have an instance of the Val.

I'm not crazy about the name. `&on_change` gets applied to the container, but I envision that this could be applied to any  fundamental type as well as a container element. We also have some potential confusion with `&delete_func`.

**Comment by jsiwek** [comment]
> What about a new attribute, `&on_destroy`? My thought is something that's analogous to `&on_change`, but that gets called as the Val is about to be destroyed.

I think there's an expectation that scripts explicitly express a
stable/reliable ordering of event-handling/actions (e.g. when a log entry is
written) within the total event-queue sequencing.  The stability makes it
easier to reason about and even extend with custom logic.

`&on_destroy` depends on the implicit lifetime of a `Val` object, so the
overall ordering of actions is less stable/certain: any new code has the chance
to unintentionally alter the sequence if it ever stores an additional `Val`
reference for whatever reason (e.g. postponed analysis/correlation), or also if
they decide to prematurely re-assign a new `Val` and happen to be
releasing the last reference to the original `Val`.  It may become hard to
reason about whether any arbitrary combination of scripts produce these
undesired interactions since intentions are not so explicitly expressed.

**Comment by JustinAzoff** [comment]
Really like this register_connection_termination_callback idea.  In addition to decreasing the function calls for syn packets by ~20 or so like the successful connection event did, it will also drop the function calls for all other protocols by ~19.

I think most protocol analyzer scripts already have a function like set_state or set_session that would be perfect for registering the callback.

**Comment by rsmmr** [comment]
Agree on the down-sides of &on_destroy, the ill-defined life-times would make that difficult to use/understand.

**Comment by jsiwek** [comment]
@grigorescu do you plan to work on this more?  I can help look into it since the callback idea was mine and don't want to waste your time if it ends up being a dead-end for some reason, but also want to avoid duplicate effort if you already started work.

**Comment by grigorescu** [comment]
@jsiwek I don't think I have the cycles to take this on in the next month or so. If it's still open then, I'm happy to take it on, but realistically, I have some higher-priority things until then.

**Comment by grigorescu** [comment]
@jsiwek I don't think I have the cycles to take this on in the next month or so. If it's still open then, I'm happy to take it on, but realistically, I have some higher-priority things until then.

**Comment by jsiwek** [comment]
I split "single RST produces `conn_state` of `RSTOS0`" as independent issue #1164.
