### ISSUE TITLE
Division by zero not allowed for type "double"

### ISSUE THREAD

**Issue by vpax** [zeek/zeek#1121]
Using `1.0/0.0` in an expression generates a run-time error complaining about division-by-zero.  While that makes sense for integral types, `double` is capable of representing the result using IEEE `Inf`.  (The same goes for use of `NaN` for things like `0.0/0.0`.)  I think it makes sense to allow such expressions.

**Comment by 0xxon** [comment]
I was curious and looked what the C++ standard has to say about division by 0 for float types - and it just says

"If the second operand of / or % is zero the behavior is undefined." (C++17, 8.6) (for all types, including float).

So - we would have to special-case this ourselves. That being said - I am not opposed.

**Comment by vpax** [comment]
Huh.  Well, I'm not picky about this one, just thought it was a bit surprising.  (This is for test suite stuff I'm working on where the current `btest` expects `Inf` and `NaN`.  I got those working, but am unable to reproduce `-0.0` correctly ... which strikes me as even more esoteric, so I'm not all shook up over that one.)  I'm fine then with closing this if others see fit.

**Comment by rsmmr** [comment]
Runtime error sounds ok to me.
