### ISSUE TITLE
error: no viable conversion from 'const caf::actor' to 'caf::node_id'

### ISSUE THREAD

**Issue by Schamschula** [zeek/zeek#1123]
While building zeek 3.2.0 on macOS 10.15.6 under MacPorts, with caf 0.17.6 installed, I get the following error:

> :info:build /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_net_zeek/zeek/work/zeek-3.2.0/auxil/broker/include/broker/store_event.hh:76:24: error: no matching function for call to 'to'
> :info:build       if (auto value = to<caf::node_id>((*xs_)[5])) {
> :info:build                        ^~~~~~~~~~~~~~~~

Note: this error does not occur under macOS Mojave. Successive versions of llvm/clang have gotten more strict.

Full log attached

[zeek-main.log](https://github.com/zeek/zeek/files/5076378/zeek-main.log)

**Comment by 0xxon** [comment]
The log file that you provided says:

```
:info:configure -- Found CAF: 0.17.5  found components: core io openssl 
```

Assuming that is true, that is the wrong version of CAF - we need exactly 0.17.6 for 3.2.0, as you said. Can you check that you actually really do have 0.17.6 installed?

I also think we should consider just making the configure version checks more strict - and just error out if the version is not what we expect...

**Comment by 0xxon** [comment]
Also note - since Zeek is generally quite tightly bound to CAF versions - if possible, it might be more prudent to just use the bundled version.

**Comment by Schamschula** [comment]
Yes, I do have caf 0.17.6 installed:

> port installed caf
> The following ports are currently installed:
>   caf @0.17.6_1 (active)

cmake fails to finish configuring when I hide caf from it.

**Comment by Schamschula** [comment]
Update: I forgot to disable `-DCAF_ROOT_DIR=${prefix}` when building the bundled copy of caf.

After that the build succeeded.

**Comment by 0xxon** [comment]
Great. I will close this, assuming that this fixes your problem :)

**Comment by Schamschula** [comment]
OK, I think Zeek is the only MacPorts port currently depending on caf. I'll update the Portfile to use the bundled version of caf.

BTW:

Starting with version 3.1.5 the Catalina build also requires the following patch (path updated for 3.2.0):


[patch-auxil-broker-src-detail-sqlite_backend.cc.txt](https://github.com/zeek/zeek/files/5076716/patch-auxil-broker-src-detail-sqlite_backend.cc.txt)

**Comment by 0xxon** [comment]
Why is that one necessary? It should build fine as it is on catalina - I build it on it nearly every day.

**Comment by Schamschula** [comment]
Looks like it's no longer need. Thanks!
