### ISSUE TITLE
GRE Protocol Failure for Aruba Tunnel Types

### ISSUE THREAD

**Issue by forewarned** [zeek/zeek#1125]
When traffic tunneled over Generic Routing Encapsulation (GRE) using an Aruba WLAN protocol type (0x8200) is consumed by Zeek 3.0.7, it generates a weird log with the name "unknown_gre_protocol_in_tunnel" and does not analyze the encapsulated traffic. Wireshark does dissect the packets appropriately, and it appears they have the various GRE types listed at https://github.com/wireshark/wireshark/blob/ef76d65fc61d01c2ce5184140f4b1bba0019078b/epan/dissectors/packet-gre.h
and https://github.com/wireshark/wireshark/blob/c914843195a0afbb1f71111deb74b0f58232eb1f/epan/dissectors/packet-gre.c.

Aruba GRE tunnels are quite popular in enterprise environments with minor differences with other GRE types, making these tunnel types strong candidates to begin supporting.

I have attached a pcap of some of this traffic for reference and testing purposes.
[gre_aruba_port_80.pcap.gz](https://github.com/zeek/zeek/files/5085687/gre_aruba_port_80.pcap.gz)

**Comment by grigorescu** [comment]
I ran into this in 2013 and was unable to find a good solution.

It's not a mere matter of adding the GRE type. Within the GRE tunnel, you have 802.11 QoS, followed by LLC/SNAP, and then you finally get to IPv4. Zeek doesn't support any of those low-level protocols. So even if you decapsulate the GRE, Zeek won't know what to do with the contents.

**Comment by grigorescu** [comment]
I ran into this in 2013 and was unable to find a good solution.

It's not a mere matter of adding the GRE type. Within the GRE tunnel, you have 802.11 QoS, followed by LLC/SNAP, and then you finally get to IPv4. Zeek doesn't support any of those low-level protocols. So even if you decapsulate the GRE, Zeek won't know what to do with the contents.

**Comment by grigorescu** [comment]
I'm attaching my old code for this. Note that in the meantime, GRE support was added a different way, so this patch is nowhere close to applying.

[aruba_gre.patch.txt](https://github.com/zeek/zeek/files/5092351/aruba_gre.patch.txt)

**Comment by JustinAzoff** [comment]
The new features in https://github.com/zeek/zeek/pull/1046 may change things as well.

**Comment by timwoj** [comment]
Once IP is moved over to the packet analysis architecture (#1131, once I have a proposal written up for it), adding more support for encapsulation protocols like GRE and extending it is just a matter of adding another packet analysis plugin that handles it.

**Comment by timwoj** [comment]
@forewarned I'm finally coming back around to this since the tunnel rework was wrapped up. Is it ok if I include that pcap you attached in the trace library that we provide with zeek?

**Comment by forewarned** [comment]
Yes, feel free to include it. Thanks!
