### ISSUE TITLE
Support /s modifier for patterns

### ISSUE THREAD

**Issue by rvictory** [zeek/zeek#1129]
Today, the 'dot' in patterns doesn't match newlines. Other languages have a "Dot all" modifier which means that dots match newlines. Basically:

`/.*/s`

would mean match anything including newlines. See Python's documentation for more information: https://docs.python.org/3/library/re.html#re.S

**Comment by vpax** [comment]
FYI, this appears to be a very easy change since the notion is already supported for signature rules.

**Comment by rsmmr** [comment]
We do have the notion, but iirc there's a catch: this won't easily work for concatenations (`/abc/ | /def/`) because an `/s` flag would need to apply to the joint regex. We could do an attribute, like `/abc/ &multiline`.

**Comment by vpax** [comment]
Seems good to me!

**Comment by rvictory** [comment]
I’d support this as well.

-Ryan

**Comment by timwoj** [comment]
@vpax I've been looking at this one for a bit, and I noticed you added `RE_Matcher::IsCaseInsensitive()` for use in script optimization. Should that variable remain true if one does the following:

1. Creates a matcher with a pattern
2. Sets case sensitive (so the mode is added to the pattern)
3. Calls `AddPat()` with a second pattern

In that case, only part of the pattern is case insensitive not the whole thing.

There's actually a lot weird with this code. For example, I'm not entirely sure what it would generate (and whether it would be valid regex) if you were to swap 2 and 3 above.

**Comment by vpax** [comment]
> Should that variable remain true if one does the following

The point of that variable is to provide enough information to correctly re-construct the pattern from scratch.  What you're framing indicates that that might not be expressible using a single variable :-(.  If not then we need to rethink the interface ...

**Comment by timwoj** [comment]
> The point of that variable is to provide enough information to correctly re-construct the pattern from scratch.

I'm not sure you could reconstruct it from scratch anyways as adding a pattern doesn't save the original text of the pattern anywhere, nor the parts individually. I added some bits to `Specific_RE_Matcher` that support additional modes and flagging whether the matcher supports them while it's building, but that information is lost as soon as Compile() runs or new patterns are added to the matcher.

**Comment by vpax** [comment]
> I'm not sure you could reconstruct it from scratch anyways as adding a pattern doesn't save the original text of the pattern anywhere, nor the parts individually

But it saves the collection, `|`'d together ... which by definition has to be enough to recover the the pattern since that's what eventually gets compiled.  Unless I'm missing something.  (If so, it might be more effective for you & me to discuss directly, rather than via dialog here.)
