### ISSUE TITLE
Supervisor Framework doesn't respect umask for directories

### ISSUE THREAD

**Issue by grigorescu** [zeek/zeek#1145]
I set the umask for the supervisor process, and expect the directories created (e.g. /usr/local/zeek/spool/bro-dev-logger) to be created with that umask. However, `ensure_dir` hardcodes the umask to 700: https://github.com/zeek/zeek/blob/8012914c16c1903799c0f00d153ab863cc27f708/src/util.cc#L318-L320

Easy fix, but does anyone have concerns about removing the default of 700?

**Comment by rsmmr** [comment]
Sounds fine to me. It could change perms for log dirs being created, but that seems fine, people can their own umasks if that's important.

**Comment by grigorescu** [comment]
Yeah, in poking around a bit, the only other use-case is in the mkdir BIF, and that respects the umask.

**Comment by grigorescu** [comment]
I missed another umask issue for the stats log:

https://github.com/zeek/zeek/blob/8012914c16c1903799c0f00d153ab863cc27f708/src/util.cc#L1007

I pushed this to topic/vlad/gh-1145 as well, which is ready. I can open a PR if needed, but might be overkill.

**Comment by jsiwek** [comment]
> I pushed this to topic/vlad/[gh-1145](https://github.com/zeek/zeek/issues/1145) as well, which is ready. I can open a PR if needed, but might be overkill.

Thanks, merged.  Generally don't mind opening new/extra PRs for sake of organization and following the same process, plus helps verify that CI doesn't report anything surprising.
