### ISSUE TITLE
Automate generation of zeek-docs

### ISSUE THREAD

**Issue by jsiwek** [zeek/zeek#1149]
The manual generation of `zeek-docs` is a minor friction to the merge process and the script that does the generation has always been successful/stable AFAIK, so here's a proposal to automate it:

- Use a daily GitHub Action to generate docs and commit changes to the
  `zeek-docs` repo.

- Also use a daily GitHub Action that updates the `zeek-docs` submodule
  within the `zeek` repo when necessary.  Generally think relying on periodic
  crons rather than auto-triggering doc generation on commit is favorable: the
  later has more potential for an out of control feedback loop to make many
  junk commits before we have a chance to notice and stop it.  E.g. if docs
  ever generate unstable output, then a new commit triggers change in docs,
  those get committed, then that commit triggers another change in docs, and so
  on.  An alternative could be to lazily update the submodule via an
  `update-change` hook whenever somone runs that next.

- Remove the `coverage/sphinx-zeekygen-docs.sh` btest.

- Add explicit step to release process to ensure docs are up to date since a
  btest will no longer catch staleness. e.g. "run `update-zeekygen-docs.sh`"

**Comment by 0xxon** [comment]
I am a big fan. Especially if we can get it to complain when some error occurs - I wouldn't want to catch that only in the release build :)

**Comment by rsmmr** [comment]
Same here, like it!

Daily sounds good. Ideally we'd have a single script that does it all both from inside an action and manually, so that it's easy to trigger on demand as well and also to debug any problems.

**Comment by jsiwek** [comment]
Due to various team/branch-protection/access-token bits, it was tricky to first get this pre-tested in a branch (or separate dummy repo), so I worked through it directly in `master`.

Anyone interested in reviewing can look at the final version of the Action at https://github.com/zeek/zeek/blob/master/.github/workflows/generate-docs.yml.  The `zeek-bot` account is now allowed to push master branches of `zeek` and `zeek-docs` repos.

**Comment by rsmmr** [comment]
LGTM!
