### ISSUE TITLE
Full precision of nanosecond timestamps is not preserved

### ISSUE THREAD

**Issue by philrz** [zeek/zeek#1163]
Consider the attached small pcapng.

[pings.pcapng.zip](https://github.com/zeek/zeek/files/5209462/pings.pcapng.zip)

When viewed in Wireshark, the timestamps have granularity out to 9 digits after the decimal place.

![image](https://user-images.githubusercontent.com/5934157/92934553-79438e00-f3fc-11ea-91c5-4b2ee9e447d0.png)

However, when run through Zeek, only 6 digits are preserved.

```
$ /usr/local/zeek-3.2.1/bin/zeek -C -r pings.pcapng local

$ cat conn.log | /usr/local/zeek-3.2.1/bin/zeek-cut ts
1599787799.006763
1599787801.385053
1599787804.008506
1599787806.320433
```

I [asked about this on Slack](https://zeekorg.slack.com/archives/CSZBXF6TH/p1599784243098800) and @grigorescu confirmed by pointing to https://github.com/zeek/zeek/blob/master/src/threading/Formatter.cc#L113 that 6 is indeed the current limit. Vern also joined the thread:

> **Vern Paxson**: Historically, libpcap provided at best usec precision, hence the wiring-in of 6 digits.  However, this has been improved, so Zeek should allow more precision.  OTOH, it’s a pity to bloat logs (slightly!) with digits that are almost never of any interest

> **Phil Rzewski**: Perhaps room for a configurable option that's off by default, so folks only pay for the bloat in the logs if it really matters to them? Like @timwoj  mentioned, I had a heck of a time even finding pcapng samples online that went out to that level of precision, and I had to invoke non-default tcpdump options on a system with a particular NIC to even generate my own. But I happened to be working with a user that did have legit pcapng files that went out that far, which was how I bumped into this.

> **Vern Paxson**: Yeah, I like that notion.

As noted, I had a difficult time finding sample data online, so the synthetic sample linked above was taken on an AWS Linux host via `tcpdump -i ens4 -w pings.pcap --time-stamp-precision=nano net 192.168.1.0/24` while I ran pings in another window.

**Comment by timwoj** [comment]
Do we want to specify the intervals like tcpdump does (`micro`/`nano`) or can this just be a numeric value for the number of decimal digits?

**Comment by timwoj** [comment]
See the above PR for more talk about the ramifications of this work.
