### ISSUE TITLE
zeekctl deploy fails with  [Errno 66] Directory not empty, if a package has a directory inside it 

### ISSUE THREAD

**Issue by LBLSecurity** [zeek/zeek#1172]
smtp-url-analysis package has scripts/feeds directory which contains raw input-files as initial seed for malicious indicators. 

When I try zeekctl deploy it fails as following: 

$ zeekctl deploy
checking configurations ...
installing ...
removing old policies in /usr/local/zeek/spool/installed-scripts-do-not-touch/site ...
Error: failed to remove directory /usr/local/zeek/spool/installed-scripts-do-not-touch/site: [Errno 66] Directory not empty: '/usr/local/zeek/spool/installed-scripts-do-not-touch/site/smtp-url-analysis/scripts/feeds'

let me know if you need more information and/or help replicating this. 

Thanks
Aashish

**Comment by JustinAzoff** [comment]
Directories are not normally a problem.. the code in question is

```
                self.ui.info("removing old policies in %s ..." % dirpath)
                try:
                    shutil.rmtree(dirpath)
                except OSError as err:
                    self.ui.error("failed to remove directory %s: %s" % (dirpath, err))
```

which normally deletes the directory tree without issues... `rmtree` is basically `rm -rf`

When it fails next, can you run 

``` find -ls /usr/local/zeek/spool/installed-scripts-do-not-touch/site
```

to see what files are left in there.

**Comment by 0xxon** [comment]
To make this into a question - could you tell us what files are left in the directory when this error occurs? :)

**Comment by rsmmr** [comment]
Ping @LBLSecurity: what's left?

**Comment by initconf** [comment]
so right now, if I run zeekctl deploy twice, first time I see the error and second time it runs. 

Note: the spool is on NFS file system - I won't know if thats gotta do something with this. 

Here : 

$ zeekctl deploy
checking configurations ...
installing ...
removing old policies in /usr/local/zeek/spool/installed-scripts-do-not-touch/site ...
Error: failed to remove directory /usr/local/zeek/spool/installed-scripts-do-not-touch/site: [Errno 66] Directory not empty: '/usr/local/zeek/spool/installed-scripts-do-not-touch/site/smtp-url-analysis/scripts/feeds'


then I ran: 

$ find  /usr/local/zeek/spool/installed-scripts-do-not-touch/site  -ls 

shows me whole lot of files/scripts as expected. 

and I tried again without doing anything else, and it worked 


$ zeekctl deploy
checking configurations ...
installing ...
removing old policies in /usr/local/zeek/spool/installed-scripts-do-not-touch/site ...
removing old policies in /usr/local/zeek/spool/installed-scripts-do-not-touch/auto ...
creating policy directories ...
installing site policies ...
generating cluster-layout.zeek ...
generating local-networks.zeek ...
generating zeekctl-config.zeek ...
generating zeekctl-config.sh ...
updating nodes ...
stopping ...
stopping workers ...
stopping proxies ...
stopping manager ...
starting ...
starting manager ...
starting proxies ...
starting workers ...

**Comment by rsmmr** [comment]
> shows me whole lot of files/scripts as expected.

Are you saying it's the full set of files, i.e., nothing is removed? In other words, what's the diff between the output of the `find` before/after that first `deploy`?

Yeah, I guess NFS could have something to do with it, maybe it deletes asynchronously. If you wait a couple of minutes after the error and repeat the `find`, any difference?

**Comment by initconf** [comment]
> Are you saying it's the full set of files, i.e., nothing is removed? In other words, what's the diff between the output of the `find` before/after that first `deploy`?

Yes. 
`$ zeekctl deploy
checking configurations ...
installing ...
removing old policies in /usr/local/zeek/spool/installed-scripts-do-not-touch/site ...
Error: failed to remove directory /usr/local/zeek/spool/installed-scripts-do-not-touch/site: [Errno 66] Directory not empty: '/usr/local/zeek/spool/installed-scripts-do-not-touch/site/smtp-url-analysis/scripts/feeds'`

`$ find  /usr/local/zeek/spool/installed-scripts-do-not-touch/site  -ls| wc -l
    1587`

But somehow there is nothing in :

[/usr/local/zeek/spool/installed-scripts-do-not-touch/site/smtp-url-analysis/scripts/feeds]$ ls -altrh
total 64
drwxr-xr-x  4 bro  bro   4.0K Nov  4 08:45 ..
drwxr-xr-x  2 bro  bro   2.0K Nov  4 08:45 .

Let me investigate NFS side of the issue - I am more and more certain this is NFS.

**Comment by rsmmr** [comment]
Ack, keep us posted.

**Comment by timwoj** [comment]
I'm inclined to close this one since we're going to be replacing zeekctl with the new management framework stuff in the nearish future.

**Comment by initconf** [comment]
I’d say close this one. It’s a an NFS issue.  The lock doesn’t go away
unless we run it twice.
I’ve learned to live with it.
