### ISSUE TITLE
Reply comes before request bug

### ISSUE THREAD

**Issue by caodongzhi1976** [zeek/zeek#1178]
When reply comes before request, the zeek can not deliver the request. see the pcap in the zip
[data_9999999999_700003.zip](https://github.com/zeek/zeek/files/5253930/data_9999999999_700003.zip)

**Comment by rsmmr** [comment]
I haven't looked at the trace yet, but it would be helpful if you could provide a bit more context here: what are you seeing, and what do you think Zeek should be doing instead. The latter is important: Generally a number of Zeek's analyzers/scripts will have trouble when things come out of order, and often it's not clear what the right strategy would be instead in such a case.

**Comment by caodongzhi1976** [comment]
void TCP_Reassembler::DeliverBlock(uint64_t seq, int len, const u_char* data)
 {
...

 if ( deliver_tcp_contents )
  {
  //-------------------------------------------------------------------------------------------------------
  // I get the tcp sequence in order 1 2 5 6, here now. 
  // I want to get the tcp sequence in order 1 2 4 3 5 6.
  //-------------------------------------------------------------------------------------------------------


...
  }

...

 }

**Comment by jsiwek** [comment]
It may be possible to add more buffering mechanisms to the TCP reassembly process so that this type of misordering isn't detected as a gap-then-retransmission, but doubt suitability for general use since whenever this has come up before, people resolve it via change in their capture setup/config, like #335.

**Comment by rsmmr** [comment]
Yeah, assuming this is a capture problem, I'll go ahead and close this.
