### ISSUE TITLE
Add support for controlling plugin loading order

### ISSUE THREAD

**Issue by rsmmr** [zeek/zeek#1179]
We don't have a way to make sure that two plugins that depend on each other are loaded in the right order. We should add a way to control loading order.

Specific example: let's say we have plugin `A` that depends C++ functions implemented by plugin `B`. Right now, Zeek will load them in alphabetical order by their names. That means loading `A` will come first, and it will fail because the dynamic linker won't be able to resolve the symbols that are implemented by `B`. If we switch the names around, it'll work.

I'm not quite sure yet how to control loading order. Couple ideas: 

- We could add priorities to plugins and load those with higher priority first. So `A` could say "I'm a high-priority plugin that needs to be loaded early".

- We could let plugins define dependencies explicitly and then figure out the loading order from that. That's a bit more complex to to implement as we would to need build up a dependency graph.

**Comment by jsiwek** [comment]
Maybe a third option is treating `dlopen()` failure as non-fatal unless there's no further plugins to load that might rectify the problem.  i.e. loop until either all plugins load successfully or there's a failure with no further progress made during one full round of looping.

**Comment by rsmmr** [comment]
Ah, that's a nice thought. It would definitely address the specific situation I was running into. Are there other cases where loading order matters, beyond symbol resolution? If not, this might be the best/easiest way out.

**Comment by rsmmr** [comment]
I'll take a stab at this.
