### ISSUE TITLE
icmpv6 type 143 calculation of payload length

### ISSUE THREAD

**Issue by benjeems** [zeek/zeek#1181]
ICMPv6 type 143 (Version 2 Multicast Listener Report) can contain multiple Address Records.
- When a single Address record is contained, c$icmp$len is correctly evaluated and this matches |payload| as expected.
- However when there are >1 Address records, c$icmp$len doesn't include the total length of all the records in the payload as one might expect. Only the length of the first record is recorded in c$icmp$len.

See diagram and sample pcap which includes a packet with a single record and a packet with two records.
![icmp_143](https://user-images.githubusercontent.com/45679313/93956075-a6952200-fd94-11ea-8db9-b0278bf67dde.jpg)
[icmpv6_type143.pcap.zip](https://github.com/zeek/zeek/files/5265101/icmpv6_type143.pcap.zip)

```
event icmp_sent_payload(c: connection, icmp: icmp_conn, payload: string)
    {
    print (fmt("icmp=%s, icmp$length=%s, |payload|=%s,  payload=%s", icmp, icmp$len, |payload|, payload)]);
    }

```
```
br:testing benreardon$ zeek -Cr pcaps/icmpv6_type143.pcap ../scripts/mini_test.zeek 
icmp=[orig_h=fe80::7d6c:b050:d9c5:73f7, resp_h=ff02::16, itype=143, icode=0, len=20, hlim=1, v6=T], icmp$length=20, |payload|=20,  payload=\x04\x00\x00\x00\xff\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0c
icmp=[orig_h=fe80::7d6c:b050:d9c5:73f7, resp_h=ff02::16, itype=143, icode=0, len=20, hlim=1, v6=T], icmp$length=20, |payload|=40,  payload=\x04\x00\x00\x00\xff\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x03\x04\x00\x00\x00\xff\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0c
```

**Comment by jsiwek** [comment]
What Zeek version?  This may be the same observation from #1019 

Using `master` branch:

```zeek
# cat test.zeek
event icmp_sent_payload(c: connection, icmp: icmp_conn, payload: string)
    {
    print fmt("using icmp_conn: itype=%s, icode=%s, len=%s, |payload|=%s",
              icmp$itype, icmp$icode, icmp$len, |payload|);
    }

event icmp_sent_payload(c: connection, info: icmp_info, payload: string)
    {
    print fmt("using icmp_info: itype=%s, icode=%s, len=%s, |payload|=%s",
              info$itype, info$icode, info$len, |payload|);
    }
```

```
$ zeek -r icmpv6_type143.pcap test.zeek
warning in ./test.zeek, line 1 and /home/jon/pro/zeek/zeek/build-rel/scripts/base/bif/plugins/./Zeek_ICMP.events.bif.zeek, line 46: use of deprecated 'icmp_sent_payload' prototype: Remove in v4.1.  The icmp_info record is replacing icmp_conn (event(c:connection; icmp:icmp_conn; payload:string;))
using icmp_conn: itype=143, icode=0, len=20, |payload|=20
using icmp_info: itype=143, icode=0, len=20, |payload|=20
using icmp_conn: itype=143, icode=0, len=20, |payload|=40
using icmp_info: itype=143, icode=0, len=40, |payload|=40
```

Zeek v3.2.0 should also give the same result.  The patch isn't backported to v3.0.x since it's a change in semantics.

**Comment by benjeems** [comment]
I was using zeek version 3.2.0-dev.459, however I now realise that I missed some of the subtlety around the icmp_info vs icmp_conn change - and indeed this causing my issue. Thanks Jon.
