### ISSUE TITLE
Packet analysis: Investigate replacing custom dispatcher class

### ISSUE THREAD

**Issue by timwoj** [zeek/zeek#1183]
There's a fairly complicated `Dispatcher` object that is used to look up the next analyzer in the dispatch tree. We'd like to replace it with something more standard, especially since what it does is fairly simple for the amount of code involved. Benchmarks showed that just using a `std::map` was a performance loss.

**Comment by rsmmr** [comment]
Another one to review once we wrap up 4.0.

**Comment by rsmmr** [comment]
Closing, seems there's no pressing need for changes right now.
