### ISSUE TITLE
Packet analysis: add more information to weirds

### ISSUE THREAD

**Issue by timwoj** [zeek/zeek#1184]
We discussed this during the PR work but decided it was better as a follow-on. We should add some more information to the weirds generated from packet analysis with information about where they originated. The file analysis code already does something similar.

**Comment by rsmmr** [comment]
Another one to review at least with 4.0.

**Comment by timwoj** [comment]
Is just putting the analyzer name in the `addl` field of the weird sufficient to cover this?

**Comment by rsmmr** [comment]
Yeah, I would say so, seems there's not really anything else that would be consistently available for recording at this layer.

Btw, does the weird's timestamp match the timestamp of the packet we're analyzing? It should, right?, and that would then be quite helpful for tracking down the offending packet in a trace.
