### ISSUE TITLE
consequence of incomplete partial migration from earlier Zeek, express it more gracefully

### ISSUE THREAD

**Issue by duffy-corelight** [zeek/zeek#1194]
The endeavor to migrate from an earlier version of Zeek to the newer, does just as documented in https://docs.zeek.org/en/current/quickstart/index.html#running-zeek-without-installing when invoking with -b, as shown in 4852. But the err result shown in 4850 could be dealt with more gracefully, by adding code to detect specifically that and then express that as `"In consequence of incomplete partial migration from an earlier version of Zeek..."` Rather than just expressing that as whatever first fatal thing that the partial migration from an earlier version of Zeek runs into.

```
4849 /usr/local/etc/3.3.0-dev.284$cd newer/zeek/build

4850 /usr/local/etc/3.3.0-dev.284/newer/zeek/build$ZEEKPATH=`./zeek-path-dev` ./src/zeek

fatal error in /usr/local/etc/3.3.0-dev.284/newer/zeek/scripts/base/init-bare.zeek, line 1: cannot load plugin library /usr/local/zeek/lib/zeek/plugins/zeek-plugin-bacnet//lib/Zeek-Bacnet.darwin-x86_64.so: dlopen(/usr/local/zeek/lib/zeek/plugins/zeek-plugin-bacnet//lib/Zeek-Bacnet.darwin-x86_64.so, 9): Symbol not found: __Z16base_type_no_ref7TypeTag
  Referenced from: /usr/local/zeek/lib/zeek/plugins/zeek-plugin-bacnet//lib/Zeek-Bacnet.darwin-x86_64.so
  Expected in: flat namespace
 in /usr/local/zeek/lib/zeek/plugins/zeek-plugin-bacnet//lib/Zeek-Bacnet.darwin-x86_64.so

4851 /usr/local/etc/3.3.0-dev.284/newer/zeek/build$set| grep ZEEK
ZEEKPATH=/Users/duffy/Documents/work/projects/maestro/zeek-agent-framework:.:/usr/local/zeek/share/zeek:/usr/local/zeek/share/zeek/policy:/usr/local/zeek/share/zeek/site:/Users/duffy/.zkg/script_dir

4852 /usr/local/etc/3.3.0-dev.284/newer/zeek/build$ZEEKPATH=`./zeek-path-dev` ./src/zeek -b -NN |less
```

**Comment by rsmmr** [comment]
Not sure this is really solvable: there are different reasons why such an error could occur, not just because of "an incomplete partial migration". Also, the instructions you are referring to are specifically for developers, not users, so I would say we can rely on a bit more self-help there.

**Comment by duffy-corelight** [comment]
I definitely concur that this primarily arises for developers not users. It is a philosophy decision whether to go down this road (since it is a road where one can never fully reach the end). When a situation is identified which will arise, and can be detected by a conditional or catch on the abnormal, it can be recharacterized with a different diagnostic text, that is directive to the underlying cause. I learned this when working on XML DOM programming. Substitutions like: "Did you forget a close-quote on the previous line?" as the error-text, instead of the specific extraordinarily inscrutable default DOM messages triggered by a missing close-quote on the previous line, made the resulting edit-run development cycle hugely more productive.

**Comment by rsmmr** [comment]
We've done things like this in the past for cases where users kept running into the same problem. This doesn't seem to be that common as case, so I'd leave it as is unless there are others here who thing we should add something.

**Comment by duffy-corelight** [comment]
I had submitted this ticket before I learned at https://github.com/zeek/spicy/issues/520 that "Compiled Zeek analyzers will always be specific to version they were built for, because Zeek doesn't provide binary compatibility between releases." With that understanding, I now see that no one who is migrating from an earlier version of Zeek to a newer one, can expect success unless all the installed plugins for the prior version are made hidden by proper use of PATH settings in the environment, or eliminated. 

I had mistakenly presumed `symbol not found: __Z16base_type_no_ref7TypeTag` was an isolated case of a symbol now required in the newer Zeek, (or now absent in that version) and any such change could be coded to gracefully detect and make an intentional error report, as part of a philosophy for the occasional needful changeover. But if "Zeek doesn't provide binary compatibility between releases" is our philosophy, then needful changeover including breaking changes is not occasional but rather the norm. We don't need to provide hand-holding for every change. I was mistaken in thinking that the reported `symbol not found` was an unrealized and rare in being not-gracefully handled outlier.

**Comment by 0xxon** [comment]
I am going to close this, as it seems there is nothing left to do.

And just to confirm - we do, as you stated, not provide binary compatibility between releases.

**Comment by duffy-corelight** [comment]
Closing this ticket is the right thing. I will re-introduce this point in a new one with a more on-point example, if I encounter one in future migrations between releases. I wrote this ticket while mistaken in thinking that plugins all but rarely wouldn't need recompilation during migrations between releases.
