### ISSUE TITLE
 Strange behaviour of Zeek version 3.2.1. Zeek splits the long connection into several small ones.

### ISSUE THREAD

**Issue by kamilababayeva** [zeek/zeek#1196]
Hello! I was analyzing the pcap and came across a strange behaviour in Zeek version 3.2.1

The folder with pcap and Zeek generated logs is here https://drive.google.com/drive/folders/13WZAA5Mu6Xww67kbDtbwSfokfNDTcB6C?usp=sharing

The pcap 74.125.133.188.pcap contains one long connection between the IP 10.8.0.61 and the IP 74.125.133.188. There is a 3-way handshake to establish the connection, but there is no 4-way handshake for the connection termination. In the pcap the time difference between some of the packets is more than 10 minutes, however it is still the same connection. 

The Wireshark (Wireshark 3.2.3) Statistics-Conversations displays this connection as a long one: 
![Screenshot from 2020-10-02 16-39-58](https://user-images.githubusercontent.com/51053878/94945161-8a9f2800-04da-11eb-916c-8f01aad4fdca.png)

Zeek (zeek version 3.2.1) displays this connection as several small ones with flags S1 and OTH:
![Screenshot from 2020-10-02 17-05-41](https://user-images.githubusercontent.com/51053878/94945216-a0ace880-04da-11eb-9d22-2090e1ed680b.png)
Is it the correct way that Zeek displays this connection not as one long connection but as several small connections???

Thanksssss!

**Comment by ckreibich** [comment]
That's a fun pcap. :-) What's happening here is that the long pauses in your pcap are making Zeek give up on the flow state and then establishing new flow state for what's actually the same flow still. Zeek's default "patience" with TCP is 5 minutes, defined in the `tcp_inactivity_timeout` variable. We default this to 5 minutes. There's no right or wrong here, so this isn't a bug.

In the case of your pcap I have to set a 21 minute inactivity timeout to get the desired behavior. You can do this at the command line:
```
$ zeek -r ~/74.125.133.188.pcap tcp_inactivity_timeout=21mins
$ cat conn.log
#separator \x09
#set_separator  ,
#empty_field    (empty)
#unset_field    -
#path   conn
#open   2020-10-05-18-06-23
#fields ts      uid     id.orig_h       id.orig_p       id.resp_h       id.resp_p       proto   service duration        orig_bytes      resp_bytes      conn_state      local_orig      local_resp      missed_bytes    history orig_pkts       orig_ip_bytesresp_pkts       resp_ip_bytes   tunnel_parents
#types  time    string  addr    port    addr    port    enum    string  interval        count   count   string  bool    bool    count   string  count   count   count   count   set[string]
1596790174.429246       CDOEb93j148iJPJxVc      10.8.0.61       40727   74.125.133.188  5228    tcp     ssl     4860.508546     1215    10309   S1      -       -       0       ShADad  26      2575    27      11721   -
#close  2020-10-05-18-06-23
```
In practice you'll have to strike a balance between theoretical correctness and practical state-keeping realities ... if your setting allows it, then by all means crank up `tcp_inactivity_timeout`.
