### ISSUE TITLE
Strange behaviour of Zeek version 3.2.1. Zeek does not display the connections from the pcap.

### ISSUE THREAD

**Issue by kamilababayeva** [zeek/zeek#1197]
Hello! I was analyzing the pcap and faced the problem of Zeek version 3.2.1 not displaying the connections from the pcap.

The pcap and zeek generated logs are here https://drive.google.com/drive/folders/125EsO1NvNaDStPoTy15TcCPu6yzCBYF2?usp=sharing

The pcap bug.pcap has 3 connections between the IP 10.8.0.137 and the IP 147.32.83.234. 

When Zeek (version 3.2.1) is run on the bug.pcap, these 3 connections are not present in the conn.log. The IP 147.32.83.234 is not found in any of the logs either:
![Screenshot from 2020-10-02 17-27-40](https://user-images.githubusercontent.com/51053878/94945732-698b0700-04db-11eb-9f3d-a25961b6875b.png)

Wireshark (Wireshark 3.2.3) Statistics-Conversation displays these 3 connections:
![Screenshot from 2020-10-02 17-21-52](https://user-images.githubusercontent.com/51053878/94945758-71e34200-04db-11eb-9145-973d0ac14421.png)

If we filter bug.pcap to have only connections between the IP 10.8.0.137 and the IP 147.32.83.234 and run Zeek on this pcap (147.32.83.234.pcap), Zeek will display these 3 connections:
![Screenshot from 2020-10-02 17-33-22](https://user-images.githubusercontent.com/51053878/94945778-79a2e680-04db-11eb-9f97-8eb47f6f084c.png)

What might be the problem? 
Thanks!!!!

**Comment by ckreibich** [comment]
Could you try this with a build of current master? It's looking to me like we've already fixed this, and it was a problem of the 3.2 series only. I believe @jsiwek's commit [bcef1fc871579b3d17a948d826671fcbee48675c](https://github.com/zeek/zeek/commit/bcef1fc871579b3d17a948d826671fcbee48675c) resolved this one — at least, that's where a `git bisect` just landed me.

**Comment by kamilababayeva** [comment]
Thanks! I am building now!!! I will try and let you know.

**Comment by jsiwek** [comment]
From Zeek 3.2 onward, truncated pcap files are treated as a fatal error (see #1004) and won't undergo a "normal" termination procedure that, for example, might otherwise guarantee that buffered log entries get flushed to disk.  You can fix the pcap with `tcpdump` to avoid the issue.  E.g. with Zeek 3.2.1:

```
$ zeek -r bug.pcap
1599754560.807338 fatal error: failed to read a packet from bug.pcap: truncated dump file; tried to read 100 captured bytes, only got 53

$ grep 147.32.83.234 conn.log

$ tcpdump -r bug.pcap -w bug-fixed.pcap
reading from file bug.pcap, link-type RAW (Raw IP)
tcpdump: pcap_loop: truncated dump file; tried to read 100 captured bytes, only got 53

$ zeek -r bug-fixed.pcap

$ grep 147.32.83.234 conn.log
1599753698.448367	C6cwgI1jJstX8KHlQk	10.8.0.137	36320	147.32.83.234	1337	tcp	-	149.024530	270	82	SF	-	-	0	ShADTadFf	9	1016	8	518	-
1599753907.484636	Ctym3L2roczO8vOwvi	10.8.0.137	36324	147.32.83.234	1337	tcp	-	50.221542	270	21	RSTR	-	-	0	ShADTadtr	4	756	11	748	-
1599751080.922036	CnIOjn2Aj2zQcRr5De	10.8.0.137	36280	147.32.83.234	1337	tcp	-	2611.345391	2849526	1198	S2	-	-	0	ShADTadTwF	3007	3016960	1580	83402	-
```

**Comment by ckreibich** [comment]
@jsiwek so should this also not be working in master then? It does: 

```
$ zeek --version
zeek version 3.3.0-dev.365
$ zeek -r bug.pcap
1599754560.807338 fatal error: failed to read a packet from /home/christian/bug.pcap: truncated dump file; tried to read 100 captured bytes, only got 53
$ grep 147.32.83.234 conn.log
1599753698.448367       CQjbcMsxSUANx1x2g       10.8.0.137      36320   147.32.83.234   1337    tcp     -       149.024530      270     82      SF      -       -       0       ShADTadFf       9       1016    8       518     -
1599753907.484636       CYV3oD1nvvYBAilKJk      10.8.0.137      36324   147.32.83.234   1337    tcp     -       50.221542       270     21      RSTR    -       -       0       ShADTadtr       4       756     11      748     -
1599751080.922036       CUi6xF4gakyvcURFbk      10.8.0.137      36280   147.32.83.234   1337    tcp     -       2611.345391     2849526 1198    S2      -       -       0       ShADTadTwF      3007    3016960 1580    83402   -
```

**Comment by ckreibich** [comment]
Ah, I think I get it now — bcef1fc871579b3d17a948d826671fcbee48675c tweaked the event handling sufficiently that the connection-removal events do get processed, regardless of the truncation issue. If I'm way off here, shout. Thanks!

**Comment by jsiwek** [comment]
@ckreibich right, appearance of Good behavior in `master` is coincidence since whether those particular entries get written can be sensitive to internal details like the the event-queue, thread-scheduling, log-buffering, etc.  The resulting `conn.log` from the truncated pcap still lacks a final `#close` tag to suggest we should suspect it may not have really wrote everything it could have.
