### ISSUE TITLE
Distribution packages do not have stable links

### ISSUE THREAD

**Issue by bbannier** [zeek/zeek#1207]
The Zeek project currently provides distribution packages via the openSUSE build service. This is great as it should take the work of compiling Zeek out of users' hands who instead can just download packages for their target distribution.

A current limitation of this setup is that packages are only provided for the last LTS and nightly versions, i.e., there is currently an LTS package for 3.0.11, but this package will go away when 3.0.12 gets released. This makes it practically impossible to use the provided packages in a reproducible way, e.g., when consuming the package in a `Dockerfile` one has to choose between hardcoding a version which might become unavailable, or using whatever is around at the time the image is build, but not being able to reliably reproduce that image (the Zeek version could have changed in the meantime).

Much easier to use would be a setup where fully versioned and immutable packages would be available e.g., `zeek-core-dev-3.0.11` or `zeek-core-dev-3.2.2`, and meta packages which pull these in, e.g.,

- `zeek-lts-core-dev` -> `zeek-core-dev-3.0.11`
- `zeek-nightly-core-dev` -> `zeek-core-dev-3.2.2`

Users could then choose whether to depend on a fixed version or a moving LTS or nightly package.

**Comment by 0xxon** [comment]
We could do this - but this would go very much against rpm and deb packaging; at least how I understand it - since the packages itself are already versioned; however OBS just keeps the most current version.

What we also could do is to just pull down copies of the deb/rpm files (which are versioned) and put them into a directory on, e.g., download.zeek.org. Then, if someone is interested in an old version, they can just pull the old exact version of the rpms/debs. (edited)

**Comment by 0xxon** [comment]
As a side-note - do you really encounter problems between minor releases? (as in 3.0.11->12)

They should basically be identical to the earlier minor versions - besides regressions and security fisex.

**Comment by bbannier** [comment]
> As a side-note - do you really encounter problems between minor releases? (as in 3.0.11->12)

We hardcode a specific version which I think is useful for reproducibility, but we haven't run into specific issues, yet.

> What we also could do is to just pull down copies of the deb/rpm files (which are versioned) and put them into a directory on, e.g., download.zeek.org. Then, if someone is interested in an old version, they can just pull the old exact version of the rpms/debs.

Like we discussed offline, this would work as well. Instead of installing via say `apt-get` we'd end up installing local files with `dpkg` and do manual dependency resolution; this should be good enough if dependencies do not change wildly between patch releases (say: broker packages being broken into different subpackages).

**Comment by 0xxon** [comment]
Ok, that sounds good.

Funnily, the most complex part of this will be the s3 side. download.zeek.org is served out of a bucket, and a trigger is used to execute a python function that generates the index.html page.

This setup is currently not able to deal with subdirectories - that will have to be fixed for this.

**Comment by rsmmr** [comment]
Adding this to 4.0, would be nice to have that in place for the next LTS cycle.

**Comment by 0xxon** [comment]
This is not partially functional. I uploaded the current set of packages to the binary-packages directory on download.zeek.org. Currently this is not in the directory listing (but I am working on that).

The current set of packages now does have stable links; just use the directory name on OBS and access it on https://download.zeek.org/binary-packages/. So for example:

https://download.zeek.org/binary-packages/xUbuntu_20.04/arm64/zeek_3.2.2-0_arm64.deb
or
https://download.zeek.org/binary-packages/Fedora_29/x86_64/zeek-lts-core-3.0.11-2.1.x86_64.rpm

Note that only the .deb and .rpm files are available here; to use this service, the user is responsible for collecting together all the rpm/deb files that they need and to install them manually.

**Comment by bbannier** [comment]
FTR, to get the correct links one can drill down to the target platform's _Build Results_ (RHS) [here](https://build.opensuse.org/package/show/security:zeek/zeek).

**Comment by bbannier** [comment]
We switched the Dockerfiles in Spicy to use the links you provided above @0xxon, e.g., for our centos-8 build we hardcoded e.g.,     https://download.opensuse.org/repositories/security:/zeek/CentOS_8/x86_64/zeek-lts-3.0.11-2.2.x86_64.rpm. This failed to rebuild today since that file does not exist anymore since at least 2020-12-10; instead now I see a file zeek-lts-3.0.11-2.3.x86_64.rpm (incremented build number). Given that the file we saw previously is now gone, I am not sure we have gained anything by switching to the raw files as opposed to the proper repo, yet.

**Comment by rsmmr** [comment]
That's not the link  provided above, no? Only the download.zeek.org links will be stable.

**Comment by bbannier** [comment]
@rsmmr, thanks for the clarification, I glossed over that part :(

I will migrate that our remotes from OBS to http://downloads.zeek.org with the build numbers backed in from the OBS listing.

**Comment by 0xxon** [comment]
This should all be done now - we have a copy of binary packages at http://download.zeek.org/binary-packages/

The manual for binary packaging also mentions how to perform the uploads.
