### ISSUE TITLE
Aggregate data based notices notices omit valuable fields

### ISSUE THREAD

**Issue by dspruell-s01** [zeek/zeek#1210]
I'm stumped with something where notices are created for aggregate activity (occurring over multiple connections) and analysis of those notices is complicated by the need to trace the activity back to records of the activity (conn and/or http).

Examples of this are `HTTP::SQL_Injection_Attacker` and `HTTP::SQL_Injection_Victim`, which if I understand correctly operate on aggregated data (a threshold of multiple events within a given timeframe). The resulting notices are fairly thin on detail:

```
#fields	ts	uid	id.orig_h	id.orig_p	id.resp_h	id.resp_p	fuid	file_mime_type	file_desc	proto	note	msg	sub	src	dst	p	n	peer_descr	actions	suppress_for	remote_location.country_code	remote_location.region	remote_location.city	remote_location.latitude	remote_location.longitude
#types	time	string	addr	port	addr	port	string	string	string	enum	enum	string	string	addr	addr	port	count	string	set[enum]	interval	string	string	string	double	double
1230820619.374040	-	-	-	-	-	-	-	-	-	HTTP::SQL_Injection_Attacker	An SQL injection attacker was discovered!	-	117.195.143.198	-	-	-	-	Notice::ACTION_LOG	3600.000000	-	-	-	-	-
1230820619.374040	-	-	-	-	-	-	-	-	-	HTTP::SQL_Injection_Victim	An SQL injection victim was discovered!	-	208.106.128.136	-	-	-	-	Notice::ACTION_LOG	3600.000000	-	-	-	-	-
```

Having the origin logs' `uid` values would obviously be helpful for enabling correlation of these events for further analysis. It's not clear to me how to otherwise correlate it back reliably when the correlation time window isn't clear (default 50, but has it been modified?) and when there may be many records for the identified victim or attacker address in a given timeframe (a likelihood when false positives may be occurring with the matched patterns). Given that it's based on aggregate data, I see how a single value field is not possible.

Is there any way that these types of notices can be enhanced to carry more attribution/correlation detail to tie back to discrete data records? (Or am I missing something obvious about these events)?

**Comment by 0xxon** [comment]
Hi,

just to confirm your understanding - the way the scripts are written, there is currently no way to correlate the log lines back to the actual unique connections that caused the notice to be raised. The data is simply not collected in the script.

I think that this was done like this on purpose - this script is just supposed to give you an indication of a host probably performing an SQL injection attack; in a case like this is probably is prudent to review connections to/from the affected hosts in general.

If you are interested in the matching connections, you also can just use the regular expression that is used by the script - and match that against the URIs in http.log.

**Comment by JustinAzoff** [comment]
for the sqli script, it already annotates the matching http log entries by adding values to the `tags` field in the http log entries.

**Comment by dspruell-s01** [comment]
Makes sense - the tags work particularly well here. Sorry for the noise!
