### ISSUE TITLE
Multiple workers on Accolade NIC

### ISSUE THREAD

**Issue by g4laad** [zeek/zeek#1212]
Hi !
I am currently benchmarking Zeek with multiple NICs in order to find the best combination to analyze a traffic of 10Gb/s.
To do so, we have different NICs and I am now looking at an Accolade one, the 40Ku.

My current setup is the following:
- Ubuntu 20.04
- Accolade 40Ku (4 ports of 10G) and its driver, port 1 connected
- PF_RING 7.7.0.200930 compiled, I have a license for PF_RING ZC so tcpdump doesn't trigger any license error
- Zeek  3.3.0-dev.377 (git version compiled with the libpcap from PF_RING)

node.cfg

```
[logger-1]
type=logger
host=localhost
#
[manager]
type=manager
host=localhost
#
[proxy-1]
type=proxy
host=localhost
#
[worker-1]
type=worker
host=localhost
interface=anic:1
lb_method=pf_ring
lb_procs=5
pin_cpus=2,3,4,5,6
```

Whenever I deploy, I always have at least one crashed worker with the following errors:
```
diag worker-1-5


[ANIC] try
[ANIC] hugepageGetAt() shmget() failed errno: 12 Cannot allocate memory
__pfring_anic_hugepageGet() failed errno:12 Cannot allocate memory
fatal error: problem with interface anic:1 (pcap_error: SIOCGIFHWADDR: No such device (pcap_activate))
```
However here's my configuration:
```
cat /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages
1024
```

or

```
/usr/local/zeek/share/zeekctl/scripts/run-zeek: line 110: 31920 Segmentation fault      (core dumped) nohup ${pin_command} $pin_cpu "$myzeek" "$@"
```

Moreover, when I set up 2 workers and both of them are running, only one of them gets the packets.

Could you tell me what should I change in my server/zeek/NIC configuration in order to have a stable Zeek server ?

Thank you !

**Comment by 0xxon** [comment]
Hi,

We don't use GitHub issues for support questions. Questions like this are best answered using on either slack or our mailing list, which is both are frequented by Zeek developers and professional users. You can join here:

Mailing list: https://lists.zeek.org/mailman3/lists/zeek.lists.zeek.org/

Slack: https://zeek.org/community/

As a side-note - going from the error message, this does not seem to be an issue with Zeek; I think the error message either originates from the driver of pf-ring.

 Johanna
