### ISSUE TITLE
Packet analysis: Switch to function-based API

### ISSUE THREAD

**Issue by rsmmr** [zeek/zeek#1215]
When working on integrating Spicy with the packet analyzer API, I realized that the current static nature of the global dispatch tables ends up being too limiting when analyzers can appear dynamically after scripts already have been parsed. I suggest we change the API to provide functions that instead create dispatcher mappings in inside `zeek_init()` handlers. That would push the dispatcher tables to behind the scenes, and I believe also remove the constraints in the module name (currently, the core needs to know in which scope to find the dispatcher table). It would also be more inline with other Zeek APIs.

I'm not quite sure whether to hide `DispatchEntry` as well, but I'm leaning towards yes. 

We'd need at least two versions of the functionality to register mappings: one taking enums (which seems the right, type-safe mechanism in general) and one taking analyzer names as strings (which is needed for dynamic cases where we don't know which analyzers will eventually be available at the time when we are parsing scripts).

Taking that altogether, here's a proposal replacing the current `dispatch_table` approach with two functions:

```

# Add an entry to `parent`s dispatcher that maps a protocol/index to a next-stage `child` analyzer.
register_packet_analyzer(parent: PacketAnalyzer::Tag, index: count, child: PacketAnalyzer::Tag);

# Attempts to add an entry to `parent`'s dispatcher that maps a protocol/index to a next-stage `child` analyzer.
# This may fail if either of the two names does not respond to a known analyzer.
try_register_packet_analyzer_by_name(parent: string, index: count, child: string) :  bool

```

These functions must not be called after `zeek_init` has finished.

@J-Gras you mentioned needeing a register function also for "static" packet analyzers that aren't part of a dispatching table. What would you suggest that to look like?

**Comment by J-Gras** [comment]
It could be necessary to configure "static" analyzers after `zeek_init` as well (e.g., the ones for Ethernet, see below).
```zeek
## IEEE 802.2 SNAP analyzer
const snap_analyzer: PacketAnalyzer::Tag &redef;
## Novell raw IEEE 802.3 analyzer
const novell_raw_analyzer: PacketAnalyzer::Tag &redef;
## IEEE 802.2 LLC analyzer
const llc_analyzer: PacketAnalyzer::Tag &redef;
```
We could either turn them into variables instead of using consts or provide a corresponding pair of functions:
```zeek
register_static_packet_analyzer(parent: PacketAnalyzer::Tag, name: string, child: PacketAnalyzer::Tag) : bool;
try_register_static_packet_analyzer_by_name(parent: string, name: string, child: string) :  bool;
```
I am in favour of just turning the consts into globals.

**Comment by timwoj** [comment]
I agree with all of this. Taking out the dispatch map and replacing it with direct registration methods makes sense to me.

**Comment by rsmmr** [comment]
> I am in favour of just turning the consts into globals.

+1

**Comment by rsmmr** [comment]
@timwoj see if you can take a stab at this
