### ISSUE TITLE
Investigate need for ENABLE_MOBILE_IPV6 macros

### ISSUE THREAD

**Issue by timwoj** [zeek/zeek#1216]
There was some discussion as part of https://github.com/zeek/zeek/pull/1198 whether the ENABLE_MOBILE_IPV6 macros were still needed or if the code surrounded by them could just be built all of the time. This issue is to investigate that.

**Comment by rsmmr** [comment]
Putting this on the 4.1 list, seems like the right time to invesitate now.

**Comment by timwoj** [comment]
https://github.com/zeek/zeek/issues/1493 was recently opened due to `ENABLE_MOBILE_IPV6` breaking the build. I'll assign this one to myself for the 4.1 timeframe to see if we can't just remove the checks. I doubt it's much of a performance loss, but I don't know if we have any significantly-long pcaps to test with.

**Comment by 0xxon** [comment]
As a side-issue to this - I built a Zeek version with the movile IPV6 macros enabled (just to see what happens). All the baselines for them have apparently not been update in forever - and are thus broken.

We should/could probably add this to CI as a first step - and also make sure that fuzzing enables those code-paths.

**Comment by timwoj** [comment]
I added the configure option for this to the oss-fuzz builds as https://github.com/google/oss-fuzz/pull/5671.
