### ISSUE TITLE
Packet analysis: rework weirds for missing analyzers

### ISSUE THREAD

**Issue by timwoj** [zeek/zeek#1221]
We currently have one weird that gets reported when the next analyzer can't be found for a set of packet headers, called `no_suitable_analyzer_found`. This isn't terribly useful, since it doesn't indicate which analyzer we were leaving from nor which protocol we couldn't find. On top of this, the lack of support for a protocol may not really meet the definition of a weird. Weirds are more for something a packet that doesn't make sense or is an indication of packet data being broken in some way.

After talking to @jsiwek for a bit, he came up with the proposal to add a new log file called something like `unknown_protocols.log`, and report all of the missing support into that. It would log unique combinations of analyzers and protocols. There's a question of whether we'd want to do something like we do for weirds where we rate-limit duplicates, but that makes some sense since if you saw one unsupported packet protocol you'll probably see more of the same.

Alongside this work, I'll be removing the `default_analyzer` entry from the Ethernet analyzer. That analyzer defaults to dropping into the IP analyzer, which doesn't make any sense for a large number of packets since not everything will contain an IP header. Instead, an entry will get reported into the new log for each of these packets.

**Comment by jsiwek** [comment]
> After talking to @jsiwek for a bit, he came up with the proposal to add a new log file called something like `unknown_protocols.log`, and report all of the missing support into that.

@rsmmr also had the idea that a `reporter.log` info or warning could also be enough.  I don't really have reasons to prefer one way or the other myself; might see if there's other feedback or otherwise just do whatever's easiest.

> There's a question of whether we'd want to do something like we do for weirds where we rate-limit duplicates

Yeah, think that's required to avoid tanking performance on per-packet reporting.  I'd collect info about the number of each (Analyzer, Unknown-Proto-ID) tuple seen over some duration (maybe hourly default) and report in batches like that.

**Comment by timwoj** [comment]
I whipped something together using the reporter weird filtering as a model. Using the same thresholds and timeout duration as for weirds, we get just over 3000 entries into the log for just the 2009-M57-day11-18.trace file.

**Comment by timwoj** [comment]
There was some excellent discussion in the Zeek slack channel related to this starting at https://zeekorg.slack.com/archives/CSZBXF6TH/p1603239538039300.

What we landed on was adding a new log file called unknown_protocols.log, defined in a script with a different set of logging thresholds as weirds. There was a little bit of discussion about what fields to include. For sure we need the analyzer that was attempting to forward and what protocol identifier failed. There was also a request for a small snippet of data from the next header, maybe just the first 10 bytes or so?
