### ISSUE TITLE
zeek worker do not run script

### ISSUE THREAD

**Issue by wangzhengqing** [zeek/zeek#1239]
I have 2 workers. 
when after `zeekctl deploy`.  successed
worker-1 run crorrectly
 worker-2 did not run zeek script but those scripts has already synchronized from manager. 
why and how could i fixed it?

**Comment by 0xxon** [comment]
Hi,

We don't use GitHub issues for support questions. Questions like this are best answered using on either slack or our mailing list, which is both are frequented by Zeek developers and professional users. You can join here:

Mailing list: https://lists.zeek.org/mailman3/lists/zeek.lists.zeek.org/

Slack: https://zeek.org/community/

 Johanna
