### ISSUE TITLE
Default floating-point formatting misrepresents small numbers

### ISSUE THREAD

**Issue by vpax** [zeek/zeek#1244]
Per https://try.zeek.org/#/tryzeek/saved/461913, the statement:
```
print 0.0000000000005;
```
produces the output:
```
0.0
```
rather than what I'd expect, which is:
```
5e-13
```

The same occurs for the explicit statement:
```
print 5e-13;
```

The underlying problem appears to be that while `modp_dtoa2` has logic for converting very large values to scientific notation, it doesn't have corresponding logic for very small values.

**Comment by Aryannath** [comment]
where is the modp_dtopa2 fuction

**Comment by vpax** [comment]
@Aryannath It's in `src/modp_numtoa.c`.  A handy trick: `grep -r modp_dtoa2 src` will directly find it.
