### ISSUE TITLE
how to connect redis or excute python/shell script using zeek 

### ISSUE THREAD

**Issue by xx-zhang** [zeek/zeek#1247]
rt . sometimes i want toi connect redis or excute some script. how to make it.

thank you.

**Comment by 0xxon** [comment]
Hi,

We don't use GitHub issues for support questions. Questions like this are best answered using on either slack or our mailing list, which is both are frequented by Zeek developers and professional users. You can join here:

Mailing list: https://lists.zeek.org/mailman3/lists/zeek.lists.zeek.org/

Slack: https://zeek.org/community/

 Johanna
