### ISSUE TITLE
Insufficient enum type-checking (e.g. Notice::ACTION_LOG misinterpreted as Weird:ACTION_IGNORE without warning)

### ISSUE THREAD

**Issue by duffy-ocraven** [zeek/zeek#1250]
Though the ordering can be arranged arbitrarily as long as the correct symbolic is used,
Notice::ACTION_LOG is not the same value as Weird::ACTION_LOG and they could be made the same
to avoid subtle, unwarned coding error
```
# assigning ethernet"] = Notice::ACTION_LOG,};
# instead of ethernet"] = Weird::ACTION_LOG,};
# makes it produce no weird.log
redef Weird::actions += {["non_ip_packet_in_ethernet"] = Notice::ACTION_LOG,};
```

Here are excerpts from the declarations in base/frameworks/notice/main.zeek
```
	## in  actions  that can be taken with notices.
	type Action: enum {
		## Indicates that there is no action to be taken.
		ACTION_NONE,

		## Indicates that the notice should be sent to the notice
		## logging stream.
		ACTION_LOG,
```
and excerpts from the declarations in base/frameworks/notice/weird.zeek
```
	## in  actions  that can be taken with weirds.
	type Action: enum {
		## A dummy action indicating the user does not care what
		## internal decision is made regarding a given type of weird.
		ACTION_UNSPECIFIED,

		## No action is to be taken.
		ACTION_IGNORE,

		## Log the weird event every time it occurs.
		ACTION_LOG,
```

**Comment by rsmmr** [comment]
I'm not quite sure what you mean by "same value" here: Is it about the ordering inside the type definitions, or about the semantics what `*_LOG` means?

**Comment by duffy-ocraven** [comment]
I mean that the typo could be rendered harmless if
`redef Weird::actions += {["non_ip_packet_in_ethernet"] = Notice::ACTION_LOG,};`
behaved the same as
`redef Weird::actions += {["non_ip_packet_in_ethernet"] = Weird::ACTION_LOG,};`

But since instead `Notice::ACTION_LOG` behaves identical to `Weird:ACTION_IGNORE`
and there is no diagnostic issued, a coder could be sent pursuing an awful lot of wrong debugging attempts to find why there is no notice.log being produced.

**Comment by jsiwek** [comment]
Think it would be better to improve enum type-checking/assignment behavior to help catch those (don't know how complicated the full picture of doing that is without going in to try changing, but for starters, `same_type()` has "always" had a FIXME regarding the fact that different enum types are treated as the same).

**Comment by rsmmr** [comment]
Got it, and yeah, agree: this is type checking issue.

**Comment by duffy-ocraven** [comment]
... with a particularly pernicious usability consequence, whilst it remains on the FIXME list.

**Comment by timwoj** [comment]
Closing this issue in favor of #1820, since it has more technical detail in it.
