### ISSUE TITLE
Cloning repo on Windows fails due to files with colons in name

### ISSUE THREAD

**Issue by timwoj** [zeek/zeek#1252]
This is a follow-on from https://github.com/zeek/zeek/issues/986, which was fixed by renaming the `aux` directory to `auxil`. The next problem is that there are a couple of files in btest baselines, under scripts.base.protocols.conn.contents-default-extract, which have colons in the filenames. Colons are not allowed in filenames on Windows, according to https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions. The problem is that these filenames are automatically generated from connection data. The offending portions of the filenames are ipv6 addresses and colons between the addresses and port numbers.

The error from git is:

```
error: unable to create file testing/btest/Baseline/scripts.base.protocols.conn.contents-default-ext
ract/contents_[2001:470:1f11:81f:c999:d94:aa7c:2e3e]:49185-[2001:470:4867:99::21]:21_orig.dat: Inval
id argument
error: unable to create file testing/btest/Baseline/scripts.base.protocols.conn.contents-default-ext
ract/contents_[2001:470:1f11:81f:c999:d94:aa7c:2e3e]:49185-[2001:470:4867:99::21]:21_resp.dat: Inval
id argument
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

**Comment by jsiwek** [comment]
They're renamed for now, making clones work for me.  The underlying issue of the original filename format containing colons can be rediscovered and resolved later if the test/CI coverage for Windows gets expanded, but seems hard for people to perform/test those improvements if they can't first get the source-tree. (e.g. for real solution ideas: maybe just a `_WIN32` block picking a different format or something more general to sanitize filenames).
