### ISSUE TITLE
Error SignedCertificateTimestampList undeclared

### ISSUE THREAD

**Issue by andreysfc** [zeek/zeek#1253]
Try to compile from branch master:

```
[ 37%] [BINPAC] Processing x509-extension.pac
/tmp/zeek/src/file_analysis/analyzer/x509/x509-extension.pac:27: error : `SignedCertificateTimestampList' undeclared
make[3]: *** [src/file_analysis/analyzer/x509/CMakeFiles/pac-file_analysis-analyzer-x509-x509-extension.pac.dir/build.make:87: src/file_analysis/analyzer/x509/x509-extension_pac.h] Error 1
make[3]: Leaving directory '/tmp/zeek/build'
make[2]: *** [CMakeFiles/Makefile2:11802: src/file_analysis/analyzer/x509/CMakeFiles/pac-file_analysis-analyzer-x509-x509-extension.pac.dir/all] Error 2
make[2]: Leaving directory '/tmp/zeek/build'
make[1]: *** [Makefile:171: all] Error 2
make[1]: Leaving directory '/tmp/zeek/build'
make: *** [Makefile:15: all] Error 2
```   

I had libssl installed.

**Comment by jsiwek** [comment]
The file it's failing on has a `%include x509-signed_certificate_timestamp.pac` that should provide the declaration of `SignedCertificateTimestampList` and I also notice that file is a symlink:

 ```
src/file_analysis/analyzer/x509/x509-signed_certificate_timestamp.pac -> ../../../analyzer/protocol/ssl/tls-handshake-signed_certificate_timestamp.pac
```

Don't have any idea on what could have went wrong with that, but first may want to verify the symlink is correct and points to expected file with expected contents: https://github.com/zeek/zeek/blob/218c24f55b02eb2f9debf1295ea38d8c2226d56e/src/analyzer/protocol/ssl/tls-handshake-signed_certificate_timestamp.pac

And/or see if a fresh git clone fixes the issue.  If it persists, information about what platform you're building on could help reproduce/confirm what BinPAC is doing wrong with that `%include`.

**Comment by andreysfc** [comment]
Thank you, probably my environment. I will try to pull it again. As for now I'll stick with the release version.
