### ISSUE TITLE
Monitoring multiple network cards at the same time，without logging

### ISSUE THREAD

**Issue by AspirePig** [zeek/zeek#1272]
When I try to monitor four network cards at the same time, I use my VPS to scan the directory of the service. I find that the number of Conn logs recorded is much less than that generated by only one network card. The traffic of the other three network cards is not big。 And there are a lot of server resources
cpu： 24 core
Memory：64GB
zeek version：v3.0.3

**Comment by 0xxon** [comment]
Hi,

We don't use GitHub issues for support questions. Questions like this are best answered using on either slack or our mailing list, which is both are frequented by Zeek developers and professional users. You can join here:

Mailing list: https://lists.zeek.org/mailman3/lists/zeek.lists.zeek.org/

Slack: https://zeek.org/community/

 Johanna
