### ISSUE TITLE
error with addition/subtraction using double and queue

### ISSUE THREAD

**Issue by saiiman** [zeek/zeek#1273]
While writing a slightly larger Zeek script I noticed a strange error in the addition/subtraction of double values.
If I convert two time variables to double and try to calculate them I get the value `0.0`. If I add another `0.0` to the calculation I get the correct value. If I add an integer value, e.g. a `1` I get the warning message: *"internal warning in <no location>: bad request for InternalUnsigned (1602838419.45033)"* (see script one).
Because I want to do different aggregations in my script I need the queue. Without it (see second script) I get the expected results.

**To reproduce the error execute the following script under try.zeek.org version 3.2.0.**
Script 1
```
@load base/protocols/http
@load base/utils/queue.zeek

export {
	type parameter: table[string] of any;
}

event zeek_init() {
	
	local connections: table[string] of Queue::Queue &read_expire=30min;
	local series = Queue::init(Queue::Settings($max_len=5));
	
	local foo = parameter(
		["timestamp"] = double_to_time(1602838419.45033),
		["size"] = 0
	);
	local bar = parameter(
		["timestamp"] = double_to_time(1602838100.45033),
		["size"] = 0
	);
	
	Queue::put(series, foo);
	Queue::put(series, bar);
	connections["abc"] = series;
	
	local values: vector of table[string] of any;
	local c: double = 0.0;

	Queue::get_vector(connections["abc"], values);

	print(values[0]["timestamp"]);
	print(values[1]["timestamp"]);
	print(type_name(values[0]["timestamp"]));
	print(type_name(values[1]["timestamp"]));
	local a = (|values[0]["timestamp"]|);
	local b = (|values[1]["timestamp"]|);
	print(a);
	print(b);
	print(type_name(a));
	print(type_name(b));
	
	print("** result **");
	c = 0.0 + a + b;
	print(c);
	#c = 1 + a + b;
	#print(c);
	c = a + b;
	print(c);
	print(type_name(c));
}
```
Output
```
1602838419.45033
1602838100.45033
time
time
1602838419.45033
1602838100.45033
double
double
** result **
3.205677e+09
0.0
double
```

Script 2
```
event zeek_init() {
	
	local connections: table[string] of time;
	
	connections["foo"] = double_to_time(1602838419.45033);
	connections["bar"] = double_to_time(16028384100.45033);
	
	local c: double = 0.0;

	print(connections["foo"]);
	print(connections["bar"]);
	print(type_name(connections["foo"]));
	print(type_name(connections["bar"]));
	local a = (|connections["foo"]|);
	local b = (|connections["bar"]|);
	print(a);
	print(b);
	print(type_name(a));
	print(type_name(b));
	
        print("** result **");
	c = 1000000000.0 + a + b;
	print(c);
	c = 1000000000 + a + b;
	print(c);
	c = a + b;
	print(c);
	print(type_name(c));
}
```
Output
```
1602838419.45033
1602838100.45033
time
time
1602838419.45033
1602838100.45033
double
double
** result **
4.205677e+09
4.205677e+09
3.205677e+09
double
```

**Comment by jsiwek** [comment]
A simplified example:

```zeek
local a: any = double_to_time(13.0);
local aa = |a|;
print a, type_name(a);
print aa, type_name(aa);
print 1 + aa;
```
```
13.0, time
13.0, double
internal warning in <no location>: bad request for InternalUnsigned (13.0)
1
```

A size expression, like `|a|`, is supposed to only ever return a `count` or `double` type, but for sure seems to have a bug in thinking that operating on an `any` type, like it is here, will yield a `count` (the `time` value here is supposed to turn into a `double`) and likely ends up bypassing type-checking/promotion logic that would normally be expected in the later arithmetic.

The bug can get fixed in a way that may make the insufficient typing of `any` more obvious (it will emit an error message at parse-time rather than run-time), but regardless, think your code will need to explicitly type-cast the `any` values at some point.  This is the way I'd change your example:

```zeek
local a = |values[0]["timestamp"] as time|;
local b = |values[1]["timestamp"] as time|;
```

**Comment by saiiman** [comment]
wow, that was fast. Thanks for the feedback and the merge. :smile:
