### ISSUE TITLE
Add filtered field for packet source stats

### ISSUE THREAD

**Issue by sethhall** [zeek/zeek#1280]
Right now there isn't a field for packets that were filtered from packet sources and all of the packet sources seem to not know what to do with the number of filtered packets so most just don't report them anywhere.  I think we could have filtered bytes as a metric for some packet sources as well so we might want to add that as well.

**Comment by rsmmr** [comment]
Could make it optional. But maybe this would be better reported through the new metrics API now, depending where we're going with existing stats in general.

**Comment by timwoj** [comment]
> For example, while you can set a filter on a pcap source, you can't get the number of packets filtered back from libpcap.
