### ISSUE TITLE
SMB: missing detection of files with multichannel feature enabled

### ISSUE THREAD

**Issue by alessio-pascolini** [zeek/zeek#1286]
When smb multichannel feature is enabled zeek does not generate smb_files.log, SMB::FileInfo record doesn't contain any value.
The two attached pcap contain almost the same traffic, ransomware-like activity on the same files.

[multichannel.pcap.zip](https://github.com/zeek/zeek/files/5531432/multichannel.pcap.zip)
[no_multichannel.pcap.zip](https://github.com/zeek/zeek/files/5531433/no_multichannel.pcap.zip)

```
@load base/protocols/smb

event smb2_message (c: connection, hdr: SMB2::Header, is_orig: bool)
  {
    print fmt("################# SMB ####################");
    print fmt("command: %s", c$smb_state$current_cmd$command);
    
    if ( c$smb_state?$current_file )
    print "############ CURRENT FILE ################";
    {
      if ( c$smb_state$current_file?$fuid )
        print fmt("fuid: %s", c$smb_state$current_file$fuid);

      if ( c$smb_state$current_file?$path )
        print fmt("path: %s", c$smb_state$current_file$path);

      if ( c$smb_state$current_file?$name )
        print fmt("name: %s", c$smb_state$current_file$name);

      if ( c$smb_state$current_file?$size )
        print fmt("size: %s", c$smb_state$current_file$size);

      if ( c$smb_state$current_file?$action )
        print fmt("action: %s", c$smb_state$current_file$action);
    }
  }
```
diff of output

![diff_multichannel](https://user-images.githubusercontent.com/8447823/98957487-89154680-2501-11eb-9b27-5b8be05d01c6.png)

The result is the same with 3.0.11 and 3.2.2.

**Comment by JustinAzoff** [comment]
That should also fix #956  It looks like the pcaps uploaded in #1286 show the behavior I have been trying to find for a year and a half.

**Comment by grigorescu** [comment]
This is fixed in the branch topic/vlad/gh-1286.

@alessio-pascolini I'd like to add multichannel.pcap to our test suite, to ensure that we support SMB multichannel and to avoid regressions. Is that OK?

**Comment by alessio-pascolini** [comment]
It's fine for me, there are no sensitive data.
Thanks @grigorescu
