### ISSUE TITLE
Improved regex for SMTP parsing of split_mime_email_addresses()

### ISSUE THREAD

**Issue by jsiwek** [zeek/zeek#1304]
Original test case reported from #1258:

```
$ cat test.zeek
local s = "\"Smith, John\" <john.smith@email.com>, \"Doe, Jane\" <jane.doe@email.com>";
print split_mime_email_addresses(s);

$ zeek test.zeek
{
Jane" <jane.doe@email.com>,
"Smith, John" <john.smith@email.com>,
"Doe
}
```

The patch from #1258 got reverted in #1301 since there were some external test baseline changes (not sure if they're actual problems or just forgot to review them / didn't have time to do that in lieu of just doing a revert).

**Comment by timwoj** [comment]
@theavgjojo is working on this one in https://github.com/zeek/zeek/pull/2221
