### ISSUE TITLE
ssl_encrypted_data events not being raised for wolfSSL TLSv1.3 connections

### ISSUE THREAD

**Issue by Chukudubem** [zeek/zeek#1323]
Using wolfSSL, **ssl_encrypted_data()** events are not raised for TLSv1.3 sessions. 

Here is a script to reproduce this bug:
```
redef SSL::disable_analyzer_after_detection = F;

event ssl_encrypted_data(c: connection, is_orig: bool, record_version: count, content_type: count, length: count) {
  print "found a record", length;
}
```

Using this [tlsv13.zip](https://github.com/zeek/zeek/files/5662347/tlsv13.zip), Zeek recognizes the connection but there's no print output. TLSv1.2 sessions via wolfSSL perform as expected. (See below)

Output of the script when run on [tlsv12.zip](https://github.com/zeek/zeek/files/5662376/tlsv12.zip):
```
$ zeek -Cr stream_7.pcap test.zeek 
found a record, 96
found a record, 96
found a record, 176
``` 

@0xxon

**Comment by 0xxon** [comment]
Hi,

thanks a lot for the bug report. As a first question even before looking at this closely - would it be ok to publish your pcap file (tlsv13.zip) as part of the Zeek test suite?

Thank you,
 Johanna

**Comment by Chukudubem** [comment]
Yes, by all means. Go ahead

**Comment by 0xxon** [comment]
The fix for this is in topic/johanna/1323. This was a bit more complex to really fix than I hoped :)
