### ISSUE TITLE
Internal error for lambdas that include uninitialized variables

### ISSUE THREAD

**Issue by vpax** [zeek/zeek#1324]
The appended script crashes on master with
```
internal error: Attempted to clone an id ('j') with no associated value.
```
This is quite similar in spirit to the problem reported in #1055 and addressed in #1065, but clearly the latter did not suffice to find all the problems.

[lambda-bug.zeek.txt](https://github.com/zeek/zeek/files/5662830/lambda-bug.zeek.txt)

**Comment by vpax** [comment]
BTW, maybe let's not bother fixing this, as the problem goes away when using the capture-via-copy semantics that I proposed (and have mostly implemented).  If we accept that change, then this becomes a bug in deprecated functionality.

**Comment by jsiwek** [comment]
Closing this since the example script does at least now print the deprecation warning (while still crashing later): `use of outer identifiers in lambdas without [] captures is deprecated: j`
