### ISSUE TITLE
Improve behavior of Dictionary iterator invalidation

### ISSUE THREAD

**Issue by jsiwek** [zeek/zeek#1328]
The checks of this nature could possibly give a better diagnostic message:

```
zeek: /root/zeek/src/Dict.cc:885: void* zeek::Dictionary::Remove(const void*, int, zeek::detail::hash_t, bool): Assertion `num_iterators == 0 || (cookies && cookies->size() == num_iterators)' failed.
/opt/zeek/share/zeekctl/scripts/run-zeek: line 110: 60902 Aborted                 (core dumped) nohup ${pin_command} $pin_cpu "$myzeek" "$@"
```

Most users won't know what that means or where to look, and our reply is also a fuzzy one: "somewhere, there's a table/set removing an element while iterating, and that's not supported".  Suggest this as a minimal change:

* If there's an interpreter call-stack/location-info when this check is triggered, then emit that to stderr to make it easy for anyone to know where to look when fixing it.

Additional ideas to consider:

* If there's not a noticeable performance impact of enabling the check in release builds, that might be helpful.

* Don't assert/abort the process (at least by default), continue going on after emitting an error message.  Whether things crash immediately or later on both fall under "undefined behavior" -- the best case is things crash immediately and maybe a worst case is that some amount operations are performed on incorrect entries and/or execute script-logic that end up generating misleading logs/output/etc.  (If that's a correct assumption of worst case, I do find it concerning, but it's also already possible due to the assert being a debug-build-only behavior).

If execution is allowed to continue, that means the special cases of altering membership within a loop and immediately breaking out after can work as one may expect/intuit, but would still emit an error as a signal/reminder that it's bordering dangerous territory if not in it already.  Example that current asserts, but could "technically" be allowed to work without issue:

```zeek
local s = set(1, 2, 3);
for ( n in s )
	{
	delete s[n];
	break;
	}
```

Any thoughts on what to do for v4.0 ?
I'd like to do at least the improvement in diagnostic message.

**Comment by timwoj** [comment]
I agree with all of the above to be honest. Having the call stack at a minimum would at least help users track down what they did wrong. Looking at the line for the assert, I can't imagine it would have a significant performance impact in release mode. It's basically a couple of lookups and a couple of comparisons.

**Comment by jsiwek** [comment]
Also questionable whether overwriting an existing value in a `table` or the attempt to add a pre-existing key to a `set` is truly a "membership modification" that can ever cause iterator invalidation issues and worth warnings/assertions.  These scripts currently trigger the assertion:

```zeek
local t = table([1] = "one", [2] = "two", [3] = "three");

for ( i in t )
	t[i] = cat(i);
```
```zeek
local s = set(1, 2, 3);

for ( n in s )
	add s[1];
```

The `set` example is contrived, but still both those loops actually do nothing to change the underlying table structure/order such that further iteration is invalid (and not sure any hypothetical Dictionary implementation ever would).
