### ISSUE TITLE
Coverity Scan analysis now failing

### ISSUE THREAD

**Issue by jsiwek** [zeek/zeek#1330]
Coverity tools no longer successfully compile more than 85% of Zeek code, so they disable all coverage.
Can see the "internal error" output from https://github.com/zeek/zeek/runs/1534360629?check_suite_focus=true has many coming from CAF code (maybe there's just more now after updating to CAF 0.18).  I've reported these to Coverity in the past already, so may have to just see if there's any CAF header inclusion to minimize/isolate to get the percentage back up in the short-term.

**Comment by Neverlord** [comment]
Maybe worth a shot: the build uses GCC 7, but Ubuntu 18.04 also has a GCC 8 package. Perhaps the Coverity build makes some more progress using GCC 8?

**Comment by jsiwek** [comment]
Somehow using more recent Ubuntu 20.04/GCC-9 made capture coverage go from 73% to 60%.
I changed it to build CAF separately and got it to 86%, so barely above minimum for now.

Could generally explore other static analysis tools to avoid having to workaround internal Coverity tools errors.  Another failing of the Coverity analysis process is we don't get results until after issues have already been merged into `master` rather than caught during a PR.

Possible alternative may be: https://lgtm.com/projects/g/zeek/zeek/?mode=list

Seems it automatically figured out how to get Zeek dependencies and build it on its own already, which is cool, but I haven't looked yet if there's further configuration tuning or issues with the quality of its reports.  It also has the option of integrating code review/analysis into the PR process.

**Comment by rsmmr** [comment]
LGTM looks cool, would certainly be nice to run this on PRs before merge. On PRs it's also not a problem to reports problems publicly, vs with master or releases where that's a bit dicey. 

But I'd like to keep Coverity as well if we can, it's been quite helpful in the past finding good stuff with little FPs.
