### ISSUE TITLE
zeek installation error-[ 25%] Linking CXX shared module ../../python/broker/_broker.so

### ISSUE THREAD

**Issue by starboy001** [zeek/zeek#1342]
hi, all.
 I suffered an error when installing zeek v3.2.3.OS version is CentOS 7.6, and the error info is as following.
make[3]: Leaving directory '/root/zeek/build'
make[3]: Entering directory '/root/zeek/build'
[ 25%] Building CXX object auxil/broker/bindings/python/CMakeFiles/_broker.dir/_broker.cpp.o
[ 25%] Building CXX object auxil/broker/bindings/python/CMakeFiles/_broker.dir/data.cpp.o
[ 25%] Building CXX object auxil/broker/bindings/python/CMakeFiles/_broker.dir/enums.cpp.o
[ 25%] Building CXX object auxil/broker/bindings/python/CMakeFiles/_broker.dir/store.cpp.o
[ 25%] Building CXX object auxil/broker/bindings/python/CMakeFiles/_broker.dir/zeek.cpp.o
[ 25%] Linking CXX shared module ../../python/broker/_broker.so
/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/ld: /usr/local/lib/python3.6/config-3.6m-x86_64-linux-gnu/libpython3.6m.a(abstract.o): relocation R_X86_64_32S against `.bss' can not be used when making a shared object; recompile with -fPIC
/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/ld: /usr/local/lib/python3.6/config-3.6m-x86_64-linux-gnu/libpython3.6m.a(boolobject.o): relocation R_X86_64_32 against `.text' can not be used when making a shared object; recompile with -fPIC
/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/ld: /usr/local/lib/python3.6/config-3.6m-x86_64-linux-gnu/libpython3.6m.a(bytearrayobject.o): relocation R_X86_64_32 against `.text' can not be used when making a shared object; recompile with -fPIC
/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/ld: /usr/local/lib/python3.6/config-3.6m-x86_64-linux-gnu/libpython3.6m.a(bytesobject.o): relocation R_X86_64_32 against symbol `_PyBytesWriter_Dealloc' can not be used when making a shared object; recompile with -fPIC
/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/ld: /usr/local/lib/python3.6/config-3.6m-x86_64-linux-gnu/libpython3.6m.a(classobject.o): relocation R_X86_64_32 against `.text' can not be used when making a shared object; recompile with -fPIC
/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/ld: /usr/local/lib/python3.6/config-3.6m-x86_64-linux-gnu/libpython3.6m.a(descrobject.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/ld: /usr/local/lib/python3.6/config-3.6m-x86_64-linux-gnu/libpython3.6m.a(exceptions.o): relocation R_X86_64_32S against symbol `_Py_ascii_whitespace' can not be used when making a shared object; recompile with -fPIC
/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/ld: /usr/local/lib/python3.6/config-3.6m-x86_64-linux-gnu/libpython3.6m.a(floatobject.o): relocation R_X86_64_32 against symbol `_PyFloat_Unpack8' can not be used when making a shared object; recompile with -fPIC
/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/ld: /usr/local/lib/python3.6/config-3.6m-x86_64-linux-gnu/libpython3.6m.a(frameobject.o): relocation R_X86_64_32 against symbol `_PyFrame_DebugMallocStats' can not be used when making a shared object; recompile with -fPIC

**Comment by starboy001** [comment]
[root@localhost zeek]# ./configure
Build Directory : build
Source Directory: /root/zeek
-- Performing Test test_arch_x64
-- Performing Test test_arch_x64 - Success
-- Performing Test test_arch_aarch64
-- Performing Test test_arch_aarch64 - Failed
-- Performing Test test_arch_arm
-- Performing Test test_arch_arm - Failed
-- Performing Test test_arch_power
-- Performing Test test_arch_power - Failed
-- Determined target architecture (for hashing): x86_64
-- Found sed: /bin/sed
-- Found PythonInterp: /usr/local/bin/python3 (found version "3.6.5") 
-- Found FLEX: /bin/flex (found version "2.5.37") 
-- Found BISON: /bin/bison  
-- Found PCAP: /usr/lib64/libpcap.so  
-- Performing Test PCAP_LINKS_SOLO
-- Performing Test PCAP_LINKS_SOLO - Success
-- Looking for pcap_get_pfring_id
-- Looking for pcap_get_pfring_id - not found
-- Found OpenSSL: /usr/lib64/libssl.so;/usr/lib64/libcrypto.so (found version "1.0.2k") 
-- Performing Test ns_initparse_works_none
-- Performing Test ns_initparse_works_none - Failed
-- Performing Test res_mkquery_works_none
-- Performing Test res_mkquery_works_none - Failed
-- Performing Test ns_initparse_works_libresolv.a
-- Performing Test ns_initparse_works_libresolv.a - Failed
-- Performing Test res_mkquery_works_libresolv.a
-- Performing Test res_mkquery_works_libresolv.a - Failed
-- Performing Test ns_initparse_works_resolv
-- Performing Test ns_initparse_works_resolv - Success
-- Performing Test res_mkquery_works_resolv
-- Performing Test res_mkquery_works_resolv - Success
-- Found BIND: /usr/lib64/libresolv.so  
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.7") 
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Check size of unsigned int
-- Check size of unsigned int - done

==================|  BinPAC Build Summary  |====================
Version:           0.57.0
SO version:        0

Build Type:        RelWithDebInfo
Debug mode:        false
Install prefix:    /usr/local/zeek
Shared libs:       yes
Static libs:       no

CC:                /opt/rh/devtoolset-7/root/usr/bin/cc
CFLAGS:             -Wall -Wno-unused -O2 -g -DNDEBUG
CXX:               /opt/rh/devtoolset-7/root/usr/bin/c++
CXXFLAGS:           -Wall -Wno-unused -Wno-register -Werror=vla -O2 -g -DNDEBUG
CPP:               /opt/rh/devtoolset-7/root/usr/bin/c++

================================================================

-- Found BinPAC: /root/zeek/build/auxil/binpac/src/./binpac  
-- Performing Test cxx17_already_works
-- Performing Test cxx17_already_works - Failed
-- Performing Test cxx17_works
-- Performing Test cxx17_works - Success

====================|  Bifcl Build Summary  |=====================

Build type:        RelWithDebInfo
Build dir:         /root/zeek/build
Install prefix:    /usr/local/zeek
Debug mode:        false

CC:                /opt/rh/devtoolset-7/root/usr/bin/cc
CFLAGS:             -Wall -Wno-unused -O2 -g -DNDEBUG
CXX:               /opt/rh/devtoolset-7/root/usr/bin/c++
CXXFLAGS:           -Wall -Wno-unused -Wno-register -Werror=vla -std=c++17 -O2 -g -DNDEBUG
CPP:               /opt/rh/devtoolset-7/root/usr/bin/c++

================================================================


=================|  Paraglob Config Summary  |===================
BUILD_TYPE:          RELWITHDEBINFO
CXX_FLAGS:            -Wall -Wno-unused -Wno-register -Werror=vla -std=c++17 -Wall -O2 -g -DNDEBUG
=================================================================

-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Performing Test BROKER_HAS_STD_FILESYSTEM
-- Performing Test BROKER_HAS_STD_FILESYSTEM - Failed
-- Looking for include file emmintrin.h
-- Looking for include file emmintrin.h - found
-- Performing Test atomic64_builtin
-- Performing Test atomic64_builtin - Success
-- Check if the system is big endian
-- Searching 16 bit integer
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Using bundled CAF
-- Performing Test has_64bit_atomic
-- Performing Test has_64bit_atomic - Success
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- Found PythonDev: /usr/local/bin/python3.6-config  
-- Performing Test HAS_LTO_FLAG
-- Performing Test HAS_LTO_FLAG - Success
-- Python bindings will be built and installed to:
--   /usr/local/zeek/lib64/zeek/python

==================|  Broker Config Summary  |====================
Version:         2.1.0-dev.8
SO version:      2

Build Type:      RelWithDebInfo
Install prefix:  /usr/local/zeek
Library prefix:  lib64
Shared libs:     yes
Static libs:     no

CC:              /opt/rh/devtoolset-7/root/usr/bin/cc
CFLAGS:           -Wall -Wno-unused 
CXX:             /opt/rh/devtoolset-7/root/usr/bin/c++
CXXFLAGS:         -Wall -Wno-unused -Wno-register -Werror=vla -std=c++17 

CAF:             /root/zeek/auxil/broker/caf (0.18.0)
RocksDB:         no
Python bindings: yes
Zeek:            /root/zeek/build/zeek-path-dev.sh
=================================================================

-- Could NOT find LibMMDB (missing:  LibMMDB_LIBRARY LibMMDB_INCLUDE_DIR) 
-- Found LibKrb5: /usr/lib64/libkrb5.so  
-- Could NOT find FTS (missing:  FTS_LIBRARY) 
-- Check if the system is big endian
-- Searching 16 bit integer
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Looking for htonll
-- Looking for htonll - not found
-- Check size of long int
-- Check size of long int - done
-- Check size of long long
-- Check size of long long - done
-- Check size of void *
-- Check size of void * - done
-- Check size of int32_t
-- Check size of int32_t - done
-- Check size of u_int32_t
-- Check size of u_int32_t - done
-- Check size of u_int16_t
-- Check size of u_int16_t - done
-- Check size of u_int8_t
-- Check size of u_int8_t - done
-- Check size of socklen_t
-- Check size of socklen_t - done
-- Check size of struct ip6_opt
-- Check size of struct ip6_opt - done
-- Check size of struct ip6_ext
-- Check size of struct ip6_ext - done
-- Looking for include file getopt.h
-- Looking for include file getopt.h - found
-- Looking for include file memory.h
-- Looking for include file memory.h - found
-- Looking for include file netinet/ether.h
-- Looking for include file netinet/ether.h - found
-- Looking for 4 include files sys/socket.h, ..., netinet/if_ether.h
-- Looking for 4 include files sys/socket.h, ..., netinet/if_ether.h - found
-- Looking for 4 include files sys/socket.h, ..., netinet/ip6.h
-- Looking for 4 include files sys/socket.h, ..., netinet/ip6.h - found
-- Looking for 3 include files sys/socket.h, ..., net/ethernet.h
-- Looking for 3 include files sys/socket.h, ..., net/ethernet.h - found
-- Looking for include file sys/ethernet.h
-- Looking for include file sys/ethernet.h - not found
-- Looking for include file net/ethertypes.h
-- Looking for include file net/ethertypes.h - not found
-- Looking for include file sys/time.h
-- Looking for include file sys/time.h - found
-- Looking for include files time.h, sys/time.h
-- Looking for include files time.h, sys/time.h - found
-- Looking for include file os-proto.h
-- Looking for include file os-proto.h - not found
-- Performing Test HAVE_READLINE_HISTORY_ENTRIES
-- Performing Test HAVE_READLINE_HISTORY_ENTRIES - Failed
-- Looking for include files stdio.h, readline/readline.h
-- Looking for include files stdio.h, readline/readline.h - found
-- Looking for include files stdio.h, readline/history.h
-- Looking for include files stdio.h, readline/history.h - found
-- Performing Test SIN_LEN
-- Performing Test SIN_LEN - Failed
-- Looking for IPPROTO_HOPOPTS
-- Looking for IPPROTO_HOPOPTS - found
-- Looking for IPPROTO_IPV6
-- Looking for IPPROTO_IPV6 - found
-- Looking for IPPROTO_IPV4
-- Looking for IPPROTO_IPV4 - not found
-- Looking for IPPROTO_ROUTING
-- Looking for IPPROTO_ROUTING - found
-- Looking for IPPROTO_FRAGMENT
-- Looking for IPPROTO_FRAGMENT - found
-- Looking for IPPROTO_ESP
-- Looking for IPPROTO_ESP - found
-- Looking for IPPROTO_AH
-- Looking for IPPROTO_AH - found
-- Looking for IPPROTO_ICMPV6
-- Looking for IPPROTO_ICMPV6 - found
-- Looking for IPPROTO_NONE
-- Looking for IPPROTO_NONE - found
-- Looking for IPPROTO_DSTOPTS
-- Looking for IPPROTO_DSTOPTS - found
-- Looking for getopt_long
-- Looking for getopt_long - found
-- Looking for mallinfo
-- Looking for mallinfo - found
-- Looking for strcasestr
-- Looking for strcasestr - found
-- Looking for strerror
-- Looking for strerror - found
-- Looking for strsep
-- Looking for strsep - found
-- Looking for sigset
-- Looking for sigset - found
-- Looking for sigaction
-- Looking for sigaction - found
-- Performing Test DO_SOCK_DECL
-- Performing Test DO_SOCK_DECL - Failed
-- Performing Test SYSLOG_INT
-- Performing Test SYSLOG_INT - Failed
-- Looking for include file pcap-int.h
-- Looking for include file pcap-int.h - not found
-- Looking for pcap_freecode
-- Looking for pcap_freecode - found
-- Performing Test LIBPCAP_PCAP_COMPILE_NOPCAP_HAS_ERROR_PARAMETER
-- Performing Test LIBPCAP_PCAP_COMPILE_NOPCAP_HAS_ERROR_PARAMETER - Failed
-- Performing Test LIBPCAP_PCAP_COMPILE_NOPCAP_NO_ERROR_PARAMETER
-- Performing Test LIBPCAP_PCAP_COMPILE_NOPCAP_NO_ERROR_PARAMETER - Success
-- Looking for DLT_PPP_SERIAL
-- Looking for DLT_PPP_SERIAL - found
-- Looking for DLT_NFLOG
-- Looking for DLT_NFLOG - found
-- Performing Test including_ssl_h_works
-- Performing Test including_ssl_h_works - Success
-- Performing Test OPENSSL_D2I_X509_USES_CONST_CHAR
-- Performing Test OPENSSL_D2I_X509_USES_CONST_CHAR - Success
-- Performing Test OPENSSL_CORRECT_VERSION_NUMBER
-- Performing Test OPENSSL_CORRECT_VERSION_NUMBER - Success
-- Performing Test have_nameser_header
-- Performing Test have_nameser_header - Success
-- Looking for kqueue
-- Looking for kqueue - not found

********** Begin libkqueue External Project CMake Output ************

-- Configuring done
-- Generating done
-- Build files have been written to: /root/zeek/build/libkqueue-build

*********** End libkqueue External Project CMake Output *************


-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes

=====================|  ZKG Build Summary  |====================

Install prefix:      /usr/local/zeek
Python module path:  /usr/local/zeek/lib64/zeek/python
Config path:         /usr/local/zeek/etc/zkg
State path:          /usr/local/zeek/var/lib/zkg

================================================================

-- Found SWIG: /bin/swig (found version "2.0.10") 

===============|  PySubnetTree Build Summary  |=================

Install dir:       /usr/local/zeek/lib64/zeek/python
Debug mode:        false

CC:                /opt/rh/devtoolset-7/root/usr/bin/cc
CFLAGS:             -Wall -Wno-unused -O2 -g -DNDEBUG
CXX:               /opt/rh/devtoolset-7/root/usr/bin/c++
CXXFLAGS:           -Wall -Wno-unused -Wno-register -Werror=vla -std=c++17 -O2 -g -DNDEBUG
CPP:               /opt/rh/devtoolset-7/root/usr/bin/c++

================================================================


=================|  capstats Build Summary  |===================

Install prefix:    /usr/local/zeek
Debug mode:        false

CXX:               /opt/rh/devtoolset-7/root/usr/bin/c++
CXXFLAGS:           -Wall -Wno-unused -Wno-register -Werror=vla -std=c++17 -O2 -g -DNDEBUG
CPP:               /opt/rh/devtoolset-7/root/usr/bin/c++

================================================================


=============|  trace-summary Install Summary  |================

Install destination:    /usr/local/zeek/bin

================================================================

-- Could NOT find Zeek (missing:  ZEEK_EXE) 
-- Found SubnetTree: build from source auxil/pysubnettree  

=================|  ZeekControl Install Summary  |===================

Install prefix:    /usr/local/zeek
Zeek root:         /usr/local/zeek
Scripts Dir:       /usr/local/zeek/share/zeek
Spool Dir:         /usr/local/zeek/spool
Log Dir:           /usr/local/zeek/logs
Config File Dir:   /usr/local/zeek/etc
Python Module Dir: /usr/local/zeek/lib64/zeek/python

================================================================


==================|  Zeek-Aux Build Summary  |==================

Install prefix:    /usr/local/zeek
Debug mode:        false

CC:                /opt/rh/devtoolset-7/root/usr/bin/cc
CFLAGS:             -Wall -Wno-unused -O2 -g -DNDEBUG
CXX:               /opt/rh/devtoolset-7/root/usr/bin/c++
CXXFLAGS:           -Wall -Wno-unused -Wno-register -Werror=vla -std=c++17 -O2 -g -DNDEBUG
CPP:               /opt/rh/devtoolset-7/root/usr/bin/c++

================================================================


====================|  ZeekArchiver Build Summary  |====================

Build type:        RelWithDebInfo
Build dir:         /root/zeek/build
Install prefix:    /usr/local/zeek

CXX:               /opt/rh/devtoolset-7/root/usr/bin/c++
CXXFLAGS (base):    -Wall -Wno-unused -Wno-register -Werror=vla -std=c++17 -O2 -g -DNDEBUG
CXXFLAGS (extra):  -std=c++17;-Wall;-Wno-unused;-Werror=vla
================================================================


====================|  Zeek Build Summary  |====================

Build type:        RelWithDebInfo
Build dir:         /root/zeek/build
Install prefix:    /usr/local/zeek
Plugin dir:        /usr/local/zeek/lib64/zeek/plugins
Python module dir: /usr/local/zeek/lib64/zeek/python
Zeek Script Path:  /usr/local/zeek/share/zeek
Debug mode:        false
Unit tests:        

CC:                /opt/rh/devtoolset-7/root/usr/bin/cc
CFLAGS:             -Wall -Wno-unused -O2 -g -DNDEBUG
CXX:               /opt/rh/devtoolset-7/root/usr/bin/c++
CXXFLAGS:           -Wall -Wno-unused -Wno-register -Werror=vla -std=c++17 -O2 -g -DNDEBUG
CPP:               /opt/rh/devtoolset-7/root/usr/bin/c++

ZeekControl:       true
Aux. Tools:        true
zkg:               true

libmaxminddb:      false
Kerberos:          true
gperftools found:  false
        tcmalloc:  false
       debugging:  false
jemalloc:          false

Fuzz Targets:      
Fuzz Engine:       

================================================================

-- Configuring done
-- Generating done
-- Build files have been written to: /root/zeek/build
[root@localhost zeek]#

**Comment by Neverlord** [comment]
Our CI build for CentOS 7 shows:

```
-- Found PythonDev: /usr/bin/python3.6-config
```

Whereas your `configure` output shows:

```
-- Found PythonDev: /usr/local/bin/python3.6-config
```

How did you install Python? Our [Docker image](https://github.com/zeek/zeek/blob/master/ci/centos-7/Dockerfile) installs `python3`, `python3-devel` and `python3-pip`.

**Comment by jsiwek** [comment]
And a preemptive addition: if that Python in `/usr/local/` is compiled from source, then I expect it won't be usable (for this purpose) unless a shared library is built via `./configure --enable-shared` or else told to compile things going into libpython.a with the `-fPIC` flag.

**Comment by starboy001** [comment]
> And a preemptive addition: if that Python in `/usr/local/` is compiled from source, then I expect it won't be usable (for this purpose) unless a shared library is built via `./configure --enable-shared` or else told to compile things going into libpython.a with the `-fPIC` flag.

Thanks very much. I reconfigured the python env with --prefix=/usr/bin --enable-shared. It works now!
