### ISSUE TITLE
BFP Filter don't take effect ,if you set "src" and "dst" keyword

### ISSUE THREAD

**Issue by xiong-liu** [zeek/zeek#1346]
if I redefine **PacketFilter::default_capture_filte = "not net 192.168.10.0/24";** in the local.zeek
![image](https://user-images.githubusercontent.com/51831890/103638188-86762100-4f87-11eb-852c-cf54e5ebcb1d.png)
it take effect!!!
because I only want have destination Ip is 192.168.10.0/24 ,i redefine **redef PacketFilter::default_capture_filter = "dst net 192.168.10.0/24";** 
![image](https://user-images.githubusercontent.com/51831890/103638723-42cfe700-4f88-11eb-8f00-ca2640a9cf30.png)
no effect!!!

zeek-version: 3.0.12
os: centos7.4

Did I understand it wrong?Thanks...

**Comment by 0xxon** [comment]
Hi,

We don't use GitHub issues for support questions. Questions like this are best answered using on either slack or our mailing list, which is both are frequented by Zeek developers and professional users. You can join here:

Mailing list: https://lists.zeek.org/mailman3/lists/zeek.lists.zeek.org/

Slack: https://zeek.org/community/

However, the short answer is that you misunderstand capture filters - they operate on packets, not connections. So - while you will only see packets that are destined to 192.168.10.0/24, Zeek can notice that these packets are part of a connection that was initiated by an IP inside that address block, and will flip the addresses in the connection history (which you see represented by the "^" character in the history column.

In any case - this question is much better suited for the mailing list or slack. 

I hope this helps,
 Johanna
