### ISSUE TITLE
macOS build failure: library not found for -lintl

### ISSUE THREAD

**Issue by jsiwek** [zeek/zeek#1351]
Not sure yet what the source of the issue may be and/or whether it simply warrants documenting in dependency/installation guides, but this was reported a couple times recently:

https://lists.zeek.org/archives/list/zeek@lists.zeek.org/thread/MKSLVRAKB2ZBAZ6A53H5SCPV2HIGEBWD/

> [ 24%] Linking CXX shared module ../../python/broker/_broker.so
> ld: library not found for -lintl

And possible workaround to just install gettext https://zeekorg.slack.com/archives/CSZBXF6TH/p1608828303096700?thread_ts=1608055440.019800&cid=CSZBXF6TH:

> brew install gettext

**Comment by Neverlord** [comment]
> Not sure yet what the source of the issue may be

I had the same issue recently when building Broker. It could be that issue has been fixed upstream, though. CMake calls `python$VERSION-config --ldflags` for assembling all necessary flags to link against the C bindings. The flags returned by the config tool included `-lintl` without `-L/path/to/libintl` that would telll Broker where to actually find the library. Locating the lib via `find` and setting `LDFLAGS` before running `configure` worked around the issue for me.

However, after updating my local packages recently, I can no longer see `-lintl`:

```
$ python3-config --ldflags
-L/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/config-3.9-darwin -ldl -framework CoreFoundation
```

```
$ brew info python
python@3.9: stable 3.9.1 (bottled)
Interpreted, interactive, object-oriented programming language
https://www.python.org/
/usr/local/Cellar/python@3.9/3.9.1_5 (3,932 files, 65.4MB) *
  Poured from bottle on 2021-01-08 at 07:59:13
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/python@3.9.rb
License: Python-2.0
==> Dependencies
Build: pkg-config ✔
Required: gdbm ✔, openssl@1.1 ✔, readline ✔, sqlite ✔, xz ✔
==> Caveats
Python has been installed as
  /usr/local/bin/python3

Unversioned symlinks `python`, `python-config`, `pip` etc. pointing to
`python3`, `python3-config`, `pip3` etc., respectively, have been installed into
  /usr/local/opt/python@3.9/libexec/bin

You can install Python packages with
  pip3 install <package>
They will install into the site-package directory
  /usr/local/lib/python3.9/site-packages

See: https://docs.brew.sh/Homebrew-and-Python
==> Analytics
install: 836,823 (30 days), 2,165,096 (90 days), 2,197,392 (365 days)
install-on-request: 248,356 (30 days), 543,091 (90 days), 543,862 (365 days)
build-error: 0 (30 days)
```

FWIW, Broker/Zeek builds without setting `LDFLAGS` for me again.

**Comment by jsiwek** [comment]
Does seem like this was probably an upstream package issue and haven't heard of this still happening recently.

**Comment by jsoref** [comment]
I tripped on this today.

```
 ./configure --with-openssl=/opt/homebrew/Cellar/openssl@3 --with-bison=/opt/homebrew/Cellar/bison/3.8.2/bin/bison --with-swig=/opt/homebrew/Cellar/swig/4.0.2/bin/swig --with-flex=/opt/homebrew/Cellar/flex/2.6.4_2/bin/flex
```
Base commit is 5aa7d80e8.

```
python3-config --ldflags

-L/Users/jsoref/.pyenv/versions/3.10.1/lib/python3.10/config-3.10-darwin -lintl -ldl -framework CoreFoundation
```

I personally expect `./configure` to tell me everything I need to do and was disappointed to trip on this.
