### ISSUE TITLE
ZEEK SMTP Header Parsing Issue

### ISSUE THREAD

**Issue by sumit240690** [zeek/zeek#1352]
There is an issue with SMTP parsing where header extraction continues parsing into the body and attachments of emails.  A common case which leads this issue to surface appears when emails are sent as attachments.  If you have an attachment that itself is an email, the headers from the attached email will override headers parsed from the actual email.

 This incidentally might be the cause of previously seen issues such as #254.

**Comment by timwoj** [comment]
Do you by chance have a pcap that illustrates it? That would help in tracking down the issue.

**Comment by sumit240690** [comment]
Hi,

We have proposed the following changes as explained in the below PR:

https://github.com/zeek/zeek/pull/1357

Please let us know if you still need pcap ?

Thanks.

**Comment by 0xxon** [comment]
Hi,

thanks for the PR. A pcap actually still would be helpful for reproduction - and for inclusion in the testsuite. Alternatively - it would be great if you could add a testcase to the PR :).

Thank you very much,
 Johanna

**Comment by theavgjojo** [comment]
@0xxon, check out #1365 -- PCAP and test case added.
