### ISSUE TITLE
files extracted problem

### ISSUE THREAD

**Issue by yuyi2017yuyi** [zeek/zeek#1355]
When I extracted files with zeek from a pcap file which included 44 files, I found that only 5 files records in files.log printed correct hash values  . But the same pcap file can be extracted all files correctly with wireshark,  whether this is related to zeek configuration?How should I set it?
[testpcap.zip](https://github.com/zeek/zeek/files/5792317/testpcap.zip)
Thank you for any reply.

**Comment by 0xxon** [comment]
Hi,

you have packet loss in all but 5 files in the pcap - so your connections in the pcap are missing packages. See the missing_bytes column in files.log.

Please also note that we don't use GitHub issues for support questions. Questions like this are best answered using on either slack or our mailing list, which is both are frequented by Zeek developers and professional users. You can join here:

Mailing list: https://lists.zeek.org/mailman3/lists/zeek.lists.zeek.org/

Slack: https://zeek.org/community/

 Johanna
