### ISSUE TITLE
In zeek cluster the logger cannot work normally

### ISSUE THREAD

**Issue by starboy001** [zeek/zeek#1359]
Hi,  I am learning how to monitor interface by zeek cluster. But it only works for a short time when I run "zeekctl deploy". Then I find the log in current folder is unincreasing. When it works in standalone mode, everything is fine. What is the reason? 

[logger-1]
type=logger
host=localhost
#
[manager]
type=manager
host=localhost
#
[proxy-1]
type=proxy
host=localhost
#
[worker-1]
type=worker
host=localhost
interface=eno2
lb_method=pf_ring
lb_procs=8
pin_cpus=0,1,2,3,4,5,6,7

[root@zeek01 current]# zeekctl status
Warning: zeekctl config has changed (run the zeekctl "deploy" command)
Name         Type    Host             Status    Pid    Started
logger-1     logger  localhost        running   14088  11 Jan 20:29:48
manager      manager localhost        running   14143  11 Jan 20:29:49
proxy-1      proxy   localhost        running   14197  11 Jan 20:29:51
worker-1-1   worker  localhost        running   14323  11 Jan 20:29:53
worker-1-2   worker  localhost        running   14341  11 Jan 20:29:53
worker-1-3   worker  localhost        running   14342  11 Jan 20:29:53
worker-1-4   worker  localhost        running   14337  11 Jan 20:29:53
worker-1-5   worker  localhost        running   14344  11 Jan 20:29:53
worker-1-6   worker  localhost        running   14350  11 Jan 20:29:53
worker-1-7   worker  localhost        running   14352  11 Jan 20:29:53
worker-1-8   worker  localhost        running   14351  11 Jan 20:29:53

the cpu usage of logger is zero. is it really normal? 
[root@zeek01 current]# zeekctl top
Warning: zeekctl config has changed (run the zeekctl "deploy" command)
Name         Type    Host             Pid     VSize  Rss  Cpu   Cmd
logger-1     logger  localhost        14088     3G   109M   0%  zeek
manager      manager localhost        14143   659M    80M  11%  zeek
proxy-1      proxy   localhost        14197   657M    78M   0%  zeek
worker-1-1   worker  localhost        14323     4G     4G 111%  zeek
worker-1-2   worker  localhost        14341     4G     4G 105%  zeek
worker-1-3   worker  localhost        14342     4G     4G 105%  zeek
worker-1-4   worker  localhost        14337     4G     4G 111%  zeek
worker-1-5   worker  localhost        14344     4G     4G 105%  zeek
worker-1-6   worker  localhost        14350     4G     4G 111%  zeek
worker-1-7   worker  localhost        14352     4G     4G 105%  zeek
worker-1-8   worker  localhost        14351     4G     4G 105%  zeek

‘zeekctl netstats’ returns timeout after several minutes.  Firewall service has been closed.

**Comment by 0xxon** [comment]
Hi,

We don't use GitHub issues for support questions. Questions like this are best answered using on either slack or our mailing list, which is both are frequented by Zeek developers and professional users. You can join here:

Mailing list: https://lists.zeek.org/mailman3/lists/zeek.lists.zeek.org/

Slack: https://zeek.org/community/

 Johanna
