### ISSUE TITLE
btest missing from Zeek installation

### ISSUE THREAD

**Issue by 0xxon** [zeek/zeek#1360]
After playing around a bit with the zkg installation that we now install together with Zeek, I noticed that packages that have tests are at the moment not installable without it erroring out. The reason for that is that packages typically use btest for their tests - and we don't ship btest together with Zeek. This does not really seem super great from a usability perspective.

I think that, if we install zkg automatically we probably also should install btest into the Zeek path.

**Comment by 0xxon** [comment]
Oh, I forgot - optimally I think this should be addressed in some way before the final 4.0.0 release.

**Comment by ckreibich** [comment]
Yes, agree. I'll get on it. (This reveals a bad habit of mine, namely that I often install packages with `--skiptests` :roll_eyes: ...)
