### ISSUE TITLE
zkg file permission problems in multi-user installations

### ISSUE THREAD

**Issue by 0xxon** [zeek/zeek#1361]
Short version of the following: we might consider setting a umask that allows group-members to write to files that zkg creates.

I just encountered a problem with the bundled zkg in our installation while testing binary packages.

With our binary packages, we currently install everything under the root user (so no one can write to it). Directories containing configuration files and logs are added to the zeek group; in the case of directories we also set the setGid bit to make files/directories that are created in those directories owned by the zeek group. However, the files that zkg creates will (at least on my test systems) end up with the group not being able to write to them. Hence, when two users interact with a system-installed zkg, the operation of the first user will succeed, and the operation of the second  user will fail with the following error messages:

```
$ /opt/zeek-nightly/bin/zkg refresh
PermissionError: [Errno 13] Permission denied: '/opt/zeek-nightly/share/zeek/site/packages/packages.zeek'
error: user does not have write access in /opt/zeek-nightly/lib/zeek/plugins
```

This does not feel entirely optimal to me - I assume that there will be cases in which several different users might interact with a system installation. So - it might make sense to set a different umask for zkg operations - at least when zkg is installed to a system-wide destination (which is, e.g., indicated by the ``--binary-package`` configuration option.

**Comment by 0xxon** [comment]
So - in the package I actually do set ``var/lib/zkg`` group-writeable. As I do with everything that zkg needs to write to.

This leads to the fact that the first user in the ``zeek`` group to use zkg basically "wins" and owns the zkg installation afterwards. Which may actually be acceptable in a lot of cases - but seems a bit... weird.

In my personal opinion, there are two approaches that are both acceptable. The first one is that we have a shared zkg installation. That means that everyone in the zeek group can issue zkg commands - and they basically manipulate data of that installation. Things currently go into that direction - with the exception that, once the first user uses zkg, the insallation is locked to them.

The second approach would be that no data lands in the global installation, but that zkg starts creating data somewhere in the home directory of the user (or at a different location that is user-specific).

**Comment by rsmmr** [comment]
How do we solve this for ZeekControl? That seems to be a very similar situation: global installation with runtime state manipulated by the client-side tool that could potentially be run by different users. Ideally, zkg would be consistent with what we do there.

>  first user in the zeek group to use zkg basically "wins" and owns the zkg installation 

That's certainly not good. But I think there's a 3rd option: given that the installation is owned by root, we could limit write access to root as well. That seems most intuitive to me (modulo the answer for ZeekControl) and also in line with other package managers.

**Comment by 0xxon** [comment]
I checked - and zeekctl does indeed have the same problem (and one additional problem that I never noticed).

In effect - whoever runs zeekctl first also owns that installation at the moment. So - we could indeed just decide that only root can use the zeek installation.

That being said - I still think that is slightly suboptimal - in practice we probably want people to not run Zeek as root :)

**Comment by ckreibich** [comment]
I'd like to try out a few things here and also take your packages for a spin, Johanna — that's long overdue. I'll follow up tomorrow.

**Comment by jsiwek** [comment]
Is https://github.com/zeek/package-manager/pull/91 sufficient for closing this?

**Comment by 0xxon** [comment]
I think I am happy with that as a solution, yes.
