### ISSUE TITLE
CLI script execution hangs

### ISSUE THREAD

**Issue by mavam** [zeek/zeek#1363]
This command line does the right thing, but it hangs indefinitely as opposed to terminating after the print statement. (At least that was the behavior in the past.)

```sh
zeek -e 'event zeek_init() { print "foo\rbar"; }'
```

It's impossible to send SIGINT to the process as well. I also tried `zeek_done` as alternative event, but that's the same behavior.

Tested with `zeek 3.2.2` on macOS Catalina, installed via Homebrew.

**Comment by sethhall** [comment]
It worked fine for me on a recent version of master

```
[seth@Blake build (master)]$ zeek -e 'event zeek_init() { print "hello"; }'
hello
[seth@Blake build (master)]$ zeek -v
zeek version 3.3.0-dev.607-debug
```

**Comment by mavam** [comment]
Just tested master; it's not longer an issue.
