### ISSUE TITLE
ZEEK bridge.

### ISSUE THREAD

**Issue by MbackeMbengue** [zeek/zeek#1373]
Hello people,

Here is my issue : 
I want to install two machines with a bridge in the middle. On this bridge, I want to put Zeek to raise an alert when Zeek sees passing a given URL which will be chosen (see the diagram)
[Schema.pdf](https://github.com/zeek/zeek/files/5852602/Schema.pdf)
. I want to do these operations with Virtualbox. I already have an OVA file which contains the 3 machines, with Debian 10 on them. I already installed the web server (Apache). Once I install Zeek on one of the machines, I don't know how to configure the bridge. Any help please ? 

Thx

**Comment by timwoj** [comment]
I'm sorry, but we don't use GitHub issues for support questions. Questions like this are best answered using on either slack or our mailing list, which is both are frequented by Zeek developers and professional users. You can join here:

Mailing list: https://lists.zeek.org/mailman3/lists/zeek.lists.zeek.org/

Slack: https://zeek.org/community/

**Comment by MbackeMbengue** [comment]
Oh I did not know. I'm completely new with this.

Thank you for your help.
