### ISSUE TITLE
Documentation discrepancy for binary packages

### ISSUE THREAD

**Issue by scuba-st3v3** [zeek/zeek#1374]
I noticed the spec file within the [CentOS 7 src rpm](https://software.opensuse.org//download.html?project=security%3Azeek&package=zeek) by default actually has file ownership as root and the zeek group which conflicts with the documentation.  In my own testing, I validated that my CentOS 7 system had a zeek group created but not a zeek user.

Location: https://github.com/zeek/zeek/wiki/Binary-Packages
`All packages are installed into /opt/zeek. A user and a group named zeek are added to the system, if they do not already exist. Users that are part of the zeek group can edit configuration files and view the Zeek log files.`

I am not sure if the documentation needs updated to reflect reality or the spec file used in the binary packages needs updated.

**Comment by 0xxon** [comment]
Ah, that's me being bad. Let me update that.

**Comment by 0xxon** [comment]
I changed this to only talk about the Zeek group. Thanks a lot again :)
