### ISSUE TITLE
Zkg RPM missing python 3 dependencies on CentOS 7

### ISSUE THREAD

**Issue by antcodd** [zeek/zeek#1382]
The Zeek 4.0 RC2 zkg RPM zeek-rc-zkg and zeek-nightly-zkg do not install easily on CentOS 7 due to missing python dependencies when using standard repositories plus EPEL.

It looks like EPEL only packages the python 2 version of python-semantic_version and python-GitPython. Perhaps zkg should be built against python 2 on that platform if that is still possible?

Note that zeek-rc/zeek-nightly depend on zkg.

Workaround: install zeek packages other than zkg individually, then install zkg using pip3

```
# yum install zeek-rc-zkg
...
Resolving Dependencies
--> Running transaction check
---> Package zeek-rc-zkg.x86_64 0:4.0.0-7.1 will be installed
--> Processing Dependency: zeek-rc-btest = 4.0.0 for package: zeek-rc-zkg-4.0.0-7.1.x86_64
--> Processing Dependency: python3-semantic_version for package: zeek-rc-zkg-4.0.0-7.1.x86_64
--> Processing Dependency: python3-GitPython for package: zeek-rc-zkg-4.0.0-7.1.x86_64
--> Running transaction check
---> Package zeek-rc-btest.x86_64 0:4.0.0-7.1 will be installed
---> Package zeek-rc-zkg.x86_64 0:4.0.0-7.1 will be installed
--> Processing Dependency: python3-semantic_version for package: zeek-rc-zkg-4.0.0-7.1.x86_64
--> Processing Dependency: python3-GitPython for package: zeek-rc-zkg-4.0.0-7.1.x86_64
--> Finished Dependency Resolution
Error: Package: zeek-rc-zkg-4.0.0-7.1.x86_64 (security_zeek)
           Requires: python3-semantic_version
Error: Package: zeek-rc-zkg-4.0.0-7.1.x86_64 (security_zeek)
           Requires: python3-GitPython
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

**Comment by 0xxon** [comment]
Well, that sucks a bit.

The only thing I can do here is to remove the dependency on semantic_version and gitpython for CentOs 7.

Zeek no longer supports python2 - this includes zkg. So changing the dependency to python2 is not an option.

I will change the configuration and start a rebuild of zeek-rc - and comment here when that is done.

**Comment by 0xxon** [comment]
I think this should be fixed - and the dependency removed. Could you test this again? :)

**Comment by antcodd** [comment]
Thanks,

Yes this appears to "work" in the sense that zkg now prints a friendly message about installing the dependencies using pip when you try to run it. I suppose the benefit of having an rpm version is it is pre-configured without needing to use autoconfig?

```
/opt/zeek-rc/bin/zkg --help
error: zkg failed to import one or more dependencies:

* GitPython:        https://pypi.org/project/GitPython
* semantic-version: https://pypi.org/project/semantic-version

If you use 'pip', they can be installed like:

     pip3 install GitPython semantic-version
```

This isn't ideal but may be a reasonable compromise. Perhaps the rpm postinstall should print a similar message as it effectively isn't installed properly out of the box (having it run pip is probably a bad idea)? I guess the other option would be to make zeek-rc not depend on zkg on CentOS 7 and have people install it using pip.

**Comment by 0xxon** [comment]
Yup, I definitely don't want it to run pip automatically - that's too much messing with the system.

I don't like the idea of making zeek-rc not depend on zkg on centos 7 - just because it feels weird to have different dependencies on different OS versions. But - let me look in the postinstall message.

**Comment by 0xxon** [comment]
After looking at this a bit, I did not really see an obvious way to cleanly output a message on RPM installation that I liked.

I am happy for pointers - but I honestly think that the current error output upon first start of zkg is good enough.
