### ISSUE TITLE
sort() BiF comparison functions lack checking for correct number of arguments

### ISSUE THREAD

**Issue by vpax** [zeek/zeek#1387]
The type-checking for the optional comparison function passed to the `sort()` BiF doesn't ensure it takes the proper number of arguments.  The following leads to a segmentation fault:

> function myfunc1(a: addr): int
	{
	return 0;
	}
event zeek_init()
	{
	local c1: vector of addr = vector( 192.168.123.200, 10.0.0.157, 192.168.0.3 );
	print sort(c1, myfunc1);
	}

I discovered this while reworking the BiF in the context of changing the internal representation of vectors, so will include a fix for this in that MR.

**Comment by timwoj** [comment]
This appears to be fixed on master. @vpax Can you confirm that a change went in for this?

**Comment by vpax** [comment]
Yes, it was fixed as part of 13e7ba3a00f133323c12c3a50b4bfe884e32c9bf.
