### ISSUE TITLE
Unable to open database file state.db

### ISSUE THREAD

**Issue by ikramchch** [zeek/zeek#1395]
![image](https://user-images.githubusercontent.com/23656204/107283708-0bf46180-6a5d-11eb-9359-465c9bb36058.png)

**Comment by 0xxon** [comment]
Hi,

We don't use GitHub issues for support questions. Questions like this are best answered using our  mailing list, which is followed by Zeek developers and professional users. You can join here:

https://lists.zeek.org/mailman3/lists/zeek.lists.zeek.org/

Once you receive confirmation you’ve been added to the list, send this question there.

 Johanna
