### ISSUE TITLE
error: zkg failed to import one or more dependencies:

### ISSUE THREAD

**Issue by yurstrulymahesh** [zeek/zeek#1396]
Hi all,

I have installed Zeek, python3, gitpython, semantic-version and zkg.
And facing the below issue on executing "zkg autoconfig":

[root@Remote ~]# zkg autoconfig
error: zkg failed to import one or more dependencies:

* GitPython:        https://pypi.org/project/GitPython
* semantic-version: https://pypi.org/project/semantic-version

If you use 'pip', they can be installed like:
pip3 install GitPython semantic-version

Can someone please help me out in fixing this.
Thank you.

**Comment by ckreibich** [comment]
Hi there,

We don't use GitHub issues for support questions, but we're happy to help out on Slack or our mailing list. Details are here: https://zeek.org/community/

Thanks!
Christian
