### ISSUE TITLE
Test failures on Apple M1 (arm64)

### ISSUE THREAD

**Issue by jsiwek** [zeek/zeek#1406]
These tests fail on Apple M1 (arm64), reporting a change in file UID:
* scripts.base.protocols.smb.smb2
* scripts.base.protocols.smb.smb2-read-write
* scripts.policy.frameworks.intel.seen.smb

File UIDs for files seen over SMB are partially derived from SMB timestamp data:

https://github.com/zeek/zeek/blob/023bed5299a8eff5969f2317fb3e81e51121a4f4/scripts/base/protocols/smb/files.zeek#L28

The conversion from NT-timestamp (100-nanosec intervals since year 1601) to Unix-timestamp relies on intermediate `long double` operations before storing back to `double`:

https://github.com/zeek/zeek/blob/023bed5299a8eff5969f2317fb3e81e51121a4f4/src/analyzer/protocol/smb/smb-time.pac#L14

The precision of `long double` varies across platforms, x86 is usually 80-bit extended, standard arm64 is 128-bit quad, and [Apple arm64 is actually a synonym for 64-bit double](https://developer.apple.com/documentation/xcode/writing_arm64_code_for_apple_platforms).  This can lead to platform-dependent rounding variation that ultimately change the file UID.

Standardizing the calculation to use 64-bit doubles could solve the variation, but it potentially picks a less accurate rounding than the `long double` calculation would and, same as before, sub-microsecond precision is simply degraded with recent/future timestamps because 64-bit `double` does not have enough precision to represent those times.

Suggested fix: use a different storage type for Zeek `time`/`interval` values.  Another use-case for this change is mentioned in https://github.com/zeek/zeek/discussions/1163: supporting nanosecond-timestamps obtained from pcap files would also need this change (among others).

An initial thought is to simply use a single `uint64_t` for `time` (absolute nanoseconds since Unix epoch, allows range of year 2555) and `int64_t` for `interval` (relative nanoseconds, allows 292 year range).  Would those ranges be sufficient ?  Any special considerations for potential script-breakage due to change in range/limit ?

**Comment by rsmmr** [comment]
I'm going to take a look at that, at least to get tests to pass on M1s.
