### ISSUE TITLE
Idea: expose Zeek performance metrics to Broker for scraping via Prometheus

### ISSUE THREAD

**Issue by Neverlord** [zeek/zeek#1408]
Recent Broker versions build on CAF 0.18, which includes support for runtime metrics and can expose them to [Prometheus](https://prometheus.io). On the Broker side, https://github.com/zeek/broker/pull/175 allows users now to spin up the metrics exposition via the environment variable `BROKER_METRICS_PORT`. @timwoj already used a pre-version of that patch to look into Zeek performance with Grafana for the RC2 performance issues.

Feeding performance metrics from Zeek into the backend would give developers, testers and operators access to all-things-performance in one place. @sethhall also mentioned we could (should?) add new BIFs to allow scripts to extend the metrics as well.

Zeek currently has no access to metrics. They are a CAF feature and the metrics registry is part of the actor system. So there are two ways to go about this.

1. We could just expose the actor system from the `broker_mgr`. So far we've avoided tying Zeek directly to CAF APIs, so I have a feeling that's not a preferred solution. 🙂
2. We could wrap the metrics with an opaque Broker or Zeek API and have the `broker_mgr` act as a factory. In code, this would look somewhat like this:
```cpp
// Gauges are available as int64_t and double versions.
auto num_conns = broker_mgr->int_gauge_singleton("zeek", "num-connections", "number of open connections");
// ... when seeing new TCP connections
num_conns.inc();
// ... when seeing FIN
num_conns.dec();

// Option 2.a: Just "hide" the CAF names.
namespace broker { using int_gauge = caf::telemetry::int_gauge; }

// Option 2.b: Hide the CAF internals with a Broker API.
namespace broker {
class int_gauge {
public:
  void inc() noexcept;
  void dec() noexcept;
private:
  void* handle; // needs to cast back to the original type
};
} // namespace broker

// Option 2.c: Completely hide Broker and CAF internals in Zeek.
namespace zeek {
class int_gauge { /* ... similar to 2.b ... */ };
} // namespace zeek
```

A note on the lifetime of the metric objects: once created, CAF stores them in a registry and the pointers to metrics remain valid until the actor system gets destroyed. For Zeek, this would mean the metrics "live" for as long as the Broker Manager lives.

**Comment by grigorescu** [comment]
Yes, please!

We run https://github.com/esnet/zeek-exporter everywhere and it's invaluable for both advanced testing as well as LTS deployments. It's also great for evaluating the impact of scripts and plugins.

We've even seen benefit helping others debug performance issues, where they don't need to run a Prometheus instance. Simply being able to run Zeek for a few minutes, then query the stats has shown problem areas.

**Comment by jsiwek** [comment]
I'd suggest route (2) and also the general idea of (2.a) seems like it may be simplest/adequate for now, but may want to put type-aliases/functions into a `zeek::telemetry` namespace -- the fact they'll currently be implemented via `broker_mgr`->CAF details seems coincidental rather than conceptual.

**Comment by rsmmr** [comment]
Yeah, that sounds good to me too: Wrap the CAF functions from a Zeek namespace, then put a set of BiFs on top to expose the script-land too.

**Comment by rsmmr** [comment]
We got the PR with the BiFs. The next step is a new telemetry framework, which is more likely a 4.2 target, but we'll see.
