### ISSUE TITLE
Telnet analyzer doesn't trigger relevant events after successfully registered for 23/tcp port

### ISSUE THREAD

**Issue by maofeichen** [zeek/zeek#1420]
Hello all, 

I tried to analyze a telnet session via zeek's telnet analyzer. And as the docs mentioned in [Zeek::Login](https://docs.zeek.org/en/lts/script-reference/proto-analyzers.html#id45), zeek doesn't activate the analyzer by default:
> Zeek’s current default configuration does not activate the protocol analyzer that generates this event; the corresponding script has not yet been ported. To still enable this event, one needs to register a port for it or add a DPD payload signature.

So I registered the 23/tcp port for telnet, and enable the telnet analyzer, but the script running result didn't trigger any telnet events. 

My script setup: under a `telnet` script directory there are 2 zeek scripts:
* \_\_load\_\_.zeek:
~~~bro
@load tuning/json-logs
@load ./main
~~~
* main.zeek:
~~~bro
# Disable all available analyzers initially
redef Analyzer::disable_all=T;

global tel_ports: set[port] = {23/tcp} &redef;

event zeek_init() &priority=5
{
    if (Analyzer::register_for_ports(Analyzer::ANALYZER_TELNET, tel_ports) ) {
        print "register telnet";
        if (Analyzer::enable_analyzer(Analyzer::ANALYZER_TELNET) ){
            print "enable telnet analyzer";
        } 
    }
}

## test trigger telnet events
event login_failure(c: connection, user: string, client_user: string, password: string, line: string)
{
    print "e login_fail";
}

event login_success(c: connection, user: string, client_user: string, password: string, line: string)
{
    print "e login_succ";
}

event login_input_line(c: connection, line: string)
{
    print "input line";
}

event login_output_line(c: connection, line: string)
{
    print "output line";
}

event login_terminal(c: connection, terminal: string)
{
    print "login terminal";
}
~~~

I put several events according to docs after zeek_init(), and I suppose those events should be triggered if the telnet analyzer is enabled correctly. 

The script running result:
* zeek version: 3.0.12
* sample pcap: [wireshark sample telnet](https://wiki.wireshark.org/SampleCaptures#Telnet)
* zeek cmd: 
    `$ zeek -Cr telnet-cooked.pcap ../../script/telnet/`
* zeek result:
```bash
register telnet
enable telnet analyzer
```
The result only print out statements in zeek_info(). It seems to me that the script enabled the telnet analyzer successfully, but none of the relevant events had been triggered. I wonder what's the issue?

Thanks and appreciate your help!

**Comment by maofeichen** [comment]
Hello all, 

I figured out the issue was due to the statement in the script:
~~~bro
redef Analyzer::disable_all=T;
~~~
which disables all analyzers initially. If I comment it out, then the script was able to trigger relevant events, and can print out those "print" statement info in the script, such as:
~~~
output line
input line
login confused
...
~~~
So I assume that there are several fundamental analyzers that must to be turn on before analyzing the telnet protocol, I wonder what those analyzers are so I can activate them manually in the script. 

Thanks!

**Comment by 0xxon** [comment]
Hi,

you should be able to figure this out by building a debug build of Zeek, and running it with ``-B dbd``. This will output a (rather verbose) debug.log which will show you which analyzers are attached when.

For telnet, you might just need TCP.

Closing this, since it is not actually a bug in Zeek.
