### ISSUE TITLE
if create_master fails to open the database, zeek aborts.

### ISSUE THREAD

**Issue by JustinAzoff** [zeek/zeek#1426]
if create_master fails to initialize the database, zeek aborts with a rather generic error

this is the minimal example:

```
event zeek_init()
{
    Broker::create_master("/cant/write/here/db", Broker::SQLITE);
}
```

here is one more fleshed out.

```
justin@mbp:/tmp$ cat sqlite_broken.zeek
redef exit_only_after_terminate=T;
global tablestore: opaque of Broker::Store;


event zeek_init()
{
    tablestore = Broker::create_master("/cant/write/here/db", Broker::SQLITE);
    print "Querying";
    when ( local res = Broker::get(tablestore, "hi")) {
        print res;
        terminate();
    } timeout 30sec {
        print "timeout";
        terminate();
    }
}
justin@mbp:/tmp$ zeek sqlite_broken.zeek
[failed to get master expiries while initializing
broker/ERROR] Abort trap: 6
justin@mbp:/tmp$
```

A fatal reporter error in this case is probably ok.. but it should be something more along the lines of

```
Error: unable to open database "/cant/write/here/db.sqlite": unable to open database file
```

which is what sqlite would return. (sqlite is also somewhat poor in this area, since it says that regardless of what the error is)

**Comment by JustinAzoff** [comment]
thinking about this more, it should not be a fatal error either. that matches the behavior of Input::add_table

As long as all the Broker::get() can just return an error that the store isn't initialized zeek should be able to keep running.

**Comment by jsiwek** [comment]
What Zeek version?  With 4.0+, looks like you'll at least get this non-fatal error:

```
error in test.zeek, line 3: Failed to attach master store caf::sec::runtime_error("std.filesystem.__cxx11.filesystem_error", "filesystemerror: cannot create directories: Permission denied [/cant/write/here/]"): (Broker::create_master(/cant/write/here/db, Broker::SQLITE, (coerce [] to Broker::BackendOptions)))
error in test.zeek, line 3: Could not create Broker master store '/cant/write/here/db' (Broker::create_master(/cant/write/here/db, Broker::SQLITE, (coerce [] to Broker::BackendOptions)))
warning: non-void function returning without a value: Broker::create_master
*** unhandled exception: [id: 7, name: core, exception typeid: std.filesystem.__cxx11.filesystem_error]: filesystem error: cannot create directories: Permission denied [/cant/write/here/]
```

A bit verbose, but probably most can figure out what it means.  The warning about "non-void function returning without a value" is maybe still problematic since it's not straightforward to tell if the `create_master()` call worked and it causes "value used but not set" runtime-errors in subsequent uses like a `Broker::get()`, so think that's worth improving (can currently workaround by stuffing return value into your own custom `&optional` record field and doing `?$` checks).

**Comment by jsiwek** [comment]
Actually, the way it was (not) handling exceptions only made it appear to be non-fatal, but it was basically still broken, so don't rely on anything I said before.  #1429 is that fix I came up with.

**Comment by JustinAzoff** [comment]
Weird.. I was on 4.0.0 but I bet I accidentally built against an older installed version of caf in /usr/local
