### ISSUE TITLE
netbios wildcard queries are logged with null padding.

### ISSUE THREAD

**Issue by JustinAzoff** [zeek/zeek#1442]
[netbios_nulls.zip](https://github.com/zeek/zeek/files/6135813/netbios_nulls.zip)

This pcap has one of the netbios queries that ends up getting logged with a bunch of padded null bytes.  This has been the case for a while, but I think these should just be logged as `*`

```
$ zeek -r ~/netbios_nulls.pcap 
$ cat dns.log |zeek-cut query
*\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00
```

**Comment by jsiwek** [comment]
This is now fixed in `master` via #1533
