### ISSUE TITLE
Possible issue in ICMP analyzer

### ISSUE THREAD

**Issue by timwoj** [zeek/zeek#1456]
I discovered this while working on moving the ICMP analyzer to a packet analyzer. This issue is just to document it so it doesn't get lost.

The ICMP analyzer contains two values, `request_len` and `reply_len`, that are used to switch one of the endpoint record's values between active and inactive:

https://github.com/zeek/zeek/blob/8fb30f1d6280d0298d338a304aad4c60278348b7/src/analyzer/protocol/icmp/ICMP.cc#L470-L484

The problem is that `request_len` and `reply_len` are never actually set to a useful value anywhere. They're set to `-1` by the constructor, but never reset after that. It looks like the code has been this way at least since we imported it to GitHub, if not longer. I also tested marking those variables as private to rule out them getting set by something else and the code still builds.

**Comment by jsiwek** [comment]
Think the following code in `DeliverPacket()` updates them ?

https://github.com/zeek/zeek/blob/8fb30f1d6280d0298d338a304aad4c60278348b7/src/analyzer/protocol/icmp/ICMP.cc#L95-L99

**Comment by timwoj** [comment]
Ah, you're correct.
