### ISSUE TITLE
Expose a zeek-archiver compatible log rotation function

### ISSUE THREAD

**Issue by grigorescu** [zeek/zeek#1463]
zeek-archiver requires a very specific file naming scheme in order to rotate logs. [Its documentation](https://github.com/zeek/zeek-archiver#use-with-zeekcontrol) shows you how to do this.

Having to copy that function seems like an unnecessary step, given that we already define that function in base/frameworks/cluster/nodes/logger.zeek. We have tests against that function, and have updated it before. It'd be nice for users not to have to duplicate this.

I'd like to propose:

1. Rename `supervisor_rotation_format_func` to `archiver_rotation_format_func`, since the format is really tied to zeek-archiver, and less so to the Supervisor framework.
2. Move the definition of the function outside of `@if ( Supervisor::is_supervised() )`, to make it easier for non-supervised setups to enable this.

Does this seem reasonable? I couldn't find any uses of the name `supervisor_rotation_format_func` outside of logger.zeek; do we need to deprecate this name if we'd like to rename it?

**Comment by jsiwek** [comment]
> Does this seem reasonable?

Yeah, thanks.

> I couldn't find any uses of the name `supervisor_rotation_format_func` outside of logger.zeek; do we need to deprecate this name if we'd like to rename it?

Technically think so / doesn't hurt, and I just did that while merging the PR.
