### ISSUE TITLE
Segfault in 4.0.0 - src/input/Manager.cc:1392

### ISSUE THREAD

**Issue by initconf** [zeek/zeek#1467]
You can reproduce this with attached files: zeek ./coredump.zeek  

Here is coredump

Core was generated by `zeek -i ixl3 host/policies/net-control-init.zeek'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  zeek::Ref (o=0x0) at /home/bro/install/zeek-4.0.0-rc3/src/zeek/Obj.h:174
174             if ( ++(o->ref_cnt) <= 1 )

[zeek-scripts-reproduce-segfault.zip](https://github.com/zeek/zeek/files/6224514/zeek-scripts-reproduce-segfault.zip)

[Current thread is 1 (LWP 102326)]
(gdb) bt
#0  zeek::Ref (o=0x0) at /home/bro/install/zeek-4.0.0-rc3/src/zeek/Obj.h:174
#1  zeek::Val::Ref (this=0x0) at /home/bro/install/zeek-4.0.0-rc3/src/zeek/Val.h:182
#2  zeek::input::Manager::EndCurrentSend (this=0x2338120, reader=<optimized out>) at /home/bro/install/zeek-4.0.0-rc3/src/input/Manager.cc:1392
#3  0x00000000008b1277 in zeek::input::EndCurrentSendMessage::Process (this=<optimized out>)
    at /home/bro/install/zeek-4.0.0-rc3/src/input/ReaderBackend.cc:100
#4  0x00000000008731f8 in zeek::threading::MsgThread::Process (this=0x3b55600) at /home/bro/install/zeek-4.0.0-rc3/src/threading/MsgThread.cc:477
#5  0x0000000000811090 in zeek::run_state::detail::run_loop () at /home/bro/install/zeek-4.0.0-rc3/src/RunState.cc:315
#6  0x00000000005f47ce in main (argc=<optimized out>, [argv=<optimized](url) out>) at /home/bro/install/zeek-4.0.0-rc3/src/main.cc:59

**Comment by jsiwek** [comment]
Are you really using 4.0.0-rc3 or 4.0.0 ?  Not sure it should matter much in relation to this one, but I generally couldn't reproduce it with either and wanted to check how you get this to happen in more detail before looking further.

**Comment by initconf** [comment]
actually I take this back! Johanna seems to have already fixed this one. I was incorrectly attributing this crash to other runtime crash I saw!
