### ISSUE TITLE
Packet analyzer error

### ISSUE THREAD

**Issue by anakorenko** [zeek/zeek#1504]
Hi, i`m try to create my own packet analyzer based on Ethernet example in src directory. I already create plugin using init-plugin script, used code from Ethernet example and script from packet analysis doc. But i`m getting error "Component 'PacketAnalyzer::ETHERNET' defined more than once". Can somebody help me resolve this error. Thank you)

**Comment by timwoj** [comment]
For the future we generally don't handle support questions like this as Github issues. These questions are easier to answer on the Zeek Community Slack server or via the mailing lists. You can find more information on how to connect to those at https://zeek.org/community/.

That said, it's likely that you didn't change the name of your new analyzer's component in your `Plugin.cc` file. The Ethernet analyzer is already defined and is one of the first analyzers to be instantiated, so your new analyzer conflicts when it tries to initialize itself.
