### ISSUE TITLE
Zeek 4 cluster mode not generating intel.log properly

### ISSUE THREAD

**Issue by dougburks** [zeek/zeek#1506]
This issue was originally reported at https://github.com/Security-Onion-Solutions/securityonion/issues/3850.

To eliminate as many variables as possible, I started with a clean CentOS 7 VM and installed the Zeek 4 RPM from https://software.opensuse.org//download.html?project=security%3Azeek&package=zeek.

I then configured Zeek for standalone mode and the Intel Framework generated intel.log properly. 

I then switched Zeek to cluster mode and the Intel Framework no longer generates intel.log properly but instead logs warnings to reporter.log like this:
```
#separator \x09
#set_separator	,
#empty_field	(empty)
#unset_field	-
#path	reporter
#open	2021-04-14-11-46-08
#fields	ts	level	message	location
#types	time	enum	string	string
1618425968.054627	Reporter::WARNING	failed to convert remote event 'Intel::match_remote' arg #0, got vector, expected record	(empty)
1618425968.055720	Reporter::WARNING	failed to convert remote event 'Intel::match_remote' arg #0, got vector, expected record	(empty)
1618425968.083044	Reporter::WARNING	failed to convert remote event 'Intel::match_remote' arg #0, got vector, expected record	(empty)
```
This worked properly in previous versions of Zeek, so this appears to be a regression.

Also see discussion in slack today for additional information:
https://zeekorg.slack.com/archives/CSZBXF6TH/p1618320486187000

Please let me know if I can provide any further information to help in resolving this issue.

Thanks!

**Comment by dougburks** [comment]
I've confirmed this issue also exists when installing Ubuntu 20.04 and then installing the Zeek 4 packages for Ubuntu from https://software.opensuse.org//download.html?project=security%3Azeek&package=zeek.

**Comment by dougburks** [comment]
node.cfg:
```
[logger-1]
type=logger
host=localhost

[manager]
type=manager
host=localhost

[proxy-1]
type=proxy
host=localhost

[worker-1]
type=worker
host=localhost
interface=ens34
```

Added to local.zeek:
```
@load frameworks/intel/seen

redef Intel::read_files += { "/opt/zeek/share/zeek/site/intel.dat" };
```

/opt/zeek/share/zeek/site/intel.dat:
```
#fields	indicator	indicator_type	meta.source
www.reddit.com	Intel::DOMAIN	my_special_source
testmyids.com	Intel::DOMAIN	my_special_source
```

**Comment by dougburks** [comment]
I've confirmed this issue also exists when installing Ubuntu 20.04 and then installing the Zeek 4 NIGHTLY (4.1-0) packages.

**Comment by jsiwek** [comment]
Thanks, patch/branch at #1513 if you want to confirm the fix.

**Comment by rsmmr** [comment]
Nice catch!

**Comment by dougburks** [comment]
Thanks @jsiwek and @rsmmr !

Is there an ETA for Zeek 4.0.1 with the fix?

**Comment by jsiwek** [comment]
@dougburks I'd estimate April 21 or 22 for 4.0.1

**Comment by dougburks** [comment]
OK, thanks @jsiwek !
