### ISSUE TITLE
SIP generating embedded NULL reporter log

### ISSUE THREAD

**Issue by MMChrisHinshaw** [zeek/zeek#1507]
One of my sensors is receiving UDP traffic on port 5060 with a length of 8, but the data is all `\x00`.  The Zeek protocol analyzer appears to concatenate these packets for later processing, and ends up generating reporter logs with the following message (or similar):

```string with embedded NUL: "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00REGISTER"```

I'm seeing this with Zeek 3.1.4, and can provide a pcap if needed.

[SIP_embedded_NUL.pcap.zip](https://github.com/zeek/zeek/files/6306729/SIP_embedded_NUL.pcap.zip)
 
(Above copied from Slack #development channel.  If this is a duplicate bug, I apologize.)

**Comment by MMChrisHinshaw** [comment]
Thanks for implementing a solution so quickly.  Will there be a patch to the 3.x release branches as well?

**Comment by jsiwek** [comment]
Not for 3.x, but I'll put it in 4.0.1
