### ISSUE TITLE
Add Geneve decap support

### ISSUE THREAD

**Issue by vijitnair** [zeek/zeek#1517]
Add ability to decap Geneve packets to process inner payload. 

See Geneve packet format here - https://datatracker.ietf.org/doc/rfc8926/

**Comment by timwoj** [comment]
I could have sworn we had an issue for this already at one point, but now I can't find it. It must have been a discussion I had with someone on Slack. This should be reasonably easy to do following the models of the other UDP tunnel protocol analyzers (AYIYA, etc) if you want to take a stab at it.

My intention is to move those analyzers to be packet analyzers at some point in the future, but it won't happen until after #1114 is done and the UDP analyzer is fully moved to that framework.

**Comment by timwoj** [comment]
There was some discussion of another community member doing the same work: https://zeekorg.slack.com/archives/CTGDGK6EA/p1616034651006100

**Comment by bbannier** [comment]
Hi @vijitnair, I recently posted PR #1522 which adds support for Geneve. Are you by chance able to contribute a small PCAP with Geneve-encapsulated traffic we could use for testing? A couple of packages would be sufficient, e.g., a ping request wrapped in Geneve.

**Comment by vijitnair** [comment]
[geneve.pcap.gz](https://github.com/zeek/zeek/files/6428952/geneve.pcap.gz)
@bbannier - can you pls try with attached
