### ISSUE TITLE
command line option to change log dir

### ISSUE THREAD

**Issue by jrespeto** [zeek/zeek#1519]
Trying to place logs into a different directory without having to be in the directory Im running zeek in.  

Is it posable to add the option like -l <dir> 

https://docs.zeek.org/en/master/scripts/base/frameworks/logging/main.zeek.html

I can't get this to work as `Log::default_rotation_dir` is not a Redefinable Options

```
zeek -C -s myzeek/sigs -r capture/capture.pcap LogAscii::use_json=T Log::default_rotation_dir="/opt/logs/zeek/"
```

**Comment by jsiwek** [comment]
Yes, guessing that kind of option could be added for convenience.  There's a previous issue about the same thing that you can follow, so closing this one as a duplicate: https://github.com/zeek/zeek/issues/772
