### ISSUE TITLE
Are sequential rules supported?

### ISSUE THREAD

**Issue by inf3rno** [zeek/zeek#1527]
I write a thesis about sequential patterns ( https://en.wikipedia.org/wiki/Sequential_pattern_mining ) in cyber security and I am looking for tools that support adding sequential rules. For example in zeek such a rule could be that if we see a certain group of messages in a certain order, then we have an ongoing attack. I don't find anything like this in the manual, but just to be sure, is there support for this in the current version?

**Comment by 0xxon** [comment]
Hi,

We don't use GitHub issues for support questions. Questions like this are best answered using on either slack or our mailing list, which is both are frequented by Zeek developers and professional users. You can join here:

Mailing list: https://lists.zeek.org/mailman3/lists/zeek.lists.zeek.org/

Slack: https://zeek.org/community/

 Johanna
