### ISSUE TITLE
Queue doesn't function as expected?

### ISSUE THREAD

**Issue by timwoj** [zeek/zeek#1528]
I’ve got some questions about our Queue implementation. I was looking at adding some unit tests to gain coverage on some missing functions, and it definitely doesn’t work the way I’d expect a queue to function.

For example, a std::deque passes this test:

```
	std::deque<int> q;
	q.push_front(2);
	q.push_front(1);
	CHECK(q.front() == 1);
	CHECK(q.back() == 2);
```

Our queue, on the other hand, does not. `push_front` doesn’t modify the `tail` value at all. `back()` on ours just returns the zeroth entry in the internal array, which is definitely not 2. It’s some random value. This also means that iteration would be broken for our `Queue`, since it just returns the internal array. If you create a default queue, it has a 10 element array. If you only add one element to it, iteration is still going to loop over all of those unset elements.

I’m wondering if we could just remove the `Queue` type in general and either replace it with `std::deque`, or replace it with our own `List` type. List handles all of the same operations that we’re currently using (`push_*`, `pop_*`, `front()`, `back()`), and it’s well tested. We only use `Queue` in a few places, but one of them is the message queues in `MsgThread`, which I’m a little concerned about modifying.

**Comment by JustinAzoff** [comment]
I thought MsgThread used src/threading/Queue.h which uses std::queue and not src/Queue.h

I don't think much of anything uses Queue.h

**Comment by grigorescu** [comment]
Looks like some of the older/rarely used code does:

```
src/Debug.h    using Filemap = PQueue<StmtLocMapping>; // mapping for a single file
src/DebugCmds.cc    zeek::PQueue<zeek::detail::DebugCmdInfo> zeek::detail::g_DebugCmdInfos;
src/DebugCmds.cc:   zeek::PQueue<zeek::detail::DebugCmdInfo>& g_DebugCmdInfos = zeek::detail::g_DebugCmdInfos;
src/DebugCmds.h:    extern PQueue<DebugCmdInfo> g_DebugCmdInfos;
src/analyzer/protocol/stepping-stone/SteppingStone.h:     PQueue<SteppingStoneEndpoint>& OrderedEndpoints()
src/analyzer/protocol/stepping-stone/SteppingStone.h:     PQueue<SteppingStoneEndpoint> ordered_endps;
```

**Comment by rsmmr** [comment]
The current semantics certainly seem either off or, likely, buggy.

Per Justin, the threading code does have it own queue implementation, which is thread-safe.

Given the few uses, removing PQueue and replacing with a `std` container sounds good to me.
