### ISSUE TITLE
get mails from IMAP sessions

### ISSUE THREAD

**Issue by cscli** [zeek/zeek#1548]
In  zeek/scripts/base/protocols/imap/README, 
`Hence, we do not get
mails from IMAP sessions, only X509 certificates`
 do you have a plan about getting mails from IMAP sessions,  getting files  from IMAP sessions.
thanks

**Comment by 0xxon** [comment]
There are no current plans to extend the imap analyzer that it built into Zeek. As the readme mentions, the analyzer is a stub that mostly exists to be able to parse the SSL/TLS sessions that are established after starttls.

Please note that this is not a bug - and for support discussions, slack or our email groups are probably the better venues in which you will get exposure to more people and much quicker response times.
