### ISSUE TITLE
Sum of two vectors of int

### ISSUE THREAD

**Issue by jsiwek** [zeek/zeek#155]
Moved from https://bro-tracker.atlassian.net/browse/BIT-1760

Created by François at 2016-11-25T16:33:09.248-0600:
> There is a bug when adding two vectors.
> It works for vector of count, but returns a vector filled iwth zeros for vector of int.
> 
> Her is my test case :
> 
> event bro_init()
> 	{
> 	local c1 : vector of count = { 1, 2 };
> 	local c2 : vector of count = { 3, 4 };
> 	local c3 = c1 + c2;
> 	print c3;
> 
> 	local v1 : vector of int = { 1, 2 };
> 	local v2 : vector of int = { 3, 4 };
> 	local v3 = v1 + v2;
> 	print v3;
> 	}
> 
> Output is :
> 
> [4, 6]
> [0, 0]
> 

Comment by François at 2016-11-25T16:58:29.761-0600:
> It works with the following change :
> 
> local v1 : vector of int = { +1, +2 };
> local v2 : vector of int = { +3, +4 };
> local v3 = v1 + v2;
> 
> Well, quite strange !
> 
> 
> 
> 

Comment by Daniel Thayer at 2016-11-25T17:10:23.412-0600:
> This might be related to #159 

Comment by François at 2016-11-25T17:17:14.343-0600:
> I think so.
> 
> This sample also works fine :
> local v1 : vector of int = { -1, 2 };
> local v2 : vector of int = { 3, 4 };
> local v3 = v1 + v2;
> 
> I think 1 is understood like a count, and -1 and +1 are understood like int.
>  { 1, 2} is understood like a vector of count and { -1, 2} a vector of int.
> 
> 
> 
> 
> 
> 
> 
> 
> 

Comment by François at 2016-11-25T17:49:27.654-0600:
> In BinaryExpr::Fold() :
> * At the beginning of this method :
>     - type of the current element is used : InternalTypeTag it = v1->Type()->InternalType();
>     - For a value of 1, i.e. count : is_integral = 0 and is_unsigned = 1, DO_FOLD is called and computes u3.
>     - For a value of +1, i.e. int : is_integral = 1 and is_unsigned = 0, Do_FOLD is called and computes i3.
> 
> * At the end of this method :
>    - yield type of the vector is used :    ret_type = ret_type->YieldType();
>    - for a vector of int : return new Val(i3, ret_type->Tag());
>    - for a vector of count : return new Val(u3, ret_type->Tag());
> 
> 1. So if we have an element of type count in a vector of int, it does not work : u3 is computed, but i3 (=0) is assigned.
> 
> 2. This is also true if we have an element of type int into a vector of count : i3 is computed, but u3 (=0) is assigned.
> 
> Test case for this second case :
> local v1 : vector of count = { +1, +2 };
> local v2 : vector of count = { +3, +4 };
> local v3 = v1 + v2;
> 
> But of course the initial problem is in the computation of types when initializating the vector.
>

**Comment by timwoj** [comment]
The above snippets are a good starting point. The reason it falls down into the unsigned case is because the vectors in the expression get converted into `count` vectors in `BinaryExpr::Eval` before they get passed down into `Fold`. I'm looking into why it does that.

**Comment by jsiwek** [comment]
Fixed via #395
