### ISSUE TITLE
No output of SSH brute forcing detection script under live traffic

### ISSUE THREAD

**Issue by maofeichen** [zeek/zeek#1552]
The **detect-bruteforcing.zeek** (under path: /opt/zeek/share/zeek/policy/protocols/ssh/detect-bruteforcing.zeek) is the default script provided by zeek to detect ssh brute-forcing attack.
I tried to verify the script via experiments, however, I found that the script generating no output under live traffic of ssh brute-forcing attack.

The experiment setups are as below:
-   VM A (192.168.153.18): a ubuntu machine installed zeek lts 4.0.0 version
-   VM B (192.168.153.6): a kali machine

I did 2 experiments to verify the script.

# 1. Test the script with a pcap file

1. I used hydra on VM B to ssh brute-forcing VM A, and used wireshark to save the traffic as a pcap file.

2. Then to detect the ssh brute-forcing With command:

   $ zeek -Cr ssh-bruteforce-local-live-top100_twice.pcap protocols/ssh/detect-bruteforcing ../../script/json.zeek

3. And Zeek generated corresponding results in the **notice.log** as:

>$ cat notice.log
{"ts":1617180637.038918,"note":"SSH::Password<sub>Guessing</sub>","msg":"192.168.153.6 appears to be guessing SSH passwords (seen in 30 connections).","sub":"Sampled servers:  192.168.153.18, 192.168.153.18, 192.168.153.18, 192.168.153.18, 192.168.153.18","src":"192.168.153.6","actions":["Notice::ACTION<sub>LOG</sub>"],"suppress<sub>for</sub>":3600.0}

So the script did work in this scenario. 

# 2. Test with live traffic

However when I did a similar experiment under live traffic, the script didn't work:

1.  start zeek via **zeekctl**, then **deploy**
2.  verify that the ssh detect script had been loaded as:

>[ZeekControl] > scripts
zeek scripts are ok.
...
{"name":"  /opt/zeek/share/zeek/policy/protocols/ssh/detect-bruteforcing.zeek"}<br />

3.  Similarly use hydra to kept ssh brute-forcing VM A

Zeek keep generating records in the **ssh.log** as:

>
{"ts":1620737950.134968,"uid":"CzwRXR1IpDyPJV600e","id.orig<sub>h</sub>":"192.168.153.6","id.orig<sub>p</sub>":37444,"id.resp<sub>h</sub>":"192.168.153.18","id.resp<sub>p</sub>":22,"auth<sub>attempts</sub>":0,"client":"SSH-2.0-libssh<sub>0.9.5</sub>"}
{"ts":1620737950.162898,"uid":"ChDNly4SbbdAmrxDWk","id.orig<sub>h</sub>":"192.168.153.6","id.orig<sub>p</sub>":37446,"id.resp<sub>h</sub>":"192.168.153.18","id.resp<sub>p</sub>":22,"auth<sub>attempts</sub>":0,"client":"SSH-2.0-libssh<sub>0.9.5</sub>"}
{"ts":1620737950.162947,"uid":"CXIWS72Z3FSC8uvS26","id.orig<sub>h</sub>":"192.168.153.6","id.orig<sub>p</sub>":37448,"id.resp<sub>h</sub>":"192.168.153.18","id.resp<sub>p</sub>":22,"auth<sub>attempts</sub>":0,"client":"SSH-2.0-libssh<sub>0.9.5</sub>"}

However, there is no detection-result records in the **notice.log**, which I suppose zeek should generate similar records with the pcap experiment.

Any help? Thanks!

**Comment by JustinAzoff** [comment]
Your ssh log indicates that zeek is only seeing the packets from the client, not the server.

Are you running zeek ON the server?  If so you probably need to ignore checksum errors, see https://old.zeek.org/documentation/faq.html#why-isn-t-zeek-producing-the-logs-i-expect-a-note-about-checksums

**Comment by maofeichen** [comment]
@anthonykasza Thanks for your comment.
The hydra command I used for tests:

~~~sh
hydra -s 22 -v -V -l root -x 1:6:a -t 16 192.168.153.18 ssh
~~~

Basically I just set the protocol, port and target IP etc., and use passwords alphabetically, other fields left by default.
And hydra printed out attempts in runtime:

~~~
[DATA] max 16 tasks per 1 server, overall 16 tasks, 321272406 login tries (l:1/p:321272406), ~20079526 tries per task<br />
[DATA] attacking ssh://192.168.153.18:22
[VERBOSE] Resolving addresses &#x2026; [VERBOSE] resolving done
[INFO] Testing if password authentication is supported by ssh://root@192.168.153.18:22
[INFO] Successful, password authentication is supported by ssh://192.168.153.18:22
[ATTEMPT] target 192.168.153.18 - login "root" - pass "a" - 1 of 321272406 [child 0] (0/0)
[ATTEMPT] target 192.168.153.18 - login "root" - pass "b" - 2 of 321272406 [child 1] (0/0)
[ATTEMPT] target 192.168.153.18 - login "root" - pass "c" - 3 of 321272406 [child 2] (0/0)
...
~~~

I'm not familiar how hydra implements, but it seems to me that it uses muti-threads (default 16). So I presume that it opened 16 tcp connections (one per threat) concurrently, and use each to perform ssh brute-forcing?

However, as you mentioned, "Hydra reuses a single SSH session for guessing multiple credentials". If that's the case, then after one ssh guessing password trial, it won't close the tcp connection and opens a new one; but keep reuse the same one over and over?

And that's the reason why the script didn't detected the brute-forcing.

However, I also have some questions to that explanation.

1. According to the ssh.log generated by the hydra brute-forcing:
>  {"ts":1620783945.039488,"uid":"CKMerZXxLezr6Feg9","id.orig\_h":"192.168.153.6","id.orig\_p":41680,"id.resp\_h":"192.168.153.18","id.resp\_p":22,"auth\_attempts":0,"client":"SSH-2.0-libssh\_0.9.5"}
 {"ts":1620783944.03499,"uid":"CVNvus4w4A94eDWxbi","id.orig\_h":"192.168.153.6","id.orig\_p":41658,"id.resp\_h":"192.168.153.18","id.resp\_p":22,"auth\_attempts":0,"client":"SSH-2.0-libssh\_0.9.5"}
   {"ts":1620783948.469617,"uid":"CzcQ2P1Xh98H0pPDS3","id.orig\_h":"192.168.153.6","id.orig\_p":41718,"id.resp\_h":"192.168.153.18","id.resp\_p":22,"auth\_attempts":0,"client":"SSH-2.0-libssh\_0.9.5"}
...

Each record has a uniqe **uid**, and each uid actually corresponds to a record in the **conn.log**, i.e.:
>   {"ts":1620783945.039377,"uid":"CKMerZXxLezr6Feg9","id.orig\_h":"192.168.153.6","id.orig\_p":41680,"id.resp\_h":"192.168.153.18","id.resp\_p":22,"proto":"tcp","duration":5.67271614074707,"orig\_bytes":1350,"resp\_bytes":0,"conn\_state":"OTH","local\_orig":true,"local\_resp":true,"missed\_bytes":0,"history":"ScADcFR","orig\_pkts":17,"orig\_ip\_bytes":2230,"resp\_pkts":0,"resp\_ip\_bytes":0}
   {"ts":1620783944.030365,"uid":"CVNvus4w4A94eDWxbi","id.orig\_h":"192.168.153.6","id.orig\_p":41658,"id.resp\_h":"192.168.153.18","id.resp\_p":22,"proto":"tcp","duration":5.659334897994995,"orig\_bytes":1350,"resp\_bytes":0,"conn\_state":"OTH","local\_orig":true,"local\_resp":true,"missed\_bytes":0,"history":"ScADcFR","orig\_pkts":17,"orig\_ip\_bytes":2230,"resp\_pkts":0,"resp\_ip\_bytes":0}
...

If I understand correctly, each unique uid represents a unique tcp connection, and since the uid of records in the **ssh.log** are different, I believe they belong to different tcp connections. And which is contradicted with the above explaination that "hydra reuse same session"?

2. Second question is actually test 1 & 2 are under similar procedures, the major difference is test1 used a pcap file and test2 used a live traffic. But the pcap file were actually generated according to the live traffic, so why test1 could detect the brute-forcing correctly, and test2 couldn't, that's where I got confused.

3. Thirdly, follow the "hydra reuse sessions" logic, instead of using hydra, if I do ssh trials manually and above the threashhold, say more than 30 times within 5 minutes; then the script should detect the brute-forcing? Since it must be different tcp connections. I'll verify this.

Attach is the pcap file I used for tests.
[ssh-bruteforce-local-live-top100_twice.pcap.zip](https://github.com/zeek/zeek/files/6463031/ssh-bruteforce-local-live-top100_twice.pcap.zip)

My goal is trying to figure out a scenario such that the script can detect ssh brute-forcing correctly under **live traffic**. 

Again thanks for your help!

**Comment by maofeichen** [comment]
@JustinAzoff As to the experiment setup: 
- VM A install ssh server and zeek, zeek listens the network interface; 
- VM B kali did ssh trials to VM A. 
So I assume the client is the VM B, and the server is the VM A under this scenario? I'll check into the link, thanks!

**Comment by maofeichen** [comment]
@anthonykasza  I did some more tests, and believe you are right. As you mentioned, the detection script relies on the how many times that event `ssh_auth_failed` had been raised, and according to the doc:
> This event is generated when an SSH connection was determined to have had a failed authentication. This determination is based on packet size analysis, and errs on the side of caution - that is, if there’s any doubt about the authentication failure, this event is not raised.
This event is only raised once per connection.

And if hydra alway reuses a same tcp connection as possible, then the script hardly raises enough times of `ssh_auth_failed` to satisfy the threshold. And no wonder the script hadn't written any corresponding entries in the `notice.log`.

It seem the event `ssh_auth_failed` is pretty unreliable in this scenario, I notice that there is another event `ssh_auth_attempted` and which seems more suitable to meet the detection purpose, as quote from doc:
> This event is generated when an SSH connection was determined to have had an authentication attempt. 

To do a test to verify both events, I did some modifications to the original script:
~~~zeek
# detect-brute-forcing.zeek
# ...

global g_ssh_auth_failed_cnt: count = 0;
global g_ssh_auth_attempt_cnt: count = 0;

# ...
event ssh_auth_failed(c: connection)
    {
    print "ssh auth failed";
    g_ssh_auth_failed_cnt += 1;
    ...
    }

event ssh_auth_attempted(c: connection, authenticated: bool)
    {
    print "ssh auth attempted";
    g_ssh_auth_attempt_cnt += 1;
    }

event zeek_done() 
    {
    print fmt("Total ssh auth attempt times: %d - failed times: %d", g_ssh_auth_attempt_cnt, g_ssh_auth_failed_cnt);
    }
~~~

Basically is to add counters to both `ssh_auth_attempted` and `ssh_auth_failed`, and print out total event counts of each during run time. 

And my test procedures are as below, still use VM A & B.
1. start zeek on VM A listening the network interface with the updated script:
~~~sh
# zeek -Ci ens160 ../../script/det_ssh_bruteforce/detect-bruteforcing.zeek ../../script/json.zeek
~~~
2. start hydra on VM B as:
~~~sh
hydra -s 22 -v -V -l root -x 1:5:a -t 1 192.168.153.18 ssh
~~~
3. hydra totally issued `11` trials of ssh connection to A as:
> [WARNING] Restorefile (you have 10 seconds to abort... (use option -I to skip waiting)) from a previous session found, to prevent overwriting, ./hydra.restore
[DATA] max 1 task per 1 server, overall 1 task, 12356630 login tries (l:1/p:12356630), ~12356630 tries per task
[DATA] attacking ssh://192.168.153.18:22/
[VERBOSE] Resolving addresses ... [VERBOSE] resolving done
[INFO] Testing if password authentication is supported by ssh://root@192.168.153.18:22
[INFO] Successful, password authentication is supported by ssh://192.168.153.18:22
[ATTEMPT] target 192.168.153.18 - login "root" - pass "a" - 1 of 12356630 [child 0] (0/0)
[ATTEMPT] target 192.168.153.18 - login "root" - pass "b" - 2 of 12356630 [child 0] (0/0)
[ATTEMPT] target 192.168.153.18 - login "root" - pass "c" - 3 of 12356630 [child 0] (0/0)
[ATTEMPT] target 192.168.153.18 - login "root" - pass "d" - 4 of 12356630 [child 0] (0/0)
[ATTEMPT] target 192.168.153.18 - login "root" - pass "e" - 5 of 12356630 [child 0] (0/0)
[ATTEMPT] target 192.168.153.18 - login "root" - pass "f" - 6 of 12356630 [child 0] (0/0)
[ATTEMPT] target 192.168.153.18 - login "root" - pass "g" - 7 of 12356630 [child 0] (0/0)
[ATTEMPT] target 192.168.153.18 - login "root" - pass "h" - 8 of 12356630 [child 0] (0/0)
[ATTEMPT] target 192.168.153.18 - login "root" - pass "i" - 9 of 12356630 [child 0] (0/0)
[ATTEMPT] target 192.168.153.18 - login "root" - pass "j" - 10 of 12356630 [child 0] (0/0)
[STATUS] 10.00 tries/min, 10 tries in 00:01h, 12356620 to do in 20594:23h, 1 active
[ATTEMPT] target 192.168.153.18 - login "root" - pass "k" - 11 of 12356630 [child 0] (0/0)
The session file ./hydra.restore was written. Type "hydra -R" to resume session.
[ERROR] Received signal 15, going down ...
4. After hydra finished, stopped zeek, and zeek printed out:
> listening on ens160
ssh auth attempted
ssh auth attempted
ssh auth attempted
ssh auth attempted
ssh auth attempted
ssh auth failed
ssh auth attempted
ssh auth attempted
ssh auth attempted
ssh auth attempted
ssh auth attempted
ssh auth failed
^C1620823792.556431 received termination signal
1620823792.556431 897 packets received on interface ens160, 0 (0.00%) dropped
Total ssh auth attempt times: 10 - failed times: 2

It's a simple test, but based on the result, `ssh_auth_attempted` is way more accuracy on detecting ssh brute-forcing than `ssh_auth_failed`. I wonder is there any particular reason that the original detecting script choose to use `ssh_auth_failed` instead of `ssh_auth_attempted`?

I'm not sure if it's reasonable to use the `ssh_auth_attempted` event here to do the detection. But if that's the case, is it possible to update the default detection script? And I'd like to participate and contribute. 

look forward to your comments and again thanks for your help! @anthonykasza @JustinAzoff

**Comment by 0xxon** [comment]
From what I recall, trying to count authentication attempt in SSH is very unreliable. For people that have a number of public keys that are tried in order, it is not super unlikely to see 5+ authentication attemps before a successful login.

You could go and count all authentication attemps for failed logins as brute-forcing attempts - however I assume you will still have a rather high false positive rate. E.g. when people misspell usernames (which happens quite regularly for me) which will result in ssh trying all ssh-keys that are available before failing.

**Comment by 0xxon** [comment]
More generally speaking, this being more of a support discussion and less of a bug description potentially makes this more suited for our other community support venues (so - our email lists or slack).

**Comment by maofeichen** [comment]
@0xxon I think you are right, initially I thought it's a bug due to it failed to detect such a simple ssh brute-forcing experiment. Now I understand it's the implementation consideration as above discussions, so I'll close the issue.

**Comment by 0xxon** [comment]
Sounds good - feel free to bring this up in slack, the mailing list or in a discussion.
