### ISSUE TITLE
Error in formatting of VirusTotal links in detect-MHR.zeek

### ISSUE THREAD

**Issue by tinsun** [zeek/zeek#1567]
detect-MHR.zeek creates the link on the form
option match_sub_url = "https://www.virustotal.com/en/search/?query=%s";
  
Current VirusTotal link format is
option match_sub_url = "https://www.virustotal.com/gui/search/%s";

We've tested it locally and it works™.

**Comment by timwoj** [comment]
Thanks for the report and the patch!
