### ISSUE TITLE
Type-checking is missing for some &attributes

### ISSUE THREAD

**Issue by jsiwek** [zeek/zeek#157]
Moved from https://bro-tracker.atlassian.net/browse/BIT-1981

Created by Vern Paxson at 2018-09-05T05:46:51.797-0500:
> The appended script [^attr-type-check.bro] doesn't generate any complaints about the non-sensical attributes; and the one attribute that does make sense, &default, doesn't work, this script generates an error complaining about a's value not being set.
> 

Comment by Jon Siwek at 2018-09-05T11:05:07.461-0500:
> I'd probably say even &default doesn't make sense to permit there?  One probably would initialize a default value via = assignment instead?

Comment by Vern Paxson at 2018-09-05T14:16:54.280-0500:
> You mean why use "`global a: count &default = 5`" instead of "`global a = 5`"? Yeah, I agree.  There are maybe microcases where there's a semantic difference (like when assigning to an `&optional` record field), but that's about it.  

Comment by Jon Siwek at 2018-09-05T14:50:27.638-0500:
> Yeah, that's all I meant: &default doesn't seem useful in the case of of a global.

Attachment https://bro-tracker.atlassian.net/secure/attachment/21473/attr-type-check.bro:
```
global a: count
        &default = 10
        &default = 9
        &optional
        &log
        &add_func = function(): count { return 3; };
print a;

```

**Comment by timwoj** [comment]
Looking at the documentation, it appears that `&redef` and `&deprecated` are the only two valid attributes here, and the rest through throw some sort of error.

**Comment by timwoj** [comment]
The base scripts use `&add_func` and `&delete_func` for a few global variables as well so those should either be considered valid or we need to go through and remove them.

**Comment by jsiwek** [comment]
> The base scripts use `&add_func` and `&delete_func` for a few global variables as well so those should either be considered valid or we need to go through and remove them.

Didn't see any use of `&delete_func`, but the couple `&add_func` usages look legit -- it's weird/uncommon, but `redef` does work for variables that don't have the `&redef` attribute.

So not sure there's anything to change for those attributes with respect to this issue.

An example similar to what's in the original report does segfault:

```zeek
global a: count &add_func = function(): count { return 3; };
redef a += 13;
print a;
```

Could either fix that as part of this issue or separately, since not sure it's just type-checking problem or a problem with `redef`ing something that has no initial value (or combination).  E.g. this one gives a "argument type mismatch error":

```zeek
global a: count = 1 &add_func = function(): count { return 3; };
redef a += 13;
print a;
```

Which seems like the right behavior (except maybe message could be more descriptive) because the actual function should be:

```zeek
global a: count = 1 &add_func = function(old: count, new: count): count { return 3; };
redef a += 13;
print a;
```

**Comment by timwoj** [comment]
> a problem with redefing something that has no initial value (or combination

it crashes because it tries to `Ref()` a null `Val`, because the variable doesn't have a value yet.
