### ISSUE TITLE
Either Fix or Remove SteppingStone Analyzer

### ISSUE THREAD

**Issue by grigorescu** [zeek/zeek#1573]
In Zeek 3.2.2 and above, the SteppingStone analyzer is segfaulting when being run with a PCAP with SSH traffic. Example at: https://try.zeek.org/#/tryzeek/saved/510139

Backtrace:
```
#0  0x0000000000bdda5f in analyzer::stepping_stone::SteppingStoneEndpoint::SteppingStoneEndpoint(analyzer::tcp::TCP_Endpoint*, analyzer::stepping_stone::SteppingStoneManager*) ()
#1  0x0000000000bddb4e in analyzer::stepping_stone::SteppingStone_Analyzer::Init() ()
#2  0x00000000009ae175 in analyzer::Analyzer::InitChildren() [clone .localalias] ()
#3  0x00000000009b25c2 in analyzer::Manager::BuildInitialAnalyzerTree(Connection*) ()
#4  0x00000000008c1f09 in NetSessions::NewConn(ConnIDKey const&, double, ConnID const*, unsigned char const*, int, unsigned int, Packet const*, EncapsulationStack const*)
    ()
#5  0x00000000008c4a4f in NetSessions::DoNextPacket(double, Packet const*, IP_Hdr const*, EncapsulationStack const*) ()
#6  0x00000000008c64e6 in NetSessions::NextPacket(double, Packet const*) ()
#7  0x0000000000895404 in net_packet_dispatch(double, Packet const*, iosource::PktSrc*) ()
#8  0x0000000000953d30 in iosource::PktSrc::Process() ()
#9  0x0000000000894d5d in net_run() ()
#10 0x0000000000669f2c in main ()
```

For some background, I'll quote a portion of the abstract of [the original paper](https://www.icir.org/vern/papers/stepping-sec00.pdf): 

> One widely-used technique by which network attackers attain anonymity and complicate their apprehension is by employing stepping stones: they launch attacks not from their own computer but from intermediary hosts that they previously compromised. We develop an efficient algorithm for detecting stepping stones by monitoring a site’s Internet access
link. The algorithm is based on the distinctive characteristics (packet size, timing) of interactive traffic, and not on connection contents, and hence can be used to find stepping stones even when the traffic is encrypted. We evaluate the algorithm on large Internet access traces and find that it performs quite well.

I think the idea is really neat, and it's still an effective way of finding potentially compromised hosts. Attackers are still using "stepping stone" hosts ("SSH pivoting" is perhaps the more modern term).

However, there are some issues that should be addressed, apart from the segfault:

- Zeek likely can't implement the detection in a cluster. Let's say the attacker has compromised phpbb.zeek.org and is then accessing internal hosts. The connection between the attacker and phpbb.zeek.org is likely being load-balanced to one Zeek worker, while the connection(s) between phpbb.zeek.org and the internal hosts are going to another Zeek worker. As it is today, the detection doesn't share state across workers, and wouldn't be able to detect this.
- I don't see anything in the test suite for this.
- There are some comments with the current implementation about how this hard-codes ports, and makes some assumptions. The approach would likely work for other protocols as well.

I kind of wonder if there's a more generic approach that could be taken. Perhaps a Characteristics Framework, which calculates and exposes a number of traffic characteristics (inter-packet timing, packet-size, jitter, etc.). Stepping Stone detection would be just one of the use-cases of this.

**Comment by 0xxon** [comment]
#1576 fixes the crash.

Apart from that - I think the stepping stone analyzer has been on the list of "things to potentially remove" for a long time. It currently is not documented at all - and, from what I know, basically unused.

So unless we can come up with a plan on how to make it usable and useful in the medium term I would opt to just remove it completely.

**Comment by 0xxon** [comment]
Also - note that the crash only happens when the event `stp_correlate_pair` is not used. So - if you want to play around with it, it actually does work once you use the events.

Example: https://try.zeek.org/#/tryzeek/saved/510303

**Comment by 0xxon** [comment]
#1576 revealed that there are more issues with the analyzer - I think that it might have memory leaks at the moment; converting it to Intrusive Pointers also was not as easy as I hoped since refcounting is used to decide when events are sent - and introducing Intrusive Pointers throws that off.

I talked to Robin a bit about this - and given that this feature never really has been documented, we do not think that anyone uses it, it does not work in cluster settings and there probably are more issues with the code - the most reasonable course of action is probably to remove it.

I am going to ask people on Slack and our email list if anyone is currently using the Stepping Stone analyzer - to determine if there is any impact on anyone.

**Comment by 0xxon** [comment]
I created the branch `topic/johanna/remove-stepping-stone`, which completely removes the stepping stone analyzer. We might want to wait at least a few more days for mailing list feedback before merging it.

**Comment by 0xxon** [comment]
We got no feedback of anyone using this - so, unless anyone has objections - I would vote to just immediately remove this for 4.1. I am happy to also create a branch for merging into 4.0 that will throw deprecation warnings if anyone tries to use the analyzer.

**Comment by timwoj** [comment]
I'm all for removing it but I agree we should probably have a deprecation warning on it in some way.

**Comment by 0xxon** [comment]
I just opened two pull requests - one against release/4 adding a warning if one uses any of the stepping stone events, and one against master removing the analyzer.

PRs: #1603 and #1604

**Comment by 0xxon** [comment]
This is done - analyzer is marked as deprecated in release/4.0 (so in 4.0.3) and removed from master.
