### ISSUE TITLE
Fully-escape unicode strings with invalid characters

### ISSUE THREAD

**Issue by timwoj** [zeek/zeek#1581]
@sethhall and I were discussing this problem in relation to https://github.com/zeek/zeek/pull/1437, where a UTF-8 encoding issue came up with one of the tests that was failing due to his changes. The failing case was this:

```
  -XXXXXXXXXX.XXXXXX	XXXXXXXXXXX	192.168.1.105	49613	65.55.53.190	80	1	GET	watson.microsoft.com	/StageOne/Generic/PCA2/mdd_1_3_exe/1_3_0_0/mdd/unknown/\xe8\x93\x93\xca\x86\xef\xbf\xbe\xef\xbf\xbf\xec\xb4\x91\xe7\x9e\x99\xef\xbf\xbd\xe7\x9e\x99\xeb\xb2\xb9\xd7\x9c\xee\x8b\xa0\xda\xa0/200/-1.htm?LCID=1033&OS=6.0.6002.2.00010100.2.0.6.18005	-	1.1	MSDW	-	0	1635	404	Not Found	-	-	(empty)	-	-	-	-	-	-	F8p4Qn20NOvGmbt434	-	text/html	USER-AGENT,HOST,CONNECTION	-	-	/StageOne/Generic/PCA2/mdd_1_3_exe/1_3_0_0/mdd/unknown/%E8%93%93%CA%86%EF%BF%BE%EF%BF%BF%EC%B4%91%E7%9E%99%EF%BF%BD%E7%9E%99%EB%B2%B9%D7%9C%EE%8B%A0%DA%A0/200/-1.htm?LCID,OS
  +XXXXXXXXXX.XXXXXX	XXXXXXXXXXX	192.168.1.105	49613	65.55.53.190	80	1	GET	watson.microsoft.com	/StageOne/Generic/PCA2/mdd_1_3_exe/1_3_0_0/mdd/unknown/蓓ʆ��촑瞙�瞙벹לڠ/200/-1.htm?LCID=1033&OS=6.0.6002.2.00010100.2.0.6.18005	-	1.1	MSDW	-	0	1635	404	Not Found	-	-	(empty)	-	-	-	-	-	-	F8p4Qn20NOvGmbt434	-	text/html	USER-AGENT,HOST,CONNECTION	-	-	/StageOne/Generic/PCA2/mdd_1_3_exe/1_3_0_0/mdd/unknown/%E8%93%93%CA%86%EF%BF%BE%EF%BF%BF%EC%B4%91%E7%9E%99%EF%BF%BD%E7%9E%99%EB%B2%B9%D7%9C%EE%8B%A0%DA%A0/200/-1.htm?LCID,OS
```

The original URI requested here included a string of what is probably intended to just be byte data, but we attempt to decode it into UTF-8 and display it as such. The problem is that because it's just random data, it includes what are technically-valid but not-really-valid glyphs:

```
$ printf "\xE8\x93\x93\xCA\x86\xEF\xBF\xBE\xEF\xBF\xBF\xEC\xB4\x91\xE7\x9E\x99\xEF\xBF\xBD\xE7\x9E\x99\xEB\xB2\xB9\xD7\x9C\xEE\x8B\xA0\xDA\xA0" | uniname -r
No LINES variable in environment so unable to determine lines per page.
Using default of 24.
character  byte       UTF-32   encoded as     glyph   range                                   name
        0          0  0084D3   E8 93 93       蓓      CJK Unified Ideographs                  No character name available
        1          3  000286   CA 86          ʆ      IPA Extensions                          LATIN SMALL LETTER ESH WITH CURL
        2          5  00FFFE   EF BF BE       �      Specials                                Undefined
        3          8  00FFFF   EF BF BF       �      Specials                                Undefined
        4         11  00CD11   EC B4 91       촑      Hangul Syllables                        HANGUL SYLLABLE COLG
        5         14  007799   E7 9E 99       瞙      CJK Unified Ideographs                  No character name available
        6         17  00FFFD   EF BF BD       �      Specials                                REPLACEMENT CHARACTER
        7         20  007799   E7 9E 99       瞙      CJK Unified Ideographs                  No character name available
        8         23  00BCB9   EB B2 B9       벹      Hangul Syllables                        HANGUL SYLLABLE BET
        9         26  0005DC   D7 9C          ל      Hebrew                                  HEBREW LETTER LAMED
       10         28  00E2E0   EE 8B A0             Private Use Area - Conlang Xaini        No character name available
       11         31  0006A0   DA A0          ڠ      Arabic                                  ARABIC LETTER AIN WITH THREE DOTS ABOVE
```

Our current UTF-8 conversion code passes those characters through as such because they're valid byte sequences, even though they probably shouldn't be. This part should be fixed, especially the "Private Use Area" values. Those should definitely be left as escaped characters.

The larger question is whether or not we should move to an all-or-nothing model for converting strings of bytes to UTF-8. Right now we convert whatever we can but escape anything that's valid sequence. Does it make more sense to try to do the conversion, but if any one sequence fails it means the entire string should be escaped?

**Comment by rsmmr** [comment]
> Does it make more sense to try to do the conversion, but if any one sequence fails it means the entire string should be escaped?

I'd leave at least ASCII characters in still, so maybe escape what's not ASCII when it doesn't decide at UTF8 as a whole?

About which code points to show, I don't think that's really solvable: either we decode UTF-8 or we don't; either choice will be wrong in some cases based on semantics; but not sure we can say which codeponts are "ok" vs "not ok".  I think people will just have to decide in the end if they want UTF8 logs or not (through the option).

**Comment by timwoj** [comment]
>  I think people will just have to decide in the end if they want UTF8 logs or not (through the option).

This issue originally stemmed from Seth's UTF-by-default PR, and a quite-broken test that came from his changes. I guess the question is whether we can come to some sort of heuristic that says "this can't really be a valid UTF-8 string, can it?".

**Comment by sethhall** [comment]
Agreed Robin!  I would expect that we either treat the whole string as UTF-8 or we treat the whole string as ASCII (with all appropriate escaping in place)

**Comment by sethhall** [comment]
Tim and I have discussed some possible heuristics to decide when and how we handle escaping for UTF8 strings.  Is this the right place to begin discussing those heuristics?

**Comment by rsmmr** [comment]
Sure, as good as any. :)

**Comment by sethhall** [comment]
What it looks like Tim implemented so far is if there are "specials" or "private use area" code points in the unicode that we probably aren't looking at valid unicode bytes and we should fall back to "normal" ASCII escaping for the entire string.

We had a bit of discussion about possibly extending this even to comparing the number of code groups that the string contains.  The example that Tim showed above had something like 5 code groups (ignoring the private use area stuff) which really starts to seem like it's not legitimate unicode.  Either way we aren't destroying data in anyway, we're just choosing whether or not we hex escape the bytes.

**Comment by timwoj** [comment]
> We had a bit of discussion about possibly extending this even to comparing the number of code groups that the string contains. The example that Tim showed above had something like 5 code groups (ignoring the private use area stuff) which really starts to seem like it's not legitimate unicode.

This sounds like a good idea to me, but I wonder how we'd even begin to implement it without some sort of external library. Keeping track of the valid blocks could be brutal. For example, just within the Basic Multilingual Plane, there's currently 160 blocks of varying lengths.

**Comment by rsmmr** [comment]
Spicy is using https://juliastrings.github.io/utf8proc/, which is nice, small C library for various UTF8 operations.
