### ISSUE TITLE
How to install earlier version?

### ISSUE THREAD

**Issue by davehouser1** [zeek/zeek#1585]
I tried downloaded 4.0.0-rc2 (need to use this version for testing of a older plugin) tag.
After untar, and trying to run `./configure` I notice that many files are missing. (Examples: no cmake files, a lot of files in auxil, etc.)

I tried git cloning the latest version and noticed the same thing. 
I then used git clone --recursive and all files then were downloaded. 

Why are the tagged older version tar balls / zip compressions not including these files?

Maybe I am missing it in the install instructions found [here](https://docs.zeek.org/en/current/install.html#installing-from-source), but what are the specific steps to install older version of zeek?

**Comment by 0xxon** [comment]
Hi,

all packaged downloads of Zeek include all files that you need to compile Zeek. The best source for old versions is our download server at https://download.zeek.org. Alternatively, the assets at https://github.com/zeek/zeek/releases also contain all files.

If you clone a specific version of Zeek with git, you will have to tell git to also clone the submodules either using `git clone --recursive`, or - in a checkout - using `git submodule update --recursive --init`.

This is nothing that we really can influence on our side - this is just how git submodules work. If you tell github to create you a zip of a specific revision, it will also not have the submodule files. This is nothing that we can influence/change.

Please also note that this is not a bug and we typically do not provide user support at this address. Questions like this are best answered using Slack, or our mailing list. Both of these are followed by Zeek developers and professional users. You can join here:

Mailing list: https://lists.zeek.org/mailman3/lists/zeek.lists.zeek.org/

Slack: https://zeek.org/community/

 Johanna
