### ISSUE TITLE
Non Default LogDir

### ISSUE THREAD

**Issue by geeksfn** [zeek/zeek#1588]
I'm trying to change the default LogDir to something like LogDir = /newdir/zeek/logs. When I do deploy I get a permissions error:

`Error: cannot create a directory on node worker-1-1
Error: mkdir: cannot create directory ‘/newdir’: Permission denied
`

I've made sure the perms are correct and the zeek user is the owner for /newdir/zeek and all its child folders. Any pointer on this issue is appreciated.

**Comment by timwoj** [comment]
Hi,

We don't use GitHub issues for support questions. Questions like this are best answered using on either slack or our mailing list, which is both are frequented by Zeek developers and professional users. You can join here:

Mailing list: https://lists.zeek.org/mailman3/lists/zeek.lists.zeek.org/

Slack: https://zeek.org/community/
