### ISSUE TITLE
IPv4 regex matching can be too aggressive

### ISSUE THREAD

**Issue by alsmith** [zeek/zeek#1589]
xref: GH-340

I have a report that within the SMTP Received: parsing, the Zeek IPv4 regex match can match unintended things. For example:

Received: from ....
by mx.google.com with ESMTPS id i24si1414282qtr.101.2021.03.03.16.28.33

Is parsed into the json path as "21.3.3.16" due to the "21.03.03.16" string.

In scripts/base/protocols/smtp/main.zeek, mime_one_header() is calling find_address_in_smtp_header() if it's parsing a Received: line, which then calls extract_ip_addresses() in scripts/base/utils/addrs.zeek

And extract_ip_addresses() looks for anything that it can find that it thinks is an IPv4 or IPv6 address, without also checking if it's surrounded by either whitespace, nor parentheses, nor square brackets - pulling all the Received lines out of my inbox, it appears that an actual IP address seems to be always surrounded by either whitespace, round brackets or square brackets - refining the regexes for Received: parsing probably ought to keep that in mind.

**Comment by timwoj** [comment]
Is it possible to provide a pcap that triggers this so I can use it for btest coverage?

**Comment by alsmith** [comment]
Here's one that ought to trigger the problem.
[rcvd.zip](https://github.com/zeek/zeek/files/6653434/rcvd.zip)

**Comment by timwoj** [comment]
@alsmith See if the above commit does what you want it to do. In testing with your attached pcap, smtp.log didn't have the random extracted IP address in the log data anymore.

**Comment by alsmith** [comment]
Commit looks good - thankyou for the fix !
