### ISSUE TITLE
initialization of "int" record fields fails for unsigned integers 

### ISSUE THREAD

**Issue by jsiwek** [zeek/zeek#159]
Moved from https://bro-tracker.atlassian.net/browse/BIT-1759

Created by Daniel Thayer at 2016-11-24T12:09:43.312-0600:
> The following script demonstrates how initialization is not consistent with
> assignment for the "int" type:
> 
> ```
> type myrecord: record {
>     ii: int;
> };
> 
> global globalfail: myrecord &redef;
> redef globalfail = [$ii = 7];
> 
> event bro_init()
> {
>     local fail1 = myrecord($ii = 7);
>     local fail2: myrecord = record($ii = 7);
>     local fail3: myrecord = [$ii = 7];
> 
>     local ok1: myrecord;
>     ok1$ii = 7;
> }
> ```
> 
> Running this script gives the following result:
> error in ./test.bro, line 6 and count: type clash for field "ii" ((coerce [$ii=7] to myrecord) and count)
> error in ./test.bro, line 6: bad record initializer ((coerce [$ii=7] to error))
> error in ./test.bro, line 10 and count: type clash for field "ii" ((coerce [$ii=7] to myrecord) and count)
> error in ./test.bro, line 11 and count: type clash for field "ii" ((coerce [$ii=7] to myrecord) and count)
> error in ./test.bro, line 12 and count: type clash for field "ii" ((coerce [$ii=7] to myrecord) and count)
> 
> Changing the "7" to "+7" in the script for all occurrences of "7" except the last one makes the script work as expected.
> 

Comment by Jon Siwek at 2018-09-13T13:25:53.081-0500:
> Another example, for reference, in [BIT-1762](https://bro-tracker.atlassian.net/browse/BIT-1762).

**Comment by timwoj** [comment]
Should I assume that we can always set a count value to an int for this? I'm looking at `RecordCoerceExpr::RecordCoerceExpr` in Expr.cc, and it seems easy enough to just check for that combination in the error case there and skip it. I realize that `int` is signed and `count` is unsigned so there might have to be a minor amount of error checking there for size as well.

**Comment by jsiwek** [comment]
Yes, I think we can allow coercion of a `count` to an `int`.  More generally we can allow coercion of any arithmetic type `count`, `int`, or `double` to each other, and then whatever standardized coercion logic we use for that could be responsible for checking at run-time if a coercion results in narrowing / loss of information (right now looks like we don't check for such unsafe arithmetic coercion).

So yeah, the way I'd do this seems there's two parts: 

1. Change the `RecordCoerceExpr::RecordCoerceExpr` ctor like you mentioned to not make a fuss about any mix of arithmetic field types
2. Change `RecordCoerceExpr::Fold` to perform the coercion of arithmetic fields once the expression has been evaluated at run-time and we have the actual values to work with.

For (2) looks like that would be done before here:

https://github.com/zeek/zeek/blob/4ff473a59622e777c69da25c9cf5b96f727914a9/src/Expr.cc#L4258

Probably the `IsArithmetic` macro and `check_and_promote` function are relevant and/or helpful to use here.

An alternative approach I was thinking of would involve inserting `ArithCoerceExpr` at the relevant nodes in the AST, but I think we'd be limited to only doing that for `RecordConstructorExpr`, and that's not the only allowable operand for record coercions: we could coerce from a identifier name, the result of a function call, etc.  And for those, we would not have anything we can go and change/insert in the AST.

**Comment by rsmmr** [comment]
One thing to add: it'd be good to catch unsafe coercions at script intialization time where we can statically determine it. So say I initialise a count to -1, that should be reported immediately, not just later an runtime when the code gets actually executed.

**Comment by timwoj** [comment]
@jsiwek Thanks for the pointers to those two methods. That helps a lot. I think the only thing that `check_and_promote` missed is overflowing an `int` if a large enough `count` is passed into it.

@rsmmr One of my test cases is remapping a global and trying to set a `count` to `-5`. That should cover the initialization-time case, correct?

**Comment by rsmmr** [comment]
Yeah, though not  immediately sure if there might be other cases as well going through a different code path.

**Comment by timwoj** [comment]
I think the only thing left here is conversion to/from double. The current status of these is:

- converting positive count/int to double: working fine
- converting negative int to double: throws fatal error relating to reference-counting and the negative value (I used -5 as a test value).
- converting double to int or count: returns an error about over-promotion of the value, which effectively is an error about narrowing a double value to the other types. It returns that error even if the value will definitely fit (I tried 1.0).

Do I need to worry about the doubles, or is it extremely rare that someone would try to convert a double to one of the integer types?

**Comment by jsiwek** [comment]
> * converting negative int to double: throws fatal error relating to reference-counting and the negative value (I used -5 as a test value).

Sounds like a reference counting bug we ought to address.

> * converting double to int or count: returns an error about over-promotion of the value, which effectively is an error about narrowing a double value to the other types. It returns that error even if the value will definitely fit (I tried 1.0).

Having an error or at least warning message for this case seems nice to me:  can't think of a legit use-case where I'd want to assign something like "1.0" to an int/count.  More likely I intended to use a double for the storage type, but made a mistake.

> Do I need to worry about the doubles, or is it extremely rare that someone would try to convert a double to one of the integer types?

It's rare.  The reference counting issue is still something to try to understand and fix, though, not something we can let slide.

**Comment by jsiwek** [comment]
Fixed via #395
