### ISSUE TITLE
Changes to the behavior of the SSH version field were not documented

### ISSUE THREAD

**Issue by J0eJ0h** [zeek/zeek#1590]
https://github.com/zeek/zeek/commit/3769ed6c6687e5ecf93c3668bebe3c3f7da3d0fb started introducing 0 to the ssh version field for client\server mismatches without documenting the change in behavior.

**Comment by grigorescu** [comment]
I'm wondering if 0 is the right value here, or if it should be an optional value, and it's simply not set if there's a mismatch. Which should also be documented.

**Comment by 0xxon** [comment]
Yup, if I understand everything right - that seems like the most reasonable solution to me here. If the client/server versions mismatch we probably should just not set the ssh version field and, instead, output a weird.

We (obviously) also document this.
