### ISSUE TITLE
Broken build on FreeBSD/PowerPC 

### ISSUE THREAD

**Issue by ckreibich** [zeek/zeek#1591]
Craig Leres reports that our version of Highwayhash breaks on FreeBSD on PowerPC. I can confirm on a VM:
```
[  4%] Building CXX object src/CMakeFiles/zeek_objs.dir/__/auxil/highwayhash/highwayhash/arch_specific.cc.o
/home/christian/zeek/auxil/highwayhash/highwayhash/arch_specific.cc:153:3: error: no matching function for call to 'sysctlbyname'
  sysctlbyname("dev.cpu.0.freq"), &freq, &length, NULL, 0);
  ^~~~~~~~~~~~
/usr/include/sys/sysctl.h:1186:5: note: candidate function not viable: requires 5 arguments, but 1 was provided
int     sysctlbyname(const char *, void *, size_t *, const void *, size_t);
        ^
/home/christian/zeek/auxil/highwayhash/highwayhash/arch_specific.cc:153:58: error: extraneous ')' before ';'
  sysctlbyname("dev.cpu.0.freq"), &freq, &length, NULL, 0);
```
They've [fixed this](https://github.com/google/highwayhash/commit/9490b14905490ae8a595fa35e2ab336647f378f1#diff-bc3479879dc1d18b70cccb9edea11e53e1635e2c6ee810ed7a1c0751d8c613beR153) upstream, so I'm thinking we should pull up our Highwayhash version.

Is there a particular reason we're pointing the submodule at our own fork, not upstream?

**Comment by timwoj** [comment]
> Is there a particular reason we're pointing the submodule at our own fork, not upstream?

Generally we do this to make sure that the commits we depend on always exist. You can definitely update our fork to match upstream though.

**Comment by ckreibich** [comment]
Got it, thanks Tim. I've brought our master in sync with theirs but not yet done anything else.

**Comment by 0xxon** [comment]
> Is there a particular reason we're pointing the submodule at our own fork, not upstream?

In this specific case - we also fixed a bug in highwayhash in the past and first pulled it in through our own repo.
