### ISSUE TITLE
[HTTP] Bad analyse on Emotet malware capture

### ISSUE THREAD

**Issue by jgvt** [zeek/zeek#1598]
Emotet C2 discuss with infected hosts by POST HTTP requests with multipart boundaries sections.
With the pcap available [here](https://github.com/pan-unit42/wireshark-tutorial-Emotet-traffic) we can see that Zeek identified several requests but correcly inspect only the first one.

Here, the http logs of this session: 

    1609951354.805404	CmnCJm1S1luKQC7ijg	10.1.6.206	49783	5.2.136.90	80	1	POST	5.2.136.90	/7u0e9j2avwlvnuynyo/szcm27k/fzb067wy/	5.2.136.90/7u0e9j2avwlvnuynyo/szcm27k/fzb067wy/	1.1	Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E)	-	0	306596	200	OK	-	-	(empty)	-	-	-	FZLrmN1Yfib3JXC6T6	iVOWebWBCLKvFqxScD	-	FM9Psl4fUa9gBZCQQh	-	-

    1609951362.022311	CmnCJm1S1luKQC7ijg	10.1.6.206	49783	5.2.136.90	80	2	-	-	-	-	1.1	-	-	6144	411556	200	OK	-	-	(empty)	-	-	-	-	-	-	FOKNaz1g8KecRiTWhi	-	-

    1609951366.378063	CmnCJm1S1luKQC7ijg	10.1.6.206	49783	5.2.136.90	80	3	-	-	-	-	1.1	-	-	0	473908	200	OK	-	-	(empty)	-	-	-	-	-	-	FoNDxZ3lGCLGrBdTJh	-	-

    1609951370.837569	CmnCJm1S1luKQC7ijg	10.1.6.206	49783	5.2.136.90	80	4	-	-	-	-	1.1	-	-	0	287012	200	OK	-	-	(empty)	-	-	-	-	-	-	FsVY0sBNS0RyFWK55	-	-

    1609951373.724956	CmnCJm1S1luKQC7ijg	10.1.6.206	49783	5.2.136.90	80	5	-	-	-	-	1.1	-	-	0	1172	200	OK	-	-	(empty)	-	-	-	-	-	-	FDuXok3U88iL5gT5Ij	-	-

and in weird logs, we can see "bad_http_request" notifications.

During analysis of issue, I saw that there was no CRLF just after the second boundary and at the end of the packet (see packet 477 in capture). It's maybe a mistake or to escape IDSs. So the contentLine analyzer continue to buffering data (until find CRLF ?).
The next http request is badly parsed (this explain the bad_http_request in weird log).

I think I can patch it in the ContentLine's code (ContentLine_Analyser::DoDeliver) or maybe in the way used to check boundary in mime content.
But before I would like your technical feedback to deal with it in the best way.

Thanks for your help

[Example-1-2021-01-06-Emotet-infection.pcap.zip](https://github.com/zeek/zeek/files/6656535/Example-1-2021-01-06-Emotet-infection.pcap.zip)

**Comment by 0xxon** [comment]
Hi,

taking a superficial look - yes, you  probably are right. And while I assume that this is a protocol violation - we optimally still should be able to correctly parse data like this.

If can contribute a patch that works (and does not break anything else) - that would be very much appreciated.

Johanna

**Comment by jgvt** [comment]
found a fix, internal review is processing

**Comment by 0xxon** [comment]
I just wanted to check how the fix review is going :)

**Comment by jgvt** [comment]
Technical review is done. Pull request submit soon (internal process for the first publication can be long)

**Comment by 0xxon** [comment]
That's great - thank you for the update.

**Comment by jgvt** [comment]
https://github.com/zeek/zeek/pull/1691

**Comment by jgvt** [comment]
PR break zeek-testing btest, rework in progress.
If you have other complains/enhancement ideas, please share

**Comment by jgvt** [comment]
PR Updated, tests seem better
