### ISSUE TITLE
Zeekctl segfault

### ISSUE THREAD

**Issue by kuba00739** [zeek/zeek#1611]
Hello,

compilation of zeek is successful but running zeekctl results in Segmentation fault (core dumped) when it tries to import ZeekCtl, ZeekControlError or CommandSyntaxError.

Pdb output:

`(Pdb) next`
`> /usr/local/zeek/bin/zeekctl(17)<module>()`
`-> from ZeekControl.zeekctl import ZeekCtl, ZeekControlError, CommandSyntaxError`
`(Pdb) next` 
`Segmentation fault (core dumped)`

OS: centos 8
Configuration:
`./configure --with-pcap=/opt/pfring` (tried to compile it to work with PF_RING, same steps as https://docs.zeek.org/en/master/cluster-setup.html#pf-ring-config)

What additional data should I provide?

Thank you in advance for your help

**Comment by timwoj** [comment]
This is likely the same issue as https://github.com/zeek/broker/issues/187. I'm going to close this one in favor of that.

To work around it, pass `--disable-python` to your call to configure.

**Comment by kuba00739** [comment]
Thank you for your quick response. The solution works :)
