### ISSUE TITLE
Provide Docker images as CI side effect

### ISSUE THREAD

**Issue by mavam** [zeek/zeek#1625]
As a Zeek user and developer of downstream solutions, I'd like to rely on official Docker images that bundle the software in a coherent manner. The expectation would be to have the following pieces work together in a single images:

- Zeek binary (for running Zeek
- Zeek sources (for plugin development)
- Broker, including Python bindings
- `zkg` (for installing packages)

I'm sure there are more pieces that could be setup out-of-the-box, e.g., `zeek-ctl`, but the focus is *not* on providing a Docker images to run Zeek in a variety of different settings. For that, separate, more specific layers that build on the base image seem to be more appropriate.

From a user/community perception point of view, I'd expect the (most trustworthy) vendor to ship and maintain the official images, rather than having a 3rd party maintain them.

The heavy lifting involves writing the Dockerfile(s) once and integrating it into CI. Ideally, we'd have images for every push to master, but starting out with a CI artifact (and subsequent push to DockerHub) would already be good starting point.

**Comment by rsmmr** [comment]
let's see if we can target this for 4.2
