### ISSUE TITLE
Adding coefficient of variation  in SumStats::Calculation

### ISSUE THREAD

**Issue by thibaultbl** [zeek/zeek#1640]
For personal use, I developed a SumStats::Calculation for the coefficient of variation (standard deviation / average), sort of standard deviation relative to the mean.

Référence:
[https://en.wikipedia.org/wiki/Coefficient_of_variation](https://en.wikipedia.org/wiki/Coefficient_of_variation)

Example:
[https://gitlab.com/thibaultB/variation_coefficient_example](https://gitlab.com/thibaultB/variation_coefficient_example)

Would it be interesting to add it to the main code base ?

**Comment by 0xxon** [comment]
Hi @thibaultbl,

the best way to publish this and to make it available to other Zeek users is probably be to create a package and add it to the package manager. https://docs.zeek.org/projects/package-manager/en/stable/package.html has the details on how to do that - you basically just have to publish the script on github with a little bit of metadata - and then create a PR with the github URL against our packages database.
