### ISSUE TITLE
SumStats issue with function event Conn::log_conn

### ISSUE THREAD

**Issue by YHChenCHT** [zeek/zeek#1642]
I used SumStats framework for counting connection of "id.resp_h", when i used event Conn::log_conn(rec: Conn::Info) as a trigger event, there is deviation in statistical result. 
The real situation is i used zeek for analyzing a pcap file, and there are 696 connections in conn_log, however, the there are only 599 connections been recorded, and there are two situations in missed recording connections. 
First, there are duplicate connections by a id.resp_h, but it is recorded as one connection only.
Second, there is totally missed recorded of connections.
Why was there deviation in statistical result?

**Comment by 0xxon** [comment]
Hi,

We don't use GitHub issues for support questions. Questions like this are best answered using our  mailing list, which is followed by Zeek developers and professional users. You can join here:

https://lists.zeek.org/mailman3/lists/zeek.lists.zeek.org/

Once you receive confirmation you’ve been added to the list, send this question there.

 Johanna
