### ISSUE TITLE
Coordinating enable/disable analyzers between multiple scripts

### ISSUE THREAD

**Issue by anthonykasza** [zeek/zeek#1678]
Zeek's default base scripts currently disable analyzers, for protocols which support encryption, after the protocol's handshake and once a connection begins using encryption. Module namespaces which do this include `SSL`, `SSH`, and `RDP`. These namespaces each export a boolean option named `disable_analyzer_after_detection` which controls some logic that wraps a call to the [disable_analyzer](https://docs.zeek.org/en/master/scripts/base/frameworks/analyzer/main.zeek.html#id-Analyzer::disable_analyzer) bif. These options are essentially a global setting for _all_ connections of that protocol type. Either all encrypted messages of a connection are processed or none of the encrypted messages of a connection are processed.

More granular control of analyzers would be useful. One use case is scripts which rely on events generated from encrypted messages, such as the [ssl_encrypted_data](https://docs.zeek.org/en/master/scripts/base/bif/plugins/Zeek_SSL.events.bif.zeek.html#id-ssl_encrypted_data) event. One can imagine a script which doesn't want the SSL analyzer to be disabled until some number of `ssl_encrypted_data` events are raised.

One way to enable more granular control would be to change the `disable_analyzer_after_detection` options from `bool` types to `count` types. The name of the variable should likely be renamed to something like `registered_analyzer_uses` or similar. The default value of the counter could be zero. New scripts could then "register" themselves by incrementing that counter's value. Upon satisfying some condition, new scripts would then need to decrement the counter's value to "unregister" themselves. Existing logic in the base scripts would need to be changed to ensure a namespace's counter equals zero before calling `disable_analyzer` for a particular connection.

**Comment by ckreibich** [comment]
It's interesting to compare this with the file analysis framework's analyzers — there, you have to explicitly add analyzers, specifying which event handler you want invoked. You can later remove such analyzers, and the involved state allows you to do this selectively:

```
event file_stream_event_1(f: fa_file, data: string)
        {
        print fmt("file_stream_event_1: File %s, content '%s'", f$id, data[:10]);
        Files::remove_analyzer(f, Files::ANALYZER_DATA_EVENT, [$stream_event=file_stream_event_1]);
        }

event file_stream_event_2(f: fa_file, data: string)
        {
        print fmt("file_stream_event_2: File %s, content '%s'", f$id, data[:10]);
        }

event file_new(f: fa_file)
        {
        Files::add_analyzer(f, Files::ANALYZER_DATA_EVENT, [$stream_event=file_stream_event_1]);
        Files::add_analyzer(f, Files::ANALYZER_DATA_EVENT, [$stream_event=file_stream_event_2]);
        }
```
With protocol analyzers you don't explicitly express interest, so one cannot selectively opt out.

**Comment by anthonykasza** [comment]
Protocol analyzers do have `Analyzer::register_for_port`, `Analyzer::schedule_analyzer`, and DPD mechanisms to express interest in associating an analyzer with a connection. And, `Analyzer::disable_analyzer` can be used to explicitly turn an analyzer off for a connection.

As it exists today, turning an analyzer off after encryption is a global setting. It either happens or it doesn't. By setting `disable_analyzer_after_detection` to F, scripts can choose to turn analyzers off after some condition is satisfied by manually calling `Analyzer::disable_analyzer` - for example, by calling the function after 10 seconds of a connection has passed or after 2KB of data has been exchanged.

My suggestion is a way to coordinate the calling of `Analyzer::disable_analyzer` between scripts which don't have knowledge of each other. That way, one script calling `Analyzer::disable_analyzer` doesn't do so before all scripts have had a chance to naysay.

There might be a parallel here to what `Log::PolicyHook` provides but for disabling analyzers instead of writing log entries. Perhaps using counts instead of bools isn't the best solution. Perhaps using hooks is more appropriate.

**Comment by awelzel** [comment]
> There might be a parallel here to what Log::PolicyHook provides but for disabling analyzers instead of writing log entries. Perhaps using counts instead of bools isn't the best solution. Perhaps using hooks is more appropriate.

The hooks direction seems nice and elegant, let me outline something:

* Introduce a new global hook `disabling_analyzer(c: connection, tag: Analyzer::Tag)` (or in some module namespace, wasn't sure where).
* This hook executes whenever analyzer `Analyzer::disable_analyzer()` has found a connection and is about to disable the analyzer for it.

* A hook implementation can veto disabling by `break`ing from the hook
* Scripts would essentially use the inverse condition to `break` from the hook as they would use before they decide to call `disable_analyzer()` (connection duration long enough, enough bytes transferred, etc.).


However, the repeated hook implementations may put too much burden on script writers as compared to a "reference-counted" approach? But could also see both being combined (checking a reference count in the hook) if down the road it turns out to cause a lot of repeated code?
