### ISSUE TITLE
please help me

### ISSUE THREAD

**Issue by KONEONE** [zeek/zeek#1686]
I encountered the following problems when configuring the Zeek cluster.
```text
updating nodes ...
Host key verification failed.
Error: cannot create a directory on node worker-1
Error: Failed to establish ssh connection to host 168.192.64.30: [Errno 32] Broken pipe
[ZeekControl] > Host key verification failed.
```
But，the manager and the worker can be connected without a password.
```shell
ssh 168.192.64.30
```
The above script does not require a password when running

**Comment by grigorescu** [comment]
Please note that this is not a bug - and for support discussions, [Slack](http://bit.ly/ZeekOrgSlackInvite) or our [email groups](http://mailman.icsi.berkeley.edu/mailman/listinfo/zeek) are probably the better venues in which you will get exposure to more people and much quicker response times.
