### ISSUE TITLE
Find overuse of zeek::id::find in analyzers

### ISSUE THREAD

**Issue by timwoj** [zeek/zeek#1699]
https://github.com/zeek/zeek/pull/1698 pointed out a few cases in release/4.0 where we were calling `zeek::id::find` for every packet, causing a performance problem. That change needs to be ported to `master` since most of the code around that PR has changed a bit since the 4.0 branch. We should also go through and find other places the same pattern exists and fix them as well.

**Comment by timwoj** [comment]
https://github.com/zeek/zeek/pull/1701 has an example of how to fix this, but it's rather involved. This might not be worth the effort for any savings gain we may encounter.

**Comment by awelzel** [comment]
@timwoj - how about closing this and if profiling in production environments indicates there's issues fix these specifically?
