### ISSUE TITLE
half duplex http connections can cause unbounded state growth

### ISSUE THREAD

**Issue by JustinAzoff** [zeek/zeek#1705]
If zeek sees half duplex http traffic it might result in unbounded state growth.

If zeek is seeing http replies but not requests, everything works OK. zeek will log the replies as they show up to the http log with the request fields unset.

if zeek is setting http requests but not replies, `c$http_state$pending` grows unbounded, and requests are not logged until the connection closes or zeek stops, at which point they all get logged at once.  This can be days later and the pending list could contain tens of thousands of requests.

Attached is http_many_one_connection.pcap, which is just from apachebench running against a server with the keepalive option enabled.

If you run it with this script and different filters you can see the problem:

```
global requests: count=0;
global replies: count=0;

event http_request(c: connection, method: string, original_URI: string,
                   unescaped_URI: string, version: string)
{
    ++requests;
}

event http_reply(c: connection, version: string, code: count, reason: string)
{
    ++replies;
}

hook HTTP::finalize_http(c: connection)
{
    print "Pending", |c$http_state$pending|;
}

event zeek_done()
{
    print "Requests", requests;
    print "Replies", replies;
}

```

```
justin@mbp:/tmp$ zeek -r ~/pcaps/http_many_one_connection.pcap ./h.zeek 
Pending, 0
Requests, 10000
Replies, 10000
justin@mbp:/tmp$ zeek -r ~/pcaps/http_many_one_connection.pcap ./h.zeek -f 'src port 8080'
Pending, 0
Requests, 0
Replies, 10000
justin@mbp:/tmp$ zeek -r ~/pcaps/http_many_one_connection.pcap ./h.zeek -f 'dst port 8080'
Pending, 10000
Requests, 10000
Replies, 0
```

This is somewhat similar to #289 The fix is likely different though.  We either need some sort of time or count (or both) threshold to cause pending messages to be flushed.

[http_many_one_connection.zip](https://github.com/zeek/zeek/files/6901156/http_many_one_connection.zip)

**Comment by JustinAzoff** [comment]
This sort of can fix things

```
event http_request(c: connection, method: string, original_URI: string,
                   unescaped_URI: string, version: string) &priority=-10
{
    if ( |c$http_state$pending| < 10)
        return;

    local now = network_time();
    local to_delete: vector of count = vector();
    for ( r, info in c$http_state$pending ) {
        # We don't use pending elements at index 0.
        if ( r == 0 ) next;
        if (T || now - info$ts > 300secs) {
            Log::write(HTTP::LOG, info);
            to_delete += r;
        }
    }
    for (idx in to_delete) {
        r = to_delete[idx];
        delete c$http_state$pending[r];
    }
}
```

the ```
        if (T || now - info$ts > 300secs) {
```

is the part that needs to be better.. Ideally the pending requests would be sorted by age, but it's an unsorted table.. so this is not really setup in memory the way we need it.  We want to do something like

```
    for each pending request ordered by oldest first:
        if this request is older than 5 minutes:
            log and remove it
        else
            break. stop looping because every request will be older.
```

**Comment by 0xxon** [comment]
Hum. Could we potentially solve that by having an &create_expire of ~5min on http_state$pending? That should have enough information that it should be able to do that by itself. 

I admittedly have no idea if a create_expire works on record elements - I quickly checked and saw no reason why it should not work...

**Comment by JustinAzoff** [comment]
oh, wow, yeah.. create_expire with an expire_func would be a lot easier!  duh!

the expire func could even check the size of the table and not bother expiring just yet... use a 1 minute timer.. if the size is small, do nothing and return a time in the future.. if the table is 100 items at that point, expire things for real

**Comment by JustinAzoff** [comment]
Improved pcap:

has the tcp handshake, which makes zeek happier and is slowed down so you can use it with --pseudo-realtime=1

[http_many_one_connection_with_handshake_slow.zip](https://github.com/zeek/zeek/files/6903412/http_many_one_connection_with_handshake_slow.zip)

Initial tests does show that this should be fixable:

```
diff --git a/scripts/base/protocols/http/main.zeek b/scripts/base/protocols/http/main.zeek
index d63a5efa4..2a931fcb1 100644
--- a/scripts/base/protocols/http/main.zeek
+++ b/scripts/base/protocols/http/main.zeek
@@ -85,11 +85,13 @@ export {
                range_request:           bool      &default=F;
        };
 
+       global http_pending_expired: function(tbl: table[count] of Info, idx: count): interval;
+
        ## Structure to maintain state for an HTTP connection with multiple
        ## requests and responses.
        type State: record {
                ## Pending requests.
-               pending:          table[count] of Info;
+               pending:          table[count] of Info &create_expire=10mins &expire_func=http_pending_expired;
                ## Current request in the pending queue.
                current_request:  count                &default=0;
                ## Current response in the pending queue.
@@ -151,6 +153,18 @@ event zeek_init() &priority=5
        Analyzer::register_for_ports(Analyzer::ANALYZER_HTTP, ports);
        }
 
+
+function http_pending_expired(tbl: table[count] of Info, idx: count): interval
+{
+       local rec = tbl[idx];
+       #If there is a status code, don't expire it.
+       #Can I just return -1 here to remove the timer?
+       if (rec?$status_code)
+               return 5mins;
+       Log::write(HTTP::LOG, rec);
+       return 0secs;
+}
+
 function code_in_range(c: count, min: count, max: count) : bool
        {
        return c >= min && c <= max;
```

I think implementing this sort of logic would work out well:

Number of outstanding requests | How old it should be before being logged
-- | --
< = 1 | 10mins
< = 10 | 5mins
otherwise | 1mins

But might want to think about what the edge cases could be first.  There is definitely a point where it would be clear that the http sessions are not seeing both directions and it should start flushing records

**Comment by timwoj** [comment]
@JustinAzoff is this something you want to stick into a PR? I'm not sure it'll make it at this point for 4.2, but we could definitely get it in for the next cycle.

**Comment by JustinAzoff** [comment]
Oh, yes, I forgot about this.  No rush.  I wanted to look into that comment:

```
+       #If there is a status code, don't expire it.
+       #Can I just return -1 here to remove the timer?
```

I'm not sure if there is a way for expire_func to return something to indicate that the item should never expire.  triggering every 5mins and doing nothing works, just isn't as clean.

**Comment by awelzel** [comment]
Possibly cause of OOMs reported by [h-mikami on Slack](https://zeekorg.slack.com/archives/CSZBXF6TH/p1692608209819579?thread_ts=1685587437.627989&cid=CSZBXF6TH).

**Comment by awelzel** [comment]
These aren't exactly the same issues as the half-duplex scenario, but hopefully addressing state growth can address these, too.

* A single dropped packet from the responder side triggers unbounded state growth. Then the analyzer only ever creates http_request events and ignores the responder side after a drop. This pcap causes 1000 pending requests after a single dropped packet from the server:

  [1000-nginx-missing-first-response.pcap.gz](https://github.com/zeek/zeek/files/12438400/1000-nginx-missing-first-response.pcap.gz)

* Additionally, someone faking HTTP traffic, producing two extra responses after a request can cause de-synchronization of request/response counters and unbounded state growth too.

  This pcap contains 200 GET requests, the first one being replied to with 3 responses. It results in 199 pending requests at finalization and  401 http.log entries:

  [http-desync-request-response.pcap.gz](https://github.com/zeek/zeek/files/12438521/http-desync-request-response.pcap.gz)
