### ISSUE TITLE
Improve signaling of deprecated code

### ISSUE THREAD

**Issue by jsiwek** [zeek/zeek#171]
Moved from https://bro-tracker.atlassian.net/browse/BIT-1474

Created by Matthias Vallentin at 2015-09-06T19:42:56.730-0500:
> Based on discussion in [BIT-1411](https://bro-tracker.atlassian.net/browse/BIT-1411), we need a better mechanism for deprecating code. In particular, Vern suggested the attribute `&deprecate=expr` syntax where `expr` would be an expression that evaluates at the point of use of the deprecated construct and would show the user a hint on how to migrate.

Comment by Vern Paxson at 2015-09-06T19:51:49.476-0500:
> One thing to add is the need for some sort of option/context such that users can control when the message about the deprecated variable gets displayed.

Comment by Jon Siwek at 2015-09-08T09:13:35.862-0500:
> I had already done "&deprecated" (as part of 2.4 I believe).  But don't think I allowed it to be assigned an expression which could contain more info or had a global flag to disable the warnings.  (Just trying to provide input on what's already available, but both those ideas do seem like useful features to add).

Comment by Matthias Vallentin at 2015-09-08T20:28:32.036-0500:
> Ah, I missed that. That's definitely something we can work with. Let's keep this ticket open for now to track the enhancement with evaluated expressions.

**Comment by jsiwek** [comment]
An additional convention to think about adopting is to include in the deprecation warning/expression a reference to the last version number we intend for it to be available (making it easier to audit which deprecated code can actually be removed at any point in time).  Applicable to both script-layer and core code deprecations.

**Comment by timwoj** [comment]
After spending a little time with this, I'm thinking of one of the following:

- The existing `&deprecated` attribute can gain an optional `=<version>` at the end that denotes the version that the deprecation will be removed. A second attribute `&deprecationHelp` or some other name can take some text that returns some help for how to fix the deprecated field.
- The existing `&deprecated` attribute can gain an optional `=<version>:<help>` and which denotes everything in one line and we can split it during handling. Possibly the `:<help>` part could be optional as well.

**Comment by jsiwek** [comment]
> * The existing `&deprecated` attribute can gain an optional `=<version>:<help>` and which denotes everything in one line and we can split it during handling. Possibly the `:<help>` part could be optional as well.

Nice ideas, I was thinking along these lines, but even simpler might be to just accept an arbitrary string and leave it to convention to stick the version number in there.  So it could work like:

* Allow `&deprecated` with nothing further (we already have this)
* Allow `&deprecated="whatever string I want"`.

Then convention or "Good Practice" for the later would be to write it like `&deprecated="Remove in 3.1.0.  Use 'foo' instead."`

**Comment by jsiwek** [comment]
Fixed via #430
