### ISSUE TITLE
Crash 4.1.0-rc1 - Manager: zeek-4.1.1-rc1/auxil/broker/caf/libcaf_core/caf/load_inspector_base.hpp:46

### ISSUE THREAD

**Issue by initconf** [zeek/zeek#1710]
This is a manager crash on `4.15.0-142-generic #146-Ubuntu` running with Address Sanitizer enabled. I don't think I have seen this crash before. 

Mostly FYI - Other workers were crashing (for various other reasons) - may be that has a role in manager crash given this seems to be in broker. 

I have coredump with me if you want to inspect - let me know  - for future here is the pointer to the coredump :  `/usr/local/zeek/spool/tmp/post-terminate-manager-2021-08-02-08-57-47-612-crash`

Here attached is the backtrace file. 
[gdb.txt](https://github.com/zeek/zeek/files/6919135/gdb.txt)

**Comment by timwoj** [comment]
We haven't seen this again in further testing. It was likely caused by a version mismatch in the build.
