### ISSUE TITLE
Crash: zeek-4.1.1-rc1/auxil/broker/caf/libcaf_core/caf/variant.hpp:307

### ISSUE THREAD

**Issue by initconf** [zeek/zeek#1714]
Forgive me if this is a repeat of a previously filed issue - I cannot quite make the distinction between this one and past ones. 

Here is attached backtrace: 
[gdb.txt](https://github.com/zeek/zeek/files/6919996/gdb.txt)

Coredump anchor: tmp/crash-1627945152-1714

**Comment by Neverlord** [comment]
If this is ASAN build - do you still have the ASAN output? This crashed in `operator new` from `libasan.so`, so either ASAN terminated the program with some diagnostic or it may be that the program was just running out of memory.

**Comment by timwoj** [comment]
We didn't see this again in further testing. We had some other crashes in `new` that were related to the asan build running out of memory and aborting, so this was probably another case of that.
