### ISSUE TITLE
Crashing on start with diag not giving usable info

### ISSUE THREAD

**Issue by SargenBK** [zeek/zeek#1720]
While attempting to run zeek after a hiatus waiting for a part to come in, when i attempt to start zeek through zeek control it does not seem to work. when i then check the status it shows that it crashed. After running diag it gives the output:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 55, in <module>
  File "<string>", line 6, in w
BrokenPipeError: [Errno 32] Broken pipe

I'm not experienced with this enough to even know where to start to look. Does anyone know what could have caused this or how to cleanly reinstall zeek?

**Comment by 0xxon** [comment]
Hi,

this sounds like more of a support question than a bug. Our Slack/mailing lists are better venues for this - seehttps://zeek.org/community/
