### ISSUE TITLE
Directory not found in zeekctl.cfg

### ISSUE THREAD

**Issue by chrisvel** [zeek/zeek#1721]
I am experimenting with zeekctl.cfg settings and I am following the README instructions.

I am setting up

```
ZeekBase=/opt/zeek
LogDir=${ZeekBase}/logs
```

but I am getting an error:

```
Error: zeekctl option "logdir" directory not found: ${ZeekBase}/logs
```

what am I doing wrong ?

**Comment by timwoj** [comment]
This is likely a configuration issue. We don't use Github for support questions. You might repost this on the mailing list or ask on the community Slack server. See https://zeek.org/community/ for info on connecting to those.

**Comment by chrisvel** [comment]
The thing is that the settings work fine with `PolicyDir`, so either there's a bug in using `ZeekBase` or I am doing something wrong, that's why I asked. I've already used the Slack server but didn't get a valuable response.

**Comment by rsmmr** [comment]
Indeed, that's not supported. Slack discussion here: https://zeekorg.slack.com/archives/CSZBXF6TH/p1628231648042000
