### ISSUE TITLE
An bug about scripts\base\frameworks\software\main.zeek

### ISSUE THREAD

**Issue by huantre** [zeek/zeek#1735]
`function found(id: conn_id, info: Info): bool
    {
    if ( ! info$force_log && ! addr_matches_host(info$host, asset_tracking) )
        return F;
`
when force_log is True, addr_matches_host has no chance to judge.
asset_tracking will be ALL_HOSTS, even if it is LOCAL_HOSTS at default.

**Comment by ckreibich** [comment]
That's the intent here, no? The caller has identified some software, describes it in the `info` record, and sets `force_log = T` if they want to side-step any host-matching.

**Comment by 0xxon** [comment]
Looks like this is desired behavior. Please re-open if you think this is not the case.
