### ISSUE TITLE
Attributes are not checked for consistency

### ISSUE THREAD

**Issue by jsiwek** [zeek/zeek#174]
Moved from https://bro-tracker.atlassian.net/browse/BIT-1982

Created by Vern Paxson at 2018-09-05T05:48:01.572-0500:
> The following script doesn't report any problems.  Seems it should, to catch bugs. [^attr-conflict.bro] 

Attachment https://bro-tracker.atlassian.net/secure/attachment/21474/attr-conflict.bro:
```
global a: table[count] of count
        &default = 10 &default = 9
        &read_expire = 5 sec &read_expire = 1 min;
print a[5];

```

**Comment by timwoj** [comment]
What error is expected here? That the attributes are being duplicated?

**Comment by rsmmr** [comment]
Not sure what we are already checking for, but in addition to reporting duplicates probably also a general sanity check that (1) only attributes are used that are supported in that context (e.g., not `&raw_output`), and that there attributes aren't contradictory (e.g., two different types of expire attributes). Doesn't need to be perfect, though, so whatever is obvious/easy to add.

**Comment by rsmmr** [comment]
> My thought is to silently accept multiple `&log` attrs on anything (internally can compress to a single attr) since there's not really an ambiguous interpretation of what the behavior of that should be.

Agree.
