### ISSUE TITLE
ill-formed table constructor leads to an internal error

### ISSUE THREAD

**Issue by vpax** [zeek/zeek#1740]
In 4.0 (and a recent branch off Master that I also checked), the following:
> print table(3=5, 4=9);

results in:
> bad initializer (3 = 5)
fatal error in error: Type::AsTableType (error/table) (error)

**Comment by timwoj** [comment]
I think the error here is actually correct, if a little lacking in information about what's wrong. According to all of the examples in the documentation for `table` (https://docs.zeek.org/en/master/script-reference/types.html#type-table), the key value should always be a list type even if the key type is a simple type like `count`. Changing it to `print table([3]=5, [4]=9)` doesn't print an error and prints the correct output.

That said it would be easy to update the error message to at least give more information about what's wrong, something like:

```
error in ./1740.zeek, line 8: bad initializer, first operand should be a list (3 = 5)
fatal error in error: Type::AsTableType (error/table) (error)
```

**Comment by vpax** [comment]
Yeah, it's wrong, the point is that it shouldn't generate an internal error (exposing `Type::AsTableType`).  Basically, the second error message shouldn't happen, the first one gets the point across.
