### ISSUE TITLE
invoking a non-hook with "hook" does not complain

### ISSUE THREAD

**Issue by vpax** [zeek/zeek#1741]
I assume that this is an error, rather than intended behavior, but I'm not 100% sure.  The following script:
> function foo()
        {
        print "hi";
        }
event zeek_init()
        {
        hook foo();
        }

prints `hi` without any complaint.  I had expected that I'd be told that `foo` is not a `hook`.

**Comment by Stark-developer01** [comment]
Hi, I want to contribute to this issue, can you help me in navigating to this part of the code mentioned by @vpax in the codebase? I am a first time contributor.

> I assume that this is an error, rather than intended behavior, but I'm not 100% sure. The following script:
> 
> > function foo()
> > {
> > print "hi";
> > }
> > event zeek_init()
> > {
> > hook foo();
> > }
> 
> prints `hi` without any complaint. I had expected that I'd be told that `foo` is not a `hook`.

**Comment by rsmmr** [comment]
From a quick look, I'd expect this go in somewhere here: https://github.com/zeek/zeek/blob/fda1b1db681330b23af41a3199945f59d161f71d/src/Expr.cc#L4357

Thanks for looking into this!
