### ISSUE TITLE
Zeek Analysis resolve the GENEVE protocol

### ISSUE THREAD

**Issue by Canon88** [zeek/zeek#1764]
My mirrored packets are encapsulated with VXLAN and GENEVE protocols respectively. Now Zeek can only parse the outermost VXLAN packets, the packets in GENEVE protocol cannot be parsed. But I saw in the official documentation that Zeek has made support. I have a question, is it that Zeek can’t parse nested these 2 layer protocols?

![image](https://user-images.githubusercontent.com/19372121/132271691-79e17c29-9ce4-427c-8723-916b6dcc5871.png)

**Comment by timwoj** [comment]
Do you happen to have a pcap that has this double-encapsulation in it? We should be handling that correctly already, but clearly something is amiss. Even just a single packet is enough to dig into it.

**Comment by Canon88** [comment]
> Do you happen to have a pcap that has this double-encapsulation in it? We should be handling that correctly already, but clearly something is amiss. Even just a single packet is enough to dig into it.

Of course, this is my PCAP, which hopefully will help us locate the problem as soon as possible.
[ntp.pcap.zip](https://github.com/zeek/zeek/files/7125335/ntp.pcap.zip)

**Comment by Canon88** [comment]
Is there anyone who can help me? I want to know what the problem is

**Comment by timwoj** [comment]
This is definitely an issue with the Geneve analyzer. Our analyzer assumes that the internal packet is always an Ethernet frame, and attempts to pass it back into the packet analysis as such. The pcap you provided (thank you!) has a protocol type of IPv4 on each of the geneve headers so it fails to process it further.

The analyzer needs to look at the actual internal protocol type and pass it to the appropriate analyzer. I can probably put a band-aid on it to get it to directly handle IP packets inside the Geneve tunnel, but there's work on-going right now to move the tunnel analyzers into the packet analysis framework. That work should resolve this as well.

**Comment by Canon88** [comment]
> This is definitely an issue with the Geneve analyzer. Our analyzer assumes that the internal packet is always an Ethernet frame, and attempts to pass it back into the packet analysis as such. The pcap you provided (thank you!) has a protocol type of IPv4 on each of the geneve headers so it fails to process it further.
> 
> The analyzer needs to look at the actual internal protocol type and pass it to the appropriate analyzer. I can probably put a band-aid on it to get it to directly handle IP packets inside the Geneve tunnel, but there's work on-going right now to move the tunnel analyzers into the packet analysis framework. That work should resolve this as well.

I'm glad you replied and look forward to this issue being resolved.
