### ISSUE TITLE
Crash zeek-4.1.0/src/packet_analysis/protocol/ethernet/Ethernet.cc:33

### ISSUE THREAD

**Issue by initconf** [zeek/zeek#1767]
I have been seeing quite regular crash of worker nodes with this specific issue - I think we visited the problem back in 4.0.0 release as well and put in some fix. 

There is a chance that myricom driver is the problem here - ie lack of data on link causes empty packets (I speculate) - but either way zeek should reject that empty / broken packet instead of core dumping. 

for future reference here is coredump anchor: `/usr/local/zeek/spool/tmp/post-terminate-worker-2021-09-09-09-17-04-27362-crash` 

here is backtrace 

```
Core was generated by `/usr/local/zeek-4.1.0/bin/zeek -i myri0 -U .status -p zeekctl -p zeekctl-live -p'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  zeek::packet_analysis::Ethernet::EthernetAnalyzer::AnalyzePacket (this=0x4de1698, len=66, data=0xffff <error: Cannot access memory at address 0xffff>, packet=0x51a4ca0) at /usr/local/src/zeek-4.1.0/src/packet_analysis/protocol/ethernet/Ethernet.cc:33
33              if ( data[12] == 0x89 && data[13] == 0x03 )
[Current thread is 1 (LWP 101967)]
(gdb) bt
#0  zeek::packet_analysis::Ethernet::EthernetAnalyzer::AnalyzePacket (this=0x4de1698, len=66, data=0xffff <error: Cannot access memory at address 0xffff>, packet=0x51a4ca0) at /usr/local/src/zeek-4.1.0/src/packet_analysis/protocol/ethernet/Ethernet.cc:33
#1  0x0000000000a31708 in zeek::packet_analysis::Analyzer::ForwardPacket (this=0x51040f8, len=66, data=0xffff <error: Cannot access memory at address 0xffff>, packet=0x51a4ca0, identifier=1) at /usr/local/src/zeek-4.1.0/src/packet_analysis/Analyzer.cc:97
#2  0x0000000000a33a70 in zeek::packet_analysis::Manager::ProcessPacket (this=0x23f2000, packet=0x51a4ca0) at /usr/local/src/zeek-4.1.0/src/packet_analysis/Manager.cc:109
#3  0x0000000000864be9 in zeek::run_state::detail::dispatch_packet (pkt=0x51a4ca0, pkt_src=<optimized out>) at /usr/local/src/zeek-4.1.0/src/RunState.cc:257
#4  0x00000000009d59c4 in zeek::iosource::PktSrc::Process (this=0x51a4c60) at /usr/local/src/zeek-4.1.0/src/iosource/PktSrc.cc:155
#5  0x0000000000864f60 in zeek::run_state::detail::run_loop () at /usr/local/src/zeek-4.1.0/src/RunState.cc:315
#6  0x000000000064834e in main (argc=<optimized out>, argv=<optimized out>) at /usr/local/src/zeek-4.1.0/src/main.cc:59
```

Please let me know if you want coredumps and/or more information. This crash is pretty regular - sometimes several times a day!

**Comment by timwoj** [comment]
Hasn't this issue been raised a few times? Can we just reopen one of the previous ones? That said, as always a pcap would really help here. We did some work previously to fix this, but there's clearly something still wrong.

**Comment by JustinAzoff** [comment]
I'm 99.9999% sure this is not a pcap issue, this is myricom libpcap returning garbage.

**Comment by JustinAzoff** [comment]
and yeah.. this is the same as https://github.com/zeek/zeek/issues/1751 and I have a comment there that should fix this.

**Comment by timwoj** [comment]
Closing in favor of #1751
