### ISSUE TITLE
Zeek - single huge pcap

### ISSUE THREAD

**Issue by aziel12** [zeek/zeek#1770]
Hi folks, I am currently struggling  how to analyse single big (500MB-1GB+) pcap file with zeek in a short time. I am using standalone mode of zeek and with this command: zeek -Cr sample_500MB.pcap local it took about 1.40min which is a bit too long for my needs... 
What do you advise, how can I get  zeek -r multithreadded behaviour like? Documentation says, use cluster with several workers (even on one node) but I am not sure if you can read pcap in cluster mode? Another option is tcpreplay and let workers generate logs in cluster mode?
So what do you guys advise, I am doing only offline pcap analysis with single 500+MB pcap and zeek should use ideally 4-6 cores instead of one. 
Thank you.

**Comment by anthonykasza** [comment]
I've previously used the [Supervisor framework](https://docs.zeek.org/en/master/frameworks/supervisor.html) in conjunction with split pcaps to test parallel processing of a large pcap. It was quite the hack.

First, I'd split my single large pcap using something like tcpdump. Then, I'd bring up network interfaces for each of my worker nodes to sniff on. Lastly, I'd use tcpreplay to replay the split pcaps on the workers' interfaces. 

The process was manual and error prone but it sometimes worked.

**Comment by awelzel** [comment]
Extending a bit what @anthonykasza  related to supervisor. If you're on Linux you could use a bonding interface to do the loadbalancing for you. 

Not sure it's a good place to provide this example, but putting it here in case it is useful. Below is the supervisor example from the docs extended a bit to create the required networking setup dynamically during startup. It prints the actual `ip link` commands to follow what's going on.

Running this with  `ZEEK_WORKERS=8 zeek -j bond-lb-supervisor.zeek` and then `tcpreplay -i zk-lb ./my-pcap` should give you traffic balanced across 8 Zeek workers. Logs should appear in the `logger` directory.

Maybe this helps a bit.

```
# bond-lb-supervisor.zeek
#
# Supervisor setup using a Linux bonding interface to load-balance
# traffic across workers.
#
# Start with environment variable ZEEK_WORKERS=4 or so set.
#
function psystem(cmd: string) {
   print(fmt("# %s", cmd));
   system(cmd);
}

#
# Linux specific function to create a bond interface in balance-xor mode
# to load balance traffic using the provided xmit_hash_policy across
# workers veth interfaces.
#
# Returns vector of string containing the interfaces for workers to listen on.
#
# xmit_hash_policy should likely be layer3+4 or encap3+4.
#
# See: https://www.kernel.org/doc/Documentation/networking/bonding.txt
#
function setup_bonding_lb(prefix: string, workers: count, xmit_hash_policy: string): vector of string {
    local lb_iface = fmt("%s-lb", prefix);

    psystem(fmt("ip link add %s type bond mode balance-xor xmit_hash_policy %s",
                lb_iface, xmit_hash_policy));

    local worker_ifaces: vector of string;
    local i = 0;
    while (i < workers) {
        local b_iface = fmt("%s-w-%03d-b", prefix, i);  # attached to bond
        local p_iface = fmt("%s-w-%03d-p", prefix, i);  # peer iface
        psystem(fmt("ip link add %s type veth peer %s", b_iface, p_iface));
        # Attach veth to bond
        psystem(fmt("ip link set %s master %s", b_iface, lb_iface));
        psystem(fmt("ip link set %s up promisc on", p_iface));
        ++i;
        worker_ifaces += p_iface;
    }

    # Bring up the bonding interface.
    psystem(fmt("ip link set %s up promisc on", lb_iface));
    return worker_ifaces;
}

function teardown_bonding_lb(prefix: string, workers: count) {

    local i = 0;
    while (i < workers) {
        local b_iface = fmt("%s-w-%03d-b", prefix, i);
        system(fmt("ip link del %s", b_iface));
        ++i;
    }
    local lb_iface = fmt("%s-lb", prefix);
    system(fmt("ip link del %s", lb_iface));
}

global worker_count = to_count(getenv("ZEEK_WORKERS"));


event zeek_init()
    {
    if ( ! Supervisor::is_supervisor() )
        return;

    Broker::listen("127.0.0.1", 9999/tcp);

    local worker_ifaces = setup_bonding_lb("zk", worker_count, "encap3+4");

    local cluster: table[string] of Supervisor::ClusterEndpoint;
    cluster["manager"] = [$role=Supervisor::MANAGER, $host=127.0.0.1, $p=10000/tcp];
    cluster["logger"] = [$role=Supervisor::LOGGER, $host=127.0.0.1, $p=10001/tcp];
    cluster["proxy"] = [$role=Supervisor::PROXY, $host=127.0.0.1, $p=10002/tcp];
    for (i in worker_ifaces)
        {
        local name = fmt("worker-%03d", i);
        cluster[name] = [
            $role=Supervisor::WORKER,
            $host=127.0.0.1,
            $p=count_to_port(20000+i, tcp),
            $interface=worker_ifaces[i]
        ];
        }

    for ( n, ep in cluster )
        {
        local sn = Supervisor::NodeConfig($name=n);
        sn$cluster = cluster;
        sn$directory = n;

        if ( ep?$interface )
            sn$interface = ep$interface;

        local res = Supervisor::create(sn);

        if ( res != "" )
            print fmt("supervisor failed to create node '%s': %s", n, res);
        }
    }

event zeek_done()
    {
    if ( ! Supervisor::is_supervisor() )
        return;

    teardown_bonding_lb("zk", worker_count);
    }
```

**Comment by timwoj** [comment]
This isn't an issue with the Zeek code itself, and we generally don't use GitHub issues for support questions. It appears you got some guidance above, so I'm going to close this.
