### ISSUE TITLE
Build failure in Gen-ZAM on debug build

### ISSUE THREAD

**Issue by ckreibich** [zeek/zeek#1776]
On an `--enable-debug` build of master I hit the following assertion failure when `Gen-ZAM` runs:

```
[ 85%] [sh] Generating ZAM operations
/builddir/build/BUILD/gcc-11.2.1-20210728/obj-x86_64-redhat-linux/x86_64-redhat-linux/libstdc++-v3/include/bits/basic_string.h:1147: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::const_reference std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::back() const [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::const_reference = const char&]: Assertion '!empty()' failed.
make[3]: *** [src/CMakeFiles/zeek_objs.dir/build.make:140: src/ZAM-AssignFlavorsDefs.h] Aborted (core dumped)
make[3]: *** Deleting file 'src/ZAM-AssignFlavorsDefs.h'
```

It goes away with the following small tweak, but I don't know `Gen-ZAM` well enough to know if it's appropriate:

```
--- i/src/script_opt/ZAM/Gen-ZAM.cc
+++ w/src/script_opt/ZAM/Gen-ZAM.cc
@@ -2101,7 +2101,7 @@ void ZAMGen::Emit(EmitTarget et, const string& s)

        fputs(s.c_str(), f);

-       if ( s.back() != '\n' && ! no_NL )
+       if ( s.size() && s.back() != '\n' && ! no_NL )
                fputs("\n", f);
        }
```

**Comment by vpax** [comment]
Thanks, folks. Weird that it didn't cause many any problems during development, I guess for my environment I just happened to be lucky with how `back()` behaves on an empty string. Anyhoo, I've pushed a fix for this in https://github.com/zeek/zeek/commit/10d8c2fe6b17f4756d6c053d7b154dbb14528871 - @timwoj let me know if this is now ready to turn into a PR.

**Comment by timwoj** [comment]
Fixed via https://github.com/zeek/zeek/pull/1779/commits/10d8c2fe6b17f4756d6c053d7b154dbb14528871
