### ISSUE TITLE
ignore_checksums_net with more than a single subnet not working (4.0 and 4.1)

### ISSUE THREAD

**Issue by awelzel** [zeek/zeek#1777]
We observed the ignore_checksums_nets not being functional when more than
a single subnet is added to the variable when running Zeek 4.0 and Zeek 4.1

After coming up with the fix against 4.1, it appears this has been fixed
with master with 802dfd80c1.

I'm going to open a separate MR that adds a test for this failure.

@timwoj ,  could we get the following piece form 802dfd80c1 into 4.0 and 4.1?
```
-	return (subnets->Lookup(addr, true) != 0);
+	return (subnets->Lookup(addr, 128, false) != 0);
```

I've had created the very same fix against 4.1 and was initially a bit confused where it went after rebasing ;-)

**Comment by 0xxon** [comment]
Just to check - did we break this with 4.0/4.1, or was this always broken?

**Comment by timwoj** [comment]
It was a change in 4.0 that Seth made (as part of https://github.com/zeek/zeek/pull/1224).

**Comment by 0xxon** [comment]
Ah, yes, then it should get into 4.0.x/4.1.x, thanks for clarifying :)
