### ISSUE TITLE
Add new string functions

### ISSUE THREAD

**Issue by moshekaplan** [zeek/zeek#178]
Picking up [BIT-1754](https://bro-tracker.atlassian.net/browse/BIT-1754) again:

List of functions to implement:

- [ ] `str.count` - Return the number of non-overlapping occurrences of substring sub in the range
- [ ] `str.find` - Return the lowest index in the string where substring sub is found within the slice s[start:end].
- [x] `str.lstrip` - Return a copy of the string with leading characters removed. The chars argument is a string specifying the set of characters to be removed.
- [ ] `str.rfind` - Return the highest index in the string where substring sub is found
- [x] `str.rstrip` - Return a copy of the string with trailing characters removed. The chars argument is a string specifying the set of characters to be removed
- [ ] `str.strip` - Return a copy of the string with the leading and trailing characters removed. The chars argument is a string specifying the set of characters to be removed

Notes from @sethhall 

We'd merge these in if you implemented them. Are you still planning on doing so? I have a couple of notes too...

- `count` can be done with the built in `find_all` function
- `find` can currently be implemented with the built in `strstr` function.
- `lstrip`, `rstrip`, can be implement with the `sub` function.

**Comment by spitfire55** [comment]
If nobody is currently working on this, I'm going to write a bunch of string BiFs this week. Here is the list of functions I'll start tackling (inspired by [Python string functions](https://docs.python.org/2/library/stdtypes.html#string-methods)):

- `str.rfind`
- `str.rstrip`
- `str.lstrip`
    - I see the notes above about `sub` being able to do `lstrip` and `rstrip`. I think this will be more clear/intuitive, even if its potentially redundant.
- `str.endswith`
- `str.isnum`
- `str.isalpha`
- `str.isalnum`
- `str.ljust`
- `str.rjust`
- `str.swapcase`
- `str.to_title`
- `str.zfill`

**Comment by moshekaplan** [comment]
You're welcome to take it over. I've already implemented `find` and `count`, in case that helps: [string_funcs.diff](https://github.com/bro/bro/files/2481079/string_funcs.txt)

**Comment by timwoj** [comment]
As noted above, the two strip methods are done. If we're going to mimic the python methods, here's what the signatures would look like:

- `function count%(str: string, sub: string%): count`: Takes a string and a substring to search for, returns the number of times that substring is seen.
- `function find%(str: string, sub: string, start: count &default=0, end: count &default=0%): count`: Takes a string and a substring to search for, returns the index of the start of the substring within the string. Also can take an index to start searching from and an index to stop searching at. `start` should always be less than `end`.
- `function rfind%(str: string, sub: string, start: count &default=0, end: count &default=0%): count`: The same as `find` but searches in reverse. Takes a string and a substring to search for, returns the index of the start of the substring within the string. Also can take an index to start searching from and an index to stop searching at. `start` should always be greater than `end`.
- `function startswith%(str: string, sub: string%): bool`: Returns true or false whether a string starts with a substring. This is easily implemented with `find`.
- `function endswith%(str: string, sub: string%): bool`: Returns true or false whether a string ends with a substring. This is easily implemented with `rfind`.
- `function isnum%(str: string%): bool`: Returns whether the entire string represents a number.
- `function isalpha%(str: string%): bool`: Returns whether the entire string is alphabetic characters.
- `function isalnum%(str: string%): bool`: Returns whether the entire string is alphanumeric characters.
- `function ljust%(str: string, width: count, fill: string%): string`: Returns a copy of a string, left-justified within a number of characters defined by `width`. The extra characters are filled in with `fill`. If the string passed for `fill` is more than one character in length, an error is thrown.
- `function rjust%(str: string, width: count, fill: string%): string`: Returns a copy of a string, right-justified within a number of characters defined by `width`. The extra characters are filled in with `fill`. If the string passed for `fill` is more than one character in length, an error is thrown.
- `function swapcase%(str: string%): string`: Returns a copy of the string with the cases of all of the character within that string swapped. For example, the string `aBc` would be returned as `AbC`.
- `function to_title%(str: string%): string`: Returns a copy of the string in titlecase. This means that the first letter of each word in the string will be capitalized. For more info, see https://docs.python.org/2/library/stdtypes.html#str.title
- `function zfill%(str: string, width: count%): string`: Returns a copy of the string filled on the left side with zeroes. This is effectively `rjust(str, width, "0")`.

Some questions:
- We already have `strstr`, which is effectively the same thing as `find`.
- I could definitely see other versions of `find` and `rfind` that take patterns, but there's a question of whether those versions should return the position or the string that matches. We already have `find_last`, but it takes a pattern and not a string. It returns the matched string and not a count.

**Comment by JustinAzoff** [comment]
if you are copying python, also see https://www.python.org/dev/peps/pep-0616/

>  add two new methods, removeprefix() and removesuffix(), to the APIs of Python's various string objects. These methods would remove a prefix or suffix (respectively) from a string, if present

reason being the current strip/lstrip methods are often mis-used under the believe that they only remove the literal argument:

```
print rstrip("banana", "na");
```

outputs `b` not `bana`.

**Comment by vpax** [comment]
Do these have some sort of module scoping to avoid name collisions? `count` and `find` seem ripe for such.  (In fact, I'd think `count` would get confused with the type.)

**Comment by timwoj** [comment]
> Do these have some sort of module scoping to avoid name collisions?

The existing string functions don't at the moment, but there's nothing that would stop us from moving them and leaving deprecated versions in the global namespace.

**Comment by timwoj** [comment]
Python's `isnumeric` method simply checks to see if every character in the string is a number. Is that sufficient or should it actually check to see if the string is a double, negative, etc? How about things like other bases? Scientific notation?

**Comment by moshekaplan** [comment]
I'd recommend making it the same as python - less cognitive load for devs who code in both languages.

**Comment by timwoj** [comment]
`find` and `rfind` technically work in Python by taking the substring between the indexes and then searching within that substring. This effectively means that if you pass a range smaller than the search string, it'll always return a failure. I currently have it implemented differently, where the start and end positions are related to the *start* of the match. This means that if the end of the match is past the requested end position, it'll still return success. Does that sound good or should I swap it to the python version?

**Comment by moshekaplan** [comment]
Unless there is a significant benefit from deviating, I think consistency is best
