### ISSUE TITLE
CI doesn't abort when the pcap downloads fail

### ISSUE THREAD

**Issue by ckreibich** [zeek/zeek#1791]
We just hit a supposed test failure of the private testsuite: https://cirrus-ci.com/task/4679090629246976?logs=test#L39 ... the actual problem is that test's pcaps failed to download, though, and we shouldn't have continued: https://cirrus-ci.com/task/4679090629246976?logs=init_external_repos#L18

For some reason the system date on that MacOS VM was a week behind, so it bailed at cert validation. Maybe we should put an `ntpdate` into our setup script. 

(This really feels like a deju vu, mhmm...)

**Comment by ckreibich** [comment]
> This really feels like a deju vu

Well, at least my brain still remembers _some_ things! We have fixed this before, but ... didn't backport into the release branches: https://github.com/zeek/zeek/pull/1579

**Comment by timwoj** [comment]
Welp, the patch-release issue list was empty for like 2 hours there 😛
