### ISSUE TITLE
HTTP 404 not found from two important public Zeek documents

### ISSUE THREAD

**Issue by meonkeys** [zeek/zeek#1810]
https://zeek.org/development/roadmap.html and https://zeek.org/why_choose_zeek.pdf both return HTTP 404 not found.

**Comment by timwoj** [comment]
Thanks for reporting this. I forwarded it over to people that manage the website.

**Comment by 0xxon** [comment]
The development roadmap now lives here, I think: https://github.com/zeek/zeek/wiki/Development-Roadmap

Additionally you can find the old state of both documents on https://old.zeek.org.

**Comment by timwoj** [comment]
Redirects have been setup for those two URLs.
