### ISSUE TITLE
FAQ BinPac tutorial link is dead

### ISSUE THREAD

**Issue by ottobackwards** [zeek/zeek#1812]
https://zeek.org/faq/ has a link to a tutorial that doesn't work.

https://www.zeek.org/development/howtos/binpac-sample-analyzer.html

**Comment by 0xxon** [comment]
FWIW - I made a list of everything that is broken in the FAQ a while ago. I don't think it was ever acted upon - but I am happy to send it to you :)

**Comment by timwoj** [comment]
This appears fixed on the site now.
