### ISSUE TITLE
Is there any way to add custom CSS in zeek pdf generator ?

### ISSUE THREAD

**Issue by mearazahemad-crescentek** [zeek/zeek#1816]
If image is too large then it is going in second page, i want it to be in one page only. By giving "max-height" CSS we can solve the problem, But somehow max-height does not apply to image.

can you please help me to solve this ?

**Comment by 0xxon** [comment]
Hi,

We don't have a pdf generator, you must be thinking of a different project.

Furthermore, we don't use GitHub issues for support questions. Questions like this are best answered using on either slack or our mailing list, which is both are frequented by Zeek developers and professional users. You can join here:

Mailing list: https://lists.zeek.org/mailman3/lists/zeek.lists.zeek.org/

Slack: https://zeek.org/community/

Johanna
