### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by lasyka** [zeek/zeek#1821]
After :
./configure 
make.
Then  I run:
source build/zeek-path-dev.sh
zeek -i wlan0
Got this error:   Segmentation fault
No more detailed errors.    How can i to anyalisis and resolve it?

**Comment by lasyka** [comment]
Hi ckreibich, thanks for your replay.
1.The zeek4.0.4LTS source code is download from offical site：https://download.zeek.org/zeek-4.0.4.tar.gz
2. OS is :  Linux kali 3.10.40-lasyka+ #30 SMP PREEMPT Sat Sep 29 19:40:50 CST 2018 armv7l GNU/Linux
3.These are gdb output info：
~/workspace/zeek/zeek-4.0.4# gdb -ex run -ex bt --args zeek -i wlan0
GNU gdb (Debian 8.3.1-1) 8.3.1
Copyright (C) 2019 Free Software Foundation, Inc.
This GDB was configured as "arm-linux-gnueabihf".
Reading symbols from zeek...
Starting program: /root/workspace/zeek/zeek-4.0.4/build/src/zeek -i wlan0
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
Program received signal SIGILL, Illegal instruction.
0xb6b9e926 in ?? () from /usr/lib/arm-linux-gnueabihf/libcrypto.so.1.1
#0  0xb6b9e926 in ?? () from /usr/lib/arm-linux-gnueabihf/libcrypto.so.1.1
#1  0xb6b990fa in ?? () from /usr/lib/arm-linux-gnueabihf/libcrypto.so.1.1
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

(gdb) c
Continuing.
Program received signal SIGSEGV, Segmentation fault.
zeek::util::detail::init_random_seed (read_file=0x0, write_file=0x0, use_empty_seeds=<optimized out>) at /root/workspace/zeek/zeek-4.0.4/src/util.cc:488
488					seed = (seed << 1) | (seed >> 31);
(gdb) c
Continuing.

Program terminated with signal SIGSEGV, Segmentation fault.
The program no longer exists.

**Comment by ckreibich** [comment]
Thanks for the details. We've been trying to reproduce this and so far have failed, but we don't regularly test Zeek on ARM, and don't currently have a way to test on `armv7l`. We do have one other 32-bit platform test in CI, so I don't think that alone explains it. We'll look into more options. Out of curiosity, what device are you on?

If you have a different compiler available, you could see if that makes a difference. A core file would also help for future reference, though I'm not sure we can examine it suitably while not on your platform.
