### ISSUE TITLE
Asking how to compile with different branch

### ISSUE THREAD

**Issue by andreyferriyan** [zeek/zeek#1825]
Hi, I have question. 

I want to compile the source from different branch as an example, v3.2.0. Should I update the module with 

`git submodule update` 

and 

`git submodule update --remote`

After I checkout v3.2.0??

**Comment by rsmmr** [comment]
`git submodule update --recursive --init` will get it all into the right state.

(Btw, Slack or the mailing list are the best places for such questions.)
