### ISSUE TITLE
HTTP HOST Value Bug for IPv6

### ISSUE THREAD

**Issue by 0x120102181f0a040a01181c** [zeek/zeek#1844]
https://github.com/zeek/zeek/blob/52b3e159a415fb3acd584f95aa64e2d2a9c0b282/scripts/base/protocols/http/main.zeek#L267

If an HTTP request is made directly to an IPv6 address, vs using a domain, the HOST header will look something like this

```
GET / HTTP/1.1
Host: [::1]:8080
```

The referenced line looks for HOSTs that contain a colon and will split on it, returning the first item. If the HOST is an IPv6 address, part of the value will be removed.

The [docs](https://docs.zeek.org/en/master/scripts/base/protocols/http/main.zeek.html#type-HTTP::Info) suggest that the value for this field is the HOST header value unchanged which is not the case. If the line that extracts the HOST could be removed, the IPv6 issue would no longer exist. Otherwise, the pattern could be changed to something like `/:[[:digit:]]{1,5}$/`.

**Comment by 0xxon** [comment]
Yup, we definitely should fix this. I obviously also understand why we do this - but I am still slightly tempted to go by the documentation and just put the actual, unchanged host-header info c$http$host. (Alternatively - we should update the documentation)

**Comment by JustinAzoff** [comment]
Note we have the same regex here:

https://github.com/zeek/zeek/blob/master/scripts/policy/frameworks/intel/seen/http-headers.zeek#L12

though in that context it's probably fine to strip the port, but still has the v6 issue.

In a way this is similar to how http_request has original_URI and unescaped_URI.  From a normalization standpoint most people probably want the header with the host stripped.. there's id.resp_p after all.  From a malware standpoint it could be useful to know if an http client is sending an extraneous port.

**Comment by 0x120102181f0a040a01181c** [comment]
Good find on the other file. Coming from the malware side, I prefer to see things unchanged just in case the malware is doing something weird. That being said, it's not very common for something to be done in the HOST and most cases will definitely be regular hosts with a possible port.
