### ISSUE TITLE
Missing HTTP host + uri  in http.log

### ISSUE THREAD

**Issue by abusech** [zeek/zeek#1864]
It appears that in some circumstances, the HTTP host and uri in http.log are missing

_**_Example #1_**_
GET /vr/hk.exe HTTP/1.1
Accept: */*
Accept-Language: en-US,en;q=0.8
Accept-Encoding: gzip, deflate
User-Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)
Host: foodpackaging.com.ar
Connection: Keep-Alive

Output:
#fields	ts	uid	id.orig_h	id.orig_p	id.resp_h	id.resp_p	trans_depth	method	host	uri	referrer	version	user_agent	origin	request_body_len	response_body_len	status_code	status_msg	info_code	info_msg	tags	username	password	proxied	orig_fuids	orig_filenames	orig_mime_types	resp_fuids	resp_filenames	resp_mime_types
#types	time	string	addr	port	addr	port	count	string	string	string	string	string	string	string	count	count	count	string	count	string	set[enum]	string	string	set[string]	vector[string]	vector[string]	vector[string]	vector[string]	vector[string]	vector[string]
1637348125.839596	CiyB5E1FnAeb56Tex4	10.0.7.56	49738	151.106.103.202	80	1	-	-	-	-	1.1	-	-	0	586752	200	OK	-	-	(empty)	-	-	-	-	-	-	FdWLvySrYh9K0ZTFd	-	application/x-dosexec

**Example #2**
GET /vvt/rt.exe HTTP/1.1
Accept: */*
Accept-Language: en-US,en;q=0.8
Accept-Encoding: gzip, deflate
User-Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)
Host: mudanzasdistintas.com.ar
Connection: Keep-Alive

Output:
#fields	ts	uid	id.orig_h	id.orig_p	id.resp_h	id.resp_p	trans_depth	method	host	uri	referrer	version	user_agent	origin	request_body_len	response_body_len	status_code	status_msg	info_code	info_msg	tags	username	password	proxied	orig_fuids	orig_filenames	orig_mime_types	resp_fuids	resp_filenames	resp_mime_types
#types	time	string	addr	port	addr	port	count	string	string	string	string	string	string	string	count	count	count	string	count	string	set[enum]	string	string	set[string]	vector[string]	vector[string]	vector[string]	vector[string]	vector[string]	vector[string]
1636646675.898934	CBjQahROaAiZHHAih	10.0.14.14	49724	23.111.169.5	80	1	-	-	-	-	1.1	-	-	0	759808	200	OK	-	-	(empty)	-	-	-	-	-	-	FBGBBk3ENFUz1s3N8c	-	application/x-dosexec

Zeek version 4.2.0-dev.333

**Comment by JustinAzoff** [comment]
Does this help? 

https://old.zeek.org/documentation/faq.html#why-isn-t-zeek-producing-the-logs-i-expect-a-note-about-checksums

**Comment by abusech** [comment]
I am happy to confirm that the -C parameter did the job. Sorry for the noise!
