### ISSUE TITLE
Zeek Cluster all worker processes reach 100% CPU uitlization on Kernel v 4.18.0-348.2.1 (Rocky Linux 8.5)

### ISSUE THREAD

**Issue by addeep99** [zeek/zeek#1866]
I'm running AF_Packet for load balancing on 4 worker nodes on Rocky Linux 8.5. 
Within few hours of restarting cluster(sometimes immediately), all worker processes reach 100% CPU utilization and ultimately zeek stops logging. I upgraded zeek version to 4.0.4 and AF_Packet to 3.0.1 but it didn't resolve the issue. I've copied output of zeekctl diag, node.cfg. 

**zeekctl diag:**

[logger]

No core file found.

Zeek 4.0.4
Linux 4.18.0-348.2.1.el8_5.x86_64

Zeek plugins:
Zeek::AF_Packet - Packet acquisition via AF_Packet (dynamic, version 3.0.1)

==== reporter.log
1637756252.419818	Reporter::WARNING	SumStat key request for the I1iPcraiirj SumStat uid took longer than 1 minute and was automatically cancelled.	/opt/zeek/share/zeek/base/frameworks/sumstats/./cluster.zeek, line 226
1637756252.419818	Reporter::WARNING	SumStat key request for the CdgjuIVucba SumStat uid took longer than 1 minute and was automatically cancelled.	/opt/zeek/share/zeek/base/frameworks/sumstats/./cluster.zeek, line 226
1637756552.434180	Reporter::WARNING	SumStat key request for the w2azE4kGNp3 SumStat uid took longer than 1 minute and was automatically cancelled.	/opt/zeek/share/zeek/base/frameworks/sumstats/./cluster.zeek, line 226
1637756552.434180	Reporter::WARNING	SumStat key request for the X0TKsToXlRi SumStat uid took longer than 1 minute and was automatically cancelled.	/opt/zeek/share/zeek/base/frameworks/sumstats/./cluster.zeek, line 226
1637756852.447389	Reporter::WARNING	SumStat key request for the bg6HkVSzR5k SumStat uid took longer than 1 minute and was automatically cancelled.	/opt/zeek/share/zeek/base/frameworks/sumstats/./cluster.zeek, line 226
1637756852.447389	Reporter::WARNING	SumStat key request for the i3F1sCPrblh SumStat uid took longer than 1 minute and was automatically cancelled.	/opt/zeek/share/zeek/base/frameworks/sumstats/./cluster.zeek, line 226
1637757152.462252	Reporter::WARNING	SumStat key request for the xZenSUEy0Bl SumStat uid took longer than 1 minute and was automatically cancelled.	/opt/zeek/share/zeek/base/frameworks/sumstats/./cluster.zeek, line 226
1637757152.462252	Reporter::WARNING	SumStat key request for the dqK14FWWT1i SumStat uid took longer than 1 minute and was automatically cancelled.	/opt/zeek/share/zeek/base/frameworks/sumstats/./cluster.zeek, line 226
1637757452.474662	Reporter::WARNING	SumStat key request for the tvau4vBoU8k SumStat uid took longer than 1 minute and was automatically cancelled.	/opt/zeek/share/zeek/base/frameworks/sumstats/./cluster.zeek, line 226
1637757452.474662	Reporter::WARNING	SumStat key request for the gFjx0YRAkF5 SumStat uid took longer than 1 minute and was automatically cancelled.	/opt/zeek/share/zeek/base/frameworks/sumstats/./cluster.zeek, line 226

==== stderr.log

==== stdout.log
max memory size         (kbytes, -m) unlimited
data seg size           (kbytes, -d) unlimited
virtual memory          (kbytes, -v) unlimited
core file size          (blocks, -c) unlimited

==== .cmdline
-U .status -p zeekctl -p zeekctl-live -p local -p logger local.zeek zeekctl base/frameworks/cluster zeekctl/auto

==== .env_vars
PATH=/opt/zeek/bin:/opt/zeek/share/zeekctl/scripts:/opt/zeek/bin:/sbin:/bin:/usr/sbin:/usr/bin
ZEEKPATH=/mnt/zeeklogs/spool/installed-scripts-do-not-touch/site::/mnt/zeeklogs/spool/installed-scripts-do-not-touch/auto:/opt/zeek/share/zeek:/opt/zeek/share/zeek/policy:/opt/zeek/share/zeek/site
CLUSTER_NODE=logger

==== .status
RUNNING [run_loop]

==== prof.log
1637757555.245708   intel/Log::WRITER_ASCII   in=53182 out=37325 pending=0/0 (#queue r/w: in=53182/53182 out=37325/37325)
1637757555.245708   dce_rpc/Log::WRITER_ASCII in=37323 out=37309 pending=0/0 (#queue r/w: in=37323/37323 out=37309/37309)
1637757555.245708   dhcp/Log::WRITER_ASCII    in=39002 out=37305 pending=0/0 (#queue r/w: in=39002/39002 out=37305/37305)
1637757555.245708   mysql/Log::WRITER_ASCII   in=38246 out=37292 pending=0/0 (#queue r/w: in=38246/38246 out=37292/37292)
1637757555.245708   capture_loss/Log::WRITER_ASCII in=37354 out=37291 pending=0/0 (#queue r/w: in=37354/37354 out=37291/37291)
1637757555.245708   snmp/Log::WRITER_ASCII    in=56299 out=37291 pending=0/0 (#queue r/w: in=56299/56299 out=37291/37291)
1637757555.245708   kerberos/Log::WRITER_ASCII in=41406 out=37284 pending=0/0 (#queue r/w: in=41406/41406 out=37284/37284)
1637757555.245708   pe/Log::WRITER_ASCII      in=37649 out=37186 pending=0/0 (#queue r/w: in=37649/37649 out=37186/37186)
1637757555.245708   reporter/Log::WRITER_ASCII in=36032 out=35883 pending=0/0 (#queue r/w: in=36032/36032 out=35883/35883)
1637757555.245708   smb_mapping/Log::WRITER_ASCII in=14843 out=14841 pending=0/0 (#queue r/w: in=14843/14843 out=14841/14841)

==== packet_filter.log
1637755578.235118	worker-1-13	(ip or not ip) and (not ((tcp and tcp[tcpflags] & (tcp-syn|tcp-fin|tcp-rst) == 0) and (host 147.156.158.14 and port 42768 and host 128.175.240.195 and port 1030)))	F	T
1637755597.160012	worker-4-9	(ip or not ip) and (not ((tcp and tcp[tcpflags] & (tcp-syn|tcp-fin|tcp-rst) == 0) and (host 128.175.20.86 and port 49881 and host 199.109.99.203 and port 80)))	F	T
1637755597.187690	worker-4-3	(ip or not ip) and (not ((tcp and tcp[tcpflags] & (tcp-syn|tcp-fin|tcp-rst) == 0) and (host 128.175.20.86 and port 49882 and host 199.109.99.209 and port 80)))	F	T
1637755597.141975	worker-4-14	(ip or not ip) and (not ((tcp and tcp[tcpflags] & (tcp-syn|tcp-fin|tcp-rst) == 0) and (host 128.175.20.21 and port 49882 and host 199.109.99.209 and port 80)))	F	T
1637755618.176163	worker-4-11	(ip or not ip) and (not ((tcp and tcp[tcpflags] & (tcp-syn|tcp-fin|tcp-rst) == 0) and (host 128.175.20.13 and port 49874 and host 199.109.99.203 and port 80)))	F	T
1637755623.691389	worker-2-7	(ip or not ip) and (not ((tcp and tcp[tcpflags] & (tcp-syn|tcp-fin|tcp-rst) == 0) and (host 128.175.20.87 and port 49866 and host 69.164.46.128 and port 80)))	F	T
1637755631.182147	worker-1-13	(ip or not ip) and (not ((tcp and tcp[tcpflags] & (tcp-syn|tcp-fin|tcp-rst) == 0) and ((host 128.175.20.75 and port 49892 and host 199.109.99.203 and port 80) and (host 147.156.158.14 and port 42768 and host 128.175.240.195 and port 1030))))	F	T
1637755644.624416	worker-4-16	(ip or not ip) and (not ((tcp and tcp[tcpflags] & (tcp-syn|tcp-fin|tcp-rst) == 0) and (host 128.175.20.29 and port 49871 and host 199.109.99.203 and port 80)))	F	T
1637755647.194526	worker-4-16	(ip or not ip) and (not ((tcp and tcp[tcpflags] & (tcp-syn|tcp-fin|tcp-rst) == 0) and ((host 128.175.20.29 and port 49871 and host 199.109.99.203 and port 80) and (host 128.175.20.13 and port 49881 and host 199.109.99.209 and port 80))))	F	T
1637755648.825799	worker-4-11	(ip or not ip) and (not ((tcp and tcp[tcpflags] & (tcp-syn|tcp-fin|tcp-rst) == 0) and ((host 128.175.20.13 and port 49874 and host 199.109.99.203 and port 80) and (host 128.175.20.89 and port 49884 and host 199.109.99.203 and port 80))))	F	T
1637755899.336260	worker-4-11	(ip or not ip) and (not ((tcp and tcp[tcpflags] & (tcp-syn|tcp-fin|tcp-rst) == 0) and (host 128.4.81.22 and port 37988 and host 96.115.198.13 and port 443)))	F	T
1637756149.763566	worker-2-13	(ip or not ip) and (not ((tcp and tcp[tcpflags] & (tcp-syn|tcp-fin|tcp-rst) == 0) and (host 128.175.102.124 and port 62646 and host 54.81.129.10 and port 443)))	F	T
1637756314.806239	worker-1-14	(ip or not ip) and (not ((tcp and tcp[tcpflags] & (tcp-syn|tcp-fin|tcp-rst) == 0) and (host 71.206.21.44 and port 50358 and host 128.175.24.120 and port 8100)))	F	T
1637756659.390627	worker-1-10	(ip or not ip) and (not ((tcp and tcp[tcpflags] & (tcp-syn|tcp-fin|tcp-rst) == 0) and (host 195.18.27.176 and port 39382 and host 128.175.28.248 and port 80)))	F	T
1637756807.457235	worker-4-11	(ip or not ip) and (not ((tcp and tcp[tcpflags] & (tcp-syn|tcp-fin|tcp-rst) == 0) and (host 38.115.62.67 and port 29475 and host 130.117.123.24 and port 443)))	F	T
1637756844.911759	worker-1-7	(ip or not ip) and (not ((tcp and tcp[tcpflags] & (tcp-syn|tcp-fin|tcp-rst) == 0) and (host 128.4.186.4 and port 53016 and host 68.67.178.22 and port 443)))	F	T
1637756851.127474	worker-4-16	(ip or not ip) and (not ((tcp and tcp[tcpflags] & (tcp-syn|tcp-fin|tcp-rst) == 0) and (host 128.4.177.187 and port 65014 and host 52.71.84.114 and port 443)))	F	T
1637756864.133674	worker-4-3	(ip or not ip) and (not ((tcp and tcp[tcpflags] & (tcp-syn|tcp-fin|tcp-rst) == 0) and (host 128.175.21.237 and port 49743 and host 8.252.241.254 and port 80)))	F	T
1637757004.042329	worker-1-13	(ip or not ip) and (not ((tcp and tcp[tcpflags] & (tcp-syn|tcp-fin|tcp-rst) == 0) and (host 128.175.28.55 and port 33748 and host 172.217.165.138 and port 443)))	F	T
1637757051.010765	worker-2-13	(ip or not ip) and (not ((tcp and tcp[tcpflags] & (tcp-syn|tcp-fin|tcp-rst) == 0) and (host 128.175.21.211 and port 49794 and host 8.240.37.254 and port 80)))	F	T
1637757097.663458	worker-4-14	(ip or not ip) and (not ((tcp and tcp[tcpflags] & (tcp-syn|tcp-fin|tcp-rst) == 0) and (host 38.115.62.67 and port 2567 and host 130.117.123.24 and port 443)))	F	T
1637757311.552200	worker-4-16	(ip or not ip) and (not ((tcp and tcp[tcpflags] & (tcp-syn|tcp-fin|tcp-rst) == 0) and (host 128.4.168.19 and port 64947 and host 23.227.139.243 and port 443)))	F	T
1637757321.949615	worker-4-11	(ip or not ip) and (not ((tcp and tcp[tcpflags] & (tcp-syn|tcp-fin|tcp-rst) == 0) and (host 128.4.6.98 and port 49868 and host 69.164.46.128 and port 80)))	F	T
1637757379.426430	worker-5-19	(ip or not ip) and (not ((tcp and tcp[tcpflags] & (tcp-syn|tcp-fin|tcp-rst) == 0) and (host 128.175.21.203 and port 49928 and host 69.164.46.0 and port 80)))	F	T
1637757389.086915	worker-5-17	(ip or not ip) and (not ((tcp and tcp[tcpflags] & (tcp-syn|tcp-fin|tcp-rst) == 0) and (host 128.4.175.26 and port 40216 and host 75.2.14.203 and port 443)))	F	T
1637757402.835699	worker-4-11	(ip or not ip) and (not ((tcp and tcp[tcpflags] & (tcp-syn|tcp-fin|tcp-rst) == 0) and (host 128.175.21.226 and port 49857 and host 69.164.46.128 and port 80)))	F	T
1637757414.099541	worker-2-13	(ip or not ip) and (not ((tcp and tcp[tcpflags] & (tcp-syn|tcp-fin|tcp-rst) == 0) and (host 128.175.21.202 and port 49738 and host 8.253.140.119 and port 80)))	F	T
1637757414.094793	worker-5-19	(ip or not ip) and (not ((tcp and tcp[tcpflags] & (tcp-syn|tcp-fin|tcp-rst) == 0) and (host 128.175.21.202 and port 49739 and host 65.58.9.254 and port 80)))	F	T
1637757424.013945	worker-1-21	(ip or not ip) and (not ((tcp and tcp[tcpflags] & (tcp-syn|tcp-fin|tcp-rst) == 0) and (host 123.157.252.232 and port 52579 and host 128.4.166.4 and port 60887)))	F	T
1637757458.091746	worker-1-10	(ip or not ip) and (not ((tcp and tcp[tcpflags] & (tcp-syn|tcp-fin|tcp-rst) == 0) and (host 128.175.21.207 and port 49863 and host 69.164.46.128 and port 80)))	F	T

==== No loaded_scripts.log

[manager]

No core file found.

Zeek 4.0.4
Linux 4.18.0-348.2.1.el8_5.x86_64

Zeek plugins:
Zeek::AF_Packet - Packet acquisition via AF_Packet (dynamic, version 3.0.1)

==== No reporter.log

==== stderr.log

==== stdout.log
max memory size         (kbytes, -m) unlimited
data seg size           (kbytes, -d) unlimited
virtual memory          (kbytes, -v) unlimited
core file size          (blocks, -c) unlimited

==== .cmdline
-U .status -p zeekctl -p zeekctl-live -p local -p manager local.zeek zeekctl base/frameworks/cluster zeekctl/auto

==== .env_vars
PATH=/opt/zeek/bin:/opt/zeek/share/zeekctl/scripts:/opt/zeek/bin:/sbin:/bin:/usr/sbin:/usr/bin
ZEEKPATH=/mnt/zeeklogs/spool/installed-scripts-do-not-touch/site::/mnt/zeeklogs/spool/installed-scripts-do-not-touch/auto:/opt/zeek/share/zeek:/opt/zeek/share/zeek/policy:/opt/zeek/share/zeek/site
CLUSTER_NODE=manager

==== .status
RUNNING [run_loop]

==== prof.log
1637757556.274323 Triggers: total=0 pending=0
1637757556.274323         RotateTimer = 8
1637757556.274323         ScheduleTimer = 9
1637757556.274323         TableValTimer = 43
1637757556.274323         ThreadHeartbeat = 1
1637757556.274323 Threads: current=4
1637757556.274323   /home/deepakas/ses/cifv3/intel/ses_fqdn.intel/Input::READER_ASCII in=37203 out=39219 pending=0/0 (#queue r/w: in=37203/37203 out=39219/39219)
1637757556.274323   /home/deepakas/ses/cifv3/intel/ses_url.intel/Input::READER_ASCII in=37203 out=530868 pending=0/0 (#queue r/w: in=37203/37203 out=530868/530868)
1637757556.274323   /home/deepakas/ses/cifv3/intel/ses_ipv4.intel/Input::READER_ASCII in=37203 out=460929 pending=0/0 (#queue r/w: in=37203/37203 out=460929/460929)
1637757556.274323   /home/deepakas/ses/cifv3/intel/ses_sha1.intel/Input::READER_ASCII in=37203 out=598 pending=0/0 (#queue r/w: in=37203/37203 out=598/598)

==== No packet_filter.log

==== No loaded_scripts.log

[proxy-1]

No core file found.

Zeek 4.0.4
Linux 4.18.0-348.2.1.el8_5.x86_64

Zeek plugins:
Zeek::AF_Packet - Packet acquisition via AF_Packet (dynamic, version 3.0.1)

==== No reporter.log

==== stderr.log

==== stdout.log
max memory size         (kbytes, -m) unlimited
data seg size           (kbytes, -d) unlimited
virtual memory          (kbytes, -v) unlimited
core file size          (blocks, -c) unlimited

==== .cmdline
-U .status -p zeekctl -p zeekctl-live -p local -p proxy-1 local.zeek zeekctl base/frameworks/cluster zeekctl/auto

==== .env_vars
PATH=/opt/zeek/bin:/opt/zeek/share/zeekctl/scripts:/opt/zeek/bin:/sbin:/bin:/usr/sbin:/usr/bin
ZEEKPATH=/mnt/zeeklogs/spool/installed-scripts-do-not-touch/site::/mnt/zeeklogs/spool/installed-scripts-do-not-touch/auto:/opt/zeek/share/zeek:/opt/zeek/share/zeek/policy:/opt/zeek/share/zeek/site
CLUSTER_NODE=proxy-1

==== .status
RUNNING [run_loop]

==== prof.log
1637757556.621971 TCP-States:Rst.                                                            
1637757556.621971 Connections expired due to inactivity: 0
1637757556.621971 Total reassembler data: 0K
1637757556.621971 Timers: current=50 max=53 lag=0.00s
1637757556.621971 DNS_Mgr: requests=0 succesful=0 failed=0 pending=0 cached_hosts=0 cached_addrs=0
1637757556.621971 Triggers: total=0 pending=0
1637757556.621971         RotateTimer = 5
1637757556.621971         ScheduleTimer = 6
1637757556.621971         TableValTimer = 39
1637757556.621971 Threads: current=0

==== No packet_filter.log

==== No loaded_scripts.log

[worker-1-1]

No core file found.

Zeek 4.0.4
Linux 4.18.0-348.2.1.el8_5.x86_64

Zeek plugins:
Zeek::AF_Packet - Packet acquisition via AF_Packet (dynamic, version 3.0.1)

==== No reporter.log

==== stderr.log
listening on eno1

==== stdout.log
max memory size         (kbytes, -m) unlimited
data seg size           (kbytes, -d) unlimited
virtual memory          (kbytes, -v) unlimited
core file size          (blocks, -c) unlimited

==== .cmdline
-i af_packet::eno1 -U .status -p zeekctl -p zeekctl-live -p local -p worker-1-1 local.zeek zeekctl base/frameworks/cluster zeekctl/auto

==== .env_vars
PATH=/opt/zeek/bin:/opt/zeek/share/zeekctl/scripts:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
ZEEKPATH=/mnt/zeeklogs/spool/installed-scripts-do-not-touch/site::/mnt/zeeklogs/spool/installed-scripts-do-not-touch/auto:/opt/zeek/share/zeek:/opt/zeek/share/zeek/policy:/opt/zeek/share/zeek/site
CLUSTER_NODE=worker-1-1

==== .status
RUNNING [run_loop]

==== prof.log
1637737353.006483         ConnectionInactivityTimer = 1087
1637737353.006483         DNSExpireTimer = 37
1637737353.006483         FileAnalysisInactivityTimer = 475
1637737353.006483         IPTunnelInactivityTimer = 9198
1637737353.006483         RotateTimer = 31
1637737353.006483         ScheduleTimer = 568
1637737353.006483         TableValTimer = 39
1637737353.006483         TCPConnectionAttemptTimer = 234
1637737353.006483         TCPConnectionExpireTimer = 632
1637737353.006483 Threads: current=0

==== No packet_filter.log

==== No loaded_scripts.log

**node.cfg** 

[logger]
type=logger
host=xx.xx.xx.xx

[manager]
type=manager
host=xx.xx.xx.xx

[proxy-1]
type=proxy
host=xx.xx.xx.xx

[worker-1]
type=worker
host=xx.xx.xx.xx
interface=af_packet::eno1
lb_method=custom
lb_procs=22
pin_cpus=4,6,8,10,12,14,16,18,20,22,1,3,5,7,9,11,13,15,17,19,21,23

**Comment by 0xxon** [comment]
Hi,

as this does not look like a bug, and more like a configuration/deployment problem, I am going to close this. Our Slack/mailing list are better venues for questions like this.

I know that you did post on Slack - and that you got the answer that you have not provided enough information for us to tell what it is going on. I would recommend to reach out there again - and ask for help with continuing diagnosing your problem.

Thanks,
 Johanna
