### ISSUE TITLE
zeek doesn't support HTTP METHOD POST logging ?

### ISSUE THREAD

**Issue by 0ktavandi** [zeek/zeek#1871]
why in `http.log` zeek doesn't log a `POST HTTP REQUEST` method , and are ZEEK doesn't log a HTTP RESPONSE BODY and HEADER ????

**Comment by 0xxon** [comment]
Hi,

We do not provide user support at this address. Questions like this are best answered using Slack, or our mailing list. Both of these are followed by Zeek developers and professional users. You can join here:

Mailing list: https://lists.zeek.org/mailman3/lists/zeek.lists.zeek.org/

Slack: https://zeek.org/community/

Note that Zeek does support post requests.

 Johanna
