### ISSUE TITLE
How should I link external library in a skeleton created with init_plugin?

### ISSUE THREAD

**Issue by labingIt** [zeek/zeek#1882]
I want to build a kafka-based plugin, but I'm stuck with linking librdkafka and include it into the bif file.
Any help will be grateful.

**Comment by timwoj** [comment]
We do not provide user support at this address. Questions like this are best answered using Slack, or our mailing list. Both of these are followed by Zeek developers and professional users. You can join here:

Mailing list: https://lists.zeek.org/mailman3/lists/zeek.lists.zeek.org/
Slack: https://zeek.org/community/

See especially the #development channel on Slack.
