### ISSUE TITLE
"mixing vector and scalar operands is deprecated" doesn't hold for string operands

### ISSUE THREAD

**Issue by vpax** [zeek/zeek#1890]
The following:

> global g = vector(3, 5, 7);
> print g == 7;

produces the warning `mixing vector and scalar operands is deprecated`, and prints `[F, F, T]`.  However, the following:

> global g = vector("a", "b", "c");
> print g == "b";

doesn't produce any warning (and prints `[F, T, F]`).  This seems inconsistent.

**Comment by ezekiiel** [comment]
Is the desired behavior here that

```zeek
const nv = vector(1, 2, 3);
print nv * 2;
```

also fails or should this only apply to equality expressions?

**Comment by vpax** [comment]
The desired behavior is that (1) yes, the example you give also generates a warning, and (2) mixed string operations (equality or otherwise) generate warnings, just like they do for arithmetics.

Basically, we've decided that the functionality of mixing vector and scalar operands was a mistake (much as I like it in some contexts!) and thus shouldn't be allowed, period.
