### ISSUE TITLE
Remove deprecated `list`, `union`, and `timer` types

### ISSUE THREAD

**Issue by timwoj** [zeek/zeek#1898]
These are old types that have no actual semantics behind them so they likely don't do anything. We should remove them to avoid confusion.

**Comment by karandeeppotato** [comment]
Hey, i can do that

Can you please assign me😀

**Comment by rsmmr** [comment]
Assigned, thanks for offering!

**Comment by Ishvina** [comment]
Hi! I am in an intro to swe class that is requiring me to work on my first open-source project. I was wondering if this issue is still open and if so could is this beginner-friendly?

**Comment by rsmmr** [comment]
I believe yes on both accounts: assuming @karandeeppotato didn't do any further work, it's open and available. The way I'd start is pick one of the types, say union, and then remove the the corresponding `TYPE_*` tags from the `TypeTag` enum in `src/Type.h`. Then see what breaks: there a few places around the code base where theses tags are used, and generally we should be able to just remove the code surrounding that usage.

**Comment by karandeeppotato** [comment]
@rsmmr 
I have been working on this...

Actually I have my university exams so shifted my track to study for the latter...

Really sorry for not giving any updates on this 😅

**Comment by rsmmr** [comment]
@karandeeppotato alright, assigned you back then. :)

@Ishvina, I suggest you take a look at other "good first issue" tickets then, and let us know if starting points would be helpful anywhere.

**Comment by Ishvina** [comment]
@karandeeppotato would it be ok to split the work/the types that we remove? I feel like a lot of other "good first issues" are out of the scope of my knowledge.

**Comment by karandeeppotato** [comment]
@Ishvina 
Really sorry!
I missed this one out and did most of the work..

I would recommend you to check this : [https://goodfirstissue.dev/](url)

Might be helpful for you..

**Comment by karandeeppotato** [comment]
@rsmmr 
I have removed each occurrences of `list` `union` and `timer` types from the base code.


but while building the code i am getting this error : 
```
/usr/bin/ld: CMakeFiles/zeek_objs.dir/script_opt/Expr.cc.o: in function `zeek::IntrusivePtr<zeek::detail::CheckAnyLenStmt> zeek::make_intrusive<zeek::detail::CheckAnyLenStmt, zeek::IntrusivePtr<zeek::detail::Expr>&, int&>(zeek::IntrusivePtr<zeek::detail::Expr>&, int&)':
/home/geekpotato/Github_Projects/zeek/src/zeek/zeek/zeek/zeek/zeek/IntrusivePtr.h:180: undefined reference to `zeek::detail::CheckAnyLenStmt::CheckAnyLenStmt(zeek::IntrusivePtr<zeek::detail::Expr>, int)'
collect2: error: ld returned 1 exit status
make[3]: *** [src/CMakeFiles/zeek.dir/build.make:1498: src/zeek] Error 1
make[3]: Leaving directory '/home/geekpotato/Github_Projects/zeek/build'
make[2]: *** [CMakeFiles/Makefile2:3831: src/CMakeFiles/zeek.dir/all] Error 2
make[2]: Leaving directory '/home/geekpotato/Github_Projects/zeek/build'
make[1]: *** [Makefile:166: all] Error 2
make[1]: Leaving directory '/home/geekpotato/Github_Projects/zeek/build'
make: *** [Makefile:15: all] Error 2
```

Line 180 of IntrusivePtr.h : 
```
template <class T, class... Ts> IntrusivePtr<T> make_intrusive(Ts&&... args)
	{
	// Assumes that objects start with a reference count of 1!
	return {AdoptRef{}, new T(std::forward<Ts>(args)...)};
	}
```

Am I doing something wrong here ?

**Comment by rsmmr** [comment]
Hard to say without seeing the code. I suppose that method still exists in your code? Did it work before you started making your changes?

**Comment by karandeeppotato** [comment]
Yup it was working before...

And i figured out that I removed the wrong code snippet.

Thanks😀

**Comment by karandeeppotato** [comment]
@rsmmr 
I am getting this error
```/zeek/src/script_opt/ZAM/Ops.in, line 278: bad op-type```

I am not able to get pass this error, what can be the possible reasons ?

**Comment by vpax** [comment]
Try doing a `make clean` (or the equivalent for your build generator) and recompiling everything.  The most likely cause of that message is that you have a `.o` object that still knows about the old type tags.  If so, recompiling will fix that.

**Comment by matthewluckie** [comment]
Attached is a patch that removes the union and timer types.  I am not sure about the list type -- my initial reaction is that the TypeList class looks like it will go as part of removing TYPE_LIST but there's a bunch more code in Type.cc at least that deals with TypeList and I'm expecting the removal of TYPE_LIST code to be more invasive.  Is this expected or am I off track?

Patch is against git.  Apart from not dealing with TYPE_LIST, I am curious if I've missed things.

[patch-zeek-deuniontimer.txt](https://github.com/zeek/zeek/files/7990596/patch-zeek-deuniontimer.txt)

**Comment by vpax** [comment]
For `list`, the only thing to remove is it being mentioned as a script-level notion (basically, in the parser).  It's used internally, so shouldn't be fully removed.

In addition, IMHO we might want to make it a visible script-level notion, so my own druthers would be to just leave it be for now.

**Comment by timwoj** [comment]
Closed via https://github.com/zeek/zeek/pull/1975
