### ISSUE TITLE
I have a question about “Use multiple ZEEK to process traffic”

### ISSUE THREAD

**Issue by luguifang** [zeek/zeek#1899]
In my program, I started ZEEK (named zeek1) to analyze a large file (the analysis will last for a long time), and started another ZEEK (named zeek2) to analyze the traffic of eth0  port. When I changed the configuration, I killed zeek2 and asked him to restart. I found that zeek2 did not generate logs. When I did not use zeek1, the problem would not appear。Is this a bug？

**Comment by 0xxon** [comment]
Hi,

We don't use GitHub issues for support questions. Questions like this are best answered using on either slack or our mailing list, which is both are frequented by Zeek developers and professional users. You can join here:

Mailing list: https://lists.zeek.org/mailman3/lists/zeek.lists.zeek.org/

Slack: https://zeek.org/community/

 Johanna
