### ISSUE TITLE
probelm with calculate the upload and download traffic

### ISSUE THREAD

**Issue by rfakit** [zeek/zeek#1915]
Hi 
I implemented SPAN SW port via zeek on that specific Ethernet . and send zeek data to ELK via the help of filebeat.
but in my setup. data calculation for in / out is not compatible with my PRTG data. 
I use orig_ip_bytes and resp_ip_bytes for my calculation
any advice where  i have gone wrong?

**Comment by 0xxon** [comment]
Hi,

We don't use GitHub issues for support questions. Questions like this are best answered using on either slack or our mailing list, which is both are frequented by Zeek developers and professional users. You can join here:

Mailing list: https://lists.zeek.org/mailman3/lists/zeek.lists.zeek.org/

Slack: https://zeek.org/community/

 Johanna

**Comment by rfakit** [comment]
no one answers neither mail nor slack.
do not close it. hope any one would encounter same issue helps me.
