### ISSUE TITLE
Why doesn't Zeek pick up HTTP requests on localhost?

### ISSUE THREAD

**Issue by brsolomon-deloitte** [zeek/zeek#1939]
To reproduce, on Ubuntu 20.04 as root:

```
apt-get update -y
apt-get install -y --no-install-recommends nginx
systemctl start nginx
```

Install Zeek to `PREFIX=/opt/zeek`. zeek version 4.0.4.

Create `$PREFIX/etc/node.cfg`:

```
[zeek]
type=standalone
host=localhost
interface=lo
```

Run `zeekctl deploy`. Confirm `zeekctl status` shows as `running`.

Then `tail -f $PREFIX/logs/current/*.log`

In another shell, `curl http://localhost` or `curl http://127.0.0.1`.

No `http.log` is created at all.  Why not?

Zeek does appear to see the connection otherwise, as `conn.log` shows

```
{"ts":1642618440.336267,"uid":"CWjO322gxWRo8LXR44","id.orig_h":"127.0.0.1","id.orig_p":59182,"id.resp_h":"127.0.0.1","id.resp_p":80,"proto":"tcp","conn_state":"OTH","local_orig":false,"local_resp":false,"missed_bytes":0,"history":"^cC","orig_pkts":0,"orig_ip_bytes":0,"resp_pkts":0,"resp_ip_bytes":0}
```

(though weirdly `resp_ip_bytes` is 0. Don't know why either.)

I can even do `for i in $(seq 100); do curl http://127.0.0.1; done` and get 100 `200 OK` responses. Still no `http.log` shows up. I can see in Wireshark that a capture of `lo` clearly shows the HTTP request from src=127.0.0.1, dest=127.0.0.1:80 that is `on interface lo`.

What am I missing here?

**Comment by JustinAzoff** [comment]
```
"history":"^cC",
```

Do you have a reporter.log? It should have this in it.

```
Your interface is likely receiving invalid TCP checksums, most likely from NIC checksum offloading.  By default, packets with invalid checksums are discarded by Zeek unless using the -C command-line option or toggling the 'ignore_checksums' variable.  Alternatively, disable checksum offloading by the network adapter to ensure Zeek analyzes the actual checksums that are transmitted.
```

Add

```
redef ignore_checksums = T;
```

to /opt/zeek/share/zeek/site/local.zeek

that will fix it.

**Comment by brsolomon-deloitte** [comment]
Confirming this fixed the issue. Thank you.

I ended up using

```
redef ignore_checksums_nets = {127.0.0.0/8};
```

Your note led me to the [FAQ](https://zeek.org/faq/) and the docs for `ignore_checksums_nets` mentioning this being used when `lo` is monitored specifically. In my opinion this could still be advertised more prominently since https://zeek.org/faq/ is not a part of https://docs.zeek.org/.
