### ISSUE TITLE
Vector slice assignment causing bad reference count

### ISSUE THREAD

**Issue by pbcullen** [zeek/zeek#1942]
Attempting vector slice assignment in Zeek 4.1 on a vector of records causes an abort with a bad reference count. In the attached script, the abort happens at line 19.
[vector_test.zeek.txt](https://github.com/zeek/zeek/files/7906194/vector_test.zeek.txt)

**Comment by vpax** [comment]
I believe I have a fix for this.  I'd like to test my branch for leaks just to make sure it's not introducing any - @timwoj any cheatsheet for how I might easily do that?  I can fire up Instruments on my MacOS system but it won't make this easy.  IIRC, we have an ASAN environment for leak-checking as part of CI, but I'm unclear on how I can actually use it (other than by submitting a PR, which I'm happy to do if that's easiest).

**Comment by vpax** [comment]
Now addresed by https://github.com/zeek/zeek/pull/1947, which has passed CI.
