### ISSUE TITLE
Default initializer for table not working in Zeek 4.1.1

### ISSUE THREAD

**Issue by pbcullen** [zeek/zeek#1945]
The &default initializer on a table doesn't seem to be properly initializing the value.
```
event zeek_init()
{
    local t: table[string] of vector of int &default=vector();

    print t["a"];
    t["a"] += 10;
    print t["a"];
}
```
The assignment in the above causes a segfault. Note that setting `t["a"] = vector()` before the assignment resolves the segfault.

**Comment by timwoj** [comment]
It looks like this was fixed on `master` already by https://github.com/zeek/zeek/pull/1932.
