### ISSUE TITLE
timer_mgr_inactivity_timeout appears to be vestigial

### ISSUE THREAD

**Issue by vpax** [zeek/zeek#1949]
While this is documented [here](https://docs.zeek.org/en/lts/scripts/base/init-bare.zeek.html?highlight=timer_mgr_inactivity_timeout#id-timer_mgr_inactivity_timeout), searching the source code it doesn't appear to actually do anything.

**Comment by timwoj** [comment]
This was probably removed when I combined all of the timer managers into a single one during the IO loop work. I agree it can be removed.
