### ISSUE TITLE
Cross-compiling zeek  && Gen-ZAM

### ISSUE THREAD

**Issue by yong-ruilin** [zeek/zeek#1963]
When I was cross-compiling, I encountered the following problem:
[ 84%] [sh] Generating ZAM operations
/bin/sh: 1: /home/ubuntu/tmp/zeek-4.1.1/build/src/Gen-ZAM: Exec format error
make[3]: *** [src/CMakeFiles/zeek_objs.dir/build.make:128：src/ZAM-AssignFlavorsDefs.h] 错误 2
make[3]: 离开目录“/home/ubuntu/tmp/zeek-4.1.1/build”
make[2]: *** [CMakeFiles/Makefile2:4627：src/CMakeFiles/zeek_objs.dir/all] 错误 2
make[2]: 离开目录“/home/ubuntu/tmp/zeek-4.1.1/build”
make[1]: *** [Makefile:163：all] 错误 2
make[1]: 离开目录“/home/ubuntu/tmp/zeek-4.1.1/build”

Briefly describe our compilation process：
1、./configure --builddir=../zeek-buildtools
2、cd ../zeek-buildtools
3、make binpac bifcl
4、cd zeek
5、./configure --toolchain=~/tmp/zeek-4.1.1/toolchain.cmake --with-binpac=$(pwd)/../zeek-buildtools/auxil/binpac/src/binpac --with-bifcl=$(pwd)/../zeek-buildtools/auxil/bifcl/bifcl
6、make

**toolchain.cmake:**

set(CMAKE_SYSTEM_NAME Linux)

set(toolchain /home/ubuntu/compiler/loongarch64-linux-gnu-2022-01-26-vector)
set(CMAKE_C_COMPILER   ${toolchain}/bin/loongarch64-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER ${toolchain}/bin/loongarch64-linux-gnu-g++)

set(CMAKE_FIND_ROOT_PATH
    /home/ubuntu/openwrt-21.02/staging_dir/target-loongarch64-linux-gnu_glibc
    ${toolchain}/loongarch64-linux-gnu/sysroot
)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

The Gen-ZAM executable is in the format of my target platform, but when cross-compiling it executes.
Can you help me analyze the problem?

**Comment by vpax** [comment]
`Gen-ZAM` is a program that generates C++ code that needs to be compiled into Zeek.  The problem you're encountering is that CMake isn't configured to build `Gen-ZAM` locally even though Zeek itself should be compiled for the target.  Unfortunately, I don't know enough about CMake to be able to fix this myself, that will take someone more familiar with it.  (The original structure currently there was done by Jon Siwek, but he's off doing other things now.)

**Comment by vpax** [comment]
By the way, `Gen-ZAM` produces the same output on any system, so a work-around would be to run it on one system and then copy the `build/src/ZAM-*` files it produces to the source tree you're using for your target.

**Comment by ckreibich** [comment]
@yong-ruilin would you be able to try out the solution in branch `topic/christian/gh-1963`? Your approach would remain the same, you'd just say 

    make binpac bifcl Gen-ZAM

in step 3, and step 5 becomes:

    ./configure --toolchain=~/tmp/zeek-4.1.1/toolchain.cmake --with-binpac=$(pwd)/../zeek-buildtools/auxil/binpac/src/binpac --with-bifcl=$(pwd)/../zeek-buildtools/auxil/bifcl/bifcl --with-gen-zam=$(pwd)/../zeek-buildtools/src/Gen-ZAM

Am I seeing correctly that you're attempting to build for OpenWRT? If so, that's exciting — by all means share your results on the Zeek Slack if you get it to work. I've long been meaning to revive those builds, but don't manage to find the time.
