### ISSUE TITLE
Decode or decapsulation of HP ERM (Encapsulated Remote Mirroring)

### ISSUE THREAD

**Issue by ilGino** [zeek/zeek#1968]
Hello,

I'd really appreciate to receive some indications on how to feed into zeek packets encapsulated with HP ERM (Encapsulated Remote Mirroring).

Basically HP/Aruba switches can mirror packets and send them to a remote IP destination, encapsulating them in UDP packets.

For example, wireshark can decapsulate/analyze packets received from such UDP streams.

https://www.wireshark.org/docs/dfref/h/hp_erm.html

If packets are not decapsulated/analyzed before being fed into zeek (or Wireshark), they do not provide relevant informations.

Regards
GG

**Comment by timwoj** [comment]
Assuming that it's always received on port 7932 (as https://wiki.wireshark.org/HPERM says), you could use the Skip packet analyzer to ignore it. Something like this should work:

```
export {
        redef PacketAnalyzer::SKIP::skip_bytes = 8;
        redef PacketAnalyzer::SKIP::default_analyzer = PacketAnalyzer::ANALYZER_ETHERNET;
}

event zeek_init()
{
	PacketAnalyzer::register_packet_analyzer(PacketAnalyzer::ANALYZER_UDP, 7932, PacketAnalyzer::ANALYZER_SKIP);
}
```

That also assumes that HP ERM is always encapsulating an ethernet frame, which it appears it is from the couple of pcaps I could pull from the Wireshark library.

That said, this falls more under a support question and we generally don't use GitHub issues for those types of questions. I'm going to close this out. If you have more questions about it, feel free to ping me on Slack. You're not the first person to ask about using the skip analyzer like this, so it might be a good idea for us to add some documentation around how that works.
