### ISSUE TITLE
`zeek-config --caf_root` returns an empty string

### ISSUE THREAD

**Issue by timwoj** [zeek/zeek#1980]
I didn't look but this may have started happening after the changes to remove CAF from the public broker API.

**Comment by Neverlord** [comment]
Probably. For Zeek, CAF is an implementation detail of Broker now. So, I think `caf_root` needs to be dropped altogether from https://github.com/zeek/zeek/blob/master/zeek-config.in. Are there any build or deployment scripts / pipelines that would break if we do?

**Comment by timwoj** [comment]
We could just cause the option to return an error if someone tries to use it, with a note that we'll be removing it later.
