### ISSUE TITLE
is_num("") == T ... is this intended?

### ISSUE THREAD

**Issue by keithjjones** [zeek/zeek#1982]
I was working on a project where the logic was something like:

```
if (is_num(val))
  mycountval = to_count(val);
```

When an empty string slips in for `val`, `is_num` is T and it threw a bug in the code I was working on.  The documentation is technically true:

https://docs.zeek.org/en/master/scripts/base/bif/strings.bif.zeek.html#id-is_num

```
Returns whether an entire string consists only of digits
```

But it seems logically it should return a F if there is no digit at all.

**Comment by ckreibich** [comment]
Agree, yeah. The implementations of the `is_num`, `is_alpha`, and `is_alnum` BiFs are all similar in that regard, so we should look into these too. The code for `is_num` says it's modeled on Python, but Python returns false on empty strings for that family of functions.
