### ISSUE TITLE
tunnel_changed event can be raised excessively when all traffic is encapsulated

### ISSUE THREAD

**Issue by JustinAzoff** [zeek/zeek#1991]
I recently saw a network where 100% of the traffic was encapsulated.  Furthermore, we seemed to see either duplicate traffic, or minimally, each half of a connection sent over a different tunnel.  Profiling showed that zeek was spending a large amount of its time in the tunnel script handling the tunnel_changed event.  This is because on that type of network, every single packet will trigger that event to be generated.

here's a pcap that I made that shows a similar issue:

[http_vxlan.pcap.zip](https://github.com/zeek/zeek/files/8172691/http_vxlan.pcap.zip)

I made it by splitting a connection into the two halves, encapsulating each part with a different vxlan tunnel, and then merging it back together.

The result is a connection that is processed properly, and while the logs don't show any outward facing issues, if you handle the tunnel changed event you see the following:

```
event tunnel_changed(c: connection, e: EncapsulatingConnVector) &priority=5
{
    print c$id, e;
}
```

```
$ zeek -Cr ./http_vxlan.pcap  ./t.zeek 
[orig_h=141.142.228.5, orig_p=59856/tcp, resp_h=192.150.187.43, resp_p=80/tcp], [[cid=[orig_h=10.10.10.1, orig_p=50000/udp, resp_h=10.10.10.2, resp_p=4789/udp], tunnel_type=Tunnel::VXLAN, uid=CYzVVV1jDfpsFppV6e]]
[orig_h=141.142.228.5, orig_p=59856/tcp, resp_h=192.150.187.43, resp_p=80/tcp], [[cid=[orig_h=10.10.10.1, orig_p=50000/udp, resp_h=10.10.10.3, resp_p=4789/udp], tunnel_type=Tunnel::VXLAN, uid=CAfuSm4Luk3Gt7RKdd]]
[orig_h=141.142.228.5, orig_p=59856/tcp, resp_h=192.150.187.43, resp_p=80/tcp], [[cid=[orig_h=10.10.10.1, orig_p=50000/udp, resp_h=10.10.10.2, resp_p=4789/udp], tunnel_type=Tunnel::VXLAN, uid=CYzVVV1jDfpsFppV6e]]
[orig_h=141.142.228.5, orig_p=59856/tcp, resp_h=192.150.187.43, resp_p=80/tcp], [[cid=[orig_h=10.10.10.1, orig_p=50000/udp, resp_h=10.10.10.3, resp_p=4789/udp], tunnel_type=Tunnel::VXLAN, uid=CAfuSm4Luk3Gt7RKdd]]
[orig_h=141.142.228.5, orig_p=59856/tcp, resp_h=192.150.187.43, resp_p=80/tcp], [[cid=[orig_h=10.10.10.1, orig_p=50000/udp, resp_h=10.10.10.2, resp_p=4789/udp], tunnel_type=Tunnel::VXLAN, uid=CYzVVV1jDfpsFppV6e]]
[orig_h=141.142.228.5, orig_p=59856/tcp, resp_h=192.150.187.43, resp_p=80/tcp], [[cid=[orig_h=10.10.10.1, orig_p=50000/udp, resp_h=10.10.10.3, resp_p=4789/udp], tunnel_type=Tunnel::VXLAN, uid=CAfuSm4Luk3Gt7RKdd]]
```

`Connection::CheckEncapsulation` only checks to see if the current encapsulation is the same as the previous, so every time it flips you get a `tunnel_changed`.  I'm not sure what the best way to fix this is, but I'd think capping the number of tunnel_changed events on a single connection to 5,10,20, whatever, should help.

**Comment by timwoj** [comment]
>  I'd think capping the number of tunnel_changed events on a single connection to 5,10,20, whatever, should help.

I think this would be fine. Would it make sense to also rate limit them like weirds, so you'd stop getting them after the limit, but then get one every 1000 packets or so? Or would that just add useless noise to the logs?
