### ISSUE TITLE
version field in http.log captures the version portion of the response instead of request

### ISSUE THREAD

**Issue by Cindylulu025** [zeek/zeek#1994]
Hello, based on official doc, the version field should capture "Value of the version portion of the request." - https://docs.zeek.org/en/master/scripts/base/protocols/http/main.zeek.html

However, based on my PCAP testing and reviewing souce code, zeek seems to extract HTTP version portion from the response instead of request -https://github.com/zeek/zeek/blob/master/scripts/base/protocols/http/main.zeek#L236

Is this intended? If not, could you help fix the version to capture from http request? 

Thank you!

**Comment by 0xxon** [comment]
This indeed seems like a bug and we should either fix the documentation or the behavior. Since it has been like this for a while - I am tempted to adjust the documentation...

**Comment by rsmmr** [comment]
Agree, also seems the more useful one I'd say.
