### ISSUE TITLE
notice.log unconditionally contains email_dest

### ISSUE THREAD

**Issue by awelzel** [zeek/zeek#2000]
This came up previously in internal discussions, but creating an issue for tracking.

Since Zeek 4.1, the notice.log unconditionally contains an `email_dest` field. Using the AsciiWriter with JSON, this is rendered as `email_dest: []` into every entry.

We're deploying Zeek on an appliance where email is not supported. The `mail_dest` field is always empty and the `email_dest` field in notice.log has no meaning in this scenario.

Some reasons are unnecessary extra bytes in the output, extra documentation needed for this new field and educating users what the `email_dest` field is for - with the unsatisfactory answer of "nothing/unused".

We'll work around it by removing it with `$exclude`.

Mostly wanted to raise that the field could've been opt-in rather than unconditionally added to the notice.log, particularly if it's unused / has no meaning / will always be empty in a default configuration. Is it too late now?

Thoughts?

**Comment by 0xxon** [comment]
Making the field &optional would remove it from the json output too, right?

Might that be a good enough solution?

Apart from that - are the extra bytes in a low-traffic log (which notice.log should be) really a huge problem? There always will be cases where a field that we include in a log won't do anything in a specific configuration/environment. We typically err on the side of including more than including less information.

**Comment by awelzel** [comment]
`&optional` would help. There is now the new `LogAscii::json_include_unset_fields`, so that would bring it back, but not for everyone.

I believe it'll still show up with the batch logs as a column (?). As an aside, that caused a bit of churn to update btests of packages baseline notice.log - we have a lot of those. We've added `zeek-cut` for pre-processing - and that was probably a good step.
 
> Apart from that - are the extra bytes in a low-traffic log (which notice.log should be) really a huge problem?

I have no numbers and it's probably not in practice.
