### ISSUE TITLE
fatal error: zeek/session/Session.h: No such file or directory

### ISSUE THREAD

**Issue by cybersecurity99** [zeek/zeek#2004]
Hi I got this error , I downloaded zeek using git clone
`[ 38%] Building CXX object src/session/CMakeFiles/bro_session.dir/Session.cc.o
/home/ctadmin/data/zeek/src/session/Session.cc:3:10: fatal error: zeek/session/Session.h: No such file or directory
 #include "zeek/session/Session.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
src/session/CMakeFiles/bro_session.dir/build.make:62: recipe for target 'src/session/CMakeFiles/bro_session.dir/Session.cc.o' failed
make[3]: *** [src/session/CMakeFiles/bro_session.dir/Session.cc.o] Error 1
`
session.h and session.cc are present in same directory

Any solutuions
Thanks

**Comment by 0xxon** [comment]
Could you give us the output of `git show --oneline -s` and `git submodule status` inside your checked out repository?

**Comment by timwoj** [comment]
Closing this due to a lack of information. Feel free to reopen if needed.
