### ISSUE TITLE
Add CAPWAP decap support

### ISSUE THREAD

**Issue by nonvegan** [zeek/zeek#2007]
Add ability to process the inner payload of CAPWAP packets. See https://datatracker.ietf.org/doc/html/rfc5415 and https://datatracker.ietf.org/doc/html/rfc5416 for the IEEE 802.11 binding.

**Comment by nonvegan** [comment]
Sure here's a sample of an encapsulated icmp request & reply.
[capwap_icmp.zip](https://github.com/zeek/zeek/files/8343231/capwap_icmp.zip)

**Comment by timwoj** [comment]
Looking at this pcap, this would probably be best served by adding another packet analyzer. It's unlikely we'd add built-in support for this but writing a 3rd party plugin to support it shouldn't be too much effort. You can follow any of the other tunnel analyzers as examples.

Given that there's not much for the team to do here, I'm going to close this one out.

**Comment by AmazingPP** [comment]
@nonvegan You can now use the [zeek-cpawa](https://github.com/AmazingPP/zeek-capwap) plugin.
