### ISSUE TITLE
Tricky config framework semantics

### ISSUE THREAD

**Issue by ckreibich** [zeek/zeek#201]
At least for new-comers to the framework it can be tricky to consistently trigger initialization/update code given a config option's value. Consider this:

    module Foo;
    
    export { option foo = F; }
    
    function foo_handler(ID: string, foo_new: bool): bool
    {
        print fmt("New foo: %s", foo_new);
        
        # Update stuff here based on foo's value
        # ...
        
        return foo_new;
    }
    
    event bro_init() {
        Option::set_change_handler("Foo::foo", foo_handler);
    }

Here, `foo_handler` doesn't get called when you simply run the script without redefing `Config::config_files`. When you do redef it, the handler fires both when the config file sets foo to `T`, and when it sets it to `F`.

So you have to make sure that your initialization happens even when the handler doesn't get called, and you cannot write your handler assuming that the new value is actually different from the old one.

These arguably aren't bugs, but they do take getting used to. Perhaps worth coming up with some design patterns or additional documentation. If we do want to change functionality, we could consider adding a mechanism that lets the user specify that they'd like to see the change handler triggered once at startup, and that they'd like to skip repeat invocations with the same value.

**Comment by 0xxon** [comment]
Just to state the obvious - you are obviously right with your example.

The reason that change handlers do get called one time when a configuration file was read, even if there was no change is that it is internally a bit... challenging to figure out if there has been a change between an old value and a new one and I thought it is just safer to get people used to the fact that change-handlers can fire several times.

There is a whole bunch of reasons for that. While for a simple example (e.g. having a boolean) not calling the change handler seems easy, things get a bit more complicated when there are complex datatypes (we don't really have an easy way to compare equality for some of them). Furthermore - some change-handlers will reformat the input data. So the current semantics are "the change handler is called whenever the respective configuration data reader deems it necessary; in case of configuration files they are called when the ascii-representation of the configuration value in the file changes".

In any case - I will add that explanation.

As to the second part - I am in principle happy to add something that calls the change handler once on Bro init with the initialization value. I think this behavior should be opt-in though; it might be only me but I actually like the way that it currently works (you have one kind-of-reasonable value defined on startup and one when things change).

Do you have an idea on the syntax you would like for an opt-in? Or would you be ok with the current behavior just being explained in documentation? I actually don't have especially strong feelings in any direction.

**Comment by rsmmr** [comment]
For the opt-in, could just be an additional argument to set_event_handler(), and fire immediately at that point?

**Comment by rsmmr** [comment]
Sounds like resolution here is just more documentation, can you add that @0xxon ?

**Comment by 0xxon** [comment]
Will try to do by the end of next week :)

**Comment by 0xxon** [comment]
@ckreibich - could you take a look at https://github.com/zeek/zeek-docs/pull/33 and see if this makes things clearer?

**Comment by ckreibich** [comment]
Looks great! Only one suggestion: add a bullet point (or expand the first one) to clarify that when there's no config file (or they don't include the corresponding option) the change handler doesn't get invoked. So if your code has an initialization route for a given option, you may have to ensure it runs, if you want to protect against this setting. In some of my code I invoke the change handler manually from `zeek_init()` to do this.
