### ISSUE TITLE
Cannot add package to zeek

### ISSUE THREAD

**Issue by ferburri** [zeek/zeek#2011]
Hello everyone :) . 
I have a problem when I trying to upload a package to zeek. I've installed [icsnpp-dnp3](https://packages.zeek.org/packages/view/c80bb6b9-9348-11eb-81e7-0a598146b5c6) package by zkg. 
When I installed this package and edit my `site/local.zeek`, I use the command `zeekctl deploy` but I had and error:

install package by zkg:
```
zeek@zeek-VirtualBox:~$ zkg install icsnpp-dnp3
The following packages will be INSTALLED:
  zeek/cisagov/icsnpp-dnp3 (main)

Proceed? [Y/n] Y
Installing "zeek/cisagov/icsnpp-dnp3"
Installed "zeek/cisagov/icsnpp-dnp3" (main)
Loaded "zeek/cisagov/icsnpp-dnp3"
```
See if this package is installed:
```
zeek@zeek-VirtualBox:~$ zkg list
zeek/cisagov/icsnpp-dnp3 (installed: main) - DNP3 script for detailed logging of the DNP3 protocol - CISA ICSNPP
```
Update site/local.zeek: 
```
# Uncomment this to source zkg's package state
@load packages
```
Deploy zeek to save the configuration:
```
zeek@zeek-VirtualBox:~$ sudo zeekctl deploy
checking configurations ...
zeek scripts failed.
fatal error in /usr/local/zeek/share/zeek/site/local.zeek, line 105: can't find packages
```

I do not know how can I deploy with this package. Thanks in advance :)

**Comment by timwoj** [comment]
Hi,

We don't use GitHub issues for support questions. Questions like this are best answered using on either slack or our mailing list, which is both are frequented by Zeek developers and professional users. You can join here:

Mailing list: https://lists.zeek.org/mailman3/lists/zeek.lists.zeek.org/

Slack: https://zeek.org/community/

Tim

**Comment by ferburri** [comment]
Hi @timwoj, thanks for your answer :)
