### ISSUE TITLE
Why Zeek doesn't free memory forever ? 

### ISSUE THREAD

**Issue by cxdinter** [zeek/zeek#2018]
Hi,
   Sorry, maybe the title is not exact. 
   But, My feeling is that Zeek always keep the allocated memory and don't free them. I done a simple test, use command 'nmap -A IPAdress -p- -Pn' for full port scan. During that, Zeek will increase about 20MB ~ 30MB memory. But, after nmap finished, and leave the board for several hours, Zeek still keep these new memory. 
   Why ?

**Comment by VijayPakhale** [comment]
@cxdinter , Hi, How this issue was resolved ? Do you remember ?? 
I am also getting the same issue.
