### ISSUE TITLE
'/bin/sh -c make -C /src/zeek distclean' returned a non-zero code: 2

### ISSUE THREAD

**Issue by neg-loss** [zeek/zeek#2022]
When I ran the docker build command, while running step 4 of the it, that error occurred.

This is what I got,

Sending build context to Docker daemon  13.82kB
Step 1/12 : FROM debian:bullseye-slim AS build
 ---> 6578cd967f7f
Step 2/12 : RUN apt-get -q update  && apt-get install -q -y --no-install-recommends      bind9      bison      cmake      flex      g++      gcc      libmaxminddb-dev      libpcap-dev      libssl-dev      libz-dev      make      python3-minimal      python3.9-dev      swig      ninja-build      python3-pip  && apt-get clean  && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> c07b2654533c
Step 3/12 : COPY . /src/zeek
 ---> Using cache
 ---> 9382d52923af
Step 4/12 : RUN make -C /src/zeek distclean
 ---> Running in bf83b91f9adb
make: Entering directory '/src/zeek'
make: Leaving directory '/src/zeek'
make: *** No rule to make target 'distclean'.  Stop.
The command '/bin/sh -c make -C /src/zeek distclean' returned a non-zero code: 2

**Comment by ckreibich** [comment]
@neg-loss, are you triggering the build via `make` in the `docker` subdirectory of a full Zeek tree? If you're triggering it differently, you may be missing the directory traversal needed so the build copies the full tree into the image. If that's not it, see whether anything happened to your source tree prior to you running `make`.

Either way, things are likely are going wrong in step 3, where our setup copies the local source tree into the image:

```
Step 3/12 : COPY . /src/zeek
---> Using cache
---> 9382d52923af
```

As a result, I suspect the toplevel Makefile wasn't there at all, or wasn't the one intended.

**Comment by ckreibich** [comment]
I'm going to go ahead and close this one because I don't think there's a bug, but feel free to reopen, @neg-loss, if you feel I didn't nail it. Thanks.
