### ISSUE TITLE
ProtocolConfirmation() needs to check for analyzer_confirmation

### ISSUE THREAD

**Issue by pbcullen** [zeek/zeek#2026]
Regarding the deprecation of the protocol_confirmation event coming in Zeek 5.1... if an analyzer plugin uses only analyzer_confirmation(), that event doesn't ever get called. This is with Zeek 4.2. It seems [this line](https://github.com/zeek/zeek/blob/master/src/analyzer/Analyzer.cc#L688) in ProtocolConfirmation() should also check analyzer_confirmation - more specifically, `if ( ! protocol_confirmation && ! analyzer_confirmation )`.
The ProtocolViolation) method also has the same issue.

**Comment by 0xxon** [comment]
Seems like something we should fix in 4.2.x.
