### ISSUE TITLE
Input-Framework `$mode=Input::STREAM` does not reopen a rotated file

### ISSUE THREAD

**Issue by initconf** [zeek/zeek#2028]
First noticed by @leres  - upon log rotation, input-framework if used in `$mode=Input::STREAM` won't attempt to reopen a sparsely used log file. 

Here a test-code to help reproduce this issue. 

```
module Test;

redef exit_only_after_terminate = T;

export {
        type lineVals: record {
                d: string;
        };

        global auth_file = "/home/bro/zeek-cpp/host/policies/testfile.log";
}

event reporter_error(t: time, msg: string, location: string)
{
        if ( /testfile/ in msg ) {
                print fmt("bakwas error: %s, %s, %s", t, msg, location);
        }
}

event raw_auth_data(description: Input::EventDescription, tpe: Input::Event,
    line: lineVals)
{
        print fmt("%s", line$d);
}

event zeek_init()
{
    local config_strings: table[string] of string = {
        ["offset"] = "-1",
                                    };

    Input::add_event([
        $source=auth_file,
        $name="RawAuthData",
        $fields=lineVals,
        $ev=raw_auth_data,
        $config=config_strings,
        $reader=Input::READER_RAW,
        $mode=Input::STREAM]);
}
```

then :

```
$ touch /home/zeek/zeek-cpp/host/policies/testfile.log
$ echo "hello zeek"  >> testfile.log
$ mv testfile.log b
$ cat b >> testfile.log
```

**Comment by 0xxon** [comment]
So - this one is interesting. Because I think Zeek is currently behaving like it should, according to documented behavior. To quote from https://docs.zeek.org/en/master/frameworks/input.html:

> When using the streaming mode (i.e., $mode=Input::STREAM), Zeek assumes that the input is an append-only file to which new data is continually appended. Zeek continually checks for new data at the end of the file and will add the new data to the table.

To me this implies that Zeek opens a file once, and does essentially the same as `tail -f`. However, I can see that we want an equivalent to `tail -F` too. That should probably be a configuration switch - or a new mode though. At least in my opinion.

**Comment by initconf** [comment]
I'd also second to @leres note ! `tail -F` is a preferred mechanism any time over `-f` - esp. given that new syslog archival systems do tend to rotate the log files every N days or so! so if we are to read in streaming mode, odds are high its a syslog file which will get rotated. 

Also, the failure is very silent! ie file disappears and we'd keep thinking, zeek is reading it. 

We were looking at `zeek-4.2.0/src/input/readers/raw/Raw.CC` 

https://github.com/zeek/zeek/blob/5ccc3ea156107c70f36cf07331a71d22085c9b54/src/input/readers/raw/Raw.cc#L591

seems like instead of just giving up, if we can have `OpenInput()` be called periodically - that would make this a `-F`

**Comment by timwoj** [comment]
@0xxon Is this one finished with the PR above and the one that followed it?
