### ISSUE TITLE
Missing `Analyzer{Confirmation,Violation}` methods for file analyzers

### ISSUE THREAD

**Issue by rsmmr** [zeek/zeek#2031]
Both protocol and packet analyzers have them, but file analyzers don't. Seems for consistency we should add them otherwise it's unclear how to report those conditions for files.

Also, should those feed into dpd.log as well then? Probably not, because `base/frameworks/dpd/main.zeek` is tailored to protocols. But what else to do with them?

And actually: what do we do with packet analyzer violations currently?

**Comment by awelzel** [comment]
We have the more generic `_info` versions of the confirmation/violation events now and the file analyzer class has respective C++ methods now, too.

> Also, should those feed into dpd.log as well then? Probably not, because base/frameworks/dpd/main.zeek is tailored to protocols. But what else to do with them?


Related comment from @rsmmr over at spicy-plugin: https://github.com/zeek/spicy-plugin/issues/101#issuecomment-1081759145

> We record parse errors in a separate log file, say spicy.log or analyzers.log. We'd probably want to make creation of that optional too in case people aren't interested.

I like the `analyzer.log` that logs all violations regardless of analyzer type and confirmation state. It would likely end-up with a few optional fields or a generic string field. Imagining that this is more on the debug side of things. Optionally logging confirmations might be interesting, too. 

> And actually: what do we do with packet analyzer violations currently?

Depends of whether they have an associated connection: If they have one and it was confirmed, it should get logged via dpd.zeek. If there's only a confirmation, c$service / c$conn$service will contain it).

If there's no connection associated with a packet analyzers, confirmations/violations are not propagated to script land.

---

I'm proposing to close this issue and opening a new one for the `analyzer.log` creation. Other thoughts?
