### ISSUE TITLE
Allow @ifdef to work on module namespaces

### ISSUE THREAD

**Issue by ynadji** [zeek/zeek#2034]
Exported variables in modules can be used in `@ifdef`, but the module namespaces themselves cannot. For example:

```zeek
$ cat bar.zeek
module Bar;

export {
  option exists = T;
}
$ cat foo.zeek
event zeek_init()
{
  @ifdef ( Bar::exists )
    print "Bar is defined";
  @endif
}
$ zeek foo.zeek
$ zeek bar.zeek foo.zeek
Bar is defined
$ cat foo2.zeek
event zeek_init()
{
  @ifdef ( Bar )
    print "Bar is defined";
  @endif
}
$ zeek foo2.zeek
$ zeek bar.zeek foo2.zeek
```

It would be cleaner, imo, if `@ifdef` also worked on the module namespace itself.

**Comment by timwoj** [comment]
I don't think we store off a list of the module names anywhere. We do lookups based on them because IDs are stored with the module name attached, but there's nothing that specifically stores just the module names. That's not to say we couldn't store them though.
