### ISSUE TITLE
Non-selectable packet sources sleep even with data available when polling

### ISSUE THREAD

**Issue by antcodd** [zeek/zeek#2038]
Some PktSrc packets sources do not have a selectable file descriptor, such as Endace DAG and Myricom. Currently `PktSrc::GetNextTimeout` always returns a fixed timeout of 20 microseconds for such sources regardless of whether they have packets available. This adds unnecessary delay when packets are available to be read. Instead Zeek should check whether packets are available (at least for non-selectable sources) and return a timeout of 0 to indicate data is available. This is closer to the behaviour of the old capture loop. 

This is mitigated somewhat by the fact `iosource::Manager::FindReadySources` poll interval defaults to 100 packets, and live sources are added to the ready list regardless of whether they have packets available (unless it is time to force a poll). The poll interval is supposed to be set to 10 at `iosource::Manager::Register` time for Live sources, but this has never worked as they are checked before `props.is_live` is initialized. This can be important for reducing CPU load in low traffic situations as checking for new data can be quite expensive, but could also affect performance from spending more time in kqueue polls.

There are somewhat conflicting comments about whether it is better to have a high or low poll interval for live capture sources:

From ``iosource::Manager::Register`` (this is the part that doesn't work as the inner Register call needs moving to before the isLive check)
```
void Manager::Register(PktSrc* src)
	{
	pkt_src = src;

	// The poll interval gets defaulted to 100 which is good for cases like reading
	// from pcap files and when there isn't a packet source, but is a little too
	// infrequent for live sources (especially fast live sources). Set it down a
	// little bit for those sources.
	if ( src->IsLive() )
		poll_interval = 10;
	else if ( run_state::pseudo_realtime )
		poll_interval = 1;

	Register(src, false);
	}
```
From ``iosource::Manager::FindReadySources``
```
// Avoid calling Poll() if we can help it since on very
// high-traffic networks, we spend too much time in
// Poll() and end up dropping packets.
```

Note that fixing the poll interval requires the non-selectable GetNetTimeout fix or capture performance from non-selectable sources becomes extremely poor from unconditionally sleeping every 10 packets.

It may make sense for Zeek to go back to always checking for new data and always polling when no data is available for non-selectable or all packet sources, this would work better for sources with expensive data polling but the broader effect on other packet sources with e.g. bursty traffic isn't clear. I'm assuming the rewrite of the capture loop to reduce polling were done for good reason. Any changes to the capture loop need to be careful to avoid reintroducing the double processing fixed by #1135.

**Comment by antcodd** [comment]
I've raised a PR with a proposed fix for the non-selectable sleep part of this issue. I'm not sure what more general changes make the most sense for the variety of packet sources/iosources Zeek supports and welcome any discussion or alternate solutions/PRs.

**Comment by timwoj** [comment]
Fixed via https://github.com/zeek/zeek/commit/37df5a30b1f1ab7d2c584072e4d1816c4ee22fd1
