### ISSUE TITLE
I found a problem in a fuzzing test.This will cause ZEEK to exit abnormally.

### ISSUE THREAD

**Issue by wubonetcn** [zeek/zeek#2044]
I found a problem in a fuzzing test.This will cause ZEEK to exit abnormally.
I uploaded this test file.You can try it yourself.
I find same sqlite3.c is repeated in /src/3rdparty/ and /auxil/broker/3rdparty/.

```
fuzzer@ubuntu:~$ /usr/local/zeek/bin/zeek -Cr a.fuzz 
=================================================================
==3444==ERROR: AddressSanitizer: odr-violation (0x000005ee1160):
  [1] size=7 'sqlite3_version' ../src/3rdparty/sqlite3.c:1244:23
  [2] size=7 'sqlite3_version' ../auxil/broker/3rdparty/sqlite3.c:1244:23
These globals were registered at these points:
  [1]:
    #0 0x1030c20  (/usr/local/zeek/bin/zeek+0x1030c20)
    #1 0x19065dd  (/usr/local/zeek/bin/zeek+0x19065dd)

  [2]:
    #0 0x1030c20  (/usr/local/zeek/bin/zeek+0x1030c20)
    #1 0x7fdd0ba62ccd  (/usr/local/zeek/lib/libbroker.so.4+0x2c19ccd)

==3444==HINT: if you don't care about these errors you may set ASAN_OPTIONS=detect_odr_violation=0
SUMMARY: AddressSanitizer: odr-violation: global 'sqlite3_version' at ../src/3rdparty/sqlite3.c:1244:23
==3444==ABORTING
```
[a.zip](https://github.com/zeek/zeek/files/8470826/a.zip)

**Comment by 0xxon** [comment]
Hi,

the fact that we have an odr violation is known, and not considered a problem. Note that the fact that you have to disable odr violation checks is called out in our fuzzing readme at https://github.com/zeek/zeek/blob/master/src/fuzzers/README

I am going to close this - feel free to re-open, or create new bugs if you find any other issues.
