### ISSUE TITLE
hook_names is missing "Reporter"

### ISSUE THREAD

**Issue by pbcullen** [zeek/zeek#2052]
As noted in the [comment for hook_names](https://github.com/zeek/zeek/blob/master/src/plugin/Plugin.cc#L23), the order must match that of HookType. There's a HOOK_REPORTER after HOOK_LOG_WRITE, but there's no "Reporter" in [hook_names](https://github.com/zeek/zeek/blob/master/src/plugin/Plugin.cc#L34). 

Running `zeek -NN` against a plugin that implements HOOK_REPORTER will give the wrong information about implemented hooks.

**Comment by ckreibich** [comment]
Thanks Peter! This also affects 4.0.x and 4.2.x.
