### ISSUE TITLE
Is it possible to extract the pcap from connection?

### ISSUE THREAD

**Issue by OhYee** [zeek/zeek#2073]
Is it possible to extract the pcap from connect? Or extract pcap from a tcp or udp session?

I found that I can extract the current tcp packet by `dump_packet(get_current_packet(), "test.pcap");`
Is there a way to get the full tcp session?

Or trigger the `file_sniff` event at the end of tcp and udp and extract it via `Files::ANALYZER_EXTRACT`

**Comment by 0xxon** [comment]
Hi,

We don't use GitHub issues for support questions. Questions like this are best answered using on either slack or our mailing list, which is both are frequented by Zeek developers and professional users. You can join here:

Slack: https://zeek.org/community/

Mailing list: https://lists.zeek.org/mailman3/lists/zeek.lists.zeek.org/

 Johanna
