### ISSUE TITLE
@if block parsing problem when located within lambda return value

### ISSUE THREAD

**Issue by 0xxon** [zeek/zeek#2075]
I tried making some script-code backwards compatible and notices that this code...

```zeek
function test()
	{
	local make_epoch_result = function(pass_name: string): function(ts: time)
		{
@if ( Version::at_least("4.1") )
		return function [pass_name] (ts: time)
@else
		return function (ts: time)
@endif
			{
			print pass_name;
			};
		};

	}
```

Throws the following error when run with a current master version of Zeek:

```
error in ./test2.zeek, line 7: syntax error, at or near "@else"
```

I _think_ that this is supposed to work fine - but someone please correct me if I am incorrect. One can work around this problem by changing the placement of the `{` after the return statement.

**Comment by awelzel** [comment]
This appears to be fixable via the following hunk, but not sure #2289 is that easy, too.

```
 anonymous_function:
-               TOK_FUNCTION begin_lambda lambda_body
-                       { $$ = $3; }
+               TOK_FUNCTION begin_lambda conditional_list lambda_body
+                       { $$ = $4; }
        ;
```

**Comment by awelzel** [comment]
> @awelzel will that change really work? The { for the body that precedes the @if in the example is part of the lambda_body, so that conditional will be prior to any elements of the body.

I will take a closer look tomorrow. I added a btest with above example and it seemed to work. Will double check and get back to you. Thanks for looking.

**Comment by awelzel** [comment]
@vpax - the example of this ticket involves a lamda returning a lambda. It's the `@else` following `function [pass_name] (ts: time)` (`begin_lambda`) what upsets the parsing. The first `@if` within the lambda_body seems to work out as it's part of lambda_body's stmt_list.

The proposed fix is similar to what we do for func_hdr / func_body:

https://github.com/zeek/zeek/blob/fad18cb352d245e1076e7b2a23d229b3c4af463f/src/parse.y#L1401-L1406

I've opened a PR, please chime in if I misunderstood or you have further concerns/thoughts. Thanks!

**Comment by vpax** [comment]
@awelzel I see.  Given that change, does the snippet at the top now work correctly?

**Comment by awelzel** [comment]
> @awelzel I see. Given that change, does the snippet at the top now work correctly?

Yep. I've added it here as a test-case:

https://github.com/zeek/zeek/pull/2346/files#diff-c7537e2ab0b02836a74f51fd55edd9a3fee02a971df499131030bd24b12f7dc1R8

**Comment by vpax** [comment]
> Yep. I've added it here as a test-case:

Great!
