### ISSUE TITLE
Build failure if older version of c-ares already exists on the system

### ISSUE THREAD

**Issue by timwoj** [zeek/zeek#2101]
Thanks to @leres for tracking this down a bit further.

If an older version of c-ares is already installed on the system in /usr/local, Zeek builds will fail with the following error:

```
[ 29%] Building C object auxil/c-ares/src/lib/CMakeFiles/c-ares.dir/ares__addrinfo2hostent.c.o
/home/leres/TEST/zeek-master.git/auxil/c-ares/src/lib/ares__addrinfo2hostent.c:132:41: error: no member named 'name' in 'struct ares_addrinfo'
      (*host)->h_name = ares_strdup(ai->name);
                                    ~~  ^
/home/leres/TEST/zeek-master.git/auxil/c-ares/src/lib/ares__addrinfo2hostent.c:133:42: error: no member named 'name' in 'struct ares_addrinfo'
      if ((*host)->h_name == NULL && ai->name)
                                     ~~  ^
2 errors generated.
*** Error code 1
```

From https://github.com/zeek/zeek/pull/2097#issuecomment-1125535533:

> 
> What I've found is that auxil/c-ares/src/lib/CMakeFiles/c-ares.dir/flags.make defines C_INCLUDES and puts -I/usr/local/include before -I/home/leres/TEST/leres-zeek.git/auxil/c-ares/include:
> 
> ```
> -I/home/leres/TEST/leres-zeek.git/auxil/rapidjson/include
> -I/home/leres/TEST/leres-zeek.git/auxil/paraglob/include
> -I/home/leres/TEST/leres-zeek.git/auxil/highwayhash
> -I/home/leres/TEST/leres-zeek.git/build/auxil/broker/include
> -I/home/leres/TEST/leres-zeek.git/auxil/broker/include
> -I/usr/local/include
> -I/home/leres/TEST/leres-zeek.git/build/auxil/binpac/lib
> -I/home/leres/TEST/leres-zeek.git/auxil/binpac/lib
> -I/home/leres/TEST/leres-zeek.git/build/auxil/c-ares
> -I/home/leres/TEST/leres-zeek.git/auxil/c-ares
> -I/home/leres/TEST/leres-zeek.git/auxil/c-ares/include
> -I/home/leres/TEST/leres-zeek.git/auxil/c-ares/src/lib/include
> ```
> 
> But I don't understand what determines the order so I don't know how to change it.

This is probably a blocker for 5.0.

**Comment by leres** [comment]
Two things: First, I think this is really a c-ares issue and I'm tooling up to test c-ares by itself. Second, the old version of c-ares installed on Aashish's test box is 1.17.2.

**Comment by leres** [comment]
> I think this is really a c-ares issue and I'm tooling up to test c-ares by itself.

I guess I need to walk that back; I don't see errors when building c-ares by itself.

This might not be optimal but it fixes the build when c-ares 1.17.2 is installed in /usr/local:
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 5f7df8ffd..dea1ad695 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -480,6 +480,7 @@ include(CheckNameserCompat)
 include(GetArchitecture)
 include(RequireCXX17)
 include(FindKqueue)
+include_directories(BEFORE "auxil/c-ares/include")
 include(FindCAres)
 include_directories(BEFORE "auxil/out_ptr/include")
```

**Comment by timwoj** [comment]
Can you try this patch to `cmake/FindCAres.cmake` instead?

```
diff --git a/FindCAres.cmake b/FindCAres.cmake
index d9e9ffd..b3e8f1b 100644
--- a/FindCAres.cmake
+++ b/FindCAres.cmake
@@ -39,6 +39,8 @@ if ( NOT HAVE_CARES )
 
   else()
 
+    include_directories(BEFORE "auxil/c-ares/include")
+
     OPTION (CARES_STATIC "" ON)
     OPTION (CARES_SHARED "" OFF)
     OPTION (CARES_INSTALL "" OFF)
```

That at least keeps it all contained in one place.

**Comment by leres** [comment]
Yes, your version works. It looks like it's the add_subdirectory(auxil/c-ares) that causes problems, when I move the include_directories() after it then the include path is wrong.

Even would  be to just rearrange the statements; that way we don't have to add anything (and the include will be relative to CMAKE_CURRENT_SOURCE_DIR):
```
zinc 126 % pwd
/var/tmp/leres-zeek.git/cmake
zinc 127 % git diff
diff --git a/FindCAres.cmake b/FindCAres.cmake
index d9e9ffd..df47035 100644
--- a/FindCAres.cmake
+++ b/FindCAres.cmake
@@ -47,17 +47,18 @@ if ( NOT HAVE_CARES )
     OPTION (CARES_BUILD_CONTAINER_TESTS "" OFF)
     OPTION (CARES_BUILD_TOOLS "" OFF)
 
-    add_subdirectory(auxil/c-ares)
-
     set(cares_src   "${CMAKE_CURRENT_SOURCE_DIR}/auxil/c-ares")
     set(cares_build "${CMAKE_CURRENT_BINARY_DIR}/auxil/c-ares")
     set(cares_lib   "${cares_build}/${CMAKE_INSTALL_LIBDIR}/libcares.a")
 
-    set(HAVE_CARES true)
-    set(zeekdeps ${zeekdeps} ${cares_lib})
     include_directories(BEFORE ${cares_src}/include)
     include_directories(BEFORE ${cares_build})
 
+    add_subdirectory(auxil/c-ares)
+
+    set(HAVE_CARES true)
+    set(zeekdeps ${zeekdeps} ${cares_lib})
+
   endif()
 endif()
```

**Comment by timwoj** [comment]
If you do that, does it still add `/usr/local/include`?

**Comment by leres** [comment]
Yes:
```
-I/var/tmp/leres-zeek.git/build/auxil/c-ares
-I/var/tmp/leres-zeek.git/auxil/c-ares/include
-I/var/tmp/leres-zeek.git/auxil/rapidjson/include
-I/var/tmp/leres-zeek.git/auxil/paraglob/include
-I/var/tmp/leres-zeek.git/auxil/highwayhash
-I/var/tmp/leres-zeek.git/build/auxil/broker/include
-I/var/tmp/leres-zeek.git/auxil/broker/include
-I/usr/local/include
-I/var/tmp/leres-zeek.git/build/auxil/binpac/lib
-I/var/tmp/leres-zeek.git/auxil/binpac/lib
-I/var/tmp/leres-zeek.git/auxil/c-ares
-I/var/tmp/leres-zeek.git/auxil/c-ares/src/lib
```

**Comment by timwoj** [comment]
I have a FreeBSD VM here to try to reproduce this on. I have c-ares installed from pkg as version 1.17.2. It's using cmake 3.22.1. For whatever reason, it's not discovering the installed c-ares and everything builds fine. What command-line are you using for `configure`?

**Comment by ckreibich** [comment]
Same here, fyi, on a fresh FreeBSD 12.3, cmake 3.22.2, c-ares via `pkg install c-ares` at 1.17.2. Builds fine. I haven't looked at the .cmake files you guys discussed above.

**Comment by leres** [comment]
> Second, the old version of c-ares installed on Aashish's test box is 1.17.2.

Sorry, it's 1.17.1 that causes problems on Aashish's box.

**Comment by leres** [comment]
[28f7827](https://github.com/zeek/zeek/commit/28f78271f08f5650862327a91ba01a8becff0d6c) does't work for me, after building /usr/local/include is still too early on the include path:
```
adhoc 10 % fmt -1 build/auxil/c-ares/src/lib/CMakeFiles/c-ares.dir/flags.make| egrep ^-I
-I/home/leres/TEST/zeek-master.git/auxil/rapidjson/include
-I/home/leres/TEST/zeek-master.git/auxil/paraglob/include
-I/home/leres/TEST/zeek-master.git/auxil/highwayhash
-I/home/leres/TEST/zeek-master.git/build/auxil/broker/include
-I/home/leres/TEST/zeek-master.git/auxil/broker/include
-I/usr/local/include
-I/home/leres/TEST/zeek-master.git/build/auxil/binpac/lib
-I/home/leres/TEST/zeek-master.git/auxil/binpac/lib
-I/home/leres/TEST/zeek-master.git/build/auxil/c-ares
-I/home/leres/TEST/zeek-master.git/auxil/c-ares
-I/home/leres/TEST/zeek-master.git/auxil/c-ares/include
-I/home/leres/TEST/zeek-master.git/auxil/c-ares/src/lib
```

**Comment by timwoj** [comment]
Are you sure you pulled the cmake submodule update? That's the same change that it's in https://github.com/zeek/zeek/issues/2101#issuecomment-1126543016 which was working for you.

**Comment by leres** [comment]
Ah, I did:

`git submodule update --recursive`

and that works a lot better.

(Yes, I suck at git too.)

**Comment by timwoj** [comment]
Fixed via https://github.com/zeek/zeek/pull/2143
