### ISSUE TITLE
Btest failures with OpenSSL 3.0.1 on CentOS Stream 9

### ISSUE THREAD

**Issue by timwoj** [zeek/zeek#2115]
There's apparently some bug in the OpenSSL 3.0.1 package on CentOS Stream 9 that causes some of our btests to fail with a "certificate signature failure" warning. It's only on that one platform because 3.0.0+ work just fine on other platforms (@0xxon notes she tested up to 3.0.3 on another machine).

See https://cirrus-ci.com/task/5837691458682880 as an example of the failures.

**Comment by 0xxon** [comment]
I just set up a CentOS 9 stream VM - and can confirm that this happens there every time.

I may not have the time to dig deeply into this this week - but I can try at the beginning of next week.
