### ISSUE TITLE
In cluster configuration, how could I judge which interface the network traffic comes from

### ISSUE THREAD

**Issue by CindyStudyEveryday** [zeek/zeek#2137]
I want to listen to multiple interface on a network, but the log file does not contain interface information, how should I determine which interface the network traffic is from? Are there any solutions here? I thought about ways to add fields, but I didn't know how to do it .

**Comment by timwoj** [comment]
I don't believe we keep any information about what interface a packet came in from currently in the code. It would depend on whatever packet source plugin you're using having that information available. That said, for the logging part you'll want to look at the docs for the logging framework at https://docs.zeek.org/en/master/frameworks/logging.html. It describes how to add new logs and how to extend existing ones.

**Comment by CindyStudyEveryday** [comment]
> 

Thank you！I read this think I know how to add some easy fields, as the Boolean field in the example，but I don't know how to associate the added fields with the the desired information，the question goes back to how to obtain the network interface.

**Comment by CindyStudyEveryday** [comment]
> I don't believe we keep any information about what interface a packet came in from currently in the code. It would depend on whatever packet source plugin you're using having that information available. That said, for the logging part you'll want to look at the docs for the logging framework at https://docs.zeek.org/en/master/frameworks/logging.html. It describes how to add new logs and how to extend existing ones.

Thank you！I read this and I think I know how to add some easy fields, as the Boolean field in the example，but I don't know how to associate the added fields with the the desired information，the question goes back to how to obtain the network interface.

**Comment by J-Gras** [comment]
This might not be what you are looking for but in a cluster setup, worker nodes know about the interface they are listening on. The following zkg package adds this information to conn.log (and others if configured): https://github.com/J-Gras/add-interfaces

**Comment by awelzel** [comment]
I'm going to close this ticket as it's better suited for https://community.zeek.org unless there's anything we want to implement to support this. @CindyStudyEveryday - feel free to start a new thread there.

A related topic has come up here (the goal is to add interface information into the path of the log file):
https://community.zeek.org/t/how-to-set-logging-path-by-interface/6659

Also, if you're a `zeekctl`, the `Cluster::nodes` is likely populated with the information you want and the package @J-Gras pointed you at would probably work.
