### ISSUE TITLE
BIF to obtain autonomous_system_organization

### ISSUE THREAD

**Issue by philrz** [zeek/zeek#2141]
I help maintain a Zeek package https://github.com/brimdata/geoip-conn that adds geolocation data to Zeek `conn` records. Up until now it's only added fields for the data returned by the `lookup_location()` BIF. A community user recently filed a [feature request](https://github.com/brimdata/geoip-conn/issues/39) to have autonomous system data added. I found I was able to leverage the `lookup_asn()` BIF to get the `autonomous_system_number` from the MaxMind ASN DB, but it looks like there's not currently a BIF to acquire the `autonomous_system_organization`. Any chance a BIF could be added to include this also?

**Comment by grigorescu** [comment]
Sorry for adding yet another layer to this, but it's unclear to me if the library that Zeek uses for this (libmaxminddb) supports retrieving the organization. I think that they put the ASN in the netmask which very much feels like a hack, and I don't see where they put the ASO.

**Comment by philrz** [comment]
@grigorescu: I'm not a C++ developer so I'm not confident in my ability to prove otherwise. However, my search gave me hope based on the following:

1.  Zeek appears to use `MMDB_get_value()` to obtain the  location info ([link](https://github.com/zeek/zeek/blob/93bed5a261997c245031bc152d7ad93bfe0b56e8/src/zeek.bif#L4264-L4292)) and AS number ([link](https://github.com/zeek/zeek/blob/93bed5a261997c245031bc152d7ad93bfe0b56e8/src/zeek.bif#L4342-L4352))
2.  The [libmaxminddb docs](https://maxmind.github.io/libmaxminddb/) seem to further reinforce that `MMDB_get_value()` is a general way to get values out of their databases and don't speak of restrictions as to what can be achieved
3.  Their ASN database ([link](https://download.maxmind.com/app/geoip_download_by_token?edition_id=GeoLite2-ASN-CSV&date=20220531&suffix=zip&token=v2.local.DdlmF-UzClxS_xVO09ECIDQj4Q3qJWH0J1990yVfaNIAO3nZEvEuvjhC-iFwob6xHqS4froDFj8rbd5M9oCll67pahS3r0lRPDuWDnejksiioUt7GXYVfjXAeZ1SpcFZvOY5Q_D-xNBvbUb7Dwg3oaDznyjZ6ryb_oQgpql7CyYkSQRhUlPYVvn95qSLPCBWJBKnKw)) definitely includes this organization field, e.g.:

```
$ zq -Z 'head 3' GeoLite2-ASN-Blocks-IPv4.csv
{
    network: "1.0.0.0/24",
    autonomous_system_number: 13335.,
    autonomous_system_organization: "CLOUDFLARENET"
}
{
    network: "1.0.4.0/22",
    autonomous_system_number: 38803.,
    autonomous_system_organization: "Wirefreebroadband Pty Ltd"
}
{
    network: "1.0.64.0/18",
    autonomous_system_number: 18144.,
    autonomous_system_organization: "Energia Communications,Inc."
}
```

Even though I'm not a developer, the pattern in the Zeek code seems simple enough that I might try my hand at hacking something together in a dev branch and confirming it's possible.

**Comment by philrz** [comment]
Update: I did get it working. I can put up a PR tomorrow.
