### ISSUE TITLE
Compiling with musl (Alpine)

### ISSUE THREAD

**Issue by hosom** [zeek/zeek#216]
There are a few issues that prevent Bro from being compiled on Alpine (or any system using musl-libc).   It looks like there have been several community efforts to get this working, like the one here: [https://github.com/blacktop/docker-bro/tree/master/2.5/patches](https://github.com/blacktop/docker-bro/tree/master/2.5/patches). 

On Alpine, I had to install some extra packages to get bro to build:

`fts-dev` and `linux-headers`

I don't think that the patches required to compile with musl would be terribly controversial. 

The bigger deal, is that as far as I can tell, is that DNS resolution doesn't work. 

```
virt-brodev01:~# cat foo.bro 
event bro_init()
	{
	when ( local h = lookup_hostname("www.google.com") ) { print h; }
	}

virt-brodev01:~# nslookup www.google.com
Name:      www.google.com
Address 1: 172.217.4.100 ord36s04-in-f4.1e100.net
Address 2: 2607:f8b0:4009:800::2004 ord36s04-in-x04.1e100.net

virt-brodev01:~# /usr/local/bro/bin/bro -i eth0 foo.bro 
warning in /usr/local/bro/share/bro/base/init-bare.bro, line 1: problem initializing NB-DNS: no valid nameservers in resolver config
listening on eth0

warning: can't issue DNS request
warning: can't issue DNS request
{
0.0.0.0
}
^C1542721228.497591 received termination signal
```

**Comment by jsiwek** [comment]
It may help if you can give contents of `/etc/resolv.conf`.  IIRC, Bro doesn't support nameservers via IPv6 addresses, so if `/etc/resolv.conf` only contains IPv6 (or not any IPv4 at all), then that could explain your situation.

**Comment by hosom** [comment]
Sure thing, I probably should have included that originally...

```
cat /etc/resolv.conf 
search localdomain
nameserver 10.211.55.1
```

**Comment by sethhall** [comment]
The problem is that Bro is currently using the `res_init()` function which isn't supported by musl.  We could yank the code from musl to parse /etc/resolv.conf.  I think we'd get the benefit that we'd be able to pretty easily add support for IPv6 resolvers too.

Alternately we could make it a user focused feature to have them manually specify their desired resolver too (in addition to making it automatically work by reading /etc/resolv.conf).

**Comment by hosom** [comment]
I think that both are great. Thanks for finding the actual problem. I got as far as "there are differences in how musl and glibc handle parsing of /etc/resolv.conf" and called it quits.

I actually went to look for a feature to specify the resolver manually when I first ran into this issue and was surprised that one didn't exist anywhere.

**Comment by jsiwek** [comment]
I didn't change any `/etc/resolv.conf` parsing (agree that should eventually be improved), but I added a `dns_resolver` option that one can configure in branch `topic/jsiwek/dns-resolver-option`: b3bff5ea870ce3b2b4ebbaa3f2d6e896da795c89

This probably won't be included soon (or at least not in the master branch until final 2.6 is released), so you may have to patch it in yourself to try it out, but let us know how it works if you do try it.

**Comment by hosom** [comment]
I pulled in that commit and tested it. Manually configuring `dns_resolver` resolves resolution issues.

**Comment by jsiwek** [comment]
A heads up: I just removed the `dns_resolver` option (added as part of resolving this issue), but the `ZEEK_DNS_RESOLVER` env. var. will serve the same purpose.  Reason/details at https://github.com/zeek/zeek/commit/f7c1cde7c7fe05eda68bfc24e7f0873c53d84315
