### ISSUE TITLE
Problems running bro with suricata on pf_ring zbalance

### ISSUE THREAD

**Issue by radoslawc** [zeek/zeek#217]
Hi!

I'm having problems with bro and suricata on the same pf_ring's zbalance cluster.
Originally this was reported as suricata issue, but after some investigation turns out it's caused by bro. Here's the pf_ring developer's answer:
```
"I see that packet len in the PF_RING packet header is 102 (caplen and len), 
while the IPLEN computed from packet headers is 1420, this should definitely not happen, 
especially with ZC as there is no snaplen, it always captures full packets.

Since reporter is using zero-copy distribution (with zbalance_ipc), 
I would not exclude that some other application is corrupting the packet. 
I would ask the reporter to provide the zbalance_ipc configuration, 
and stop all other applications if any and try to reproduce the crash again."
```
Whole thread on suricata's redmine:
https://redmine.openinfosecfoundation.org/issues/2618

I've excluded other applications, this issue was only happening with bro and suricata running at the same time.

bro version 2.5.5 (and 2.5.4 had the same issue)
compilation flags:
./configure --prefix=%{_prefix} --binary-package --disable-broker
pf_ring connectivity via pf_ring plugin from aux/plugins/pf_ring
OS: Centos 1804
PF_RING 7.2.0
node.cfg
```
[manager]
type=manager
host=172.30.9.55

[proxy-1]
type=proxy
host=172.30.9.55

[proxy-2]
type=proxy
host=172.30.9.55

[worker-0]
type=worker
host=172.30.9.55
interface=pf_ring::zc:27@0
pin_cpus=2

and so on for 20 workers in total
```
no external bro scripts

Issue happens rarely, 2 - 3 times a week or sometimes not for two weeks or so.

Any help how to tackle this issue is greatly appreciated.

**Comment by sethhall** [comment]
If you don't run Bro on the same zbalance_ipc cluster do you still see the Suricata crash?

Also, I see that you are running the PF_Ring plugin for Zeek and I would expect if there was any corruption of the length field provided by PF_Ring that it's occurring in that plugin (I haven't looked at that plugin to see if that's possible either but it was written by a PF_Ring developer).

**Comment by sethhall** [comment]
One other note, you can configure your workers this way....

```
[worker]
type=worker
host=172.30.9.55
interface=pf_ring::zc:27
lb_method=custom
lb_procs=20
```

That *should* work.

**Comment by sethhall** [comment]
Since there has been no follow up on this in a few months and we don't have enough information to debug it, I'm going to close the ticket.  If you have more information to provide, please reopen the ticket.
