### ISSUE TITLE
Modbus logs not corresponding to wireshark export

### ISSUE THREAD

**Issue by AaronDeRybelHowest** [zeek/zeek#2188]
When I create a standard modbus log from a pcapng file i receive **12361** lines.
When I create an export and filter on modbus/tcp recognised in wireshark **12790** lines.

There seems to have been some packets lost in converting the network capture to this log. 
The way wireshark recognizes is to check for protocol=TCP and port=502 (also see: https://ask.wireshark.org/question/16386/decoding-modbus-tcp-on-different-port-number/)
But how does zeek recognizes modbus packets? This could explain the difference in lines.

**Comment by AaronDeRybelHowest** [comment]
Hello @0xxon , 
Did you have time to look into this? 
I also made a comparison based on the timestamps of zeek logs and wireshark export of modbus protocol. I can share this with you

**Comment by 0xxon** [comment]
Hi,
sorry - no, I did not have time to look into this - and might not have time to look into this myself. So it would be great if you could share your data publicly so that others can take a look at it too.

The comparison would be interesting, especially the differences.

**Comment by AaronDeRybelHowest** [comment]
I've made the github public: https://github.com/AaronDeRybelHowest/pcap-share
I also included a couple of files in different formats

Anyone that can look into this different processing of modbus packets?

**Comment by micrictor** [comment]
The disparity is because the default script only logs if `is_orig` is False. 

https://github.com/zeek/zeek/blob/1d2c12e9801018575f462a496b7da87e2cbd21e1/scripts/base/protocols/modbus/main.zeek#L58

Removing that condition from the script results in the expected number of entries in the log.

I think that this is because your PCAP is mid-stream - there's no TCP handshake indicating the start of the TCP session.

**Comment by 0xxon** [comment]
Oh, that is great - thank you very much for examining this.

**Comment by micrictor** [comment]
I need to look into it more - the is_orig check seems like it might have
unintended consequences even if the session initiation is observed.

**Comment by AaronDeRybelHowest** [comment]
Hi @micrictor ,
Thank you so much for looking into this, If I can help in any way in this analysis please let me know.
