### ISSUE TITLE
|x| operator is limited & buggy

### ISSUE THREAD

**Issue by vpax** [zeek/zeek#219]
Right now, `|x|` is hardwired to have a type of `count`, but this isn't actually correctly enforced.  For example, if I print `|5-9|` I get `18446744073709551612`, and `|5 sec - 9 sec|` has an actual type of `double` (which is the internal type of `interval`).

We should either (1) extend `|x|` to be absolute value, with consistent typing [preferred], or (2) add type-checking so it can't be misused.

**Comment by mavam** [comment]
Would that imply that operator `|x|` is polymorphic? It

1. returns the number of elements if `x` is a container
2. returns the absolute value for arithmetic data types

It makes sense notationally, but it requires that the user now needs to factor in type information. I would imagine that the context makes it obvious most of the time.

**Comment by vpax** [comment]
@mavam yes, polymorphic.  Same as other operators, such as the recent ones introduced for sets and vectors, so I don't see this as any significant conceptual change.  (In fact, it's also the case for the '/' operator, which means different things in the expression "8 / 2" vs. "128.27.26.25/21".)

**Comment by ckreibich** [comment]
2005 strikes back! :+1: CHANGES sez:
```
- New operator |x|, a sizeof operator (Christian Kreibich).  It yields
  absolute values for numerical values, file size for files, the number
  of enums for an enum type, the number of addresses in subnets, number
  of fields in records, numeric equivalent for addresses, the number of
  elements in vectors/sets/tables, and the length of strings.
```
I do not remember how we drew the line at that feature set. Perhaps hours left until Jupiter :beer:?

I remember that back then I was very excited that |x| on a container would report its number of elements. Today I find this less convincing — for example, both Python and Go use `len()` vs `abs()`. But if people accept the polymorphism (I guess it's always been there, per the above), then I'm all for completing it.

I was relieved to see that we have btests for the operator, but none of the tests apply statements, and some of the differences are subtle (there's a test for |-10|, but not for something like |5-9|). Clearly a total minefield and I'm glad you caught it.

**Comment by sl33k** [comment]
This now breaks any way to convert `interval`s to `double` in scripts if i'm correct.
The documentation [here](https://docs.zeek.org/en/stable/script-reference/types.html) states that the only way to convert a `interval` to a double is to take its absolute value, which will now return an `interval`.
This makes any usage of interval's with for example the `SumStats` framework impossible as this uses double's internally.

**Comment by jsiwek** [comment]
Technically, there's still the `interval_to_double()` function that can convert, but I think I didn't originally realize the |x| operator was documented/used anywhere for doing the conversion to double and just changed it since that's what the original suggestion was.  But I'm going to revert that shortly to avoid introducing a breaking change, thanks for pointing it out.
