### ISSUE TITLE
Zeek Packet capture frequency

### ISSUE THREAD

**Issue by CindyStudyEveryday** [zeek/zeek#2196]
How often does Zeek capture packets? Every 10 seconds? Every 20 seconds? Is this set in some configuration file?  I couldn't find it,, thank you.

**Comment by 0xxon** [comment]
Hi,

We don't use GitHub issues for support questions. Questions like this are best answered using on either slack or our forum, which is both are frequented by Zeek developers and professional users. You can join here:

Forum: https://community.zeek.org/

Slack: https://zeek.org/community/

 Johanna
