### ISSUE TITLE
Bad load balancing with PF_RING

### ISSUE THREAD

**Issue by vbr-cts** [zeek/zeek#2209]
Hi.
I've got a sensor handling ~5gbps from an interface. I'm using PF_RING, pinned cpus, etc. I've been experimenting with 8, 12 or 14 workers. I'm also adjusting the number of RSS queues to the number of workers.

For some reason, some workers (~ 30%) are capping at 100% CPU usage, while others are chilling at 40-50%.

I'm at a loss trying to figure out why load balancing seems so uneven, or what I could do about it. Any ideas on how to debug the issue further ?

**Comment by 0xxon** [comment]
Hi,

We don't use GitHub issues for support questions. Questions like this are best answered using on either slack or our forum, which is both are frequented by Zeek developers and professional users. You can join here:

Forum: https://community.zeek.org/

Slack: https://zeek.org/community/

 Johanna
