### ISSUE TITLE
An error occurred while making  ——   bro2.6

### ISSUE THREAD

**Issue by DaemonShao** [zeek/zeek#223]
/root/bro-2.6/aux/broker/3rdparty/caf/libcaf_core/caf/intrusive/drr_queue.hpp:45:33: error: ‘policy_type’ is not a class, namespace, or enumeration
   using deficit_type = typename policy_type::deficit_type;
                                 ^
/root/bro-2.6/aux/broker/3rdparty/caf/libcaf_core/caf/intrusive/drr_queue.hpp:64:3: error: ‘deficit_type’ does not name a type
   deficit_type deficit() const {
   ^
/root/bro-2.6/aux/broker/3rdparty/caf/libcaf_core/caf/intrusive/drr_queue.hpp:77:20: error: ‘deficit_type’ has not been declared
   void inc_deficit(deficit_type x) noexcept {
                    ^
/root/bro-2.6/aux/broker/3rdparty/caf/libcaf_core/caf/intrusive/drr_queue.hpp:105:30: error: ‘deficit_type’ has not been declared
   new_round_result new_round(deficit_type quantum, F& consumer) {
                              ^
/root/bro-2.6/aux/broker/3rdparty/caf/libcaf_core/caf/intrusive/drr_queue.hpp:131:3: error: ‘deficit_type’ does not name a type
   deficit_type deficit_ = 0;
   ^
/root/bro-2.6/aux/broker/3rdparty/caf/libcaf_core/caf/intrusive/drr_queue.hpp: In constructor ‘caf::intrusive::drr_queue<Policy>::drr_queue(typename caf::intrusive::drr_queue<Policy>::super::policy_type)’:
/root/bro-2.6/aux/broker/3rdparty/caf/libcaf_core/caf/intrusive/drr_queue.hpp:49:51: error: class ‘caf::intrusive::drr_queue<Policy>’ does not have any field named ‘deficit_’
   drr_queue(policy_type p) : super(std::move(p)), deficit_(0) {
                                                   ^
/root/bro-2.6/aux/broker/3rdparty/caf/libcaf_core/caf/intrusive/drr_queue.hpp: In constructor ‘caf::intrusive::drr_queue<Policy>::drr_queue(caf::intrusive::drr_queue<Policy>&&)’:
/root/bro-2.6/aux/broker/3rdparty/caf/libcaf_core/caf/intrusive/drr_queue.hpp:53:59: error: class ‘caf::intrusive::drr_queue<Policy>’ does not have any field named ‘deficit_’
   drr_queue(drr_queue&& other) : super(std::move(other)), deficit_(0) {
                                                           ^
/root/bro-2.6/aux/broker/3rdparty/caf/libcaf_core/caf/intrusive/drr_queue.hpp: In member function ‘void caf::intrusive::drr_queue<Policy>::inc_deficit(int)’:
/root/bro-2.6/aux/broker/3rdparty/caf/libcaf_core/caf/intrusive/drr_queue.hpp:79:7: error: ‘deficit_’ was not declared in this scope
       deficit_ += x;
       ^
/root/bro-2.6/aux/broker/3rdparty/caf/libcaf_core/caf/intrusive/drr_queue.hpp: In member function ‘typename caf::intrusive::drr_queue<Policy>::super::unique_pointer caf::intrusive::drr_queue<Policy>::next()’:
/root/bro-2.6/aux/broker/3rdparty/caf/libcaf_core/caf/intrusive/drr_queue.hpp:99:24: error: ‘deficit_’ was not declared in this scope
     return super::next(deficit_);
                        ^
/root/bro-2.6/aux/broker/3rdparty/caf/libcaf_core/caf/intrusive/drr_queue.hpp: In member function ‘caf::intrusive::new_round_result caf::intrusive::drr_queue<Policy>::new_round(int, F&)’:
/root/bro-2.6/aux/broker/3rdparty/caf/libcaf_core/caf/intrusive/drr_queue.hpp:107:7: error: ‘deficit_’ was not declared in this scope
       deficit_ += quantum;

-----
How should this error be resolved

**Comment by jsiwek** [comment]
That's using GCC 4.8.2 and the embedded CAF dependency requires at least GCC 4.8.3.

The easiest way I found to get sufficient compiler on CentOS 6 was via [Software Collections](https://www.softwarecollections.org/en/scls/rhscl/devtoolset-6/).  E.g.:

```
sudo yum install centos-release-scl
sudo yum install devtoolset-6
scl enable devtoolset-6 bash
# Now try compiling Bro/Zeek like you were (but also may need to disable python bindings):
./configure --with-pcap=/opt/pfring/ --prefix=/usr/local/bro --disable-python
```

Generally, CentOS 6 is on the way out and "The CentOS team recommends that you start moving workloads from CentOS Linux 6 to CentOS Linux 7" I gather due to it being in the last phase of maintenance for which [Red Hat Policy](https://access.redhat.com/support/policy/updates/errata/) only indicates critical/urgent security updates being provided and lower priority ones possibly not.  So it's also not a high priority for us (or CAF developers) to improve support for this OS or older compilers.
