### ISSUE TITLE
Can't exit zeek with ctrl+c when reading scripts from stdin

### ISSUE THREAD

**Issue by awelzel** [zeek/zeek#2239]
On Debian 11, with Zeek 5.0.0, running as follows doesn't exit Zeek via `ctrl+c`:
```
$ zeek
^C
^C^C^C^C^C^C^C^C^C
^C
^\
Quit (core dumped)
```

This worked fine with 4.2.1:
```
$ zeek --version
zeek version 4.2.2
$ zeek
^C
$
```

@bbannier  says it doesn't happen for him on osx, but does happen via docker, too.
```
$ docker run --rm -it zeekurity/zeek:5.0.0 
root@9c30f7ce9dbe:/# zeek
^C^C^C^C

^C^C^C^C^C^C^C
^\Quit (core dumped)
```

The good part, `ctrl+c` does work when actually listening on an interface.
```
root@9c30f7ce9dbe:/# zeek -i lo
listening on lo

^Creceived termination signal
0 packets received on interface lo, 0 (0.00%) dropped, 0 (0.00%) not processed
```

**Comment by awelzel** [comment]
Hmm, this might be related to something else I observed: Not being able to `ctrl+c` out a run of doctests with `zeek --test`.

Suspicious is the following commit: 9a11df808bd67b8bbe4bac91be9adbfbd7be62c7. It looks like doctests are indeed running with signal handlers masked (and reading of stdin also if I grasp the zeek-setup code right).

**Comment by 0xxon** [comment]
Oh, fun. I think this is the first one that should be in a 5.0.1 release.

**Comment by timwoj** [comment]
> Just to clarify, I see this issue on osx in a release build (without --enable-debug and with default build-type). If I change this to a debug build with --enable-debug and --build-type=Debug CTRLc works like expected.

As a counter-point, I'm on a debug build on macOS and it's definitely happening here. 

> Suspicious is the following commit: https://github.com/zeek/zeek/commit/9a11df808bd67b8bbe4bac91be9adbfbd7be62c7.

It's strange that this would crop up now though. That commit's been in master since April, you'd think someone would have noticed by now. I wonder if it was possibly c5b435f2cc88f3c1a2a7e0a4b22699916e87706c, but part of my testing for that was starting zeek and hitting ctrl-c about 100 times and it was working fine there.

**Comment by timwoj** [comment]
@awelzel hit it on the first try. I bisected back to the start of 5.0.0-dev, and it returned:

```
tim@coregeek2 zeek-master% git bisect good                                                        [8a99e343a]
d29160e9dea2bd305e3e5a3b30811495c8387e73 is the first bad commit
commit d29160e9dea2bd305e3e5a3b30811495c8387e73
Merge: 8a99e343a 9a11df808
Author: Christian Kreibich <christian@corelight.com>
Date:   Mon Apr 11 12:46:51 2022 -0700

    Merge branch 'topic/christian/fix-tsan-supervisor'
    
    * topic/christian/fix-tsan-supervisor:
      Mask our signal handlers' triggering signals around thread creation

 CHANGES           |  4 ++++
 VERSION           |  2 +-
 src/zeek-setup.cc | 23 +++++++++++++++++++++++
 3 files changed, 28 insertions(+), 1 deletion(-)
```

**Comment by ckreibich** [comment]
I can confirm over here too (Fedora).

**Comment by ckreibich** [comment]
I hope you're happy, tsan!

:-)
