### ISSUE TITLE
Unable to stop other protocols, how do I do it?

### ISSUE THREAD

**Issue by Blason** [zeek/zeek#2249]
Hi Team,

Can someone please guide me on stopping certain protocols that I do not want to run with zeek. I want only http/https/dns. I already ttried disabling protocol under local.zeek or under framework. However it did not work.

Can someone please help me?

TIA
Blason R

**Comment by 0xxon** [comment]
Hi,

We don't use GitHub issues for support questions. Questions like this are best answered using on either slack or our forum, which is both are frequented by Zeek developers and professional users. You can join here:

Forum: https://community.zeek.org/

Slack: https://zeek.org/community/

 Johanna
