### ISSUE TITLE
Broctl log rotation with multiple logger nodes

### ISSUE THREAD

**Issue by stefanmaerz** [zeek/zeek#225]
Hi,

I am running a Bro Cluster using Bro v2.5.5. This cluster has two loggers. It is using Broker.

In my broctl.cfg file, I have specified  LogExpireInterval to 60 days.

Today I noticed that the second logger's data partition is filling up.
Logger 2 has about  a year of logs (dating back to when I moved the cluster to prod) and 169 GB of data.
Logger 1 has about 60 days of data and 27 GB of data. This logger demonstrates the behavior I would expect. 

So it would seem that broctl cron is not rotating logs from the second logger node.

This seems to me like a bug in broctl cron not correctly understanding distributed logging. I'm willing to submit a pull request, however before i do I would like to get feedback from the Bro/Zeek team to make sure that this is not desirable behavior.

Best Regards,
-Stefan

**Comment by jsiwek** [comment]
Sounds like a bug to me.  PRs appreciated.

**Comment by jsiwek** [comment]
Addressed via https://github.com/zeek/broctl/pull/12
