### ISSUE TITLE
Unit tests take a long time

### ISSUE THREAD

**Issue by ckreibich** [zeek/zeek#2258]
Zeek's unit tests used to complete nearly instantaneously. On my system they now take almost a minute, apparently due to waiting for DNS timeouts:

```
$ time zeek --test
[doctest] doctest version is "2.4.8"
[doctest] run with "--help" for options
warning in /home/christian/inst/opt/zeek/share/zeek/base/init-bare.zeek, line 1: can't resolve IP address: 240.0.0.0
warning in /home/christian/inst/opt/zeek/share/zeek/base/init-bare.zeek, line 1: can't resolve IP address: 1.1.1.1
warning in /home/christian/inst/opt/zeek/share/zeek/base/init-bare.zeek, line 1: Can't resolve host: one.one.one.one
error in /home/christian/inst/opt/zeek/share/zeek/base/init-bare.zeek, line 1: string without NUL terminator: "abcdef"
error in /home/christian/inst/opt/zeek/share/zeek/base/init-bare.zeek, line 1: string with embedded NUL: "ab\x00def"
===============================================================================
[doctest] test cases:  78 |  78 passed | 0 failed | 0 skipped
[doctest] assertions: 567 | 567 passed | 0 failed |
[doctest] Status: SUCCESS!

real    0m54.308s
user    0m0.030s
sys     0m0.033s
```
It'd be nice to get this to run quickly again, if possible.

**Comment by timwoj** [comment]
We could set the timeout on the DNS tests lower but it's currently only 5 seconds and anything lower wouldn't really change it much. Most of the tests make actual DNS requests so any of them could take up to that 5 seconds to run. 

One option is to set the [skip decorator](https://github.com/doctest/doctest/blob/master/doc/markdown/testcases.md#decorators) on all of those tests, but then fix the CI to pass `--no-skip` when it runs the tests. The tests would still exist and be run during automated builds, but wouldn't slow down people trying to run the tests locally.

**Comment by ckreibich** [comment]
Thanks Tim. I discovered that the tests have their own timing feature — here's the relevant section:

```
$ zeek --test -d
...
warning in /home/christian/inst/opt/zeek/share/zeek/base/init-bare.zeek, line 1: can't resolve IP address: 1.1.1.1
warning in /home/christian/inst/opt/zeek/share/zeek/base/init-bare.zeek, line 1: Can't resolve host: one.one.one.one
===============================================================================
/home/christian/devel/zeek/zeek/src/DNS_Mgr.cc:1801:
TEST CASE:  dns_mgr timeouts

35.020552 s: dns_mgr timeouts
===============================================================================
/home/christian/devel/zeek/zeek/src/DNS_Mgr.cc:1827:
TEST CASE:  dns_mgr async timeouts

16.009100 s: dns_mgr async timeouts
===============================================================================
```
I see what you mean with the 5 secs — `zeek --test --test-case='dns_mgr timeouts'` while tcpdumping DNS shows 5 second timeouts, but with repeated attempts.

I thought the runtime might be a surprise, but it sounds like it's expected. It'd be nice to mock out the whole DNS interaction, but I don't know c-ares at all. Please feel free to handle this one as you see fit.
