### ISSUE TITLE
Inconsistent prototypes for `analyzer_[confirmation|violation]`

### ISSUE THREAD

**Issue by bbannier** [zeek/zeek#2261]
During the discussion for zeek/spicy-ldap#10 @rsmmr noticed that the [argument types for `analyzer_confirmation` was inconsistent](https://github.com/zeek/spicy-ldap/pull/10#discussion_r909209959),

> That said, I'm now wondering if we have a problem in Zeek (or whether I'm just confused at this point): Here are the prototypes in current master:
> ```
> # git grep '^event.*_confirmation' src/event.bif
> src/event.bif:event analyzer_confirmation%(c: connection, atype: Analyzer::Tag, aid: count%);
> src/event.bif:event protocol_confirmation%(c: connection, atype: AllAnalyzers::Tag, aid: count%) &deprecated="Remove in v5.1. > Use analyzer_confirmation.";
> ```
>
> At the same time, we're using the new event like this in master:
> ```
> # git grep '^event.*_confirmation' scripts/
> scripts/base/frameworks/dpd/main.zeek:event analyzer_confirmation(c: connection, atype: AllAnalyzers::Tag, aid: count) &priority=10
> scripts/base/protocols/conn/inactivity.zeek:event analyzer_confirmation(c: connection, atype: AllAnalyzers::Tag, aid: count)
> ...
> ```
> 
> In 4.1 we have:
> ```
> # git grep '^event.*_confirmation' scripts/
> scripts/base/frameworks/dpd/main.zeek:event protocol_confirmation(c: connection, atype: Analyzer::Tag, aid: count) &priority=10
> scripts/base/protocols/conn/inactivity.zeek:event protocol_confirmation(c: connection, atype: Analyzer::Tag, aid: count)
> ...
> ```

@timwoj than mentioned

> analyzer_* should be using AllAnalyzers everywhere. If there are spots where it isn't, then I probably screwed something up in that migration 😅

`analyzer_violation` seems to have the same issue, but I haven't ruled out that there are more places which handle this inconsistently.

**Comment by timwoj** [comment]
It looks like the type in event.bif is wrong. All of the uses of it in the scripts are `AllAnalyzers::Tag` which should be correct.
