### ISSUE TITLE
SMB: FILE_DELETE not always shown in logs

### ISSUE THREAD

**Issue by jlucovsky** [zeek/zeek#2276]
SMB is not always logging FILE_DELETE in the `smb_files.log`.

This pcap helps demonstrate the problem -- there should be a `FILE_DELETE` for `opcreatep\roattr\rttaor.dat` but it's missing. Other `FILE_DELETE` mentions are logged:
    https://wiki.wireshark.org/uploads/__moin_import__/attachments/SMB2/ifstest.cap.gz

See packets 309 and 310 from the pcap

**Comment by jlucovsky** [comment]
@JustinAzoff provided this analysis:

Looking through how the analyzers and scripts are written I found at least two problems.

The smb1 analyzer does not implement deletions at all. This can be seen in src/analyzer/protocol/smb/smb1-protocol.pac:

```
#       #SMB_COM_DELETE                   -> delete                 : SMB_delete_request(header);
#       #SMB_COM_RENAME                   -> rename                 : SMB_rename_request(header);
```
Now, no one should be using SMB1 anymore, so practically speaking that's not likely an issue moving forward.

The other problem is that looking at some of the SMB traffic on the customer sensor there are at least two ways a file can be removed. We handle the first but not the second.

## Method one
A set info request via SMB2_FILE_DISPOSITION_INFO. Apparently the only thing this is used for is to set the "delete on close" flag. We don't actually check the flag, but just assume, but it seems to work ok. from https://wiki.wireshark.org/SMB2/SMB2_FILE_DISPOSITION_INFO

When Vista deletes a file, it will open the file with SMB2/Create, then use SMB2/SetFile and disposition to 1 and finally SMB2/Close to close the file. Since disposition is set to delete on close the file or directory will be deleted.

## Method two
The other way I see that files are deleted is that they are opened (Create Request) with a Create Options including the "Delete On Close" flag. Zeek currently does not handle this.

I worked out that we do have the options as part of the smb2_create_request record, but don't currently pull out the individual bits. This script is able to identify the files that will be deleted on close:
```
event smb2_create_request(c: connection, hdr: SMB2::Header, request: SMB2::CreateRequest)
{
    if ( (request$create_options & 0x00001000) == 0 )
        return;

    if (! (c?$smb_state && c$smb_state?$current_file))
        return;

    print c$id, c$smb_state$current_file$name;
}
```
So as I understand it a file can be opened with the "delete on close" bit set, then either closed immediately, or closed at a later date. At that point the file will be implicitly deleted. Zeek would need to track this flag in the file record and ensure that when the file is closed (or possibly expires, since I think that's still an open bug) that we log the DELETE entry.

**Comment by awelzel** [comment]
> Zeek would need to track this flag in the file record and ensure that when the file is closed (or possibly expires, since I think that's still an open bug) that we log the DELETE entry.

Outside of expiration, is the following reasonable? I have to admit the smb scripts look very complex, so that may be too short-sighted.

```
--- a/scripts/base/protocols/smb/main.zeek
+++ b/scripts/base/protocols/smb/main.zeek
@@ -69,6 +69,9 @@ export {
                prev_name               : string  &log &optional;
                ## Last time this file was modified.
                times                   : SMB::MACTimes &log &optional;
+               ## Whether delete_on_close was set during the CREATE request
+               ## for this file.
+               delete_on_close         : bool &default=F;
        };
 
        ## This record is for the smb_mapping.log
diff --git a/scripts/base/protocols/smb/smb2-main.zeek b/scripts/base/protocols/smb/smb2-main.zeek
index c45a56a79..a6c40f2ef 100644
--- a/scripts/base/protocols/smb/smb2-main.zeek
+++ b/scripts/base/protocols/smb/smb2-main.zeek
@@ -127,6 +127,7 @@ event smb2_create_request(c: connection, hdr: SMB2::Header, request: SMB2::Creat
                request$filename = "<share_root>";
 
        c$smb_state$current_file$name = request$filename;
+       c$smb_state$current_file$delete_on_close = (request$create_options & 0x00001000) != 0;
 
        switch ( c$smb_state$current_tree$share_type )
                {
@@ -327,6 +328,14 @@ event smb2_close_request(c: connection, hdr: SMB2::Header, file_id: SMB2::GUID)
                delete c$smb_state$fid_map[file_id$persistent+file_id$volatile];
 
                SMB::write_file_log(c$smb_state);
+
+               # If this file was opened with delete_on_close set, produce
+               # a DELETE entry in the smb_files.log, too.
+               if ( c$smb_state$current_file$delete_on_close )
+                       {
+                       c$smb_state$current_file$action = SMB::FILE_DELETE;
+                       SMB::write_file_log(c$smb_state);
+                       }
                }
        else
                {
```

For the pcap in question, it adds the following DELETE entries in smb_files.log:
```
$ diff -u1  <(zeek-cut id.orig_h id.resp_h action path name  < smb_files.log)  <(zeek-cut id.orig_h id.resp_h action path name  < smb_files.log.new)
--- /dev/fd/63  2022-07-15 12:29:59.279839758 +0200
+++ /dev/fd/62  2022-07-15 12:29:59.279839758 +0200
@@ -45,2 +45,3 @@
 192.168.114.20 192.168.114.129 SMB::FILE_OPEN  \\\\192.168.114.129\\test       opcreatp\\archattr
+192.168.114.20 192.168.114.129 SMB::FILE_DELETE        \\\\192.168.114.129\\test       opcreatp\\archattr
 192.168.114.20 192.168.114.129 SMB::FILE_OPEN  \\\\192.168.114.129\\test       opcreatp\\colaelif.dat
@@ -51,4 +52,6 @@
 192.168.114.20 192.168.114.129 SMB::FILE_OPEN  \\\\192.168.114.129\\test       opcreatp\\crfiled
+192.168.114.20 192.168.114.129 SMB::FILE_DELETE        \\\\192.168.114.129\\test       opcreatp\\crfiled
 192.168.114.20 192.168.114.129 SMB::FILE_OPEN  \\\\192.168.114.129\\test       opcreatp\\dirattr\\dirattr
 192.168.114.20 192.168.114.129 SMB::FILE_OPEN  \\\\192.168.114.129\\test       opcreatp\\dirattr\\dirattr
+192.168.114.20 192.168.114.129 SMB::FILE_DELETE        \\\\192.168.114.129\\test       opcreatp\\dirattr\\dirattr
 192.168.114.20 192.168.114.129 SMB::FILE_OPEN  \\\\192.168.114.129\\test       opcreatp\\dirattr\\dirattr.dat
@@ -57,2 +60,3 @@
 192.168.114.20 192.168.114.129 SMB::FILE_OPEN  \\\\192.168.114.129\\test       opcreatp\\dirattr
+192.168.114.20 192.168.114.129 SMB::FILE_DELETE        \\\\192.168.114.129\\test       opcreatp\\dirattr
 192.168.114.20 192.168.114.129 SMB::FILE_OPEN  \\\\192.168.114.129\\test       opcreatp\\eliflavo.dat
@@ -67,2 +71,3 @@
 192.168.114.20 192.168.114.129 SMB::FILE_OPEN  \\\\192.168.114.129\\test       opcreatp\\hidattr
+192.168.114.20 192.168.114.129 SMB::FILE_DELETE        \\\\192.168.114.129\\test       opcreatp\\hidattr
 192.168.114.20 192.168.114.129 SMB::FILE_OPEN  \\\\192.168.114.129\\test       opcreatp\\normattr
@@ -72,4 +77,6 @@
 192.168.114.20 192.168.114.129 SMB::FILE_OPEN  \\\\192.168.114.129\\test       opcreatp\\normattr
+192.168.114.20 192.168.114.129 SMB::FILE_DELETE        \\\\192.168.114.129\\test       opcreatp\\normattr
 192.168.114.20 192.168.114.129 SMB::FILE_OPEN  \\\\192.168.114.129\\test       opcreatp\\opalfidr
 192.168.114.20 192.168.114.129 SMB::FILE_OPEN  \\\\192.168.114.129\\test       opcreatp\\opalfidr
+192.168.114.20 192.168.114.129 SMB::FILE_DELETE        \\\\192.168.114.129\\test       opcreatp\\opalfidr
 192.168.114.20 192.168.114.129 SMB::FILE_OPEN  \\\\192.168.114.129\\test       opcreatp\\opalfile.dat
@@ -80,2 +87,3 @@
 192.168.114.20 192.168.114.129 SMB::FILE_OPEN  \\\\192.168.114.129\\test       opcreatp\\opfiled
+192.168.114.20 192.168.114.129 SMB::FILE_DELETE        \\\\192.168.114.129\\test       opcreatp\\opfiled
 192.168.114.20 192.168.114.129 SMB::FILE_OPEN  \\\\192.168.114.129\\test       opcreatp\\ovalatro.dat
@@ -101,2 +109,3 @@
 192.168.114.20 192.168.114.129 SMB::FILE_OPEN  \\\\192.168.114.129\\test       opcreatp\\roattr
+192.168.114.20 192.168.114.129 SMB::FILE_DELETE        \\\\192.168.114.129\\test       opcreatp\\roattr
 192.168.114.20 192.168.114.129 SMB::FILE_OPEN  \\\\192.168.114.129\\test       opcreatp\\supraloc.dat
@@ -118,4 +127,6 @@
 192.168.114.20 192.168.114.129 SMB::FILE_OPEN  \\\\192.168.114.129\\test       opcreatp\\sysattr
+192.168.114.20 192.168.114.129 SMB::FILE_DELETE        \\\\192.168.114.129\\test       opcreatp\\sysattr
 192.168.114.20 192.168.114.129 SMB::FILE_OPEN  \\\\192.168.114.129\\test       opcreatp
 192.168.114.20 192.168.114.129 SMB::FILE_OPEN  \\\\192.168.114.129\\test       opcreatp
+192.168.114.20 192.168.114.129 SMB::FILE_DELETE        \\\\192.168.114.129\\test       opcreatp
 192.168.114.20 192.168.114.129 SMB::FILE_OPEN  \\\\192.168.114.129\\test       <share_root>

```

**Comment by awelzel** [comment]
> Yeah, that looks about right. A better test pcap would definitely help build some test cases.

The samba project has `smbtorture` and one of the test suites is [smb2.delete-on-close-perms](https://github.com/samba-team/samba/blob/master/source4/torture/smb2/delete-on-close.c).

Attached a capture running this test locally and another one picking out just a single connection from that. For the latter, I see at least two deletes happening for `test_dir\\test_create.dat`, but smb_files.log doesn't contain those with current `master`.

[smb2.delete-on-close-perms.pcap.gz](https://github.com/zeek/zeek/files/9123754/smb2.delete-on-close-perms.pcap.gz)
[smb2.delete-on-close-perms-delete-existing.pcap.gz](https://github.com/zeek/zeek/files/9123755/smb2.delete-on-close-perms-delete-existing.pcap.gz)

**Comment by awelzel** [comment]
Attaching one more file here from an smbclient (Version 4.13.13-Debian) invocation uploading a `README` file. It's using the same delete-on-close flag in CREATE to delete the file again.
 
[smbclient.put-rm-file.pcap.gz](https://github.com/zeek/zeek/files/9130366/smbclient.put-rm-file.pcap.gz)
