### ISSUE TITLE
Add `assert` statement for script-level testing

### ISSUE THREAD

**Issue by timwoj** [zeek/zeek#2285]
### Discussed in https://github.com/zeek/zeek/discussions/1792

<div type='discussions-op-text'>

<sup>Originally posted by **rsmmr** September 22, 2021</sup>
The discussion in #1475 on integrating ZTest led to some of us wondering if we really understand already how unit testing for Zeek scripts should look like. We can certainly continue that discussion, but there's a piece in there where I'm wondering if that be a good initial step to tackle independently first: adding an `assert` statement to Zeek's scripting language. Here's a straw man proposal on how that could look like:

1. Add a statement `assert <expr> [: <failure message>]`. `<expr>` is a boolean expression that is expected to be true. `<failure message>` is an optional string to report as an error message in case the boolean ends up being false.

2. By default, a failing `assert` produces an error through the reporter, including the failure message if given. It then aborts the current event handler by raising an `InterpreterException` (i.e., Zeek will continue its processing).

3. To change that default behavior, we provide a script-level hook `assert_failure` that runs whenever an assert fails, receiving (1) a string rendering of the failing expression, (2) the failure message, (3) location information where it happened. The hook would return a boolean to indicate whether it wants the script processing to continue normally despite the failing assert or abort through the `InterpreterExcption`. If it wanted, the hook could also just abort Zeek altogether at that point.
 
I believe that this would be helpful on its own for both (1) writing tests (which instead of printing/diffing could now write `assert ...`), and (2) normal scripts to enforce constraints they rely on. And if we later added a larger testing framework, it could continue to rely on `assert` and implement the hook for any custom processing (e.g., logging & counting failures).

What do people think?</div>

**Comment by stevesmoot** [comment]
I like it, but that doesn’t count for much.  Did wonder if you have thought
of how the location information part will work, seems like we should make
sure that is approachable for the non test usage.

S

**Comment by ynadji** [comment]
I like this a lot and would immediately use it when writing btests that are closer to unit tests in spirit. In fact, I've switched to doing `print function() == F;` or something similar in my btests so it's explicit what I expect the return value to be. `assert` seems cleaner. I like the idea of including this in normal scripts for making the constraints explicit as well.

Would it be possible to have the failure message default to something sane/useful? My thought is just the Zeek script path and line number of the failure. It actually might make sense to always have this even if a failure message is specified. A string representation of `expr` would be nice too, but I suspect that gets lost in the intermediate representation.

**Comment by awelzel** [comment]
> A string representation of expr would be nice too, but I suspect that gets lost in the intermediate representation.

The proposal in the description assumes it's available (1):

> 3\. To change that default behavior, we provide a script-level hook `assert_failure` that runs whenever an assert fails, receiving (1) a string rendering of the failing expression, (2) the failure message, (3) location information where it happened.

**Comment by rsmmr** [comment]
> Would it be possible to have the failure message default to something sane/useful? My thought is just the Zeek script path and line number of the failure.

Yeah, we can definitely capture the location information in any case.

> (1) a string rendering of the failing expression

Actually, I'm now wondering if that's even useful: `<expr>` will return the boolean result, which in the case of failure will always be false,  so rendering that won't tell us anything really.

**Comment by ynadji** [comment]
Oh, I meant the expression prior to evaluation rather than the evaluated result of `<expr>` and I kind of assumed that was what (1) referred to. I agree the evaluated form is not useful.
