### ISSUE TITLE
LogExpireInterval not work(archive log files always there)

### ISSUE THREAD

**Issue by cxdinter** [zeek/zeek#2304]
Hi
    I want to delete archive log files by zeek itself(zeekctl cron), but whatever I set any value for LogExpireInterval in zerkctl.cfg, the archive log files are always there, no deleted. I tried to export zeekctl binary path into PATH environment variable, but no help.
    I also tried to add 'croncmd' in zeekctl.cfg,  but still no help.
     But, if I run 'zeekctl cron' manually, it works. The archive log files will be deleted totally.
      so, what's the mechanism for zeekctl to delete archive log files? Does zeek will edit crontab by itself?
      I am very appreciate if someone give me some guide.
      Thank you in advance.

**Comment by JustinAzoff** [comment]
Zeek does not edit the crontab itself, you need to add the `zeekctl cron` entry yourself
something like

    */5 * * * * /usr/local/zeek/bin/zeekctl cron

**Comment by awelzel** [comment]
I'm closing this given that Justin provided some guidance. @cxdinter , if you need more support, those kind of questions are more suited for Slack or the forum. Thanks!

Forum: https://community.zeek.org/
Slack: https://zeek.org/community/
