### ISSUE TITLE
Suppressing notices not atomic

### ISSUE THREAD

**Issue by anniebryan** [zeek/zeek#2316]
I ran a test script on a pcap that contains several identical packets sent within the same millisecond. The first packet triggers a notice, as desired, but subsequent packets were additionally generating notices that were not being suppressed. Despite these subsequent notices having the same unique `identifier` and a suppress time set to 6 hours, the `notices.log` file was still showing several identical  notices.

After some debugging, I discovered that this was most likely due to the fact that the action of suppressing further notices was not atomic. In [scripts/base/frameworks/notice/main.zeek#L540](https://github.com/zeek/zeek/blob/master/scripts/base/frameworks/notice/main.zeek#L540), the call to `event Notice::begin_suppression` does not guarantee that the `suppressing` table will be updated before the next notification arrives.

My workaround for this was to hook into `Notice::notice` with a greater priority, and manually update the `suppressing` table if the conditions apply.

However, it would be nice to make this action atomic, either by turning `Notice::begin_suppression` into a function, or by updating the `suppressing` table from inside `Notice::notice`.

**Comment by JustinAzoff** [comment]
> turning Notice::begin_suppression into a function

This is a little more complicated because the notice suppression info is distributed across the cluster using that event.

> updating the suppressing table from inside Notice::notice

this would definitely work!  Adding another line that does the

    suppressing[note, identifier] = n$ts + n$suppress_for;

should do it.

**Comment by anniebryan** [comment]
> this would definitely work! Adding another line that does the
> `suppressing[note, identifier] = n$ts + n$suppress_for;`
> should do it.

Is it likely that the maintainers will add this fix in a patch release, or should I create a pull request?

**Comment by JustinAzoff** [comment]
That looks reasonable. should be able to add a test case that calls NOTICE back to back and verify that only a single log entry is written.
