### ISSUE TITLE
Recognize LLC/SNAP after VLAN

### ISSUE THREAD

**Issue by J-Gras** [zeek/zeek#2324]
So far, Zeek assumes to deal with Ethernet II frames when handling VLAN tags. Actually, VLAN tags can be inserted in all Ethernet frame types including LLC and SNAP. While the Ethernet analyzer [considers other frame types](https://github.com/zeek/zeek/blob/857b21ae73b967485e499f84f5cb474ab22a3dfe/src/packet_analysis/protocol/ethernet/Ethernet.cc#L56), VLAN tags followed by LLC/SNAP will cause entries in the unknown protocols log.

This is triggered by some STP variant. See [packetlife.net](https://packetlife.net/captures/protocol/stp/) for an example ([MSTP_Intra-Region_BPDUs.cap](https://www.cloudshark.org/captures/9b9797bd79f6)):
```
zeek -e '@load policy/misc/unknown-protocols redef UnknownProtocol::sampling_rate=1;' -r MSTP_Intra-Region_BPDUs.cap
```

From the top of my head I can imagine three solutions:

1. Replicate the Ethernet analyzer's distinction code in the VLAN analyzer.
2. Remove the VLAN analyzer and integrate it into the Ethernet analyzer.
3. Come up with dedicated Sub-Analyzers that consume some data and then "jump back" into the parent packet analyzer.

The first seems to be the easiest but would replicate code and (maybe) configuration. The second doesn't seem too complicated. The drawback would be that we circumvent the packet analysis composition mechanism. The third approach would need some thinking and most likely change the existing interfaces. If there are other applications (e.g. tunneling) this might still be worth to consider.

**Comment by J-Gras** [comment]
Forgot to include mention a [discussion](https://forums.cabling-design.com/ethernet/ethernet-vlan-using-llc-snap-encapsulation-6862-.htm) that provides some pointers to the potentially relevant standards.

**Comment by timwoj** [comment]
> Replicate the Ethernet analyzer's distinction code in the VLAN analyzer.

I'll be honest, I'm not entirely sure why were did it this way in the first place. Why didn't we just implement SNAP/Novell/LLC analyzers (or leave them unimplemented) and forward into them like any other packet analyzer? Those analyzers wouldn't need to be too complicated, and then the Ethernet and VLAN analyzers could just forward into them. It would break the one packet-protocol-plugin test, since it relies on that mechanism, but it seems more correct to me.

**Comment by J-Gras** [comment]
I am not sure I can follow.
> Why didn't we just implement SNAP/Novell/LLC analyzers (or leave them unimplemented) and forward into them like any other packet analyzer?

We cannot forward into  SNAP/Novell/LLC like other anlyzers because of the somehow strange way these are identified. If the Ethertype is <= 1500, one has to look at the first two payload bytes to determine the actual protocol (see https://en.wikipedia.org/wiki/Ethernet_frame#Types).

The Ethernet analyzer implements the required logic. It allows to explicitly configure and forward into SNAP/Novell/LLC analyzers: https://github.com/zeek/zeek/blob/5db2e5fd8e4c739bd1ab157e81a7611dcddb4940/src/packet_analysis/protocol/ethernet/Ethernet.cc#L56-L84

**Comment by timwoj** [comment]
Ah, now I see how this is working. I recall not being a huge fan of this approach back when we originally merged it, probably for this exact reason. Let me stare at it a bit.
