### ISSUE TITLE
Support for QUIC after recent RFC9114 publication

### ISSUE THREAD

**Issue by fox-ds** [zeek/zeek#2326]
Recently in June 2022, [RFC9114](https://www.rfc-editor.org/rfc/rfc9114.html) was passed. This means that the next version of HTTP, HTTP/3, will use QUIC (RFC8999-9002) as its underlying transport protocol. QUIC is currently used by 8.2% of the websites on the internet (https://w3techs.com/technologies/details/ce-quic), but it is expected that this number will grow a lot bigger in the near future, when clients & servers start to adopt and enable the new HTTP/3 standard by default. 

Currently, there are two plugins that are able to parse an earlier version of the protocol, GQUIC, but they explicitly state that they only support specific (probably outdated) versions of the GQUIC protocol.

* https://github.com/corelight/zeek-quic
* https://github.com/salesforce/GQUIC_Protocol_Analyzer

Therefore, we'd like to start a discussion on whether:
* the official and final QUIC RFC standard needs to be supported in Zeek, or not
* if so, should it be part of the Zeek core (because QUIC is often referred to as a successor of TCP) or built as a standalone (Spicy) plugin?
* anyone is interested in or has the intention to get the parsing of QUIC up-to-date?

We also don't know how fast the QUIC standard will expand on the internet, but we think it's good to adopt this protocol in an early phase to allow for a lot of testing and debugging, before it has silently taken over TCP as the major carrier for HTTP.

Love to hear your opinions on this!

_______________

Tip: A useful YouTube video of the implications can be found [here](https://www.youtube.com/watch?v=cdb7M37o9sU).

**Comment by timwoj** [comment]
We talked about this one as a team a bit today and agree that it's something that Zeek should handle internally. Are there existing pcaps that cover the ratified version of the protocol?

**Comment by 0xxon** [comment]
FWIW - pcaps of IETF-quic are easy to make nowadays, since it seems to be the default version of QUIC used by current versions of Chrome.

**Comment by fox-ds** [comment]
Indeed - we also recorded some Firefox traffic from Windows 11 to YouTube and that also uses IETF-quic. We can generate some sample pcaps of default browser traffic, but also from other tools (e.g. the [Merlin C2 over QUIC](https://github.com/Ne0nd0g/merlin)) if that's useful for the development process.

**Comment by 0xxon** [comment]
I might take a stab at this.

**Comment by fox-ds** [comment]
That's great! Please let us know if we can assist with something.

**Comment by fox-ds** [comment]
@0xxon We'll also experiment a bit with Spicy, will post/commit it into a branch if anything useful comes out of that

**Comment by 0xxon** [comment]
Thank you.
I took a short peak yesterday and - from what I can tell - implementing basic parsing of the handshake should not be too hard. I am a bit low on time this week - my plan is to get something workable done next week-ish.

**Comment by fox-ds** [comment]
I worked on it for a while, and pushed the code to https://github.com/fox-ds/spicy-quic. Note that it's just a start; it should be further improved, but it can be used as a starting point. If the code needs to be moved to some other repository (maybe even part of the main Zeek repo) then that's obviously possible, but I found it easier to work and share the code like this. Feel free to contribute.

**Comment by fox-ds** [comment]
I think so yes, but currently it's not really finished, nor properly tested. However, it might be the most up-to-date Zeek QUIC parser out there since it targets the actual (non draft) RFC. Furthermore, it uses the OpenSSL 3.x.x libraries which are not (yet) commonly used in distributions like Debian (though that seems to change this year). So I think it needs a little more attention / improvements / code review / time before this can be pulled into the main Zeek repo.

**Comment by fox-ds** [comment]
Debian 12 is being released on June 10. Once it's out, I'll try to add some more tests around it and a Dockerfile that will yield in a successful install of the plugin.

**Comment by fox-ds** [comment]
Turns out that the Docker image for Debian 12 was already available, so I edited the code rightaway to work with D12 and did some small refactoring. You can check the Dockerfile at https://github.com/fox-ds/spicy-quic/blob/main/Dockerfile. I can confirm that it still works, I generated & captured some live traffic in my VM and got the TLS SNI from the QUIC Initial packet in both Wireshark & Zeek.

![image](https://github.com/zeek/zeek/assets/90677781/bdf9b856-27cb-4a6a-b228-8b48c655c199)
![image](https://github.com/zeek/zeek/assets/90677781/befb2cb3-4e06-403a-9830-a09e637d5b39)

For now extracting the `server_name`  from those packets seems the most interesting part to me. Also the Zeek parser has some delay, because I think it does not know when the UDP 'connection' is done and thus, when it should forward the packets to the correct analyzer; that's probably something to improve. But I'm still convinced that this repo is a good starting point for getting QUIC support into Zeek. Next steps are probably integrating it with @0xxon 's Spicy TLS parser (as this plugin currently parses the TLS Handshake in a very hacky way) and add some useful Zeek events / scripting around the plugin.

**Comment by awelzel** [comment]
> Furthermore, it uses the OpenSSL 3.x.x libraries which are not (yet) commonly used in distributions like Debian (though that seems to change this year). 

After testing and experimenting with the analyzer, the decryption routines used by the analyzer compile and work within the `zeek/zeek:5.2` image. That image is based on Debian 11.6 and uses OpenSSL 1.1.1n, so the OpenSSL 3.x.x usage should not be a concern (I cross checked with Joost from Fox-IT and he confirmed).

**Comment by awelzel** [comment]
For extensive testing material, the [QUIC Interop Runner](https://interop.seemann.io/) project records pcaps when executing test cases for interop purposes of different implementations and scenarios.

https://github.com/marten-seemann/quic-interop-runner/

**Comment by ckreibich** [comment]
@awelzel this is the work you're currently doing in zeek/zeek#3320, right?
