### ISSUE TITLE
Broker::create_master is very slow when using Broker::scheduler_policy = "stealing"

### ISSUE THREAD

**Issue by awelzel** [zeek/zeek#2332]
Doing more with Broker stores. Below script inserts 1000 entries into a broker backed table (sqlite) and sets Broker::scheduler_policy to "stealing"

The very first run populating the database takes ~0.5seconds on a tmpfs. Follow up runs take 16.5 seconds each, where 16 seconds are spent withing `Broker::create_master()` and from what it looks like blocking the event loop. Switching from Broker::scheduler_policy = "stealing" to "sharing" improves the runtime to ~0.5 seconds, again.

Observed on Zeek 4.2.2, Zeek 5.0 and latest dev release.

```
$ mount -t tmpfs tmpfs ./tmpfs/
$ time zeek ./store-slow-load.zeek
starting create_master, 202.0 msecs 492.952347 usecs
create_master done, 217.0 msecs 300.891876 usecs
received termination signal
zeek_done, 318.0 msecs 881.034851 usecs

real    0m0.447s
user    0m0.185s
sys     0m0.156s
$ time zeek ./store-slow-load.zeek
starting create_master, 222.0 msecs 769.021988 usecs
create_master done, 16.0 secs 495.0 msecs 828.866959 usecs
received termination signal
zeek_done, 16.0 secs 517.0 msecs 205.953598 usecs

real    0m16.673s
user    0m0.496s
sys     0m0.315s
```

In practical terms, this suggests that when running with the "stealing" policy the event loop blocks for  `#entries * Broker::moderate_sleep` on a `Broker::create_master()` call. This would be a reason to use the "sharing" policy, but such a stark difference doesn't seem reasonable.

```
# Store 1000 elements into sqlite backed table tmpfs/mystore.sqlite, when
# running this script a second time and putting Broker::scheduler_policy = "stealing"
# into the command line it takes 16 seconds before "create_master done" loading.
# Which appens to be 1000 * 16msec from the moderate_sleep below.
#
# redef Broker::moderate_sleep = 16msec;
# redef Broker::relaxed_sleep = 64msec;


redef Broker::scheduler_policy = "stealing";

redef exit_only_after_terminate=T;

module Test;

global store : opaque of Broker::Store;
global store_table: table[addr] of string &broker_store="persistenceStore";

global a_count = 0;
event loop()
        {
        local host = count_to_v4_addr(1000000 + ++a_count);
        if ( a_count >= 1000 )
                terminate();

        local uid = unique_id("X");
        store_table[host] = uid;
        schedule 0.00001 sec { loop() };
        }

event zeek_init()
        {
        local pstats = get_proc_stats();
        print "starting create_master", pstats$real_time;
        store = Broker::create_master("persistenceStore", Broker::SQLITE, [$sqlite=[$path=cat("tmpfs/mystore.sqlite")]]);
        pstats = get_proc_stats();
        print "create_master done", pstats$real_time;
        schedule 0.1sec { loop() };
        }

event zeek_done()
        {
        local pstats = get_proc_stats();
        print "zeek_done", pstats$real_time;
        }
```

**Comment by awelzel** [comment]
cc @Neverlord

**Comment by Neverlord** [comment]
@awelzel I have tweaked the work-stealing scheduler to avoid spinlocks and `yield()`. Could you check out the branch `topic/neverlord/work-stealing` in your `auxil/broker` and see if that changes anything?

**Comment by awelzel** [comment]
> @awelzel I have tweaked the work-stealing scheduler to avoid spinlocks and yield(). Could you check out the branch topic/neverlord/work-stealing in your auxil/broker and see if that changes anything?

It does - populating and loading takes roughly the same time now. The 16seconds delay is gone.

I'm a bit unsure about the implications of the caf side change where the `sleep_for()` being replaced with an interruptible sleep on a mutex (IIUC). There may be positive (non-intended) effects of the `sleep_for` resulting in implicitly batching up work.

For example, understanding from previous experiments: if a work item appears every 100usec or less in the queue, it may be more efficient to sleep for sometime (16msec, moderate_sleep default) and then process all queued items at once rather than taking a mutex for each individual item anew. Basically trading interactivity for throughput. When previously switching from `sharing` to `stealing` policy in a Zeek deployment, we saw much improved `%sys` load of individual processes and mainly attributed it to above implicit batching rather than anything particular about the `stealing` algorithm.

Seems for the loading of broker store tables, that sleeping/batching does introduce noticeable delay, however.

Anyway, mainly something to look out for if the `caf` change makes and raising awareness a bit.

**Comment by Neverlord** [comment]
I'm not quite sure what you mean by "improved" `%sys` load. Overall less CPU cycles? That would not be a result of the batching itself, I think. That's probably due to fewer aggressive attempts overall as a result of the uninterruptable sleeping.

In any case, thank you for testing and confirming! There also had been reports of performance degradations on Windows, where the spinning/yielding could also escalate to scheduling delays of several milliseconds. Not as extreme, but all data points so far point at going the mutex-wait route is the right thing to do. The results of the benchmarking I did so far also look solid.

**Comment by timwoj** [comment]
Is this done once that CAF update gets merged?

**Comment by Neverlord** [comment]
Yep, there's no other todo.

**Comment by timwoj** [comment]
Great. I'm just waiting on a build for https://github.com/zeek/zeek/pull/2451 then I'll close this out.
