### ISSUE TITLE
Zeek renaming: update event names

### ISSUE THREAD

**Issue by jsiwek** [zeek/zeek#236]
`bro_init`, `bro_done`, and `bro_script_loaded` need zeekification (not sure there's others).  Old names need deprecation tag/warning.

**Comment by sethhall** [comment]
Hm, I guess I have more work to do to really finish this task.  The existing branch I did doesn't implement `bro_script_loaded`

**Comment by jsiwek** [comment]
Thanks, Seth.  I took care of `bro_script_loaded` and didn't see any remaining event names with "bro" in them.
