### ISSUE TITLE
broker.ssl_auth_failure consistently fails on Mac Os (monterey) after broker update

### ISSUE THREAD

**Issue by 0xxon** [zeek/zeek#2367]
After updating broker to zeek/broker@92b4287c3a744923116e9c34af2e8b656f393b29, the broker.ssl_auth_failure test consistently fails on my mac os installation with:

```
$ btest -d broker.ssl_auth_failure
[  0%] broker.ssl_auth_failure ... failed
  % '$SCRIPTS/wait-for-file send/failed 20 || (btest-bg-wait -k 1 && false)' failed unexpectedly (exit code 1)
  % cat .stderr
  <<< [90842] zeek -b ../recv.zeek >recv.out
  received termination signal
  >>>
  <<< [90852] zeek -b ../send-check.zeek >send.out
  received termination signal
  >>>
  <<< [90870] zeek -b ../send.zeek >send.out
  received termination signal
  received signal while waiting for thread reporter/Log::WRITER_ASCII, aborting all ...
  >>>
```

Changing the broker submodule pointer is the only required change. The previous version (which Zeek master points to as of now), works. That version is zeek/broker@8d03476847411b0ab7b9c47ea9eaf7b1535d08c2 of broker. 

Convenience diff link: https://github.com/zeek/broker/compare/8d03476847411b0ab7b9c47ea9eaf7b1535d08c2..92b4287c3a744923116e9c34af2e8b656f393b29

This test was done with a clean Zeek checkout at 882949004591a1af6ac2dbb112c20a06e7465bba on Mac Os 12.5.1; my system uses OpenSSL 3.0.5 (macports).

**Comment by timwoj** [comment]
I'm seeing the same failure on the release/5.0 branch on a local macOS build. I don't have that broker commit in the 5.0 build though. The only broker commit I brought over that wasn't in the 5.0.0 release is https://github.com/zeek/broker/commit/92b4287c3a744923116e9c34af2e8b656f393b29.

**Comment by ckreibich** [comment]
I'm seeing this also on Fedora on fresh master builds, and I can confirm that your branch also fixes it over here, Tim.

**Comment by timwoj** [comment]
Yep, I think it's actually failing on basically every platform now, based on the last CI build: https://cirrus-ci.com/build/5887215984181248

**Comment by rsmmr** [comment]
@Neverlord? This will be blocking the 5.0.1 release.

**Comment by Neverlord** [comment]
@rsmmr Looks like Tim already has a PR filed: https://github.com/zeek/zeek/pull/2372.

**Comment by rsmmr** [comment]
Ah, I missed that. Taking a look.
