### ISSUE TITLE
Creating fuzzer corpus from dictionary doesn't work

### ISSUE THREAD

**Issue by timwoj** [zeek/zeek#2374]
The fuzzer documentation has this snippet in it for generating a corpus from a `.dict` file:

```
mkdir corpus && ./src/fuzzers/zeek-pop3-fuzzer corpus \
  -dict=../src/fuzzers/pop3.dict -max_total_time=300 -fork=$(($(nproc) - 1))
```

Except for that running that command results in this:

```
Standalone fuzzer processing 4 inputs
  test: failed to read full file: 0/64
```

Looking at the files in the fuzzer directory for starting up a process, I don't see where that actually ever worked.

**Comment by JustinAzoff** [comment]
That looks like you are using the fallback fuzzer `main()` impl that Jon wrote for use in the tests, and not the one that comes with libfuzzer that implements all those options.

**Comment by timwoj** [comment]
Yep. Once built with libFuzzer it operated as expected. I'm working on trying to run the fuzzer locally for some testing, and this came up.
