### ISSUE TITLE
Zeek renaming: GitHub language name and highlighting

### ISSUE THREAD

**Issue by jsiwek** [zeek/zeek#238]
We'd likely want to look at how to change the language name to Zeek on GitHub and also support a new filename extension (#237).

I haven't looked into how that stuff works yet, but seems to be the linguist stuff here: https://github.com/github/linguist/blob/master/lib/linguist/languages.yml

**Comment by jsiwek** [comment]
The linguist changes got merged: https://github.com/github/linguist/pull/4516

But expect GitHub website won't see changes until at least a linguist release gets made, so keeping this open to check back in once that happens.

**Comment by jsiwek** [comment]
New linguist got released today and looks like GitHub website is properly detecting our Zeek language usage and highlighting .zeek files now.

**Comment by rsmmr** [comment]
Nice!

-- 
Robin Sommer * Corelight, Inc. * robin@corelight.com * www.corelight.com
