### ISSUE TITLE
analyzer/dpd: Remove "-<analyzer>" strings from c$service

### ISSUE THREAD

**Issue by awelzel** [zeek/zeek#2388]
Currently, the `dpd/main.zeek` (or `analyzer/dpd.zeek` file in the future - if/when #2379 is merged) is populating the `c$service` field with `-<analyzer>` and `<analyzer>` strings depending on analyzer confirmation and violations.

@sethhall isn't particularly fond of the above and suggested to track, violating analyzers in a separate set instead rather than putting string modified analyzer names. Within the base scripts, for conn.log entries there's an extra check to entries with a leading `-`.

https://github.com/zeek/zeek/blob/master/scripts/base/protocols/conn/main.zeek#L229-L233

Otherwise, it's unlikely that someone is relying on `-<analyzer>` name in `c$service` while there are know situations where users need to accommodate and filter out `-<analyzer>` names (when tracking known services, for example).

Proposal is to remove the `-<analyzer>` names from `c$service`. While this is a "silent" change in behavior, it seems worthwhile doing.

**Comment by awelzel** [comment]
@JustinAzoff  - I know you provided feedback on scripts dealing with the `-<analyzer>` in `c$service` - any opinion if they could be useful?

**Comment by rsmmr** [comment]
Sounds good to me.
