### ISSUE TITLE
Logging outages with Zeek 5

### ISSUE THREAD

**Issue by ckreibich** [zeek/zeek#2389]
We've touched this in various contexts now and afaict there's no ticket yet, so here's @awelzel's summary from [Slack](https://zeekorg.slack.com/archives/C01T41ULYKG/p1661345227682119), combining a few findings:

----

Here's a scenario for complete logging fallout - not sure it's what [@MikeP](https://zeekorg.slack.com/team/U01CCHE5SDB) is seeing, but might be close. Setup:

* Two Ubuntu VMs configured with zeekctl (installed via deb packags from OBS build service)
    * VM1: hosting manger, logger, two proxies (and "control")
    * VM2: two worker nodes with 4 lb_procs each, all sniffing the very same interface with lb_method=interfaces
* Replaying traffic through a second-interface attached to VM2 at ~300pkts/s, mix of HTTP, dns and https traffic.
* Set `Known::*tracking` to `ALL_HOSTS`

The crux is, if I kill one of the worker processes on VM2 (`kill <pid of worker-1-1>`), there's a flurry of activity in cluster.log that looks very confused (see [cluster.log](https://github.com/zeek/zeek/files/9457208/cluster.log)). Few seconds later, conn.log, http.log etc stop being populated. stats.log continues, but only for proxy-1, proxy-2 and logger.

It seems the multiple VMs are required. I wasn't able to reproduce it with a `zeek -j` setup and selectively killing a worker.

One more datapoint: Running the initial experiment with 2 VMs without the known-* scripts loaded still stops logging after killing a single worker. Hand-wavy-seemingly takes longer than with them loaded, but eventually logging stops too.

A complete fallout of logging just because one worker unexpectedly died or is killed (even with SIGTERM) seems pretty bad - this isn't an unusual occurrence.

----

(@Neverlord, fyi)

**Comment by Neverlord** [comment]
Thanks for the inputs here, I'll try and reproduce this.

**Comment by awelzel** [comment]
Likely related: https://community.zeek.org/t/logging-issue-after-upgrade-to-lts-5-0-0/6613/4

**Comment by ckreibich** [comment]
I'm closing this given zeek/broker#296 — if this resurfaces, we can reopen here or create a new issue.
