### ISSUE TITLE
build  error in apple silicon

### ISSUE THREAD

**Issue by kento996** [zeek/zeek#2395]
-- Configuring done
CMake Error in auxil/spicy/spicy/hilti/toolchain/CMakeLists.txt:
  Found relative path while evaluating include directories of "driver.cc":

    "FLEX_INCLUDE_DIR-NOTFOUND"

CMake Error in auxil/spicy/spicy/hilti/toolchain/CMakeLists.txt:
  Found relative path while evaluating include directories of "__parser.cc":

    "FLEX_INCLUDE_DIR-NOTFOUND"

CMake Error in auxil/spicy/spicy/hilti/toolchain/CMakeLists.txt:
  Found relative path while evaluating include directories of "__scanner.cc":

    "FLEX_INCLUDE_DIR-NOTFOUND"

CMake Error in auxil/spicy/spicy/spicy/toolchain/CMakeLists.txt:
  Found relative path while evaluating include directories of "driver.cc":

    "FLEX_INCLUDE_DIR-NOTFOUND"

CMake Error in auxil/spicy/spicy/spicy/toolchain/CMakeLists.txt:
  Found relative path while evaluating include directories of "__parser.cc":

    "FLEX_INCLUDE_DIR-NOTFOUND"

CMake Error in auxil/spicy/spicy/spicy/toolchain/CMakeLists.txt:
  Found relative path while evaluating include directories of "__scanner.cc":

    "FLEX_INCLUDE_DIR-NOTFOUND"

-- Generating done

**Comment by awelzel** [comment]
I believe I've seen that with a missing or too old flex.

Do you have flex installed and what does `flex --version` tell you? The minimum requirement is 2.6 these days.

**Comment by kento996** [comment]
> 

![image](https://user-images.githubusercontent.com/72925466/188193410-7a09ac7d-8f70-4e79-ab5b-c35cd5051634.png)

**Comment by kento996** [comment]
![image](https://user-images.githubusercontent.com/72925466/188193661-9b772a16-5abb-4b23-9abe-c1df7ec24079.png)

**Comment by timwoj** [comment]
There's something about the flex installed by default that doesn't work correctly. @bbannier might remember exactly what it was.

On my m1 machine here though, the version in `brew` works correctly.

**Comment by kento996** [comment]
@bbannier Have you encountered such a problem?

**Comment by kento996** [comment]
> There's something about the flex installed by default that doesn't work correctly. @bbannier might remember exactly what it was.
> 
> On my m1 machine here though, the version in `brew` works correctly.

think you!solve it.

**Comment by hominsu** [comment]
The documentation has to be updated, there is no mention of Flex being required.

**Comment by AmazingPP** [comment]
> The documentation has to be updated, there is no mention of Flex being required.

The document says that Flex is a required dependency. [Required Dependencies](https://docs.zeek.org/en/master/install.html?highlight=Flex#required-dependencies)

**Comment by timwoj** [comment]
I opened a docs issue to get the documentation updated. I'm going to close this one out as it seems your problem is resolved.
