### ISSUE TITLE
Support disabling packet analyzers

### ISSUE THREAD

**Issue by awelzel** [zeek/zeek#2399]
This ticket is about tracking ideas and implementing functionality to disable packet analyzers.

Existing analyzers for tunnels have special `enable` flags.

https://github.com/zeek/zeek/blob/875e81883c666e2058a976bd84e5ebd734e9faf2/src/const.bif#L18-L22

These are not runtime changeable (though there may not be a good reason for that limitation).

Further, it's currently *not* possible to disable packet analyzers using, for example, the `AllAnalyzers::Tag` allocated to them. Let alone using the data passed to `analyzer_violation()` from packet analyzers (calling `disable_analyzer()` for a packet analyzer tag is not sensible as `disable_analyzer()` looks for a protocol analyzer attached to the connection).

Ideas:
* Remove analyzers out of the analyzer tree using their tags (and optionally identifier)
  * Need to know at which point in the tree they are located (or support recursive/wild-card removal)
  * This approach modifies the analyzer tree, so to re-enable analyzers, the caller requires knowledge of the "right" locations in the tree and identifiers

* Add a "enabled or disable" flag into the dispatcher table entries
  * The `AnalyzerPtr` entries become structs/classes of `{AnalyzerPtr, enabled}`
  * Can disable analyzers but keep them in the tree (again, recursively or at individual points)
  * Enabled/disabled lookup is fast (no indirection via `AnalyzerPtr` needed, within the memory of the table)
  * Easier to re-enable without needing to know the locations of analyzers/identifiers (recursively enable in the whole tree, for example)
  * Possible signature: `disable_packet_analyzer(parent, child, identifier: int =-1 &otional, recursive: bool &default=true)`
  * Analyzer tree structure is immutable

* Use the Component mechansim as done for protocol and file analyzers
  * May require a `->Lookup()` to get the component on a per-packet basis may be prohibitive

I'm thinking of sketching/implementing the second approach and see how it fares. Thoughts.

cc @J-Gras

**Comment by ckreibich** [comment]
The main driver for this is symmetry with protocol and file analyzers, right? If so, the third option sounds appealing to me — it looks like the lookup in the packet analyzers' dispatcher is just a vector index. I like the second option too, but it might be worth checking if the third is in fact problematic before going a new route for the packet analyzers.

**Comment by rsmmr** [comment]
How about a lighter-weight version of (3): I'd say the main API to align is the managers' `DisableAnalyzer` methods. That's what for protocol analyzers then branches out into the components to call their `SetEnabled()`. For packet analyzers, we could instead keep state internal in the manager for quicker lookup, like just an array of bools, pretty much like (2). 

And I think we could then also extend the script-side `disable_analyzer` to support packet analyzers as well.

**Comment by awelzel** [comment]
> How about a lighter-weight version of (3): I'd say the main API to align is the managers' DisableAnalyzer methods. That's what for protocol analyzers then branches out into the components to call their SetEnabled().

Okay. The idea with (2) was had in mind to disable/remove individual entries within the analyzer tree, but maybe that was overthinking it. Happy to just enable/disable for now. The packet analyzer instances are singletons via shared_ptr IIRC, we may also be able to attach state to them directly for global enable/disable.

**Comment by awelzel** [comment]
So #2443 implemented a "fast version of (3)". I'm currently unclear if we actually want to do some version of (2) in the near future where individual entries of the dispatcher table can be toggled? (Jan was curious/interested in this).

I'm closing this now and if the ask comes up can re-open/re-consider the (2) approach.
