### ISSUE TITLE
Zeek renaming: BroControl -> ZeekControl

### ISSUE THREAD

**Issue by jsiwek** [zeek/zeek#240]
If BroControl is intended to be replaced by a new supervisor project, it's maybe not worth renaming the project?  Or just rename it to avoid confusion?

It's probably likely there will at least be code changes needed to get it to work with all the other renaming going on.  E.g. I imagine #239 will probably break BroControl and we can't just release a 2.7 where BroControl is completely broken, we need at least one release of it being in a working, but deprecated state.

**Comment by jsiwek** [comment]
Seems we'll need to do a rename.  #239 should cover the basic broctl -> zeekctl executable file rename and possibly other details and #233 might get all the content renaming, but I'll keep this open as a reminder to audit whether anything further needs to be done.  E.g. the git repo and submodule name will be something to change.

**Comment by rsmmr** [comment]
This is included in the work for  #239.

**Comment by jsiwek** [comment]
Last thing here would be renaming the repo/submodule, which I'll try to take care of later today.

**Comment by jsiwek** [comment]
Renamed the GitHub repo to `zeekctl` and the submodule is also renamed via f37a16b7151cde38b1c3b3321e6a3dd9b9338e62.
