### ISSUE TITLE
dns_mgr priming test failures in ci

### ISSUE THREAD

**Issue by awelzel** [zeek/zeek#2402]
I've seen this twice now, so opening an issue. This happened in a `centos-7` job.

```
[doctest] doctest version is "2.4.8"
[doctest] run with "--help" for options
===============================================================================
../../src/DNS_Mgr.cc:1614:
TEST CASE:  dns_mgr priming

../../src/DNS_Mgr.cc:1656: ERROR: CHECK( strcmp(addr_result->CheckString(), "one.one.one.one") == 0 ) is NOT correct!
  values: CHECK( -1 == 0 )
```

This is a link to the cirrus task:
https://cirrus-ci.com/task/4653923205120000?logs=test#L19

**Comment by timwoj** [comment]
We talked this morning and it seems like there's a few options here:

- Talk to Fedor about why the network connectivity fails periodically on the runners and see if we can fix it to not fail like this
- Mark these tests as `may_fail`, and accept they might fail on CI
- Try to add something to /etc/hosts on the runners to force this to always succeed

I like the third options, personally.

**Comment by ckreibich** [comment]
> I like the third options, personally.

Yeah, same.

**Comment by 0xxon** [comment]
Is this still happening regularly? :)

**Comment by timwoj** [comment]
I think Arne was the only one that ever saw it. I'll make the change for /etc/hosts and see if it works today.

**Comment by timwoj** [comment]
I made the /etc/hosts change on the Ubuntu 22 Dockerfile. It didn't break anything but it's hard to tell if it fixed anything either since the build ran through previously without failing. I can make the same change to the other Dockerfiles and just cross our fingers that this acctually does something.

**Comment by ckreibich** [comment]
Tim this remained an experiment, right? I'm wondering if you could verify that the approach works by putting in place a false address mapping. If that fails the tests, I vote for putting a mapping into all Dockerfiles ... we could establish a script run by them all, for centralized tweaking.

**Comment by timwoj** [comment]
Right. It never went beyond that one CI test.

**Comment by timwoj** [comment]
Given that we haven't really seen this again, I'm going to just close this.
