### ISSUE TITLE
Func->Name() returning invalid characters

### ISSUE THREAD

**Issue by dopheide-esnet** [zeek/zeek#2409]
Func->Name() is sometimes returning illegible characters.
zeek: 5.0.1  (so far, I'll try to test more versions)

Background:   We've been using the zeek-exporter package that Vlad wrote for quite some time.  I noticed recently that data for workers was disappearing from our grafana dashboard.   As it turns out, the issue is the data collected by prometheus starts to look like this:

zeek_function_calls_total{node="zeek-east1-w3",function_caller="<80><AA>s^N",function_type="event",name="ssh_auth_attempted"} 138.000000

Which results in...

2022-09-04T03:29:17.412619+00:00 sec-west prometheus[2584987]: ts=2022-09-04T03:29:17.412Z caller=scrape.go:1335 level=debug component="scrape manager" scrape_pool=every_10s target=http://zeek-east1.es.net:9102/metrics msg="Append failed" err="invalid UTF-8 label value"

Prometheus is refusing to append the data because of the invalid 'function_caller' label name.   All that should be is the name of the function that called the current function, as the plugin is tracking the function lineage.   The value as far as I can tell comes from calls to Func->Name().

I'm attaching a file of sample functions where the function_caller was illegible in case someone can see a pattern.
[function-name-sample.txt](https://github.com/zeek/zeek/files/9536617/function-name-sample.txt)

**Comment by vpax** [comment]
It's pretty hard to see how that method could return garbage since `Func` objects keep their own copy of the name, so it's not like there's an opportunity for a dangling pointer, and nothing should be changing the name after initial compilation. So unfortunately I don't see how this can be run down without code that reproduces the problem.

**Comment by vpax** [comment]
Hmmm though maybe what's going on is the pointer to the `Func` is bad, so it's retrieving garbage for the name - that seems more likely than the name having been stepped on.

**Comment by dopheide-esnet** [comment]
Yeah, more troubleshooting and a bunch of horrible C++ code later, I think Func->Name() is fine as you say and it's just the whole func structure getting cleaned up out from under me.  I'm currently making my own copy of the name for our lineage tracking which so far seems to be working.   Closing this issue.

**Comment by timwoj** [comment]
I'm curious what's eating the object though.

**Comment by dopheide-esnet** [comment]
Me too.  If you think of a way to test that I'm happy to try it out.  Maybe there's somewhere in the base code where we can test types of objects before they are freed?
