### ISSUE TITLE
Zeek renaming: bro-pkg

### ISSUE THREAD

**Issue by jsiwek** [zeek/zeek#241]
This is similar to #239, but also requires doing something about the name of project on PyPI.  Haven't looked into possibilities for renaming, but I imagine we may have to maintain a duplicate upload under the old bro-pkg name after choosing a new one.

Also open to suggestions on what to name it, `zkg` seems short/easy and what I'll go with if there's no other strong candidates.

**Comment by sethhall** [comment]
I like zkg!

**Comment by 0xxon** [comment]
I like zkg too - nice and short.

**Comment by JonZeolla** [comment]
+1 to that

**Comment by thinrope** [comment]
There is no (sane) link between `zeek` and `zkg`, short does not mean simple always.

What is wrong with zeek as package name? It is generally both user and package maintainer frustration to find "which software are you referring to" by using one name, why add another?
I think, given the new name, all places should use the name zeek and nothing else (except platform specific, e.g. under Gentoo that will (soon!) be `net-analyzer/zeek`) .

Now, I get it... there is already unrelated pkg with that name https://pypi.org/project/zeek/ coming originally from @kristianperkins https://github.com/kristianperkins/zeek ..
The next best will be `zeek-pkg` then (and contact ask @kristianperkins for a link in URL? And add one to his project?).

In the same train of thoughts, may be we should ask @jathanism to retract his unrelated bro [package from PyPI](https://pypi.org/project/bro/) and [github](https://github.com/jathanism/bro), given that it has no actual release, and code for that matter, for 3 years.

**Comment by jsiwek** [comment]
@thinrope you're probably confused since this issue is filed in the `zeek` repo, but it's actually referring to a different package management tool, currently named `bro-pkg`:

https://github.com/zeek/package-manager

So we obviously can't name both the package manager (`bro-pkg`) and the network analysis tool (`bro`, soon to be `zeek`) to be `zeek`.  The other bro/zeek projects you mention aren't harmful to just let be IMO.

**Comment by thinrope** [comment]
Oh well, yes indeed, a bit :-D

bro -> zeek and bro-pkg ->zkg makes sense, iff you rename the repo zeek/package-manager to zeek/zkg (and probably this issue must have been in the [zeek/package-manager](https://github.com/zeek/package-manager) list to begin with)

**Comment by kristianperkins** [comment]
Hi, thanks for @-ting me in. The zeek package I created a long time ago probably doesn't have a lot of usage these days (I personally haven't used zookeeper in years).

I'm not sure what the rules on recycling projects on PyPI are (if there are any) but if the owners of this project are interested in taking over "zeek" on PyPI for this project, that's ok with me.

**Comment by jsiwek** [comment]
This is done: `bro-pkg` is now `zkg` and has a v2.0.0 release.

**Comment by jathanism** [comment]
> There is no (sane) link between `zeek` and `zkg`, short does not mean simple always.
> 
> What is wrong with zeek as package name? It is generally both user and package maintainer frustration to find "which software are you referring to" by using one name, why add another?
> I think, given the new name, all places should use the name zeek and nothing else (except platform specific, e.g. under Gentoo that will (soon!) be `net-analyzer/zeek`) .
> 
> Now, I get it... there is already unrelated pkg with that name https://pypi.org/project/zeek/ coming originally from @kristianperkins https://github.com/kristianperkins/zeek ..
> The next best will be `zeek-pkg` then (and contact ask @kristianperkins for a link in URL? And add one to his project?).
> 
> In the same train of thoughts, may be we should ask @jathanism to retract his unrelated bro [package from PyPI](https://pypi.org/project/bro/) and [github](https://github.com/jathanism/bro), given that it has no actual release, and code for that matter, for 3 years.

OMG. I had no idea I was hogging this name. I staged it so long ago I had completely forgotten abou tit. I will happily release and/or transfer ownership of `bro` on PyPI to you and your team.  

If you'd like to discuss it out of band or just let me know which user to transfer ownership to I'll jump on it ASAP. And my apologies for being a blocker to your project's naming!

**Comment by jsiwek** [comment]
@jathanism not a problem: the `bro` package on PyPI has never been a blocker to what we're trying to do and you only got mentioned here due to a misunderstanding.  So nothing more to do here IMO.
