### ISSUE TITLE
Replay pcaps but 0 packets received on interface.

### ISSUE THREAD

**Issue by seventrees** [zeek/zeek#2420]
Hi!
I make zeek listen for traffic on the NIC ```ens9f1```  with the following command.  
```
sudo zeek -i ens9f1 -C
```
And then I use tcpreplay to replay some pcaps from open datasets on the NIC ```ens9f1```.
And I confirme that the traffic was successfully sent through the nload. But somehow, zeek just say "0 packets received on interface ens9f1" and no logs are output. Could you tell me why this happens? Thanks!!!

**Comment by awelzel** [comment]
> And I confirme that the traffic was successfully sent through the nload.

Can you confirm that `tcpdump -i ens9f1` or using `wireshark` on the interface works as expected when running tcpreplay?

Further, I'm going to close this issue. Please join Slack (zeekorg.slack.com) or Discourse (community.zeek.org) and post your findings there if you need further guidance/support. Thanks!
