### ISSUE TITLE
Docs for prereq packages incomplete for bullseye on raspbian

### ISSUE THREAD

**Issue by gtaws** [zeek/zeek#2421]
More for future reference, needed to install libfl-dev so that configure can generate build files

symptoms: Cmake reports errors during configure complaining that FLEX_INCLUDE_DIR-NOT_FOUND
machine: Raspberry Pi 4 2GB
OS: DietPi
version: bullseye

how to reproduce:
- run git clone --recursive https://github.com/zeek/zeek
- run sudo apt-get install cmake make gcc g++ flex bison libpcap-dev libssl-dev python3 python3-dev swig zlib1g-dev
- cd zeek
- run configure

Workaround:
- run sudo apt-get install libfl-dev

**Comment by awelzel** [comment]
This is due to spicy depending on libfl-dev. Disabling spicy, or using a pre-built spicy (`--with-spicy=/opt/spicy`) avoids the dependency.

So while technically not a Zeek dependency, I'm happy to just add it to `install.rst` in zeek/zeek-docs unconditionally given how we're defaulting to building this.

```
================================================================

-- Configuring done
CMake Error in auxil/spicy/spicy/hilti/toolchain/CMakeLists.txt:
  Found relative path while evaluating include directories of "driver.cc":

    "FLEX_INCLUDE_DIR-NOTFOUND"



CMake Error in auxil/spicy/spicy/hilti/toolchain/CMakeLists.txt:
  Found relative path while evaluating include directories of "__parser.cc":

    "FLEX_INCLUDE_DIR-NOTFOUND"



CMake Error in auxil/spicy/spicy/hilti/toolchain/CMakeLists.txt:
  Found relative path while evaluating include directories of "__scanner.cc":

    "FLEX_INCLUDE_DIR-NOTFOUND"



CMake Error in auxil/spicy/spicy/spicy/toolchain/CMakeLists.txt:
  Found relative path while evaluating include directories of "driver.cc":

    "FLEX_INCLUDE_DIR-NOTFOUND"



CMake Error in auxil/spicy/spicy/spicy/toolchain/CMakeLists.txt:
  Found relative path while evaluating include directories of "__parser.cc":

    "FLEX_INCLUDE_DIR-NOTFOUND"



CMake Error in auxil/spicy/spicy/spicy/toolchain/CMakeLists.txt:
  Found relative path while evaluating include directories of "__scanner.cc":

    "FLEX_INCLUDE_DIR-NOTFOUND"



-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
Also, before re-running configure, consider cleaning the cache (removing the build directory) via `make distclean`
```

**Comment by gtaws** [comment]
Is spicy needed for zeek, or is it to help with creating other zeek plugins? I still get problems building it with errors such as type names that don't name a type "error: ‘zeek_uint_t’ does not name a type"

**Comment by awelzel** [comment]
> Is spicy needed for zeek, or is it to help with creating other zeek plugins? I still get problems building it with errors such as type names that don't name a type "error: ‘zeek_uint_t’ does not name a type" on v5.0.1 codebase

Spicy is currently not required for Zeek, but including it makes it easier to leverage and work with analyzers written with Spicy.

> I still get problems building it with errors such as type names that don't name a type "error: ‘zeek_uint_t’ does not name a type" on v5.0.1 codebase

Is it possible you didn't synchronize submodules or are otherwise using a stale checkout/build? Try running the following and remove the build directory to see whether that helps.
```
git submodule update --init --recursive .
```

**Comment by gtaws** [comment]
that was it - I need to run this after I checkout the tagged release. Thanks!
