### ISSUE TITLE
CentOS 8 Stream repository is empty

### ISSUE THREAD

**Issue by x4rxes** [zeek/zeek#2431]
Last modification of https://download.opensuse.org/repositories/security:/zeek/CentOS_8_Stream/ repo was 07-Jul-2022 13:31 and the repository contains no packages.

**Comment by awelzel** [comment]
Hello - this has been reported on community.zeek.org as well and it's an issue with the openSUSE build service we're leveraging - please chime in or follow the following thread:

https://community.zeek.org/t/centos-8-stream-installation/6637

I'm closing this ticket - @0xxon feel free to re-open if you think it's worth tracking here has well?

**Comment by ckreibich** [comment]
Duplicate of #2406
