### ISSUE TITLE
zeek 5.0.2 does not build with caf 0.18.6

### ISSUE THREAD

**Issue by chenrui333** [zeek/zeek#2452]
👋 it looks like zeek 5.0.2 does not build with caf 0.18.6

See details in this PR, https://github.com/Homebrew/homebrew-core/pull/111218

**Comment by timwoj** [comment]
@Neverlord Can you take a peek at this?

**Comment by Neverlord** [comment]
Broker no longer follows the CAF release cycle. Hence, the recipe should no longer set `CAF_ROOT`. This option only exists for Zeek developers at this point. I've also left a comment in the Homebrew ticket. 🙂

**Comment by timwoj** [comment]
The conversation related to this moved over to https://github.com/Homebrew/homebrew-core/pull/111218.
