### ISSUE TITLE
Missing fuid in some smb_files.log entries

### ISSUE THREAD

**Issue by GrayNeel** [zeek/zeek#2455]
Hello, i'm having troubles understaing the way Zeek decides to add or not the fuid field to smb_files.log entries. An example of a run gives me as output the following entries:

```
{
  "ts": 138.836303,
  "uid": "Cq7HgmaYpCfODsjh",
  "id.orig_h": "192.168.1.4",
  "id.orig_p": 49191,
  "id.resp_h": "192.168.1.5",
  "id.resp_p": 445,
  "action": "SMB::FILE_OPEN",
  "path": "\\\\PCB\\directorioCompartido",
  "name": "F10012.pdf",
  "size": 33233,
  "times.modified": 1582207053.462991,
  "times.accessed": 1582207540.5640702,
  "times.created": 1582207540.5640702,
  "times.changed": 1582207540.5640702
}

{
  "ts": 138.836303,
  "uid": "Cq7HgmaYpCfODsjh",
  "id.orig_h": "192.168.1.4",
  "id.orig_p": 49191,
  "id.resp_h": "192.168.1.5",
  "id.resp_p": 445,
  "action": "SMB::FILE_READ",
  "path": "\\\\PCB\\directorioCompartido",
  "name": "F10012.pdf",
  "size": 33233,
  "times.modified": 1582207053.462991,
  "times.accessed": 1582207540.5640702,
  "times.created": 1582207540.5640702,
  "times.changed": 1582207540.5640702
}

{
  "ts": 138.836303,
  "uid": "Cq7HgmaYpCfODsjh",
  "id.orig_h": "192.168.1.4",
  "id.orig_p": 49191,
  "id.resp_h": "192.168.1.5",
  "id.resp_p": 445,
  "fuid": "FAmChGaYZ8hZoKD0j",
  "action": "SMB::FILE_READ",
  "path": "\\\\PCB\\directorioCompartido",
  "name": "F10012.pdf",
  "size": 33233,
  "times.modified": 1582207053.462991,
  "times.accessed": 1582207540.5640702,
  "times.created": 1582207540.5640702,
  "times.changed": 1582207540.5640702
}
```

As you can see, only the last entry contains the fuid, but i need to have it also in all the other actions (e.g., the first entry which is a FILE_OPEN). Is it possible to force zeek to give me the fuids for all the entries?

**Comment by ckreibich** [comment]
Hi there,

I'm wondering if it might be a long-lived connection whose beginning Zeek didn't observe, or some such. More importantly: we don't use GitHub issues for support questions. Please post questions such as this one on Slack or our Discourse server. The Zeek developers and users will be happy to help. You can join here:

Slack: https://zeek.org/community/
Discourse: https://community.zeek.org/

Thanks!
