### ISSUE TITLE
About zeek packet capture data writing time

### ISSUE THREAD

**Issue by CindyStudyEveryday** [zeek/zeek#2467]
When zeek captures a complete packet, a log record will be formed. But how can we count traffic data once in a fixed period of time? For example, when users upload or download files, it takes half an hour. I want to count the unfinished sessions every ten minutes, even though the session has not ended yet. Do you have any relevant solutions or ideas? Thank you.

**Comment by 0xxon** [comment]
Hi,

We don't use GitHub issues for support questions. Questions like this are best answered using on either slack or our forum, which is both are frequented by Zeek developers and professional users. You can join here:

Forum: https://community.zeek.org/

Slack: https://zeek.org/community/

 Johanna
