### ISSUE TITLE
can't use built-in event to analyze pcag file

### ISSUE THREAD

**Issue by AatroxMercer** [zeek/zeek#2474]
when I tried to reproduce the spicy tutorial, a fatal error occured.
https://docs.zeek.org/projects/spicy/en/v1.4.1/tutorial/index.html#parsing-one-packet-type
```
$ zeek -r tftp_rrq.pcap udp-contents
fatal error: can't find udp-contents
```
and the udp-contents should be installed
```
$zeek -NN | grep udp
    [Event] rdpeudp_syn
    [Event] rdpeudp_synack
    [Event] rdpeudp_established
    [Event] rdpeudp_data
    [Event] udp_request
    [Event] udp_reply
    [Event] udp_contents
    [Event] udp_multiple_checksum_errors
```
I'm using zeek 5.0.2, and spicy1.5.1

**Comment by bbannier** [comment]
The script `udp-contents.zeek` is linked near the end of section 4.1.1 in the doc you linked.

The example assumes that you downloaded the file and have it in a location where Zeek can find it, e.g., the direction from which you execute `zeek -r tftp_rrq.pcap udp-contents`.
