### ISSUE TITLE
Error in PIA TCP

### ISSUE THREAD

**Issue by pbcullen** [zeek/zeek#2475]
We saw the following stack trace on a system running Zeek 4.2.2:

`zeek::detail::EquivClass::CCL_Use(zeek::detail::CCL*)
zeek::detail::DFA_State::SymPartition(zeek::detail::EquivClass const*)
zeek::detail::DFA_State::DFA_State(int, zeek::detail::EquivClass const*, zeek::List<zeek::detail::NFA_State*, (zeek::ListOrder)0>*, std::set<int, std::less<int>, std::allocator<int> >*)
zeek::detail::DFA_Machine::StateSetToDFA_State(zeek::List<zeek::detail::NFA_State*, (zeek::ListOrder)0>*, zeek::detail::DFA_State*&, zeek::detail::EquivClass const*)
zeek::detail::DFA_State::ComputeXtion(int, zeek::detail::DFA_Machine*)
zeek::detail::RE_Match_State::Match(unsigned char const*, int, bool, bool, bool)
zeek::detail::RuleMatcher::Match(zeek::detail::RuleEndpointState*, zeek::detail::Rule::PatternType, unsigned char const*, int, bool, bool, bool)
zeek::detail::RuleMatcher::InitEndpoint(zeek::analyzer::Analyzer*, zeek::IP_Hdr const*, int, zeek::detail::RuleEndpointState*, bool, zeek::analyzer::pia::PIA*)
zeek::detail::RuleMatcherState::InitEndpointMatcher(zeek::analyzer::Analyzer*, zeek::IP_Hdr const*, int, bool, zeek::analyzer::pia::PIA*)
zeek::analyzer::pia::PIA::DoMatch(unsigned char const*, int, bool, bool, bool, bool, zeek::IP_Hdr const*)
zeek::analyzer::pia::PIA_TCP::FirstPacket(bool, zeek::IP_Hdr const*)
zeek::packet_analysis::TCP::TCPSessionAdapter::CheckPIA_FirstPacket(bool, zeek::IP_Hdr const*)
zeek::packet_analysis::TCP::TCPSessionAdapter::Process(bool, tcphdr const*, int, std::shared_ptr<zeek::IP_Hdr> const&, unsigned char const*, int)
zeek::packet_analysis::TCP::TCPAnalyzer::DeliverPacket(zeek::Connection*, double, bool, int, zeek::Packet*)
zeek::packet_analysis::IP::IPBasedAnalyzer::AnalyzePacket(unsigned long, unsigned char const*, zeek::Packet*)
zeek::packet_analysis::Analyzer::ForwardPacket(unsigned long, unsigned char const*, zeek::Packet*, unsigned int) const
zeek::packet_analysis::IP::IPAnalyzer::AnalyzePacket(unsigned long, unsigned char const*, zeek::Packet*)
zeek::packet_analysis::Analyzer::ForwardPacket(unsigned long, unsigned char const*, zeek::Packet*, unsigned int) const
zeek::packet_analysis::Analyzer::ForwardPacket(unsigned long, unsigned char const*, zeek::Packet*, unsigned int) const
zeek::packet_analysis::Manager::ProcessPacket(zeek::Packet*)
zeek::run_state::detail::dispatch_packet(zeek::Packet*, zeek::iosource::PktSrc*)
zeek::iosource::PktSrc::Process()
zeek::run_state::detail::run_loop()
main
__libc_start_main
_start `

**Comment by 0xxon** [comment]
On a first glance, this points to a location that is somewhat unlikely to be directly responsible for a crash.

Do you have any more details? Can you reproduce this or does it happen at least from time to time? Do you potentially have any core dumps?

**Comment by 0xxon** [comment]
Small ping - without more details we probably won't be able to do anything here.

**Comment by pbcullen** [comment]
This is a recurring problem, but not reproducible. Unfortunately, we haven't been able to grab a core-dump for this. I'm OK closing this one until we can get more information / reproduce it. Thanks.
