### ISSUE TITLE
Unknown connection errors during DPD

### ISSUE THREAD

**Issue by pbcullen** [zeek/zeek#2477]
We're seeing 100s to 1000s of errors messages like the following on a daily basis:

`Reporter::ERROR unknown connection id in get_conn_transport_proto() (get_conn_transport_proto(DPD::c$id) and [orig_h=XXX.XXX.XXX.XXX orig_p=33176/tcp, resp_h=XXX.XXX.XXX.XXX, resp_p=443/tcp])     /opt/bro/share/zeek/base/frameworks/dpd/./main.zeek, line 82`

In many cases these messages are logged during DPD when a connection id should be readily available, so it seems like something is wrong.
Also, the messages clutter the reporter log. Would it be possible to make these optional, and allow the calling function to handle the "unknown connection id" error?

**Comment by 0xxon** [comment]
This is definitely not supposed to happen - I have never seen this error message being raised before.

Do you have any way for us to reproduce this? Does this happen with life traffic, or with pcaps? Which version of Zeek is this on? Are you using any plugins?

**Comment by awelzel** [comment]
Hmm, there had been a fix from @bbannier for exactly this issue not too long ago with a bit of motivation.

https://github.com/zeek/zeek/pull/2288

> When setting up the DPD info we previously would get the
> transport_proto for the connection with get_conn_transport_proto.
> This function takes a conn_id and would fail fatally if the connection
> for the given ID was unknown. It seems it was possible to run into such
> scenarios when the analyzer_violation event was processed after the
> connection had been cleaned up.

Now, I'm not 100% sure how an analyzer_violation can occur after a connection teardown, but maybe it's something that could've happen through the spicy-plugin holding/passing a connection that's been long been removed?

@pbcullen - Any chance you can get the analyzer IDs involved with those errors? Is that all spicy analyzers?

**Comment by pbcullen** [comment]
This is with Zeek 4.2.2. Several spicy analyzers are in use on the system. This is happening with live traffic, but we cannot take pcaps from the system.

**Comment by 0xxon** [comment]
@awelzel - you are right, this is exactly the fix - and I even merged it and forgot about it.

@pbcullen - this should be fixed in master and the fix will be in 5.1. We should probablyadd this to a 5.0 maintenance release, if this is a common problem.

**Comment by pbcullen** [comment]
I'm seeing this change in 5.0, which is even better! I believe that will resolve this issue. Thanks.
