### ISSUE TITLE
Enhance output `--profile-scripts` to include trace of function calls on the stack

### ISSUE THREAD

**Issue by ynadji** [zeek/zeek#2485]
Currently, `--profile-scripts` shows time and memory usage for individual events and function calls, however, it does not include the stack trace to know _where_ the function was called from. By altering the output to include the stack traces, it would be easy to generate [flamegraphs](https://github.com/brendangregg/FlameGraph#flame-graphs-visualize-profiled-code) of the CPU execution time to better understand the performance profile of large Zeek packages on large PCAPs.

As an example, these [comments in the flamegraph repo](https://github.com/brendangregg/FlameGraph/blob/master/stackcollapse-perf.pl#L14-L26) show the standard output from the Linux `perf` tool, as well as the output of the linked Perl script that is used as input to generate the flamegraph. I think the list of different profiler programs in that repo helps justify altering the Zeek script profiling output to either (1) contain the stack traces to allow generating flamegraphs or (2) output directly in a format that can be used to generate flamegraphs.

**Comment by timwoj** [comment]
> I think the list of different profiler programs in that repo helps justify altering the Zeek script profiling output to either (1) contain the stack traces to allow generating flamegraphs or (2) output directly in a format that can be used to generate flamegraphs.

Considering the output from `--profile-scripts` is a Zeek table, I could see doing (2) and then just adding it as an extra column in the output. You could filter for just that column and pipe it to Flamegraph.

**Comment by timwoj** [comment]
Actually this might be better off as a separate output. The problem is that the existing profiling output combines all calls to a function into a single line that includes the call count, no matter where that function is called from. The output that Flamegraph is expecting is a string for each call stack plus a count for the number of times that stack is called.

**Comment by timwoj** [comment]
Something like this, perhaps, with an extra column on each record:

```
foo2	/Users/tim/Desktop/test.zeek:6	function	1	0.000044	0.000034	0	0	foo2;zeek_init;1
foo	/Users/tim/Desktop/test.zeek:1	function	2	0.000041	0.000000	0	0	foo;zeek_init;foo2;1|foo;zeek_init;foo3;1
foo3	/Users/tim/Desktop/test.zeek:11	function	1	0.000012	0.000007	0	0	foo3;zeek_init;1
```

Each record would contain a pipe-separated list of call stacks plus the number of times that call stack was seen. It works ok for functions, but the stack information isn't there for events so it just outputs an entry with just the event name.

```
ChecksumOffloading::check	/Users/tim/Desktop/projects/zeek-master/scripts/base/misc/find-checksum-offloading.zeek:24	event	2	0.000050	0.000012	0	0	ChecksumOffloading::check;2
```

@ynadji Is that kind of what you were envisioning?

**Comment by ynadji** [comment]
Yeah, I really like the suggested output there. The events limitation makes sense, but at least in cases I've had in the past just having the functions fired by the events would be more than enough to identify hot spots.
