### ISSUE TITLE
"count" underflow inconsistency

### ISSUE THREAD

**Issue by vpax** [zeek/zeek#2486]
If I have a `count` variable `c` with a value of `0`, then `--c` generates a run-time underflow error, but `c = c - 1` doesn't (and instead wraps around).

**Comment by awelzel** [comment]
Any thoughts on the "right" behavior?

Triggering consistent run-time errors for all of them might break a few existing scripts. But seems better than allowing the underflow and potentially causing a large allocation or long loop runtime, etc. I haven't tried, but probably should check for the `++c` and `c = c + 1` overflow behavior as well.

**Comment by vpax** [comment]
How about consistent run-time _warnings_?  That way if there are compatibility issues, they're less painful, but still brought to the script-writer's attention.
