### ISSUE TITLE
Bro 2.5.3 core dumping

### ISSUE THREAD

**Issue by JulianCeaser** [zeek/zeek#249]
I am running Bro-2.5.3 alongside PF_Ring 7.0.0 and CAF 0.15.7. I install all the packages inside a docker container and run it and it works fine for the most part.
However today I deployed on a different system and it was constantly crashing and generating core dumps.
I installed gdb and debuginfo and am seeing the following 
```
"gdb bin/bro core.3140
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-114.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/local/.../bro/bin/bro...done.
[New LWP 3140]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/usr/local/.../bro/bin/bro -i enp4s0f3 -U .status -p broctl -p broctl-live -'.
Program terminated with signal 4, Illegal instruction.
#0  0x00007f965e3d015c in pfring_open () from /usr/local/.../pf_ring/lib/libpcap.so.1
(gdb) bt
#0  0x00007f965e3d015c in pfring_open () from /usr/local/.../pf_ring/lib/libpcap.so.1
#1  0x00007f965e3b2864 in pcap_activate_linux (handle=0x2e35180) at ./pcap-linux.c:1558
#2  0x00007f965e3b7a99 in pcap_activate (p=0x2e35180) at ./pcap.c:787
#3  0x00000000008874ad in iosource::pcap::PcapSource::OpenLive (this=0x23bbce0) at /sources/bro-2.5.3/src/iosource/pcap/Source.cc:129
#4  0x00000000008a1519 in iosource::Manager::Register (this=this@entry=0x23167c0, src=src@entry=0x23bbce0, dont_count=dont_count@entry=false)
    at /sources/bro-2.5.3/src/iosource/Manager.cc:198
#5  0x00000000008a166c in iosource::Manager::Register (this=this@entry=0x23167c0, src=src@entry=0x23bbce0) at /sources/bro-2.5.3/src/iosource/Manager.cc:211
#6  0x00000000008a18e2 in iosource::Manager::OpenPktSrc (this=0x23167c0, path="enp4s0f3", is_live=is_live@entry=true) at /sources/bro-2.5.3/src/iosource/Manager.cc:274
#7  0x0000000000600e41 in net_init (interfaces=..., readfiles=..., writefile=0x0, do_watchdog=do_watchdog@entry=0) at /sources/bro-2.5.3/src/Net.cc:180
#8  0x000000000055d797 in main (argc=<optimized out>, argv=<optimized out>) at /sources/bro-2.5.3/src/main.cc:958"
```
Core Dump file uploaded.

[core.zip](https://github.com/zeek/zeek/files/2778959/core.zip)

**Comment by JulianCeaser** [comment]
I am thinking it might be because the initial system had some CPU instruction set that is absent on the 2nd system. Is there a way to make the bro compilation stop using things like that ?

**Comment by jsiwek** [comment]
No, there's not any such compile options because Bro doesn't have have code that depends on specific/alternate instruction sets.  Technically, there is some use of SSE2 SIMD instructions in Broker, but there's a configure-time check to ensure that works on the build system and also that code isn't actually used at run-time anymore in latest versions of Bro 2.6.x.

That stack you gave is pointing to the crash being within PF_RING, not Bro, so I'm going to close this.  Here's a similar issue you may reference for ideas: https://github.com/ntop/PF_RING/issues/364.  E.g. maybe the build system had linked against mismatched versions of PF_RING.
