### ISSUE TITLE
can't install zeek 

### ISSUE THREAD

**Issue by BodaTomato** [zeek/zeek#2492]
`└─$ sudo apt install zeek        
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 zeek-core : Depends: libc6 (< 2.32) but 2.35-3 is to be installed
E: Unable to correct problems, you have held broken packages.
`

**Comment by 0xxon** [comment]
Hi,

We don't use GitHub issues for support questions. Questions like this are best answered using on either slack or our forum, which is both are frequented by Zeek developers and professional users. You can join here:

Forum: https://community.zeek.org/

Slack: https://zeek.org/community/

 Johanna
