### ISSUE TITLE
Zeek failed to start and reported an error On the operating system ubantu 22.04.1LTS

### ISSUE THREAD

**Issue by liuweiGit** [zeek/zeek#2498]
zeek version is zeek-nightly_5.2.0.orig.tar.gz

The error message is

fatal error in /usr/local/zeek/share/zeek/base/init-bare.zeek, line 1: Failed to initialize kqueue: Invalid argument

**Comment by liuweiGit** [comment]
> Hey - mind providing more details around your environment?
> ![image](https://user-images.githubusercontent.com/19206107/198177134-c640dfc8-57bb-429f-8e94-8d968dc3cb21.png)
> Is this Ubuntu on x86_64? Or arm64?
>  is Ubuntu  x86_64
> Are you possibly running Windows Subsystem for Linux. I've found this issue that seems related, but quite old, so not sure it's still relevant: #842
> is Windows Subsystem for Linux

**Comment by awelzel** [comment]
Thanks for getting back to us.

Searching for the `Linux 4.4.0-19041-Microsoft` kernel on the web indeed indicates this is Ubuntu running under/on-top-of WSL1 which isn't a supported platform.

In #842 [better results with WSL2 were reported](https://github.com/zeek/zeek/issues/842#issuecomment-603749292). If you're able to upgrade your environment, you could give that a try. No guarantees, however, WSL2 isn't really supported either.

I'll close this, but @timwoj or someone else from the team may re-open if we should keep WSL on the radar.

**Comment by liuweiGit** [comment]
> Thanks for getting back to us.
> 
> Searching for the `Linux 4.4.0-19041-Microsoft` kernel on the web indeed indicates this is Ubuntu running under/on-top-of WSL1 which isn't a supported platform.
> 
> In #842 [better results with WSL2 were reported](https://github.com/zeek/zeek/issues/842#issuecomment-603749292). If you're able to upgrade your environment, you could give that a try. No guarantees, however, WSL2 isn't really supported either.
> 
> I'll close this, but @timwoj or someone else from the team may re-open if we should keep WSL on the radar.

Thank you very much
