### ISSUE TITLE
GitHub is not displaying our license correctly

### ISSUE THREAD

**Issue by timwoj** [zeek/zeek#2521]
Both @Neverlord and @jsoref recently brought up that GitHub isn’t properly detecting our license, as shown below.

![Screen Shot 2022-11-01 at 11 49 01 AM](https://user-images.githubusercontent.com/2653616/199314089-be18b7e2-444e-4f00-8c6f-200acb6b5016.png)

If you click on that license line, you get this window:

![Screen Shot 2022-11-01 at 7 56 13 AM](https://user-images.githubusercontent.com/2653616/199314260-b3fde630-b742-4dd5-86fc-b43544a67cb1.png)

I spent a little time tinkering with this in a personal repo, and it looks like the following issues exist:

- The extra line at the bottom of COPYING is confusing it, so it doesn’t see that it’s 3-clause BSD. If I add that line in my personal repo, the same thing happens. If the line isn't there, it's properly detected.
- Having the Copyright line separated onto multiple lines confuses it. If it's all on one line, it's fine.
- COPYING.3rdparty is confusing it, and it’s trying to use all of the licenses in there as well.

I'm not sure what the right answer here is. I like having the two files named closely to the same thing, mostly so they appear next to each other in the file listing. As for the extra line at the bottom of COPYING, does it need to exist? Is it ok to make the copyright line all one line?

**Comment by ckreibich** [comment]
Jeeeez! I futzed too and for me even the difference between enumerating the clause with "1.", "2.", "3." vs "(1)", "(2)", "(3)" breaks detection.

I noticed that renaming `COPYING.3rdparty` to `COPYING-3rdparty` makes it ignore that file.

Github doesn't actually mention that `COPYING` should work, but [Licensee](https://github.com/licensee/licensee), the Gem [apparently](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#detecting-a-license) driving detection, lists it in its guts as something to check. I couldn't find anything in Licensee that would let the repo control detection. Presence of `LICENSE` also doesn't override the others. All of this seems pretty ... rudimentary.

I don't think we have strong rules re. what `COPYING` needs to contain. We can update it to appease Github/Licensee. I'm more concerned that we have that formatting in many of our repos.

**Comment by jsoref** [comment]
I'm willing to file bugs (and post PRs) to the github docs if people feel it's worthwhile. The docs are clearly at least a bit inaccurate in that they don't mention `COPYING`, although they do at least have a pointer to `Licensee`... (I file bugs/PRs to the docs repo fairly often.)

**Comment by jsoref** [comment]
If you have input, https://github.com/licensee/licensee/pull/545 seems like it's a good place for it...

**Comment by timwoj** [comment]
Good find on licensee. I installed the gem and tinkered with it a bit. Looking at their code, they set a confidence threshold of 98% to be considered the correct one.

Our stock COPYING file:
    BSD-3-Clause-Clear similarity:  77.02%
    BSD-4-Clause similarity:        76.13%
    BSD-3-Clause similarity:        70.45%

The content of our license text is the same, but the formatting is a little different from the one that GitHub provides with a new repo. Copying/pasting the license text from the stock 3-Clause BSD license from GitHub but leaving behind the footer line that I mentioned:
    BSD-3-Clause-Clear similarity:  86.64%
    BSD-4-Clause similarity:        85.61%
    BSD-3-Clause similarity:        78.55%

Converting the copyright line to be all one line instead of 4, and putting All Rights Reserved on a separate line:
    BSD-3-Clause similarity:        91.19%
    BSD-4-Clause similarity:        90.77%
    BSD-3-Clause-Clear similarity:  89.47%

Removing the footer line:
  Content hash:  a961b19cc6921d510e29a13b0ba1a826fcffe41c
  Attribution:   Copyright (c) 1995-2021, The Regents of the University of California through the Lawrence Berkeley National Laboratory and the International Computer Science Institute.
  Confidence:    100.00%
  Matcher:       Licensee::Matchers::Exact
  License:       BSD-3-Clause

**Comment by ckreibich** [comment]
Thanks Tim! It seems there are a few different levels of license rendering in Github — for Zeek, it's currently really bad ("Unknown, Unknown licenses found"). For some of our other projects it at least points at the file, but doesn't label it (see e.g. Broker — "View license"). In the best case it's able to spell out what the license actually is.

The second case ("View license") seems pretty common. For example, llvm and cpython both show it. I think it'd be perfectly fine if that's true for us too. This is already the case for most of our submodules, thankfully.

So let's figure out what we need to do for Zeek to get at least to that state. I think it means we need to rename `COPYING.3rdparty` so Licensee no longer sees it (though we can hopfully eventually use licensee/licensee#545 assuming Github adopts it — thx @jsoref!). At that point I'm up for whatever `COPYING` changes get us from "Unknown" at least to "View license".

Does that make sense to folks?

**Comment by timwoj** [comment]
With the changes in the above PR, we now show this on the front page:

<img width="163" alt="Screenshot 2023-01-03 at 12 16 05 PM" src="https://user-images.githubusercontent.com/2653616/210425801-97ea52de-5336-4640-8b64-404765966a43.png">

I don't think we can do anything more without actual changes to our license file and I think we've decided not to do those. I'm good with closing this now, unless anyone objects.

**Comment by ckreibich** [comment]
Sounds good to me, Tim.
