### ISSUE TITLE
NTLM feature + potential bug?

### ISSUE THREAD

**Issue by nadavkluger** [zeek/zeek#2530]
Hello!
I made [these](https://github.com/zeek/zeek/compare/master...nadavkluger:zeek:topic/nadavk/ntlm?expand=1) changes and when I run it on [example.pcapng](https://github.com/zeek/zeek/files/9923870/mb.txt)
(Change file name extension after download) I get different result than I should
![image](https://user-images.githubusercontent.com/27895842/199592559-6851bbad-bbf0-4cc1-8e5c-643f59d63d21.png)
Here is a good script to find the wanted outcome https://github.com/mlgualtieri/NTLMRawUnHide

Besides this problem, I noticed `proc_ntlm_challenge` in `ntlm-analyzer.pac` is called only 3 times for this pcap (added printf) but it should be called way more times. There are many more type II messages in this pcap.

For anyone less fluent in the NTLM protocol the [MS-NLMP].pdf on Microsoft's website is the ultimate reference for details

**Comment by timwoj** [comment]
Did you push the changes to your fork? Github is showing that it's the same as our current master branch.

**Comment by nadavkluger** [comment]
Hmm.. Yes I did. So what is the correct format to show the diff? Upload the files here? (I do not have permissions to open a branch)

**Comment by nadavkluger** [comment]
Update: It turns out it does not work for specific protocols. For instance on [this pcap](https://wiki.wireshark.org/uploads/__moin_import__/attachments/SMB2/smb-on-windows-10.pcapng) it works :)

It seems like the problem is in calling `forward_gssapi` (in smb-gssapi.pac) from `SMB1_session_setup_andx_response_ntlm` ( in smb1-com-session-setup-andx.pac)

Also probably `DCE_RPC_Bind_Ack` misses the security blob :(

**Comment by timwoj** [comment]
Fixed via the above PR.
