### ISSUE TITLE
Why does zeek not analyze mirror traffic?

### ISSUE THREAD

**Issue by gdianq** [zeek/zeek#2533]
Hello!
I'm new to zeek and recently ran into a problem I couldn't solve.
I installed zeek, PF-RING, and AF_PACKET on a superior server,When I use zeek to analyze my local traffic in real time, it works.
This is the content of notice.log file.
![image](https://user-images.githubusercontent.com/81155906/199638926-be33e8e4-938d-466f-bbdc-e24fa4987bbd.png)
zeek did analyze the burst traffic I was generating.
However, when I mirrored the traffic of the other two network segments, zeek could not analyze the burst traffic. At first, I thought that the traffic was too large. However, I only mirrored the traffic of one network segment and zeek could not analyze the burst traffic.
This is the content of the notice.log file for the connection image port.
![image](https://user-images.githubusercontent.com/81155906/199639684-a8602e8c-a9be-452f-bede-9a694b17be5f.png)
What confused me was that I could see ssh traffic I was generating in ssh.log.
![image](https://user-images.githubusercontent.com/81155906/199640131-96df1da1-251e-428c-885e-c68f412007f1.png)

**Comment by gdianq** [comment]
I also tried to connect the mirrored traffic directly to my physical network card and found that the problem still occurred, as did the offline packets.

**Comment by awelzel** [comment]
Hi,

We don't use GitHub issues for support questions. Questions like this are best answered using on either slack or our forum, which is both are frequented by Zeek developers and professional users. You can join here:

Forum: https://community.zeek.org/

Slack: https://zeek.org/community/

Arne
