### ISSUE TITLE
Update DNS type strings to match correct mappings

### ISSUE THREAD

**Issue by munty-corelight** [zeek/zeek#2539]
30 should be NXT not EID
    31 should be EID not NIMLOC
    32 should be NIMLOC not NB. NB was originally defined in RFC 1002, but it was later made obsolete and replaced by NIMLOC. Similarly, NBSTAT was originally defined at 33, but was replaced by SRV.

**Comment by timwoj** [comment]
Closed by https://github.com/zeek/zeek/pull/2531
