### ISSUE TITLE
ContentLine::SupressWeirds is spelled incorrectly

### ISSUE THREAD

**Issue by jsoref** [zeek/zeek#2547]
`ContentLine` is unfortunately a class used by a number of other analyzers, so we can't rename this without a deprecation cycle. Can you open an issue for this and I'll take care of it?

_Originally posted by @timwoj in https://github.com/zeek/zeek/pull/2544#discussion_r1015755582_

**Comment by timwoj** [comment]
I fixed the title. This will need to go through a deprecation cycle to fix correctly.
