### ISSUE TITLE
Windows: Investigate performance differences with using `unordered_map` for `PortVal` caching

### ISSUE THREAD

**Issue by timwoj** [zeek/zeek#2571]
From https://github.com/zeek/zeek/pull/2518#pullrequestreview-1163245371:

> The original std::array version appears to run twice as fast as the std::unordered_map/uint32_t version still. It is a microbenchmark, but PortVal lookups aren't exactly uncommon, so we may at least keep that in mind.
>
> Edit: Could consider making this runtime/compiletime configurable if it matters as a knob for memory vs performance.

**Comment by awelzel** [comment]
Attaching a pcap with 1mio syn packets from random source ports to destinations 443,80,22 generated with below following trafgen script. It has a bursty 10kpps rate:

[1mio-syn-packets.pcap.gz](https://github.com/zeek/zeek/files/10758115/1mio-syn-packets.pcap.gz)

Running this through `perf` with only base/protocols/conn does show `ValManager::Port()` among the hottest functions with 2.7% (and the second hottest Zeek one after `BubbleDown()`).
```
$ time taskset -c 1 perf record -g zeek -b -Cr /home/pcaps/1mio-syn-packets.pcap base/protocols/conn Log::default_writer=Log::WRITER_NONE
```
![Screenshot-20230216-172602](https://user-images.githubusercontent.com/2100509/219427041-ecc51432-4193-430f-b5a6-1df5b06861af.png)

Patching back "a" pre-alloced version makes the 2.7% overhead go down to 0.1% at the cost of pre-allocating all these ports which might be a few megabytes, but on "large systems" shouldn't be an issue. The test is pretty artificial, so it might be interesting to hear if this shows in live production environments.

Could see it as a runtime or compile time option. For large, long running systems pre-allocation makes sense. For tests, constrained systems, maybe less so.

That's the patch I had used - not pretty, but for reference.
```
--- a/src/Val.cc
+++ b/src/Val.cc
@@ -3951,6 +3951,8 @@ unsigned int Val::Footprint(std::unordered_set<const Val*>* analyzed_vals) const
        return fp;
        }
 
+#define PRE_ALLOC 1
+
 ValManager::ValManager()
        {
        empty_string = make_intrusive<StringVal>("");
@@ -3962,6 +3964,13 @@ ValManager::ValManager()
 
        for ( auto i = 0u; i < PREALLOCATED_INTS; ++i )
                ints[i] = Val::MakeInt(PREALLOCATED_INT_LOWEST + i);
+
+#if PRE_ALLOC
+       for ( int space = 0; space < NUM_PORT_SPACES; space++ )
+               for ( int port_num = 0; port_num < 65536; port_num++ )
+                       all_ports[(space << 16) + port_num] = make_intrusive<PortVal>(
+                               PortVal::Mask(port_num, TransportProto(space)));
+#endif
        }
 
 const PortValPtr& ValManager::Port(uint32_t port_num, TransportProto port_type)
@@ -3972,11 +3981,15 @@ const PortValPtr& ValManager::Port(uint32_t port_num, TransportProto port_type)
                port_num = 0;
                }
 
+#if PRE_ALLOC
+       return all_ports[(int(port_type) << 16) + port_num];
+#else
        auto port_masked = PortVal::Mask(port_num, port_type);
        if ( ports.count(port_masked) == 0 )
                ports.insert({port_masked, make_intrusive<PortVal>(port_masked)});
 
        return ports[port_masked];
+#endif
        }
 
 const PortValPtr& ValManager::Port(uint32_t port_num)
diff --git a/src/Val.h b/src/Val.h
index 5db5368b6..04bbfd4fa 100644
--- a/src/Val.h
+++ b/src/Val.h
@@ -340,6 +340,7 @@ public:
 
 private:
        std::unordered_map<uint32_t, PortValPtr> ports;
+       std::array<PortValPtr, NUM_PORT_SPACES * 65536> all_ports;
        std::array<ValPtr, PREALLOCATED_COUNTS> counts;
        std::array<ValPtr, PREALLOCATED_INTS> ints;
        StringValPtr empty_string;

```

Trafgen script
```
# $ trafgen -n 1000000 -i syn.cfg -o /home/pcaps/1mio-syn-packets.pcap
{
    eth(saddr=aa:bb:cc:dd:ee:ff, saddr=dinc()),
    ipv4(saddr=drnd(), daddr=drnd(), ttl=32),
    tcp(sport=drnd(1024, 16123), dport=443, syn)
}
{
    eth(saddr=aa:bb:cc:dd:ee:ff, saddr=dinc()),
    ipv4(saddr=drnd(), daddr=drnd(), ttl=32),
    tcp(sport=drnd(1024, 16123), dport=80, syn)
}
{
    eth(saddr=aa:bb:cc:dd:ee:ff, saddr=dinc()),
    ipv4(saddr=drnd(), daddr=drnd(), ttl=32),
    tcp(sport=drnd(1024, 16123), dport=22, syn)
}
```

**Comment by timwoj** [comment]
> Could see it as a runtime or compile time option. For large, long running systems pre-allocation makes sense. For tests, constrained systems, maybe less so.

I could definitely see it as a compile/configure-time option. `--low-memory`, maybe. The documentation for it just has to be very explicit about the tradeoffs.

**Comment by JustinAzoff** [comment]
Yeah.. I think the change to remove the preallocation was well intentioned, but misguided.  Any production system will end  up seeing a good chunk of the port range after a short amount of time.

It wouldn't even really be --low-memory, it would "lower memory if you only run on a small pcap for a short period of time".  With the way maps are allocated and grow over time, it may use more memory in the long run.

I looked at some days on my home network and I regularly have 45,000 unique ports over the day. still only 1/3 of the total set, but that 45,000 ports in the map likely has some reserved space for growth..  At best i'd be saving something like 10MB.
