### ISSUE TITLE
Windows: Live packet capture failures

### ISSUE THREAD

**Issue by timwoj** [zeek/zeek#2575]
I ran a script with zeek that simply calls the `Pcap::findalldevs()` bif during `zeek_init`. It returned an empty set of devices. We might need to switch from libpcap to npcap or winpcap instead.

**Comment by timwoj** [comment]
It looks like libpcap/winpcap are pretty non-functional on Windows other than for reading files. https://npcap.com/ appears to be the library nmap and Wireshark are using, but it's a non-free license.

**Comment by Neverlord** [comment]
> The free version of Npcap may be used (but not externally redistributed) on up to 5 systems ([free license details](https://github.com/nmap/npcap/blob/master/LICENSE)). It may also be used on unlimited systems where it is only used with [Nmap](https://nmap.org/), [Wireshark](https://www.wireshark.org/), and/or [Microsoft Defender for Identity](https://docs.microsoft.com/en-us/defender-for-identity/what-is).

How does that even work for Wireshark? I though they're using the GPL. How can they rely on a non-free library?

Anyways, since npcap seems to grant license exceptions to OSS projects, maybe we could just ask them?

**Comment by timwoj** [comment]
> How does that even work for Wireshark? I though they're using the GPL. How can they rely on a non-free library?

I have no idea. You have the option to not install it while installing Wireshark, but that just means that you can't read live traffic. Maybe that's the workaround?

> Anyways, since npcap seems to grant license exceptions to OSS projects, maybe we could just ask them?

Worth a shot, I suppose. As of right now we're not intending to distribute a binary Windows installer, so we might not have to worry about the licensing at all? I legitimately don't know how that works.

**Comment by ckreibich** [comment]
npcap still [implements the regular pcap API](https://npcap.com/vs-winpcap.html), right? If so, we wouldn't really have to switch any code, but perhaps warn if we can tell that on Windows we're not dealing with npcap. Is that what you mean Tim?

**Comment by timwoj** [comment]
I believe it depends on how you install it. I think you can install it in a way that isn't compatible, or at least there was an option during installation for that when I last did it. I'll look into that this week.

**Comment by timwoj** [comment]
We made some strides in Slack today with getting this work, to the point of it reading from a network interface and creating logs. There's work to do to make it more generic so everything will still build and work on other platforms, but the work starts at https://zeekorg.slack.com/archives/CSZBXF6TH/p1671718031812489.

Thanks to Gavin Li for helping to troubleshoot this.

**Comment by timwoj** [comment]
The above PR fixes problems with linking against Winpcap/Npcap, so at least Zeek can find the interfaces and start capturing data. After a few minutes of capture, Zeek fails with the following:

```
[broker/ERROR] 2022-12-23T14:29:09.945 exception: POLLRDHUP: cannot read from closed pipe
1671826522.943000 received termination signal
1671826522.943000 7761 packets received on interface \Device\NPF_{EE0453E2-10F1-426C-8B99-CD460FDD9188}, 0 (0.00%) dropped, 3689 (47.53%) not processed
*** unhandled exception: [id: 4, name: broker.core, exception typeid: class%20std.runtime_error]: wrong number of bytes written to the pipe
```

**Comment by timwoj** [comment]
Live packet capture seems fine now with npcap. The above error was also reported in https://github.com/zeek/zeek/issues/2580, so I'm going to close this one.
