### ISSUE TITLE
when kali(2022.1) install zeek(for debain11) ouccer this problem

### ISSUE THREAD

**Issue by jiaxinga** [zeek/zeek#2576]
The following packages have unmet dependencies:
 zeek-core : Depends: libc6 (< 2.32) but 2.35-4 is to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by B0073D** [comment]
Also seeing the same issue. (was actually about to file a bug).

Would a Debian bug be a better place for this?

**Comment by awelzel** [comment]
@jiaxinga / @B0073D - you didn't state, but I assume you're using the openSUSE Build Service Binary Zeek Packages?

A better place to report those errors is community.zeek.org. In fact, there's the following thread describing the same issue and potential solutions (building from Slack or trying debian-testing binaries):

https://community.zeek.org/t/installation-issues-on-kali-linux/6702

From @0xxon in the thread above:
> As mentioned above - we don’t support Kali linux for binary installations. In the past I have heard of people having success installing the Debian testing binaries - but only these, no other versions.

Please continue discussion in a new thread on community.zeek.org or follow-up on the existing thread.

Closing this issue.
