### ISSUE TITLE
broctl looks like an APT

### ISSUE THREAD

**Issue by mpurzynski** [zeek/zeek#259]
While doing Threat Hunting I saw an interesting string in our Audit Execve logs, only on my NSM fleet

`python
/usr/bin/python -c import zlib,base64; exec(zlib.decompress(base64.b64decode(beJxlU8Fu2zAMPUdfIehSGdOMJtgpgI459DCsh+7kGYFr060KWzIke05Q9N9HSvaaNAFiW+TjI/lIMdMPzo/cBRXO+J+eB+9qCPhpXmzVqQAd1KN6C86yp4efh1+/n/R2d89YAy2fZcj2bIOReRgbN4357M0I0sPg0cW/cfHHiuwK0XZTeJVZIoAT1Me6b4KkB3ENuijZpnWeG4U2biwHO/XgK+RdQZvRn+m1oWL1Z9H5oxvAEkylbFe+h8cDmcH7r2aeRbK8GjC8kdIo8mZkhVMNw8gP8WWc5VXgEHPPhJNbdXeHrF5Chj+28TBO3vKBsVkKD1Vzxv5r1/eVbQL1lnTNq67yvVwUzRg13BkL1C8qiOolxYzNiYRcSjTOAumJ6VfGtWSaT965CpUkLFbCqIWgLxReQrCcvjn21aDfP1h78RV0gBEnk8SncKom0mBGp9+FaU5ibxQXZBR7euIhSS32RZkOKPBymCszGvsi9rsPnGlMVVDQsguldsUaXd4AkGYFECMClrq/UNzaUyQRhnwaGtoceRGjLnAk1PxqOuAIxi69OqqjTkufp5dEj8J2ihLHS9q0cSs9LQGyDbhlLsQpITJvkcs6mant/e4HLZBpeULFpVl6bJtynZyLzriAtbMo1wQMD9iTXvtCNFqoGw+9+wuYh/DoLv5LXH7X25Tt2hyzXhLHKxMxcYjEHMZqnIKOslAg7kBsTT8Lkb85E2/U56TitcBLdOONYyIvXo1oo30plUz8CoNVlJw0l3Gb8W78A22ieEg=)))`

I jumped in my seat and after some quick exchange got it decoded

```python
import os,sys,subprocess,signal,select,json
TIMEOUT=120

def w(s):
	sys.stdout.write(repr(s) + "\n")
	sys.stdout.flush()

def exec_cmds(cmds):
	p=[]
	for i,cmd in enumerate(cmds):
		try:
			proc=subprocess.Popen(cmd,stdout=subprocess.PIPE,stderr=subprocess.PIPE )
			p.append((i,proc))
		except Exception as e:
			w((i,(1,'',str(e))))
	return p

w("ready")
commands=[]
signal.alarm(TIMEOUT)
for line in iter(sys.stdin.readline,"done\n"):
	commands.append(json.loads(line))

procs=exec_cmds(commands)
cmd_map={}
fd_map={}
fds=set()
for i,proc in procs:
	o={"idx":i, "proc":proc, "stdout":[], "stderr":[], "waiting":2}
	fd_map[proc.stdout]=o["stdout"]
	fd_map[proc.stderr]=o["stderr"]
	cmd_map[proc.stdout]=o
	cmd_map[proc.stderr]=o
	fds.update((proc.stdout,proc.stderr))

while fds:
	r,_,_=select.select(fds,[],[])
	for fd in r:
		output=os.read(fd.fileno(),1024)
		if output:
			fd_map[fd].append(output)
			continue

		cmd=cmd_map[fd]
		fds.remove(fd)
		cmd["waiting"]-=1
		if cmd["waiting"]:
			continue

		proc=cmd["proc"]
		status=proc.wait()
		out=b"".join(cmd["stdout"])
		err=b"".join(cmd["stderr"])
		w((cmd["idx"],(status,out,err)))

w("done")
```

What I received was made me even more suspicious than before. I understand that this is part of the broctl, but does it really have to be this way?

**Comment by jsiwek** [comment]
Not sure.  A quick suggestion would be to change the `python -c` to insert a no-op string like "This is BroControl" and also include a comment in the decoded python script of the same nature.  There's nothing stopping an adversary from mimicking such a comment string to divert skepticism, but I guess it may still help initial impression/research?

**Comment by mpurzynski** [comment]
Indeed, some form of identification would be nice. Any threat actor could use that, but at least it will not raise the blood pressure in the middle of the night.

The Zeek's roadmap shows broctl going away, anyway, so feel free to do whatever you feel like doing.

**Comment by JustinAzoff** [comment]
I'm sorry for writing that :-)

Older broctl opened one ssh connection for each remote command it would run, so if you had 30 workers a `broctl start` would run 30 ssh commands like `ssh node ... run-bro`

I had originally wanted to use ssh sessions to multiplex the commands over a single connection, but it turns out the sshd option 'MaxSessions' defaults to 10 so that would have required everyone to edit sshd_config to support more than 10 workers.  Plan B was the multiplexer, and since there was no easy way to tell if the remote node had been setup yet, the program was just serialized onto the command line so it would always work.

**Comment by mmguero** [comment]
+1

**Comment by mmguero** [comment]
FYI here's what this looks like as an [auditbeat](https://www.elastic.co/products/beats/auditbeat) event:

```
{
  "_index": "auditbeat-6.8.3-2019.12.11",
  "_type": "doc",
  "_id": "gWbO9m4BYdZ77mbfly0o",
  "_version": 1,
  "_score": null,
  "_source": {
    "@timestamp": "2019-12-11T21:12:43.816Z",
    "event": {
      "module": "auditd",
      "category": "audit-rule",
      "type": "syscall",
      "action": "opened-file"
    },
    "beat": {
      "name": "sensor2",
      "hostname": "sensor2",
      "version": "6.8.3"
    },
    "host": {
      "name": "sensor2"
    },
    "user": {
      "gid": "1000",
      "selinux": {
        "user": "=unconfined"
      },
      "suid": "1000",
      "fsgid": "1000",
      "uid": "1000",
      "auid": "1000",
      "egid": "1000",
      "fsuid": "1000",
      "sgid": "1000",
      "euid": "1000",
      "name_map": {
        "fsgid": "sensor",
        "sgid": "sensor",
        "suid": "sensor",
        "uid": "sensor",
        "auid": "sensor",
        "egid": "sensor",
        "euid": "sensor",
        "fsuid": "sensor",
        "gid": "sensor"
      }
    },
    "process": {
      "pid": "15014",
      "ppid": "14996",
      "title": "/bin/python -c import zlib,base64; exec(zlib.decompress(base64.b64decode(b\"eJxlU01v2zAMPUe/QvClEqYZTbCTAR1z6GFYD93JMwLXplsVtmRI9",
      "name": "python",
      "exe": "/usr/bin/python2.7"
    },
    "file": {
      "group": "root",
      "path": "/usr/lib/python2.7/json/",
      "device": "00:00",
      "inode": "788758",
      "mode": "0755",
      "uid": "0",
      "gid": "0",
      "owner": "root"
    },
    "tags": [
      "access"
    ],
    "auditd": {
      "session": "13398",
      "data": {
        "a2": "2c1",
        "syscall": "openat",
        "a1": "55fc9d4f2ad0",
        "a3": "81a4",
        "a0": "ffffff9c",
        "arch": "x86_64",
        "exit": "EACCES",
        "tty": "(none)"
      },
      "summary": {
        "actor": {
          "primary": "sensor",
          "secondary": "sensor"
        },
        "object": {
          "primary": "/usr/lib/python2.7/json/",
          "type": "file"
        },
        "how": "python"
      },
      "paths": [
        {
          "nametype": "PARENT",
          "ouid": "0",
          "cap_fp": "0000000000000000",
          "cap_fver": "0",
          "dev": "fe:00",
          "inode": "788758",
          "mode": "040755",
          "rdev": "00:00",
          "cap_fe": "0",
          "cap_fi": "0000000000000000",
          "item": "0",
          "name": "/usr/lib/python2.7/json/",
          "ogid": "0"
        }
      ],
      "sequence": 50473233,
      "result": "fail"
    }
  },
  "fields": {
    "@timestamp": [
      "2019-12-11T21:12:43.816Z"
    ]
  },
  "highlight": {
    "host.name": [
      "@kibana-highlighted-field@sensor2@/kibana-highlighted-field@"
    ]
  },
  "sort": [
    1576098763816
  ]
}```

The issue is there's really nothing in here that indicates to me that this is zeekctl. It makes this very hard to filter out as "noise" as the same technique could be used by an attacker. :/

**Comment by jsiwek** [comment]
Any help with suggesting and testing of potential patches is very welcome -- still think the easy thing to do is insert some no-op string so you end up seeing `python -c '"Do not worry, this is ZeekControl"; import zlib,base64; ...'` and then also have the decoded string come out with a comment at the top like `# This script is used by ZeekControl`

**Comment by JustinAzoff** [comment]
Could probably change things to just write the multiplexer onto the remote system as a normal file.  The only tricky part is the initial bootstrapping.

**Comment by rsmmr** [comment]
ZeekControl will eventually be replaced by the supervisor, so doesn't seem worth any major changes, and not sure the insert-a-string solution would help much given the lack of follow-up here.
