### ISSUE TITLE
Failed Intel file upload response

### ISSUE THREAD

**Issue by jlagermann** [zeek/zeek#2613]
I'm testing a new source of indicators for Zeek and when it tries to upload the intel file, I get the following error
```
{
  "diagnostics": "Value '' is not a valid enum.\n  Value '' is not a valid enum.\n  Value '' is not a valid enum.\n  Value '' is not a valid enum.\n  Value '' is not a valid enum.\n  Value '' is not a valid enum.",
  "title": "Intelligence data could not be installed",
  "description": "Intelligence data failed validation"
}
```
It turns out, the source added a new indicator type called "BitcoinAddress" that does not have a map to a Zeek indicator type so it just gets left blank in the intel file.

If the output would have said something like, "missing indicator type on line 22", it would have saved me hours of troubleshooting.

Can we get better output for "invalid enum"?

**Comment by awelzel** [comment]
> If the output would have said something like, "missing indicator type on line 22", it would have saved me hours of troubleshooting.

`Value '' is not a valid enum.` does say the missing part (albeit a bit cryptic). #2619 will add the missing line information that should allow to find the problematic lines faster.
