### ISSUE TITLE
how to specify the cluster type when setup zeek cluster-in-a-box  with PF_RING 

### ISSUE THREAD

**Issue by frank-s-liu** [zeek/zeek#2614]
I just try to setup zeek cluster-in-a-box  with PF_RING.
following the document, it seems working now.
but I don't know how it working.
PF_RING documents says one can use some commands looks like "pfcount -i eth1 -c 10 -H 5" to do loadbalance
and it also gives an API "int pfring_set_cluster(pfring *ring, u_int clusterId, cluster_type the_type)
both of them need to give a special parameter about "cluster-type"
but I don't found any comments in document about cluster info(cluster id and type)

**Comment by awelzel** [comment]
Hi,

We don't use GitHub issues for support questions. Questions like this are best answered using on either slack or our forum, which is both are frequented by Zeek developers and professional users. You can join here:

Forum: https://community.zeek.org/

Slack: https://zeek.org/community/

This also looks very specific to PF_RING specific, so you may want to look at the external [PF_RING plugin](https://github.com/ntop/bro-pf_ring/blob/master/src/PF_RING.cc#L6) for input or the [PF_RING Cluster documentation](https://www.ntop.org/guides/pf_ring/rss.html#pf-ring-cluster-kernel)

Arne
