### ISSUE TITLE
Custom Zeek script to merge conn.log and weird.log

### ISSUE THREAD

**Issue by aswinjose89** [zeek/zeek#2615]
I'm writing zeek custom script at local.zeek file based on our needs, How to combine conn.log and weird.log into one file via zeek script? i can able to combine conn.log and dns.log by accessing c$dns$query..

![image](https://user-images.githubusercontent.com/6614386/203742164-eb98428f-708f-4430-bf09-a96f083bb85b.png)

**Comment by awelzel** [comment]
I see you posted on zeekorg.slack.com as well: https://zeekorg.slack.com/archives/CSZBXF6TH/p1669280593999349

I'm closing this issue. Another place to ask scripting questions would be community.zeek.org.
