### ISSUE TITLE
release archive does not include submodules (e.g. cmake)

### ISSUE THREAD

**Issue by thinrope** [zeek/zeek#263]
I have been trying to test this and realized that releases omit the submodules...
So:
````
tmp $ cd /tmp/ && wget -q https://github.com/zeek/zeek/archive/v2.6.1.tar.gz -O -|tar xz
tmp $ cd zeek-2.6.1/
zeek-2.6.1 $ ./configure
Build Directory : build
Source Directory: /tmp/zeek-2.6.1
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:7 (include):
  include could not find load file:

    cmake/CommonCMakeConfig.cmake


CMake Error at CMakeLists.txt:78 (include):
  include could not find load file:

    FindRequiredPackage


-- Found sed: /bin/sed
CMake Error at CMakeLists.txt:90 (FindRequiredPackage):
  Unknown CMake command "FindRequiredPackage".


-- Configuring incomplete, errors occurred!
See also "/tmp/zeek-2.6.1/build/CMakeFiles/CMakeOutput.log".
zeek-2.6.1 $ ls -ls cmake/
total 0
````

As such this is quite useless at the moment...
What are your thoughts on that?

**Comment by jsiwek** [comment]
The official place to get releases is:

https://www.zeek.org/download/index.html

The releases provided by GitHub are automatic and they do not include source code from submodules.  We can't currently configure them to or even disable them entirely.  Others have complained to GitHub about this deficiency already.

The best I can do is overwrite the automatic release with my own and manually attach the full source code tarfiles (which I've just done for v2.6.1):

https://github.com/zeek/zeek/releases/tag/v2.6.1

Note that it still includes its own "Source code" zip and tar.gz links which won't contain submodule code, but at least the first tar.gz in the list is the full/correct one.  If you find/know any better way to configure this, just let me know.

**Comment by thinrope** [comment]
OK, I am still trying to grasp the bro->zeek rename and was looking for some tar.bz that had zeek in the name :-D 
Current workaround is fine for me, hopefully we'll have a new release with mostly all renamed. As for the github releases - yup, known PITA... other projects have scripted releases (a separate "make release" that does everything needed and make the tar.bz).

**Comment by jsiwek** [comment]
> I am still trying to grasp the bro->zeek rename and was looking for some tar.bz that had zeek in the name

There's no official release named 'zeek' yet and all 2.6.x will likely use 'bro'.
