### ISSUE TITLE
Segmentation fault with --profile-scripts command line option

### ISSUE THREAD

**Issue by DocFore** [zeek/zeek#2645]
On Ubuntu 22.04 with zeek 5.1.1.

The following command creates a segmentation fault.
`zeek -r exercise-traffic.pcap --profile-scripts=/opt/zeek/share/zeek/site/local.zeek`

The URL for the file is https://old.zeek.org/static/traces/exercise-traffic.pcap.

cc @catenacyber

**Comment by vpax** [comment]
Yep.  I'll put it on my list for my next maintenance run in early January.

**Comment by DocFore** [comment]
Indeed, there is no segmentation fault when starting the command with sudo.

**Comment by vpax** [comment]
> Indeed, there is no segmentation fault when starting the command with sudo.

But if you did that, you just stepped on your `local.zeek`!

**Comment by DocFore** [comment]
Ok, i guess I did something wrong and it explains why I didn't have any segmentation fault 😅
