### ISSUE TITLE
Zeek Intelligence Framework - Intel::FILE_NAME not matching

### ISSUE THREAD

**Issue by tim-acki** [zeek/zeek#2647]
I am using Zeek v5.0.2 and have experimented with the Intel framework. I got all Intel type to match and produce an entry in intel.log and notice.log except for the Intel::FILE_NAME. 
I send a file test.exe via HTTP to a HTTP server for testing. In my http.log everything is fine and the orig_filenames field contains the value test.exe. Still, the file name does not result in an Intel match. I also tested the Intel::FILE_HASH by providing the hash of my test file and in this case a match is produced for the file hash.
Are there any ideas on how tho get Intel::FILE_NAME to match with HTTP or could this be a bug?

**Comment by awelzel** [comment]
> Are there any ideas on how tho get Intel::FILE_NAME to match with HTTP or could this be a bug?

Yeah, that looks like a bug. Thanks for the detailed report, @tim-acki .

It seems what happens is that `seen/file-names.zeek` uses `file_new` and the `f$info$filename` record. But for HTTP, that is only populated during `file_over_new_connection`. I think we can just switch `seen/file-names.zeek` over to `file_over_new_connection` and accept the "same file over multiple connection triggers Intel::seen more than once", which isn't all that bad.
