### ISSUE TITLE
Error messages for type clashes in iteration loops lack line numbers

### ISSUE THREAD

**Issue by vpax** [zeek/zeek#2669]
For the following input:
```
global a: table[count] of count;
global b: table[int] of int;

event zeek_init()
        {
        for ( i, x in a ) print i;
        for ( i, x in b ) print i;
        }
```
Zeek correctly generates errors about the type clashes, but they lack line numbers:
```
error in count and int: type clash in iteration (count and int)
error in count and int: type clash in iteration (count and int)
```
making them difficult to find in large scripts.

**Comment by timwoj** [comment]
Looks like the type object generated for the loop var here has no location data in it:

https://github.com/zeek/zeek/blob/master/src/Stmt.cc#L1243-L1253

Just passing down `lv`'s location info into `Error` doesn't help because `obj2` also has a location value in it that's not useful. This is probably going to have to be fixed down in the parser to set proper locations on these types.

**Comment by timwoj** [comment]
Staring at this a bit more, shouldn't `i` and `x` be out of scope for the second for-loop, thus negating the error message altogether?

**Comment by vpax** [comment]
> Staring at this a bit more, shouldn't `i` and `x` be out of scope for the second for-loop, thus negating the error message altogether?

Perhaps, but the same problem occurs without the reuse, e.g.:
```
global a: table[count] of count;

event zeek_init()
        {
        local d: double;
        for ( d in a )
                print "inside the loop";
        }
```

**Comment by timwoj** [comment]
Yeah, I dug a bit further into it and it gets mired in how we build that error message in `Obj::Error`. `ind_type` there is the global `int` type. It has a location attached to it, but it's all zeroes other than the name. Cloning the type and modifying the location causes output that doesn't look any better (it replaces the first `int` with the location info). Basically we're tricking `Obj::DoMsg` into using the filename as the type name in the output, which isn't great.

**Comment by vpax** [comment]
FYI, the following makes the messages less-sucky and basically ok IMHO:

```
diff --git a/src/Stmt.cc b/src/Stmt.cc
index 0d5306cf9..e3448272b 100644
--- a/src/Stmt.cc
+++ b/src/Stmt.cc
@@ -1249,7 +1249,7 @@ ForStmt::ForStmt(IDPList* arg_loop_vars, ExprPtr loop_expr)
 			else if ( lvt )
 				{
 				if ( ! same_type(lvt, ind_type) )
-					lvt->Error("type clash in iteration", ind_type.get());
+					e->Error("type clash in iteration", lvt.get());
 				}
 
 			else
@@ -1341,7 +1341,7 @@ ForStmt::ForStmt(IDPList* arg_loop_vars, ExprPtr loop_expr, IDPtr val_var)
 	else if ( value_var->GetType() )
 		{
 		if ( ! same_type(value_var->GetType(), yield_type) )
-			value_var->GetType()->Error("type clash in iteration", yield_type.get());
+			value_var->Error("type clash in iteration", yield_type.get());
 		}
 	else
 		add_local(value_var, yield_type, INIT_NONE, nullptr, nullptr, VAR_REGULAR);
```

**Comment by timwoj** [comment]
Yeah, I had tried that already, but was trying to keep the "count and int" part completely intact. In the end, if you're content with that output then I'll open a PR for it. You're the one who reported it 😃

**Comment by vpax** [comment]
"content" might be too strong of a word, but it seems adequate, as at least you know where to look.

And if two years from now I file an issue complaining that that message isn't clear on the problem, I give you permission to say **I Told You So** in boldface

**Comment by timwoj** [comment]
Fixed via https://github.com/zeek/zeek/pull/2721
