### ISSUE TITLE
The DNS analyzer should break the 3-bit header Z field into Z / DC / AD bits

### ISSUE THREAD

**Issue by ckreibich** [zeek/zeek#2672]
Zeek's DNS analyzer treats the Z field in a message header as three bits (see [here](https://github.com/zeek/zeek/blob/master/src/analyzer/protocol/dns/DNS.h#L324) and [here](https://github.com/zeek/zeek/blob/master/src/analyzer/protocol/dns/DNS.cc#L1793)), as originally defined. DNSSEC broke that field up into a single Z bit, an "authentic data" AD bit, and a "checking disabled" CD bit, see [RFC 2535](https://www.rfc-editor.org/rfc/rfc2535#section-6.1). The semantics of the fields then needed several iterations in subsequent RFCs so it's all a bit messy, but essentially CD may be set by the resolver, and AD may be [set by resolver or server](https://www.rfc-editor.org/rfc/rfc6840#section-5.7).

Wireshark and tcpdump both parse the fields: Wireshark's query strings are `dns.flags.authenticated` and `dns.flags.checkdisable`, tcpdump shows CD in queries as `%`, and AD in responses as `$` after the query ID.

Zeek technically provides all values in the script layer since the 3-bit Z field is rendered as a `count`, but it'd be nicer to separate out the bits as well.

**Comment by micrictor** [comment]
@ckreibich Would you mind assigning this to me? I can take it.

I think that my approach wouldbe to add an optional field to the logged record - `dnssec_flags` - that is itself a record with two bool-typed fields - `authenticated` and `checking_disabled`.

**Comment by timwoj** [comment]
@micrictor Done! Let us know if we can help in any way.

**Comment by micrictor** [comment]
zeek PR: https://github.com/zeek/zeek/pull/2772
zeek-testing PR: https://github.com/zeek/zeek-testing/pull/11
zeek-docs PR: https://github.com/zeek/zeek-docs/pull/174
