### ISSUE TITLE
In some scenarios, zeek cannot detect the SSH login status (pcap file attached)

### ISSUE THREAD

**Issue by cxdinter** [zeek/zeek#2673]
Hi,
My test environment is an embedded Linux system, zeek is installed on it. Normally, when I login this Linux system through SSH login from MacBook, zeek will record it (set “auth_success” as true, and “auth_attempts” as 1/2/3…).
But, when I switch to another ubuntu PC (NUC computer) , zeek cannot detect the login behavior, nothing updated in ssh.log file.  But I really login successfully.
I used 'tcpdump' to capture the network traffic for both MacBook and ubuntu (see attached file).  I compared the two pcap files, the whole packet process/sequence is similar. The only difference is NUC computer use DH algorithm for SSH key exchange negotiation. While, macbook use ECDH. 
I tried below command to use ECDH on NUC computer, but the result is same (zeek still cannot detect SSH login)
ssh -o KexAlgorithms=ecdh-sha2-nistp256 user@xx.xx.xx.xx
[macbook2.pcap.zip](https://github.com/zeek/zeek/files/10350043/macbook2.pcap.zip)
[nuc.pcap.zip](https://github.com/zeek/zeek/files/10350044/nuc.pcap.zip)

Does anybody meet this phenomenon before? Is it related with some network settings (network cable is same) ? Thanks in advance.

**Note:**
The ubuntu PC (NUC computer) is remote, before login embedded linux system, I must login ubuntu PC through SSH firstly. Not sure this situation affect the issue result or not.

**Comment by awelzel** [comment]
Hey @cxdinter - the `nuc.pcap` file you're providing contains packets with invalid checksums which are by default discarded. You should've seen the following message:
```
$ zeek -r nuc.pcap LogAscii::use_json=T
1672877782.012086 warning in /home/awelzel/corelight-oss/zeek/scripts/base/misc/find-checksum-offloading.zeek, line 54: Your trace file likely has invalid TCP checksums, most likely from NIC checksum offloading.  By default, packets with invalid checksums are discarded by Zeek unless using the -C command-line option or toggling the 'ignore_checksums' variable.  Alternatively, disable checksum offloading by the network adapter to ensure Zeek analyzes the actual checksums that are transmitted
```

Reading the same pcap with `-C` to ignore the checksum errors, the ssh.log contains the information you (presumably) expect:
```
$ zeek -Cr nuc.pcap LogAscii::use_json=T; jq < ssh.log
{
  "ts": 1672877777.126309,
  "uid": "CLmD4y1twaFn3fyFod",
  "id.orig_h": "172.20.1.2",
  "id.orig_p": 52058,
  "id.resp_h": "172.20.1.1",
  "id.resp_p": 22,
  "version": 2,
  "auth_success": true,
  "auth_attempts": 3,
  "client": "SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.5",
  "server": "SSH-2.0-OpenSSH_8.2",
  "cipher_alg": "chacha20-poly1305@openssh.com",
  "mac_alg": "umac-64-etm@openssh.com",
  "compression_alg": "none",
  "kex_alg": "curve25519-sha256",
  "host_key_alg": "ecdsa-sha2-nistp256",
  "host_key": "8d:84:e8:04:0c:53:93:36:bd:fe:7a:b3:a4:78:49:50"
}
```

I'm going to close this issue. We've a bit of docs around offloading here: https://docs.zeek.org/en/master/cluster-setup.html?highlight=offloading#offloading-and-ethtool-tuning and there are more resources around offloading/checksumming issues on the web.

**Comment by cxdinter** [comment]
> Hey @cxdinter - the `nuc.pcap` file you're providing contains packets with invalid checksums which are by default discarded. You should've seen the following message:
> 
> ```
> $ zeek -r nuc.pcap LogAscii::use_json=T
> 1672877782.012086 warning in /home/awelzel/corelight-oss/zeek/scripts/base/misc/find-checksum-offloading.zeek, line 54: Your trace file likely has invalid TCP checksums, most likely from NIC checksum offloading.  By default, packets with invalid checksums are discarded by Zeek unless using the -C command-line option or toggling the 'ignore_checksums' variable.  Alternatively, disable checksum offloading by the network adapter to ensure Zeek analyzes the actual checksums that are transmitted
> ```
> 
> Reading the same pcap with `-C` to ignore the checksum errors, the ssh.log contains the information you (presumably) expect:
> 
> ```
> $ zeek -Cr nuc.pcap LogAscii::use_json=T; jq < ssh.log
> {
>   "ts": 1672877777.126309,
>   "uid": "CLmD4y1twaFn3fyFod",
>   "id.orig_h": "172.20.1.2",
>   "id.orig_p": 52058,
>   "id.resp_h": "172.20.1.1",
>   "id.resp_p": 22,
>   "version": 2,
>   "auth_success": true,
>   "auth_attempts": 3,
>   "client": "SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.5",
>   "server": "SSH-2.0-OpenSSH_8.2",
>   "cipher_alg": "chacha20-poly1305@openssh.com",
>   "mac_alg": "umac-64-etm@openssh.com",
>   "compression_alg": "none",
>   "kex_alg": "curve25519-sha256",
>   "host_key_alg": "ecdsa-sha2-nistp256",
>   "host_key": "8d:84:e8:04:0c:53:93:36:bd:fe:7a:b3:a4:78:49:50"
> }
> ```
> 
> I'm going to close this issue. We've a bit of docs around offloading here: https://docs.zeek.org/en/master/cluster-setup.html?highlight=offloading#offloading-and-ethtool-tuning and there are more resources around offloading/checksumming issues on the web.

Hi awelzel,
     Thanks for your quick response. Now I understand this phenomenon. I am very appreciate !
