### ISSUE TITLE
libspicy and libhilti should build as shared objects

### ISSUE THREAD

**Issue by sethhall** [zeek/zeek#2675]
They're being built as static libraries now which means that the size of the following binaries is needlessly large...

```
-rwxr-xr-x 1 root root  439337760 Jan  6 05:33 hilti-config
-rwxr-xr-x 1 root root  442081168 Jan  6 05:33 hiltic
-rwxr-xr-x 1 root root  725743872 Jan  6 05:36 spicy-config
-rwxr-xr-x 1 root root  728677696 Jan  6 05:36 spicyc
-rwxr-xr-x 1 root root  728891008 Jan  6 05:36 spicy-driver
-rwxr-xr-x 1 root root  731454632 Jan  6 05:36 spicy-dump
-rwxr-xr-x 1 root root  751046864 Jan  6 05:39 spicyz
-rwxr-xr-x 1 root root 1048532000 Jan  6 05:40 zeek
```

Other than zeek, those binaries should all be very small but with a default build they're huge right now.  Even if you strip them they're rather large due to the large amount of code that is in libhilti and libspicy.

**Comment by awelzel** [comment]
Probably related #2650

**Comment by ckreibich** [comment]
The Spicy [cmake shim](https://github.com/zeek/zeek/blob/master/auxil/spicy/CMakeLists.txt#L25) currently explicitly turns off shared builds, with the following comment:
```
# We currently only support building against statically linked Spicy libraries.
# This is due to global state held in the Spicy and HILTI runtime libraries. If
# we would like Spicy dynamically this global state would end up the the final
# binary once via the static link of the runtime libraries into Zeek (needed to
# make sure we can e.g., load arbitrary HLTO files), and once as a link
# dependency of spicy-plugin. This can lead to e.g. consistency issues during
# execution or the problem during teardown where the same global might be
# cleaned up multiple times.
```
@rsmmr, @bbannier, is this still accurate? Does this mean that if I use Zeek with an externally build spicy & spicy-plugin that use shared linking, I'm exposed to these problems?

**Comment by bbannier** [comment]
Since most of the code which ends up in Zeek is for Spicy JIT mode the situation might look differently once zeek/spicy-plugin#154 has landed.

**Comment by awelzel** [comment]
>> Does this mean that if I use Zeek with an externally built spicy & spicy-plugin that use shared linking, I'm exposed to these problems?

> @ckreibich, I just checked and this is still the case.

I'm not quite sure what that means with regards to the question around an external spicy and spicy-plugin with dynamic linking being affected or problematic. I'm not expecting this to be buggy/problematic given that was the normal approach before there was the builtin support. I've also been using an external Spicy and it's been quite alright.

**Comment by bbannier** [comment]
> I'm not quite sure what that means with regards to the question around an external spicy and spicy-plugin with dynamic linking being affected or problematic. I'm not expecting this to be buggy/problematic given that was the normal approach before there was the builtin support. I've also been using an external Spicy and it's been quite alright.

Sorry for being unclear, but you are correct. 

1. we still need the workaround (simplify allowing shared libraries is insufficient)
2. there should be no issue with any installation method for Spicy or spicy-plugin we support at the moment.

**Comment by awelzel** [comment]
> @[bbannier](https://github.com/bbannier) bbannier linked a pull request [1 hour ago](https://github.com/zeek/zeek/issues/2675#event-8400770831) that will close this issue

Agree, but only if you're not building with ``--binary-package``, which will make things static again. I think I can see the reasons, but also adding a bit of info below rpath/packaging I had looked up previously...

> Dynamic libraries tend to be problematic - you often are now allowed to set a RPATH and we tend to be installed into non-standard locations.

Both, Debian and Fedora guidelines, while discouraging RPATH usage, they do also point out that it's okay for internal libraries. And I can see the spicy tools linking to shared internal lib being an acceptable case.

> Currently, the only generally accepted use of this feature in Debian is to add non-standard library path (like /usr/lib/<package>) to libraries that are only intended to be used by the executables or other libraries within the same source package.
https://wiki.debian.org/RpathIssue

> Rpath for Internal Libraries
> When a program installs internal libraries they are often not installed in the system path. These internal libraries are only used for the programs that are present in the package (for example, to factor out code that’s common to the executables). These libraries are not intended for use outside of the package. When this occurs, it is acceptable for the programs within the package to use an rpath to find these libraries.
https://asamalik.fedorapeople.org/fedora-docs-antora/en_US/packaging-guidelines/latest/#rpath-for-internal-libraries

Anyway, for the container images we're currently not using ``--binary-package`` and so #2651  have a nice size-down effect there, too.

**Comment by bbannier** [comment]
@awelzel, while with #2651 we still potentially link the Spicy runtime libraries statically, the PR also completely removes support for running Spicy JIT via Zeek, i.e., `zeek foo.spicy foo.evt` is not supported anymore and one instead needs to build a HLTO file; this allows us to not link the JIT parts of Spicy in the executable anymore which will reduce executable sizes.

If we cannot close this issue with that PR, we should at least reevaluate the state after it is merged.

**Comment by awelzel** [comment]
> If we cannot close this issue with that PR, we should at least reevaluate the state after it is merged.

We can close it. The ticket's motivation was spicyc, spicy-dump, spicy-driver, etc all being large due to static linking by default. #2651 fixes that for the default build - I mostly wanted leave some note around ``--binary-package``
