### ISSUE TITLE
Add support for tables indexed by globs

### ISSUE THREAD

**Issue by rsmmr** [zeek/zeek#268]
The challenge is to find an efficient data structure that supports parallel glob matching for large numbers of patterns. We have an earlier attempt at this ([paraglob](https://github.com/zeek/paraglob)) that didn't show the anticipated performance; should revisit/reconsider how to do this.

**Comment by sethhall** [comment]
Yes!  This would still be such a useful functionality!

**Comment by JustinAzoff** [comment]
All the use cases I've ever had for this was related to prefix or suffix matching.. whitelists, dynamic local_domains, that sort of thing.

I was going to try adding an opaque type for a trie.. I think I know how to do it for a set but not a table.

**Comment by mavam** [comment]
> I was going to try adding an opaque type for a trie

FWIW, Broker ships already with an implementation of [ART](https://db.in.tum.de/~leis/papers/ART.pdf).

That said, I'm not sure if offering a trie data structure is going to add a lot of additional value from a user perspective. Instead of lifting it via an opaque type, I think it could make sense to use it transparently internally, e.g., when the key type of a map is a string/pattern.

**Comment by ZekeMedley** [comment]
Has anyone tried doing this with a suffix tree? There is an attempt here that comes from HKN at Berkeley I believe. While they weren't successful, the idea at least seems worth trying.

**Comment by ckreibich** [comment]
Sounds great to me Zeke, go for it!

**Comment by ZekeMedley** [comment]
Robin, Christian, and I met up today to talk a little about this and here are some goals for paraglob we came up with:

1. Support general gob syntax.
2. Run in better than linear time for most operations.

I'm going to start by seeing if the existing implementation can be sped up so it'll do the job. If that doesn't work, I'll try using a suffix tree internally. For more complicated globs it'll just have to move over all the keys to find ones that match, but using a suffix tree has potential to make things a lot quicker for some common globs like ones with only one wildcard.

I'll benchmark everything against a normal linear search like the one used by SQL's `LIKE` statement and am planning on testing implementations on spam lists. I plan on implementing this as an opaque type. 

If anyone has any use cases they see for this that havn't been covered yet it would be great to hear about them so that I can test implementations on them. :blush:

**Comment by ZekeMedley** [comment]
I now have a working implementation of paraglob [here](https://github.com/ZekeMedley/Paraglob-2). This version moves all of the code to C++ and uses some quicker data structures internally.

(All of the below numbers are from running on a 2.7GHz Intel i7)

With the old paraglob adding a set of 5,000 patterns took 7.5 seconds and then it could perform about 6,500 queries a second on those patterns. The time to build the paraglob also grew in N^2 time. Building a paraglob with 10,000 patterns took 55.5 seconds.

This version can add a set of 5,000 patterns in 0.66 seconds and the time taken grows lineally with the number of patterns. Adding 10,000 patterns takes about 1.3 seconds. It also does somewhere in the range of 100,000 to 400,000 queries a second. This  varies with the percentage of patterns that match are in the dataset. It is faster when a higher percentage of patterns match.

If this looks good, I'll go ahead and add some more robust error handling and then work on integrating it into Zeek. @jsiwek Do you have any suggestions on how this is done best?

**Comment by jsiwek** [comment]
Nice work, that's sounding good to me.  I'd start with getting the original paraglob repo, https://github.com/zeek/paraglob, updated to include all your changes/improvements.  Probably @rsmmr would like to take a look and help review/finalize that.

Then, for integrating into Zeek, you can start working in a branch that:

* Adds a git submodule for the paraglob code base, e.g. in `aux/paraglob`
* Integrate building paraglob into Zeek's CMake build system
* Add a script-layer interface to utilize paraglob data structures.

Likely all you need for that last point is a new opaque type and some built-in-functions that interact with it.  The new opaque type/val acts like a handle that the script-layer can use to reference the real paraglob data structures that are used internally in the C++ code.  Maybe take a look at `src/OpaqueVal.h` and `src/probabilistic/bloom-filter.bif` for reference -- not everything will probably be directly copy-able, but the basic idea should be the same.

**Comment by rsmmr** [comment]
Nice work indeed. Where's the main performance gain coming from, is that the change to using C++ containers?

Agree that merging it into the main Paraglob repo makes sense. Fine to just replace everything there I'd say, let's just keep its history for reference. Some sort of a basic test suite would be good to have; also our normal boiler plate for configure/cmake, CHANGES, and license.

**Comment by ZekeMedley** [comment]
Yep. The original paraglob was actually pretty quick except for its set data structure (see the below flame graph). I replaced the set with a `std::unordered_map` which maps meta words to their respective pattern words and made a couple other pretty small changes which resulted in a pretty substantial speedup. You were right about it being an implementation detail causing the trouble.

![paragraph](https://user-images.githubusercontent.com/30676292/55856666-d197a180-5b1f-11e9-954f-1b75cf2602e8.png)

Great! I'll add btests and use the existing repo as a reference for adding the boilerplate. I also want to make a pass through and add some better error handling before I make a pull request on the original.

**Comment by ZekeMedley** [comment]
Any suggestions for how this should be exposed at the scripting layer? Should we call it a paraglob? I was thinking of using syntax similar to the existing set/table syntax, something like:

```
# Support initialization from an existing vector (call it V here)
local pv = paraglob(V);
local p = paraglob();

add p["dog*"];
add p["[fdl]og"];

# matches is a vector
local matches = p["dog"];
for ( i in x ) {
	print i;  # Iterates over matching patterns
}
```

**Comment by rsmmr** [comment]
I suppose you mean adding a new type to the language. Doing it that way is quite some effort unfortunately, and the functionality is specific enough that I'm not sure it'd really be worth it. Two simpler alternatives:

1. Adding an opaque type with corresponding bif functions, something along these lines:

```
local p: opaque of paraglob = paraglob_init();
paraglob_add(p, "dog*");
paraglob_add(p, "[fdl]og");
local matches = paraglob_match(p, "dog");
```

Pro: This is pretty easy to implement. 
Con: This API isn't very pretty.

2. Overload the existing `table` type similar to how we do it for CIDR lookups with subnets, maybe something like this:

```
local p: set[string] &paraglob;

add p["dog*"];
add p["[fdl]og"];

local matches = p["dog"];
for ( i in x ) {
	print i;  # Iterates over matching patterns
}
```
Pro: This actually looks pretty similar to your code. 
Con: It's not so pretty internally, as the existing table/set code needs to special-case the operator implementations (just as it does for subnets already).

Also note that this would need to work for both tables and sets; and that the lookup operation now returns multiple matches (vs. the standard set/table only a single), which the static type checking would need to account for.

---

I can see doing either, although I think I'd go with (1) for now to get some first experience with the new functionality, and keep the option to do (2) later if it seems worth it.

Re/ if we should actually name it "paraglob" in Zeek: not sure. If there's a nicer / more intuitive name, I'd go for that, but can't think of much right now.
