### ISSUE TITLE
Linking http.log to dns.log for a shared event

### ISSUE THREAD

**Issue by brsolomon-deloitte** [zeek/zeek#2687]
Running `curl http://www.example.com/ > /dev/null` will generate one `http.log` and two `dns.log` entries with _different_ UIDs. 

- `http.log`: `CgF95m3NSrrGHaROhi`
- `dns.log`: `CRrYR14n6CZtF0g0h1`
- `conn.log`: `CgF95m3NSrrGHaROhi`

Intuitively though, these log lines are all part of the same request event. Is there a way to link them together? Is there documentation on how `uid` is formed?

```
==> http.log <==
{"ts":1673613702.352106,"uid":"CgF95m3NSrrGHaROhi","id.orig_h":"REDACTED","id.orig_p":49008,"id.resp_h":"93.184.216.34","id.resp_p":80,"trans_depth":1,"method":"GET","host":"www.example.com","uri":"/","version":"1.1","user_agent":"curl/7.79.1","request_body_len":0,"response_body_len":1256,"status_code":200,"status_msg":"OK","tags":[],"resp_fuids":["FjJhJ82LwtWPYebiN8"],"resp_mime_types":["text/html"]}

==> dns.log <==
{"ts":1673613702.33942,"uid":"CRrYR14n6CZtF0g0h1","id.orig_h":"REDACTED","id.orig_p":60029,"id.resp_h":"172.31.0.2","id.resp_p":53,"proto":"udp","trans_id":59136,"rtt":0.0014069080352783203,"query":"www.example.com","qclass":1,"qclass_name":"C_INTERNET","qtype":1,"qtype_name":"A","rcode":0,"rcode_name":"NOERROR","AA":false,"TC":false,"RD":true,"RA":true,"Z":0,"answers":["93.184.216.34"],"TTLs":[300.0],"rejected":false}
{"ts":1673613702.339456,"uid":"CRrYR14n6CZtF0g0h1","id.orig_h":"REDACTED","id.orig_p":60029,"id.resp_h":"172.31.0.2","id.resp_p":53,"proto":"udp","trans_id":59403,"rtt":0.0014820098876953125,"query":"www.example.com","qclass":1,"qclass_name":"C_INTERNET","qtype":28,"qtype_name":"AAAA","rcode":0,"rcode_name":"NOERROR","AA":false,"TC":false,"RD":true,"RA":true,"Z":0,"answers":["2606:2800:220:1:248:1893:25c8:1946"],"TTLs":[300.0],"rejected":false}

==> conn.log <==
{"ts":1673613702.341256,"uid":"CgF95m3NSrrGHaROhi","id.orig_h":"REDACTED","id.orig_p":49008,"id.resp_h":"93.184.216.34","id.resp_p":80,"proto":"tcp","service":"http","duration":0.03307199478149414,"orig_bytes":79,"resp_bytes":1591,"conn_state":"SF","local_orig":true,"local_resp":false,"missed_bytes":0,"history":"ShADadFf","orig_pkts":7,"orig_ip_bytes":451,"resp_pkts":5,"resp_ip_bytes":1859,"community_id":"1:InbMp+vk1G7mR9s/hFYERvBopB8="}
```

Version: Zeek 5.1.1

**Comment by awelzel** [comment]
> Intuitively though, these log lines are all part of the same request event. Is there a way to link them together? Is there documentation on how uid is formed?

The uid is a unique identifier per connection. For the DNS requests and the HTTP request, two connections are involved that while "intuitively" belong together, from Zeeks perspective, it's just two separate connections of different protocols with no relation.

---

If you'd like to continue this discussion and possible ways to add correlation via Zeek scripting, feel free to join Slack or the forum - either might be better suited for such questions than GitHub:

Forum: https://community.zeek.org/

Slack: https://zeek.org/community/

Thanks,
   Arne
