### ISSUE TITLE
Recursive record segfaults when used as key in table or set

### ISSUE THREAD

**Issue by ynadji** [zeek/zeek#2690]
See the following [try.zeek](https://try.zeek.org/#/tryzeek/saved/627514) example for details. Code copy/pasted at the end as well.

A `record` can be recursive, i.e., contain a member of the same type, by `redef`'ing the record to add the previous definition. It requires the use of indirection through a `table`. This works fine when defining variables and using them, but causes a segfault when the recursive type is used as the key in a `table` or `set`. I could see this being undefined, but it probably shouldn't segfault.

```ruby
type Foo: record {
	bar: count;
};

redef record Foo += {
	parent: table[bool] of Foo &optional;
};

event zeek_init()
	{
	print "Hello, World!";
	
	# The following definitions segfault.
	local tmp: table[Foo] of set[count];
	#local tmp: set[Foo];

	# This block works just fine, however.
	#local tmp1 = Foo($bar = 1);
	#local tmp2 = Foo($bar = 2, $parent=table([T] = tmp1));
	#local tmp3: table[count] of Foo;
	}

event zeek_done()
	{
	print "Goodbye, World!";
	}
```

**Comment by timwoj** [comment]
Should we even be allowing the recursive definition here?

The actual crash is a stack-overflow:

```
    frame #14411: 0x0000000100e18464 zeek`zeek::is_supported_index_type(t=0x000000010df95e60, tname=0x000000016fdeef60) at Type.cc:520:11
    frame #14412: 0x0000000100e18110 zeek`zeek::is_supported_index_type(t=0x000000010ddd7850, tname=0x000000016fdeef60) at Type.cc:493:12
    frame #14413: 0x0000000100e18464 zeek`zeek::is_supported_index_type(t=0x000000010df95e60, tname=0x000000016fdeef60) at Type.cc:520:11
    frame #14414: 0x0000000100e18110 zeek`zeek::is_supported_index_type(t=0x000000010d78e890, tname=0x000000016fdeef60) at Type.cc:493:12
    frame #14415: 0x0000000100e17a98 zeek`zeek::TableType::TableType(this=0x000000010dddaad0, ind=zeek::TypeListPtr @ 0x000000016fdf4320, yield=zeek::TypePtr @ 0x000000016fdf4340) at Type.cc:548:10
    frame #14416: 0x0000000100e18758 zeek`zeek::TableType::TableType(this=0x000000010dddaad0, ind=<unavailable>, yield=<unavailable>) at Type.cc:534:2
    frame #14417: 0x000000010002c2a4 zeek`yyparse() at parse.y:1197:24
    frame #14418: 0x0000000100522164 zeek`zeek::detail::setup(argc=3, argv=0x000000016fdfef80, zopts=0x0000000000000000) at zeek-setup.cc:797:3
    frame #14419: 0x00000001031927d0 zeek`main(argc=3, argv=0x000000016fdfef80) at main.cc:57:22
    frame #14420: 0x000000018bce7e50 dyld`start + 2544
```

`is_supported_index_type` is called recursively until it runs out of stack and crashes.

**Comment by ynadji** [comment]
FWIW, I've found useful applications for this kind of recursive definition. It makes implementing some more complicated data structures in Zeek script easier/more idiomatic.

**Comment by ckreibich** [comment]
Your first warning was that you had to redef the record, Yacin. ;-)

I think we should support this. We've recently become more supportive of complex types in tables, so this just extends that path.
