### ISSUE TITLE
RDP Keyboard Parsing

### ISSUE THREAD

**Issue by jeff-bb** [zeek/zeek#2700]
For unknown variations on otherwise known keyboards in the lookup table, the returned number should be converted to hex and the low order bytes compared against the lookup table.

A known example of this behavior --
1033 -> 0x0409 -> 1033 -> en-US
66569 -> 0x00010409 -> Use lower bits, 0x0409 -> 1033 -> en-US

The top one is a standard en-US language keyboard, bottom is a Dvorak. If we didn't know what it was, it would report/log as "keyboard-English - United States", which is less helpful than having it hit the "best guess match" (and possible logging as such), eg "keyboard-English - United States (Best Guess)"

Example unknown Japanese keyboard variant that is not in the list, but seen in the wild.
3758162961 -> 0xE0010411 -> Use lower bits, 0x0411 -> dec 1041, aka ja-JP

Apologies for not simply doing a pull and making the changes, but I've only looked the code today and unfamiliar with the syntax or capabilities of the scripting language. Figured I would start with opening it as a suggestion/enhancement while reading up.

**Comment by timwoj** [comment]
This was fixed via https://github.com/zeek/zeek/pull/2699, https://github.com/zeek/zeek/pull/2701, and https://github.com/zeek/zeek/pull/2712
