### ISSUE TITLE
Global hooks implemented in modules not invoked

### ISSUE THREAD

**Issue by awelzel** [zeek/zeek#2709]
From #2708 , @rsmmr  indicates that the hook handler for `my_hook` implemented in `module MyModule` should reference the one in the GLOBAL module and the explicit `GLOBAL` prefix not required.

```
global my_hook: hook(c: count);

event zeek_init() {
  hook my_hook(42);
}

# Implementation in implicit GLOBAL module.
hook my_hook(c: count) {
  print "my_hook in global", c;
}

module MyModule;
# Not executed.
hook my_hook(c: count) {
  print "my_hook in MyModule", c;
}

# Explicit GLOBAL reference
hook GLOBAL::my_hook(c: count) {
  print "my_hook in MyModule with GLOBAL prefix", c;
}

$ zeek bug.zeek 
warning in ./bug.zeek, line 17: handler for non-existing hook cannot be invoked (MyModule::my_hook)
my_hook in global, 42
my_hook in MyModule with GLOBAL prefix, 42
```

I think this was discussed elsewhere before as a gotcha, will see if it can be found.

Edit: #1830 is somewhat related.

**Comment by awelzel** [comment]
Hmm, this is somewhere in the realm of #163  and #1830, but with hooks/functions.

The hook handler implementation in MyModule module is separate from the one in GLOBAL and new function that can only be invoked via `hook MyModule::my_hook` or  when moving the `zeek_init()` from above example into `module MyModule`, then *only* the `MyModule::my_hook` is invoked and not the global instances. Seems somewhat reasonable from that perspective.

**Comment by bbannier** [comment]
One reason I bring this up is that in C-like languages which use a `::` prefix to refer to identifiers in global identifier scope one usually can have multiple levels of nesting for identifier scopes. Zeek doesn't really have that in the language (but maybe as a convention), and I feel like `GLOBAL::...` was a okay way to handle that (also conceptually easy to explain), and adding an alternative way wouldn't add much and would documenting two ways (which one is the "right" way?).

As an example, this is a valid Zeek script:

```zeek
module a::b;

export {
	global a::b::c: count = 47;
	global d::e::f: count = 11;
}

event zeek_init()
	{
	print a::b::c, d::e::f;
	}
```

The other reason is that this would require a second lookup impl in my language server :shrug:

**Comment by rsmmr** [comment]
I'm in favor of moving to `::` replacing `GLOBAL`. I don't remember the history for `GLOBAL` but to me, that has always looked like a hack; certainly nothing I'd know from any other language. In contrast, a `::` prefix is what people should be used to and hence more intuitive.  The fact that we don't have multiple levels doesn't seem to contract it. In fact, it would fit in nicely if we wanted to add layered scoping at some point. 

If we went this route, I'd deprecate `GLOBAL` and eventually remove.

**Comment by timwoj** [comment]
I like the idea of `::` as well, mostly because of the consistency with other languages. +1 from me for adding this and deprecating `GLOBAL`.

**Comment by awelzel** [comment]
> If we went this route, I'd deprecate GLOBAL and eventually remove.

With deprecation, one point is how "re-opening GLOBAL" should look like `module ::;` or `module ;` appear rather cryptic. We do document `module GLOBAL` usage as something base/low-level/internal scripts would use, so could see that continue to be non-deprecated.

**Comment by rsmmr** [comment]
>  could see that continue to be non-deprecated.

Yeah, that sounds reasonable, for lack of much of an alternative.
