### ISSUE TITLE
file descriptor leak with broctl/broker

### ISSUE THREAD

**Issue by set-element** [zeek/zeek#273]
When using broctl, issuing the following commands can cause large numbers of file descriptors to be leaked: netstats, peerstatus and print.

Based on testing, the number of file descriptors leaked is 4 * number of nodes that are processed by the broctl routine. For example a small cluster of (manager,proxy,logger and 2 workers) would leak 4*5=20 FD per execution cycle.

The leaked FD descriptions in /proc/<pid>/fd look like:
l-wx------ 1 bro bro 64 Feb 8 19:48 100 -> pipe:[9803837] 
lr-x------ 1 bro bro 64 Feb 8 19:48 101 -> pipe:[9804917] 
lr-x------ 1 bro bro 64 Feb 8 19:48 102 -> pipe:[9804477] 
l-wx------ 1 bro bro 64 Feb 8 19:48 103 -> pipe:[9804477]

Which gives a clue as to their origin.

Following the code back and looking for similarities, these were the only commands that exercised the ​send_events_parallel(eventlist, config.Config.controltopic)​ interface to broker in events.py.

This issue is completely deterministic and can be found in the current git version of bro (as of ~ 7 days ago)

Any questions, please contact me at set.element@gmail.com

**Comment by jsiwek** [comment]
Thanks for reporting that.  It's fixed in zeek + broker master branches now.
