### ISSUE TITLE
File extract when file open on "Windows" platform  should use binary mode to ignore CRLF translate

### ISSUE THREAD

**Issue by chuanyi** [zeek/zeek#2730]
https://github.com/zeek/zeek/blob/e9caea9694c586a69efac1772396993642e35f50/src/file_analysis/analyzer/extract/Extract.cc#L21

Correct:
`file_stream = fopen(filename.data(), "wb"); `

Refers:
https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/fopen-wfopen?view=msvc-170

**Comment by timwoj** [comment]
I grepped through the code and there's a few other places that might benefit from this:

- src/iosource/pcap/Dumper.cc, which opens a file in append mode but not as binary
- `write_random_seeds` in util.cc, which opens a file in `w+` but not binary. I don't think that one matters at all.
- `rotate_file` in util.cc, which opens a file in write but not binary. I'm not sure if it would matter though, as this should only be used by log rotation and those files would have already been written in whatever the local line endings are I think.

**Comment by timwoj** [comment]
Fixed via https://github.com/zeek/zeek/pull/2815
