### ISSUE TITLE
Consider adding ssl_all_extensions()

### ISSUE THREAD

**Issue by awelzel** [zeek/zeek#2751]
During conversations around JA3 package performance improvements, the idea to have an ``ssl_all_extensions()`` events came up. JA3 collects all SSL extensions from Client Hello / Server Hello via the `ssl_extension()` event. For its use case (and others that use multiple or all extensions), it may be more efficient to provide an `ssl_all_extensions()` similar to the `http_all_headers()` event.

It may be worth implementing and adapting the JA3 package to see if there's a noticeable benefit. This hinges a bit on the idea that there's enough overhead invoking individual handlers that it's worth it.

https://github.com/salesforce/ja3

**Comment by awelzel** [comment]
I've drafted it in the branch below and converted the ja3 package over, but there wasn't an improvement when using a pcap producing ~9950 ssl.log entries (taking ~12.5sec to process).
  
https://github.com/zeek/zeek/tree/topic/awelzel/ssl-extensions-ja3-perf

The resulting JA3 code looked as follows and I suspect any potential speed-up by using just a single event is hampered by the vector iteration and field lookups in the record type that are introduced.
```
event ssl_extensions(c: connection, is_orig: bool, extensions: vector of SSL::Extension)
    {
    if ( ! is_orig || |extensions| == 0 )
        return;

     if ( ! c?$tlsfp )
         c$tlsfp = TLSFPStorage();


    local str_exts: vector of string;
    for ( _, ext in extensions )
        {
        local code = ext$extension_type;
        if ( code in grease )
            next;

        str_exts += cat(code);
        }

    c$tlsfp$extensions = join_string_vec(str_exts, sep);
    }
```

I'm tempted to close this again.

@vpax / @benjeems - fyi.

**Comment by vpax** [comment]
@awelzel thanks for looking into this!  I'm okay with closing this.
