### ISSUE TITLE
Plugins created with init-plugin won't recompile on OS-X, if IntrusivePtr.h is included

### ISSUE THREAD

**Issue by 0xxon** [zeek/zeek#2784]
When creating a plugin with `init-plugin` and compiling it on a Mac, the plugin needs a `make distclean` or `rm build/VERSION` inbetween every code change. If this is not done, the `VERSION` file in the build-directory will clash with the C++20 `version` header.

Example error message:

```
In file included from /Users/johanna/zeek/lalatest/build/lalatest.bif.cc:4:
In file included from /Users/johanna/zeek/lalatest/build/lalatest.bif.h:7:
In file included from /Users/johanna/zeek/install/include/zeek/zeek-bif.h:4:
In file included from /Users/johanna/zeek/install/include/zeek/BifReturnVal.h:7:
In file included from /Users/johanna/zeek/install/include/zeek/IntrusivePtr.h:5:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/functional:490:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/__algorithm/search.h:15:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/__iterator/iterator_traits.h:14:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/__iterator/incrementable_traits.h:14:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/concepts:133:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/__functional/invoke.h:14:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/__functional/weak_result_type.h:16:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/type_traits:420:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/cstddef:37:
/Users/johanna/zeek/lalatest/build/version:1:1: error: expected unqualified-id
0.1.0
```

**Comment by ckreibich** [comment]
@bbannier I seem to recall that you resolved something about case-insensitive file systems in the package template, but I don't think it was this, right? We'll need to make sure to keep the fix for this in sync across the two.

Also, @Neverlord's new plugin cmake infrastructure in zeek/cmake#60 might affect when/whether/how to fix this.

**Comment by bbannier** [comment]
@ckreibich, I do not recall. I opened a PR with a different fix, zeek/zeek-aux#37.

**Comment by bbannier** [comment]
The real issue is that the `zeek-plugin-create-package.sh` pollutes the build directory which is also in the include path, https://github.com/zeek/cmake/blob/9f05362a5c33ed11dab37d2dedf74206d59d8f6d/zeek-plugin-create-package.sh#L18-L26

**Comment by Neverlord** [comment]
> Also, @Neverlord's new plugin cmake infrastructure in https://github.com/zeek/cmake/pull/60 might affect when/whether/how to fix this.

Benjamin's patch (https://github.com/zeek/cmake/pull/61) wouldn't interfere it.

**Comment by ckreibich** [comment]
Cool, thanks for the updates ... and thank you Benjamin! Happy to look over the PR if Johanna hasn't already beaten me to it.
