### ISSUE TITLE
Change defaults in Known scripts to not use broker stores

### ISSUE THREAD

**Issue by JustinAzoff** [zeek/zeek#2803]
We have seen a number of clusters recently having various performance issues that are fixed by changing these settings:

```
redef Known::use_host_store = F;
redef Known::use_service_store = F;
redef Known::use_cert_store = F ;
```

I'm not sure if it's large clusters only, or if a small cluster will also show issues.  Recently on one system with 30 workers I noticed a 20-30% CPU reduction on each worker as well as a drop of over 100% across the manager and proxies.

**Comment by timwoj** [comment]
From @initconf via Slack:

> I’d also say - lets just default known-*  scripts to use tables instead of broker stores. We’ve been advertently or inadvertently doing that for > year now in testing trying to zero-out when and other issues
