### ISSUE TITLE
Dangling link to Dockerfile in docs

### ISSUE THREAD

**Issue by rsmmr** [zeek/zeek#2805]
https://docs.zeek.org/en/master/install.html#docker-images is saying that our Dockerfile lives at https://github.com/zeek/zeek/blob/master/docker/Dockerfile, which doesn't exit.

**Comment by bbannier** [comment]
This was completely rewritten to not have single Dockerfiles anymore as part of #2694. I am unsure how to best reference the new, broken up setup, but maybe this is another reason to bring back the previous simpler setup @awelzel?

**Comment by awelzel** [comment]
If we bring back a single Dockerfile, it'll possibly get stale. How about removing mentioning the location, or pointing at the wole directory?

From a separate project:

> Elasticsearch is also available as Docker images. A list of all published Docker images and tags is available at [www.docker.elastic.co](https://www.docker.elastic.co/). The source files are in [Github](https://github.com/elastic/elasticsearch/blob/8.6/distribution/docker).
