### ISSUE TITLE
Builtin external plugins and zeek/zeek-version.h backwards compat

### ISSUE THREAD

**Issue by awelzel** [zeek/zeek#2806]
With #2802, ZEEK_VERSION* macros were split from zeek-config.h into zeek-version.h. For backwards compatibility, when building an external plugin, zeek-config.h does include zeek-version.h. This mechanism does not extend to "builtin external" plugins - those configured with `--include-plugins`. If they reference ZEEK_VERSION_NUMBER, zeek/zeek-version.h must be included explicitly. For AF_Packet and spicy-plugin that was done in zeek/zeek-af_packet-plugin#45, zeek/spicy-plugin#48.

If we could string through a `-DZEEK_BUILTIN_EXTERNAL_PLUGIN=true` or so, that would allow extending the `zeek/zeek-version.h` include condition also to builtin plugins. I don't see how we otherwise know we're building an external plugin.

For most users, there's no impact, but minimally @bbannier was wondering if that isn't too fragile. Other opinions?

Maybe it's not worth the trouble, in which case we can close this again.

This is where builtin external plugins are added, I'd guess we could push and pop to the compile options, but @Neverlord may have better ideas: https://github.com/zeek/zeek/blob/ebc956324358d194c77dd2fe67572fd10ca35b9f/src/CMakeLists.txt#L214-L222

**Comment by Neverlord** [comment]
I'll fix it as a followup to https://github.com/zeek/zeek/pull/2799. 🙂
