### ISSUE TITLE
Software.log JSON_streaming/Log::WRITER_ASCII Error related to Google Pixel User Agent strings 

### ISSUE THREAD

**Issue by dwdixon** [zeek/zeek#281]
Hi, I've been experiencing this issue for some time, which seems to occur quite frequently.  It appears that it is related to Google Pixel user agents in the software.log, specifically the "version.major" field.  Below is just one example, this occurs quite frequently probably in relation to the number of Google Pixel devices generating traffic.  I'm logging both the default tab delimited and json-streaming-logs in my current setup.

```0.000000        Reporter::ERROR json_streaming_software/Log::WRITER_ASCII: count value too large for JSON: 13271048900884792351 (empty)```

```
#fields	ts	host	host_p	software_type	name	version.major	version.minor	version.minor2	version.minor3	version.addl	unparsed_version
1550762951.419927       192.168.1.200      -       HTTP::BROWSER   A/9/Google/Pixel#XL/marlin/unknown/QCX3/l       13271048900884792351    -       -       -       /       A/9/Google/Pixel#XL/marlin/unknown/QCX3/l13271048900884792351/-/757883484/-/google/338143/338135/-```

**Comment by jsiwek** [comment]
If you have a pcap you can share that reproduces this, it may help -- I'm thinking the thing to do here may be to just have a special-case for Google Pixel User Agents.  Or maybe more generally the parsing logic should throw out version numbers that are obscenely large and unlikely to indicate version numbers.

The fundament reason for the error message is maybe a bit trickier to solve, I just created a separate issue for that: https://github.com/zeek/zeek/issues/282

**Comment by dwdixon** [comment]
Thanks Jon! So it would be a bit non-trivial currently for me to get a slice of traffic with a useable pcap that reproduces this but I have plenty of logs that support this being related to these Pixel User Agent strings.  This seems to be somewhat isolated to the Google Pixel 2 and Pixel XL and their associated code names...FWIW.

Would you be willing to use curl -A to spoof/replicate these Pixel User Agent string formats and generate a pcap from that HTTP traffic?  I've attached a list of about 260 unique variations of these unparsed "Pixel#" junk User Agent strings from my logs to spoof with curl and maybe grab a pcap that way if that sounds ok and would work on your end?  

Many thanks for the quick response!

Cheers,

-Drew

[Pixel_UA_junk.txt](https://github.com/zeek/zeek/files/2891714/Pixel_UA_junk.txt)

**Comment by jsiwek** [comment]
Thanks for the list.  And yeah, I don't need so much the original pcap, I was mostly just curious if there was another other info I could glean from it.  As far as making a fix with test case, that list helps a lot -- seems like the thing to match may like `A/(.*)/Google/Pixel.*` and then pull out the Android version from that.
