### ISSUE TITLE
Improve "value too large for JSON" behavior

### ISSUE THREAD

**Issue by jsiwek** [zeek/zeek#282]
See:

https://github.com/zeek/zeek/blob/aff3f4b3fde1e8d896ac4f450602e2d1c1139da2/src/threading/formatters/JSON.cc#L82-L86

The general loss of information here is a bit worrying but I'm not sure what would be better.  Encoding things outside a standard "interoperability" range as string instead ?

A secondary point is that the current interoperability range being used in the JSON formatter here seems off: the JSON format itself does support arbitrary size *numbers*, but the common ground for consuming applications/implementations is typically taken to be IEEE 754 "double", not "signed 64-bit integer".

So I'm not sure about why it's checking for being outside the range of `INT64_MAX`, since the actual range of representable integers when using a `double` is from `-(2**53) + 1` to  `(2**53) - 1`, much less than the maximum signed 64-bit integer at `2**63 - 1`.

Reference: https://tools.ietf.org/html/rfc7159#section-6

Note that the same "too large" behavior is also used here:

https://github.com/zeek/zeek/blob/aff3f4b3fde1e8d896ac4f450602e2d1c1139da2/src/threading/formatters/JSON.cc#L154-L155

And the range check is absent when formatting an `int` type, but maybe should be there.

**Comment by sethhall** [comment]
This was all my bad based on some misinformation that I read years ago.  I believe it can be freely changed and generally I don't think we should worry about number size much at all.  The variety of behaviors that I've seen from various json implementations indicates that this isn't handled consistently at all on the reading side.

**Comment by jsiwek** [comment]
Yeah, I also think it's sane to produce numbers that are as large as we support since otherwise we lose data and technically we are still within JSON spec by doing so.  If the consumer doesn't support some range/precision, I think it's reasonable to expect them to be able to detect that situation and treat it in a way that's most appropriate (like ignoring it).
