### ISSUE TITLE
Add CI job to test --include-plugins functionality

### ISSUE THREAD

**Issue by awelzel** [zeek/zeek#2837]
We've previously had issues with the ``--include-plugins`` feature related to plugins containing BinPAC based analyzers and plugins using shared library dependencies:
* https://github.com/zeek/zeek/issues/2482
* https://github.com/zeek/cmake/pull/56
* https://github.com/zeek/zeek/issues/2483

There's been an external report about included BinPAC based plugins again (or still) not working from @JustinAzoff .

Outcome:
* Nightly or "fullci" job that builds Zeek with a few popular plugins (or those that caused issues previously)
* Ideas: bro-http2, community-id, BinPAC based analyzer, zeek-kafka

Minimally run `zeek -NN` or a simple `zeek -r` test for the resulting Zeek build.

**Comment by awelzel** [comment]
> There's been an external report about included BinPAC based plugins again (or still) not working from @JustinAzoff .

@JustinAzoff , it's indeed broken after the removal of the src `zeek -> .` symlink with Zeek 5.2, grumble.

**Comment by Neverlord** [comment]
> > There's been an external report about included BinPAC based plugins again (or still) not working from @JustinAzoff .
> 
> @JustinAzoff , it's indeed broken after the removal of the src `zeek -> .` symlink with Zeek 5.2, grumble.

Could that explain why the spicy-plugin broke with the CMake overhaul branch? https://github.com/zeek/spicy-plugin/pull/192/checks?check_run_id=11725451492

**Comment by awelzel** [comment]
Seems different. The issue mentioned above is specific to BinPAC invocations and include directories for .pac files.
