### ISSUE TITLE
zeek 5.2.0 rpath issue with libspicy.dylib

### ISSUE THREAD

**Issue by Schamschula** [zeek/zeek#2840]
While test building zeek 5.2.0 to update the MacPorts Portfile I got the following error:

> :info:build cd /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_net_zeek/zeek-devel/work/zeek-5.2.0/src/analyzer/protocol/finger && /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_net_zeek/zeek-devel/work/build/src/builtin-plugins/spicy-plugin/bin/spicyz -L /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_net_zeek/zeek-devel/work/zeek-5.2.0/auxil/spicy/spicy/hilti/lib -L /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_net_zeek/zeek-devel/work/zeek-5.2.0/auxil/spicy/spicy/spicy/lib -x /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_net_zeek/zeek-devel/work/build/src/analyzer/protocol/finger/finger finger.spicy finger.evt
> :info:build cd /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_net_zeek/zeek-devel/work/zeek-5.2.0/src/analyzer/protocol/syslog && /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_net_zeek/zeek-devel/work/build/src/builtin-plugins/spicy-plugin/bin/spicyz -L /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_net_zeek/zeek-devel/work/zeek-5.2.0/auxil/spicy/spicy/hilti/lib -L /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_net_zeek/zeek-devel/work/zeek-5.2.0/auxil/spicy/spicy/spicy/lib -x /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_net_zeek/zeek-devel/work/build/src/analyzer/protocol/syslog/syslog syslog.spicy syslog.evt
> :info:build dyld[73655]: Library not loaded: '@rpath/libspicy.dylib'
> :info:build   Referenced from: '/opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_net_zeek/zeek-devel/work/build/src/builtin-plugins/spicy-plugin/bin/spicyz'
> :info:build   Reason: tried: '/opt/local/lib/libspicy.dylib' (no such file), '/opt/local/lib/libspicy.dylib' (no such file), '/usr/local/lib/libspicy.dylib' (no such file), '/usr/lib/libspicy.dylib' (no such file)
> :info:build dyld[73654]: Library not loaded: '@rpath/libspicy.dylib'
> :info:build   Referenced from: '/opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_net_zeek/zeek-devel/work/build/src/builtin-plugins/spicy-plugin/bin/spicyz'
> :info:build   Reason: tried: '/opt/local/lib/libspicy.dylib' (no such file), '/opt/local/lib/libspicy.dylib' (no such file), '/usr/local/lib/libspicy.dylib' (no such file), '/usr/lib/libspicy.dylib' (no such file)
> :info:build /bin/sh: line 1: 73655 Abort trap: 6           /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_net_zeek/zeek-devel/work/build/src/builtin-plugins/spicy-plugin/bin/spicyz -L /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_net_zeek/zeek-devel/work/zeek-5.2.0/auxil/spicy/spicy/hilti/lib -L /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_net_zeek/zeek-devel/work/zeek-5.2.0/auxil/spicy/spicy/spicy/lib -x /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_net_zeek/zeek-devel/work/build/src/analyzer/protocol/finger/finger finger.spicy finger.evt
> :info:build /bin/sh: line 1: 73654 Abort trap: 6           /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_net_zeek/zeek-devel/work/build/src/builtin-plugins/spicy-plugin/bin/spicyz -L /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_net_zeek/zeek-devel/work/zeek-5.2.0/auxil/spicy/spicy/hilti/lib -L /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_net_zeek/zeek-devel/work/zeek-5.2.0/auxil/spicy/spicy/spicy/lib -x /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_net_zeek/zeek-devel/work/build/src/analyzer/protocol/syslog/syslog syslog.spicy syslog.evt
> :info:build make[2]: *** [src/analyzer/protocol/finger/finger_Finger.cc] Error 134
> :info:build make[2]: Leaving directory `/opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_net_zeek/zeek-devel/work/build'
> :info:build make[2]: *** [src/analyzer/protocol/syslog/syslog_Syslog.cc] Error 134

I didn't see this error in version 5.1.3.

**Comment by Schamschula** [comment]
I get the following for spicyz:

> otool -L net/zeek/work/build/src/builtin-plugins/spicy-plugin/bin/spicyz 
> net/zeek/work/build/src/builtin-plugins/spicy-plugin/bin/spicyz:
> 	@rpath/libspicy.dylib (compatibility version 0.0.0, current version 0.0.0)
> 	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.100.3)
> 	@rpath/libhilti.dylib (compatibility version 0.0.0, current version 0.0.0)
> 	/opt/local/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.13)
> 	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1300.23.0)

However, at this point in the process that file is still in the `build` directory, not even in `destroot`, never mind in `/opt/local/bin`.

**Comment by timwoj** [comment]
Pinging @bbannier or @rsmmr

**Comment by bbannier** [comment]
Could you provide a more standalone way to reproduce this @Schamschula?

I looked at your [`Portfile`](https://github.com/macports/macports-ports/blob/master/net/zeek/Portfile), but it wasn't immediately clear to me how the effective `configure command line would look like. By default e.g., the `libspicy` mentioned in your error message snippet would be build as a static archive, but I see nothing in the `Portfile` switching to a dynamic build; I assume there are implicit arguments involved as well.

**Comment by Schamschula** [comment]
I've attached the full log:

[zeek-devel-main.log](https://github.com/zeek/zeek/files/11017751/zeek-devel-main.log)

The configure command was

`cd "/opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_net_zeek/zeek-devel/work/build" && /opt/local/bin/cmake -G "CodeBlocks - Unix Makefiles" -DCMAKE_BUILD_TYPE=MacPorts -DCMAKE_INSTALL_PREFIX="/opt/local" -DCMAKE_INSTALL_NAME_DIR="/opt/local/lib" -DCMAKE_SYSTEM_PREFIX_PATH="/opt/local;/usr" -DCMAKE_C_COMPILER="$CC" -DCMAKE_CXX_COMPILER="$CXX" -DCMAKE_OBJC_COMPILER="$CC" -DCMAKE_OBJCXX_COMPILER="$CXX" -DCMAKE_POLICY_DEFAULT_CMP0025=NEW -DCMAKE_POLICY_DEFAULT_CMP0060=NEW -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_COLOR_MAKEFILE=ON -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_MAKE_PROGRAM=/usr/bin/make -DCMAKE_MODULE_PATH="/opt/local/share/cmake/Modules" -DCMAKE_PREFIX_PATH="/opt/local/share/cmake/Modules" -DCMAKE_BUILD_WITH_INSTALL_RPATH:BOOL=ON -DCMAKE_INSTALL_RPATH="/opt/local/lib" -Wno-dev -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DPYTHON_EXECUTABLE=/opt/local/bin/python3.11 -DPYTHON_CONFIG=/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/config-3.11m-darwin/python-config.py -DOPENSSL_ROOT_DIR=/opt/local/libexec/openssl3 -DOPENSSL_INCLUDE_DIR=/opt/local/libexec/openssl3/include -DWITH_SSL=/opt/local/libexec/openssl3 -DCMAKE_OSX_ARCHITECTURES="arm64" -DCMAKE_OSX_DEPLOYMENT_TARGET="12.0" -DCMAKE_OSX_SYSROOT="/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk" /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_net_zeek/zeek-devel/work/zeek-5.2.0 `

`cmake` knows about MacPorts and also sets some switches.

**Comment by bbannier** [comment]
Thanks for the details and the log.

The log has this:

```
:info:build [100%] Compiling Syslog analyzer
:info:build [100%] Compiling Finger analyzer
:info:build cd /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_net_zeek/zeek-devel/work/zeek-5.2.0/src/analyzer/protocol/finger && /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_net_zeek/zeek-devel/work/build/src/builtin-plugins/spicy-plugin/bin/spicyz -L /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_net_zeek/zeek-devel/work/zeek-5.2.0/auxil/spicy/spicy/hilti/lib -L /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_net_zeek/zeek-devel/work/zeek-5.2.0/auxil/spicy/spicy/spicy/lib -x /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_net_zeek/zeek-devel/work/build/src/analyzer/protocol/finger/finger finger.spicy finger.evt
:info:build cd /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_net_zeek/zeek-devel/work/zeek-5.2.0/src/analyzer/protocol/syslog && /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_net_zeek/zeek-devel/work/build/src/builtin-plugins/spicy-plugin/bin/spicyz -L /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_net_zeek/zeek-devel/work/zeek-5.2.0/auxil/spicy/spicy/hilti/lib -L /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_net_zeek/zeek-devel/work/zeek-5.2.0/auxil/spicy/spicy/spicy/lib -x /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_net_zeek/zeek-devel/work/build/src/analyzer/protocol/syslog/syslog syslog.spicy syslog.evt
:info:build dyld[73655]: Library not loaded: '@rpath/libspicy.dylib'
:info:build   Referenced from: '/opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_net_zeek/zeek-devel/work/build/src/builtin-plugins/spicy-plugin/bin/spicyz'
:info:build   Reason: tried: '/opt/local/lib/libspicy.dylib' (no such file), '/opt/local/lib/libspicy.dylib' (no such file), '/usr/local/lib/libspicy.dylib' (no such file), '/usr/lib/libspicy.dylib' (no such file)
:info:build dyld[73654]: Library not loaded: '@rpath/libspicy.dylib'
:info:build   Referenced from: '/opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_net_zeek/zeek-devel/work/build/src/builtin-plugins/spicy-plugin/bin/spicyz'
:info:build   Reason: tried: '/opt/local/lib/libspicy.dylib' (no such file), '/opt/local/lib/libspicy.dylib' (no such file), '/usr/local/lib/libspicy.dylib' (no such file), '/usr/lib/libspicy.dylib' (no such file)
:info:build /bin/sh: line 1: 73655 Abort trap: 6           /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_net_zeek/zeek-devel/work/build/src/builtin-plugins/spicy-plugin/bin/spicyz -L /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_net_zeek/zeek-devel/work/zeek-5.2.0/auxil/spicy/spicy/hilti/lib -L /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_net_zeek/zeek-devel/work/zeek-5.2.0/auxil/spicy/spicy/spicy/lib -x /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_net_zeek/zeek-devel/work/build/src/analyzer/protocol/finger/finger finger.spicy finger.evt
:info:build /bin/sh: line 1: 73654 Abort trap: 6           /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_net_zeek/zeek-devel/work/build/src/builtin-plugins/spicy-plugin/bin/spicyz -L /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_net_zeek/zeek-devel/work/zeek-5.2.0/auxil/spicy/spicy/hilti/lib -L /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_net_zeek/zeek-devel/work/zeek-5.2.0/auxil/spicy/spicy/spicy/lib -x /opt/local/var/macports/build/_Users_marius_Development_MacPorts_ports_net_zeek/zeek-devel/work/build/src/analyzer/protocol/syslog/syslog syslog.spicy syslog.evt
```

This is due to you configuring your build with `-DCMAKE_BUILD_WITH_INSTALL_RPATH:BOOL=ON` which makes it impossible to run programs from the build before installation,

The Zeek build needs to run its `spicyz` program it just built to generate analyzers for syslog and finger which are [Spicy analyzers](https://docs.zeek.org/projects/spicy/en/latest/). These analyzers were migrated to from [binpac](https://github.com/zeek/binpac) to Spicy with zeek-5.2.0. I suspect this setup worked for you before since the `binpac` executable did not depend on libraries from the build. Our plan is to migrate more analyzers in the future and prefer Spicy for new analyzers.

I suggest you build with `CMAKE_BUILD_WITH_INSTALL` disabled (CMake default; RPATH would then be set on install). Alternatively you could configure with `-DUSE_SPICY_ANALYZERS=OFF` (default is `ON`) to instead use the legacy analyzers we kept in tree for the time being, but this will leave you with incomplete and potentially diminishing support going forward.

> cmake knows about MacPorts and also sets some switches.

I see you set `-DCMAKE_BUILD_TYPE=MacPorts`, but I see nothing in the modules from my Homebrew CMake installation making use of it. AFAIK this variable is just a string with some conventions around its use; the Zeek build understands e.g., `Debug`, `Release` or `RelWithDebInfo` values. It does not understand a `MacPorts` value and instead triggers an error:

```
CMake Warning at auxil/spicy/spicy/3rdparty/fiber/cmake/cmake-utils/cmu_detect_env.cmake:66 (message):
  unknown build type: "MacPorts"
Call Stack (most recent call first):
  auxil/spicy/spicy/3rdparty/fiber/cmake/cmake-utils/cmu_detect_env.cmake:299 (cmu_warning)
  auxil/spicy/spicy/3rdparty/fiber/cmake/cmake-utils/cmake-utils.cmake:7 (include)
  auxil/spicy/spicy/3rdparty/fiber/CMakeLists.txt:12 (include)
```

**Comment by Schamschula** [comment]
Indeed: I needed to override `-DCMAKE_BUILD_WITH_INSTALL_RPATH:BOOL=ON` which is set by the cmake 1.1 PortGroup (https://github.com/macports/macports-ports/blob/master/_resources/port1.0/group/cmake-1.1.tcl). It is set by default due to many broken rpaths. I then got a clean build on my work machine.

Why do you expect to see anything other than an error when setting `-DCMAKE_BUILD_TYPE=MacPorts` under Homebrew? cmake knows the difference between the two.

**Comment by bbannier** [comment]
> Why do you expect to see anything other than an error when setting -DCMAKE_BUILD_TYPE=MacPorts under Homebrew? cmake knows the difference between the two.

Your comment made it sound like stock CMake knew anything about MacPorts, but I guess this is something particular about MacPort's CMake instead.

In any case, great you were able to resolve this.
