### ISSUE TITLE
Zeek issues "not a http reply line" in DPD, when dealing with HTTP/0.9 requests

### ISSUE THREAD

**Issue by alsmith** [zeek/zeek#2845]
Zeek issues "not a http reply line" in DPD, when dealing with HTTP/0.9 requests.

Steps to repro:

zeek -r http09-one.pcap; cat dpd.log

**Comment by alsmith** [comment]
This was reported by a Corelight customer, no less.
[http09-one.zip](https://github.com/zeek/zeek/files/10896027/http09-one.zip)

**Comment by alsmith** [comment]
We saw that in live traffic at one of our customers, [http09-one.zip](https://github.com/zeek/zeek/files/10896027/http09-one.zip).

**Comment by timwoj** [comment]
HTTP/0.9 doesn't require a status code from the sender, in that the sender can just reply with HTML data right away. We parse the request line in the first packet correctly but then expect an HTTP 1.0+ formatted response in `HTTP_Analyzer::HTTP_ReplyLine`. When it's not found, we bail out and log an analyzer violation. There's a TODO in that code that reads:

```
		// ##TODO: some server replies with an HTML document
		// without a status line and a MIME header, when the
		// request is malformed.
```

That's exactly what HTTP/0.9 is supposed to do, and shouldn't be considered a malformed request.

**Comment by awelzel** [comment]
`http09-one.pcap` has been extracted from `http_09.pcap` by me and shared with Al to confirm it's the same he's been seeing. May still make sense to have it as a separate test case, because that's the only valid request/reply from that pcap.
