### ISSUE TITLE
zeek detecting SFTP through script and not SFTP through applications like WinSCP and FileZilla

### ISSUE THREAD

**Issue by cyborg1234** [zeek/zeek#2874]
Hi,

Currently, I am testing the capability of zeek in one of my implementation.
I have tried file transfer through a custom-made dashboard which uses SFTP to transfer files from another computer, and zeek is able to detect the traffic and the traffic has protocol 'tcp ssl'.

When I carried out file transfer using applications WinSCP and FileZilla to transfer files from the same computer, zeek is not able to detect it automatically.

One of my guess is that the file transfer applications uses ssh protocol instead.

Would tinkering with zeek backend in terms of the way it detects traffic allows the file transfer using applications be detected? And how do I go about doing the tinkering?

Thank you.

**Comment by awelzel** [comment]
Hi,

We don't use GitHub issues for support questions. Questions like this are best answered using on either slack or our forum, which is both are frequented by Zeek developers and professional users. You can join here:

Forum: https://community.zeek.org/

Slack: https://zeek.org/community/

Please reach out in either of these channels. I'm going to close this ticket for the time being.

> Would tinkering with zeek backend in terms of the way it detects traffic allows the file transfer using applications be detected? And how do I go about doing the tinkering?

It will help developers and other user immensely if you can provide a packet capture (pcap) file of the traffic that you suspect Zeek is not analyzing correctly. If there's a bug or limitation in Zeek found, we can open a new ticket.
