### ISSUE TITLE
vector errors in dovehawk module script

### ISSUE THREAD

**Issue by amrroq** [zeek/zeek#2878]
Trying to debug the [dovehawk](https://github.com/tylabs/dovehawk) zeek module which has seemingly not been supported for a while now....I've already fixed dovehawk.zeek to address the "when" statement referring to locals without an explicit [] capture deprecated functionality, but now I'm getting these errors when I try to start zeek w/ dovehawk:
`error in /opt/zeek/share/zeek/site/dovehawk/./scripts/./dovehawk.zeek, line 120: vector index in "for" loop must be integral (dovehawk::lines)
error in /opt/zeek/share/zeek/site/dovehawk/./scripts/./dovehawk.zeek, line 122: expression with type 'vector' is not a type that can be indexed (dovehawk::lines[line])
error in /opt/zeek/share/zeek/site/dovehawk/./scripts/./dovehawk.zeek, line 122: expression with type 'vector' is not a type that can be indexed (dovehawk::lines[line])
error in /opt/zeek/share/zeek/site/dovehawk/./scripts/./dovehawk.zeek, line 122: expression with type 'vector' is not a type that can be indexed (dovehawk::lines[line])
error in /opt/zeek/share/zeek/site/dovehawk/./scripts/./dovehawk.zeek, line 123: expression with type 'vector' is not a type that can be indexed (dovehawk::lines[line])
error in /opt/zeek/share/zeek/site/dovehawk/./scripts/./dovehawk.zeek, line 123 and string: type mismatch (dovehawk::lines[line] and string)
error in /opt/zeek/share/zeek/site/dovehawk/./scripts/./dovehawk.zeek, line 123: argument type mismatch in function call (gsub(dovehawk::lines[line], /^?(\x0d)$?/, ))
error in /opt/zeek/share/zeek/site/dovehawk/./scripts/./dovehawk.zeek, line 124: expression with type 'vector' is not a type that can be indexed (dovehawk::lines[line])
error in /opt/zeek/share/zeek/site/dovehawk/./scripts/./dovehawk.zeek, line 124 and string: type mismatch (dovehawk::lines[line] and string)
error in /opt/zeek/share/zeek/site/dovehawk/./scripts/./dovehawk.zeek, line 124: argument type mismatch in function call (sub_bytes(dovehawk::lines[line], 0, 10))
error in /opt/zeek/share/zeek/site/scan-NG/./scan-blocked-hotsubnets.zeek, line 91: global variable used in for loop (line)
error in /opt/zeek/share/zeek/site/dovehawk/./scripts/./dovehawk.zeek, line 178: vector index in "for" loop must be integral (dovehawk::lines)
error in /opt/zeek/share/zeek/site/dovehawk/./scripts/./dovehawk.zeek, line 179: expression with type 'vector' is not a type that can be indexed (dovehawk::lines[line])
error in /opt/zeek/share/zeek/site/dovehawk/./scripts/./dovehawk.zeek, line 179 and string: type mismatch (dovehawk::lines[line] and string)
error in /opt/zeek/share/zeek/site/dovehawk/./scripts/./dovehawk.zeek, line 179: argument type mismatch in function call (strip(dovehawk::lines[line]))
error in /opt/zeek/share/zeek/site/dovehawk/./scripts/./dovehawk.zeek, line 182 and string: type mismatch (dovehawk::sig and string)
error in /opt/zeek/share/zeek/site/dovehawk/./scripts/./dovehawk.zeek, line 182: argument type mismatch in function call (split_string(dovehawk::sig, /^?(\t)$?/))
error in /opt/zeek/share/zeek/site/dovehawk/./scripts/./dovehawk.zeek, lines 188-195 and error: type clash for field "desc" ((coerce [$source=MISP, $do_notice=T, $expire=Intel::item_expiration, $desc=dovehawk::parts[3], $url=dovehawk::parts[4], $hits=dovehawk::zero] to Intel::MetaData) and error)
error in /opt/zeek/share/zeek/site/dovehawk/./scripts/./dovehawk.zeek, lines 196-200 and error: type clash for field "indicator" ((coerce [$indicator=dovehawk::parts[0], $indicator_type=Intel::DOMAIN, $meta=dovehawk::dh_meta] to Intel::Item) and error)`

I've done some googling but still don't really understand what the issue is and how to fix it....TIA!

**Comment by awelzel** [comment]
Hello @amrroq - we usually don't discuss package specific issues as GitHub issues here.

I'd suggest you either start a new thread on community.zeek.org, or on zeekorg.slack.com (in the #packages) channel. Opening a GitHub issue in the dovehawk project may help, too (I realize you've done so). It will help if you provide a link to a repository where your updated version of the source code is.

Thanks,
   Arne

**Comment by awelzel** [comment]
FWIW, the following repo contains changes that make the script at least run: https://github.com/awelzel/dovehawk

```
# zeek -i lo ./scripts/
listening on lo

Downloading Signatures 2023/03/17 09:56:24 [1.02.002]
NETSTATS: pkts_dropped=0  pkts_recvd=0  pkts_link=0  bytes_recvd=0
Local Directory: /home/awelzel/corelight-oss/projects/dovehawk/././scripts/.
MISP Server: https://yourmispsite.com/
Please edit config.zeek to include your MISP API key and URL
```

I don't have access to a MISP instance for testing, however, so please get in touch on Slack or the forum and we can work through further fixes or opening a PR for the original repo.

Thanks!

**Comment by amrroq** [comment]
Hi Arne,

Totally understand this is not the proper forum for the question I asked.  Thank you so much for the help you provided despite that.  I'll take a look at that repo and ask in the #packages channel if I still have questions.
