### ISSUE TITLE
Confusion on how exactly ConnPolling::watch works against netcat connections

### ISSUE THREAD

**Issue by TheDumbCatto** [zeek/zeek#2890]
I'm running Zeek latest version on standalone mode, testing out Corelight's [zeek-long-connections](https://github.com/corelight/zeek-long-connections).

In a nutshell, the package uses **ConnPolling::watch** to watch and periodically log (to a new file called `conn_long.log`) connections whose duration exceeds certain thresholds. By default it should fire its' first notice once a connection stays alive for more than 10 minutes.

To test the package's capability, I established a `netcat` connection between **_2 machines' terminals_** (my host machine and the VM running Zeek, with `netcat -lvnp 9100` on one and `netcat x.x.x.x 9100` on the other) and sent some data into that connection every 4 minutes.

First off, even though Zeek only writes to `conn.log` once a connection is terminated, `conn.log` has 2 entries immediately after the netcat connection was initiated, saying that the flow lasted for only 0.021 seconds like so:

![image](https://user-images.githubusercontent.com/82995186/227159600-957df935-1000-4544-b933-cdb446b19212.png)

The connection was alive for at least 20 minutes, and after `netcat` was terminated, `conn.log` adds the final entry, which states that the connection's duration was indeed over 20 minutes:

![image](https://user-images.githubusercontent.com/82995186/227160192-d11daa33-90aa-4f25-afc7-43c1cfaaac3b.png)

However, there were no notices nor `conn_long.log` entries, which suggests that **ConnPolling::watch** didn't actually monitor the connection made by `netcat`. I'm having some difficulty figuring out why, and would appreciate any help available!

**Comment by awelzel** [comment]
Closing this issue as the author started a thread on zeekorg.slack.com.

Most likely culprit are checksum errors as can be seen by the "C" and "cA" histories.
