### ISSUE TITLE
There seems to be a non-recursive version of `Analyzer::FindChild` missing

### ISSUE THREAD

**Issue by bbannier** [zeek/zeek#2899]
Most of the `Analyzer` functions related to the analyzer tree seem to work on direct children (`HasChildAnalyzer`, `AddChildAnalyzer`, `RemoveChildAnalyzer`). The exception is `Analyzer::FindChild` which recurses over the analyzer tree. This is unfortunate, but probably too late to fix.

I came across this while working on zeek/spicy-plugin#198 which is about explicitly manipulating the Zeek analyzer tree in a safe way, e.g., via their `ID`s.

Assume we have built the following analyzer tree where e.g., _Analyzer B_ lives in a separate package or in Zeek proper and we have no knowledge of its internals:

```mermaid
graph TD;
A[Analyzer A]-->B;
B[Analyzer B]--> |2| ASN1[ASN.1];
A--> |1| ASN2[ASN.1];
```

We can detect edge _1_ with `HasChildAnalyzer` since that function does not recurse. If we however naively call `FindChild` we will likely get the analyzer at the end of edge _2_ since this function recurses and performs a depth-first search. The only way to get the analyzer at the end of edge _1_ is to iterate `GetChildren` ourself.

If there was a prominent non-recursive version of `FindChild` we could avoid this pitfall. Alternatively and more cumbersome, if `FindChild` would operate breath-first we could at least use it together with `HasChildAnalyzer` to get the wanted child analyzer.

**Comment by bbannier** [comment]
> The naming makes this unfortunate, but how about `GetChildAnalyzer()`. Minimally fits the naming of the existing ones.

I like that.

One aspect I was missing around me using `GetChildren` and also `FindChild` is they don't do a good job at hiding the different states a child analyzer could be in. For my use case of manually feeding dedicated child analyzers in zeek/spicy#198 I would always need to filter children in `Removing` or `IsFinished` state (I could see a use case for getting finished children, but removing children should probably not be visible anymore for me as an outside user). There are also prevented child analyzers which I probably would want to exclude as well, but I cannot even query that state from the outside.

**Comment by awelzel** [comment]
> One aspect I was missing around me using GetChildren and also FindChild is they don't do a good job at hiding the different states a child analyzer could be in.

Think `GetChildAnalyzer()` should act just the same as `HasChildAnalyzer()`. If it turns out a more powerful API is needed, could consider a fancy `QueryAnalyzers(tags, states, recursive, ...)` I presume?

> There are also prevented child analyzers which I probably would want to exclude as well, but I cannot even query that state from the outside.

:-/
