### ISSUE TITLE
 redef Log::default_logdir has bringed an error "redef" used but not previously defined (Log::default_logdir)""

### ISSUE THREAD

**Issue by jupyzhu** [zeek/zeek#2900]
in local.zeek,add the following statement
@load /usr/local/zeek5.0.5-opt/share/zeek/base/frameworks/logging
redef Log::default_logdir = "/root/log";
save,and run "zeek -i ens41f0 /usr/local/zeek/share/zeek/site/local.zeek". The resulting error is as follows：
“error in /usr/local/zeek/share/zeek/site/local.zeek, line 111: "redef" used but not previously defined (Log::default_logdir)”
my zeek version is 5.2.0.
Who has experienced similar problems and help me?

**Comment by awelzel** [comment]
Hi,

We don't use GitHub issues for support questions. Questions like this are best answered using either slack or our forum, which is both are frequented by Zeek developers and professional users. You can join here:

Forum: https://community.zeek.org/

Slack: https://zeek.org/community/

---

That said:

> @load /usr/local/zeek5.0.5-opt/share/zeek/base/frameworks/logging

If you're using Zeek 5.2, you should not be loading the logging framework from a zeek5.0.5, but instead use the one from 5.2. The more common way to do that is to late with a relative path:
```
@load base/frameworks/logging
```

Try changing the load line and if you still run into errors, please also verify using `zeek --version` that you're actually running 5.2.0.

Thanks,
   Arne
