### ISSUE TITLE
IPTunnel::build_inner_packet: Not keeping wire lengths intact

### ISSUE THREAD

**Issue by awelzel** [zeek/zeek#2914]
Stumbled over in relation to #2907 and #2683.

When building an inner packet, currently `packet->len`, the "wire length", is set to the same as the available "capture length":

https://github.com/zeek/zeek/blob/5718046b967e22ff375c55402e9a877163565719/src/packet_analysis/protocol/iptunnel/IPTunnel.cc#L185

That may not always be right. If the packet was truncated, the wire length of an inner packet should be computed based on the wire length of a more outer packet.

E.g., when analyzing a packet `eth-ip-udp-geneve-eth-ip-tcp-[snaplen-truncated]`, the wire length of the inner IP packet is currently set to the caplen left at that point, rather than to the "wire length" of the outer UDP packet minus the length of the Genve header.

The effect is that the IP analyzer finds the inner IP header invalid due to its header length disagreeing with the packet's wire length, creates a weird and stops. No further packet/protocol analysis is done and have no visibility into further protocols.

**Comment by awelzel** [comment]
The GLB `ip-udp-geneve-ip-udp-vxlan-payload` structure used by AWS may be affected by this when used with a smallish snaplen.

![traffic-mirroring-gwlb-packets](https://user-images.githubusercontent.com/2100509/229188686-dc6f4eeb-dc56-4bf4-a022-a8d24abfe9ea.png)

https://docs.aws.amazon.com/vpc/latest/mirroring/traffic-mirroring-packet-formats.html

We also have #2517 though, so truncated packets may be challenging anyway.

**Comment by awelzel** [comment]
@timwoj pinged me for a pcap, so here it comes: The first one contains two DNS packets encapsulated with geneve then vxlan (vxlan is inner) like the AWS example. The `-truncate` version was produced by running `tcpdump -i <interface> -s 175` to snip away a few bytes off of the DNS packets at the end.

[geneve-vxlan-dns.pcap.zip](https://github.com/zeek/zeek/files/11226708/geneve-vxlan-dns.pcap.zip)
[geneve-vxlan-dns-truncate.pcap.zip](https://github.com/zeek/zeek/files/11226709/geneve-vxlan-dns-truncate.pcap.zip)

For the first one, zeek produces a nice conn.log:
```
{"ts":1630165389.090197,"uid":"Ceox0y1RDIpxMuHvRj","id.orig_h":"172.16.11.201","id.orig_p":36872,"id.resp_h":"1.1.1.1","id.resp_p":53,"proto":"udp","service":"dns","duration":0.04377388954162598,"orig_bytes":54,"resp_bytes":74,"conn_state":"SF","local_orig":true,"local_resp":false,"missed_bytes":0,"history":"Dd","orig_pkts":1,"orig_ip_bytes":82,"resp_pkts":1,"resp_ip_bytes":102,"tunnel_parents":["CM0CTj3bz7QlfzKgIj"]}
{"ts":1630165389.090197,"uid":"CM0CTj3bz7QlfzKgIj","id.orig_h":"127.0.0.1","id.orig_p":26383,"id.resp_h":"127.0.0.1","id.resp_p":4789,"proto":"udp","service":"vxlan","duration":0.04377388954162598,"orig_bytes":228,"resp_bytes":0,"conn_state":"S0","local_orig":true,"local_resp":true,"missed_bytes":0,"history":"D","orig_pkts":2,"orig_ip_bytes":284,"resp_pkts":0,"resp_ip_bytes":0,"tunnel_parents":["Ca2eCM2BO4n1deonB3"]}
{"ts":1630165389.090197,"uid":"Ca2eCM2BO4n1deonB3","id.orig_h":"127.0.0.1","id.orig_p":11803,"id.resp_h":"127.0.0.1","id.resp_p":6081,"proto":"udp","service":"geneve","duration":0.04377388954162598,"orig_bytes":300,"resp_bytes":0,"conn_state":"S0","local_orig":true,"local_resp":true,"missed_bytes":0,"history":"D","orig_pkts":2,"orig_ip_bytes":356,"resp_pkts":0,"resp_ip_bytes":0}
```

For the truncated one, just one conn.log entry for the geneve tunnel, and a weird complaining about the truncated IP header:
```
$ cat conn.log
{"ts":1681421823.895599,"uid":"C7n9Xt4yQfa2Shk3Cd","id.orig_h":"127.0.0.1","id.orig_p":11803,"id.resp_h":"127.0.0.1","id.resp_p":6081,"proto":"udp","service":"geneve","duration":2.000009059906006,"orig_bytes":300,"resp_bytes":0,"conn_state":"S0","local_orig":true,"local_resp":true,"missed_bytes":0,"history":"D","orig_pkts":0,"orig_ip_bytes":0,"resp_pkts":0,"resp_ip_bytes":0}
$ cat weird.log 
{"ts":1681421823.895599,"name":"truncated_IPv6_in_tunnel","notice":false,"peer":"zeek","source":"IP"}
```

Feeding the truncated pcap into `tshark` (or wireshark) they do much better and show the inner connections and even manage to extract info about the DNS payload:
```
$ tshark -r geneve-vxlan-dns-truncate.pcap
    1   0.000000 172.16.11.201 36872 1.1.1.1      53 DNS 182 Standard query 0xfa48 A corelight.com OPT[Packet size limited during capture]
    2   2.000009      1.1.1.1 53 172.16.11.201 36872 DNS 202 Standard query response 0xfa48 A corelight.com A 199.60.103.6[Packet size limited during capture]
```

With [dns-truncated.pcap.zip](https://github.com/zeek/zeek/files/11226770/dns-truncated.pcap.zip), just the original DNS packets truncatd a bit, Zeek doesn't manage to extract DNS information (tshark/wireshark do), so don't expect that to actually work in the tunnel scenario. The gap seemingly is visibility into inner connections.

**Comment by awelzel** [comment]
Hmm - so with the cap-len-fwd fix from #2907 reverted, the results are actually much better, but I suspect because we trusted the wire-length a bit too much, but for reference:
```
root@5f8a656a43a6:/pcaps# zeek -C -r geneve-vxlan-dns-truncate.pcap 
root@5f8a656a43a6:/pcaps# zeek --version
zeek version 5.2.0
root@5f8a656a43a6:/pcaps# zeek -C -r geneve-vxlan-dns-truncate.pcap  LogAscii::use_json=T
root@5f8a656a43a6:/pcaps# cat conn.log 
{"ts":1681421823.895599,"uid":"Chc7rzLVslIONfhGj","id.orig_h":"172.16.11.201","id.orig_p":36872,"id.resp_h":"1.1.1.1","id.resp_p":53,"proto":"udp","service":"dns","duration":2.000009059906006,"orig_bytes":54,"resp_bytes":74,"conn_state":"SF","missed_bytes":0,"history":"Dd","orig_pkts":1,"orig_ip_bytes":82,"resp_pkts":1,"resp_ip_bytes":102,"tunnel_parents":["CqoclF30GreGsgNgz7"]}
{"ts":1681421823.895599,"uid":"CqoclF30GreGsgNgz7","id.orig_h":"127.0.0.1","id.orig_p":26383,"id.resp_h":"127.0.0.1","id.resp_p":4789,"proto":"udp","service":"vxlan","duration":2.000009059906006,"orig_bytes":228,"resp_bytes":0,"conn_state":"S0","missed_bytes":0,"history":"D","orig_pkts":2,"orig_ip_bytes":284,"resp_pkts":0,"resp_ip_bytes":0,"tunnel_parents":["CQoIbN1lX5C2NmFBp4"]}
{"ts":1681421823.895599,"uid":"CQoIbN1lX5C2NmFBp4","id.orig_h":"127.0.0.1","id.orig_p":11803,"id.resp_h":"127.0.0.1","id.resp_p":6081,"proto":"udp","service":"geneve","duration":2.000009059906006,"orig_bytes":300,"resp_bytes":0,"conn_state":"S0","missed_bytes":0,"history":"D","orig_pkts":0,"orig_ip_bytes":0,"resp_pkts":0,"resp_ip_bytes":0}
```

**Comment by timwoj** [comment]
> Hmm - so with the cap-len-fwd fix from https://github.com/zeek/zeek/pull/2907 reverted (not in 5.2.0, but in 5.2.1), the results are actually much better, but I suspect because we trusted the wire-length a bit too much and read some chunk past the actual packet data...

Yep, that's where the lost 6 bytes go. Prior to reverting that, when it gets into the IP analyzer the second time around the len value is 6 bytes shorter than wireshark is showing that it should be. `IPTunnel::build_inner_packet` can recalculate cap_len based on the original difference between the original packet's len and cap_len, but that doesn't help if the len value is already too small.

@J-Gras Did you have a pcap that triggered something strange that was the driver for that PR.

**Comment by J-Gras** [comment]
> Did you have a pcap that triggered something strange that was the driver for that PR?

I didn't see this in the wild. I just thought potentially reading past the valid data could be problematic.

**Comment by timwoj** [comment]
> I didn't see this in the wild. I just thought potentially reading past the valid data could be problematic.

Well, asan definitely doesn't like that truncated pcap with it reverted, so you were probably on to something:

```
=================================================================
==47453==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x00011ba76c50 at pc 0x0001032b871c bp 0x00016ddc8d90 sp 0x00016ddc8d88
READ of size 2 at 0x00011ba76c50 thread T0
    #0 0x1032b8718 in zeek::detail::in_cksum(zeek::detail::checksum_block const*, int) in_cksum.cc:107
    #1 0x10364f868 in zeek::detail::ip4_in_cksum(zeek::IPAddr const&, zeek::IPAddr const&, unsigned char, unsigned char const*, int) net_util.cc:53
    #2 0x102a7f218 in zeek::detail::ip_in_cksum(bool, zeek::IPAddr const&, zeek::IPAddr const&, unsigned char, unsigned char const*, int) net_util.h:193
    #3 0x102b47a78 in zeek::packet_analysis::UDP::UDPAnalyzer::ValidateChecksum(zeek::IP_Hdr const*, udphdr const*, int) UDP.cc:235
    #4 0x102b45cdc in zeek::packet_analysis::UDP::UDPAnalyzer::DeliverPacket(zeek::Connection*, double, bool, int, zeek::Packet*) UDP.cc:139
    #5 0x102b2d518 in zeek::packet_analysis::IP::IPBasedAnalyzer::AnalyzePacket(unsigned long, unsigned char const*, zeek::Packet*) IPBasedAnalyzer.cc:99
    #6 0x102aa7450 in zeek::packet_analysis::Analyzer::ForwardPacket(unsigned long, unsigned char const*, zeek::Packet*, unsigned int) const Analyzer.cc:120
    #7 0x102b24d64 in zeek::packet_analysis::IP::IPAnalyzer::AnalyzePacket(unsigned long, unsigned char const*, zeek::Packet*) IP.cc:296
    #8 0x102aa7450 in zeek::packet_analysis::Analyzer::ForwardPacket(unsigned long, unsigned char const*, zeek::Packet*, unsigned int) const Analyzer.cc:120
    #9 0x102bb05cc in zeek::packet_analysis::Geneve::GeneveAnalyzer::AnalyzePacket(unsigned long, unsigned char const*, zeek::Packet*) Geneve.cc:88
    #10 0x102aa7450 in zeek::packet_analysis::Analyzer::ForwardPacket(unsigned long, unsigned char const*, zeek::Packet*, unsigned int) const Analyzer.cc:120
    #11 0x102b47080 in zeek::packet_analysis::UDP::UDPAnalyzer::DeliverPacket(zeek::Connection*, double, bool, int, zeek::Packet*) UDP.cc:226
    #12 0x102b2d518 in zeek::packet_analysis::IP::IPBasedAnalyzer::AnalyzePacket(unsigned long, unsigned char const*, zeek::Packet*) IPBasedAnalyzer.cc:99
    #13 0x102aa7450 in zeek::packet_analysis::Analyzer::ForwardPacket(unsigned long, unsigned char const*, zeek::Packet*, unsigned int) const Analyzer.cc:120
    #14 0x102b24d64 in zeek::packet_analysis::IP::IPAnalyzer::AnalyzePacket(unsigned long, unsigned char const*, zeek::Packet*) IP.cc:296
    #15 0x102aa7450 in zeek::packet_analysis::Analyzer::ForwardPacket(unsigned long, unsigned char const*, zeek::Packet*, unsigned int) const Analyzer.cc:120
    #16 0x102aed3fc in zeek::packet_analysis::Ethernet::EthernetAnalyzer::AnalyzePacket(unsigned long, unsigned char const*, zeek::Packet*) Ethernet.cc:51
    #17 0x102aa7450 in zeek::packet_analysis::Analyzer::ForwardPacket(unsigned long, unsigned char const*, zeek::Packet*, unsigned int) const Analyzer.cc:120
    #18 0x102abe6c4 in zeek::packet_analysis::Manager::ProcessPacket(zeek::Packet*) Manager.cc:131
    #19 0x103d33a14 in zeek::run_state::detail::dispatch_packet(zeek::Packet*, zeek::iosource::PktSrc*) RunState.cc:290
    #20 0x10307b020 in zeek::iosource::PktSrc::Process() PktSrc.cc:160
    #21 0x103d34b1c in zeek::run_state::detail::run_loop() RunState.cc:349
    #22 0x1048cd4e4 in main main.cc:102
    #23 0x1812f3f24  (<unknown module>)
```

**Comment by timwoj** [comment]
Ugh, the `geneve-truncated.pcap` capture we have in the traces library acts differently. I'm going to have to rethink how I did this. The length of the first IP header in the vxlan pcap is set as if it was the full packet, even tho it's been truncated. The `len` value being passed into `IPAnalyzer::AnalyzePacket` is smaller than the total len in the IP header. In the other pcap, it's set as if it wasn't truncated even though the packet's cap_len is set correctly to match the truncation.

**Comment by awelzel** [comment]
> The length of the first IP header in the vxlan pcap is set as if it was the full packet, even tho it's been truncated.

This should be expected. The geneve-vxlan-dns-truncate was produced with `tcpdump -s` and tcpdump will not update any length fields of headers, just truncate and set the fields in the pcap packet header accordingly.

>  In the other pcap, it's set as if it wasn't truncated even though the packet's cap_len is set correctly to match the truncation.

[assuming "the other pcap" being `geneve-truncated.pcap`]

Hmm, yes, this is curious/confusing. The lengths within IP/UDP aligns with `cap_len` and  not with the wire length as indicated from the pcap packet header. That doesn't make much sense and mostly hints at an inconsistency somewhere. We should obviously not fail completely, but also be suspicious..

In fact, if I hexedit down wire length to 58 bytes wire length and run the test this is used for it works just the same.

@J-Gras, how was geneve-truncated.pcap produced?

![Screenshot-20230502-131150](https://user-images.githubusercontent.com/2100509/235650985-e4e0c500-80f3-486a-bd7f-cf1b1d82c1b1.png)

**Comment by J-Gras** [comment]
> how was geneve-truncated.pcap produced?

The PCAP was handcrafted. @mari0d might be able to provide more details.

**Comment by mari0d** [comment]
I'm not familiar with this pcap. However, the pcapng meta suggests it was produced with `editcap` if that helps any...

**Comment by J-Gras** [comment]
Then it must have been me tinkering with the PCAP 🤔  The PCAP seems to be a truncated version of the first packet from `geneve.pcap`. As pointed out, it's just "the inner packet" that is truncated. So the scenario would be some endpoint encapsulated a truncated packet/garbage. Not sure what the odds would be to see this in the wild.

> Hmm, yes, this is curious/confusing. The lengths within IP/UDP aligns with cap_len and not with the wire length as indicated from the pcap packet header. That doesn't make much sense and mostly hints at an inconsistency somewhere.

Assuming the above scenario, the wire length in the PCAP header would be the inconsistency here.
