### ISSUE TITLE
Add a parse_json() bif

### ISSUE THREAD

**Issue by awelzel** [zeek/zeek#2915]
If we had a bif that could parse a JSON formatted string to a record (even if of anonymous type), that would allow reading input data in JSON lines format through an input reader and converting to Zeek records in an appropriate handler for ingestion.

One idea was the following API, very informal:
```
type ParseJsonResult: record {
    valid: bool;
    error: string;
    rec: any;
}

## Parse s and convert into record. If typ is provided, result$rec is of type `typ` and field conversion happens as expected best-effort.
parse_json(s: string, options: typ: any &optional): ParseJsonResult
```

But, I could also see keeping `typ` out for now and returning an anonymous record of usual JSON types, leaving any type conversions to script writers using `to_addr()` to convert from strings to addr.

**Comment by timwoj** [comment]
This is actually on a list of things that @sethhall and I talked about a long long time ago:

> JSON Importing
> 
> - Load directly into a record type of some sort
> - BIF method for parsing JSON as a response from an event

It's one of those "someday" tasks that I just haven't ever gotten around to.

**Comment by AmazingPP** [comment]
> I've got a message on Slack pointing at @AmazingPP 's [zeek-json](https://github.com/AmazingPP/zeek-json) plugin. Maybe we can just pick that up or use for inspiration?

I would be happy to contribute this feature. Is there anything I can help :)

**Comment by awelzel** [comment]
> I would be happy to contribute this feature. Is there anything I can help :)

Thanks. If I'm skimming correctly, your plugin supports the basic JSON types, but there would be no magic string to IP addr conversion, or string to enum values. Without some type magic within `from_json()`, one would first load into a record type with basic JSON types, then convert into a nicely typed Zeek record type within Zeek script (e.g an Intel::Item). Is that how you're using it? We might be missing some conversion to make that all work though (not sure we have `to_enum(s: string): any`, for example).

In a different area: I've now added a test loading intel data from a `.json_lines` file using JavaScript from within Zeek. I've found some issues :sweat_smile: - but mostly works as expected:
https://github.com/zeek/zeek/blob/067a40bf8d37fbaf068e5951ec580fb5ed6a25c7/testing/btest/javascript/intel.js#L22-L32

Though, that plugin does type magic to make it look seamless. Not sure it's worth adding that all to `from_json()`, because this might just be an area better suited to be offloaded.

**Comment by AmazingPP** [comment]
> @AmazingPP - do you want to try integrating your `from_json(...)` into Zeek? Possibly extended to handle addr, subnet, enum and what else comes up :-)

No problem, I will try to implement it in the next few days and create an RP. I may need to discuss some details with you while implementing the code.

**Comment by ckreibich** [comment]
> After chatting a bit with @rsmmr, a bit of type magic similarly to the input readers might be good (addr, subnet, enum come to mind).

I believe this is already obvious to all involved, but the idea was that this function is a step-stone on the way to supporting JSON data in the input framework. So the above strikes me as the right goalpost.

@AmazingPP, thanks for helping out! Feel free to start sharing the PR in early stages, better to iterate closely on this one.

**Comment by AmazingPP** [comment]
I'm sorry for replying so late. I've been trying to implement implicit conversion of extension types more elegantly lately.

I understand that we want to have implicit conversions for them, but I think we should limit the parsing of JSON strings to only the basic types supported by the JSON standard. This way, we can avoid potential issues with type mismatches or data loss that could happen with implicit conversions.

For example, in JavaScript, `JSON.parse()` doesn't support parsing JSON strings into `Date`. Instead, developers have to use explicit constructor. This approach not only ensures that the data is parsed correctly, but also makes the code more readable and maintainable.

So, I suggest that we implement basic type parse only, let user use explicit conversion functions to convert into enum,addr types. This approach would be safer and more in line with industry best practices.

Let me know what you think. Thanks!

**Comment by AmazingPP** [comment]
Can we consider adding an optional parameter for explicit conversion, similar to TypeScript:

Assuming we have a TypeScript class MyClass that contains a property of type `Date`, like this:
```ts
class MyClass {
  id: number;
  name: string;
  date: Date;
}
```
Now, let's say we have a JSON string jsonString that represents an instance of the `MyClass` class, like this:
```json
{
  "id": 1,
  "name": "John",
  "date": "2022-03-14T09:00:00.000Z"
}
```
To parse this JSON string into an instance of the `MyClass` class, we can use the following code:
```ts
const myClassObject = JSON.parse(jsonString, (key, value) => {
  if (key === 'date') {
    return new Date(value);
  }
  return value;
}) as MyClass;
```
In the code above, the `JSON.parse()` method accepts an optional second parameter, which is a function that is used to convert property values while parsing the JSON string. In this function, we check if the name of the property is date, and if it is, we convert the property value to a `Date` object. If it is not, we return the original value.

Note that the `JSON.parse()` method returns a value of type any. To convert it to an instance of the `MyClass` class, we use a type assertion with the `as` keyword.

**Comment by awelzel** [comment]
> So, I suggest that we implement basic type parse only, let user use explicit conversion functions to convert into enum,addr types. This approach would be safer and more in line with industry best practices.

We do have implicit type conversions within the Input framework from strings and it's not too surprising how these work - that was the motivation. With JSON defining a few types, it seems that mostly leaves string to subnet, port, addr or enum values.

https://github.com/zeek/zeek/blob/master/src/threading/formatters/Ascii.cc#L209

> To parse this JSON string into an instance of the MyClass class, we can use the following code:
> const myClassObject = JSON.parse(jsonString, (key, value) => {

I can see the callback also in Zeek script. Not sure an initial implementation would really need it though, unless there's more objections against the implicit type conversions.
