### ISSUE TITLE
Add `log2` function

### ISSUE THREAD

**Issue by ynadji** [zeek/zeek#2931]
We have `ln` and `log10` but no `log2`.

**Comment by ofekkr1** [comment]
Hi,
may I work on this issue?

**Comment by ckreibich** [comment]
@ofekkr1, absolutely. Take a look [here](https://github.com/zeek/zeek/blob/master/src/zeek.bif#L1719-L1741) for an example, and just place yours alongside.

**Comment by ofekkr1** [comment]
@ckreibich I'm having some issues setting the environment for the project.
when I'm trying to run ```./configure && make && sudo make install``` (according to what the README.md says) , Im having this error:
![error](https://user-images.githubusercontent.com/94454456/234030382-744cf4eb-f7b9-4e50-b634-33c77d67246e.png)
I have tried searching for a solution on the internet, but nothing seems to fit for that case.
Any idea what is causing this issue?

**Comment by ynadji** [comment]
i'm not expert but i wonder if mingw64 just isn't supported? can you try it in wsl to see if that fixes the issue?

**Comment by timwoj** [comment]
I'd be really surprised if mingw built directly, to be honest. The only officially supported build system on WIndows right now is Visual Studio.

**Comment by awelzel** [comment]
@ofekkr1 - you could try the [Writing Plugins](https://docs.zeek.org/en/master/devel/plugins.html) tutorial with a supported development environment and see if you can get the examples to work.

If you run into issues, feel free to ask questions in the `#development` Slack channel.
