### ISSUE TITLE
Build of external packages can't find zeek/binpac.pac

### ISSUE THREAD

**Issue by timwoj** [zeek/zeek#2932]
Something changed between 5.1 and 5.2 that breaks the build for packages that contain binpac code. Using https://github.com/cisagov/icsnpp-bsap as an example:

```
[  7%] [BINPAC] Processing src/bsap.pac
/Users/tim/Desktop/projects/packages/clones/icsnpp-bsap/src/bsap.pac:10: error: cannot include file "zeek/binpac.pac"
make[2]: *** [bsap_pac.h] Error 1
make[1]: *** [CMakeFiles/pac-bsap.pac.dir/all] Error 2
make: *** [all] Error 2
```

It's currently failing on both release/5.2 and master but builds on release/5.1.

**Comment by timwoj** [comment]
I bisected between the v5.2.0-dev and master:

```
a8fc63e182d40781ab6c15b80d1cf0b344037e29 is the first bad commit
commit a8fc63e182d40781ab6c15b80d1cf0b344037e29
Merge: 2739275b8 642d44009
Author: Tim Wojtulewicz <tim@corelight.com>
Date:   Fri Nov 11 15:13:47 2022 -0700

    Merge remote-tracking branch 'microsoft/master'
```

**Comment by timwoj** [comment]
I also double checked @Neverlord's cmake redesign branch and it's still busted there too. I'm less concerned about fixing it on that PR though because it's not making it any worse.

**Comment by awelzel** [comment]
Speculatively closing based on: https://github.com/zeek/cmake/pull/64#issuecomment-1513680756
