### ISSUE TITLE
Zeek only recognized unidirection packets. The 'orig_pkts' or 'resp_pkts' is 0.

### ISSUE THREAD

**Issue by fdfdsf** [zeek/zeek#2934]
Hi, all
When I used zeek to parse one small pcap file, zeek only recognized unidirection packets. The 'orig_pkts' or 'resp_pkts' is 0 in conn.log. For example: 
```
#fields	ts	uid	id.orig_h	id.orig_p	id.resp_h	id.resp_p	proto	service	duration	orig_bytes	resp_bytes	conn_state	local_orig	local_resp	missed_bytes	history	orig_pkts	orig_ip_bytes	resp_pkts	resp_ip_bytes	tunnel_parents
1519130020.242980	C6AulC2g3h5R3KdvF9	172.31.65.42	49197	104.107.44.44	443	tcp	-	0.251281	0	10551	OTH	-	-	0	^had	0	0	11	11003	-
```
![image](https://user-images.githubusercontent.com/13058939/230552709-3b57f0d7-ce6d-4aa0-a21e-6490504fcb1d.png)

As the results above, the 'resp_pkts' is 11, but the 'orig_pkts' is 0. In reality, this flow contains 21 packets, the value of 'orig_pkts' should be 10. 
And, When I use another tool, such as brim or wireshark, all the packets can be recognized. 
![image](https://user-images.githubusercontent.com/13058939/230552617-6f17fe16-bb2a-40b7-b9f4-2937a2db4218.png)

I don't know why it occurs. And, sometimes, the 'resp_pkts' is 0, and the is 'orig_pkts' non-zero. It looks like the zeek only recognized unidrection pakcets.

**Comment by fdfdsf** [comment]
[capWIN-J6GMIG1DQE5-172.31.65.42.zip](https://github.com/zeek/zeek/files/11195874/capWIN-J6GMIG1DQE5-172.31.65.42.zip)
the pcap file used in the example.

**Comment by JustinAzoff** [comment]
Your pcap has invalid checksums. You need to run zeek with the `-C` option.
