### ISSUE TITLE
High memory usage in 5.0.8 by monitoring_thread_loop in Rocky 9 with Docker

### ISSUE THREAD

**Issue by TOoSmOotH** [zeek/zeek#2951]
When using a docker image of Zeek 5.0.8 using Rocky 9 as the container OS and Rocky 9 as the host OS, I see heavy memory usage with each one of the zeek processes. Its around 8GB per process.

jemalloc profiling:
`{"func": "monitoring_thread_loop", "direct_mb": 8192.0, "direct_pct": 98.8, "direct_pct_cumm": 98.8, "callees_mb": 8192.0, "callees_pct": 98.8}`

I also saw this in 5.0.7

**Comment by timwoj** [comment]
`monitoring_thread_loop` is spawned by libkqueue. I'll see if those guys have run into this as well. Some notes from the Slack thread:

- Also happens with a standalone zeek process
- Doesn't happen on other platforms tested

**Comment by TOoSmOotH** [comment]
With jemalloc profiling we were able to determine the monitoring_thread_loop was grabbing the extra memory. Per @JustinAzoff the loop grabs the max number of file descriptors and allocates 2 arrays of ints. The root cause is containerd on R9 identifies the file limit to be infinity which really translates to `1073741816`. Setting the files limits to something more sane such as `1048576` fixes the issue.

You can change the `LimitNOFILE=1048576` in `/usr/lib/systemd/system/containerd.service` to fix the issue or target the zeek container with the limit directly.

**Comment by timwoj** [comment]
I opened a ticket with libkqueue for this: https://github.com/mheily/libkqueue/issues/153
