### ISSUE TITLE
How to optimize RuleEndpointState * RuleMatcher:: InitEndpoint function

### ISSUE THREAD

**Issue by wubonetcn** [zeek/zeek#2956]
I spent several weeks debugging the possible memory leak points of zeek line by line. I created a new file called ha.sig, which contains 20000 signatures and loaded ha.sig in local.zeek. My testing environment is an 80 core CPU with 250GB of memory, using multiple zeek processes and a professional device to generate 30000 new HTTP concurrent connections in the network. This will result in an additional 5GB of memory per second, quickly filling up 250GB of memory, and I have to kill the zeek process.The zeek version I tested is 5.2.0.
I found that in the RuleEndpointState * RuleMatcher:: InitEndpoint function in the RuleMatcher.cc file
If I annotate the following code, there will be no memory leak.
```
//auto* m = new RuleEndpointState::Matcher;
//m->state = new RE_Match_State(set->re);
//m->type = (Rule::PatternType)i;
//state->matchers.push_back(m);
```
And strangely, I saw in the RuleEndpointState::~RuleEndpointState() function that delete match ->state was written;
I see that the matcher has been destroyed here, but why won't memory leak occur once I annotate the above code?
How can I optimize this code?

**Comment by awelzel** [comment]
>and a professional device to generate 30000 new HTTP concurrent connections in the network. This will result in an additional 5GB of memory per second, quickly filling up 250GB of memory, and I have to kill the zeek process.
> but why won't memory leak occur once I annotate the above code?

What you describe might not be a memory leak, but the required memory at such loads with such a configuration. Could you try to run with 3000 or 15000 concurrent connections and see if memory usage stabilizes. If it doesn't stabilize, would it be possible to provide a setup with a sample minimal ha.sig file and sample pcap so that this can be reproduced with tcpreplay?

Further, could you provide the code changes in form of a `diff` so it's easier to recognize where you did those changes?

**Comment by 0xxon** [comment]
Also - to add to this question - could you share details about the 20,000 signatures you are loading?

**Comment by wubonetcn** [comment]
Thank you very much. I'll give you ha.sig first

[ha.zip](https://github.com/zeek/zeek/files/11272989/ha.zip)

**Comment by wubonetcn** [comment]
I generated 3Gbps of traffic through Spirent's professional device, which is a small portion of what I intercepted using tcpdump. I am not sure if tcpreplay can achieve the same simulation effect.
[spirent-tc-mix_flow-100k.zip](https://github.com/zeek/zeek/files/11273079/spirent-tc-mix_flow-100k.zip)
