### ISSUE TITLE
String with embedded NUL Errors related to IRC(ish) traffic analysis

### ISSUE THREAD

**Issue by dwdixon** [zeek/zeek#297]
Hi there, I've also been seeing this error for many months now, first while running master prior to the official release of 2.6.1, but after moving to running 2.6.1 release  I noticed that I'm still seeing this error, it looks like the NUL maybe isn't handled properly?  I'm not totally sure, even though the NUL I don't think is supposed to be there (probably not following the RFC for the IRC protocol)... is throwing this error the proper way to address/handle that?

```
Reporter::ERROR string with embedded NUL: "jaK\\x00\\x00\\x00\\x00\\x00jaK\\x00\\x00\\x00\\x00\\x00jaK\\x00\\x00\\x00\\x00\\x00jaK\\x00\\x00\\x00\\x00\\x00jaK\\x00\\x00\\x00\\x00\\x00BYE"     (empty)
Reporter::ERROR string with embedded NUL: "P\\x00\\x01*ACK"     (empty)
Reporter::ERROR string with embedded NUL: "P\\x00\\x01\\xaaMESSAGE"     (empty)
Reporter::ERROR string with embedded NUL: "P\\x00\\x01XMESSAGE" (empty)
Reporter::ERROR string with embedded NUL: "P\\x00\\x01oMESSAGE" (empty)
Reporter::ERROR string with embedded NUL: "P\\x00\\x01*ACK"     (empty)
Reporter::ERROR string with embedded NUL: "P\\x00\\x01*ACK"     (empty)
Reporter::ERROR string with embedded NUL: "P\\x00\\x01_INVITE"  (empty)
Reporter::ERROR string with embedded NUL: "jaK\\x00\\x00\\x00\\x00\\x00jaK\\x00\\x00\\x00\\x00\\x00jaK\\x00\\x00\\x00\\x00\\x00jaK\\x00\\x00\\x00\\x00\\x00jaK\\x00\\x00\\x00\\x00\\x00jaK\\x00\\x00\\x00\\x00\\x00jaK\\x00\\x00\\x00\\x00\\x00jaK\\x00\\x00\\x00\\x00\\x00REGISTER"      (empty)
Reporter::ERROR string with embedded NUL: "jaK\\x00\\x00\\x00\\x00\\x00jaK\\x00\\x00\\x00\\x00\\x00jaK\\x00\\x00\\x00\\x00\\x00jaK\\x00\\x00\\x00\\x00\\x00jaK\\x00\\x00\\x00\\x00\\x00jaK\\x00\\x00\\x00\\x00\\x00jaK\\x00\\x00\\x00\\x00\\x00jaK\\x00\\x00\\x00\\x00\\x00jaK\\x00\\x00\\x00\\x00\\x00jaK\\x00\\x00\\x00\\x00\\x00REGISTER"      (empty)

**Comment by jsiwek** [comment]
Hi, it is possibly indicating some bug or improvement that could be made, but it's hard to tell from just the error messages which code path is responsible for emitting them.  It would be best if you could provide a pcap file that reproduces the errors, or, if you can't share that, give a call stack trace that pinpoints file/line information to pinpoint where those errors are generated.

**Comment by timwoj** [comment]
@dwdixon Bringing this issue back up again, do you have a pcap that reproduces this or can we close it out for now?

**Comment by dwdixon** [comment]
Hi there, I'm not sure that I have enough to go on to easily narrow down getting a useful pcap to help get to the bottom of this atm.  I think maybe down the line I could spend some time on trying to get a useful pcap but that wouldn't be anytime in the near future unfortunately.  I'll leave it up to you all if you want to leave the issue open and we can circle back later or if you want to close it for now and I can re-open if I'm still seeing this error once I'm able to circle back to spending some time digging into this on our end.  Thanks for reaching out and all you do! : )

**Comment by timwoj** [comment]
I'll go ahead and close it for now. If you run across it again and can get a sample, feel free to reopen it.
