### ISSUE TITLE
Cirrus CI timeouts due to hanging tests

### ISSUE THREAD

**Issue by awelzel** [zeek/zeek#2987]
Tim opened a PR to add verbose logging of completed tests: https://github.com/zeek/zeek/pull/2816

I'm unable to find any bread-crumbs about follow-ups, but observed two timeouts today. One with [arm_debian11](https://cirrus-ci.com/task/4651603739803648) and one with [asan_sanitizer](https://cirrus-ci.com/task/5969497450872832?logs=test#L0).

The missing and supposedly hanging test was `doc.zeekygen.package` in the first and `doc.zeekygen.identifier` in the second. Might hint at something with the zeekygen subsystem / test setup.

Script to compare two Cirrus CI test.log files:
```
#!/bin/bash
# diff-test-log.sh
set -eux

function tests {
    sed -E -n  's/^\[#[ 0-9]*\]\s*(.*)\s+\.\.\..*$/\1/p' < $1 | sort
}

diff -u <(tests $1) <(tests $2)
```

[asan_timeout_pr.log](https://github.com/zeek/zeek/files/11344184/asan_timeout_pr.log)
[debian11.log](https://github.com/zeek/zeek/files/11344185/debian11.log)
[arm-debian11.log](https://github.com/zeek/zeek/files/11344186/arm-debian11.log)

**Comment by timwoj** [comment]
`doc.zeekygen.package_index` was the one that I had seen timeout before, but I never dug into exactly what it was doing that was taking so long.

**Comment by timwoj** [comment]
> Maybe we should add a timeout to btest itself so it can fail cleanly ahead of Cirrus' timeout. None of our tests should take more than a couple of minutes at the longest.

Looking really briefly at btest, we use `subprocess.Popen` followed by `Popen.communicate` when we run the individual processes. `communicate` has a timeout argument, which would let us fail if it hits that.

**Comment by awelzel** [comment]
This one timed out for me last week as well, misses `doc.zeekygen.identifier`.
https://cirrus-ci.com/task/5446879278792704

Seems this is happen fairly regular and somehow `doc.zeekygen.*` related.

**Comment by awelzel** [comment]
> We also use subprocess.check_call which also has a timeout argument.

Hmm, skimming `btest` there are other places. For example, i think this isn't safe at all:

https://github.com/zeek/btest/blob/master/btest#L379-L382

If a test subprocess is killed with `kill -9` or by an oom-killer this might just hang forever waiting for something to show up in the queue. So the `get()` would also need a timeout.

**Comment by timwoj** [comment]
Another possible timeout point is the joins on processes from `mutliprocess`.

**Comment by timwoj** [comment]
I'm frequently seeing timeouts for the cluster-testing build: https://cirrus-ci.com/task/5393991806484480

**Comment by timwoj** [comment]
We haven't seen this one in a while. Closing.
