### ISSUE TITLE
`@unload` doesn't work with packages installed with `zkg`

### ISSUE THREAD

**Issue by ynadji** [zeek/zeek#2991]
If I am `@unload`ing then `@load`ing zeek files, it works as expected:

```
$ cat foo.zeek
event zeek_init() { print "foo!"; }
$ cat load.zeek
@load ./foo
$ cat load-unload.zeek
@unload ./foo
@load ./foo
$ zeek ./load.zeek
foo!
$ zeek ./load-unload.zeek
```

But if I do it with a package installed by `zkg` it doesn't work and an `@unload`ed package still gets `@load`ed.

```
$ cat load.zeek
@load packages/foo
$ cat load-unload.zeek
@unload packages/foo
@load packages/foo
$ zkg list | grep foo
/Users/yacin.nadji/code/foo (installed: main) - TODO: A more detailed description of Foo.
$ cat /usr/local/share/zeek/site/packages/foo/main.zeek
module Foo;

event zeek_init()
        {
        print "foo!";
        }
$ zeek -e 'print 1;'
1
$ zeek ./load.zeek
foo!
$ zeek ./load-unload.zeek
foo!
```

```
$ zeek --version
zeek version 5.2.0-dev.435
$ zkg --version
zkg 2.13.0-3
```

**Comment by J-Gras** [comment]
I guess this expected. The issue is probably the loading sequence. See [docs](https://docs.zeek.org/en/master/script-reference/directives.html#unload):
> However, if the specified script has already been loaded, then this directive has no affect.

You can verify by loading `policy/misc/loaded-scripts`. Would `zkg unload` be an option in your use case?

**Comment by awelzel** [comment]
> I guess this is expected. The issue is probably the loading sequence. See [docs](https://docs.zeek.org/en/master/script-reference/directives.html#unload):

Nah, this is not expected. I think there's a bug or minimal silent surprise. The `'zeek -e print 1;'` indicates the package isn't loaded. This isn't about `zkg` either.

The `@unload <directory>` marks/prevents the directory path from being loaded. That isn't sensible, as a `@load <directory>` resolves the  `__load__.zeek` file instead and loads that. The workaround is `@unload packages/foo/__load__.zeek`.

**Comment by awelzel** [comment]
> let me know if i should make a separate issue for this.

Hmm - it should use a fully resolved path, so that's a bit surprising, though in the presence of various ZEEKPATH and possibly symlinks (?) things could fall apart. If you have an "easy" reproducer with Zeek base, that would help. New ticket would be better.

**Comment by awelzel** [comment]
Also, because I hadn't said that: You should probably not be using `@unload` if you can avoid it :-)

**Comment by ynadji** [comment]
> Also, because I hadn't said that: You should probably not be using `@unload` if you can avoid it :-)

hahahaha i'm going `@unload` even *harder* now.

>  If you have an "easy" reproducer with Zeek base, that would help. New ticket would be better.

ok! i'll see what i can put together here. wouldn't be surprised if it's because of something weird we're doing.
