### ISSUE TITLE
Include DF, MF and frag offset in ip4_hdr

### ISSUE THREAD

**Issue by awelzel** [zeek/zeek#2994]
@multicast-bytes attempted to use Zeek for packet-level analysis and was missing DF, MF and frag offset from ip4_hdr when using `new_packet()`.

He also mentioned that IPv4 options aren't currently available in script-land unless I've missed something obvious.
https://en.wikipedia.org/wiki/Internet_Protocol_version_4#Options

https://docs.zeek.org/en/master/scripts/base/init-bare.zeek.html#type-ip4_hdr

**Comment by awelzel** [comment]
Partly addressed by PR #3000 .

@multicast-bytes: Had you found anything for IPv4 options? I've crunched the pcaps in testing/ for one with a header length != 20 and nothing turned up. Also nothing immediate online. If you have a sample pcap with options that you can share, that would help, otherwise think skipping ip4_options may be sensible, too.

**Comment by multicast-bytes** [comment]
> @multicast-bytes attempted to use Zeek for packet-level analysis and was missing DF, MF and frag offset from ip4_hdr when using `new_packet()`.
> 
> He also mentioned that IPv4 options aren't currently available in script-land unless I've missed something obvious. https://en.wikipedia.org/wiki/Internet_Protocol_version_4#Options
> 
> https://docs.zeek.org/en/master/scripts/base/init-bare.zeek.html#type-ip4_hdr

Hey,
Thanks for the super quick response.

Yes I was looking into Zeek's packet-level analysis potential (packet and not event based).
As I have a usecase to collect other artefacts from the IP header that didn't seem to be present.

Clearly this usecase is not typical as it's using `new_packet().` which I know isn't advised for typical installs.

**Comment by multicast-bytes** [comment]
Definitely agree to de-scope IP Options here as it's not often used.
 It's one of those vestigial items that's in the RFC spec, but does not often seen in the modern day.

I guess from a network visibility perspective, historical threats that sit in there are source routing - but this could be considered _vintage_ .
> Loose Source and Record Route (LSRR): https://www.rfc-editor.org/rfc/rfc791

As I am sure you will have read, IP Options are.. optional and all pcaps in my library don't populate this.
I think if this is truly required, it should split out as a seperate item for cleanness.?

> https://www.iana.org/assignments/ip-parameters/ip-parameters.xhtml#ip-parameters-1


<img width="974" alt="image" src="https://user-images.githubusercontent.com/110049134/235627463-b836409d-04df-41b6-a485-a3e2f3045cb7.png">

**Comment by awelzel** [comment]
> I think if this is truly required, it should split out as a seperate item for cleanness.?

I've removed them from the subject. I agree with a new issue. If you find a use-case and can share a pcap a new issue makes sense.

**Comment by awelzel** [comment]
@multicast-bytes , the latest dev snapshot now has the fields in the ip4_hdr:
```
$ docker pull zeek/zeek-dev; docker run --rm -it -v $(pwd)/Traces:/Traces zeek/zeek-dev
...
Digest: sha256:1f6296c688c0fd026c294be4baeb1ec84c4eee4249a739a5541cb3820f5ad7e1
Status: Downloaded newer image for zeek/zeek-dev:latest
docker.io/zeek/zeek-dev:latest
root@b19dddf44dc1:/# zeek -Cr Traces/ipv4/fragmented-1.pcap  -e 'event raw_packet(hdr: raw_pkt_hdr) { print hdr$ip; }'
[hl=20, tos=0, len=38, id=242, DF=F, MF=T, offset=0, ttl=64, p=17, sum=6898, src=164.1.123.163, dst=164.1.123.61]
[hl=20, tos=0, len=136, id=242, DF=F, MF=F, offset=48, ttl=64, p=17, sum=14986, src=164.1.123.163, dst=164.1.123.61]
[hl=20, tos=0, len=324, id=242, DF=F, MF=T, offset=0, ttl=64, p=17, sum=6898, src=164.1.123.163, dst=164.1.123.61]
root@b19dddf44dc1:/# zeek --version
zeek version 6.0.0-dev.480
```

Closing.
