### ISSUE TITLE
Detecting (some) misordered UDP

### ISSUE THREAD

**Issue by vpax** [zeek/zeek#2998]
I've just been bitten by packet capture reordering mis-identifying the directionality of an NTP request/response.  In this environment, I can deal with this readily for TCP by looking at `$history` and making sure I have clean `Sh`... handshakes, but for UDP this connection showed `Dd` even though, conceptually, it _should_ have shown `dD`.

Some UDP protocols, such as NTP and DNS, have client/server information inside the messages themselves.  It'd be great if there were analyzer hooks that would allow this sort of information to make it into the connection history.

I've attached a PCAP I edited up to demonstrate this problem for NTP. 
[misordered-ntp.pcap.gz](https://github.com/zeek/zeek/files/11356803/misordered-ntp.pcap.gz)

**Comment by awelzel** [comment]
> Some UDP protocols, such as NTP and DNS, have client/server information inside the messages themselves. It'd be great if there were analyzer hooks that would allow this sort of information to make it into the connection history.

For DNS it appears this is handled (or minimally attempted) and the call to `FlipRoles()` should add the `^`. Any chance you have a shareable pcap where it's not happening for DNS?

https://github.com/zeek/zeek/blob/bef1d510155e2edef18e556dc11596b8e1eac001/src/analyzer/protocol/dns/DNS.cc#L44-L52

(there's no such logic in the existing NTP analyzer)

**Comment by vpax** [comment]
Where I observed it was indeed for NTP.  I'll see if I can share a PCAP.
