### ISSUE TITLE
errors while installing

### ISSUE THREAD

**Issue by slsanna** [zeek/zeek#3001]
I am following the guide for installing zeek on my linux machine (kali). But the make process stops everytime at 92% with the following error. I tried many things such as installing broker, searched on Google but found nothing useful. Can you help me solving this?

[ 92%] Linking CXX shared module ../../python/broker/_broker.so
lto-wrapper: warning: using serial compilation of 15 LTRANS jobs
lto-wrapper: note: see the ‘-flto’ option documentation for more information
/usr/bin/ld: /usr/local/lib/python3.7/config-3.7m-x86_64-linux-gnu/libpython3.7m.a(bltinmodule.o): warning: relocation against `PyFilter_Type' in read-only section `.text'
/usr/bin/ld: /usr/local/lib/python3.7/config-3.7m-x86_64-linux-gnu/libpython3.7m.a(abstract.o): relocation R_X86_64_PC32 against symbol `PyDict_Type' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[3]: *** [auxil/broker/bindings/python/CMakeFiles/_broker.dir/build.make:164: auxil/broker/python/broker/_broker.so] Error 1
make[3]: Leaving directory '/home/kali/zeek/build'
make[2]: *** [CMakeFiles/Makefile2:4297: auxil/broker/bindings/python/CMakeFiles/_broker.dir/all] Error 2
make[2]: Leaving directory '/home/kali/zeek/build'
make[1]: *** [Makefile:166: all] Error 2
make[1]: Leaving directory '/home/kali/zeek/build'
make: *** [Makefile:15: all] Error 2

**Comment by Neverlord** [comment]
I can't tell why it fails to compile, but if you don't need the Python bindings for Broker, you could exclude it as a workaround. This should do the trick:

```
./configure -D DISABLE_PYTHON_BINDINGS=ON
```

**Comment by awelzel** [comment]
We don't use GitHub issues for support questions. Questions like this are best answered using either slack or our forum, which is both are frequented by Zeek developers and professional users. You can join here:

Forum: https://community.zeek.org/

Slack: https://zeek.org/community/

---

That said, this seems the same error but in a different subproject. Try building with `--disable-zeekctl` (assuming you don't need that).

Alternatively, what's standing out here is that you're linking against a static libpython3.7 libary located in `/usr/loca/lib/python3.7`. This looks like a custom Python build. Do you have a need for a custom Python build? We'd highly recommend using the system's `libpython3.11-dev` instead (on modern Kali).

Here's a possibly related error from someone using a custom Python build:
https://community.zeek.org/t/zeek-broker-python-module-fails-python3-11/6990?u=awelzel

If you continue having trouble compiling, reach out on Discourse and provide detailed instructions how you setup your Python environment as well. Thanks.
