### ISSUE TITLE
core.network_time.broker btest failing periodically

### ISSUE THREAD

**Issue by timwoj** [zeek/zeek#3013]
I've only seen this happen on the FreeBSD hosts but I've seen it a few times now. https://cirrus-ci.com/task/5022708241530880 is the latest instance. Rerunning the build typically fixes it.

**Comment by timwoj** [comment]
@awelzel is it possible this is caused by some of your recent changes around network time?

**Comment by awelzel** [comment]
This test was added with the network time changes - it may have been never fully reliable. If it's happening too often we can disable the test, but I'll try and see if it triggers on a FreeBSD VM sporadically.
