### ISSUE TITLE
Connection flipping recreates c$id, removing extra fields

### ISSUE THREAD

**Issue by JustinAzoff** [zeek/zeek#3028]
This definitely may fall under "Don't do that", but this is certainly odd behavior:

```
module IDFlipBug;

redef record conn_id += {
	my_field: string &log &optional;
};

event new_connection(c: connection) &priority=4
	{
	c$id$my_field = "Hello";
	print "Adding my_field to", c$id;
	}
```

When ran on a pcap with the initial syn packet removed:

```
$ zeek -Cr  ~/work/pcaps/http_single_no_syn_high_port.pcap ./bug.zeek tuning/json-logs                                            
Adding my_field to, [orig_h=192.168.2.127, orig_p=28080/tcp, resp_h=192.168.2.185, resp_p=49420/tcp, my_field=Hello]
$ 
$ cat conn.log|jq .                                                                    
{
  "ts": 1620657542.468,
  "uid": "CvjXtL1vqLsPQGjMd2",
  "id.orig_h": "192.168.2.185",
  "id.orig_p": 49420,
  "id.resp_h": "192.168.2.127",
  "id.resp_p": 28080,
  "proto": "tcp",
  "duration": 0.017675161361694336,
  "orig_bytes": 87,
  "resp_bytes": 118,
  "conn_state": "SF",
  "missed_bytes": 0,
  "history": "^hADadfF",
  "orig_pkts": 5,
  "orig_ip_bytes": 355,
  "resp_pkts": 5,
  "resp_ip_bytes": 378
}
```

It appears that when the internals flip the connection - which I also notice doesn't have a `connection_flipped` type event, the `id` record is recreated from scratch, rather than being updated in place.  This removes any custom fields that may have been added to the record.

**Comment by awelzel** [comment]
> This definitely may fall under "Don't do that", but this is certainly odd behavior:

This applies to the whole connection value, not just c$id. The new community-id-logging policy script is actually affected by this:

https://github.com/zeek/zeek/blob/c543387ce0d4949ed82e7c6f3dbfb9cd13dc562b/scripts/policy/protocols/conn/community-id-logging.zeek#L22-L26

> It appears that when the internals flip the connection - which I also notice doesn't have a connection_flipped type event, the id record is recreated from scratch, rather than being updated in place.

I can see updating fields (also orig/resp endpoints) in place. But certainly need the event you suggested for custom scripts to flip/reset state if needed, too. likely_server_ports, #3016, out-of-order DNS packet heuristic and Spicy's `flip_roles()` could all trigger this.

I wonder if there's any historic background on resetting the whole connection val upon flipping? Seems that topic might have came up before?

**Comment by ckreibich** [comment]
> I wonder if there's any historic background on resetting the whole connection val upon flipping?

Looks to me like the philosophy in Conn.c is basically one of late binding — the underlying `conn_val` gets created the first time someone invokes `Connection::GetVal()`, and `Connection::FlipRoles()` just sets `conn_val` to null. Preserving additional vals was likely just not part of the thinking, but a more careful implementation could do so.

**Comment by awelzel** [comment]
This came up on Slack: https://zeekorg.slack.com/archives/CSZBXF6TH/p1689099127412749

I'm putting it on the 6.0.1 list, but should maybe have a bit of scrutiny if it's worth/safe.
