### ISSUE TITLE
Bro Installation Fails

### ISSUE THREAD

**Issue by aniss05** [zeek/zeek#305]
Hi all,

I am trying to install the latest version of bro(2-6.1) by following the exact steps on the website. After executing the 'make' command, I get the following errors:

lto1: internal compiler error: in lto_tag_to_tree_code, at lto-streamer.h:1005
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
lto-wrapper: fatal error: /usr/bin/c++ returned 1 exit status
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
aux/broker/bindings/python/CMakeFiles/_broker.dir/build.make:204: recipe for target 'aux/broker/python/broker/_broker.so' failed
make[3]: *** [aux/broker/python/broker/_broker.so] Error 1
make[3]: Leaving directory '/home/aniss/bro-2.6.1/build'
CMakeFiles/Makefile2:520: recipe for target 'aux/broker/bindings/python/CMakeFiles/_broker.dir/all' failed
make[2]: *** [aux/broker/bindings/python/CMakeFiles/_broker.dir/all] Error 2
make[2]: Leaving directory '/home/aniss/bro-2.6.1/build'
Makefile:151: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/aniss/bro-2.6.1/build'
Makefile:15: recipe for target 'all' failed
make: *** [all] Error 2

I don't know exactly what is causing this issue, my configuration is the following:
OS: Ubuntu 18.04
GCC: 7.3.0
G++: 7.3.0

I have also tried to chage the version of gcc and g++ to older version (4.8) but I still get the same errors.

I really appreciate any help. 

Thanks.

**Comment by jsiwek** [comment]
Generally seems the compiler has an internal issue doing link-time optimization.  Never seen that before, so don't have an initial idea sure why that is.  Posting the full output of of the `./configure` may help or more info on where the GCC installations come from (package manager, custom built, etc.). 

Note that if you do try to switch compilers, you need to delete the `build/` directory before doing a subsequent `./configure`, that could be why you saw the same error again on 4.8 if it didn't actually use the new compiler (also I believe the minimum supported compiler is technically 4.8.3 and looks like we do regular tests with 4.8.4 on Ubuntu 18.04).

**Comment by aniss05** [comment]
I have installed GCC using apt-get for both versions (7.3.0, 4.8). I also used this command to specify gcc 4.8 version:

CC=gcc-4.8 CPP=g++-4.8 ./configure --prefix=/home/aniss/bro

Is that correct?

**Comment by aniss05** [comment]
This is the output of the configure command I get:


Build Directory : build
Source Directory: /home/aniss/bro-2.6.1
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/gcc-4.8
-- Check for working C compiler: /usr/bin/gcc-4.8 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found sed: /bin/sed
-- Found PythonInterp: /home/aniss/anaconda3/bin/python (found version "3.6.5") 
-- Found FLEX: /usr/bin/flex (found version "2.6.4") 
-- Found BISON: /usr/bin/bison  
-- Found PCAP: /usr/lib/x86_64-linux-gnu/libpcap.so  
-- Performing Test PCAP_LINKS_SOLO
-- Performing Test PCAP_LINKS_SOLO - Success
-- Looking for pcap_get_pfring_id
-- Looking for pcap_get_pfring_id - not found
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.1.0g") 
-- Performing Test ns_initparse_works_none
-- Performing Test ns_initparse_works_none - Failed
-- Performing Test res_mkquery_works_none
-- Performing Test res_mkquery_works_none - Failed
-- Performing Test ns_initparse_works_libresolv.a
-- Performing Test ns_initparse_works_libresolv.a - Success
-- Performing Test res_mkquery_works_libresolv.a
-- Performing Test res_mkquery_works_libresolv.a - Success
-- Found BIND: /usr/lib/x86_64-linux-gnu/libresolv.a  
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Check size of unsigned int
-- Check size of unsigned int - done
-- Found BinPAC: /home/aniss/bro-2.6.1/build/aux/binpac/src/binpac  
-- Could NOT find LibMMDB (missing: LibMMDB_LIBRARY LibMMDB_INCLUDE_DIR) 
-- Could NOT find LibKrb5 (missing: LibKrb5_LIBRARY LibKrb5_INCLUDE_DIR) 
-- Could NOT find GooglePerftools (missing: GooglePerftools_LIBRARIES GooglePerftools_LIBRARIES_DEBUG GooglePerftools_INCLUDE_DIR) 
-- Could NOT find tcmalloc (missing: GooglePerftools_LIBRARIES) 
-- Check if the system is big endian
-- Searching 16 bit integer
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Looking for htonll
-- Looking for htonll - not found
-- Check size of long int
-- Check size of long int - done
-- Check size of long long
-- Check size of long long - done
-- Check size of void *
-- Check size of void * - done
-- Check size of int32_t
-- Check size of int32_t - done
-- Check size of u_int32_t
-- Check size of u_int32_t - done
-- Check size of u_int16_t
-- Check size of u_int16_t - done
-- Check size of u_int8_t
-- Check size of u_int8_t - done
-- Check size of socklen_t
-- Check size of socklen_t - done
-- Check size of struct ip6_opt
-- Check size of struct ip6_opt - done
-- Check size of struct ip6_ext
-- Check size of struct ip6_ext - done
-- Looking for include file getopt.h
-- Looking for include file getopt.h - found
-- Looking for include file memory.h
-- Looking for include file memory.h - found
-- Looking for include file netinet/ether.h
-- Looking for include file netinet/ether.h - found
-- Looking for 4 include files sys/socket.h, ..., netinet/if_ether.h
-- Looking for 4 include files sys/socket.h, ..., netinet/if_ether.h - found
-- Looking for 4 include files sys/socket.h, ..., netinet/ip6.h
-- Looking for 4 include files sys/socket.h, ..., netinet/ip6.h - found
-- Looking for 3 include files sys/socket.h, ..., net/ethernet.h
-- Looking for 3 include files sys/socket.h, ..., net/ethernet.h - found
-- Looking for include file sys/ethernet.h
-- Looking for include file sys/ethernet.h - not found
-- Looking for include file net/ethertypes.h
-- Looking for include file net/ethertypes.h - not found
-- Looking for include file sys/time.h
-- Looking for include file sys/time.h - found
-- Looking for include files time.h, sys/time.h
-- Looking for include files time.h, sys/time.h - found
-- Looking for include file os-proto.h
-- Looking for include file os-proto.h - not found
-- Performing Test HAVE_READLINE_HISTORY_ENTRIES
-- Performing Test HAVE_READLINE_HISTORY_ENTRIES - Failed
-- Looking for include files stdio.h, readline/readline.h
-- Looking for include files stdio.h, readline/readline.h - not found
-- Looking for include files stdio.h, readline/history.h
-- Looking for include files stdio.h, readline/history.h - not found
-- Performing Test SIN_LEN
-- Performing Test SIN_LEN - Failed
-- Looking for IPPROTO_HOPOPTS
-- Looking for IPPROTO_HOPOPTS - found
-- Looking for IPPROTO_IPV6
-- Looking for IPPROTO_IPV6 - found
-- Looking for IPPROTO_IPV4
-- Looking for IPPROTO_IPV4 - not found
-- Looking for IPPROTO_ROUTING
-- Looking for IPPROTO_ROUTING - found
-- Looking for IPPROTO_FRAGMENT
-- Looking for IPPROTO_FRAGMENT - found
-- Looking for IPPROTO_ESP
-- Looking for IPPROTO_ESP - found
-- Looking for IPPROTO_AH
-- Looking for IPPROTO_AH - found
-- Looking for IPPROTO_ICMPV6
-- Looking for IPPROTO_ICMPV6 - found
-- Looking for IPPROTO_NONE
-- Looking for IPPROTO_NONE - found
-- Looking for IPPROTO_DSTOPTS
-- Looking for IPPROTO_DSTOPTS - found
-- Looking for getopt_long
-- Looking for getopt_long - found
-- Looking for mallinfo
-- Looking for mallinfo - found
-- Looking for strcasestr
-- Looking for strcasestr - found
-- Looking for strerror
-- Looking for strerror - found
-- Looking for strsep
-- Looking for strsep - found
-- Looking for sigset
-- Looking for sigset - found
-- Performing Test DO_SOCK_DECL
-- Performing Test DO_SOCK_DECL - Failed
-- Performing Test SYSLOG_INT
-- Performing Test SYSLOG_INT - Failed
-- Looking for include file pcap-int.h
-- Looking for include file pcap-int.h - not found
-- Looking for pcap_freecode
-- Looking for pcap_freecode - found
-- Performing Test LIBPCAP_PCAP_COMPILE_NOPCAP_HAS_ERROR_PARAMETER
-- Performing Test LIBPCAP_PCAP_COMPILE_NOPCAP_HAS_ERROR_PARAMETER - Failed
-- Performing Test LIBPCAP_PCAP_COMPILE_NOPCAP_NO_ERROR_PARAMETER
-- Performing Test LIBPCAP_PCAP_COMPILE_NOPCAP_NO_ERROR_PARAMETER - Success
-- Looking for DLT_PPP_SERIAL
-- Looking for DLT_PPP_SERIAL - found
-- Performing Test including_ssl_h_works
-- Performing Test including_ssl_h_works - Success
-- Performing Test OPENSSL_D2I_X509_USES_CONST_CHAR
-- Performing Test OPENSSL_D2I_X509_USES_CONST_CHAR - Success
-- Performing Test OPENSSL_CORRECT_VERSION_NUMBER
-- Performing Test OPENSSL_CORRECT_VERSION_NUMBER - Success
-- Performing Test have_nameser_header
-- Performing Test have_nameser_header - Success
-- Performing Test cxx11_header_works
-- Performing Test cxx11_header_works - Success
-- Could NOT find RocksDB (missing: ROCKSDB_LIBRARIES ROCKSDB_INCLUDE_DIRS) 
-- Check if the system is big endian
-- Searching 16 bit integer
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Looking for include file emmintrin.h
-- Looking for include file emmintrin.h - found
-- Found PythonDev: /home/aniss/anaconda3/bin/python3.6-config  
-- Performing Test HAS_LTO_FLAG
-- Performing Test HAS_LTO_FLAG - Success
-- Python bindings will be built and installed to:
--   /home/aniss/bro/lib/broctl
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found SWIG: /usr/bin/swig3.0 (found version "3.0.12") 
-- Found SubnetTree: build from source aux/pysubnettree  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/aniss/bro-2.6.1/build

**Comment by aniss05** [comment]
It is finally working now. I noticed in the output of the configure command that I posted that CXX was of version 7.3.0; so I did the following:

CC=gcc-4.8 CPP=g++-4.8 CXX=g++-4.8 ./configure --prefix=/home/aniss/bro

Then, make and make install just worked fine.

Thanks for your help @jsiwek
