### ISSUE TITLE
Syntactic sugar to switch between `vector` and `set`

### ISSUE THREAD

**Issue by ynadji** [zeek/zeek#3059]
Easiest would be allow `vector` and `set` to take one argument of the other type and convert, i.e.,

```ruby
local v = vector(1, 1, 1, 2, 2, 3, 3, 4);
set(v); # returns {1, 2, 3, 4}
```

and vice-versa. Not sure this is easily doable in Zeek, so `vector_to_set` and `set_to_vector` seem reasonable.

**Comment by timwoj** [comment]
We do already have the `any_set_to_any_vec` BIF in options.bif, but it returns a vector of `any` vs a vector that matches the type of the original set. Given that a vector can't have multiple elements for each entry, I think we'd a new BIF that throws an error if passed a set that has multiple indexes.

**Comment by JustinAzoff** [comment]
Should that bif work for this?

```
root@ba351a215dc9:/tmp# cat foo.zeek 
event zeek_init()
{
    local foo: set[string] = {"hello", "world"};
    print paraglob_init(Option::any_set_to_any_vec(foo));

    local bar: string_vec = Option::any_set_to_any_vec(foo);
    print paraglob_init(bar);

    local baz: string_vec = Option::any_set_to_any_vec(foo) as string_vec;
    print paraglob_init(baz);
}
root@ba351a215dc9:/tmp# zeek --version
zeek version 6.0.0
root@ba351a215dc9:/tmp# zeek ./foo.zeek 
error: paraglob requires a vector of strings for initialization.
error: paraglob requires a vector of strings for initialization.
error: paraglob requires a vector of strings for initialization.
fatal error: errors occurred while initializing
root@ba351a215dc9:/tmp#
```

**Comment by timwoj** [comment]
The reason that's failing is because `paraglob_init` is expecting a vector with a pure type in it vs a type list containing the pure type. I actually just fixed that bug in the new `set_to_vector` bif because it was doing the same thing. The output vectors are now a vector of string instead of a vector of a typelist containing strings.

**Comment by timwoj** [comment]
For reference, this ended up using the `as` operator for the conversions. There's a new section in the docs for that operator describing its usage.
