### ISSUE TITLE
Support for negative vector indices

### ISSUE THREAD

**Issue by ynadji** [zeek/zeek#3060]
Many modern programming languages support negative index values for vectors for referring to entries from the end, i.e., `vec[-1]` is the last value, `vec[-2]` is the second-to-last value, and so on. Folks will expect this coming from these languages and it makes the code a bit more readable/succinct. For example:

```ruby
local stack: vector of count;
stack += 1;
stack += 2;
stack += 3;

# more readable (imo) equivalent to pop
local top = stack[-1];
stack = stack[0:-1];
```

etc.

**Comment by awelzel** [comment]
> stack = stack[0:-1];

Slices with negative indices actually work, so not supporting negative indices even a bit inconsistent.
