### ISSUE TITLE
Building Zeek 5.0.9 on Fedora 38 x86_64

### ISSUE THREAD

**Issue by LawrenceRRogers** [zeek/zeek#3064]
Fails with the following:

$ make
make -C build all
make[1]: Entering directory '/home/repoman/rpmbuild/BUILD/zeek-5.0.9/build'
[  0%] Building libkqueue
[100%] Built target kqueue
[  0%] Completed 'project_kqueue'
[  1%] Built target project_kqueue
[  1%] Built target binpac_static
[  3%] Built target binpac
[  4%] Built target bifcl
[  5%] Built target gen-zam
[  5%] Built target paraglob
[  6%] Built target ahocorasick
[  6%] Built target paraglob-test
[ 15%] Built target libcaf_core_obj
[ 15%] Built target libcaf_core
[ 18%] Built target libcaf_net_obj
[ 18%] Built target libcaf_net
[ 20%] Built target libcaf_io_obj
[ 20%] Built target libcaf_io
[ 24%] Built target broker_static
[ 24%] Built target broker-node
[ 24%] Built target broker-pipe
[ 24%] Staging Python scripts in /home/repoman/rpmbuild/BUILD/zeek-5.0.9/build/auxil/broker/python/broker
[ 24%] Built target python-scripts-stage
[ 24%] Built target _broker
[ 24%] Built target fiber
[ 25%] Built target jrx-objects
[ 26%] Built target hilti-rt-objects
[ 26%] Built target hilti-rt
[ 27%] Built target hilti-rt-debug-objects
[ 27%] Built target hilti-rt-debug
[ 27%] Built target hilti-rt-tests-library-dummy1
[ 27%] Built target hilti-rt-tests-library-dummy2
[ 28%] Built target reproc
[ 28%] Built target reproc++
[ 28%] Building CXX object auxil/spicy/spicy/hilti/toolchain/CMakeFiles/hilti-objects.dir/__/src/autogen/operators-implementations.cc.o
In file included from /home/repoman/rpmbuild/BUILD/zeek-5.0.9/auxil/spicy/spicy/hilti/runtime/include/hilti/rt/types/address.h:14,
                 from /home/repoman/rpmbuild/BUILD/zeek-5.0.9/auxil/spicy/spicy/hilti/toolchain/include/hilti/ast/ctors/address.h:7,
                 from /home/repoman/rpmbuild/BUILD/zeek-5.0.9/auxil/spicy/spicy/hilti/toolchain/include/hilti/ast/ctors/all.h:5,
                 from /home/repoman/rpmbuild/BUILD/zeek-5.0.9/auxil/spicy/spicy/hilti/toolchain/include/hilti/ast/all.h:5,
                 from /home/repoman/rpmbuild/BUILD/zeek-5.0.9/build/auxil/spicy/spicy/hilti/src/autogen/operators-implementations.cc:1:
/home/repoman/rpmbuild/BUILD/zeek-5.0.9/auxil/spicy/spicy/hilti/runtime/include/hilti/rt/types/stream.h: In member function ‘hilti::rt::stream::View hilti::rt::stream::View::extract(Byte*, uint64_t) const’:
/home/repoman/rpmbuild/BUILD/zeek-5.0.9/auxil/spicy/spicy/hilti/runtime/include/hilti/rt/types/stream.h:1288:28: warning: comparison of integer expressions of different signedness: ‘int’ and ‘uint64_t’ {aka ‘long unsigned int’} [-Wsign-compare]
 1288 |         for ( int i = 0; i < n; ++i )
      |                          ~~^~~
In file included from /home/repoman/rpmbuild/BUILD/zeek-5.0.9/auxil/spicy/spicy/hilti/toolchain/include/hilti/ast/ctor.h:7,
                 from /home/repoman/rpmbuild/BUILD/zeek-5.0.9/auxil/spicy/spicy/hilti/toolchain/include/hilti/ast/ctors/address.h:9:
/home/repoman/rpmbuild/BUILD/zeek-5.0.9/auxil/spicy/spicy/hilti/toolchain/include/hilti/ast/node.h: In instantiation of ‘std::vector<hilti::Node> hilti::nodes(T, Ts ...) [with T = Type; Ts = {Type}]’:
/home/repoman/rpmbuild/BUILD/zeek-5.0.9/auxil/spicy/spicy/hilti/toolchain/include/hilti/ast/types/bytes.h:41:51:   required from here
/home/repoman/rpmbuild/BUILD/zeek-5.0.9/auxil/spicy/spicy/hilti/toolchain/include/hilti/ast/node.h:839:24: warning: moving a temporary object prevents copy elision [-Wpessimizing-move]
  839 |     return util::concat(std::move(nodes(t)), nodes(std::move(ts)...));
      |            ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/repoman/rpmbuild/BUILD/zeek-5.0.9/auxil/spicy/spicy/hilti/toolchain/include/hilti/ast/node.h:839:24: note: remove ‘std::move’ call
/home/repoman/rpmbuild/BUILD/zeek-5.0.9/auxil/spicy/spicy/hilti/toolchain/include/hilti/ast/node.h: In instantiation of ‘std::vector<hilti::Node> hilti::nodes(T, Ts ...) [with T = Type; Ts = {std::vector<expression::detail::Expression, std::allocator<expression::detail::Expression> >}]’:
... (same errors repeated many times)
g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[3]: *** [auxil/spicy/spicy/hilti/toolchain/CMakeFiles/hilti-objects.dir/build.make:922: auxil/spicy/spicy/hilti/toolchain/CMakeFiles/hilti-objects.dir/__/src/autogen/operators-implementations.cc.o] Error 1
make[3]: *** Deleting file 'auxil/spicy/spicy/hilti/toolchain/CMakeFiles/hilti-objects.dir/__/src/autogen/operators-implementations.cc.o'
make[2]: *** [CMakeFiles/Makefile2:4182: auxil/spicy/spicy/hilti/toolchain/CMakeFiles/hilti-objects.dir/all] Error 2
make[1]: *** [Makefile:166: all] Error 2
make[1]: Leaving directory '/home/repoman/rpmbuild/BUILD/zeek-5.0.9/build'
make: *** [Makefile:15: all] Error 2

**Comment by LawrenceRRogers** [comment]
I believe this is a resource issue on the system I use to build Fedora 38 packages. Feel free to hold off on trying to debug this. I changed the physical memory on the build VM from 4Gb to 12Gb and that seems to have made a difference.

**Comment by ckreibich** [comment]
Fwiw, 5.0.9 is building fine on Fedora 38 over here. I'm noticing that the build is riddled with warnings, though. We're unlikely to iterate on this unless there's an outright build failure, since the 5.0 release train is about to end as we release 6.0.

**Comment by timwoj** [comment]
> I believe this is a resource issue on the system I use to build Fedora 38 packages. Feel free to hold off on trying to debug this. I changed the physical memory on the build VM from 4Gb to 12Gb and that seems to have made a difference.

Yes, it is. Spicy requires quite a bit of memory to build. We're seeing ~2-3GB/CPU in order to guarantee it doesn't fail. If you're going to use a system that small, you're going to have to cut down on the number of jobs you're asking Make/Ninja to run.
