### ISSUE TITLE
Can the binpac.a be a dynamic library?

### ISSUE THREAD

**Issue by mpurzynski** [zeek/zeek#307]
Hey,

could the binpac.a become binpac.so?

ClearLinux has the policy to strip static archives and there is no way to build external plugins without the binpac lib. I can ask for an exception, but maybe we can just change it here?

**Comment by jsiwek** [comment]
Yes, I think it's only built as a static lib historically, not for any technical reason.  In `master` I've changed it to build only a shared lib by default.  Unit tests and installation of external packages/plugins still seem to work, but let me know if anything else amiss gets noticed.
