### ISSUE TITLE
DNS over TLS on port 853?

### ISSUE THREAD

**Issue by timwoj** [zeek/zeek#3082]
@initconf brought up in a call that port 853 is now apparently a standard port used for DNS over TLS. Should we considering fixing our DNS analyzer to at least detect these connections, even if we can't do anything with them due to the encryption?

See https://datatracker.ietf.org/doc/html/rfc7858 for details.

**Comment by 0xxon** [comment]
For DNS over TLS, we will only see a TLS connection - so from out point of view, there is no DNS involvement at all. So the DNS analyzer will never be involved in any way.

Is the ask to call it out somehow that "hey, this port is well-known, and while it is TLS, it will probably be carrying DNS traffic"?
