### ISSUE TITLE
zeek log Chinese is garbled,how to solve

### ISSUE THREAD

**Issue by shuaidonga** [zeek/zeek#309]
zeek log chinese is garbled, How should I solve it？
![image](https://user-images.githubusercontent.com/16378509/54521044-0b540d00-49a5-11e9-8ca6-2983bae3e8c9.png)
Output the results are as following
![image](https://user-images.githubusercontent.com/16378509/54521112-39395180-49a5-11e9-8360-7667d0b0cd40.png)

**Comment by jsiwek** [comment]
Currently, I don't think there's anything you can do other than use printable ASCII characters in all output -- anything else gets escaped, as you observed.

**Comment by shuaidonga** [comment]
@jsiwek 
I recently got into the zeek project and I want to know the environment in which your programming IDE is configured, such as the IDE configuration for writing c/c++ and bro scripting. Or send it to wangtindong7@gmail.com. please help me

**Comment by jsiwek** [comment]
There's no particular IDE required, any text editor will do.  I currently use just `vim`, but in the past I've found Qt Creator and CLion promising IDE choices.

Generally, any Linux/Mac IDEs supported by CMake will likely work -- you can check the output of `cmake -G` for a list available on your system and pass the desired value to the `./configure --generator=` option.

**Comment by shuaidonga** [comment]
@jsiwek 
can you share your .vimrc file with me?
