### ISSUE TITLE
CXXFLAGS used by external plugins: differences between 5.2.2 and master

### ISSUE THREAD

**Issue by awelzel** [zeek/zeek#3090]
Compiling external plugins with master uses different CXXFLAGS than with Zeek 5.2.2.

The following flags aren't passed to external plugins anymore (and the rapidjson include):
```
-Wall -Wno-unused -Wno-register -Werror=vla -g -I/opt/zeek-5.2.2-debug/include/zeek/3rdparty/rapidjson/include
```

Edit after Tim's reply: I had missed the following:
```
-DDOCTEST_CONFIG_DISABLE 
```

Mostly recording a ticket for discussion. Maybe can close as acceptable new behavior. For me it was the missing `-g` that lead at looking: Didn't have line numbers in crashdumps with an external plugin with `master`, but do get them with Zeek 5.2.2 (debug builds, both).

Sample output of `VERBOSE=1 make` between 5.2.2 and 6.0.0 dev660:

#### zeek version 5.2.2-debug
> ```/usr/bin/c++ -DDOCTEST_CONFIG_DISABLE -DZEEK_PLUGIN_INTERNAL_BUILD=false -DZeek_JavaScript_linux_x86_64_EXPORTS -I/opt/node-19.8/include/node -I/opt/node-19.8/include -I/home/awelzel/corelight-oss/zeekjs/src -I/home/awelzel/corelight-oss/zeekjs/build/src -I/home/awelzel/corelight-oss/zeekjs/build -I/opt/zeek-5.2.2-debug/include -I/opt/zeek-5.2.2-debug/include/binpac -I/opt/zeek-5.2.2-debug/include/zeek/3rdparty/rapidjson/include -std=c++17 -Wall -Wno-unused -Wno-register -Werror=vla -Wall -Wno-unused -g -DDEBUG -DBRO_DEBUG -Wno-register -Werror=vla -g -fPIC -o CMakeFiles/Zeek-JavaScript.linux-x86_64.dir/src/Plugin.cc.o -c /home/awelzel/corelight-oss/zeekjs/src/Plugin.cc```

#### zeek version 6.0.0-dev.660-debug
> ```/usr/bin/c++ -DDEBUG -DZeek_JavaScript_EXPORTS -I/opt/node-19.8/include/node -I/opt/node-19.8/include -I/home/awelzel/corelight-oss/zeekjs/build -I/home/awelzel/corelight-oss/zeekjs/src -I/opt/zeek-dev/include/binpac -isystem /opt/zeek-dev/include -fPIC -std=gnu++17 -o CMakeFiles/Zeek_JavaScript.dir/src/Plugin.cc.o -c /home/awelzel/corelight-oss/zeekjs/src/Plugin.cc```

**Comment by timwoj** [comment]
Isn't `-DDOCTEST_CONFIG_DISABLE` at the very least needed so that unit tests in the plugins work correctly? I'd prefer it keep the way that it was, with the flags being passed down into the plugins just for consistency.

**Comment by timwoj** [comment]
Tagging @Neverlord on this one.

**Comment by timwoj** [comment]
A bunch of those flags are set in `cmake/SetDefaultCompileFlags.cmake`. Looks like all of `-Wall -Wno-unused -Wno-register -Werror=vla -g -DDEBUG -DBRO_DEBUG` are in there. Was that file included for plugin builds previously, and it isn't anymore?

**Comment by timwoj** [comment]
It's also curious that your build used `-std=c++17` for the 5.2.2 build but used `-std=gnu++17` for the 6.0 build.

**Comment by timwoj** [comment]
Thinking about this one more, I can definitely see an argument for not passing the flags along. It's this line from the original post that got me thinking about it:

> For me it was the missing -g that lead at looking

Plugins provide an `--enable-debug` flag for building with debug information enabled. On top of that, it's possible that some flag passed down from Zeek would override a flag intentionally set by a plugin author. I do think we need to pass down whatever flags are needed for doctest, but I'm not sure about the rest of them.

**Comment by Neverlord** [comment]
Regarding the doctest setup, there's been a bit of discussion surrounding that in the PR here: https://github.com/zeek/zeek/pull/2710#issuecomment-1432012004.

IIRC, building Zeek without unit tests enabled will also disable them in the plugins because we pass them along from the base target.

Are plugins supposed to have access to the rapidjson header? If we always install it and if it's required, we can bring that back.

**Comment by timwoj** [comment]
> IIRC, building Zeek without unit tests enabled will also disable them in the plugins because we pass them along from the base target.

Right. I think the doctests are enabled because we called `enable_testing()`, but we're missing a couple of variables depending on whether or not doctests are enabled (I tried with both enabled and disabled):

https://github.com/zeek/zeek/blob/9f80d62cde8d9a8a33f8fa8e4341f29354cf69d0/CMakeLists.txt#L405-L410

I don't know if they make a big difference to plugins. I also don't see a plugin in the packages repo that has doctests, but I can whip something together tomorrow (unless @awelzel already has one).

> Are plugins supposed to have access to the rapidjson header? If we always install it and if it's required, we can bring that back.

We do always install it: `./include/zeek/3rdparty/rapidjson/include/rapidjson/rapidjson.h`. There may be headers that a plugin can include that expecting it to exist.

**Comment by awelzel** [comment]
There are a few separate things popping up around the flags and maybe best tracked as separate tickets for those that should be fixed for Zeek 6.0?

* rapidjson include dirs missing
* doctest flags missing
* `zeek-config --build_type == debug` enables debug build for external plugins logic is not functional anymore
* external plugins build without optimizations, previously `-O2` by default due to `include(SetDefaultCompileFlags)`
* -std=gnu++17 vs -std=c++17 in compile flags for external plugins - possibly related to `include(RequireCXX17)`

---

> Plugins provide an --enable-debug flag for building with debug information enabled.
> On top of that, it's possible that some flag passed down from Zeek would override a flag intentionally set by a plugin author.
 
Yes, can see that and never liked `-Wno-unused` being propagated.

However, we do have logic in existing configure files that implicitly does ``--enable-debug`` if ``zeek-config --build_type == debug`` (it's even in the template/skeleton). This workflow still sense sensible to me, but I can't see how this would work today given that `BRO_PLUGIN_ENABLE_DEBUG` isn't respected anymore. Maybe that's the actual regression here for the `-g` flag missing.

https://github.com/zeek/package-template/blob/b914087045082bf2730bd5ca85ffaa1298e0b791/features/plugin/configure#L140-L144
https://github.com/corelight/zeek-community-id/blob/0f7c699a539b3a80e845f4da58d29a897ca6b987/configure#L149-L153


It also makes me nervous that external plugins are not using `-O2` by default anymore (for non-debug Zeek builds) and instead are being built without optimizations. Building an external plugin with Zeek 5.2.2 it always gets `-O2` by default. This could be surprising to users as it's unlikely they enable them explicitly (think zkg workflow). Might be related to `include(SetDefaultCompileFlags)` not being in ZeekPluginDynamic.

> I don't know if they make a big difference to plugins. I also don't see a plugin in the packages repo that has doctests, but I can whip something together tomorrow (unless @awelzel already has one).

I haven't done that. doctest in plugins is the least worrying to me TBH :-)

> There may be headers that a plugin can include that expect it to exist/be on the include path.

`threading/formatters/JSON.h`, though it would probably be nice to not do this.

**Comment by timwoj** [comment]
> external plugins build without optimizations, previously -O2 by default due to `nclude(SetDefaultCompileFlags)`

There's a bigger question here if we want to include all of the arguments that this file sets up (such as `-Wno-unused`). 

> -std=gnu++17 vs -std=c++17 in compile flags for external plugins - possibly related to `include(RequireCXX17)`

We used to include this file from ZeekPluginCommon.cmake, so that's an easy fix.

**Comment by timwoj** [comment]
> -std=gnu++17 vs -std=c++17 in compile flags for external plugins - possibly related to include(RequireCXX17)

Strangely, on macOS I'm actually getting *both* of these flags on the build of Zeek itself:

```
[29/540] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DDEBUG -DDOCTEST_CONFIG_SUPER_FAST_ASSERTS -DZEEK_CONFIG_SKIP_VERSION_H -DZEEK_PLUGIN_SKIP_VERSION_CHECK -I/Users/tim/Desktop/projects/zeek-master/build/src/include -I/Users/tim/Desktop/projects/zeek-master/build/src -I/Users/tim/Desktop/projects/zeek-master/src/include -I/Users/tim/Desktop/projects/zeek-master/src -I/Users/tim/Desktop/projects/zeek-master/build -I/Users/tim/Desktop/projects/zeek-master/auxil/out_ptr/include -I/Users/tim/Desktop/projects/zeek-master/build/auxil/c-ares -I/Users/tim/Desktop/projects/zeek-master/auxil/c-ares/include -I/Users/tim/Desktop/projects/zeek-master/auxil/rapidjson/include -I/Users/tim/Desktop/projects/zeek-master/auxil/paraglob/include -I/Users/tim/Desktop/projects/zeek-master/auxil/highwayhash -I/Users/tim/Desktop/projects/zeek-master/build/auxil/broker/include -I/Users/tim/Desktop/projects/zeek-master/auxil/broker/include -I/opt/homebrew/opt/openssl/include -I/Users/tim/Desktop/projects/zeek-master/build/auxil/binpac/lib -I/Users/tim/Desktop/projects/zeek-master/auxil/binpac/lib -I/Users/tim/Desktop/projects/zeek-master/build/src/analyzer/protocol/dhcp -Wall -Wno-unused -g -DDEBUG -DBRO_DEBUG -Wno-register -Werror=vla **-std=c++17 -g -std=gnu++17** -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk -MD -MT src/analyzer/protocol/dhcp/CMakeFiles/plugin-Zeek-DHCP.dir/events.bif.init.cc.o -MF src/analyzer/protocol/dhcp/CMakeFiles/plugin-Zeek-DHCP.dir/events.bif.init.cc.o.d -o src/analyzer/protocol/dhcp/CMakeFiles/plugin-Zeek-DHCP.dir/events.bif.init.cc.o -c /Users/tim/Desktop/projects/zeek-master/build/src/analyzer/protocol/dhcp/events.bif.init.cc```

That's probably not ideal.

**Comment by timwoj** [comment]
> Strangely, on macOS I'm actually getting both of these flags on the build of Zeek itself:

It looks like setting the compiler standard here is what sets the `-std=gnu++17` flag:

https://github.com/zeek/zeek/blob/f64304067b96e4b1ffa0f858d94d2bf96f47d262/CMakeLists.txt#L191

We then try to override it in `RequireCXX17`, but we do it by setting `CMAKE_CXX_FLAGS` which doesn't override the flag already set on the target. Is there any reason not to just use the flag that's already set via the target? We'd have to do the same in `ZeekPluginDynamic`, but that would solve that one.

**Comment by ckreibich** [comment]
I don't know how we thought about this when plugins got introduced, and I'm pretty sure we've not revisited the set of flags since. For any plugin installed as part of a Zeek package the plugin will generally not have user-customized configuration — there's generally no way to say "I'd like to install this package with debugging support please", for example, because the configuration is hardwired in `zkg.meta` and implied by the plugin's configure & CMake setup. So the guideline should be that the plugin build inherits everything from Zeek that makes it behave broadly similar — same debugging settings, optimization flags, unit test compilation, etc.

**Comment by timwoj** [comment]
From the list @awelzel posted above:

- rapidjson include dirs missing (https://github.com/zeek/zeek/pull/3127)
- doctest flags missing (https://github.com/zeek/zeek/pull/3129)
- zeek-config --build_type == debug enables debug build for external plugins logic is not functional anymore (https://github.com/zeek/zeek/pull/3126, https://github.com/zeek/cmake/pull/82)
- external plugins build without optimizations, previously -O2 by default due to include(SetDefaultCompileFlags)
- -std=gnu++17 vs -std=c++17 in compile flags for external plugins - possibly related to include(RequireCXX17) (https://github.com/zeek/zeek/pull/3124)

**Comment by awelzel** [comment]
I think we've squelched everything so far. Closing.

Maybe a NEWS worthy change is that with 6.0.0 external plugins inherit Zeek's CMAKE_BUILD_TYPE. Previously that was either set to Debug if Zeek's build was debug or RelWithDebInfo by default. Now it is either what a user set explicitly via -DCMAKE_BUILD_TYPE for the plugin (unusual), or Zeek's CMAKE_BUILD_TYPE.
