### ISSUE TITLE
__load__.zeek not found in /usr/local/share/zeek/policy/protocols/ssh

### ISSUE THREAD

**Issue by Johandershmut** [zeek/zeek#3106]
__load__.zeek not found in /usr/local/share/zeek/policy/protocols/ssh

` sudo zeekctl deploy
checking configurations ...
zeek scripts failed.
error in /usr/local/share/zeek/site/local.zeek, line 50: Failed to open package '/usr/local/share/zeek/policy/protocols/ssh': missing '__load__.zeek' file
fatal error in /usr/local/share/zeek/site/local.zeek, line 50: can't open /usr/local/share/zeek/policy/protocols/ssh/__load__.zeek`

zeek version used is zeek-5.0.8. this was downloaded from source and install using the make command. Is this a known problem with the new version and what is the fix?

**Comment by awelzel** [comment]
Hey @Johandershmut - did you put `@load protocols/ssh` into your local.zeek file? This wouldn't be how the policy scripts are meant to be used, load the contained files explicitly, like `@load protocols/ssh/geo-data`.

These questions are also better for Slack or the Forum - from the docs:

Join the Zeek community [Slack channel](https://zeek.org/slack/) or [forum](https://community.zeek.org/) for interacting with fellow Zeekers and Zeek core developers.
