### ISSUE TITLE
Add an OPC UA plugin to zeek

### ISSUE THREAD

**Issue by Sun-Dordje** [zeek/zeek#311]
hello zeek/bro comunity, i try to add a plugin to zeek/bro to parse the OPC UA protocol.

So:
1) i installed bro
2) i used binpac to generate C++ for bro (opcua-protocol.pac OPCUA.cc OPCUA.h opcua-analyser.pac opcua_pac.cc opcua_pac.h)
3) i created some event to test

my edit files :

- opcua-protocol.pac => contains formal definition of opcua message
- main.bro => my bro script (events)
- event.bif => defines prototype for the interface between parser and policy scripts
- init-bare.bro => definition of the data structure that
the parser generated by Binpac will fill and pass to the bro policy

my commands (im root):
1) git clone https://github.com/zeek/zeek.git
2) cd zeek
3) ./configure
4) make
5a) make install
5b) cd ~/zeek/src/analyzer/protocol/opcua
6) binpac -I ~/zeek/src opcua.pac
7)  (recompiling bro to include the updated analyzer)
    cd ~/zeek/
    make
8)  (define OPC UA types structure)
    -cp ~/zeek/scripts/base/init-bare.bro /usr/local/bro/share/bro/base/init-bare.bro

9) #default policy scripts
    mkdir -p /usr/local/bro/share/bro/site/base/protocols/opcua/
    cp -r ~/zeek/scripts/base/protocols/opcua/* /usr/local/bro/share/bro/base/protocols/opcua/
    cp -r ~/zeek/scripts/base/protocols/opcua/* usr/local/bro/share/bro/site/base/protocols/opcua/

10)
    -#update other scripts
    -cp ~/zeek/build/scripts/base/bif/plugins/* /usr/local/bro/share/bro/base/bif/plugins/

11) ./bro -r opcua.pcap

    output
    >OPC UA POLICY SCRIPT INIT (BRO_INIT)
    The connection Cug27z1DJM9p5bhzg from ::1 on port 60532/tcp to ::1 on port 4840/tcp started at 03/18/19 08:41. (NEW_CONNECTION)
    Connection Cug27z1DJM9p5bhzg took 0.0 seconds (CONNECTION_STATE_REMOVE)
    The connection CIRT5a134zDL1GdpYb from ::1 on port 4840/tcp to ::1 on port 60532/tcp started at 03/18/19 08:41.
    The connection CkHdpA3fKPpkVD6zb6 from ::1 on port 60534/tcp to ::1 on port 4840/tcp started at 03/18/19 08:41.
    Connection CkHdpA3fKPpkVD6zb6 took 0.0 seconds
    The connection CE7qpJ3HkNu4J9WFT9 from ::1 on port 4840/tcp to ::1 on port 60534/tcp started at 03/18/19 08:41.
    Connection CE7qpJ3HkNu4J9WFT9 took 0.0 seconds
    Connection CIRT5a134zDL1GdpYb took 0.0 seconds
    TERMINATE BRO SCRIPT, CHECK IF EACH REQUEST HAD A RESPONSE.... (BRO_DONE)

So bro detect my script but dont recognize for example an "event opcua_hello_event()" but recognize events and  "new_connection()"  " connection_state_remove()"

i don't understand why bro_init() is use from my script but not event opcua_hello_event(),
if someone can help me it will be very cool.
Sorry for my english.

Dordjé

**Comment by jsiwek** [comment]
It sounds like you maybe did not actually integrate the new analyzer/plugin into the build system -- it may be easier for others to help you if you push all your code modifications to a GitHub fork and can point people at it.

Or here's other documentation / references in case it helps:

* [generic plugin documentation](https://docs.zeek.org/en/stable/devel/plugins.html)
* [recent presentation on writing plugins](https://youtu.be/3IJkST8eX90)
* [a plugin / analyzer I recently worked on](https://github.com/corelight/bro-quic)
* [package manager documentation](https://docs.zeek.org/projects/package-manager/en/stable/) (optional, but if you intend to share your projects, this is one way)

Since we mostly use GitHub for tracking bug requests, and not general user support, I'd also suggest following up for further help on the developers mailing list if needed:

http://mailman.icsi.berkeley.edu/mailman/listinfo/zeek-dev

**Comment by siemenslt123** [comment]
> 
> 
> hello zeek/bro comunity, i try to add a plugin to zeek/bro to parse the OPC UA protocol.
> 
> So:
> 
>     1. i installed bro
> 
>     2. i used binpac to generate C++ for bro (opcua-protocol.pac OPCUA.cc OPCUA.h opcua-analyser.pac opcua_pac.cc opcua_pac.h)
> 
>     3. i created some event to test
> 
> 
> my edit files :
> 
>     * opcua-protocol.pac => contains formal definition of opcua message
> 
>     * main.bro => my bro script (events)
> 
>     * event.bif => defines prototype for the interface between parser and policy scripts
> 
>     * init-bare.bro => definition of the data structure that
>       the parser generated by Binpac will fill and pass to the bro policy
> 
> 
> my commands (im root):
> 
>     1. git clone https://github.com/zeek/zeek.git
> 
>     2. cd zeek
> 
>     3. ./configure
> 
>     4. make
>        5a) make install
>        5b) cd ~/zeek/src/analyzer/protocol/opcua
> 
>     5. binpac -I ~/zeek/src opcua.pac
> 
>     6. (recompiling bro to include the updated analyzer)
>        cd ~/zeek/
>        make
> 
>     7. (define OPC UA types structure)
>        -cp ~/zeek/scripts/base/init-bare.bro /usr/local/bro/share/bro/base/init-bare.bro
> 
>     8. #default policy scripts
>        mkdir -p /usr/local/bro/share/bro/site/base/protocols/opcua/
>        cp -r ~/zeek/scripts/base/protocols/opcua/* /usr/local/bro/share/bro/base/protocols/opcua/
>        cp -r ~/zeek/scripts/base/protocols/opcua/* usr/local/bro/share/bro/site/base/protocols/opcua/
> 
>     9. -#update other scripts
>        -cp ~/zeek/build/scripts/base/bif/plugins/* /usr/local/bro/share/bro/base/bif/plugins/
> 
>     10. ./bro -r opcua.pcap
>         output
>         > OPC UA POLICY SCRIPT INIT (BRO_INIT)
>         > The connection Cug27z1DJM9p5bhzg from ::1 on port 60532/tcp to ::1 on port 4840/tcp started at 03/18/19 08:41. (NEW_CONNECTION)
>         > Connection Cug27z1DJM9p5bhzg took 0.0 seconds (CONNECTION_STATE_REMOVE)
>         > The connection CIRT5a134zDL1GdpYb from ::1 on port 4840/tcp to ::1 on port 60532/tcp started at 03/18/19 08:41.
>         > The connection CkHdpA3fKPpkVD6zb6 from ::1 on port 60534/tcp to ::1 on port 4840/tcp started at 03/18/19 08:41.
>         > Connection CkHdpA3fKPpkVD6zb6 took 0.0 seconds
>         > The connection CE7qpJ3HkNu4J9WFT9 from ::1 on port 4840/tcp to ::1 on port 60534/tcp started at 03/18/19 08:41.
>         > Connection CE7qpJ3HkNu4J9WFT9 took 0.0 seconds
>         > Connection CIRT5a134zDL1GdpYb took 0.0 seconds
>         > TERMINATE BRO SCRIPT, CHECK IF EACH REQUEST HAD A RESPONSE.... (BRO_DONE)
> 
> 
> So bro detect my script but dont recognize for example an "event opcua_hello_event()" but recognize events and "new_connection()" " connection_state_remove()"
> 
> i don't understand why bro_init() is use from my script but not event opcua_hello_event(),
> if someone can help me it will be very cool.
> Sorry for my english.
> 
> Dordjé

Hi，
       You are so great! I am  also learning  the protocol, but I don't know how to parse it.

        Could you share OPC-UA zeek plugin with me ?

       Thank you so much !
