### ISSUE TITLE
Docker images for Debian 12

### ISSUE THREAD

**Issue by fox-ds** [zeek/zeek#3115]
Debian 12 has been released on June 10th, 2023. Next to a lot of package upgrades, they also updated OpenSSL from 1.1.1n to 3.0.9-1, which might be relevant to Zeek too. At least our (currently in development) Spicy QUIC parser (https://github.com/fox-ds/spicy-quic) needs the OpenSSL v3 libraries, but I can think of other packages that may have dependencies on a specific OpenSSL version and want to test if they still work properly.

When will the Dockerfiles on https://hub.docker.com/r/zeek/zeek support Debian 12? Would it be possible for e.g. the LTS and latest feature branches to  publish a Docker image ( `e.g. 5.2.2-amd64-deb12` ) for people to check out and validate their packages? Unfortunately, it's not possible to perform an OpenSSL upgrade in Debian 11 (bullseye) as a kind of workaround, so using `debian:bookworm`  as a base image would be the preferrable option. Thanks!

**Comment by bbannier** [comment]
> Would it be possible for e.g. the LTS and latest feature branches to publish a Docker image (e.g. `5.2.2-amd64-deb12`) for people to check out and validate their packages?

When we added the image we deliberately decided against giving users a choice of platform and instead provided only a single image. I think we shouldn't need to change that now, but should just consider bumping the base release of the image.

**Comment by fox-ds** [comment]
That would indeed also solve (at least our specific) problem
