### ISSUE TITLE
Zeek renaming: install prefix and other directory names

### ISSUE THREAD

**Issue by jsiwek** [zeek/zeek#313]
The default install prefix, `/usr/local/bro`, and some other installation directory names ought to use "zeek" instead of "bro".  Hopefully keeping symlinks around is enough to avoid breakages.  Though, I'm not sure if there's really a good way to signal to people that we'd like them to stop using the old path (so we can get rid of it eventually) other than a note in NEWS ...

**Comment by sethhall** [comment]
We'll have to do a blog post about the release anyway and we can specifically call out the potentially breaking changes that could impact people there too.

**Comment by shuaidonga** [comment]
I don't think these things are of much significance. I think the ecological significance of developing bro will be even greater. For example [,](https://github.com/apache/metron-bro-plugin-kafka) the bro log is docked with kafka. . Although there are some plugins, this plugin is not good, there are many bugs.

**Comment by JonZeolla** [comment]
Not to distract from this issue but you are welcome to open a ticket at https://issues.apache.org/jira/projects/METRON for any issues or questions with the Kafka plugin.

**Comment by dnthayer** [comment]
In addition to the default install prefix `/usr/local/bro` itself, the other relevant directory names are
(relative to the install prefix): `include/bro`, `lib/bro`, `share/bro`.

**Comment by jsiwek** [comment]
When making this change, we'd like for configuration files from the old default install prefix to be picked up by an installation going into the new prefix (to prevent silently dropping the user's customizations upon upgrading).

So the logic will look like "if we're installing into `/usr/local/zeek` and a `/usr/local/bro` already exists, somehow transfer or symlink the configurations from the old directory".  That means config files like `local.bro` and things in `etc/`.

The CMake logic for this will probably look similar to a change I already did to detect an old `local.bro` when installing the new `local.zeek` (and also for `broctl.cfg` to `zeekctl.cfg`), except just needs to be updated to consider looking in the old `/usr/local/bro` path.

**Comment by jsiwek** [comment]
@dnthayer did you still plan to wrap this up or have any branches where you started working on things that I can pick up from ?

**Comment by dnthayer** [comment]
> @dnthayer did you still plan to wrap this up or have any branches where you started working on things that I can pick up from ?

The only remaining task is to deal with zeekctl config files in `etc/` when a user does an upgrade
install.  I probably won't have time to work on this for a while, so you can finish this if you want.
Other than that, branch `topic/dnthayer/gh-313` in the zeek, bifcl, zeek-netcontrol, zeek-aux, cmake,
zeek-docs, zeekctl, pysubnettree, and trace-summary repos is ready for merge.

**Comment by jsiwek** [comment]
@dnthayer thanks, I'll get it wrapped up

**Comment by jsiwek** [comment]
Merged.
