### ISSUE TITLE
Stop publishing to Docker zeekurity organization, there is zeek now

### ISSUE THREAD

**Issue by awelzel** [zeek/zeek#3143]
This was discussed internally and the ideas was to not publish the 6.0 release to zeekurity anymore, only zeek

@bbannier suggested to remove the `latest` (and probably the `lts`) tags so that consumers receive an error upon pulling what would otherwise be a potentially outdated tag. Keeping versioned tags around should not hurt.

Deleted the tags through the UI seems easiest for this task.

**Comment by timwoj** [comment]
The fix for this will get merged into master but we're waiting a couple of days after the announcement post on Discourse.

**Comment by timwoj** [comment]
This is done now.
