### ISSUE TITLE
After the latest version of zeek is installed, error occurs.

### ISSUE THREAD

**Issue by shuaidonga** [zeek/zeek#317]
After the latest version of zeek is installed, the following error occurs.

error in /usr/local/bro/share/bro/policy/tuning/defaults/./packet-fragments.bro, line 12: syntax error, at or near "redef"
![image](https://user-images.githubusercontent.com/16378509/55224200-f69c3280-524a-11e9-9f41-36ac750c6e67.png)

**Comment by jsiwek** [comment]
Can you give steps to reproduce this from scratch (I don't see this in a typical/default installation of the `master` branch) ?  A guess is that there's a customization/script loaded in your `/site/local.bro` causing a problem.

**Comment by shuaidonga** [comment]
I found that redefining rede ignore_checksums =T in /site/local.bro  will cause this problem.

**Comment by JustinAzoff** [comment]
Did you forget the semicolon after the T?

    # incorrect, will cause strange errors when the next statements run
    redef ignore_checksums = T 

    # correct
    redef ignore_checksums = T;

**Comment by shuaidonga** [comment]
@JustinAzoff 
Sorry, the cause is this.
