### ISSUE TITLE
Bro cluster installation fails

### ISSUE THREAD

**Issue by aniss05** [zeek/zeek#318]
Hi everyone,

I am trying to configure a Bro cluster. I have followed the instructions on the following link: 

https://blog.rapid7.com/2016/06/24/bro-series-creating-a-bro-cluster/

which allows the configuration of a cluster with workers as virtual machines.

After following all the instructions in the link, I get the following error when I try to install bro configuration:

[BroControl] > install
removing old policies in /home/aniss/bro/spool/installed-scripts-do-not-touch/site ...
removing old policies in /home/aniss/bro/spool/installed-scripts-do-not-touch/auto ...
creating policy directories ...
installing site policies ...
generating cluster-layout.bro ...
generating local-networks.bro ...
generating broctl-config.bro ...
generating broctl-config.sh ...
updating nodes ...
Host key verification failed.
Error: cannot create a directory on node worker-1
Error: Failed to establish ssh connection to host 192.168.56.2: [Errno 32] Broken pipe

I checked my ssh configuration on both the host machine and the vm worker and I think everything is correct.
 For the node.cfg file on the host machine (Bro manager), I have the following configuration:

# Example BroControl node configuration.
#
# This example has a standalone node ready to go except for possibly changing
# the sniffing interface.

# This is a complete standalone configuration.  Most likely you will
# only need to change the interface.
#[bro]
#type=standalone
#host=localhost
#interface=eno1

## remove the [bro] node above.

[logger]
type=logger
host=192.168.56.1

[manager]
type=manager
host=192.168.56.1

[proxy-1]
type=proxy
host=192.168.56.1

[worker-1]
type=worker
host=192.168.56.2
interface=eno1

#[worker-2]
#type=worker
#host=localhost
#interface=eth0

Notice also that I can access from my host machine to the vm (worker-1) using ssh over command line without issues.

Any ideas on how to fix this issue? Thanks.

**Comment by jsiwek** [comment]
"Host key verification failed." is an error message which commonly needs to be addressed in the ssh config, namely the `known_hosts` file (you can learn a bunch more details via google), so I suggest giving that another pass.  Some ideas: make sure your checking the config of the user that's actually running bro/broctl and make sure `known_hosts` has a valid entry for the destination host -- since you're using VMs it's often the case you had previously ssh'd into one at a given IP, but then later replaced the VM entirely such that in the future trying to ssh in again gives you this error due to the host key being different.

**Comment by aniss05** [comment]
Hi @jsiwek  I have fixed the ssh key validation issue but now when I try to run ''broctl deploy' I get the following error:

fatal error: problem with interface eno1 (pcap_error: SIOCGIFHWADDR: No such device (pcap_activate))

Any idea on how to fix this issue?

**Comment by jsiwek** [comment]
> fatal error: problem with interface eno1 (pcap_error: SIOCGIFHWADDR: No such device (pcap_activate))

Is "eno1" the name of a valid interface (e.g. listed in `ifconfig`) on `worker-1` ?  If it does it exist, you might test capturing on it with `tcpdump` to help troubleshoot further.  If it doesn't exist, you need to fix your `node.cfg`.

You might get quicker/better responses if you use the mailing list or IRC channel for seeking general support/help.  See contact info at https://www.zeek.org/contact/index.html
