### ISSUE TITLE
Modbus: Implement Diagnostics (0x08) parsing (and other extensions)

### ISSUE THREAD

**Issue by awelzel** [zeek/zeek#3184]
@biswajitutil in the forum asked to support parsing the diagnostics function code:

https://community.zeek.org/t/modbus-parser-enhancement/7079/5

He provided a link to a SO post of someone dissecting this over TCP:
https://reverseengineering.stackexchange.com/questions/30386/interpreting-response-for-modbus-tcp-function-code-0x08-diagnostics

The large `modbus.trace` file we have in the repo actually contains examples of this code being used over TCP:
https://github.com/zeek/zeek/blob/master/testing/btest/Traces/modbus/modbus.trace

Additional comments were the following, though could consider splitting into separate tickets.

> we may need to support the way to get pdu length in case of read file record ( func code 0x14)
>
> MBAP(modbus applucation PDU) header’s transaction ID, data length, execution code, address if any etc.
>
> There should be support extracting delimeter from PDU in case of func code 0x8 and sub function code 0x01
>
> For file related access ( read or write), we need to extract File number, therefore if we know the function code, there should be option to get all possible values it returns alongside . ( eg.
If FC == 43 and sub FC == 14 :
Source address = extract from PDU)

Reference: https://modbus.org/docs/Modbus_Application_Protocol_V1_1b3.pdf

**Comment by biswajitutil** [comment]
Thanks @awelzel ! 
So just want to two points
1. Subfunc code available with func code 0x8(diagonistics) and 0x2b( Encapsulated Interface Transport) in modbus TCP.
2. PDU length should come with all type of read/write ops. 
Lastly, can we add write_quantity similar to read_quantity in [modbus_read_write_multiple_registers_request](https://docs.zeek.org/en/master/scripts/base/bif/plugins/Zeek_Modbus.events.bif.zeek.html#id-modbus_read_write_multiple_registers_request). I am not sure why write_quantity is not there.

Thanks
Biswa

**Comment by timwoj** [comment]
> Subfunc code available with func code 0x8(diagonistics) and 0x2b( Encapsulated Interface Transport) in modbus TCP.

Does the data in the requests and responses matter or do you only care about the subfunction code for the diagnostics and the MEI code for the encapsulated transport?

**Comment by biswajitutil** [comment]
Thanks @timwoj , for diagnostics publishing subfunc code will be sufficient according to my understanding. But for 0x2b request resp may be needed, but as of now returning subfunc byte string should be ok. Will you provide patch for that or is it already merged? Please let me know the commit ID.

Regards,
Biswa

**Comment by timwoj** [comment]
@biswajitutil A prelim version is on the topic/timw/3184-modbus-extension branch, if you want to tinker with it. It's not complete, is missing the requested change to [modbus_read_write_multiple_registers_request](https://docs.zeek.org/en/master/scripts/base/bif/plugins/Zeek_Modbus.events.bif.zeek.html#id-modbus_read_write_multiple_registers_request), and needs some cleanup, but it'll parse the two extensions that you wanted. There's a new request an response event for each.

**Comment by timwoj** [comment]
@biswajitutil I added a commit to that branch to return a record containing the diagnostics data to be logged. It might be a bit too much, but you can take a look. Do you happen to have a pcap that includes diagnostic responses for subfunctions that return count values? Apparently the samples we have don't have any of those.

**Comment by biswajitutil** [comment]
Hi @timwoj ,
Can you please tell me how to get pdu_length in modbus packet? I can get pdu_type inside [Modbus::Info](https://github.com/zeek/zeek/blob/master/scripts/base/protocols/modbus/main.zeek#L12-L29) but not pdu length.
Similar information required for DNP3 as well. 

Thanks
Biswa

**Comment by timwoj** [comment]
The branch I linked above has a commit that adds the pdu length to the ModbusHeaders record type. An object of that type is passed with every event, so it should be available.

**Comment by biswajitutil** [comment]
Thanks @timwoj , I missed that commit. Should I try to merge to the release branch or compile your pushed branch separately?
Thanks
Biswa

**Comment by timwoj** [comment]
I merged in the above PR. If there's anything else feel free to reach out.
