### ISSUE TITLE
Potential performance issue with Supervisor Framework

### ISSUE THREAD

**Issue by J-Gras** [zeek/zeek#3190]
Using Zeek's Supervisor Framework to spawn clusters, I noticed that they don't scale as expected. Increasing the number of workers increases the total CPU time required to process the same amount of traffic rather significantly. For my tests I am working with Zeek 6.

To reproduce the issue, I am using the following script to process a PCAP replayed via a veth interface (`zeekplay`):
```Zeek
redef Cluster::retry_interval = 1sec;
redef Log::default_rotation_interval = 0secs;

event zeek_init()
        {
        if ( ! Supervisor::is_supervisor() )
                return;

        Broker::listen("127.0.0.1", 9999/tcp);

        local cluster: table[string] of Supervisor::ClusterEndpoint;
        cluster["manager"] = [$role=Supervisor::MANAGER, $host=127.0.0.1, $p=10000/tcp];
        cluster["logger"] = [$role=Supervisor::LOGGER, $host=127.0.0.1, $p=10001/tcp];
        cluster["proxy"] = [$role=Supervisor::PROXY, $host=127.0.0.1, $p=10002/tcp];

        local i = 0;
        while ( ++i <= 16 )
                {
                cluster[fmt("worker-%s", i)] = [
                        $role=Supervisor::WORKER, $host=127.0.0.1,
                        $p=count_to_port(10003 + i, tcp),
                        $interface="af_packet::zeekplay"];
                }

        for ( n, ep in cluster )
                {
                local sn = Supervisor::NodeConfig($name=n);
                sn$cluster = cluster;
                sn$directory = n;

                if ( ep?$interface )
                        sn$interface = ep$interface;

                local res = Supervisor::create(sn);

                if ( res != "" )
                        print fmt("supervisor failed to create node '%s': %s", n, res);
                }
        }
```
The above script creates 16 workers using AF_Packet to listen on the veth. Looking at the flame graph of a worker, pipe reads caught my attention:
![perf-16w-live-supervised-topspeed](https://github.com/zeek/zeek/assets/9075701/fd073a5e-3feb-44cc-bd06-4294e97ab811)
The pipe reads belong to the flare that is used in the event manager (the underlying file descriptor is used to make the event manager an IO source that can be polled):
https://github.com/zeek/zeek/blob/b6bff8aa37f3b51839b5d8dae606a09759e31e8c/src/Event.cc#L193-L195
Spending a lot of time in `native_queued_spin_lock_slowpath` doesn't seem desirable. Talking to @awelzel, we realized that it's not only the read but also the writes to the pipe that take a lot of time. Overall, about 22% is spent in spin locks here (search for `spin_lock_slowpath`). Unfortunately, it looks like this overhead scales with the number of workers.

Running a cluster with the same setup using `zeekctl`, the pipes don't run into these spin locks:
![perf-16w-live-topspeed](https://github.com/zeek/zeek/assets/9075701/42f7d40e-b9c0-4eed-a912-84ab31194ad8)

My next idea was that forking as done in supervisor mode somehow leads to all workers using the same pipe. While I would have expected this to cause even more trouble, I played around with `lsof` to take a look at the pipes used by each process. From what I understand, there is only one pipe, that is shared between all nodes. This pipe is probably the one used for the communication with the supervisor's stem process. So the nodes don't seem to share the _same_ pipes. However, maybe the problem is still somehow related to the way the processes are forked.

**Comment by awelzel** [comment]
Okay, sorry for the delay. With a setup similar to Jan's, comparing a supervisor cluster and a cluster started with a bit of ad-hoc Python subprocess management:

* Replaying `tls13_wolfssl.pcap` at 50kpps into a veth:
  ```
  tcpreplay -p 50000 --unique-ip --stats 1 -l 0 -T nano -i zeekplayin tls13_wolfssl.pcap
  ```

* 16 worker listening on `zeekplay` using af_packet
* one proxy, one logger, one manager
* Generates ~2400 ssl logs/s

The Zeek supervisor results in 40-70% per-worker cpu usage, the Python based supervisor 5-8% per worker CPU usage.

This is not just a potential performance issue, this pretty much can't be used for anything serious...q

![Screenshot-20231020-151314](https://github.com/zeek/zeek/assets/2100509/487c434b-bab4-4518-b592-ea5fe4aae745)

![Screenshot-20231020-151538](https://github.com/zeek/zeek/assets/2100509/8750efbd-8fae-4668-be38-0637c7d6dbd0)

Will try to figure out what's going on next, `perf report` indicates `linux_kevent_copyout` `ioctl` invocation hitting a spinlock.
![Screenshot-20231020-152607](https://github.com/zeek/zeek/assets/2100509/785a9d0b-94b8-4e4a-8191-1e3c33900f57)
