### ISSUE TITLE
VNC Scanners trigger binpac exceptions

### ISSUE THREAD

**Issue by JustinAzoff** [zeek/zeek#320]
This dpd log is triggered thousands and thousands of times by a vnc scanner:

{"analyzer":"RFB","failure_reason":"Binpac exception: binpac exception: out_of_bound: RFBSecurityTypes37:types: 2 > 0"}

Likely it just isn't sending any security types or something.

**Comment by jsiwek** [comment]
A pcap may be best for this -- it looks like `RFBSecurityTypes37` is in the server response and it's saying there's 2, but not sending anything, so it may be a legit exception to throw.  Maybe either the ProtocolConfirm needs to happen later, or need a way to generally limit/blacklist logging per-type in `dpd/main.bro`, or something else is going wrong.

**Comment by JustinAzoff** [comment]
was able to extract + anonymize this from a larger pcap

[5900_scan_one_anon_fixed.zip](https://github.com/zeek/zeek/files/3030800/5900_scan_one_anon_fixed.zip)

```
$ bro -r 5900_scan_one_anon_fixed.pcap
$ cat dpd.log |bro-cut failure_reason
Binpac exception: binpac exception: out_of_bound: RFBSecurityTypes37:types: 2 > 0
```

Interesting that wireshark also complains about a malformed packet

**Comment by jsiwek** [comment]
Thanks, this seems like it may be due using `datagram` instead of `flowunit`.  I.e. we need incremental parsing, but I'll need to update a bunch of records in the protocol grammar to get that to work -- looking into it.
