### ISSUE TITLE
6.0.0 vs FreeBSD

### ISSUE THREAD

**Issue by leres** [zeek/zeek#3200]
I can't quite figure out this configure puzzle:
```
CMake Error at /wrkdirs/usr/ports/security/zeek/work/stage/usr/local/share/zeek/cmake/ZeekPlugin.cmake:27 (find_package):
  Could not find a package configuration file provided by "Zeek" with any of
  the following names:

    ZeekConfig.cmake
    zeek-config.cmake

  Add the installation prefix of "Zeek" to CMAKE_PREFIX_PATH or set
  "Zeek_DIR" to a directory containing one of the above files.  If "Zeek"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  /wrkdirs/usr/ports/security/zeek/work/stage/usr/local/share/zeek/cmake/ZeekPlugin.cmake:68 (zeek_plugin_bootstrapping)
  CMakeLists.txt:5 (include)
```
I can find `/wrkdirs/usr/ports/security/zeek/work/.build/ZeekConfig.cmake` but I cannot find a way to set a variable so that the file is found. Interestingly this is the same directory where `ZeekPlugin.cmake` is found!

A little help please?

**Comment by timwoj** [comment]
It should automatically discover that without needing to tell it where it is. What version of FreeBSD and CMake? We're doing builds for 12, 13, and 14 on CI and all of them are currently passing, but we're also not building it as part of a FreeBSD port.

**Comment by awelzel** [comment]
@leres - could you provide some more background when this error occurs? Is it during the Zeek build or when building an additional plugin? In either case, mind providing a few more detailed steps how to provoke that error?

**Comment by leres** [comment]
Sorry for opening an issue and then going MIA -- I've been out of town for a few weeks...

Here's an example failing poudriere build log: [zeek-6.0.0.log.gz](https://github.com/zeek/zeek/files/12317308/zeek-6.0.0.log.gz)

The poudriere build happens inside a jail and although the build happens with `PREFIX=/usr/local`,  it is installed in `/wrkdirs/usr/ports/security/zeek/work/stage` before creating a package that can be used to install on other systems. So one problem is that it tries to find `ZeekConfig.cmake`, which at that point in the build, is located in `/wrkdirs/usr/ports/security/zeek/work/stage/usr/local/share/zeek/cmake/ZeekConfig.cmake`.

So I think I'm pretty close, I just need to update `CMAKE_PREFIX_PATH` or `Zeek_DIR` so the build can find this file.

Another issue I see is just prior to the build failure we have:
```
cd /wrkdirs/usr/ports/security/zeek/work/zeek-netmap-2.0.0 && /usr/bin/env PATH=/wrkdirs/usr/ports/security/zeek/work/zeek-bin:/wrkdirs/usr/ports/security/zeek/work/.bin:/usr/local/bin:/usr/local/sbin:/bin:/usr/bin:/sbin:/usr/sbin  ./configure --with-netmap=/usr  --install-root=/wrkdirs/usr/ports/security/zeek/work/stage/usr/local/lib/zeek/plugins
Usage: zeek-config [OPTIONS]
Basic options:

  --build_type          Zeek build type as per cmake, lower case (e.g. 'relwithdebinfo')
[...]
```
Which looking at my poudriere/port `Makefile` is telling me my NETMAP option needs updating:
```
post-install-NETMAP-on:
        ${MKDIR} ${WRKDIR}/zeek-bin
        ${CP} ${STAGEDIR}${PREFIX}/bin/zeek-config ${WRKDIR}/zeek-bin
        ${REINPLACE_CMD} -e 's|${PREFIX}|${STAGEDIR}${PREFIX}|g' \
            ${WRKDIR}/zeek-bin/zeek-config
        cd ${WRKSRC_zeek_netmap} && ${SETENV} PATH=${WRKDIR}/zeek-bin:${PATH} \
            ./configure --with-netmap=/usr \
            --install-root=${STAGEDIR}${PREFIX}/lib/zeek/plugins
        cd ${WRKSRC_zeek_netmap}/build && make && make install
        @${STRIP_CMD} ${STAGEDIR}${PREFIX}/lib/zeek/plugins/Zeek_Netmap/lib/Zeek-Netmap.freebsd-${UNAME_M}.so
```
So maybe what I really need to ask is does it still make sense to build `NETMAP` and if so what am I doing wrong?

**Comment by timwoj** [comment]
Assuming I'm looking at the right version of the netmap plugin (zeek/zeek-netmap), it's still trying to lookup the CAF root from `zeek-config`. That option was deprecated in 5.0 and removed in 5.1. These lines can go:

```
            if [ -z "$caf_root" ]; then
		echo "caf"
                append_cache_entry CAF_ROOT_DIR PATH `${zeek_config} --caf_root`
            fi
```

That at least explains why you're getting the `zeek-config` usage output. I'll open a PR against that repo to remove them.

**Comment by leres** [comment]
Thanks Tim, that solves the configure usage issue. 

My remaining problem is configuring netmap. I can solve the missing cmake pluging by setting  Zeek_DIR to the /wrkdirs/... path containing ZeekPlugin.cmake in the environment but now I have a new error:
```
zinc 32 @ make post-install-NETMAP-on
/bin/mkdir -p /wrkdirs/usr/ports/security/zeek/work/zeek-bin
cp -f /wrkdirs/usr/ports/security/zeek/work/stage/usr/local/bin/zeek-config /wrkdirs/usr/ports/security/zeek/work/zeek-bin
/usr/bin/sed -i.bak -e 's|/usr/local|/wrkdirs/usr/ports/security/zeek/work/stage/usr/local|g'  /wrkdirs/usr/ports/security/zeek/work/zeek-bin/zeek-config
cd /wrkdirs/usr/ports/security/zeek/work/zeek-netmap-2.0.0 && /usr/bin/env PATH=/wrkdirs/usr/ports/security/zeek/work/zeek-bin:/usr/local/libexec/ccache:/wrkdirs/usr/ports/security/zeek/work/.bin:/usr/local/bin:/usr/local/sbin:/bin:/usr/bin:/sbin:/usr/sbin  Zeek_DIR=/wrkdirs/usr/ports/security/zeek/work//usr/local/lib/zeek/cmake  ./configure --with-netmap=/usr  --install-root=/wrkdirs/usr/ports/security/zeek/work/stage/usr/local/lib/zeek/plugins
Build Directory        : build
Zeek Source Directory  : 
CMake Error at /wrkdirs/usr/ports/security/zeek/work/stage/usr/local/share/zeek/cmake/BifCl.cmake:2 (message):
  BifCl.cmake needs Zeek::BifCl
Call Stack (most recent call first):
  /wrkdirs/usr/ports/security/zeek/work/stage/usr/local/share/zeek/cmake/ZeekPlugin.cmake:73 (include)
  CMakeLists.txt:5 (include)


-- Configuring incomplete, errors occurred!
*** Error code 1

Stop.
make: stopped in /usr/ports/security/zeek
```
It feels like what I'm fighting is that netmap really wants zeek to be installed in /usr/local at configure time and that's not really possible. I don't understand why this wasn't a problem before now since netmap hasn't changed for some time.

Maybe it makes sense for me to split netmap off to a separate FreeBSD port so that zeek can be installed when the netmap configure script runs?

**Comment by timwoj** [comment]
> CMake Error at /wrkdirs/usr/ports/security/zeek/work/stage/usr/local/share/zeek/cmake/BifCl.cmake:2 (message):
>   BifCl.cmake needs Zeek::BifCl
> Call Stack (most recent call first):
>   /wrkdirs/usr/ports/security/zeek/work/stage/usr/local/share/zeek/cmake/ZeekPlugin.cmake:73 (include)
>   CMakeLists.txt:5 (include)

This looks like https://github.com/zeek/cmake/issues/76. I'm not sure what the plan is on fixing that, but I'll ping Dominik when he's back from vacation.

I managed to reproduce it not finding ZeekPlugin by installing zeek, moving the entire install root to a different location, and then pointing `--install-root` for zeek-netmap's configure at that new location. I was able to get around that by passing `--zeek-dist` as well and pointing it at the root of the source tree I built zeek from. I imagine we could make the stock `configure` script for plugins a little smarter to have it try harder to find the cmake files in install path though.

**Comment by leres** [comment]
I fought with cmake but ultimately I was not able to get zeek-netmap to build with zeek installed in ` /wrkdirs/usr/ports/security/zeek/work/stage/usr/local`.

I started working on a new zeek-netmap port for FreeBSD but even in a poudriere jail that has zeek installed in /usr/local, I'm still having trouble getting it to configure:
```
CMake Error at CMakeLists.txt:5 (include):
  include could not find requested file:

    ZeekPlugin


CMake Error at CMakeLists.txt:7 (find_package):
  By not providing "FindNetmap.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Netmap", but
  CMake did not find one.

  Could not find a package configuration file provided by "Netmap" with any
  of the following names:

    NetmapConfig.cmake
    netmap-config.cmake

  Add the installation prefix of "Netmap" to CMAKE_PREFIX_PATH or set
  "Netmap_DIR" to a directory containing one of the above files.  If "Netmap"
  provides a separate development package or SDK, be sure it has been
  installed.
```
Looking at the option configure I'm guessing I need to have a zeek source tree unpacked and added to BRO_DIST, ZEEK_DIST, and CMAKE_MODULE_PATH?

**Comment by leres** [comment]
I was able to update the FreeBSD zeek port by ditching NETMAP support. The consensus seems to be that this is a rarely used feature.

I looked into creating a new  zeek-netmap port but didn't quite get it working. Meanwhile Michael Shirk tells me another way to get NETMAP is via a zkg package so maybe a zeek-netmap is not even the "right" way to do this.

Thanks (as usual) for the help.
