### ISSUE TITLE
Allow to add &log attribute for exported types.

### ISSUE THREAD

**Issue by J-Gras** [zeek/zeek#3218]
Sometimes it would be handy to use auto-exported types for logging. However, as the type definitions are missing Zeek's `&log` attribute, no values will be written if the type is used in a log.

Take the following example (see https://github.com/J-Gras/spicy-test-export for the complete code):
```
public type A = unit {
	: b"\xFF";
	b1: bitfield(8) {
		b1_1: 0..3;
		b1_2: 4..7;
	};
	b2: B;
	b3: uint8;
	b4: bytes &eod;
};

type B = unit {
	data: bitfield(8) {
		b2_1: 0..3;
		b2_2: 4..7;
	};
} &convert=self.data;
```
Exporting `A`, non of its fields will be logged when putting A into a log record:
```Zeek
type Info: record {
	ts: time &log;
	#...
	content: A &log;
};
```
Like in zeek/zeek#3219 , extending the export syntax in evt-files could be an option.

For now there is a partial workaround by adding the `&log` attribute on the Zeek side:
```Zeek
redef record Export_Test::A$b3 += { &log };
redef record Export_Test::A$b4 += { &log };
```
Note that this won't work for `b1` and `b2` in the above example.

**Comment by rsmmr** [comment]
I'll look into this.
