### ISSUE TITLE
Cirrus CI Free Usage Limits starting September

### ISSUE THREAD

**Issue by awelzel** [zeek/zeek#3221]
We're currently using Cirrus CI for testing Linux, FreeBSD, MacOS, Windows builds and running the test suite upon PRs and merges to master.

Starting September, Cirrus CI will restrict usage.

https://cirrus-ci.org/blog/2023/07/17/limiting-free-usage-of-cirrus-ci/

> Unfortunately the day has come. As a self-bootstrapped company Cirrus Labs can no longer provide unlimited usage of Cirrus CI for public repositories for free. We have to put a limit on the amount of compute resources that can be consumed for free each month by organizations and users. Starting September 1st 2023, there will be an upper monthly limit on free usage equal to 50 compute credits (which is equal to a little over 16,000 CPU-minutes for Linux tasks).

Posted elsewhere by @timwoj :

> We’re so far over that ~40~ 50 credit limit that it’s not even funny.
> ![Screenshot 2023-08-02 at 10 43 16 AM](https://github.com/zeek/zeek/assets/2100509/3080d6a0-ad68-4b91-9cd4-163a3132acc6)

From the looks of it, if we don't do anything, we won't have CI in September.

### Ideas

* Reduce test matrix on PRs and merges drastically, use cron building
  * 50 credits seem out of reach no matter how we cut the matrix or lower the frequency
* Provide Compute Services via gcloud/AWS
  * Unsure how this fares price wise and adds operational burden
* Pay $ for compute credits
* Move to GitHub actions
  * [FreeBSD support](https://github.com/vmactions/freebsd-vm) via VM on MacOS runners
  * No native arm64 runners
    * Only building/testing on Debian and providing Docker container images.
    * Cross-compiling possible?
  * [Limited CPU cores available](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources). Linux/Windows have 2. Bigger runners cost money.

**Comment by timwoj** [comment]
This is resolved. Corelight has offered to pay for the service, and we've switched over to a paid plan.
