### ISSUE TITLE
Require Python 3.7 or greater?

### ISSUE THREAD

**Issue by timwoj** [zeek/zeek#3239]
We recently bumped the required version of Python for standalone installs of btest up to Python 3.7. The btest script still runs fine if invoked manually with an older version of Python, since we didn't make a lot of changes that would have required the newer version. As part of the changes to remove uses of `FndRequiredPackage`, I was also bumping our required version of Python in other submodules to 3.7 as well. Unfortunately I ran into some issues with a few of the builds where it would fail to find that version, because the VM on Cirrus (and the base OS) still have some older version of Python by default.

Python 3.6 was marked as end-of-life back in 2021. Python 3.7 was actually marked end-of-life in June 2023 too. Should we consider moving our required version of Python up to something that's supported? That will require fixing the following VMs on Cirrus to have a newer version of Python installed than the stock version:

- ubuntu18 with python 3.6.9
- opensuse leap with python 3.6.15
- centos7 with an unknown version of python, since their old version of cmake doesn't report it. A docker container says it's 3.6.8.
- centosstream8 with python 3.6.8

**Comment by 0xxon** [comment]
This will also have an impact for the binary packages; in cases where the python version is deemed to old, the python broker bindings are no longer built - which (I think) means that some zeekctl functionality stops working; there are some people who also use the broker bindings for their projects.

Unless we need the new features, I am tempted to leave things as they are. While the python versions are EOL - they are still maintained by the distributions.

**Comment by bbannier** [comment]
> Unless we need the new features, I am tempted to leave things as they are. While the python versions are EOL - they are still maintained by the distributions.

One motivation for moving to a non-EOL version of Python was that e.g. language features like f-strings and lint tooling which didn't support EOL versions like python-3.6; it was e.g., previously impossible to catch uses of features from >=python-3.6 in our code. With the switch to requiring at least python-3.7 we now [run code which automatically upgrades constructs to more modern forms](https://github.com/zeek/btest/blob/6339085fa2d09ff44ab0e4c00905f92b8f79217f/.pre-commit-config.yaml#L30-L34) in most repos with Python code (e.g., BTest, package-manager). As an example, BTest contains many f-strings now and I'd doubt that it would run on stock python-3.6 and am unsure what distributions backport.

**Comment by awelzel** [comment]
> like f-strings

They are in 3.6, luckily..


>Unless we need the new features, I am tempted to leave things as they are. While the python versions are EOL - they are still maintained by the distributions.

For new projects - thinking broker websocket python bindings - external dependencies may require >= Python 3.7 ([websockets has a 3.8 entry](https://github.com/python-websockets/websockets/blob/main/pyproject.toml#L8). They may still work, but could break at anytime. IMO we should not go out of our way to support these on distros that ship Python 3.6.

**Comment by 0xxon** [comment]
Are the newer versions of python just available as packages on these operating systems? In that case, that seems fine and easy.

Otherwise we should/will have to change our [Platform Support Policy](https://github.com/zeek/zeek/wiki/Platform-Support-Policy) - either by dropping some operating systems, or changing the part about python in it.

**Comment by timwoj** [comment]
> Are the newer versions of python just available as packages on these operating systems? In that case, that seems fine and easy.

- Centos 7: rh-python38 package exists in centos-scl repo, which we're already using for other packages. It installs into `/opt/rh/rh-python38`, so that would need to be in the path for all of our tests.
- Centos Stream 8: python38, python39, and python311 (but not python310?) packages are available in the default repository
- OpenSUSE Leap 15.4: python39, python310, and python311 packages are available in the default repository
- Ubuntu 18: python37 package exists in default repository

**Comment by timwoj** [comment]
I put the required changes for each of those platforms on the `topic/timw/python37-builds` branch. All of them have Python 3.8 installed and the necessary changes to make builds complete. Most of them are pretty straight-forward except for ubuntu18. That one has a python38 package, but not a corresponding python38-pip package so I had to do a bit of gymnastics to get pip to work correctly. It ends up installing both python36 and python38, but the paths point to python38 and packages are installed for that version.

**Comment by 0xxon** [comment]
We can actually just remove Ubuntu 18.04 - it reached it's standard EOL in May.

**Comment by 0xxon** [comment]
Mostly note to myself - after merging this, the binary packages will be broken for a bit until I sort this out there too. But this is relatively easily fixable as it only affects rpm-based distributions.

**Comment by timwoj** [comment]
How does the OS support matrix work in regards to a change like this? I see we have notes on a few of the builds because they have old compilers and we had to do special things to get them to build. Should we add an extra note for these platforms once the actual 3.7 upgrade is finished across the board? 

Pinging @ckreibich for thoughts since he's the one that maintains that matrix usually.

**Comment by timwoj** [comment]
I went through all of the other builds and collected the versions seen: 

macOS ventura: 3.11.4
macOS Monterey: 3.8.9
Freebsd 14: 3.9.17
Freebsd 13: 3.9.16
Freebsd 12: 3.9.17
Fedora 38: 3.11.4
Fedora 37: 3.11.4
CentOS Stream 9: 3.9.17
Debian 12: 3.11.2
Debian 11: 3.9.2
Debian 10: 3.7.3
OpenSUSE Tumbleweed: 3.11.4
Ubuntu 22.10: 3.10.7
Ubuntu 22: 3.10.12
Ubuntu 20: 3.8.10
Alpine: 3.11.4
Windows: 3.11.4

Debian 10 is the only one that's not 3.8 or above. I propose fixing that build as well if possible, and then setting the minimum Python version to 3.8. That's in line with 3.7 already being EOL'd back in June, making 3.8 the currently lowest supported version.

**Comment by timwoj** [comment]
Reopening because this isn't actually done (thanks GitHub).

**Comment by timwoj** [comment]
> Debian 10 is the only one that's not 3.8 or above. I propose fixing that build as well if possible.

This doesn't look possible. Nothing above 3.7 is available in the standard repositories, the deadsnakes PPA only supports ubuntu, and a quick googling only found instructions for installing it via a manual build of the release tarball.

**Comment by ckreibich** [comment]
Thanks for digging through the details here folks, tedious stuff.

@timwoj you asked about the support policy and I think https://github.com/zeek/zeek/wiki/Platform-Support-Policy still applies. Within reason this means up to the last two releases plus any LTS, as long as supported, assuming we can build with packages available by default in the distribution (i.e., no non-standard repos).

So as long as a platform offers supported Python versions, even if they're not the default but switchable via package manager commands, I think we should support it.

I don't think we need to call out the Python version on https://github.com/zeek/zeek/wiki/Zeek-Operating-System-Support-Matrix unless somebody here would find that info useful — it all adds to our manual maintenance burden.

Sound good? 

Btw — Ubuntu 22.10 is EOL too.

**Comment by timwoj** [comment]
Debian 10 is being removed from the list of supported distros (as of 7.0-dev), so we can go through with this upgrade.

**Comment by timwoj** [comment]
Also, since we last talked about this, 3.7 went end-of-llfe (27 Jun 2023) and 3.8 is slated to go end-of-life in Oct 2024. With those in mind, we should considering moving to 3.9 across the board which gives us until Oct 2025 before it goes EOL as well.

**Comment by bbannier** [comment]
Another reason to move to at least >=3.9 is that the ecosystem has moved past 3.8, e.g., [Sphinx](https://pypi.org/project/Sphinx/) which we require for building docs in many subprojects currently requires at least >=3.9, but we currently cannot use that version (e.g., in https://github.com/zeek/package-manager we still [require `Sphinx>=3.0`](https://github.com/zeek/package-manager/blob/06dea74d6f1ae25474f541d5891d98255370ef2a/requirements.txt#L6) even tough the current version is `Sphinx-7.2.6`).

**Comment by timwoj** [comment]
After a discussion in a team call, we've decided to go through with this and bump the support to Python 3.9. It's supported by all of the platforms on our OS support matrix as well as on Cirrus and OBS.

The following repos will need changes:
- btest
- zeek-aux
- zeek-client
- zeek-docs
- zeekctl
- zeek

**Comment by timwoj** [comment]
This is now done via https://github.com/zeek/zeek/pull/4083 and a series of associated PRs.
