### ISSUE TITLE
Compiling on Alpine is failing at 91%

### ISSUE THREAD

**Issue by 2Belette** [zeek/zeek#3244]
Alpine Linux v 3.18

```
[ 91%] Building libkqueue
[ 88%] Built target objlib
[ 94%] Built target kqueue
[100%] Built target kqueue_static
[ 91%] Completed 'project_kqueue'
[ 91%] Built target project_kqueue
[ 91%] Linking CXX executable src/zeek
/usr/lib/gcc/x86_64-alpine-linux-musl/12.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: src/zeekygen/CMakeFiles/zeek_zeekygen_obj.dir/Target.cc.o: in function `zeek::zeekygen::detail::dir_contents_recursive(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
/root/zeek/src/zeekygen/Target.cc:493: undefined reference to `fts_open'
/usr/lib/gcc/x86_64-alpine-linux-musl/12.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /root/zeek/src/zeekygen/Target.cc:505: undefined reference to `fts_read'
/usr/lib/gcc/x86_64-alpine-linux-musl/12.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /root/zeek/src/zeekygen/Target.cc:514: undefined reference to `fts_close'
collect2: error: ld returned 1 exit status
make[3]: *** [CMakeFiles/zeek_exe.dir/build.make:1521: src/zeek] Error 1
make[2]: *** [CMakeFiles/Makefile2:3718: CMakeFiles/zeek_exe.dir/all] Error 2
make[1]: *** [Makefile:166: all] Error 2
make[1]: Leaving directory '/root/zeek/build'
make: *** [Makefile:15: all] Error 2
```

Any suggestion on how to fix the undefined reference to 'fts_read' and 'fts_close' ?

I read a couple of things from other projects but it seems that some others have been able to succesfuly build/run Zeek on Alpine Linux, so I imagine I am close to.

**Comment by bbannier** [comment]
It looks like musl [deliberately doesn't include `fts.h` and related functions like `fts_read` or `fts_close`](https://wiki.musl-libc.org/faq.html#Q:_Why_is_%3Ccode%3Efts.h%3C/code%3E_not_included?), so default musl is insufficient for fully linking Zeek.

There seem to be [extensions available](https://github.com/pullmoll/musl-fts) for musl which included this functionality. I haven't tried this, but you might have luck with linking these libraries.

**Comment by awelzel** [comment]
> Any suggestion on how to fix the undefined reference to 'fts_read' and 'fts_close' ?

In CI, we're installing `musl-fts-dev`, that should fix it.

https://github.com/zeek/zeek/blob/e8292be0ce8469758a5f8cb444c7e379e67dba65/ci/alpine/Dockerfile#L15C1-L17

**Comment by 2Belette** [comment]
Thanks @awelzel, indeed that's what I did (installing musl-fts-dev) but it was apparently not enough.. but I am wondering if it was because of running ./configure prior to installing musl-fts-dev. I just re-ran ./configure and make and now I was able to make it :)

Many thanks and sorry for the noise
