### ISSUE TITLE
Allow for enumeration of intel

### ISSUE THREAD

**Issue by mavam** [zeek/zeek#325]
The intel framework currently doesn't provide a public API for enumerating the contained intel. The global `data_store` instance is not exported. However, I'm not sure if exporting it would be a clean solution, because it's only available at the master.

How do other scripts handle such a use case? Provide a function that takes a callback? For example, if we had a public function `Intel::for_each(f)` with `f` being an instance of `function(x: Intel::Item)`, we wouldn't have to export the internal representation of intel but still  allow for enumeration.

**Comment by rsmmr** [comment]
What's the use case here? As intel data can potentially be very large, iterating over it could lead to long delays and exposing an API for it could hence cause trouble if people don't realize the risk.

**Comment by mavam** [comment]
The idea was to get a dump of all intel that in Zeek. This set could be different from the one bulk-loaded with files at startup, due to aging and insertion at runtime. I hear your concerns regarding performance. It could certainly be an expensive operation.

But we no longer need this abstraction at this point, so feel free to close this issue.
