### ISSUE TITLE
PKtDumper file rotation support (-w)

### ISSUE THREAD

**Issue by SigmaStar** [zeek/zeek#3258]
Currently zeek can dump packets into pcap file with the option "-w". But all packets were stored into a single file which makes this file very giant in size. Is that possible to split trace logs into pieces and store them in different file? for example the first 1000 packets will be stored in record.0.pcap, and the following 1000 in record.1.pcap and so on.

**Comment by awelzel** [comment]
> Currently zeek can dump packets into pcap file with the option "-w". But all packets were stored into a single file which makes this file very giant in size. Is that possible to split trace logs into pieces and store them in different file? 

Hello @SigmaStar - Zeek currently does not support this. It's possible to add this functionality through and external plugin - one would implement a `PktDumperComponent`.

Could you say a bit more about your environment? I'm seeing that `tcpdump` has `-W`, `-G` and `-C`. If possible it might be more robust - restarting Zeek workers would cause gaps in pcap stream - to run tcpdump next to it. Depends on your packet acquisition however if that's feasible/efficient.

**Comment by ckreibich** [comment]
There's a quirky feature in Zeek around log rotation that actually supports this. If you call the `rotate_file_by_name()` function on the file you're dumping packets to, Zeek will rotate to a new pcap. This is actually implemented in a script that ships with the distribution, see [`misc/trim-trace-file`](https://github.com/zeek/zeek/blob/master/scripts/policy/misc/trim-trace-file.zeek).

**Comment by awelzel** [comment]
@SigmaStar - does @ckreibich answer help your use-case?

Feel free to re-post the question on how to best do this on Slack or Discourse. I'm closing this ticket for now.
---
https://zeek.org/community/
