### ISSUE TITLE
Registering a Spicy analyzer for a single port `N` also registers for `N+1`

### ISSUE THREAD

**Issue by bbannier** [zeek/zeek#3278]
If one registers a Spicy analyzer for a single port `N` it will also be registered for the following port `N+1`.

```ruby
# @TEST-REQUIRES: have-spicy
#
# @TEST-EXEC: spicyz -d -o x.hlto analyzer.spicy analyzer.evt
# @TEST-EXEC: zeek x.hlto -B spicy
# @TEST-EXEC: grep 'Scheduling analyzer for port' debug.log > registration.log
# @TEST-EXEC: btest-diff registration.log

# @TEST-START-FILE analyzer.spicy
module foo;
public type X = unit {
    : bytes &eod;
};
# @TEST-END-FILE

# @TEST-START-FILE analyzer.evt
protocol analyzer spicy::SSH over TCP:
    port 1024/udp;
# @TEST-END-FILE
```

This outputs
```
0.000000/1694070268.754467 [spicy]   Scheduling analyzer for port 1024/udp
0.000000/1694070268.754473 [spicy]   Scheduling analyzer for port 1025/udp
```

This seems to be due to how we handle port ranges, https://github.com/zeek/zeek/blob/1441b83411a4cf79d095b0d9950ad47e5ffa3d2f/src/spicy/spicyz/glue-compiler.cc#L300-L302

**Comment by awelzel** [comment]
Possibly work-around for Zeek 6.0 is to remove the `port 1024/udp` specification from `.evt` files and instead to the analyzer registration within Zeek script using the `Analyzer::register_for_ports()` port.
