### ISSUE TITLE
the method of get the name of input stream 

### ISSUE THREAD

**Issue by lzkking** [zeek/zeek#3286]
Hello, I'm currently working on parsing the TNS protocol, and I'm using self.input() at the beginning of each packet to mark rewind points in the data stream. This is necessary because I need to perform packet reassembly and skip unknown fields. However, I've noticed that when I use self.input to mark a rewind point, the data after that point isn't being released. As a result, when I capture and parse multiple packets from the network, a lot of processed data remains in memory. I've checked the Spicy documentation, and it suggests using trim from the iterator<stream> obtained with self.input to manually trim the stream. However, I'm using a method that captures data packets from the network in real-time for parsing. How can I obtain the name of that data stream?

    on %init {
        self.start = self.input();      (1)
    }

    packetLength : uint64;
    packetType : int8 &convert = typeOpcode($$);
    packetRsrvd : int8;
    headerChksm : uint16;

In (1), after using self.input to obtain an iterator<stream>, I have observed that the memory located after this iterator<stream> is not released in the future unless I manually release it, even though this data has already been parsed. I found in section 5.2.5.17 of the Spicy documentation that I can use trim(inout i: iterator<stream>) → void to trim the memory before the iterator<stream>, but this is a method of the stream type. How can I obtain the name of that input stream, just like using inputStream.trim(iterator<stream>) to trim memory? Is there any function to obtain this inputStream?

Here is my EVT file：
protocol analyzer spicy::ORACLE over TCP:
    parse originator with ORACLE::LoopReadClientPacket,
    parse responder with ORACLE::LoopReadServerPacket,
    port 1521/tcp;

I want to use the trim method from the stream, but to use trim, I need to know the stream. How can I obtain this stream?

**Comment by bbannier** [comment]
We don't use GitHub issues for support questions. Questions like this are best answered using either slack or our forum, which is both are frequented by Zeek developers and professional users. You can join here:

Forum: https://community.zeek.org/

Slack: https://zeek.org/community/

---

Duplicates #3283.
