### ISSUE TITLE
Push container images for RC releases

### ISSUE THREAD

**Issue by awelzel** [zeek/zeek#3287]
Plainly creating a ticket from this discussions on zeek-docs:

              We don't push `-rc1` - I sometimes wished we did though. Worth it?

_Originally posted by @awelzel in https://github.com/zeek/zeek-docs/pull/200#discussion_r1262178127_

**Comment by ckreibich** [comment]
I wonder whether we should give this one a go for 7.1. still. It might get a little futzy but overall it doesn't look too hard — tweaks to the `container_image_manifest_docker_builder` task for the `only_if` tag pattern so it allows RC tags, and where to route the images?

We'd need to make sure they don't get tagged `latest`, and we'd probably send RC images to `zeek/zeek-dev`?

**Comment by awelzel** [comment]
> and we'd probably send RC images to zeek/zeek-dev?

I'd actually vote for `zeek/zeek` given those tags are stable, e.g. make `docker pull zeek/zeek:7.0.1-rc1` work.

Also, `latest` should be the only tag in `zeek/zeek-dev` and it's always moving with master. There's no stable tags in the `zeek/zeek-dev` repo so far. I like the distinction between the repos in this regard (it's okay to nuke zeek/zeek-dev and have it recover with the next build. It'd be different once it contains rc tags).

**Comment by ckreibich** [comment]
Sounds good. I was thinking that regular users won't care about our release candidates — no biggie. My comments re `latest` only applied to `zeek-dev`, exactly because it's always moving with master.

Thanks for jumping on this!
