### ISSUE TITLE
Missing Zeek 5.0.10 dependencies of Zeek repository in Ubuntu 20.04

### ISSUE THREAD

**Issue by dknhat2000** [zeek/zeek#3296]
Follow install instructions on this link https://software.opensuse.org/download.html?project=security%3Azeek&package=zeek-lts
Run:
`apt install zeek-5.0`
Output:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 zeek-5.0 : Depends: zeek-5.0-zkg (= 5.0.1-0) but it is not going to be installed
            Depends: zeek-5.0-client (= 5.0.1-0) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
Check repository:
`apt search zeek-5.0`
Output:
```
Sorting... Done
Full Text Search... Done
zeek-5.0/unknown 5.0.1-0 arm64
  Zeek is a powerful framework for network analysis and security monitoring.

zeek-5.0-btest/unknown 5.0.9-0 all
  The BTest test framework

zeek-5.0-btest-data/unknown 5.0.9-0 all
  Test data for use by the BTest test framework

zeek-5.0-client/unknown 5.0.9-0 all
  The Zeek Cluster Management Client

zeek-5.0-core/unknown 5.0.1-0 arm64
  Zeek is a powerful framework for network analysis and security monitoring.

zeek-5.0-core-dev/unknown 5.0.1-0 arm64
  Zeek is a powerful framework for network analysis and security monitoring.

zeek-5.0-spicy-dev/unknown 5.0.1-0 arm64
  Spicy development files.

zeek-5.0-zkg/unknown 5.0.9-0 all
  Zkg is Zeek's package manager.
```

The repository does not have zeek-5.0-zkg (= 5.0.1-0) and zeek-5.0-client (= 5.0.1-0)

**Comment by awelzel** [comment]
@dknhat2000 , which Debian / Ubuntu version are you running? It looks like you're on arm64/ aarch64 and the latest packages may have failed to build (for Debian 12 it looks as if we never attempted to build them, and the latest Debian 11 build for aarch64 failed):

https://build.opensuse.org/packages/zeek-5.0/job_history/security:zeek/Debian_12/aarch64

https://build.opensuse.org/packages/zeek-5.0/job_history/security:zeek/Debian_11/aarch64

@timwoj , would you know which knobs to press to start a Debian 12 build for zeek-5.0 with aarch64? Also, it doesn't seem aarch64 is enabled for zeek-6.0+Debian 12 while it is for Debian 11.

For the Debian 11 failure it says:
```
[ 6230s] /usr/lib/aarch64-linux-gnu/libresolv.a(res_comp.o): in function `__res_hnok':
[ 6230s] (.text+0x120): relocation truncated to fit: R_AARCH64_LD64_GOTPAGE_LO15 against symbol `__stack_chk_guard@@GLIBC_2.17' defined in .data.rel.ro section in /lib/ld-linux-aarch64.so.1
[ 6230s] /usr/bin/ld: (.text+0x120): warning: too many GOT entries for -fpic, please recompile with -fPIC
[ 6230s] collect2: error: ld returned 1 exit status
```
And we had the following ticket around the linker error previously - assumption was Gold linker usage may be to blame, but Zeek 5.0.10 + Spicy 1.5.4 should not use Gold anymore. Maybe we need to put `-fPIC` somewhere.
https://github.com/zeek/zeek/issues/2330

**Comment by timwoj** [comment]
I revived #2330 since it describes the error. aarch64 builds for Debian 12 are working on now, but Debian 11 builds are failing still. I'm closing this issue in favor of the other one.
