### ISSUE TITLE
Zeek source code build.

### ISSUE THREAD

**Issue by coltonfreeman26** [zeek/zeek#3311]
Good day all,
I am trying to build the latest Zeek releases 6.0.1 from source in a docker image and the end results vary from an 18gb docker image to a 5.5gb docker image. We are building off of a python-3.11 image which is in turn built off of RHEL's UBI-9 image. I have built it as expected (according to the docs) and that was nearly 10gb and then after removing all extra dependencies and disabling every possible configuration option on top of a multi stage build the image is still 5.5gb. Is this expected when building from source? 
Please let me know if you need any more information on this. I can also share the Dockerfile if that would help. Mostly just trying to see if this is pretty typical or not. I do see that your image on Docker Hub is right about .5gb so I am guessing I am doing something wrong. 
PS. The /usr/local/zeek directory is huge, so might be some things from there I can pull out. I have never used Zeek before so I am not familiar with how it is supposed to function.

**Comment by bbannier** [comment]
We do not really do support in Github issues, and a better place for such discussions is usually our [Discord](https://community.zeek.org/) or [Slack](https://zeekorg.slack.com/signup#/domain-signup).

> I have built it as expected (according to the docs) and that was nearly 10gb and then after removing all extra dependencies and disabling every possible configuration option on top of a multi stage build the image is still 5.5gb. Is this expected when building from source?

No, this is not expected. We [publish Docker images] and the image for zeek-6.0.1 is ~580MB (~170MB compressed). I suggest to either start with that image and add modifications on top, or look into [our setup](https://github.com/zeek/zeek/tree/master/docker) for inspiration.
