### ISSUE TITLE
Registering Spicy analyzer with ports in EVT not equivalent to using Zeek `Analyzer::register_for_ports`

### ISSUE THREAD

**Issue by bbannier** [zeek/zeek#3318]
One can specify ports for a Spicy analyzer in an EVT file, or alternatively register the analyzer in a Zeek script with `Analyzer::register_for_ports`. Both these approaches should be identical.

While testing for #3305 I noticed that this was not the case, namely `notice.log` was different. This was due to `ProtocolDetector` using `Analyzer::registered_ports` which uses state [updated by `Analyzer::register_port`](https://github.com/zeek/zeek/blob/0b940d8b3ce8ebb5539b99b8eea460fd6eac3cdc/scripts/base/frameworks/analyzer/main.zeek#L226) but not updated by the [code for registering ports from EVT files](https://github.com/zeek/zeek/blob/0b940d8b3ce8ebb5539b99b8eea460fd6eac3cdc/src/spicy/manager.cc#L694).

We should make their behavior identical.

**Comment by awelzel** [comment]
My thoughts are to either deprecate `port` within `.evt` files, update the package template to render the boiler-plate and move on.

The alternative could be for the spicy integration to up-call into Zeek script land and run `Analyzer::register_for_ports` - that'd probably be better than modifying the underlying tables directly.

**Comment by 0xxon** [comment]
FWIW - I think that deprecating `port` in `evt` files is the right way to do this.

**Comment by bbannier** [comment]
> FWIW - I think that deprecating `port` in `evt` files is the right way to do this.

We are on it with #3442 ;)

**Comment by awelzel** [comment]
I'm closing this. `ports` support in `.evt` has been deprecated for Zeek 7.0 and Tim is in the process of ripping out support for 7.1 :-)
