### ISSUE TITLE
Unintuitive `get_current_packet*()` behavior

### ISSUE THREAD

**Issue by J-Gras** [zeek/zeek#3330]
The behavior of `get_current_packet()` and `get_current_packet_header()` seems rather unintuitive wrt. event recursion. Descending into recursion access to the current packet gets lost. Once descending deep enough, the event will be scheduled with the next iteration of the run loop causing the `get_current_packet*()` calls to provide the next packet. Below a btest based on [testing/btest/language/event-ts.zeek](https://github.com/zeek/zeek/blob/5ff24dad234f90dcae0d89a2b8bcc6b19f41f4b5/testing/btest/language/event-ts.zeek).

```zeek
# @TEST-EXEC: zeek -b -r $TRACES/ticks-dns.pcap %INPUT > out
# @TEST-EXEC: btest-diff out

# Note: We use a PCAP with DNS queries only so that we have a single packet per
# time step. Thus the run loop will be executed only once per time step.

global runs = -1;

event test(depth: count)
	{
	if ( depth == 0 )
		return;

	local hdr = get_current_packet_header();
	local ip_hdr = hdr?$ip ? cat(hdr$ip) : "[]";
	print fmt("[%D] Test %s current IP header %s", network_time(), depth, ip_hdr);
	event test(--depth);
	}

event new_connection(c: connection)
	{
	print fmt(">> Run %s (%D):", ++runs, network_time());
	# Descend into recursion to enqueue events until we add an event that will
	# be handled in the next run loop iteration, i.e. processing a different
	# packet than as it was enqueued. Use four levels of recursion as every
	# drain of the event queue handles two layers and the event queue is
	# drained two times. First after processing a packet and second in the run
	# loop.
	event test(4);
	}
```

Not sure it's worth keeping the packet around (i.e., delay calling `DoneWithPacket`) for the first descends. However, some hint/warning in the docs seems helpful.

**Comment by awelzel** [comment]
> Not sure it's worth keeping the packet around (i.e., delay calling DoneWithPacket) for the first descends. However, some hint/warning in the docs seems helpful.

I've opened a PR with a few sentences that `get_current_packet()`) is a very sharp knife. The test case would fall under "undefined" behavior. If one needs to keep a certain packet (and they are sure they actually have the right packet), it can be passed as argument.

In addition to our discussion around IP defrag and tcp-reassembly, the fact that the packet payload isn't de-capsulated further widens the disconnects with relation to protocol specific events.
