### ISSUE TITLE
GRE-over-UDP support

### ISSUE THREAD

**Issue by ckreibich** [zeek/zeek#3344]
[RFC 8086](https://www.rfc-editor.org/rfc/rfc8086) defines GRE over UDP, for which we've received [a request](https://zeekorg.slack.com/archives/CSZBXF6TH/p1695944452273349). This is basically just
```
const gre_ports = { 4754/udp } &redef;
PacketAnalyzer::register_for_ports(PacketAnalyzer::ANALYZER_UDP, PacketAnalyzer::ANALYZER_GRE, gre_ports);
```
plus a test case, unless I'm overlooking something @timwoj?

I'm attaching a quick synthetic [pcap](https://github.com/zeek/zeek/files/12755047/gre-over-udp.zip) with a single Eth/IP/UDP/GRE/IP/UDP packet, for testing.

If anyone reading this has a real example they could share, that'd be great.

The RFC also mentions encapsulation in DTLS (port 4755) — not sure we can do much with that but perhaps we can note down the protocol association somehow. @0xxon might know more.

@JustinAzoff, fyi.

**Comment by timwoj** [comment]
> plus a test case, unless I'm overlooking something @timwoj?

That sounds correct to me.
