### ISSUE TITLE
Save live traffic to pcap files

### ISSUE THREAD

**Issue by zliucd** [zeek/zeek#3358]
Hi,

Does Zeek support writing pcaps from live traffic?  Further, I would like to store each TCP connection as a standalone pcap file.
If Zeek does not support file writing, can I write plugins?

There are a few options, e.g., ```-c, -w``` in Zeek command line(version 5.2.2), but they didn't work of writing pcaps,
```zeek -w test.pcap```

Thanks.

**Comment by timwoj** [comment]
> There are a few options, e.g., `-c, -w` in Zeek command line(version 5.2.2), but they didn't work of writing pcaps,
`zeek -w test.pcap`

`-w` should support writing pcaps, but as you wrote it there you're not actually listening for traffic. I ran `./src/zeek -i en0 -w file.pcap` on my local machine and it captured live traffic from my wifi into a pcap file. 

> Further, I would like to store each TCP connection as a standalone pcap file.

This isn't supported currently. The default packet writer is global, in that it writes all packets into a single file. It should be possible to write a plugin for a packet dumper that does specific things with packets, but I don't believe anyone has actually done it before. The built-in dumper is technically a plugin, so you can look at that for guidance. It's in `src/iosource/pcap/Dumper.{h,cc}`.

**Comment by timwoj** [comment]
The comment above notwithstanding, this issue is more of a support question. We tend to reserve Github issues for problems with the code itself. If you have further questions, our Discourse and Slack servers are better avenues for those.
