### ISSUE TITLE
Zeek renaming: environment variables

### ISSUE THREAD

**Issue by jsiwek** [zeek/zeek#339]
For any BRO-prefixed environment variables we use (get a list from `--help` output and/or grepping `getenv` usages), need to accept/prefer a ZEEK-prefixed version.

**Comment by dnthayer** [comment]
Zeek uses these: `BROPATH`, `BRO_PLUGIN_PATH`, `BRO_PLUGIN_ACTIVATE`,
`BRO_PREFIXES`, `BRO_DNS_FAKE`, `BRO_SEED_FILE`, `BRO_LOG_SUFFIX`,
`BRO_PROFILER_FILE`, `BRO_DISABLE_BROXYGEN`, `BRO_DEFAULT_CONNECT_RETRY`,
`BRO_BROKER_MAX_THREADS`, `BRO_DEFAULT_LISTEN_ADDRESS`,
`BRO_DEFAULT_LISTEN_RETRY`.
The zeek-cut tool uses `BRO_CUT_TIMEFMT`.

**Comment by dnthayer** [comment]
Branch "topic/dnthayer/gh-339" in the zeek, zeek-aux, zeek-docs, and zeekctl git repos
contains the changes needed to rename all BRO-prefixed env. vars.

**Comment by jsiwek** [comment]
Fixed via #374 (thanks, Daniel).

Also added a centralized getenv wrapper function in case we ever want to emit deprecation warnings for use of the old env. vars.
