### ISSUE TITLE
Matching sets of regular expressions

### ISSUE THREAD

**Issue by ckreibich** [zeek/zeek#3402]
### Discussed in https://github.com/zeek/zeek/discussions/3326

<div type='discussions-op-text'>

<sup>Originally posted by **vpax** September 22, 2023</sup>
@JustinAzoff and I were discussing how we could significantly speed up some of our code that currently loops through sets of `pattern`s if Zeek could tell us _which_ pattern(s) were matched.  For example, it would be neat if code like this:
```
global a: table[pattern] of count;

a[/foo/] = 3;
a[/bar/] = 7;
a[/(foo|bletch)/] = 9;

print a["x"], a["foo"], a["bar"], a["bletch"];
```
would print
```
[], [3, 9], [7], [9]
```
My recollection was that Zeek in fact has this information internally but it gets lost in the layering used for matching `pattern`s. I took a look in the internals and sure enough that's the case, and in fact this is leveraged by the signature framework to tell which of several signatures have matched.

I took a quick stab at prototyping and got the above example to work with < 150 lines of new code (`topic/vern/pattern-tables-work`).  Assuming that given its feasibility, there's interest in developing this further (which I'd hope, as it really is helpful in some situations!), several questions come to mind:

- is `table[pattern] of X` the right way to expose this feature to users? It's certainly convenient for some cases.
- should the match be _exact_, _anywhere_, or user-selectable (maybe via some syntax)? My prototype implements _exact_, which seems best as one can always add `.*` on either side to make a pattern _anywhere_.
- are we okay with not supporting `/.../i` or `/.../s` distinctions? (The prototype just loses these.) It would not be hard to make them apply to _all_ patterns, but due to the way the implementation works they would be difficult to support for only some of the patterns but not others. Un-pretty.

BTW I'm perfectly happy for someone else to pick up the prototype and build out the rest - just would like to see some functionality along these lines available sometime soon!</div>

**Comment by vpax** [comment]
I've assigned this to myself, as I've started refining my prototype and should have a PR for it fairly soon
