### ISSUE TITLE
Spicy ignores Zeek-side FUID generation

### ISSUE THREAD

**Issue by 0xxon** [zeek/zeek#3440]
Spicy currently does not call the Zeek script-side code that can be used for file uid generation; specifically it seems to ignore the functions that are set in `Files::register_protocol`. The Zeek C++-side functionality that should be called somewhere is `file_mgr->GetFileID`. This steps is currently completely skipped, instead Spicy generates its own IDs in `rt::cookie::FileStateStack::push()` - https://github.com/zeek/zeek/blob/9b1f3b58386c110302747d2f49d5a0bcfb334bd4/src/spicy/runtime-support.cc#L684-L689

In slightly different, but related things - it is somewhat common for binpac parsers to generate their own file-IDs and pass these to the files framework. This is currently also not possible in Spicy.

**Comment by rsmmr** [comment]
> specifically it seems to ignore the functions that are set in Files::register_protocol

This is now implemented by #3703.

> it is somewhat common for binpac parsers to generate their own file-IDs and pass these to the files framework. This is currently also not possible in Spicy.

Is this the protocol or the file parser generating the ID? The former is possible already: https://docs.zeek.org/en/master/devel/spicy/reference.html#spicy-file-begin. If the latter, can you point me to an example?

**Comment by 0xxon** [comment]
> > it is somewhat common for binpac parsers to generate their own file-IDs and pass these to the files framework. This is currently also not possible in Spicy.
> 
> Is this the protocol or the file parser generating the ID? The former is possible already: https://docs.zeek.org/en/master/devel/spicy/reference.html#spicy-file-begin. If the latter, can you point me to an example?

This comment was added before that functionality was added to Spicy - I am using exactly that in the TLS analyzer  :).
