### ISSUE TITLE
Add DNSSEC signature algorithms Ed25519 & Ed448

### ISSUE THREAD

**Issue by dwhitemv25** [zeek/zeek#3453]
As per [RFC 8080](https://www.rfc-editor.org/rfc/rfc8080.html) and the IANA [DNS Security Algorithm Numbers](https://www.iana.org/assignments/dns-sec-alg-numbers/dns-sec-alg-numbers.xhtml) registry, DNSSEC signature algorithm numbers 15 and 16 are now defined for Ed25519 and Ed448, respectively.

Please add these signature numbers to the DNS protocol analyzer so they are not logged as unknown in weird.log.

**Comment by awelzel** [comment]
Thanks @dwhitemv25 , any chance you have a pcap that we could add to our corpus for testing?

**Comment by awelzel** [comment]
> Hm, I don't have the equipment to generate an anonymized pcap to test signature numbers. I just saw the weird.log entries, then checked the source to verify they weren't listed.
> 
> The ideal setup would be 2 machines and a hierarchy of subdomains of example.com, each signed with a different algorithm.

Turns out ed448.no and ed25519.no provide that :-)
