### ISSUE TITLE
`split_string_n` returns incorrect match if pattern includes `^`

### ISSUE THREAD

**Issue by bbannier** [zeek/zeek#3455]
I would expect exactly one element for `split_string_n("test", /^est/, T, 1)` since the pattern does not match the input. Instead Zeek returns `[t, est, ]`.

This got reported by a user out of band since they saw unexpected results for `match_pattern("test", /^est/)` (expectation: no match, behavior: match found).

**Comment by awelzel** [comment]
Hmm, hmm, I can see how a split pattern with anchors might not happen a lot, but the resulting `match_pattern()` behavior is clearly sad. I have a patch idea, but it's more involved than I was hoping for, but hey...

We have the same behavior with `sub()`, too. That's a different code path and actually rather irritating.
```
# zeek -e 'print sub("testme", /^est/, "meh")'
tmehme

zeek -e 'print gsub("testme testme", /^est/, "meh")'
tmehme tmehme
```
