### ISSUE TITLE
Enabling the broctl fails on Alpine based docker image

### ISSUE THREAD

**Issue by blacktop** [zeek/zeek#347]
It appears that broctl fails on Alpine?  Is it because I do not have python installed?

I apologize for my ignorance as I never use broctl, but I do know that is how people use it in prod.

REF: https://github.com/blacktop/docker-zeek/issues/3

Thanks!

**Comment by blacktop** [comment]
ping @lbpan

**Comment by jsiwek** [comment]
BroControl does require Python, so if that's not available, I'd expect that to be a major problem.

I did do some misc. improvements to support Alpine November and recall things may have generally been in a working state then:

* https://github.com/zeek/broctl/issues/10
* https://github.com/zeek/zeek/issues/216

**Comment by blacktop** [comment]
Thank you for the quick response!

I apologize for asking a somewhat unrelated question in the issue, but I noticed the compiled Bro size used to be on the order of 20MBs, but the new version 2.6/Zeek is a whoppin' 170MB.

It looks like most of the size is coming from the CAF and Broker libs.  Is there a way to shrink them? 

I assume this is the NEW hotness and user will want them, was just wondering.

Again, thank you! 👍

**Comment by jsiwek** [comment]
`./configure --build-type=<type>` would be the first thing I'd look at to to compare sizes.  Default is `RelWithDebInfo` which includes debug symbols, so you can see if `Release` is better, or even `MinSizeRel` to enable further compiler optimizations to reduce size.

**Comment by blacktop** [comment]
It shrank down to 40MBs using `MinSizeRel` !!!! 🎉 Many thanks for all your help today! 👍
