### ISSUE TITLE
can't find policy/protocols/ssl/extract-certs-pem

### ISSUE THREAD

**Issue by cchansk** [zeek/zeek#3517]
After I recently updated zeek-lts to 6.0.2 and zeekctl-lts to 2.5.0-24, when I try to deploy from zeekctl, I keep getting

fatal error in /opt/zeek/spool/installed-scripts-do-not-touch/site/local.zeek, line 118: can't find policy/protocols/ssl/extract-certs-pem

The files are definitely missing and I haven't been able to get anything to start, but I'm not quite sure if this is a self-inflicted problem.

**Comment by 0xxon** [comment]
Hi,

the `extract-certs.pem` script was deprecated in Zeek 4.1.0 (starting to raise deprecation warnings) and was removed later following our deprecation policies. This is also documented in the NEWS file. A replacement script that offers similar functionality was added instead (`log-certs-base64.zeek`).

**Comment by cchansk** [comment]
Do you have any recommendations on how I might resolve these errors?

**Comment by cchansk** [comment]
Thanks... I was staring at it earlier and had a bit of a DUH moment and realized the same thing.
