### ISSUE TITLE
Overzealous HTTP SQL injection detection?

### ISSUE THREAD

**Issue by emillynge** [zeek/zeek#352]
Dear Maintainers.

I am seeing a lot of HTTP SQL injection notices generated in [detect-sqli.zeek](https://github.com/zeek/zeek/blob/aebcb1415d74ef71f90b7dfc651c3f6025b34647/scripts/policy/protocols/http/detect-sqli.zeek), which are clearly not actual SQL injection attempts.

The endpoint has the form `my.server.com/api/find?tag=hello&SELECT0=true`

I am guessing the regex is actually looking for requests along the lines of 
`my.server.com/api/find?tag=hello;SELECT0=true` where `;` is used to terminate an SQL statement and subsequently execute `SELECT 0` if the `tag` parameter is used in an SQL statement.

But in my case, `&` is being treated as an SQL statement termination even all http query parsers, would treat the `&` as a seperator between the `tag` and `SELECT0` parameter and thus cannot possibly be used for SQL injection.

Is the above analysis correct? 

In that case, maybe the regex can be rewritten such that the instances of `[[:blank:]\x00-\x37]` is replaced by `[[:blank:]\x00-\x25\x27-\x37]` in order to "whitelist" the ampersand character?

**Comment by jsiwek** [comment]
@emillynge thanks for pointing out the false positive.  Generally, you may find it useful to implement your own `HTTP::sqli_policy` hook to whitelist miss-detected URIs, but yes this is a case where it looks like the `\x00-\x37` range may be unintentionally capturing the `&` character.   More suspicious since it is also capturing it within the same regex group that looks like it's trying to match a `;` character.

Seems like an odd range overall: stopping at `\x37` which is '7', so I don't understand what it's trying to accomplish.

@sethhall do you remember anything about where these patterns come from?

Doing some archaeology, that weird range wasn't always there:

https://github.com/zeek/zeek/blob/68171cf179e05e35fe9b73fdf4157e0d71ffd5e9/policy/protocols/http/base/detect-sqli.bro#L30-L35

Seems to appear here first:

https://github.com/zeek/zeek/blob/597a4d6704b3d22004c160c52541aeaf44001a93/scripts/policy/protocols/http/detect-sqli.bro#L27-L33

**Comment by sethhall** [comment]
Those patterns came from my work at OSU and there have unfortunately 
always been false positives. There is a test suite for those patterns 
too that would be good to fill out more...
	https://github.com/zeek/zeek/blob/a994be9eebd80cd7fbeaa62f2eba1a045b269b3f/testing/btest/scripts/policy/protocols/http/test-sql-injection-regex.zeek

You can see in that test file that there are already some URLs that I 
couldn't get it to work with correctly.

**Comment by philrz** [comment]
I'm a bit of a Zeek newbie and was looking into some of my first logs and happened to also see some false positives, so I found this open issue. In our case, we often use Grafana to visualize metrics from an InfluxDB backend. When one of our engineers is doing lots of Grafana work in their browser, it seems that the flurry of SQL-like InfluxQL queries as logged in in the `URI` field of `http` events is enough to make the `notice` event fire, as I see the `http` events all having `HTTP::URI_SQLI` marked in their `tags` field. Here's a couple examples of `URI` values from such events:

```
/api/datasources/proxy/1/query?db=telegraf&q=SELECT sum("gauge") FROM "boomd_indexer_memory_index_bytes_total" WHERE ("space" =~ /^(corelight|wrccdc)$/) AND time >= 1561410802000ms and time <= 1561416568000ms GROUP BY time(1s)&epoch=ms

/api/datasources/proxy/1/query?db=telegraf&q=SELECT mean("0.5") AS "0.5", mean("0.9") AS "0.9", mean("0.99") AS "0.99" FROM "boomd_indexer_write_size_bytes" WHERE ("type" = 'key' AND "space" =~ /^(corelight|wrccdc)$/) AND time >= 1561410802000ms and time <= 1561416568000ms GROUP BY time(1s);SELECT derivative(sum("sum"), 1s) FROM "boomd_indexer_write_size_bytes" WHERE ("type" = 'key' AND "space" =~ /^(corelight|wrccdc)$/) AND time >= 1561410802000ms and time <= 1561416568000ms GROUP BY time(1s)&epoch=ms

/api/datasources/proxy/1/query?db=telegraf&q=SELECT derivative(sum("counter"), 1s) FROM "boomd_indexer_slabs_processed_total" WHERE ("space" =~ /^(corelight|wrccdc)$/) AND time >= 1561410802000ms and time <= 1561416568000ms GROUP BY time(1s)&epoch=ms
```

I confess that my regexp skills are not quite at a level where I can eyeball the Zeek script and say precisely why it's firing and what needs to change, but if this issue inspires anyone to further refine the logic to reduce false positives, I figured I'd put some more fuel on the fire. Thanks!

**Comment by grigorescu** [comment]
> Seems like an odd range overall: stopping at `\x37` which is '7', so I don't understand what it's trying to accomplish.

I have a theory... 00 - 37 octal are the ASCII control characters (excluding DEL @127). I'm betting that the intent was to exclude those control characters, but hex was used instead.
