### ISSUE TITLE
Add case-insensitive pattern matching to signature framework

### ISSUE THREAD

**Issue by epeterso** [zeek/zeek#353]
Bro 2.6 added a case-insensitive option for patterns using `/<pattern>/i`. However, it is not supported for patterns used under the signature framework for content conditions like `payload /<regex>/i`. Adding this option to the signature framework pattern would be very helpful as well.  

Error Produced (Bro 2.6.1):
`error: Error in signature (/opt/bro/share/bro/site/signatures/test.sig:2): syntax error`

**Comment by jsiwek** [comment]
Does `payload /(?i:<regex>)/` work for you in the meantime ?  AFAICT, the `/<regex>/i` syntax just converts to the former for script-layer patterns, so we'd just do the same for signatures, but either way achieves the same goal of case-insensitivity.
