### ISSUE TITLE
@if directives don't work in record definitions

### ISSUE THREAD

**Issue by vpax** [zeek/zeek#3531]
The following generates a syntax error:
```
type r: record {
	a: count;
@if ( ! Version::at_least("6.1.0") )
	b: double;
@endif
};
```
This is unfortunate as I'm trying to update a script to work with two different versions of Zeek. (This is in the context of the change to `files.log` removing some record fields.) The problem is quite akin to #2075 which required a parser tweak to support.

Also, AFAICT the documentation doesn't indicate any restrictions on where `@if`s can appear ...

**Comment by JustinAzoff** [comment]
Probably not ideal, but does this work for now?

```
@if ( ! Version::at_least("6.1.0") )
type r: record {
	a: count;
	b: double;
};
@else 
type r: record {
	a: count;
};
@endif
```

**Comment by vpax** [comment]
Yeah that's what I'm doing ... but it's a record with a dozen+ fields and a bunch of comments, so it's ug-ly.

(Also, amusingly, some of those comments talk about `@if`s in another context - and wrapping them in a _live_ `@if` then gets the scanner confused as to `@if` nesting depth ... so I have to add faux `@endif`s to pair with them :-P)
