### ISSUE TITLE
ERROR STARTING BRO

### ISSUE THREAD

**Issue by throro** [zeek/zeek#355]
[BroControl] > diag
[bro]

No core file found and gdb is not installed.  It is recommended to
install gdb so that BroControl can output a backtrace if Bro crashes.

Bro 2.6-264
Linux 5.0.0-13-generic

Bro plugins: (none found)

==== No reporter.log

==== stderr.log
fatal error: problem with interface eth0 (pcap_error: SIOCGIFHWADDR: No such devi                                ce (pcap_activate))

==== stdout.log
max memory size         (kbytes, -m) unlimited
data seg size           (kbytes, -d) unlimited
virtual memory          (kbytes, -v) unlimited
core file size          (blocks, -c) unlimited

==== .cmdline
-i eth0 -U .status -p broctl -p broctl-live -p standalone -p local -p bro local.z                                eek broctl broctl/standalone broctl/auto

==== .env_vars
PATH=/usr/local/bro/bin:/usr/local/bro/share/broctl/scripts:/usr/local/sbin:/usr/                                local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/bi                                n:/usr/local/bro/bin
BROPATH=/usr/local/bro/spool/installed-scripts-do-not-touch/site::/usr/local/bro/                                spool/installed-scripts-do-not-touch/auto:/usr/local/bro/share/bro:/usr/local/bro                                /share/bro/policy:/usr/local/bro/share/bro/site
CLUSTER_NODE=

==== .status
TERMINATED [atexit]

==== No prof.log

==== No packet_filter.log

==== No loaded_scripts.log

[BroControl] >

**Comment by jsiwek** [comment]
> fatal error: problem with interface eth0 (pcap_error: SIOCGIFHWADDR: No such devi ce (pcap_activate))

That's the relevant error message -- be sure to set an appropriate interface in your `/usr/local/bro/etc/node.cfg` file.
