### ISSUE TITLE
Spicy: Rename `replaces` to `disables`

### ISSUE THREAD

**Issue by J-Gras** [zeek/zeek#3569]
Given that  `replaces` only disables an existing analyzer and does not provide any additional functionality, we should consider renaming it to `disables` (see https://docs.zeek.org/en/master/devel/spicy/reference.html#analyzer-setup). In case of nested analyzers, the name `replaces` kind of suggests that analyzers that forwarded into the "replaced" analyzer will now forward into the "replacing" analyzer, which is not the case.

**Comment by bbannier** [comment]
@rsmmr do you have context on this? Did we have more in mind, or was the pretty wide naming more accidental?

**Comment by rsmmr** [comment]
There's one additional piece: using `replace` also lets the Spicy analyzer take over the script-side tag for the existing analyzer, so that the new analyzer gets activated just like the old one. In that sense, it's not just disabling the old one, it's taking its role.

**Comment by J-Gras** [comment]
Oh, that's probably where my confusion comes from. While this works in script-land, calls to `InstantiateAnalyzer` in C++ will not pick up the new analyzer, for example:
https://github.com/zeek/zeek/blob/13fde341d25302f46901693a05d191591781c6ea/src/analyzer/protocol/smtp/SMTP.cc#L388
In my case, I had to use the new analyzer name in the instantiate call.

**Comment by rsmmr** [comment]
Yeah, iirc, that's purely script-side now. We could see if we can adapt C++-land as well. Generally, I believe this is worth keeping though.

**Comment by J-Gras** [comment]
Closing this in favor of #3573.
