### ISSUE TITLE
Spicy: Make `replaces` cover calls to `InstantiateAnalyzer`

### ISSUE THREAD

**Issue by J-Gras** [zeek/zeek#3573]
While this works in script-land, calls to `InstantiateAnalyzer` in C++ will not pick up the new [replaced] analyzer, for example:
https://github.com/zeek/zeek/blob/13fde341d25302f46901693a05d191591781c6ea/src/analyzer/protocol/smtp/SMTP.cc#L388
In my case, I had to use the new analyzer name in the instantiate call.

_Originally posted by @J-Gras in https://github.com/zeek/zeek/issues/3569#issuecomment-1903578604_

**Comment by awelzel** [comment]
As mentioned in #3654, deprecating "port" / "ports" points out that ports registered though `Analyzer::register_for_ports()` are not respected when used together with `replaces`.

That's boiling down to InstantiateAnalyzer(), but tag based which may add a bit of a twist to this:
https://github.com/zeek/zeek/blob/a45489de90a78c2815d6589b03ddd398251f0001/src/packet_analysis/protocol/ip/IPBasedAnalyzer.cc#L177-L181

(and I'm tempted to open a PR to rename `port` and `ports` to *analyzer_tag* :-)
