### ISSUE TITLE
Zeek renaming: update broker's bro.hh

### ISSUE THREAD

**Issue by jsiwek** [zeek/zeek#359]
Didn't look closely for other Bro usages in Broker yet, but I noticed least `broker/bro.hh` and the `bro` namespace.

**Comment by dnthayer** [comment]
The broker-related bro-to-zeek renaming is in branch "topic/dnthayer/gh-359" in the zeek and broker repos.

**Comment by jsiwek** [comment]
Thanks for helping with this one, Daniel.
