### ISSUE TITLE
SMB: FILE_DELETE logged as FILE_OPEN

### ISSUE THREAD

**Issue by sq-gh** [zeek/zeek#3593]
## issue
macOS clients perform deletes in a way that causes them to be logged as SMB::FILE_OPEN and the delete action is missed

In #2276 there is a description of how some clients delete a file by doing:

> SMB/Create, then
> SMB/SetFile with SMB2_FILE_DISPOSITION_INFO set (delete on close), then
> SMB/Close

macOS looks to be using SMB/SetInfo to do this instead of SMB/SetFile. Another point of note, all three commands are sent in a single packet - I'm not sure if this matters to the smb2 protocol scripts or not. 

## pcap
this is truncated to just a couple packets but i'm happy to test in more detail
[macos-delete.pcap.tgz](https://github.com/zeek/zeek/files/14116684/macos-delete.pcap.tgz)

### clients
macOS Sonoma 14.3, SMB 3.1.1
macOS Ventura 13.6.4, SMB 3.1.1
### smb server 
Samba 4.15.13
### zeek
Zeek 6.1.1

**Comment by awelzel** [comment]
> Another point of note, all three commands are sent in a single packet - I'm not sure if this matters to the smb2 protocol scripts or not.

I stared quickly and this is the crux - the scripts are setup to deal with SMB/SetInfo properly, but the BinPac analyzer fails to parse multiple requests within the same packet /  NetBIOS PDU.

This has been confirmed by @mohan-dhawan, too.

Ouch :-(

![Screenshot from 2024-02-01 14-49-44](https://github.com/zeek/zeek/assets/2100509/7f5d268a-9c06-4d16-a7cb-372bd6310758)

**Comment by sq-gh** [comment]
> > Another point of note, all three commands are sent in a single packet - I'm not sure if this matters to the smb2 protocol scripts or not.
> 
> I stared quickly and this is the crux - the scripts are setup to deal with SMB/SetInfo properly, but the BinPac analyzer fails to parse multiple requests within the same packet / NetBIOS PDU.
> 
> This has been confirmed by @Mohan-Dhawan, too.
> 
> Ouch :-(
> 

Ah! I'm wondering if this issue should be in the binpac repo instead, then

**Comment by bbannier** [comment]
> Ah! I'm wondering if this issue should be in the binpac repo instead, then

This is good here, [Binpac](https://github.com/zeek/binpac) is the technology used to implement the parser, but the actual parser lives [here in this repo](https://github.com/zeek/zeek/tree/master/src/analyzer/protocol/smb).

**Comment by sq-gh** [comment]
awesome!
