### ISSUE TITLE
Error - using wrong interface

### ISSUE THREAD

**Issue by indianatoms** [zeek/zeek#361]
Hi, I am new to Zeek and i am trying to configure bro on my VM (Ubuntu) Virtualbox.
I have an issue which seems to be common, however solution that I have found while googling does not fix my problem.

Thats the error I obtain 
```
==== stderr.log
fatal error: problem with interface eth0 (eth0: SIOCETHTOOL(ETHTOOL_GET_TS_INFO) ioctl failed: No such device)
```

My ifconfig interface name is enp0s3 so I have changed the name in node.cfg.

```
node.cfg[bro] 
type=standalone
host=localhost
interface=enp0s3

```
When i use Bro as a Command-Line Utility everything works fine.

`bro -i enp0s3 -C `

Then I have deployed changes but it didnt fix the issue. Do you have any ideas, how i can fix it?

Here is the whole diag log:

```
[BroControl] > start
starting bro (was crashed) ...
bro terminated immediately after starting; check output with "diag"
[BroControl] > diag
[bro]

Bro 2.4.1
Linux 4.4.0-36-generic


==== No reporter.log

==== stderr.log
    fatal error: problem with interface eth0 (eth0: SIOCETHTOOL(ETHTOOL_GET_TS_INFO) ioctl failed: No such device)

==== stdout.log
max memory size         (kbytes, -m) unlimited
data seg size           (kbytes, -d) unlimited
virtual memory          (kbytes, -v) unlimited
core file size          (blocks, -c) unlimited

==== .cmdline
-i eth0 -U .status -p broctl -p broctl-live -p standalone -p local -p bro local.bro broctl broctl/standalone broctl/auto

==== .env_vars
PATH=/usr/bin:/usr/share/broctl/scripts:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
BROPATH=/var/spool/bro/installed-scripts-do-not-touch/site::/var/spool/bro/installed-scripts-do-not-touch/auto:/usr/share/bro:/usr/share/bro/policy:/usr/share/bro/site
CLUSTER_NODE=

==== .status
TERMINATED [atexit]

==== No prof.log

==== No packet_filter.log

==== No loaded_scripts.log

```

**Comment by jsiwek** [comment]
The `broctl deploy` command should pick up the changes and start the process, did you try using that instead of `broctl start` ?

I see it's also Bro 2.4.1, which is old and not supported anymore, so I also suggest using a newer version if possible.

**Comment by indianatoms** [comment]
I have updated to 2.5.3 , but unfortunately, I still cannot use broctl. I have tried to use deploy instead of a start command but it did not help.

**Comment by jsiwek** [comment]
The only explanations I can think are either not saving changes to the `node.cfg` or else there's a mismatch in which `node.cfg` file is being read.  Can you give the output of:

`which broctl`

and

`cat $(dirname $(which broctl))/../etc/node.cfg`

**Comment by indianatoms** [comment]
Here you go

```
tom@tom-VirtualBox:~$ which broctl
/usr/bin/broctl

```

```
root@tom-VirtualBox:/usr/bin# cat $(dirname $(which broctl))/../etc/node.cfg
cat: /usr/bin/../etc/node.cfg: No such file or directory

```

In addition here is the node.cfg that I have changed

```
root@tom-VirtualBox:/usr/local/bro/etc# ls
broctl.cfg  networks.cfg  node.cfg
root@tom-VirtualBox:/usr/local/bro/etc# cat node.cfg
# Example BroControl node configuration.
#
# This example has a standalone node ready to go except for possibly changing
# the sniffing interface.

# This is a complete standalone configuration.  Most likely you will
# only need to change the interface.
[bro]
type=standalone
host=localhost
interface=enp0s3


```

**Comment by jsiwek** [comment]
Do you have a `/usr/local/bro/bin/broctl` ?  If so, try using that.  I'm guessing `/usr/bin/broctl` is from the old installation/version, so it's not actually picking up the file you edited ?

**Comment by indianatoms** [comment]
Yes i have `/usr/local/bro/bin/broctl`

but when i run it, I obtain the same error. 


```
root@tom-VirtualBox:/usr/local/bro/bin# broctl

Welcome to BroControl 1.4

Type "help" for help.

[BroControl] > diag
[bro]

Bro
Linux 4.18.0-15-generic


==== No reporter.log

==== stderr.log
fatal error: problem with interface eth0 (pcap_error: SIOCGIFHWADDR: No such device (pcap_activate))

==== stdout.log
max memory size         (kbytes, -m) unlimited
data seg size           (kbytes, -d) unlimited
virtual memory          (kbytes, -v) unlimited
core file size          (blocks, -c) unlimited

==== .cmdline
-i eth0 -U .status -p broctl -p broctl-live -p standalone -p local -p bro local.bro broctl broctl/standalone broctl/auto

==== .env_vars
PATH=/usr/bin:/usr/share/broctl/scripts:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
BROPATH=/var/spool/bro/installed-scripts-do-not-touch/site::/var/spool/bro/installed-scripts-do-not-touch/auto:/usr/share/bro:/usr/share/bro/policy:/usr/share/bro/site
CLUSTER_NODE=

==== .status
TERMINATED [atexit]

==== No prof.log

==== No packet_filter.log

==== No loaded_scripts.log
```

**Comment by jsiwek** [comment]
> root@tom-VirtualBox:/usr/local/bro/bin# broctl
> 
> Welcome to BroControl 1.4

That doesn't look like it's actually running the version you expect.  Bro 2.5.3 should install BroControl 1.7, so something is still up with your PATH and/or install dirs.  Don't really know what to suggest other than trying to get that all straightened out -- maybe clean everything up, start from scratch, and make sure you've got only one Bro/BroControl version installed that you are using.

**Comment by jsiwek** [comment]
I'm going to close this since it was looking more like a system configuration / installation issue rather than a bug.  Let us know if you found otherwise.
