### ISSUE TITLE
lib64/ not getting deployed in a multi-node cluster

### ISSUE THREAD

**Issue by dopheide-esnet** [zeek/zeek#362]
With the current master, 'broctl deploy' apparently isn't copying over lib64 to the worker cluster nodes.  As a result, bro can't run.

**Comment by jsiwek** [comment]
Thanks for reporting that.  I pushed a patch, can you pull from `master` and try it out?

**Comment by dopheide-esnet** [comment]
Will do, it might not be right away though.  Our only multi-node cluster is production (I can probably change that...)

**Comment by dopheide-esnet** [comment]
This looks good, thanks Jon!
