### ISSUE TITLE
Mozilla CA list outdated

### ISSUE THREAD

**Issue by AmalieDue** [zeek/zeek#3620]
It seems like the Mozilla CA list (mozilla-ca-list.zeek) and the Google CT list (ct-list.zeek) are not up to date. They have not been updated in 10 months. Furthermore, it seems like the tools used to update the lists are not publicly available. @0xxon, can the lists be updated? And is it possible to get access to the tools used to update the lists, or do I need to write my own?  

Thanks!

**Comment by 0xxon** [comment]
Hi,

sorry - you are right, I forgot to do that for the current release. I will remedy this shortly - and we will put it onto the release checklist.

The tool that we use for conversion is publically available here: https://github.com/zeek/zeek-aux/blob/master/devel-tools/gen-mozilla-ca-list.rb

The current best way to use it is to download a recent release of NSS, and point it at the contained certdata.txt.

**Comment by 0xxon** [comment]
I updated the process description in https://github.com/zeek/zeek/wiki/Release-Process and added the generation of the files to the release checklist.
