### ISSUE TITLE
How to check if a folder exists

### ISSUE THREAD

**Issue by joscarras** [zeek/zeek#3633]
Hello, and thanks for this great tool.

We are using Files::add_analyzer and generating lots of files to analyze them at a later time.

To avoid FS issue we want to store the files in various folders. We have found the mkdir, however we are unable to find a documented function that we can use to check if a folder already exists so we can safely then use mkdir.

So here are a few questions.
1. Is there a way to make mkdir create folders recursively or any other util that does this in zeek? 
2. How can we check if a directory path already exists?

Thank you very much,

**Comment by awelzel** [comment]
> To avoid FS issue we want to store the files in various folders. We have found the mkdir, however we are unable to find a documented function that we can use to check if a folder already exists so we can safely then use mkdir.

`mkdir()` will silently accept directories that already exist (in contrast to Python's os.mkdir()), so you don't necessarily need to check.

We don't seem to have `is_dir()` or so. Maybe a `Filesystem::stat()` BiF could be useful. But then.. are you in a modern environment? Any chance you could offload this logic to Node.js and use [fs.stat()](https://nodejs.org/en/learn/manipulating-files/nodejs-file-stats) or `fs.statSync()`?


> Is there a way to make mkdir create folders recursively or any other util that does this in zeek?

The following might do, though only lightly tested.

```
function mkdir_p(path: string): bool {
        local parts = split_string(path, /\/+/);
        local cur: string = "";
        for ( idx, p in parts ) {
                if ( idx > 0 && |p| == 0 )
                        next;
                cur += (p + "/");
                if ( ! mkdir(cur) )  # error currently logged.
                        return F;
        }
        return T;
}
```
There's [fs.mkdirSync](https://nodejs.org/api/fs.html#fsmkdirsyncpath-options) with options `{recursive: true}` on the Node.js side, too.

---

I'm closing this for now. If you think `stat()` or `is_dir()` please open a new one as a feature request. Such questions are also a better fit for the [forum](https://community.zeek.org) or  [Slack](https://zeek.org/slack).

**Comment by joscarras** [comment]
Thanks you so much for your quick response and help!

I will gladly accept this and work with it!

Also I had totally miss the work on NodeJS and this was an amazing addition and for sure will greatly improve our experience!
