### ISSUE TITLE
Improve log filter predicates

### ISSUE THREAD

**Issue by ckreibich** [zeek/zeek#364]
In the logging framework streams and filters have nice APIs to create/update/remove them. Predicate functions in filters have no such API, and there are two main difficulties in using them in practice:

(1) It's tedious to write code that is aware of any already existing predicates on a filter. You basically have to check whether the filter has a predicate member, and if so, try to chain it to a new predicate. It's also easy to forget to do this, and in turn blow away an existing predicate.

(2) Predicate functions only receive the log record they decide on, and no other state. This makes it harder to write stateful predicates. (Others have already pointed out that closures would also be a nice way to handle this.)

So it would be nice to structure this more, for example by having a management API for predicates that properly supports multiple predicates and how to chain them. I also like the idea of a state pointer for the predicates themselves. (I believe we've recently also touched the possibility of optional function arguments / overloading function signatures.)

**Comment by ckreibich** [comment]
Returning to this one after long absence :-) — I think the shortcomings flagged above still apply, but there's one big difference: we now have closures at our disposal. IIRC, the above was one of the inspirations for their implementation, so I think it's time to apply them here. Thoughts?  Meanwhile I'm assigning this one to myself.

**Comment by JustinAzoff** [comment]
One thing that might also be nice if we could add log hooks in additions to log events.  A hook could be used to modify the log record or 'break' to prevent it from being logged.  I think this also solves a lot of the issues you mentioned with predicates.

**Comment by ckreibich** [comment]
I agree, it's a natural fit and would make it resemble our handling of notices. I believe the discussion we had about this in the past assumed working with the existing predicate function. I'll dig it up, it had some fun ideas. But if people are open to the idea of deprecating the existing predicates, I could see hooks replacing them altogether.

**Comment by rsmmr** [comment]
yeah, hooks seems the right way here. Iirc, we wanted to stick to predicates previously only because of maintaining  backwards compability. I would say it's worth moving forward at this point tand switch to hooks as the more appropiatel mechanism.

Pinging @sethhall, any thoughts?

**Comment by J-Gras** [comment]
I really like that idea! This is how I have been dealing with predicates since there have been closures: https://github.com/J-Gras/add-json/blob/master/scripts/add-json.zeek#L29 It is possible but as @JustinAzoff said, hooks could simplify this a lot.
