### ISSUE TITLE
MySQL Analyzer: Log handshake metadata

### ISSUE THREAD

**Issue by safest-place** [zeek/zeek#3667]
Hello zeek team, there is a requirement that I need to detect mysql weak password in network traffic.
And I checked zeek mysql analyzer source code (https://github.com/zeek/zeek/blob/master/src/analyzer/protocol/mysql/mysql-protocol.pac).
It looks that zeek already parse the handshake metadata, example:
    Handshake_v10->auth_plugin_data_part_1
    Handshake_v10->auth_plugin_name
    Handshake_Credentials_v10->username
    Handshake_Credentials_v10->password
Can you log this handshake metadata in mysql.log ? Or zeek can log handshake metadata but disabled by default ? (How to enable it ?)

**Comment by 0xxon** [comment]
Hi,

We don't use GitHub issues for support questions. Questions like this are best answered using on either slack or our forum, which is both are frequented by Zeek developers and professional users. You can join here:

Forum: https://community.zeek.org/

Slack: https://zeek.org/community/

 Johanna
