### ISSUE TITLE
Wildcard Notice::lookup_location_types?

### ISSUE THREAD

**Issue by philrz** [zeek/zeek#3674]
I’ve been trying to populate the `remote_location` in Zeek's `notice` logs, as a [Zui](https://zui.brimdata.io/) user inquired about this via https://github.com/brimdata/build-zeek/issues/10 and I'd hoped it could be an easy change in the `local.zeek`. What I've found via testing though is that it appears the `Notice::lookup_location_types` being defaulted to `{}` seems to have the effect that Zeek never attempts to populate `remote_location` unless I enumerate all the notice types, i.e., it behaves like a whitelist that starts out empty. Maybe this is a novice Zeek scripting question, but is there some way to set this to a wildcard-like value such that Zeek would attempt to populate `remote_location` for _all_ notice types? If not, might there be interest in adding such a thing? Without it, if a user wanted to see this detail for whatever notice-generating IPs have geolocation data available, the whitelist would need to be very long and updated each time a new type of notice is added.

---

I tested this out by installing the [binary package for Zeek v6.2.0](https://build.opensuse.org/project/show/security:zeek) on Ubuntu Linux 20.04. The only changes I initially made from the defaults were to install the [geoip-conn](https://github.com/brimdata/geoip-conn) package (which provides a minimal geolocation database) and uncommented `@load packages` in my `local.zeek` so it would be active. At this point, running Zeek against the test data [repro2.pcap.gz](https://github.com/zeek/zeek/files/14858901/repro2.pcap.gz), we can see geolocation data for some `conn` and `ssh` events, but none of the `notice` events.

```
# zeek --version
zeek version 6.2.0

# zeek -C -r repro2.pcap local

# zq -Z 'cut geo.resp | head 1' conn.log 
{
    geo: {
        resp: {
            country_code: "SE",
            region: "AB",
            city: "Liljeholmen",
            latitude: 59.3199,
            longitude: 18.0123
        }
    }
}

# zq -Z 'cut remote_location | head 1'
 ssh.log 
{
    remote_location: {
        country_code: "CN",
        region: null (string),
        city: null (string),
        latitude: 34.7732,
        longitude: 113.722
    }
}

# zq -Z 'cut remote_location' notice.l
og
{
    remote_location: {
        country_code: null (string),
        region: null (string),
        city: null (string),
        latitude: null (float64),
        longitude: null (float64)
    }
}
{
    remote_location: {
        country_code: null (string),
        region: null (string),
        city: null (string),
        latitude: null (float64),
        longitude: null (float64)
    }
}
{
    remote_location: {
        country_code: null (string),
        region: null (string),
        city: null (string),
        latitude: null (float64),
        longitude: null (float64)
    }
}
```

However, if I re-process the pcap after adding this line to my `local.zeek`:

```
redef Notice::lookup_location_types += {SSL::Invalid_Server_Cert};
```

Now I can see `remote_location` data for the related `notice` event.

```
# zq -Z 'cut remote_location' notice.log
...
{
    remote_location: {
        country_code: "SE",
        region: "AB",
        city: "Liljeholmen",
        latitude: 59.3199,
        longitude: 18.0123
    }
}
...
```

**Comment by JustinAzoff** [comment]
The script that implements that is fairly small: https://github.com/zeek/zeek/blob/master/scripts/base/frameworks/notice/actions/add-geodata.zeek

based on how it works you could do something like

```
hook policy(n: Notice::Info) &priority=10
	{
	add n$actions[ACTION_ADD_GEODATA];
	}
```

and that should trigger the lookup for all notices

**Comment by philrz** [comment]
Thanks @JustinAzoff. Can you suggest a way it might be possible to make that config change by just modifying the `local.zeek`? It did cross my mind that I could modify the script like that but part of why I opened an issue is because I wanted to avoid shipping with a hacked base script if possible.

**Comment by JustinAzoff** [comment]
Hi,

I meant that for local.zeek, just forgot that you need to stick `Notice::` in front of the hook and action type.

```
hook Notice::policy(n: Notice::Info) &priority=10
	{
	add n$actions[Notice::ACTION_ADD_GEODATA];
	}
```

You can also do

```
module Notice;
hook policy(n: Notice::Info) &priority=10
	{
	add n$actions[ACTION_ADD_GEODATA];
	}
```

but probably wouldn't recommend that unless you already were doing a ton of notice related tweaks, at which point you could put them in a file named like `local-notice.zeek` and load that from `local.zeek`.

**Comment by philrz** [comment]
Thanks @JustinAzoff! That leading `Notice::` definitely made the difference. As predicted, it was a novice Zeek scripting problem on my part all along. 😉  I'll close the door on my way out.
