### ISSUE TITLE
There is a problem with the integration of zeek and metron-bro-plugin-kafka

### ISSUE THREAD

**Issue by shuaidonga** [zeek/zeek#369]
Start with broctl after installing metron-bro-plugin-kafka
The following error occurred：

[logger]

No core file found.

Bro 2.6-195
Linux 3.10.0-862.el7.x86_64

Bro plugins:
Apache::Kafka - Writes logs to Kafka (dynamic, version 0.3.0)

==== reporter.log

==== stderr.log
fatal error: errors occurred while initializing

==== stdout.log
max memory size         (kbytes, -m) unlimited
data seg size           (kbytes, -d) unlimited
virtual memory          (kbytes, -v) unlimited
core file size          (blocks, -c) unlimited

==== .cmdline
-U .status -p broctl -p broctl-live -p local -p logger local.bro broctl base/frameworks/cluster broctl/auto

==== .env_vars
PATH=/usr/local/bro/bin:/usr/local/bro/share/broctl/scripts:/usr/local/bro/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin:/root/bin
BROPATH=/usr/local/bro/spool/installed-scripts-do-not-touch/site::/usr/local/bro/spool/installed-scripts-do-not-touch/auto:/usr/local/bro/share/bro:/usr/local/bro/share/bro/policy:/usr/local/bro/share/bro/site
CLUSTER_NODE=logger

==== .status
TERMINATED [atexit]

==== No prof.log

==== No packet_filter.log

==== loaded_scripts.log

[manager]

Bro 2.6-195
Linux 3.10.0-862.el7.x86_64

Bro plugins:
Apache::Kafka - Writes logs to Kafka (dynamic, version 0.3.0)

==== No reporter.log

==== No stderr.log

==== No stdout.log

==== No .cmdline

==== No .env_vars

==== No .status

==== No prof.log

==== No packet_filter.log

==== No loaded_scripts.log

[proxy-1]

Bro 2.6-195
Linux 3.10.0-862.el7.x86_64

Bro plugins:
Apache::Kafka - Writes logs to Kafka (dynamic, version 0.3.0)

==== No reporter.log

==== No stderr.log

==== No stdout.log

==== No .cmdline

==== No .env_vars

==== No .status

==== No prof.log

==== No packet_filter.log

==== No loaded_scripts.log

[worker-1-1]

Bro 2.6-195
Linux 3.10.0-862.el7.x86_64

**Comment by jsiwek** [comment]
The `master` branch should give better error messages now, else the easiest way to get the real error messages may be to temporarily edit:
```
/usr/local/bro/share/bro/broctl/main.bro
14:redef Reporter::errors_to_stderr = F;
```
To set that option to `T` and then re-run `deploy` / `diag`.  Once you do, please report back the new error messages given.

**Comment by jsiwek** [comment]
@shuaidonga just checking: were you able use the previous suggestions to get more informative error messages ?

**Comment by shuaidonga** [comment]
@jsiwek 
To set that option to T and then re-run deploy / diag. new errors as following.
warning in /usr/local/bro/share/bro/site/add_http_bodies.bro, line 220: deprecated (bro_init)
warning in /usr/local/bro/share/bro/site/kafka-test.bro, line 1: Discarded extraneous Zeekygen comment: print fmt("connection: %s, is_orig: %s, stat: %s", c, is_orig, stat
warning in /usr/local/bro/share/bro/site/packages/metron-bro-plugin-kafka/__load__.bro, line 1: Discarded extraneous Zeekygen comment: print fmt("connection: %s, is_orig: %s, stat: %s", c, is_orig, stat
warning in /usr/local/bro/share/bro/site/packages/metron-bro-plugin-kafka/./logs-to-kafka.bro, line 1: Discarded extraneous Zeekygen comment: print fmt("connection: %s, is_orig: %s, stat: %s", c, is_orig, stat
warning in /usr/local/bro/share/bro/site/packages/metron-bro-plugin-kafka/./logs-to-kafka.bro, line 38: deprecated (bro_init)
warning in /usr/local/bro/share/bro/site/add_dns_logs.bro, line 99: deprecated (bro_init)
warning in /usr/local/bro/share/bro/site/add_ignored_noties.bro, line 57: deprecated (bro_init)
warning in /usr/local/bro/share/bro/site/kafka-test.bro, line 35: deprecated (bro_init)
error: stream event's argument type does not match column record type
fatal error: errors occurred while initializing

**Comment by shuaidonga** [comment]
This problem has been fixed due to the custom bro script module and bro ids
