### ISSUE TITLE
Telemetry headers reference Prometheus headers which are not installed

### ISSUE THREAD

**Issue by bbannier** [zeek/zeek#3760]
Since very recently Zeek uses Prometheus. We use a vendored version of  https://github.com/jupp0r/prometheus-cpp. This is observable to users since headers from that project are included in installed, public headers

```console
$ grep -r "#include <prometheus" /usr/local/zeek/include/
/usr/local/zeek/include/zeek/telemetry/Utils.h:#include <prometheus/family.h>
/usr/local/zeek/include/zeek/telemetry/Utils.h:#include <prometheus/labels.h>
/usr/local/zeek/include/zeek/telemetry/Gauge.h:#include <prometheus/family.h>
/usr/local/zeek/include/zeek/telemetry/Gauge.h:#include <prometheus/gauge.h>
/usr/local/zeek/include/zeek/telemetry/Manager.h:#include <prometheus/exposer.h>
/usr/local/zeek/include/zeek/telemetry/Manager.h:#include <prometheus/registry.h>
/usr/local/zeek/include/zeek/telemetry/Histogram.h:#include <prometheus/family.h>
/usr/local/zeek/include/zeek/telemetry/Histogram.h:#include <prometheus/histogram.h>
/usr/local/zeek/include/zeek/telemetry/Counter.h:#include <prometheus/counter.h>
/usr/local/zeek/include/zeek/telemetry/Counter.h:#include <prometheus/family.h>
/usr/local/zeek/include/zeek/telemetry/Opaques.h:#include <prometheus/counter.h>
/usr/local/zeek/include/zeek/telemetry/Opaques.h:#include <prometheus/family.h>
```

If one currently installs any of these headers one very likely runs into a compilation error, or is in danger of using an incompatible out-of-band version of prometheus-cpp.

We should very likely install headers from the vendored package into Zeek's prefix, or alternatively make sure there exists a documented way to use an out-of-band installation of these headers (ideally: catching incompatible versions).

**Comment by timwoj** [comment]
Fixed by dd0814c8048b1db9b1cc755017fd88f5404ba135
