### ISSUE TITLE
zeek 6.2.1, [ZeekControl] > start  :  error in /opt/zeek/share/zeek/policy/frameworks/control/controllee.zeek, line 13: syntax error, at or near "module"

### ISSUE THREAD

**Issue by wahyueko22** [zeek/zeek#3799]
[ZeekControl] > start
starting zeek ...
creating crash report for previously crashed nodes: zeek
Error: zeek terminated immediately after starting; check output with "diag"
[ZeekControl] > diag
[zeek]

No core file found and gdb is not installed.  It is recommended to
install gdb so that ZeekControl can output a backtrace if Zeek crashes.

Zeek 6.2.1
Linux 5.10.16.3-microsoft-standard-WSL2

Zeek plugins:
Demo::Rot13 - Caesar cipher rotating a string's letters by 13 places. (dynamic, version 0.1.0)
ICSNPP::BACnet - BACnet Protocol analyzer (dynamic, version 1.4.0)
ICSNPP::ENIP - Ethernet/IP and CIP Protocol analyzer for TCP/UDP (dynamic, version 1.3.0)

==== No reporter.log

==== stderr.log
error in /opt/zeek/share/zeek/policy/frameworks/control/controllee.zeek, line 13: syntax error, at or near "module"

==== stdout.log
max memory size             (kbytes, -m) unlimited
data seg size               (kbytes, -d) unlimited
virtual memory              (kbytes, -v) unlimited
core file size              (blocks, -c) unlimited

==== .cmdline
-i eth0 -U .status -p zeekctl -p zeekctl-live -p standalone -p local -p zeek local.zeek zeekctl zeekctl/standalone zeekctl/auto

==== .env_vars
PATH=/opt/zeek/bin:/opt/zeek/share/zeekctl/scripts:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ZEEKPATH=/opt/zeek/spool/installed-scripts-do-not-touch/site::/opt/zeek/spool/installed-scripts-do-not-touch/auto:/opt/zeek/share/zeek:/opt/zeek/share/zeek/policy:/opt/zeek/share/zeek/site:/opt/zeek/share/zeek/builtin-plugins
CLUSTER_NODE=

==== .status
TERMINATED [atexit]

==== No prof.log

==== No packet_filter.log

==== No loaded_scripts.log

[ZeekControl] >

**Comment by awelzel** [comment]
@wahyueko22 - could you check if your own scripts/modifications are missing a semicolon? You're likely being mislead by difficult error reporting when there's a syntax error directly followed by `@load` - see the following ticket: https://github.com/zeek/zeek/issues/3265

Possibly check for modifications in `local.zeek`. I also see you have the demo rot 13 plugin installed. This might also be the culprit.
---

I'm closing this issue. Please reach out in the forum or on Slack if you need further assistance. Thanks!
