### ISSUE TITLE
Address CAF spinlock problem

### ISSUE THREAD

**Issue by jsiwek** [zeek/zeek#380]
Using the work-stealing CAF scheduler, we've observed the spinlock used by its double-ended-queue being a cpu hog.  Unclear exactly why, but introducing a 1 microsecond sleep to the spinlock resolved the issue.  Either need to coordinate to get that improved in upstream CAF and patched for Zeek 3.0 or else try switching to the work-sharing CAF scheduler, which doesn't use a spinlock (the work-stealing I don't think best fits our default use-case anyway: we don't need a high level of concurrency or particularly low latency).

**Comment by rsmmr** [comment]
Waiting for testing of nanosleep change to CAF.

**Comment by jsiwek** [comment]
I reported the issue and test results to Dominik: looks like for CAF, incorporating the nanosleep patch is still an improvement to consider.

For our use-case, looks like switching to the work-sharing scheduler is an even better improvement in terms of potential cpu utilization improvements, and it additionally bypasses the potential spinlock issue altogether.
