### ISSUE TITLE
7.0.0-rc1 cmake error

### ISSUE THREAD

**Issue by leres** [zeek/zeek#3828]
My initial test build of 7.0.0-rc1 on FreeBSD didn't get very far:
```
-- Configuring bundled project: prometheus-cpp
CMake Error at auxil/broker/cmake/ZeekBundle.cmake:70 (file):
  file failed to open for reading (No such file or directory):

    /wrkdirs/usr/ports/security/zeek-devel/work/.build/_deps/dl_prometheus-cpp-build/cmake.err
Call Stack (most recent call first):
  auxil/broker/cmake/ZeekBundle.cmake:128 (zeekbundle_build)
  auxil/broker/CMakeLists.txt:219 (ZeekBundle_Add)


CMake Error at auxil/broker/cmake/ZeekBundle.cmake:71 (message):
  Failed to configure external project prometheus-cpp:



Call Stack (most recent call first):
  auxil/broker/cmake/ZeekBundle.cmake:128 (zeekbundle_build)
  auxil/broker/CMakeLists.txt:219 (ZeekBundle_Add)


-- Configuring incomplete, errors occurred!
*** Error code 1

Stop.
make: stopped in /usr/ports/security/zeek-devel
```
Looking around, /wrkdirs/usr/ports/security/zeek-devel/work/.build/_deps does not exist and I don't see any files name cmake.err anywhere. Given my (well documented) lack of cmake chops I clearly need some help. I'll attach the build output.
[zeek.log](https://github.com/user-attachments/files/16184466/zeek.log)

**Comment by leres** [comment]
FYI, my first test was with 14.1-RELEASE but I did another with 13.3-RELEASE and got the same error.

**Comment by awelzel** [comment]
@Neverlord , this is reproducible with: `/configure -D FETCHCONTENT_FULLY_DISCONNECTED:BOOL=ON` which the FreeBSD [ports system sets by default](https://cgit.freebsd.org/ports/commit/?id=33ec243a799f8eae4402334bc2e851ac1ad3d293). 

My only hunch is to do an explicit `file(MAKE_DIRECTORY, ... BUILD_DIR)` for 7.0.0. I do note, however, that `FetchContent_Populate` was deprecated in the name-only version with cmake 3.30, too, so maybe there's something better with `FetchContent_MakeAvailable()` ?

```
CMake Warning (dev) at /opt/cmake-3.30/share/cmake-3.30/Modules/FetchContent.cmake:1953 (message):
  Calling FetchContent_Populate(dl_prometheus-cpp) is deprecated, call
  FetchContent_MakeAvailable(dl_prometheus-cpp) instead.  Policy CMP0169 can
  be set to OLD to allow FetchContent_Populate(dl_prometheus-cpp) to be
  called directly for now, but the ability to call it with declared details
  will be removed completely in a future version.                                              
Call Stack (most recent call first):                                                           
  auxil/broker/cmake/ZeekBundle.cmake:126 (FetchContent_Populate)                              
  auxil/broker/CMakeLists.txt:219 (ZeekBundle_Add)                                             
This warning is for project developers.  Use -Wno-dev to suppress it.     
```

Think this is sufficient for now?
```
diff --git a/ZeekBundle.cmake b/ZeekBundle.cmake
index 234a060..45399c3 100644
--- a/ZeekBundle.cmake
+++ b/ZeekBundle.cmake
@@ -125,6 +125,7 @@ function (ZeekBundle_Add)
     string(TOLOWER "dl_${arg_NAME}" internalName)
     FetchContent_Populate(${internalName})
     # Build the package and verify that it was found.
+    file(MAKE_DIRECTORY "${${internalName}_BINARY_DIR}")
     zeekbundle_build(${arg_NAME} "${${internalName}_SOURCE_DIR}" "${${internalName}_BINARY_DIR}"
                      ${arg_CONFIGURE})
     find_package(
```

Thanks @leres !

**Comment by awelzel** [comment]
> this is reproducible with: /configure -D FETCHCONTENT_FULLY_DISCONNECTED:BOOL=ON which the FreeBSD [ports system sets by default](https://cgit.freebsd.org/ports/commit/?id=33ec243a799f8eae4402334bc2e851ac1ad3d293).

Wonder if we should use that flag in CI, actually.

**Comment by timwoj** [comment]
> I do note, however, that FetchContent_Populate was deprecated in the name-only version with cmake 3.30, too, so maybe there's something better with FetchContent_MakeAvailable() ?

From the docs about FetchContent_Populate:

> It is rarely the right command to use, projects should almost always use [FetchContent_Declare()](https://cmake.org/cmake/help/latest/module/FetchContent.html#command:fetchcontent_declare) and [FetchContent_MakeAvailable()](https://cmake.org/cmake/help/latest/module/FetchContent.html#command:fetchcontent_makeavailable) instead.

**Comment by ckreibich** [comment]
> Wonder if we should use that flag in CI, actually.

I like that!

**Comment by ckreibich** [comment]
Do we have any ideas why we didn't hit this in CI?

**Comment by timwoj** [comment]
For the record, just swapping over to `FetchContent_Declare`/`FetchContent_MakeAvailable` calls results in a configure failure later in the process:

```
==================|  prometheus-cpp Config Summary  |====================

CMake Error at auxil/broker/auxil/prometheus-cpp/cmake/googlemock-3rdparty-config.cmake:5 (add_library):
  add_library cannot create target "gmock_main" because another target with
  the same name already exists.  The existing target is a static library
  created in source directory
  "/home/tim/zeek/auxil/broker/auxil/prometheus-cpp".  See documentation for
  policy CMP0002 for more details.
Call Stack (most recent call first):
  auxil/prometheus-cpp/CMakeLists.txt:86 (find_package)


-- Could NOT find benchmark (missing: benchmark_DIR)
CMake Error at auxil/prometheus-cpp/core/CMakeLists.txt:2 (add_library):
  add_library cannot create target "core" because another target with the
  same name already exists.  The existing target is a shared library created
  in source directory
  "/home/tim/zeek/auxil/broker/auxil/prometheus-cpp/core".  See documentation
  for policy CMP0002 for more details.


CMake Error at auxil/prometheus-cpp/core/tests/CMakeLists.txt:2 (add_executable):
  add_executable cannot create target "prometheus_core_test" because another
  target with the same name already exists.  The existing target is an
  executable created in source directory
  "/home/tim/zeek/auxil/broker/auxil/prometheus-cpp/core/tests".  See
  documentation for policy CMP0002 for more details.


CMake Error at auxil/prometheus-cpp/util/CMakeLists.txt:1 (add_library):
  add_library cannot create target "util" because another target with the
  same name already exists.  The existing target is an interface library
  created in source directory
  "/home/tim/zeek/auxil/broker/auxil/prometheus-cpp/util".  See documentation
  for policy CMP0002 for more details.
  
<snipped for brevity, lots more follows>
```

This occurs while attempting to configure prometheus-cpp for the Zeek build itself. Broker was able to configure prometheus-cpp for its uses.

**Comment by ckreibich** [comment]
> Do we have any ideas why we didn't hit this in CI?

Tim's theory is that without that `FULLY_DISCONNECTED` flag, the FetchContent call correctly finds/downloads the sources and we don't notice in CI, since we don't set the flag. If that's the case I wonder whether we should set that flag at all times since we never want anything downloaded anywhere, ever.

**Comment by timwoj** [comment]
I added the flag to just the Broker CI, and it's failing there on some of the builds: https://cirrus-ci.com/task/4550278567952384

```
CMake Error at cmake/ZeekBundle.cmake:71 (message):
  Failed to configure external project prometheus-cpp:
  
  CMake Error: The source directory
  "/broker/build/_deps/dl_prometheus-cpp-src" does not exist.
  Specify --help for usage, or press the help button on the CMake GUI.
Call Stack (most recent call first):
  cmake/ZeekBundle.cmake:129 (zeekbundle_build)
  CMakeLists.txt:219 (ZeekBundle_Add)
-- Configuring incomplete, errors occurred!
```

That's with the `flie()` command that Arne added above as well. Something deeper is wrong with this setup.

**Comment by timwoj** [comment]
The `file()` workaround that Arne posted plus one other fix to the call to `FetchContent_Populate` are in master and release/7.0 now.

**Comment by leres** [comment]
> The `file()` workaround that Arne posted plus one other fix to the call to `FetchContent_Populate` are in master and release/7.0 now.

Is the release/7.0 branch where 7.0.0-rc1 came from? How long until 7.0.0-rc2 appears?

**Comment by timwoj** [comment]
> Is the release/7.0 branch where 7.0.0-rc1 came from?

Yes.

> How long until 7.0.0-rc2 appears?

I can't really say. Depends on if anything else major comes up. It won't happen today since the day is almost over, but we could do one early next week. I had already cherry-picked over a spicy compilation-time fix for @bbannier into the branch, so this isn't the only fix.

**Comment by leres** [comment]
I took a run at building as a FreeBSD port from the release/7.0 branch but I don't quite understand how to create a blob that has all of the bits that rc1 has. (I figured out "git submodule update --init" but the auxil/zeekctl/auxil/trace-summary dir is still empty so I gave up.)

**Comment by timwoj** [comment]
> I figured out "git submodule update --init" but the auxil/zeekctl/auxil/trace-summary dir is still empty so I gave up

Add the `--recursive` flag so it gets all of the sub-submodules: `git submodule update --init --recursive`

Alternatively, if you're cloning the repo instead of downloading the tarball, you can pass the same flag to `git clone` to automatically get all of the submodules.

**Comment by leres** [comment]
That gets me further, thanks!

I found "make dist" which seems to require gmake. It gives me a couple of errors though:
```
zinc 233 % gmake dist
error: cannot run grealpath: No such file or directory
fatal: run_command returned non-zero status for auxil/bifcl
.
error: cannot run grealpath: No such file or directory
fatal: run_command returned non-zero status for auxil/bifcl
.
Package: zeek.git-7.0.0-rc1.tar.gz

```
I tried building with the resulting tarchive and it dies here:
```
=================|  Paraglob Config Summary  |===================
BUILD_TYPE:          RELEASE
CXX_FLAGS:           -O2 -pipe -fstack-protector-strong -fno-strict-aliasing -Wall -Wno-unused -funsigned-char -Wno-register -Werror=vla -funsigned-char -std=c++17 -Wall -O3
=================================================================

-- Performing Test BROKER_HAS_STD_FILESYSTEM
-- Performing Test BROKER_HAS_STD_FILESYSTEM - Success
-- Looking for include file emmintrin.h
-- Looking for include file emmintrin.h - found
-- Performing Test atomic64_builtin
-- Performing Test atomic64_builtin - Success
-- Configuring bundled project: prometheus-cpp
CMake Error at auxil/broker/cmake/ZeekBundle.cmake:70 (file):
  file failed to open for reading (No such file or directory):

    /wrkdirs/usr/ports/security/zeek-rc1/work/.build/_deps/dl_prometheus-cpp-build/cmake.err
Call Stack (most recent call first):
  auxil/broker/cmake/ZeekBundle.cmake:128 (zeekbundle_build)
  auxil/broker/CMakeLists.txt:219 (ZeekBundle_Add)


CMake Error at auxil/broker/cmake/ZeekBundle.cmake:71 (message):
  Failed to configure external project prometheus-cpp:



Call Stack (most recent call first):
  auxil/broker/cmake/ZeekBundle.cmake:128 (zeekbundle_build)
  auxil/broker/CMakeLists.txt:219 (ZeekBundle_Add)


-- Configuring incomplete, errors occurred!
*** Error code 1

Stop.
make: stopped in /usr/ports/security/zeek-rc1
```
I assume it's because the tarchive is incomplete.

**Comment by leres** [comment]
Yeah, the FreeBSD realpath is very simple.

(After installing coreutils to get grealpath) here's what I did:
```
git clone --recursive https://github.com/zeek/zeek.git
cd zeek.git && git checkout v7.0.0-rc1
git submodule update --init --recursive
gmake dist
mv zeek.git-7.0.0-rc1.tar.gz /usr/ports/distfiles/zeek-7.0.0-devel.tar.gz
```
But the build dies in the same place, related to prometheus-cpp:
```
=================|  Paraglob Config Summary  |===================
BUILD_TYPE:          RELEASE
CXX_FLAGS:           -O2 -pipe -fstack-protector-strong -fno-strict-aliasing -Wall -Wno-unused -funsigned-char -Wno-register -Werror=vla -funsigned-char -std=c++17 -Wall -O3
=================================================================

-- Performing Test BROKER_HAS_STD_FILESYSTEM
-- Performing Test BROKER_HAS_STD_FILESYSTEM - Success
-- Looking for include file emmintrin.h
-- Looking for include file emmintrin.h - found
-- Performing Test atomic64_builtin
-- Performing Test atomic64_builtin - Success
-- Configuring bundled project: prometheus-cpp
CMake Error at auxil/broker/cmake/ZeekBundle.cmake:70 (file):
  file failed to open for reading (No such file or directory):

    /wrkdirs/usr/ports/security/zeek-rc1/work/.build/_deps/dl_prometheus-cpp-build/cmake.err
Call Stack (most recent call first):
  auxil/broker/cmake/ZeekBundle.cmake:128 (zeekbundle_build)
  auxil/broker/CMakeLists.txt:219 (ZeekBundle_Add)


CMake Error at auxil/broker/cmake/ZeekBundle.cmake:71 (message):
  Failed to configure external project prometheus-cpp:



Call Stack (most recent call first):
  auxil/broker/cmake/ZeekBundle.cmake:128 (zeekbundle_build)
  auxil/broker/CMakeLists.txt:219 (ZeekBundle_Add)


-- Configuring incomplete, errors occurred!
*** Error code 1

Stop.
make: stopped in /usr/ports/security/zeek-rc1
```

**Comment by leres** [comment]
> Change this to `git checkout release/7.0`. You're still using the broken version from rc1.

Not sure how I switched back to rc1.. But release/7.0 seems to build ok.

But installing it on a system to test I have a new problem:
```
mote 76 # service zeek deploy
/usr/local/bin/zeekctl: Command not found.
mote 77 # head -1  /usr/local/bin/zeekctl
#!/wrkdirs/usr/ports/security/zeek-rc1/work/.bin/python3
```
My FreeBSD port Makefile is almost identical; to make all of the scripts that reference "python3" work I used:
```
BINARY_ALIAS=   python3=${PYTHON_CMD}
```
which creates a .bin directory, adds it to the path, and adds a symlink:
```
zinc 22 @ pwd
/wrkdirs/usr/ports/security/zeek-rc1/work
zinc 23 @ ls -l .bin
total 0
lrwxr-xr-x  1 root wheel 45 Jul 15 23:08 python3 -> ../../../../../../../usr/local/bin/python3.11
```
This works for 6.0 so I'm guessing 7.0 is running realpath/grealpath on the link and sticking that in some script(s).

I tried setting Python_EXECUTABLE to /usr/local/bin/python3.11 but not all zeek python scripts use that:
```
env: python3: No such file or directory
CMake Error at CMakeLists.txt:1315 (message):
  Could not collect repository info
```
I'm trying other things but wanted to report this in case it's something you want to adjust from your side. (Looks like 37 scripts use "#!/usr/bin/env python3")

**Comment by leres** [comment]
Never mind... I added all 37 scripts to SHEBANG_FILES and everything seems to work now. (Well, it looks like I need to adjust some scripts to work with 7.0 but that's my problem.)

**Comment by ckreibich** [comment]
Hey Craig, thanks! :wave:  — I'm reading between the lines here that FreeBSD has `python` and python3.11` binaries, but not `python3`. Is that correct?

Our use of `Python_EXECUTABLE` is mainly about cmake-internal invocations of Python, not so much identifying a binary that the installed scripts would run. One place I do see it used is in `zeekctl`, for the SSH runner. I suspect for your purposes it doesn't matter whether a Python script is installed or not, but I'm still struggling to identify 37 ... is there a quick way you could list them?

**Comment by leres** [comment]
I used:
```
find . -type f -print0 | xargs -0 fgrep -w python3 | fgrep '#!' 
```
Taking Python_EXECUTABLE out of the cmake config made no difference to my build.

My port Makefile has USES=python which gets me the default which I set to python311 on my build server. When I install python311, I get /usr/local/bin/python3.11

There's also a wrapper port called python3 that just installs symlinks from python3 to python3.11. And another called python that installs symlnks from python to python3.

Python scripts built from ports always use python3.11 (or whatever version), I always install the python and python3 ports so I use "/usr/local/bin/python" in any scripts I write.

**Comment by ckreibich** [comment]
Got it, thanks. Yeah that pulls up a bunch of stuff, partially ours, partially in third-party dependencies. Looks like nearly all of ours go via `env` to locate the binary.

It's unfortunate if something changed here between 6 and 7 because I don't think we've intentionally gone near this.

I also need to revise my comment above about `Python_EXECUTABLE`, because I just found some path-munging logic in `InstallShellScript.cmake` that seems to pick up that variable, and we use that in a bunch of places.

So ... really hard to straighten this out consistently. :-(
