### ISSUE TITLE
Zeek integrates with metron-bro-plugin-kafka, output log memory keeps rising

### ISSUE THREAD

**Issue by shuaidonga** [zeek/zeek#383]
Zeek integrates with metron-bro-plugin-kafka, output log memory keeps rising, remove metron-bro-plugin-kafka and hit the local is normal.
![image](https://user-images.githubusercontent.com/16378509/58449871-01861d00-813f-11e9-8fd3-83560be4c95b.png)

**Comment by jsiwek** [comment]
We don't develop or support that plugin directly, so you may have to reach out to the authors/maintainers for suggestions.

@JonZeolla any pointers to where they should seek further help or guidance ?

**Comment by JonZeolla** [comment]
Feel free to send an email to the appropriate [Metron mailing list](http://metron.apache.org/community/#mailinglist), or open a JIRA [here](https://issues.apache.org/jira/secure/Dashboard.jspa).

**Comment by neal1991** [comment]
@shuaidonga Can you install metron-bro-plugin-kafka. I try to install. But failed. It keep stucking.

**Comment by JonZeolla** [comment]
If you have specific issues with the plugin, please follow the links [above](https://github.com/zeek/zeek/issues/383#issuecomment-496646778) and let us know.

Note that we should have an `0.3` version release here any day, and expect to do a `1.0` release not too long in the future to account for the zeek project rename from bro.
