### ISSUE TITLE
Define coding style and a clang-format config

### ISSUE THREAD

**Issue by rsmmr** [zeek/zeek#386]
We should develop a summary of the C++ side coding style along with a corresponding `clang-format` config (In fact, that config can *be* the style documentation for things can it can express).

Note that `clang-format` doesn't support (at least) two formatting bits yet that the Zeek code uses:

- Inserting a space after a logical not (`!`). This has actually just been added to `clang-format`  and will be part of version 9 (option `SpaceAfterLogicalNot`, see [commit](https://github.com/llvm-mirror/clang/commit/9a63380260860))

- Inserting spaces around conditions in `if` etc. There's a [patch](https://github.com/rsmmr/install-clang/blob/master/patches/tools--clang--linker-addl-clang-format-options.patch) that adds a corresponding option coming with the [install-clang](https://github.com/rsmmr/install-clang) script. `install-clang` script incorporates that patch into a mostly statically linked version of `clang-format`; which we could make available as a binary ("mostly" because it keeps linking against some shared low-level system libraries)

**Comment by timwoj** [comment]
If you're building Clang via homebrew, there's a way to insert extra patches into existing recipes: https://www.ralfebert.de/snippets/brew-apply-patch-to-package-formula/. That might be better than building a static version of Clang to pass around, since most (all?) of us work on macOS.

As for the actual formatting, did you have a config already created when you were working on the patch?

**Comment by rsmmr** [comment]
On Wed, May 29, 2019 at 17:07 -0700, Tim Wojtulewicz wrote:

> If you're building Clang via homebrew, there's a way to insert extra
> patches into existing recipes:
> https://www.ralfebert.de/snippets/brew-apply-patch-to-package-formula/.

Interesting, that's good to know.

Yeah, we'll probably need multiple options. With the static version I
was also thinking of CI integration. And on macOS, some of us use
MacPorts. :) But static or not, the install-clang script builds a
patched clang-format on both Linux and macOS, so one can always
compile it locally as well that way.

> As for the actual formatting, did you have a config already created
> when you were working on the patch?

Not for Zeek (or if I did, it's long enough ago that I don't remember
it ...).  Recently I've been using it for another project.


-- 
Robin Sommer * Corelight, Inc. * robin@corelight.com * www.corelight.com

**Comment by timwoj** [comment]
At a first glance, clang-format also doesn't support Whitesmith. There's a very old patch open against LLVM for it, but it hasn't been looked at since 2016. See https://reviews.llvm.org/D6833.

**Comment by rsmmr** [comment]
Ah, I missed that. For some reason I thought clang-format would support Whitesmith. Sounds like another patch will be needed; maybe that old one will work, or at least can be a starting point.

**Comment by timwoj** [comment]
Coding style documentation is now available at https://github.com/zeek/zeek-docs/blob/master/devel/style_guide.rst

**Comment by timwoj** [comment]
I'm leaving this GHI open in case I ever get back to finishing the whitesmiths patch for clang-format.

**Comment by timwoj** [comment]
The whitesmiths patch and a patch for spaces inside conditional have both landed in master for clang-format. Both should be in the next LLVM release, which is slated for sometime in Feb 2020.

**Comment by timwoj** [comment]
As I was working on reformatting the code for #248, I figured I should start working on a configuration for this. Here's a starter config for clang-format. It only works with clang 10.0 and above because of the dependence on `BreakBeforeBraces: Whitesmiths` and `SpacesInConditionalStatement`.

```
# Clang-format configuration for Zeek.

Language: Cpp
Standard: c++17

BreakBeforeBraces: Whitesmiths

#BraceWrapping:
#    AfterCaseLabel: true
#    AfterClass: true
#    AfterControlStatement: Always
#    AfterEnum: true
#    AfterFunction: true
#    AfterNamespace: true
#    AfterStruct: true
#    AfterExternBlock: false
#    BeforeCatch: true
#    BeforeElse: true
#    IndentBraces: true
#    SplitEmptyFunction: false
#    SplitEmptyRecord: false

AccessModifierOffset: -4
AlignAfterOpenBracket: true
AllowShortBlocksOnASingleLine: Empty
AllowShortFunctionsOnASingleLine: Inline
AllowShortIfStatementsOnASingleLine: false
AllowShortLambdasOnASingleLine: Empty
AllowShortLoopsOnASingleLine: false
BreakConstructorInitializers: BeforeColon
BreakInheritanceList: BeforeColon
ColumnLimit: 0
ConstructorInitializerAllOnOneLineOrOnePerLine: true
FixNamespaceComments: false
IndentCaseLabels: true
IndentPPDirectives: None
IndentWidth: 4
NamespaceIndentation: None
PointerAlignment: Left
SpaceAfterLogicalNot: true
SpaceBeforeAssignmentOperators: true
SpaceBeforeCpp11BracedList: true
SpaceBeforeCtorInitializerColon: true
SpaceBeforeInheritanceColon: true
SpaceBeforeParens: ControlStatements
SpaceBeforeRangeBasedForLoopColon: true
SpaceBeforeSquareBrackets: false
SpaceInEmptyBlock: true
SpaceInEmptyParentheses: false
SpacesInAngles: false
SpacesInConditionalStatement: true
SpacesInContainerLiterals: false
TabWidth: 4

# With clang-format 11, we can get "AlignWithSpaces" here, but for
# now this will have to do.
UseTab: Always
```

The `BraceWrapping` section is commented out to show what `Whitesmiths` implies. My big concerns with it are that `Whitesmiths` sets `AfterClass`, `AfterEnum`, `AfterNamespace`, and `AfterStruct` to true (because that's how the actual Whitesmiths style defines it). That results in diffs that look like this:

```
-namespace llanalyzer {
+namespace llanalyzer
+       {
 
-class Analyzer {
+class Analyzer
+       {
```

Unfortunately, there's no way to override `BreakBeforeBraces` unless you set it to `Custom` and then define it all by hand. I tried this though, and for some reason the `IndentBraces` sub-setting to `BraceWrapping` doesn't work correctly, and so things like function braces don't get indented as expected.

**Comment by timwoj** [comment]
Any thoughts on the above configuration?

**Comment by rsmmr** [comment]
Noticed some more changes that would be nicer to avoid (some are quite small, but maybe there's an option):

```
- switch ( type->InternalType() ) {
+ switch ( type->InternalType() )
+              {
```

```
-       delete [] bound_id;
+       delete[] bound_id;
```

```
- return {NewRef{}, i->second};
+ return {NewRef {}, i->second};
```

```
- unit_word{ Days, "day" },
+ unit_word {Days, "day"},
```

```
-       case TYPE_INTERNAL_OTHER:
-               XXX
+       case TYPE_INTERNAL_OTHER:
+       XXX
```

And the changes to `class` braces go further than the example in the comment above, the closing brace moves too:

```
-class AddrVal final : public Val {
- ...
- };
+class AddrVal final : public Val
+       {
+      ...
+.      };

**Comment by rsmmr** [comment]
This is looking mostly good to me. The main things that bother me are the bracing for `class` and, a little less so, for `namespace`; and for now the lack of `AlignWithSpaces`.

If we could figure these out, I'd be quite happy with the style. Maybe we need another clang-format patch?

**Comment by rsmmr** [comment]
The other question is whether we'd use this in some automated fashion. I don't quite recall where we were in that discussion but I recall the idea of not reformatting all of the code wholesale at once, but using clang-format only only pieces that we touch for other reasons (i.e, on new code and lines that change in the context of other PRs). I like that because it would would be quite a bit less disruptive.

**Comment by mavam** [comment]
@rsmmr we apply [a script to the diff](https://github.com/tenzir/vast/blob/master/scripts/clang-format-diff.py) for every PR. It works well in CI.

(We also have a script to setup git aliases to reformat the local branch/diff.)

**Comment by rsmmr** [comment]
@Tim clang11 should be coming out soon, that'll give us `AlignWithSpaces`. I could live with the other differences that we're still seeing, even the bracing for `class`. I think the benefit of getting a clang-format spec would definitely outweigh all of this.

So question: can we move forward here? I think the two action items are:

1. Settle on a final clang-format spec.
2. Decide how we want to apply this: 
    a. Option 1: One run across the board to get everything consistent, then commit/push-time checks for new code.
    b. Option 2: Apply only to changed code as we commit it, like wit the script that @mavam linked to. Ideally, we'd also enforce this commit/push-time.

Option 2 is my preference, the only concern I would have is editor integration: it might be cumbersome to prevent IDEs/editors to not reformat the whole file (unless there's already a plugin for e.g. vi to limit clang-format to git chunks?)

**Comment by timwoj** [comment]
If I remember correctly there's also a feature of git where you can do reformatting commits that don't show up in diffs. That might be useful here. I'll take a look at what's new for clang11 and rework my existing config.

**Comment by timwoj** [comment]
I pushed a branch (see above commit) that has a clang-format config as well as the `Dict.h` file converted to use the configuration. There's still some issues with the wrapping of braces after class and namespaces, and the indentation of the braces closing those blocks. The `AlignWithSpaces` is a nice addition and fixes a bunch of issues.

I'm pretty convinced that there’s bugs with the `IndentBraces` flag if you use `BreakBeforeBraces: Custom` to try to fix the above class/namespace issues. With it set to true, you get a mishmash of what braces get indented. For example, braces that enclose a function don’t get indented, but braces that enclose a control block (like an if statement) do get indented. On top of that, statements inside those blocks do get indented. You end up with this:

```     DictEntry(void* arg_key, int key_size = 0, hash_t hash = 0, void* value = nullptr,                        
              int16_t d = TOO_FAR_TO_REACH, bool copy_key = false)                                            
        : distance(d), key_size(key_size), hash((uint32_t)hash), value(value)                                 
    {                                                                                                         
        if ( key_size <= 8 )                                                                                  
            {                                                                                                 
                memcpy(key_here, arg_key, key_size);                                                          
                if ( ! copy_key )                                                                             
                    delete[](char*) arg_key; // own the arg_key, now don't need it.                           
            }                                                                                                 
        else                                                                                                  
            {                                                                                                 
                if ( copy_key )                                                                               
                    {                                                                                         
                        key = new char[key_size];                                                             
                        memcpy(key, arg_key, key_size);                                                       
                    }                                                                                         
                else                                                                                          
                    {                                                                                         
                        key = (char*)arg_key;                                                                 
                    }                                                                                         
            }                                                                                                 
    }                                                                                                         
```

Setting it to false (or not setting it), you end up with something more akin to Allman style:

```
    DictEntry(void* arg_key, int key_size = 0, hash_t hash = 0, void* value = nullptr,                        
              int16_t d = TOO_FAR_TO_REACH, bool copy_key = false)                                            
        : distance(d), key_size(key_size), hash((uint32_t)hash), value(value)                                 
    {                                                                                                         
        if ( key_size <= 8 )                                                                                  
        {                                                                                                     
            memcpy(key_here, arg_key, key_size);                                                              
            if ( ! copy_key )                                                                                 
                delete[](char*) arg_key; // own the arg_key, now don't need it.                               
        }                                                                                                     
        else                                                                                                  
        {                                                                                                     
            if ( copy_key )                                                                                   
            {                                                                                                 
                key = new char[key_size];                                                                     
                memcpy(key, arg_key, key_size);                                                               
            }                                                                                                 
            else                                                                                              
            {                                                                                                 
                key = (char*)arg_key;                                                                         
            }                                                                                                 
        }                                                                                                     
    }                                                                                                         
```

**Comment by rsmmr** [comment]
That `Dict.h` file looks acceptable to me, and I think I could live with that brace-after-class style.

I can't quite tell if you're saying that the `IndentBraces` bug makes this unusable for us right now? Neither of the two examples look good, but I thought we can do Whitensmiths?

**Comment by timwoj** [comment]
We can do Whitesmiths. I was trying to use the custom breaks to mimic Whitesmiths, but with the class braces working the way we have them now.

**Comment by timwoj** [comment]
Is everyone ok with the formatting in that commit? Any objections before I do a bit more as a sample?

**Comment by ckreibich** [comment]
I just started tinkering with this — pretty cool!

On my systems Clang is at 10.0.1, which objects to the following `.clang-format` options:
- `UseTab` doesn't like `AlignWithSpaces`
- `IndentExternBlock` isn't recognized
- `AllowShortEnumsOnASingleLine` isn't recognized
- `IndentCaseBlocks` isn't recognized

Just wanted to flag in case there are any surprises here.

That Dict.h looks pretty good! This brace misalignment caught my eye:

        union {
                char key_here[8]; // hold key len<=8. when over 8, it's a pointer to real keys.
                char* key;
                };

Do we need to think about comments at all? Can it happen that clang-format reformats comments in a way that would affect docs extraction (e.g. with `@param`)?

**Comment by timwoj** [comment]
> On my systems Clang is at 10.0.1, which objects to the following .clang-format options:

Right, I should have added the caveat that this requires clang-format 11 primarily because of `AlignWithSpaces`

> This brace misalignment caught my eye

I'll look into it. It might be something with the Whitesmiths style built-into clang-format though, so fixing those might have to wait until 12 ☹️ 

> Do we need to think about comments at all?

There are some options for comments, but none that affect block comments like that. It's mostly for things like end-of-line comments being aligned, etc.

**Comment by rsmmr** [comment]
I'm fine going ahead here with a larger sample.

One more thing I noticed:

```
T* NextEntry(IterCookie*& cookie) const
		{
		detail::HashKey* h;
		return (T*)Dictionary::NextEntry(h, cookie, false);
		}
T* NextEntry(detail::HashKey*& h, IterCookie*& cookie) const
		{
		return (T*)Dictionary::NextEntry(h, cookie, true);
		}
```

Could clang-format add an empty line between those methods? With the bodies being multi-line now, it's getting crowded (not a show-stopper, just a nice-to-have),

**Comment by timwoj** [comment]
The next question is how we want to apply this. I think there's three options here:

1. Apply it across the entire codebase and do one gigantic commit that includes all of it all at once. This has a bad side-effect of breaking any long-lived branches, but a lot of those branches that haven't been rebased on master for a while are probably already broken.
2. Require it to be applied whenever you touch a file. This has two sub-options:
a. Require reformatting to be in a separate commit from any functional changes.
b. Don't require formatting to be in a separate commit.
3. Don't set any explicit policy around it. Just commit the clang-format file and let people do what they will with it.

**Comment by rsmmr** [comment]
I’d be interested in hearing if people think that (1) would be too painful …

**Comment by grigorescu** [comment]
Why not both (1) and (2)? I think that what was being discussed in terms of (2) is an automated check for PRs.

We can fix up the codebase today, and then also doing (2) provides two benefits. First, we ensure formatting for code moving forward, and second, it partially addresses the issue with older branches. If I have an old branch, before the PR for  it is ready, I need to fix the formatting. Once I do that, it would apply cleanly, and the diff to master would be minimal.

**Comment by rsmmr** [comment]
So looks like (1) is the consensus, let's do it! :)

For reference, also on Slack: https://zeekorg.slack.com/archives/CTGDG83B8/p1604562861231200

**Comment by timwoj** [comment]
This is on hold until I can fix some bugs in clang-format with `case` statements. There are two bugs:
- Single-line comments above a case statement are non-deterministic. One run will indent them properly, and the next run with undo it and move them back one indent level.
- Blocks underneath a case statement that are not surrounded by braces are not indented as expected.

I'm hoping to spend some time working on these soon and get fixes for them in by the time clang 11.0.1 is released.

**Comment by timwoj** [comment]
This issues with case blocks are already fixed in the trunk and will be fixed in clang 12. I opened an issue on the LLVM Bugzilla for the comment issues now that i have bit more information about what it's doing: https://bugs.llvm.org/show_bug.cgi?id=48668.

**Comment by timwoj** [comment]
Submitted https://reviews.llvm.org/D94500 to fix a few more bugs in clang-format.

**Comment by timwoj** [comment]
Just as an update, Clang accepted the above change request and we're now just waiting for Clang 13 to be released. This should be happening in the next 6 months or so.

**Comment by timwoj** [comment]
Clang 12.0.1 came out today, which includes a back-ported version of all of the changes I made. We can definitely use this version to reformat everything. The start of the 4.2 cycle would be a great timeline for this as well.

**Comment by timwoj** [comment]
This has finally been merged!
