### ISSUE TITLE
zeek handle 230m/s of traffic, each work memory keeps rising

### ISSUE THREAD

**Issue by shuaidonga** [zeek/zeek#390]
Bro is handling 230m/s of traffic, and the memory growth of each work over time causes system memory to run out.
![image](https://user-images.githubusercontent.com/16378509/58603392-26a39880-82c3-11e9-8763-36d6aeb17bcd.png)
Bro with PF_RING is configured as follows
![image](https://user-images.githubusercontent.com/16378509/58603797-ac741380-82c4-11e9-9a75-f76eab4b4220.png)

Centos machine configuration is as follows 40 core cpu, 64G memory。

Bro resource occupancy
![image](https://user-images.githubusercontent.com/16378509/58603937-2e643c80-82c5-11e9-94f6-7fed8338a84a.png).

Is there an optimized way?

**Comment by shuaidonga** [comment]
Increase cpu to 30, then logger takes up memory growth.
![image](https://user-images.githubusercontent.com/16378509/58614410-d5a79a80-82ea-11e9-97e1-3476f0bda526.png)

**Comment by schenksj** [comment]
@aeppert is this the issue you resolved locally?

**Comment by shuaidonga** [comment]
What can I do to optimize?
@schenksj  @aeppert  @jsiwek

**Comment by rsmmr** [comment]
This looks better suited for discussion on the mailing list.
