### ISSUE TITLE
How to populate IMEI value Type 20

### ISSUE THREAD

**Issue by Chiragdeshlehra27** [zeek/zeek#3902]
### Discussed in https://github.com/zeek/zeek/discussions/3901

<div type='discussions-op-text'>

<sup>Originally posted by **Chiragdeshlehra27** August 28, 2024</sup>
I have added a coloum in radius log with a name IMEI and want to get the populated values but the catch is the value comes under Type 20 vendor specific, So for me pulling Type 20 is easy but with this nested condition Type 26 then inside it Type 20 

</div>

**Comment by bbannier** [comment]
Hi,

We do not provide user support in GitHub discussions. Questions like this are best answered using Slack, or our forum. Both of these are followed by Zeek developers and professional users. You can join here:

Forum: https://community.zeek.org/

Slack: https://zeek.org/community/
