### ISSUE TITLE
libpcap 1.10.5 not returning negative timestamps anymore

### ISSUE THREAD

**Issue by awelzel** [zeek/zeek#3921]
The core.negative-time test on opensuse_tumbleweed[ starting failing](https://cirrus-ci.com/task/5145380709466112).

After looking a bit, on tumbleweed there's libpcap 1.10.5, while locally I have 1.10.4. And indeed, using libpcap.so.1.10.5 flips the timestamp sign (poor man fprintf output in PktSrc).

```
$ zeek -C -r Traces/negative-time.pcap 
time=1425182592.408334
time=-1410166911.589203

$ LD_PRELOAD=/home/awelzel/corelight-oss/projects/libpcap/libpcap.so.1.10.5 zeek -C -r Traces/negative-time.pcap 
time=1425182592.408334
time=2884800384.410797
```

@timwoj was wondering if that's a regression libpcap.

**Comment by timwoj** [comment]
I ran a bisect on libpcap and it points at https://github.com/the-tcpdump-group/libpcap/commit/8b90dfa10dea820658a5bc9b58ae6ac185d2ab7d

This part in the commit message is nice:

> Making the microseconds/nanoseconds field unsigned means that you don't
> have to think about what the heck a negative value means.

**Comment by timwoj** [comment]
@rsmmr Do remember the background for negative timestamps? The message in the above commit makes a lot of sense about why negative timestamps shouldn't even be valid. Should we be ok to fixup any negatives on older versions of libpcap? We might have to live with wild jumps in network time in those cases.

**Comment by rsmmr** [comment]
No memories here, I'd just remove the test.
