### ISSUE TITLE
When SYN is dropped conn log gets an entry per remaining packet, high memory utilization

### ISSUE THREAD

**Issue by schenksj** [zeek/zeek#394]
If a SYN packet (possibly other handshake packets) is dropped by Zeek, each subsequent packet is logged as a connection in the conn_log.  This is particularly problematic for high-bandwidth long-running connections (like video conferencing, remote desktop protocols, etc...).   Also, it appears that memory utilization gets very high as the connections seem to rely on the expiration timer to release the memory.   Both of these factors seem to contribute to slower performance and dropping more packets (vicious cycle).

All single-packet connections are logged with "history" of A, D, a, or d... No S/Sh 

Is this a bug?  If not, is there a better way to manage this so that the logs don't get spammed and processes don't consume an unmanageable amount of memory/CPU.

**Comment by jsiwek** [comment]
> If a SYN packet (possibly other handshake packets) is dropped by Zeek, each subsequent packet is logged as a connection in the conn_log

Don't think that's what should (or would) happen in a default configuration: packets all get associated with the same connection state based on their endpoint hosts/ports (5-tuples).  And there's no reason to create new connection state (new conn.log entry) unless observing the old one being closed (FIN/RST) or it's been inactive for a while (`tcp_inactivity_timeout`).

Do you have any customizations for any of the various TCP options?  e.g. those usually start with `tcp_`.  Or other things you've tuned away from the defaults?

Otherwise, might be helpful to get an example pcap to reproduce the behavior (simply chopping off a SYN or SYN+SYN-ACK doesn't do it for me).  Or providing a more detailed excerpt from conn.log may help.

**Comment by schenksj** [comment]
Thanks @jsiwek.  It is some crazy split routing thing.  I'll have to get an export of the data and sanitize it to remove the server names, IP addresses etc and then I'll post it

**Comment by schenksj** [comment]
@jsiwek Enclosed, please find the first ~500k of ~900k bro_conn entries for this one long-lived socket.  You'll notice that the first 4 lines show the actual socket evaluated for the most part properly, split across 4 sensors (its being tapped twice in the first data center (ds13), though I'm not sure why the packet distributor is routing the socket to 4 hosts instead of 2.  It clearly shows the conversation of >700k packets on one socket.

The next 500k+ lines show a single conn.log entry for each PACKET as tapped in the second data center (ds2)... The data has been manipulated to change the IP addresses in question (though the changes are consistent), and the sensor names have been changed to anonymize the infra as well.    Without question there is something odd happening with our routing, but the crazy thing is the conn.log entries 1-per-packet though its clearly a conversation and this ideally shouldn't cause un-manageable behavior in zeek.  Perhaps we broke something, or maybe it is an oddity exposed in Zeek when we get this very strange routing behavior.  Only this one sensor has this issue, and it only does the one-connection-per-packet for a few of the thousands of hosts it sees traffic for (Citrix and Skype servers).   I have yet to reproduce this issue, but will search through our pcap databases to see if I can find a more incriminating pcap.
[long_crazy_socket_anonymized.csv.gz](https://github.com/zeek/zeek/files/3243280/long_crazy_socket_anonymized.csv.gz)

**Comment by schenksj** [comment]
Two other interesting observations...

1) In the first data center where the zeek analysis is mostly sane looking, the raw pcap reveals a pretty normal looking TLS conversation...  In the second data center where the data appears to be mirroring incorrectly and zeek is going nuts logging every packet as a connection, the raw PCAP reveals tons of dup-acks and retransmissions (in fact every packet and ack gets at least one retransmission and/or dup-ack):
--- Again IP addresses anonymozed
<img width="1198" alt="Screen Shot 2019-06-01 at 8 43 15 AM" src="https://user-images.githubusercontent.com/15025459/58748633-dc005880-8449-11e9-843a-cbf09bc0fe2a.png">

2) All sockets for this particular host show these crazy re-transmits/dup-acks in their pcaps in data center #2, but not all connections do that crazy logging
3) Re-procesing the PCAP hasn't yet reproduced the issue, neither using tcpreplay nor at the command line.  I'll let tcpreplay grind on it, but there may be some very special circumstance that triggers the issue

**Comment by jsiwek** [comment]
> 1. In the first data center where the zeek analysis is mostly sane looking, the raw pcap reveals a pretty normal looking TLS conversation...  In the second data center where the packets are duplicated, zeek is going nuts logging every packet as a connection, the raw PCAP reveals tons of dup-acks and retransmissions (in fact every packet and ack gets at least one retransmission and/or dup-ack):

Ideally, Zeek would only see one copy of the traffic, not two, so would make sense to first resolve that inefficiency and see if the conn-log-per-packet issue goes away, too.

**Comment by schenksj** [comment]
Thanks jsiwek.  We will of course do that!   Will also look offline to figure out why zeek is logging a line for each packet to see if there are defensive safeguards that can be introduced.  I appreciate you looking into this.
