### ISSUE TITLE
Input Raw: 100% CPU usage when line is not immediately terminated with \n

### ISSUE THREAD

**Issue by awelzel** [zeek/zeek#3957]
A user reported 100% CPU usage of a ReaderBackend thread when executing a long-running process and reading its stdout/stderr process. I think the following reproduces it well:

```
#!/bin/sh
#
echo -n "aaa"
sleep 0.55
echo -n "aaa"
sleep 0.55
echo  "aaa"

sleep infinity
```
This isn't great, there's nothing special about this program except that "aaaaaaaaa\n" is produced "slowly". That seems to knock the input thread into an endless loop. There's also reallocation with every loop iteration (4096 bytes) which shouldn't be needed either.

```
redef exit_only_after_terminate = T;

type OneLine: record { s: string; is_stderr: bool; };

event one_line(d: Input::EventDescription, tpe: Input::Event, l: string, is_stderr: bool) {
        print "one_line", is_stderr, l;
}

event zeek_init() {
        Input::add_event([
                $name="run",
                $source="./run.sh |",
                $reader=Input::READER_RAW,
                $fields=OneLine,
                $mode=Input::STREAM,
                $ev=one_line,
                $want_record=F,
                $config=table(["read_stderr"] = "1"),
        ]);
}
```

I presume we should yield from `GetLine()` with no data and resume reading later.

**Comment by bwerthmann** [comment]
I tested [971b446](https://github.com/zeek/zeek/commit/971b446276ae71bae76f23cd75afce8e9c84b012) applied to zeek 6.04 and it seems to address the issue as reported.
