### ISSUE TITLE
TCP packets get parsed as Modbus

### ISSUE THREAD

**Issue by Lucasmeteenc** [zeek/zeek#3962]
Dear Zeek team,

I’ve encountered an issue with how Zeek parses Modbus traffic on port 502. Currently, all traffic on port 502 is parsed as Modbus if an entire PDU from both sides is successfully parsed, even if the traffic isn't valid Modbus TCP. This leads to cases where invalid TCP traffic is misidentified as Modbus traffic. In my application, I frequently encounter odd data and invalid function codes, making it difficult to distinguish between genuine Modbus traffic and erroneously parsed data.
The Modbus Messaging on TCP/IP Implementation Guide (V1.0b) specifies that the MBAP header should contain a Protocol Identifier and a Length field. By incorporating this information into the Modbus analyzer, we could prevent incorrectly parsed TCP traffic by verifying that the Protocol Identifier (PID) and length are correct.
![image](https://github.com/user-attachments/assets/4d5fa6ae-54a0-427a-96c6-872605b11828)

 
I’ve examined the relevant code and believe the necessary changes can be made in zeek/src/analyzer/protocol/modbus/modbus-analyzer.pac, specifically in the function deliver_ModbusTCP_PDU(message: ModbusTCP_PDU): bool at line 101. This function should return false if the MBAP headers do not contain the correct PID or if the length does not match the body length (plus 1 for the Unit Identifier).

![image](https://github.com/user-attachments/assets/3dc87869-b411-4e80-bb58-18d6b9c8c1e3)
![image](https://github.com/user-attachments/assets/c01bd81a-0efc-4964-b3e3-1837943be079)

However, I’m unsure about how to access the header and body fields within this function. From what I understand of the .pac language, we should be able to access these through message.header and message.body. If this is correct, we can verify the Protocol Identifier and Length fields as part of the header and ensure they match the PDU body.

Could you confirm if the header and body fields are correctly defined and accessible in deliver_ModbusTCP_PDU? If this structure is valid, I’d be happy to proceed with implementing the fix and submitting a pull request.

**Comment by awelzel** [comment]
> This leads to cases where invalid TCP traffic is misidentified as Modbus traffic. In my application, I frequently encounter odd data and invalid function codes, making it difficult to distinguish between genuine Modbus traffic and erroneously parsed data.

Would you be able to extract a few such sessions as pcap files and share them? (possibly with the correct protocol attribution for reference). This would make creation of a fix and adding test cases much easier.

**Comment by zambo99** [comment]
Dear Zeek team,

Here are some PCAPs with traffic directed to TCP port 502 that is not Modbus/TCP. The name of the PCAP indicates what traffic the initial request packet is supposed to be.

[non_modbus_on_port_502.zip](https://github.com/user-attachments/files/17265494/non_modbus_on_port_502.zip)

With all these PCAPs, the modbus.log displays the packets as modbus with unknown function codes.

**Comment by zambo99** [comment]
Dear Zeek team,

We have a patch ready addressing the above-mentioned limitation. 

Is it OK if we submit a pull request?

**Comment by evantypanski** [comment]
@zambo99 

> Is it OK if we submit a pull request?

Please do, no need to ask :)
