### ISSUE TITLE
Zeek cluster startup error

### ISSUE THREAD

**Issue by shuaidonga** [zeek/zeek#398]
Zeek cluster startup error. The cluster configuration is
![image](https://user-images.githubusercontent.com/16378509/58927774-8518bd00-8782-11e9-8abf-e8091e923057.png)

Wrong message is

error in /usr/local/bro/share/bro/base/frameworks/cluster/./setup-connections.zeek, lines 93-95: Failed to listen on INADDR_ANY:47761 (Broker::listen(Broker::default_listen_address, Cluster::self$p, Broker::default_listen_retry))
fatal error: errors occurred while initializing

**Comment by jsiwek** [comment]
Is another process already listening on port 47761 ?  We don't have much choice at the moment other than abort cluster startup with an error in that case and leave it up to the user to resolve the port conflict.

**Comment by Ethycs** [comment]
I encountered a similar issue. It turns out this was caused by multiple zeek instances running on the box. Rebooting the system(s) involved cleared the communication issues.
