### ISSUE TITLE
7.0.3 build errors with FreeBSD 15 current and clang 19.1.2

### ISSUE THREAD

**Issue by leres** [zeek/zeek#3994]
pkg fallout just started complaining about zeek. Here's a representative example error:
```
/usr/include/c++/v1/string:820:42: error: implicit instantiation of undefined template 'std::char_traits<unsigned char>'
  820 |   static_assert(is_same<_CharT, typename traits_type::char_type>::value,
      |                                          ^
/wrkdirs/usr/ports/security/zeek/work/zeek-7.0.3/src/DFA.cc:257:23: note: in instantiation of template class 'std::basic_string<unsigned char>' requested here
  257 |     for ( auto& entry : states ) {
      |                       ^
/usr/include/c++/v1/__fwd/string.h:23:29: note: template is declared here
   23 | struct _LIBCPP_TEMPLATE_VIS char_traits;
      |                             ^
```

The failed build log with all errors is here:

https://pkg-status.freebsd.org/beefy18/data/main-amd64-default/p645a502a4f60_s8b2e7da7085/logs/zeek-7.0.3.log

**Comment by evantypanski** [comment]
Hm, I'm not quite able to reproduce this, but it seems like Zeek is relying on a `uchar` specialization that [doesn't exist](https://en.cppreference.com/w/cpp/string/char_traits#Specializations) in the standard (though the `char8_t` one would probably suffice if we were on C++20).

If others can reproduce and verify that'd be nice, but if not, could you try this patch and see if it helps? It might need some touching up but this could check if my intuition is correct:

<details>

<summary>patch content</summary>

```
diff --git a/src/DFA.cc b/src/DFA.cc
index b9d62f8db..c2ac56b61 100644
--- a/src/DFA.cc
+++ b/src/DFA.cc
@@ -265,9 +265,9 @@ DFA_State_Cache::~DFA_State_Cache() {
 DFA_State* DFA_State_Cache::Lookup(const NFA_state_list& nfas, DigestStr* digest) {
     // We assume that state ID's don't exceed 10 digits, plus
     // we allow one more character for the delimiter.
-    auto id_tag_buf = std::make_unique<u_char[]>(nfas.length() * 11 + 1);
+    auto id_tag_buf = std::make_unique<char[]>(nfas.length() * 11 + 1);
     auto id_tag = id_tag_buf.get();
-    u_char* p = id_tag;
+    char* p = id_tag;
 
     for ( int i = 0; i < nfas.length(); ++i ) {
         NFA_State* n = nfas[i];
@@ -287,7 +287,7 @@ DFA_State* DFA_State_Cache::Lookup(const NFA_state_list& nfas, DigestStr* digest
     // HashKey because the data is copied into the key.
     hash128_t hash;
     KeyedHash::Hash128(id_tag, p - id_tag, &hash);
-    *digest = DigestStr(reinterpret_cast<const unsigned char*>(hash), 16);
+    *digest = DigestStr(reinterpret_cast<const char*>(hash), 16);
 
     auto entry = states.find(*digest);
     if ( entry == states.end() ) {
diff --git a/src/DFA.h b/src/DFA.h
index 1bf2979ec..0a7bb31da 100644
--- a/src/DFA.h
+++ b/src/DFA.h
@@ -2,7 +2,7 @@
 
 #pragma once
 
-#include <sys/types.h> // for u_char
+#include <sys/types.h>
 #include <cassert>
 #include <map>
 #include <string>
@@ -67,7 +67,7 @@ protected:
     DFA_State* mark;
 };
 
-using DigestStr = std::basic_string<u_char>;
+using DigestStr = std::basic_string<char>;
 
 struct DFA_State_Cache_Stats {
     // Sum of all NFA states
```

</details>

**Comment by awelzel** [comment]
> -using DigestStr = std::basic_string<u_char>;
> +using DigestStr = std::basic_string<char>;

Couldn't/shouldn't we go with std::string directly then, or am I being too naive?

I think for a 7.0.4 this could be okay.

@leres - would you be able to test patches?

**Comment by evantypanski** [comment]
> Couldn't/shouldn't we go with std::string directly then, or am I being too naive?

Probably, I just did the simplest thing possible for that patch (find+replace `u_char`->`char`) :)

I'm ok with it swapping to `std::string` there if it works. I also wondered if checking with a C++20 upgrade if `unsigned` works again it could be changed back, since `char8_t` gets a specialization, but that's not a big deal if it's the same behavior

**Comment by leres** [comment]
> > -using DigestStr = std::basic_string<u_char>;
> > +using DigestStr = std::basic_string;
> 
> Couldn't/shouldn't we go with std::string directly then, or am I being too naive?
> 
> I think for a 7.0.4 this could be okay.
> 
> @leres - would you be able to test patches?

Absolutely.

**Comment by leres** [comment]
> Hm, I'm not quite able to reproduce this, but it seems like Zeek is relying on a `uchar` specialization that [doesn't exist](https://en.cppreference.com/w/cpp/string/char_traits#Specializations) in the standard (though the `char8_t` one would probably suffice if we were on C++20).
> 
> If others can reproduce and verify that'd be nice, but if not, could you try this patch and see if it helps? It might need some touching up but this could check if my intuition is correct:
> patch content

(Your patch gives me similar errors as with unpatched 7.0.3)

**Comment by evantypanski** [comment]
@leres can you provide output for that patched run? There are a few ways it could be off and some would be easier than others. Just whatever errors/notes come up would work

**Comment by leres** [comment]
> @leres can you provide output for that patched run? There are a few ways it could be off and some would be easier than others. Just whatever errors/notes come up would work

I put a copy here: _[zeek-7.0.3.log](https://ee.lbl.gov/leres/scratch/zeek-7.0.3.log)_

**Comment by evantypanski** [comment]
@leres thanks a bunch, the patch may have fixed the issue, but now the issue appears in other files. It's just aborting early (and giving too many errors :/ )

Also: I just saw a note in the `SSL.cc` file with those errors that says `char_traits<unsigned char>` will be removed in LLVM 19. So this is definitely something we need to be cleaning up. I'll grab this for now and see if I can have something for you to check out again soon. Thanks for the logs and issue

**Comment by leres** [comment]
Confirming 562da9f fixes my issue. And I see github is fancy enough to notice that I pushed the fix to the security/zeek port.

Thanks for the fix!
