### ISSUE TITLE
Zeek renaming: internals (C++ / CMake)

### ISSUE THREAD

**Issue by jsiwek** [zeek/zeek#405]
The internal C++ source-code and CMake infrastructure have many uses of "bro" still, but not critical to change those for 3.0.  A good time to consider updating them is if/when we revamp the API we expose for plugins to use.

**Comment by timwoj** [comment]
I think with all of the changes from the namespacing work and PR #1144, all that's left here is bro_inet_ntop.h and all of the CMake stuff.

**Comment by rsmmr** [comment]
This could also come with a separate v2 plugin CMake API.

**Comment by timwoj** [comment]
After the above PR, the only things remaining are in the CMake modules. There's a plan to basically redo our CMake setup, so I'm going to close this out and we can revisit those namings in a separate issue/PR.
