### ISSUE TITLE
Test `core.expr-exception` reliably fails under ZAM with ASAN

### ISSUE THREAD

**Issue by bbannier** [zeek/zeek#4052]
The test `core.expr-exception` fails reliably under ZAM with ASAN due to [detected memory leaks](https://github.com/user-attachments/files/17830204/test.log), see e.g., https://cirrus-ci.com/task/6065381939347456.

**Comment by awelzel** [comment]
@vpax - mind referencing the issue number in a commit message (e.g `Fixes #4052`) once you get around poking at the `core.expr-exception` leak? Thanks!
