### ISSUE TITLE
Generic parsing for HTTP UPGRADE connections not containing sub protocols

### ISSUE THREAD

**Issue by blightzero** [zeek/zeek#4068]
The http_connection_upgrade() event and the websocket protocol parser allow the analysis of traffic in a websocket connection. However, some APIs do not use any particular protocol after an HTTP 101 UPGRADE response. For example the docker HTTP API makes a lot of use of HTTP upgrade messages to facilitate the interaction of the docker client and the docker server. The connection is upgraded and then the stdin and stdout/stderr of the respective program are connected via the established HTTP connection. This happens without any particular sub protocol in place that transports the data. There is currently no obvious way in zeek to further analyze or log events inside this stream.

One application of this would be docker honeypots where it would be great to analyze the interaction of actors with the docker container. For that it would be awesome if it was possible to extract and match the traffic using zeek.

The Upgrade response has Content-Type `application/vnd.docker.raw-stream` and the Upgrade protocol `tcp`:
![Screenshot from 2024-11-27 09-56-52](https://github.com/user-attachments/assets/94334876-bb09-40ef-9f83-6bb0fe5a4c39)

A minimal pcap with the respective HTTP UPGRADE and following interaction via the docker API can found in the attached pcap zip:
[docker_http_uprade.zip](https://github.com/user-attachments/files/17939740/docker_http_uprade.zip)

For further reference see slack discussion with @awelzel : https://zeekorg.slack.com/archives/CTGDG83B8/p1732622761199559

**Comment by awelzel** [comment]
@blightzero - I'm closing this after the inclusion of #4088 and your positive feedback on Slack. Please re-open if you end up having a more complex use-case.
