### ISSUE TITLE
Configure `ASAN_OPTIONS` for test suite with `address` sanitizer under macos

### ISSUE THREAD

**Issue by bbannier** [zeek/zeek#4078]
Large parts of the test suite fail when executing on macos due to ASAN diagnostics about e.g., container overflows. This comes out of a pretty standard build configured with `./configure --build-type=debug --sanitizers=address`.

The undocumented workaround is to set `ASAN_OPTIONS=detect_container_overflow=0` on macos so the test suite passes. We should automate this so the test suite behaves as expected by default.

**Comment by bbannier** [comment]
The default behavior caused confusion over in #4077.

**Comment by awelzel** [comment]
> The undocumented workaround is to set ASAN_OPTIONS=detect_container_overflow=0 on macos so the test suite passes.

It's documented in the ASAN wiki and rather discoverable: https://github.com/google/sanitizers/wiki/AddressSanitizerContainerOverflow#false-positives

This isn't just about macos, but might also happen on FreeBSD or Linux with libc++ and ASAN IIUC?

> We should automate this so the test suite behaves as expected by default.

This isn't just about the test suite though, is it? This would also crash for any bare zeek invocation and so devs/users will need to know how to set ASAN_OPTIONS.

I'm tempted to close this after fixing the test in question to include users's provided ASAN_OPTIONS rather than overriding - how would you feel about that?

```
diff --git a/testing/btest/spicy/type-converter.zeek b/testing/btest/spicy/type-converter.zeek
index 469a8c9008..19bb94ef3f 100644
--- a/testing/btest/spicy/type-converter.zeek
+++ b/testing/btest/spicy/type-converter.zeek
@@ -1,7 +1,7 @@
 # @TEST-REQUIRES: have-spicy
 #
 # @TEST-EXEC: spicyz -o test.hlto conv.spicy ./conv.evt
-# @TEST-EXEC: ASAN_OPTIONS='detect_odr_violation=0 detect_leaks=0' zeek -r ${TRACES}/ssh/single-conn.trace test.hlto %INPUT Spicy::enable_print=T >output
+# @TEST-EXEC: ASAN_OPTIONS="${ASAN_OPTIONS}:detect_leaks=0" zeek -r ${TRACES}/ssh/single-conn.trace test.hlto %INPUT Spicy::enable_print=T >output
 # @TEST-EXEC: btest-diff output

```

**Comment by bbannier** [comment]
> > The undocumented workaround is to set ASAN_OPTIONS=detect_container_overflow=0 on macos so the test suite passes.
> 
> It's documented in the ASAN wiki and rather discoverable: [Wiki: AddressSanitizerContainerOverflow (false positives) (google/sanitizers)](https://github.com/google/sanitizers/wiki/AddressSanitizerContainerOverflow#false-positives)

It is undocumented in the sense that "everybody" working on Zeek knows that for the test suite to pass with ASAN on macos one needs to set `detect_container_overflow=0`. Not having that automated makes it unclear which failures are expected. There is some of this in `.cirrus.yml`, but this is IMO only weak "documentation".

> This isn't just about the test suite though, is it? This would also trickle for any bare zeek invocation and so devs/users will need to know how to set ASAN_OPTIONS.

This seems to be secondary issue. Compiling automatic suppression into Zeek itself rather than e.g., setting it in `btest.cfg` would be great. There is also https://github.com/zeek/zeek/blob/master/testing/scripts/spicy/run-zeek which could be a useful wrapper, but it seems stale and unused (`auxil/broker` and `auxil/zeekctl` seem to use their own script).

> I'm tempted to close this after fixing the test in question to include users's provided ASAN_OPTIONS rather than overriding - how would you feel about that?

No strong feelings. IMO the current situation isn't ideal, but this obviously not a high priority issue.

**Comment by awelzel** [comment]
> No strong feelings. IMO the current situation isn't ideal, but this obviously is not a high priority issue.

I'm closing. The test has been fixed to not set ASAN_OPTIONS anymore.

This ticket (at least the subject) duplicates #3347 and with the reference they'll be linked.
