### ISSUE TITLE
Add Spicy to Coverity build

### ISSUE THREAD

**Issue by bbannier** [zeek/zeek#4103]
We currently disable Spicy for the Coverity build.

https://github.com/zeek/zeek/blob/1c42bfc7156800c1407d1487a80f3d8e00efda0e/.github/workflows/coverity-scan.yml#L46

As we move more analyzers in Zeek to Spicy we should add enable Spicy to get coverage. Ideally such a Coverity run would cover generated analyzers, as well as the runtime code the use.

**Comment by timwoj** [comment]
I'm fine with enabling it and seeing what we get out of it. Sadly we can't run it locally to test first.

> Ideally such a Coverity run would cover generated analyzers, as well as the runtime code the use.

I don't know how Coverity handles files that are created during the build process. It might just ignore them.

**Comment by rsmmr** [comment]
> I don't know how Coverity handles files that are created during the build process. It might just ignore them.

Don't fully remember but isn't it catching stuff in binpac-generated files? If so, we should get some coverage through the built-in Spicy analyzers in the same way.
