### ISSUE TITLE
Consider removing p0f support

### ISSUE THREAD

**Issue by rsmmr** [zeek/zeek#417]
The p0f engine that we're currently using in Zeek is very much outdated, and the signatures no longer maintained. It'd be great to switch this over to a current version, but it's unclear if that's viable given the p0f's structural changes. Either way, retaining the current version doesn't seem very useful at this point.

**Comment by 0xxon** [comment]
Removing p0f support is implemented in topic/johanna/gh-417-consider-removing-p0f. If we decide to remove it, that branch can be merged.
