### ISSUE TITLE
Add script-layer function overloading

### ISSUE THREAD

**Issue by jsiwek** [zeek/zeek#418]
It's been common for us to change event parameters (adding, removing, changing), but that always has the effect of breaking any user scripts that implement an event handler.

One idea was making handler arguments optional and matching them by name: #262.  Another I think was a more explicit event deprecation and overloading (as in function overloading) mechanism.

It would be nice for 3.0 to get a solution that gives a better migration path (user experience) than what we have now (which results in breaking people's code).

First step is to lay out concrete examples of what the migration path looks like with various proposed implementations, then compare/contrast.

**Comment by jsiwek** [comment]
Probably not worth it to re-hash the solution based on optional/named-matching of parameters.  It has merit, but either the syntax for event handlers is too similar to languages that require full/positional parameter set or the historical basis for the scripting language to only do positional matching made it feel odd to introduce a change at this late of a time.  Maybe still something to reconsider if ever starting a new version of the scripting language from scratch.

Here's the alternate deprecation strategy/solution based overloading:

# Use-Case: Adding an event parameter

## Step 0

`event foo(bar: bool)`

## Step 1

`event foo(bar: bool)`
`event foo(bar: bool, grault: string)`

Deprecation process done.

OR

`event foo(bar: bool) &deprecated`
`event foo(bar: bool, grault: string)`

User adapts their handler upon seeing deprecation warning and we later take a Step 2 to remove the deprecated version.

## Notes

There's not any real reason to introduce a deprecation here.  It only creates unnecessary work for users.
Maybe if number of overloads becomes excessive, then we deprecate the under-specified ones.

# Use-Case: Removing an event parameter

## Step 0

`event foo(bar: bool, grault: string)`

## Step 1

`event foo(bar: bool, grault: string) &deprecated`
`event foo(bar: bool)`

User adapts their handler on seeing deprecation warning.

## Step 2

`event foo(bar: bool)`

Deprecation process done.

# Use-Case: Changing a parameter's semantics

## Step 0

`event foo(wrong_semantics: bool)`

## Step 1

`event foo(wrong_semantics: bool) &deprecated`
`event foo(wrong_semantics: bool, fixed_semantics: bool)`

User adapts their handler on seeing deprecation warning.

## Step 2

`event foo(wrong_semantics: bool, fixed_semantics: bool) &deprecated`
`event foo(fixed_semantics: bool)`

User adapts their event *again*.

## Step 3

`event foo(fixed_semantics: bool)`

Deprecation process done.

## Notes

Potential pitfall if user "skips a version".  Maybe we can just have a policy of "don't ever do that without carefully reading release notes, or else whatever subtle problems occur are your own fault".

We could avoid the 2x user-annoyance if this could work at Step 1:

`event foo(wrong_semantics: bool) &deprecated`
`event foo(fixed_semantics: bool)`

But that requires inspecting/matching parameter names which seems like something we wanted to avoid.

# Use-Case: Combos (remove + add parameters simultaneously)

## Step 0

`event foo(bar: addr)`

## Step 1

`event foo(bar: addr) &deprecated`
`event foo(baz: string)`

User adapts their handler.

## Step 2

`event foo(baz: string)`

Deprecation process done.

# Implementation / Performance

Are we generally adding an overloading mechanism to each function flavor: function, hook, and event ?

I'd say yes.  Conceptually, we'd need hooks to support the same deprecation process as events, and overloading of functions is generally something that's familiar/useful to people.

We'll need to name-mangle the various function flavors.

  - At any "declaration site" (in scripts or bifs)

  - At any "call site" scripting expressions (includes various forms of
    generating events/hooks)

  - At any "implementation site" scripting expressions (function definition +
    event/hook handlers)

  - When inserting a function/event/hook ID into a Scope, we'd put both the
    unmangled name and the mangled name into the Scope.  Inserting the
    unmangled name is to prevent one from re-using that name for a
    non-function variable by mistake.

  - We have various internal lookup operations that search for functions by name
    that may need to change.  e.g. `EventRegistry::Lookup`, `Scope::Lookup`,
    `lookup_ID`.  We could keep using this same interface everywhere for the
    moment and just make such lookups fail if they would be ambiguous (we
    shouldn't have any such cases at the moment).  We could provide new APIs
    that map an unmangled name to all mangled names for use where it matters.

  - Our current event queuing logic looks like:

      ```c++
      if ( foo )
          QueueEvent(foo, arg1);
      ```

    For events that have no overloads, we can keep that the same, but for
    events that do have overloads, we can't generate `EventHandlerPtr` names
    that are as convenient to use (have to mangle). This may be ok, since overloading
    events isn't a common use-case, so for the few times we need it, we can do:

      ```c++
      vector<EventHandlerPtr> handlers = lookup_event("foo");

      for ( auto ehp : handlers )
          {
          if ( ! ehp ) continue;

          if ( ehp->FType()->Args()->NumFields() == 1 )
              QueueEvent(foo, arg1);
          else
              QueueEvent(foo, arg1, arg2);
          }
      ```

    The actual function signature inspection logic would vary depending on the
    circumstances.

    If we were to instead generally mangle arguments in order to automatically
    generate the right event(s), that possibly introduces run-time performance
    overhead.  Unless maybe we found a way macro or template-metaprogram a way
    to mangle event parameter types into the associated event handler at compile
    time. I imagine our types can get a bit complex and make that difficult.

# Other considerations

Don't think there's any conflicts with plugins.  If someone implements an overload in a plugin, that still goes through the same mangling/resolve process as if it were not in a plugin.

Missing anything?

**Comment by 0xxon** [comment]
Without going into the technical specifics - I like the way that the syntax looks for this way more - and the fact that it does allow deprecation warnings (e.g. when removing event parameters - which actually has happened a few times for me).

**Comment by rsmmr** [comment]
Me too. I like relying on relying on a combination of overloading and &deprecated.

I have a couple of thoughts on the use cases, but need to mull over that a bit more. And need to think through the implementation more, the mangling worries me a bit, that seems quite a complex change.

**Comment by rsmmr** [comment]
Couple more thoughts here:

- Jon and I discussed the implementation more the other day. It might be possible to avoid the mangling by allowing to associate an ID with more than one function, either directly within the scope or by extending functions to become containers of several versions (like we do with bodies already, but now including the function signature). Without anything further, that would incur a performance penalty because each call would now have to find out first which version to execute. However, I believe that could often be done statically at parse time and then cached along with the call.

- The "Changing a parameter's semantics" use case seems rate enough that I wouldn't worry much. In some cases that sequence might be fine; in others maybe we'd just rename the new event. Either way seems case by case.

**Comment by jsiwek** [comment]
> * by extending functions to become containers of several versions (like we do with bodies already, but now including the function signature). Without anything further, that would incur a performance penalty because each call would now have to find out first which version to execute. However, I believe that could often be done statically at parse time and then cached along with the call.

Trying out this approach most appeals to me:

* IDs continue mapping to a single function object

* Function objects change to contain a list of overloads

* Script-layer calls change to statically cache which function overload to use

* Core-layer calls can go unaltered if we leave current Call() API to just select the first overload (we can't possibly have more than one at the moment for any of those)

* Provide new core-layer API to actually be able to select an overload (e.g. by matching list of types)

* Adjust Zeekygen documentation output.  Two possibilities: (1) allow referencing overloads directly based on signature.  e.g. `` :zeek:see:`foo(int)` `` or (2) no change to referencing syntax, always generate the docs such that overloads are grouped with each other, referencing the function name takes you to its full group of overloads.  Option (2) is easier, as fully specifying various composite types in a function signature can get crazy real quick.

**Comment by rsmmr** [comment]
Option (2) on the docs sound good to me, plus skipping any &deprecated versions from being documented.

**Comment by jsiwek** [comment]
I'm putting my work toward adding function overloading on hold for while, so just making a few notes in case someone else comes along to try to finish the project:

Initial implementation of just script-layer *function* overloading is in branch `topic/jsiwek/gh-418-add-function-overloading`.  I have more complete notes on the remaining tasks that need to be done, but the main areas are:

* Add *event* overloading (this maybe the hardest part as the internal API needs to change a bit to now deal with event names possibly mapping to more than one function)
* Add *hook* overloading
* Add overloading support for BIFs
* Serialization: on receiving a function from remote peer, functions/events currently lookup by just name, so we'd need to extend that code to also match argument types or else add an "overload index" to the serialization

**Comment by jsiwek** [comment]
I have general worries about hook/event overloading.  We originally focused on using it as a way to improve the "deprecation process" use-case, but would not be worthwhile if found to be unusable in more general usage, so below are such examples showing off the oddity of hook/event overloads (done all in script-land, but same logic still extrapolates for core-generated events).

Remember that the usage pattern of hook/event is an inverse of what we're used to with function usage patterns -- the pattern for function usage is "the implementation already exists, you write the calls" but the pattern for hook/event usage is "the calls already exists, you write the implementation".  So if one wants to add overloads for a hook/event, all the calls must exist and you get this pattern at call sites:

```zeek
# Generating all overloads of event "foo"
event foo();
event foo(qux);
event foo(qux, grault);

# Generating all overloads of hook "bar"
hook bar();
hook bar(qux);
hook bar(qux, grault);
```

Those call sites are already a bit awkward on at the superficial level: for each overload, the generating/call site lists out all possible overloads (contrasted with more-familiar function overloads, where caller chooses the single overload that is most convenient).  However, the more important problem is that `&priority` semantics are broken.  Here's someone trying to handle overloads:

```zeek
event foo(qux: string) &priority=10
    { ... }
event foo() &priority=0
    { ... }
```

What's the execution order?  I expect the no-args `foo` handler to be first despite lower priority since it's "generated" earlier, but it's ambiguous/confusing.  It's not only difficult for users to understand the ordering, but particularly for the deprecation use-case, a user could have been depending on the original event ordering and we'd likely break that usage upon introducing an overload.

Maybe we could extend the logic of event dispatch/queue to "merge" sequential overloads and interleave them based on `&priority`, but that's not possible in any generalized way, especially for hooks where it's essential to know if the the first call to an overload is part of a "sequence" of overload calls. 
 Hooks also return a value for caller to potentially act upon, making them more awkward and fragile. 
 Statically "merging" a sequence of hook overloads to interleave priorities likely isn't going to happen for arbitrary ASTs.

Shifting back to address original problem of potential improvements to deprecation process: we need a way to change hook/event parameters in a way that doesn't alter semantics of the global event stream (or hook chain) and we need consumers with ability to be resilient to those parameter changes (e.g. if they can elect which parameters they want to consume).  An example implementation for that behavior is the previous suggestion at #262, which was closed since several people thought handlers omitting parameters could be confusing since it's not-similar to *function* syntax of other familiar languages.  I'd remind/argue that these are not *functions*, they are called *hook* or *event* and already differ in behavior and usage pattern, so may not be too surprising if parameter listings/signatures also operate a bit differently.  Also this really is it's own independent language and may be ok to deviate from others when beneficial.  If we still can't get past that, it's fine, but think it's a matter of *how* we implement the solution, not the solution itself that ought to change.  E.g. can look at alternate implementation for "handlers elect which parameters to consume" behavior, but with the syntax changed to explicitly deviate from the familiar function syntax.

Back to general usage of *hook* or *event* overloading: I expect they'll be more confusing than useful, so suggest not adding that feature.  Even for things already at different points in the global event stream, it would be confusing to use an overload -- since the semantics are already different, just pick a different name for the event.

As for *function* overloading: still sounds ok to add that feature, but can be a separate treatment.

Shorter summary/breakdown of my thoughts:
* function overloads: yay
* event/hook overloads: nay
* improve event/hook deprecation process: possibly revisit #262 w/ alternate handler syntax

In any case, I don't plan on pursuing this in near-term, but nice to hear other ideas/opinions on the situation.

**Comment by rsmmr** [comment]
Reading through your notes, @jsiwek, I agree on not overloading events and hooks, for all the reasons you mention. 

Mulling over this more, I had another idea for addressing our original use-case of making backward-compatible event changes, which would be hybrid of the two things we discussed so far: 1. your name-based matching, and the 2. overloading. This would go as follows:

- We implement the name-based matching as you have described & prototyped, using exactly the runtime semantics that you have proposed (allowing parameters to be missing and/or reordered).

- However, we do not allow any arbitrary combinations of parameters for an event handler, but only versions that have explicitly been prototyped as an overload of the event. That way, it's very explicit which versions of the event are available/supported, and we can document them separately through Zeekygen. And and overloaded prototype can use `&deprecated` to signal it'll be going away.

Example for adding a parameter:

### Original version

Prototype:

`global foo: event(bar: bool);`

User handler:

`event foo(bar: bool)` { ... }

### Updated version

Prototype:

`global foo: event(bar: bool);`
`global foo: event(grault: string, bar: bool);`

User handler:

`event foo(bar: bool)` { ... }

So the handler will just keep working because we're doing name-based arg matching across the two available prototypes. If the old version had a `&deprecated` now, the user would get warning.

However, the user cannot define a handler that's not been prototyped. E.g., `global foo: event(bar: bool, grault: string);` would be rejected (at compile time; the runtime code would actually handle it if we left it through).

**Comment by jsiwek** [comment]
@rsmmr that's a real neat idea and think it's workable since it's only additional parse-time type-checks with everything still resolving to a single, canonical event to dispatch.  But since the extra layer about requiring explicit prototype-overloads is less about solving a technical problem and more about solving a human preconception problem, I want to poke further to see if it generates anything useful:

### Deprecations

If we're just making new data available in the event like these:

```zeek
global foo: event(bar: bool);
global foo: event(grault: string, bar: bool);
```

I suppose we're not too motivated to ever deprecate in those cases and allow users to continue using the old prototype?  Or do we try to keep number of prototypes to a minimum?

For the case where we actually want to change/remove some parameter but also add others, it's unclear whether we do:

```zeek
global foo: event(bar: bool) &deprecated;
global foo: event(grault: string, bar: bool) &deprecated;
global foo: event(grault: string);
```

or just:

```zeek
global foo: event(bar: bool) &deprecated;
global foo: event(grault: string);
```

The later is probably fine, but contrast with what we can do without requiring the explicit prototype-overloads to type-check against:

```zeek
global foo: event(grault: string, bar: bool &deprecated);
event foo(grault: string) { ... }
```

A bit simpler/clearer since deprecating at parameter-level rather than event-level better matches the real intent.  More of a "just saying" than a showstopper realization.

### Unintended user extensibility?

> However, the user cannot define a handler that's not been prototyped. E.g., `global foo: event(bar: bool, grault: string);` would be rejected (at compile time; the runtime code would actually handle it if we left it through).

I didn't follow that, can you clarify?  You said "the user cannot define a handler", but the "e.g." that follows shows a prototype, not a handler, and if it were changed to a handler, that actually would be valid since it's just re-ordering parameters of a prototype given in earlier example.  So didn't track if there was something to be said about limiting re-ordering, not allowing prototype-overloads with params that form disjoint sets (agree that would be required), or something about what "users" are actually allowed to define.

Regardless, the last point is interesting to work through on its own -- I don't think we have any way to limit what overloads a user adds.  Limiting to BIF-only doesn't help because of plugins, and well, we probably do want this to extend to script-layer events/hooks anyway in case we need it.  So given that users can define their own prototype-overloads for anything, are we cool with them doing this:

```zeek
# I don't need all those params from the version defined in http/events.bif ...
global http_request: event(c: connection, version: string);
event http_request(c: connection, version: string) { ... }
```

What if they use a tool to auto-generate every valid prototype for all events?  What if we use the tool to provide all prototypes for things we ship? Those are rhetorical, but start to wonder about the value of implementing such a limitation if it's completely and ultimately circumventable.

None of that is against this approach if the value is in another area, like playing to preconceptions, but I guess just points out again that the limitation is "artificially" added without intent to solve a technical problem and so maybe no surprise there is a technical way to bypass it.

**Comment by rsmmr** [comment]
> I suppose we're not too motivated to ever deprecate in those cases and allow users to continue using the old prototype? Or do we try to keep number of prototypes to a minimum?

Case-by-case decision I think but I'd bias towards minimizing and deprecating the old one, mainly to avoid these alternative versions to proliferate over time. I prefer having a canonical version of an event.

> ```zeek
> global foo: event(bar: bool) &deprecated;
> global foo: event(grault: string);
> ```

This is interesting, I didn't even think about it, but I like it, because it gives us a way to complete change an event's signature without breaking things for a while. And I don't think it's a drawback that we need to deprecate a whole prototype instead of just a parameter.

> I didn't follow that, can you clarify? You said "the user cannot define a handler", but the "e.g." that follows shows a prototype, not a handler,

Sorry, copy/paste error, it was meant to be handler, not prototype.

> and if it were changed to a handler, that actually would be valid since it's just re-ordering parameters of a prototype given in earlier example.

Actually reordering wouldn't be allowed for a handler, the handler needs to match one of the prototypes exactly.

> Regardless, the last point is interesting to work through on its own -- I don't think we have any way to limit what overloads a user adds.

Yes, correct, a user can get around these restrictions by adding their own prototype. I'm not worried about that, I don't see a need for fully policing this. One could even argue that once it's prototyped, that's completely fine because then intent is expressed; no matter where the prototype comes from.

**Comment by jsiwek** [comment]
Thanks, it's starting to sound like a ways forward, but just checking what you think about the wrinkle of user-generated event "calls" ?  Like this could be what exists:

```zeek
global foo: event(bar: bool);
event zeek_init()
    { event foo(T); }
```

And then upon changing the event, the "call" site is now broken since it doesn't emit all necessary parameters.

```zeek
global foo: event(bar: bool);
global foo: event(grault: string bar: bool);

event zeek_init()
    { event foo(T); } # needs to be updated to emit the full parameter set
```

That's not anything introduced by what you suggested, just I didn't even originally think much of that, and want to check if you think it's an acceptable breakage (I do).  If a person is in control of changing an event's parameter set , they are usually also the person in control of the call sites and will change both locations at the same time.  So "event producers are expected to break on parameter changes and event consumers remain compatible".

**Comment by rsmmr** [comment]
Good point, I hadn't really thought about that either.  I don't see a way to avoid that breakage, no matter what our solution is (because, as you say, it's all about the receiving end). So, yes, I think that's acceptable / out of scope.

**Comment by jsiwek** [comment]
@vpax if you get a chance to review Robin's idea in https://github.com/zeek/zeek/issues/418#issuecomment-600497140, would be great to hear if you think of any concerns.  I'll likely try implementing this week.

**Comment by vpax** [comment]
@jsiwek do you mean specifically the proposal in https://github.com/zeek/zeek/issues/418#issuecomment-600497140, or do you mean including the lengthy follow-on discussion that talks about variants?

**Comment by jsiwek** [comment]
> @jsiwek do you mean specifically the proposal in [#418 (comment)](https://github.com/zeek/zeek/issues/418#issuecomment-600497140), or do you mean including the lengthy follow-on discussion that talks about variants?

@vpax That particular comment should capture the entire plan.  The follow-on discussion may be interesting if you want to read, but it didn't result in any revisions.  Gist of the proposed change is to allow declaring multiple event prototypes for a given event name:

```zeek
global foo: event(bar: bool);
global foo: event(grault: string, bar: bool);
```

Then allow handlers to use either prototype (enforced by parse-time type-checking).

```zeek
event foo(bar: bool) { ... }
event foo(grault: string, bar: bool) { ... }
# Those are the only two ways we allow handlers for `foo`, unless someone explicitly
# adds another prototype for other arguments (or argument ordering).
```

The thing that "generates" those event calls (often the internal event engine) will have to provide the full argument set/union needed for calling any particular handler, but that's fine for the scenarios we imagine: extending/deprecating event parameters without breaking user handlers.

**Comment by vpax** [comment]
Whoops meant to follow up sooner - yes, I'm good with the proposal.

**Comment by rsmmr** [comment]
The proposed event overloading mechanism went in, which seems was the main goal of this ticket (despite the more generic title "function overloading").
