### ISSUE TITLE
Documentation Bug for Intel Item Expiration

### ISSUE THREAD

**Issue by grigorescu** [zeek/zeek#427]
I was recently debugging a problem, and looked at the documentation for Intel::item_expiration:

https://docs.zeek.org/en/latest/scripts/base/frameworks/intel/main.zeek.html#id-Intel::item_expiration

The documentation states it has a default of 10 mins, but I think that's only the case if do_expire.zeek is loaded, which, AFAICT, is not in init-default. I think the correct default is disabled (-1 minute).

Are there other documentation bugs of this nature, where a policy script that's not being loaded by default is overriding a correct default?

**Comment by jsiwek** [comment]
It's maybe uncommon to declare an option and redefine it in a policy script, but yeah, the generated docs will load everything and display whatever the final value is after parsing.  Should be possible to change it to track and display all possible values along with the script that makes modifications.
