### ISSUE TITLE
Remove the list type?

### ISSUE THREAD

**Issue by grigorescu** [zeek/zeek#432]
Should the list type be removed? From what I can tell, it's just:

```
TOK_LIST
				{
				set_location(@1);
				// $$ = new TypeList();
				reporter->Error("list type not implemented");
				$$ = 0;
}
```

**Comment by jsiwek** [comment]
I suppose it can serve to reserve `list` as a keyword for if we ever do implement it.  Not far-fetched that we'd potentially want it later, so seems fine to leave be.
