### ISSUE TITLE
RPC analyzer can crash on bad RPCs

### ISSUE THREAD

**Issue by vpax** [zeek/zeek#435]
There are code paths in `RPC_Interpreter::DeliverRPC` (in `src/analyzer/protocol/rpc`) that can de-reference a null pointer (`buf`) in the face of errors.  One of these is from the call to `RPC_BuildReply` returning an error, which leads to a `bad_RPC` weird but doesn't return at that point.  The failed call can have set `buf` to null, and then the later test `if ( *buf != 0 )` attempts to dereference that null pointer, crashing.

**Comment by jsiwek** [comment]
@vpax Thanks, would be great if you're able to verify the patch:

https://github.com/zeek/zeek/commit/8cb8c83daff576d739da8c7b856fe99e84bbd298

**Comment by vpax** [comment]
@jsiwek Yep that fixes it for me, thanks!
