### ISSUE TITLE
Zeek regular expression consumes a lot of memory

### ISSUE THREAD

**Issue by shuaidonga** [zeek/zeek#450]
After writing a zeek regex that matches the phone number, the zeek work consumes a huge increase in memory.
The following is my matching regular expression script
![image](https://user-images.githubusercontent.com/16378509/60477101-b23c8a80-9cb0-11e9-93eb-4aacb5d1f8a8.png)
![image](https://user-images.githubusercontent.com/16378509/60477124-c54f5a80-9cb0-11e9-98a4-49c816f436ec.png)
The above processing will consume a lot of memory, is there any good solution?

**Comment by ZekeMedley** [comment]
Sorry about the high memory use. If the pattern matching is really what is so expensive, some quick thoughts:

1. I'd imagine that the event `http_message_done` is happening with some frequency. Even if the pattern matching is fairly low cost, that cost could add up if you're doing it every time a http message finishes. Maybe there is a way you could narrow that down?

2. In `assert_num11_not_contain_num12` could you just match against `/[0-9]{11}([^0-9]|$)/`? My regex is a little rusty, but the idea there is to match against 11 numbers and then something else or the end of the text. That way you don't have to check for an 11 digit number and then a 12 digit one. You could also try and just add a check like that to the end of your `mobile_regex` and then match that against the response body.

**Comment by JustinAzoff** [comment]
Can you attach those files as text instead of images?

**Comment by shuaidonga** [comment]
@JustinAzoff  ok

**Comment by rsmmr** [comment]
Closing, as it's a primarily a usage question. Internally, things quite likely won't change before #426 gets figured out.
