### ISSUE TITLE
HTTP.log MIME type "x-msdownload" missing?

### ISSUE THREAD

**Issue by Crypto-Cat** [zeek/zeek#454]
Hi,

When reading a PCAP with Zeek, the HTTP log field for 'resp_mime_types' does not always populate.

In the example I'm using, the MIME types for all HTTP log entries are shown correctly except for 'application/x-msdownload' are displayed correctly. I've verified the PCAP manually and the MIME type is definitely displayed there without correctly.

Any ideas?

Thanks,
Crypto

**Comment by jsiwek** [comment]
The `resp_mime_types` field is populated by matching the actual content against a set of signatures:

https://github.com/zeek/zeek/tree/002109973dbb2b86cf9b0be0a85797c5feba5a4e/scripts/base/frameworks/files/magic

We don't have an `application/x-msdownload` type there.  We do have a `application/x-dosexec` -- is the file format any different from that ?  What's the actual output you get ?  Is just not detected as any MIME type or just something other than you expect ?  Best if you can provide the pcap.

Also, how were you manually verifying the MIME type in your pcap ?  If it's via Content-Type header, I mentioned we use another method to populate `resp_mime_types`, although you can write your own custom Zeek script to use the `http_header` event if you wanted.

**Comment by Crypto-Cat** [comment]
Hi,

It is indeed from Content-Type HTTP header, I'll write a script for it. 

Thanks,
Crypto
