### ISSUE TITLE
known-services missing some DNS connections?

### ISSUE THREAD

**Issue by mauropalumbo75** [zeek/zeek#455]
I believe some DNS are missing in the known-services log because of this if statement:

                if ( "DNS" in c$service && c$resp$size == 0 )
                        # For dns, require that the server talks.
                        return;
                }

in the script known-services.zeek. The above if statement is called sometimes after protocol confirmation and before the field c$resp$size is properly filled some time later for each connection.  I attach a couple of pcap files where the problem occurs.

[dns-caa.pcap.gz](https://github.com/zeek/zeek/files/3367290/dns-caa.pcap.gz)
[http.cap.gz](https://github.com/zeek/zeek/files/3367291/http.cap.gz)

I am not sure there is an easy fix for this. I doubt trying to fill c$resp$size earlier in a connection lifetime is the right way to go.  Alternatively, one can log known-services for DNS only when the  connection ends (using the event connection_state_remove), but in this way it would be logged quite later...

**Comment by jsiwek** [comment]
Since that specific behavior, "For dns, require that the server talks", isn't what you expected, I'd suggest just making that an option, so we can keep the intended/default behavior and still allow you to customize.  Either let us know if the following patch works for you, or go ahead and make a PR for it:

```
diff --git a/scripts/policy/protocols/conn/known-services.zeek b/scripts/policy/protocols/conn/known-services.zeek
index 24774586d..db9cee9e9 100644
--- a/scripts/policy/protocols/conn/known-services.zeek
+++ b/scripts/policy/protocols/conn/known-services.zeek
@@ -58,6 +58,10 @@ export {
        ## :zeek:see:`Known::service_store`.
        option service_store_timeout = 15sec;

+       ## For DNS, require that the server has responded before logging it
+       ## as a known service.
+       option dns_requires_response = T;
+
        ## Tracks the set of daily-detected services for preventing the logging
        ## of duplicates, but can also be inspected by other scripts for
        ## different purposes.
@@ -181,7 +185,8 @@ function known_services_done(c: connection)
                        # Don't include ftp data sessions.
                        return;

-               if ( "DNS" in c$service && c$resp$size == 0 )
+               if ( "DNS" in c$service && c$resp$size == 0 &&
+                    dns_requires_response )
                        # For dns, require that the server talks.
                        return;
                }
```

**Comment by timwoj** [comment]
@mauropalumbo75 Did the above patch work for you?

**Comment by timwoj** [comment]
Given that almost two years has gone by without any response from the original reporter, I'm considering just closing this one out.
