### ISSUE TITLE
Support UTF-8 in ASCII logs

### ISSUE THREAD

**Issue by timwoj** [zeek/zeek#458]
As a follow-on to the work for #150, we should also support UTF-8 output in regular ASCII logs.

**Comment by devbali** [comment]
I can give this a stab, since this is not a show-stopper. You are talking about simply escaping utf-8 in logs, as enabled by customisation features from zeek scripts?

**Comment by 0xxon** [comment]
Probably the other way round - currently UTF8 is always escaped in log-files. Not escaping valid UTF8 would be the new feature.

**Comment by timwoj** [comment]
@devbali I'm just waiting on the JSON stuff to land that's in PR. There's already a method there to do the escaping so it should just be a matter of calling it from the right places in the ASCII logger.

**Comment by devbali** [comment]
The issue with non ASCII text was the `std::isprint` method being called in the `ODesc::FirstEscapeLoc` method. This returns false, and results in a series of procedures that break the unicode structure into the \x format. The ASCII log  can we remove checking for `std::isprint` in the first place, which is just a method to check if a character is ASCII?

**Comment by rsmmr** [comment]
> into the \x format. The ASCII log can we remove checking for
> `std::isprint` in the first place, which is just a method to check if
> a character is ASCII?

We probably can't completely remove it, but we could replace it with a
check wether it's a valid UTF8 code point.

Robin

-- 
Robin Sommer * Corelight, Inc. * robin@corelight.com * www.corelight.com

**Comment by devbali** [comment]
Yeah, I did not know about the byte data type in zeek. I am adding that into the current set up right now.

**Comment by timwoj** [comment]
@rsmmr There was some chatter in slack about it. We decided was to just remove the escaping altogether for ascii logs, since it would already be escaped by the utf8 method. It needs heavy testing though to make sure it didn't break anything.

**Comment by devbali** [comment]
Pull request opened: https://github.com/zeek/zeek/pull/482

**Comment by jsiwek** [comment]
Now implemented/merged via #482
