### ISSUE TITLE
expire_func lacks type-checking

### ISSUE THREAD

**Issue by vpax** [zeek/zeek#460]
The following script type-checks when it shouldn't:

`global b: function(s1: string, s2: string): interval;`
`global a: table[addr] of count &create_expire=1sec &expire_func=b;
`

**Comment by ZekeMedley** [comment]
This should probably happen here :) there is a nice example for `&default` above.

https://github.com/zeek/zeek/blob/c22edc28a5dc3e9469ff67dc30d978770d914d29/src/Attr.cc#L453

**Comment by 0xxon** [comment]
Fixed via https://github.com/zeek/zeek/pull/473
