### ISSUE TITLE
expire_func unhelpful for containers with multiple indices

### ISSUE THREAD

**Issue by vpax** [zeek/zeek#461]
The current type-checking requires that `&expire_func`'s take exactly two arguments, the first being the container itself, and the second being the index into the container corresponding to the expiring element.  This restriction means that you can't use `&expire_func`'s in any sort of flexible way for containers with multiple indices.

A work-around is to change the container to be indexed by a record instead (ugh).

**Comment by ckreibich** [comment]
I think there's an asymmetry here between how we can spell out a tuple of values vs. a tuple of types. For the former, ee can use the `[...]`-notation in for-loops over key/val pairs, or keys that are tuples (see [discussion here](https://github.com/zeek/zeek/issues/154#issuecomment-470740595). That is, we can say

    for ([i, j] in something)

when that something is e.g. a `set[count, count]`, but we don't have a similarly convenient way of saying that an argument to a function is a `[count, count]`.

If the solution here is that we unpack the tuple into multiple arguments to the `&expire_func`, then that's in a way making things more asymmetric. Seems it would be nicer to make such tuples explicit, so they can be passed in as a single argument. I'm not immediately sure what that should look like. Perhaps something like `function foo(..., val: [count, count])`, with vector-style numeric indexing to get the individual vals.

**Comment by vpax** [comment]
@ckreibich nice thought!  Not sure though how much work it might wind up being, to do this coherently.

**Comment by rsmmr** [comment]
Might be easier to implement unpacking outside of function arguments, like through locals like this:

```
   local [x, y] = val;
```

**Comment by ZekeMedley** [comment]
I thought about this a today [here](https://github.com/zeek/zeek/tree/topic/zeke/value-unpacking) and got this working:

```zeek
local [x, y: vector of count, z] = ["dog", [1, 2, 3], 3];
print x, y; # dog, [1, 2, 3], 3
```

The natural extension here is for value unpacking to work for vectors and arguments to functions. I'm beginning to think though that the best solution here is just to let `&expire_func` take more than one argument. That's how `&default` works at the moment and afik that actually gets used places in people's Zeek scripts.



Actually implementing that shouldn't be particularly difficult. Just need to perform the same move that we do in `&default` [here](https://github.com/zeek/zeek/blob/50e4da74cf33750d6ffbcdb7af7ae02d9edae9ab/src/Val.cc#L1770).
