### ISSUE TITLE
post-terminate-logger folder

### ISSUE THREAD

**Issue by DaemonShao** [zeek/zeek#466]
Under the zeek spool/tmp folder, a lot of folders like post_terminate-logger-2019-** are generated. How does this happen? How to solve it?

**Comment by 0xxon** [comment]
Hi,

I think that these are kept around when a process crashes (@JustinAzoff might be able to correct me on that one).

Hence - perhaps investigate if there are instances that keep crashing.

**Comment by rsmmr** [comment]
Closing due to no more follow-up.
