### ISSUE TITLE
Segfault when calling redef on a variable without a value

### ISSUE THREAD

**Issue by timwoj** [zeek/zeek#467]
From https://github.com/zeek/zeek/issues/157#issuecomment-509815197:

> An example similar to what's in the original report does segfault:
> 
> ```
> global a: count &add_func = function(): count { return 3; };
> redef a += 13;
> print a;
> ```
> 
> Could either fix that as part of this issue or separately, since not sure it's just type-checking problem or a problem with redefing something that has no initial value (or combination). E.g. this one gives a "argument type mismatch error":
> 
> ```
> global a: count = 1 &add_func = function(): count { return 3; };
> redef a += 13;
> print a;
> ```
> 
> Which seems like the right behavior (except maybe message could be more descriptive) because the actual function should be:
> 
> ```
> global a: count = 1 &add_func = function(old: count, new: count): count { return 3; };
> redef a += 13;
> print a;
> ```

**Comment by 0xxon** [comment]
There seem to be two things here.

Redef-ing a variable without an initial value actually seems like it should be fine - when the redef just does a normal assignment. +=, etc obviously cannot work.

An &add_func only seems to make sense when there is an initial value - otherwise there is no "old".
