### ISSUE TITLE
Dictionary timing measurements

### ISSUE THREAD

**Issue by timwoj** [zeek/zeek#472]
I started looking into converting the `Dictionary` class into more of a template the other day similar to the recent work for `List` and `Queue`. This led me to a lot of questions about the implementation and some discussion in Slack about rework of the class and timing issues.  Below are some benchmarks of `Dictionary` against `std::map` and `std::unordered_map`, in order to get a sense of what the actual performance differences are.

The primary reason for the way `Dictionary` is implemented is to avoid a spike in CPU usage when the dictionary needs to be resized. It's implemented as a set of two `List`s of buckets based on `HashKey`s. When a resize occurs, it spreads the actual resize process over a span of time instead of doing all of the resize all at once. `std::unordered_map` is typically implemented as a hash table of buckets based on the key, similar to `Dictionary`. The main difference is that `unordered_map` will do the entire resize at once so you see the timing hit as it resizes. `std::map` is typically implemented as a tree (usually red-black trees) based on a hash of the key.

The graphs below are for inserting 1000000 elements into each of the tables. For `map` and `unordered_map` the key is an `int` and value is an `int*`. For `Dictionary`, it uses a PDict where the key is a `HashMap` containing an `int` and the value is an `int*`. The graphs are the time (in microseconds) it takes to insert each element, measured by `clock_gettime`, plotted by python's `matplotlib`.

Note that these graphs are for inserts only and don't measure any of the other operations on the tree, but inserts are where the primary complication of `Dictionary`'s implementation lies.

### `Dictionary`

```
coregeek:dict testing tim$ time ./a.out d
Dictionary
real	0m1.758s
user	0m1.697s
sys	0m0.057s

Average operation time (us): 1.389912
Max operation time (us): 1734
```

![dict](https://user-images.githubusercontent.com/2653616/61395059-64f81580-a879-11e9-8a79-ae08ce6759ba.png)

### `map`

```
coregeek:dict testing tim$ time ./a.out r
std::map
real	0m2.015s
user	0m1.733s
sys	0m0.276s

Average operation time (us): 2.226538
Max operation time (us): 68
```

![map](https://user-images.githubusercontent.com/2653616/61484543-fd62c880-a953-11e9-9fc4-c91acfcdae7f.png)

### `unordered_map`

```
coregeek:dict testing tim$ time ./a.out u
std::unordered_map
real	0m1.088s
user	0m0.806s
sys	0m0.277s

Average operation time (us): 1.266901
Max operation time (us): 98
```

![umap](https://user-images.githubusercontent.com/2653616/61484559-02277c80-a954-11e9-9c6e-cfc34e22192f.png)

Timing code: [test.cc.txt](https://github.com/zeek/zeek/files/3408047/test.cc.txt)
Plotting code: [plot.py.txt](https://github.com/zeek/zeek/files/3403022/plot.py.txt)

**Comment by timwoj** [comment]
@JustinAzoff asked in Slack whether we had any benchmarks for creating/destroying small Dictionaries, so I added that below. The data below is for creating 1000000 3-element `std::map` and `Dictionary` objects and deleting them in between each creation. I didn't create graphs for these.

### `Dictionary`

```
real	0m2.548s
user	0m2.489s
sys	0m0.048s
```

### `std::map`

```
real	0m1.410s
user	0m1.174s
sys	0m0.230s
```

**Comment by rsmmr** [comment]
Interesting, nice plots!

**Comment by timwoj** [comment]
Just for comparison I ran a graph of the `Dictionary` data, removing any point > 100us. This forces the lower points to become more pronounced and gives an easier comparison to the individual inserts against `map`.

```
Average operation time (us): 1.383076
Max operation time (us): 76
```

![dict trimmed](https://user-images.githubusercontent.com/2653616/61483321-70b70b00-a951-11e9-98b0-f341acfa06a5.png)

**Comment by timwoj** [comment]
@JustinAzoff pointed out that the code for `map`/`unordered_map` might be slightly faster due to the fact that I'm storing pointers in Dictionary but regular ints in the other two, and the call to `new int()` may be skewing the data. I fixed the code to store `<int,int*>` and updated the graphs/text in the original post.

It definitely was definitely skewing the data, with the runtime for both going up about 400ms and the average operation time going up slightly.

**Comment by timwoj** [comment]
Both @rsmmr and @JustinAzoff mentioned that some benchmarks for lookups would be useful. These are containers using `const char*` keys and `int*` values. The code creates the map, and then times how long it takes to look up each key in reverse order of creation, run 5 times in a row.

### `Dictionary`

```
Time for 50 lookups (us): 21000
Time for 50 lookups (us): 15000
Time for 50 lookups (us): 15000
Time for 50 lookups (us): 15000
Time for 50 lookups (us): 14000
```

### `std::map`

```
Time for 50 lookups (us): 13000
Time for 50 lookups (us): 13000
Time for 50 lookups (us): 13000
Time for 50 lookups (us): 12000
Time for 50 lookups (us): 11000
```

### `std::unordered_map`

```
Time for 50 lookups (us): 9000
Time for 50 lookups (us): 9000
Time for 50 lookups (us): 9000
Time for 50 lookups (us): 9000
Time for 50 lookups (us): 9000
```

**Comment by rsmmr** [comment]
Nice. Clear win all around.

**Comment by timwoj** [comment]
As I started working on this in further detail, one benchmark missing above is when the key is a complex object such as in the case of connections that have two IPs and two port numbers. 

With the old `Dict` code, a lookup loops through all of the elements in the list and compares them one at a time using `memcmp` against the provided `HashKey`. For `std::map` the comparison uses `std::less` and the `operator<` method defined for the complex object. Since the map is likely implemented as a tree, we'd expect the searching to be faster than linear time. Depending on the speed of the `operator<` method, this ought to be faster than `Dict`. For `std::unordered_map` it's just a comparison against the hash of the object, however that is calculated, and also faster than linear time depending on how the hash table is implemented.

The test below is the same as the regular test at the start of the GHI, where we insert 1000000 elements into a container. This causes at least one comparison for every inserted object. I didn’t add `fifo_map` tests because earlier testing showed that it was slow enough to be unusable. Surprisingly, `unordered_map` is slower than `std::map` here. I’m not sure if that’s because of the slowness of creating the hashes for the elements vs just inserting them directly.

### `Dictionary`

```
real	0m1.968s
user	0m1.903s
sys	0m0.058s

Average operation time (us): 1.517161
Max operation time (us): 100
```

![Screen Shot 2019-07-31 at 10 48 26 AM](https://user-images.githubusercontent.com/2653616/62234998-c0013080-b380-11e9-8d31-265b58695058.png)

### `std::map`

```
real	0m1.506s
user	0m1.248s
sys	0m0.252s

Average operation time (us): 1.546464
Max operation time (us): 73
```

![Screen Shot 2019-07-31 at 10 47 30 AM](https://user-images.githubusercontent.com/2653616/62235005-c4c5e480-b380-11e9-9c1a-1530c321e398.png)

### `std::unordered_map`

```
real	0m1.755s
user	0m1.459s
sys	0m0.286s 
Average operation time (us): 1.444918
Max operation time (us): 96
```

![Screen Shot 2019-07-31 at 10 48 08 AM](https://user-images.githubusercontent.com/2653616/62235011-c8f20200-b380-11e9-9a6d-cd5e716e5073.png)

**Comment by timwoj** [comment]
@jsiwek [brought up](https://github.com/zeek/zeek/pull/495#issuecomment-516619643) the following on the PR for simple types:

> Generally, I think this is the decision process I use:
> 
> - Need ordering: use map
> - Don't need ordering, not on perf. critical path: still use map
> - Don't need ordering, on perf. critical path: measure if unordered_map is better and use it if so
> 
> Reason for needing measurements is it's not always intuitive that unordered will be better. E.g. commonly suspect small unordered-maps with long string keys actually may have hash operations which end up causing worse lookup performance than ordered-map. Memory usage differences could be another consideration to add even more nuance.

I think that last paragraph matches the above benchmarks. `unordered_map` is definitely slower than prior benchmarks once larger keys are used.

**Comment by JustinAzoff** [comment]
One thing the benchmarks may be missing is adding and removing many items over time.

**Comment by jasonlue** [comment]
Hi, Tim,

Probably we should take new int(i) out of the loop of measurement. If you use default gcc malloc, the new may cost 300 nanosecs on average according to http://goog-perftools.sourceforge.net/doc/tcmalloc.html. It may look fine as both measurements uses the same new int(1). However, if the rest of insert takes ~300nanosecs, the comparison may be off quite a bit between two.   For example, d1: total 400 nanosec; d2: total 500 nanosec. they look close, but the actual difference is 400-300 = 100 vs 500 - 300 = 200.  One actually doubles the other.  For a good hash table, I think the insert, or at least lookup, should be faster than a not fully optimized memory allocation. Just a thought, I haven't written program to test that. 

Also, when you said us(micro seconds),  Do you actually mean nano seconds? It's surprising that one hash table insert could take more than 1 micro seconds.  one benchmarking site points out std::unordered_map at 1million inserts takes 0.2 sec,  that's 200 nanosecond / item.  It could be possible that your number is big because of operations that's not related to insert(), such as new int(1). 

Please don't mind, these are all my quick thoughts, just speculation for now. I need to do more work to prove it.

**Comment by timwoj** [comment]
Closing this as I don't think we have any more work to do here.
