### ISSUE TITLE
Install Error at aux/broker

### ISSUE THREAD

**Issue by ob1xxx** [zeek/zeek#481]
I've reviewed the install guide multiple times over and every install fails. I'm compiling on Ubuntu 16.04. Once I start make I hit 83% or 37% and it seem s to be at " Building CXX object libcaf_io/CMakeFiles/libcaf_io_shared.dir/src/middleman.cpp.o". All dependencies present. I've seen closed issue, but no answer to this issue.

**Comment by JustinAzoff** [comment]
You're probably running out of memory, but you didn't include enough information to tell for sure.

**Comment by ob1xxx** [comment]
Heres memory 

total        used        free      shared  buff/cache   available
Mem:        1014384       70632      642028        3324      301724      778584
Swap:             0           0           0

**Comment by JustinAzoff** [comment]
You only have 1G of ram with 760M free.  Try adding some swap

**Comment by jsiwek** [comment]
Please give full error output if memory wasn't the issue.

**Comment by ob1xxx** [comment]
It appeared to be memory. I added swap but didn't edit /etc/fstab so it was a mess. Thanks.
