### ISSUE TITLE
Failed to create separated server for Logger instance.

### ISSUE THREAD

**Issue by hamana** [zeek/zeek#484]
Hi all,
I am using Bro 2.6.1 and deploy cluster with 2 servers: Manager, Logger and Proxy on the same one and  Worker on the other one. And, I want to split the Logger, that will be run on a new server. Now, I have an issue when deploy Logger node. I defined, in node.cfg like that:
**[logger]
type=logger
host=10.90.30.8
[manager]
type=manager
host=10.90.30.7
[proxy-1]
type=proxy
host=10.90.30.7**

In broctl.cfg, I define LogDir and SpoolDir like that:
**LogDir = /opt/bro/logs
SpoolDir = /opt/bro/spool**

I created bro group/user, created folders (like i defined for LogDir & SpoolDir), chown and chmod 777 them. I had copied ssh key from Manager server to new Logger server, too. 

But when run "broctl install" It inform that:
**Error: cannot create a directory on node logger
Error: Failed to establish ssh connection to host 10.90.30.8: too many values to unpack**

It's mean Bro cannot create folder or file on Logger server. So, how can I solve this problem?

**Comment by jsiwek** [comment]
Have you manually tested whether an ssh connection works to that host ?

Since you've had something previously running with a worker on a separate host, a guess is that the ssh configuration of the new logger host has something missing or different about it that causes this failure.

**Comment by 0xxon** [comment]
Closing this since this just looks like an ssh issue. If you feel like this is an issue with Zeek/Bro, feel free to re-open.
