### ISSUE TITLE
Some DHCP messages present little value

### ISSUE THREAD

**Issue by mpurzynski** [zeek/zeek#485]
Hey,

with the new DHCP analyzer, I see messages that have no useful content. It might be that this is due to the way DHCP protocol works, or maybe we have a bug?

Example "useless" messages, i.e. no information about the client whatsoever.

{"ts":1563913245.414444,"uids":["C8zwZq4lbTOMYq3hQ5"],"host_name":"nsm3","msg_types":["DISCOVER"],"duration":0.0}
{"ts":1563913261.837461,"uids":["C8zwZq4lbTOMYq3hQ5"],"host_name":"nsm3","msg_types":["DISCOVER","DISCOVER"],"duration":17.663983}
{"ts":1563913296.174444,"uids":["C8zwZq4lbTOMYq3hQ5"],"host_name":"nsm3","msg_types":["DISCOVER"],"duration":0.0}
{"ts":1563913313.96544,"uids":["C8zwZq4lbTOMYq3hQ5"],"host_name":"nsm3","msg_types":["DISCOVER"],"duration":0.0}
{"ts":1563913331.286443,"uids":["C8zwZq4lbTOMYq3hQ5"],"host_name":"nsm3","msg_types":["DISCOVER","DISCOVER"],"duration":16.716212}
{"ts":1563913365.262445,"uids":["C8zwZq4lbTOMYq3hQ5"],"host_name":"nsm3","msg_types":["DISCOVER"],"duration":0.0}
{"ts":1563913381.869451,"uids":["C8zwZq4lbTOMYq3hQ5"],"host_name":"nsm3","msg_types":["DISCOVER","DISCOVER"],"duration":16.623999}
{"ts":1563913415.901448,"uids":["C8zwZq4lbTOMYq3hQ5"],"host_name":"nsm3","msg_types":["DISCOVER"],"duration":0.0}
{"ts":1563913432.533486,"uids":["C8zwZq4lbTOMYq3hQ5"],"host_name":"nsm3","msg_types":["DISCOVER","DISCOVER"],"duration":16.167956}
{"ts":1563913466.445449,"uids":["C8zwZq4lbTOMYq3hQ5"],"host_name":"nsm3","msg_types":["DISCOVER"],"duration":0.0}
{"ts":1563913483.101445,"uids":["C8zwZq4lbTOMYq3hQ5"],"host_name":"nsm3","msg_types":["DISCOVER"],"duration":0.0}
{"ts":1563913500.165443,"uids":["C8zwZq4lbTOMYq3hQ5"],"host_name":"nsm3","msg_types":["DISCOVER","DISCOVER"],"duration":16.488001}

**Comment by mpurzynski** [comment]
More messages without an actual content

{"ts":1563914073.117621,"uids":["Cddayo2X0JJbHGk9Xg"],"mac":"00:c0:b7:e3:07:0c","host_name":"apcE3070C","msg_types":["DISCOVER","DISCOVER","DISCOVER","DISCOVER"],"duration":0.0}

**Comment by jsiwek** [comment]
Maybe the useful information about those is that there was no server responding to the discovery messages (or we missed/dropped those packets) ?

**Comment by JustinAzoff** [comment]
that makes sense for that last record, it has the mac and host_name fields.. the first batch posted is missing the mac which seems wrong, but hard to say for sure without a pcap.

**Comment by jsiwek** [comment]
Yeah, if client didn't send the client-identifier option and there's also no message from the server, then the mac wouldn't get populated.  If just getting the mac populated is enough to close this, then that's what's done in the PR here: https://github.com/zeek/zeek/pull/497

**Comment by mpurzynski** [comment]
Yes, indeed the #497 would help us. The way we use DHCP logs is, as you can imagine, to help identify hosts by finding out the MAC address and this change helps in forensics.
