### ISSUE TITLE
'nlohmann::detail::type_error'... [json.exception.type_error.316] invalid UTF-8 byte at index 19: 0xC1...etc.

### ISSUE THREAD

**Issue by dwdixon** [zeek/zeek#486]
Hi, I switched my zeek cluster back to running master this evening, at least temporarily.  After doing so I immediately noticed what appears to be an issue here...while I haven't spent much time at all digging into this I wanted to get something posted here to see what the right people think about what I'm running into currently with Zeek version 2.6-649.  

My logger node seems to just crash repeatedly after upgrading (if zeekctl cron job is running, else logger seems to just stay crashed from what I can tell) the lines below are being written to stderr.log.  I have a core dump as well I could share.  I'm running the bro/corelight/json-streaming-logs package and logging simultaneously to both the default tab-delimited ascii logs and also json streaming logs.   Is this something where the handling of this error condition needs to be improved or maybe something else I'm not immediately seeing here?

```
terminate called after throwing an instance of 'nlohmann::detail::type_error'
  what():  [json.exception.type_error.316] invalid UTF-8 byte at index 19: 0xC1
/opt/bro/share/zeekctl/scripts/run-zeek: line 110: 182598 Aborted                 (core dumped) nohup "$myzeek" "$@"
```

Best,

-Drew

**Comment by timwoj** [comment]
That code should only be hit if you're logging to JSON. I saw a report from another user about something similar and I'm looking into it. In the meantime you can disable the JSON if you don't absolutely need it.

I don't suppose you can give me a pcap that you know triggers it? The other user said that it was a POST request that hit it for him.

**Comment by dwdixon** [comment]
Hi Tim, thanks- we do in fact need to be logging to JSON so disabling really isn't an option for us at the moment to consider any longer than maybe a few days or so and then I'd probably just revert back to 2.6.2 until this was sorted out.  

Unfortunately it's tough to pinpoint the traffic and git a pcap of the traffic that triggers this specifically and would probably require more time than I can spend at the moment to try to get something like that.  I can say (while it probably won't help much) that this appears to be very common traffic as the crash seems to be happening repeatedly/constantly so it's not any kind of traffic that is few and far between.  

If I can get something for you in the way of a pcap that I can share I will reach out but at the moment I don't think I'd be able to get that to you anytime soon.

**Comment by JustinAzoff** [comment]
Here's a way to reproduce:

```
module JSONStress;

export {
    redef enum Log::ID += { LOG };
    type Info: record {
        data:   string  &log;
    };
}

event bro_init() &priority=5
{
    Log::create_stream(JSONStress::LOG, [$columns=Info, $path="json_stress"]);
}

event log_all_data(f: fa_file, data: string)
{
    Log::write(JSONStress::LOG, [$data=data]);
}

event file_over_new_connection(f: fa_file, c: connection, is_orig: bool)
{
    Files::add_analyzer(f, Files::ANALYZER_DATA_EVENT, [$stream_event=log_all_data]);
}
```

then run on a pcap with an x509 cert

```
$ zeek tuning/json-logs log-all-data.bro -r ~/src/zeek/testing/btest/Traces/tls/ssl-v2.trace
libc++abi.dylib: terminating with uncaught exception of type nlohmann::detail::type_error: [json.exception.type_error.316] invalid UTF-8 byte at index 1096: 0xC0
Abort trap: 6
```

**Comment by timwoj** [comment]
@dwdixon I just pushed a fix for this to the `topic/timw/cleaner-utf8` branch. Can you give that a spin and see if it fixes your issue? It fixes the test that @JustinAzoff posted above.

**Comment by dwdixon** [comment]
@timwoj @JustinAzoff Hi Tim/Justin, I pulled your fix and switched to ```topic/timw/cleaner-utf8``` branch and reinstalled, so far so good.  It's been running for a little over an hour and the logger hasn't crashed yet.  Will keep it running overnight and report back if I run into any issues or crashes etc.

Best,

-Drew

**Comment by timwoj** [comment]
@dwdixon Have you seen this issue pop up again on that branch?

**Comment by dwdixon** [comment]
@timwoj @JustinAzoff  I haven't seen that particular crash and error crop up again since switching to that branch no, but I have ran into a few logger crashes today that I think are probably unrelated.  I think this particular fix is probably looking pretty good?  Unrelated, but I'm seeing some other strange errors in reporter.log related to the NTP analyzer and also related to "Bad IP Addresses" that just look like CIDR notation, oddly....these may (or may not) have contributed to those logger crashes today but I will post them in new issues to see if they are something that needs to be addressed with a code change or some type of different/better error handling due to the types and volume of traffic my cluster is seeing.

**Comment by 0xxon** [comment]
Should be fixed with https://github.com/zeek/zeek/pull/487

**Comment by 0xxon** [comment]
And yes - please post different logger crashes into new issues :).

Thank you very much for your work testing :)
