### ISSUE TITLE
Duplicate TCP packets are not detected as retransmissions

### ISSUE THREAD

**Issue by jsbarber** [zeek/zeek#499]
When a TCP segment represented by the packet is exactly coincident with the last-seen TCP segment, the 't'/'T' (retransmission indicators) are not being added to the connection history string, and the `tcp_multiple_retransmissions` event is not being triggered. 

The most common case of this is where a duplicate packet exactly like the previous one is observed. However, any non-zero-length retransmission ending in the same last-seen sequence number would also not be detected.

PR with fix at https://github.com/zeek/zeek/pull/494

**Comment by jsiwek** [comment]
Patch looked good, thanks for finding/fixing the bug along with the unit test updates.
