### ISSUE TITLE
Repeated NTP Analyzer "field value missing" Reporter:ERROR occurrences

### ISSUE THREAD

**Issue by dwdixon** [zeek/zeek#506]
I'm running latest up-to-date ```master```, specifically ```zeek version 2.6-713``` and I'm seeing nearly constant occurrences in reporter.log related to what appears to be empty values being attempted to be written for the stratum field from the NTP analyzer in ntp.log...is this something that should maybe be handled differently than generating a Reporter::ERROR for every occurence of this and instead just replace the empty value with a "-" in the ntp.log or something similar?

```
Reporter::ERROR	field value missing (NTP::c$ntp)	/opt/bro/share/zeek/base/protocols/ntp/./main.zeek, line 100
Reporter::ERROR	field value missing (NTP::msg$std_msg)	/opt/bro/share/zeek/base/protocols/ntp/./main.zeek, line 70
Reporter::ERROR	field value missing (NTP::c$ntp)	/opt/bro/share/zeek/base/protocols/ntp/./main.zeek, line 100
Reporter::ERROR	field value missing (NTP::msg$std_msg)	/opt/bro/share/zeek/base/protocols/ntp/./main.zeek, line 70
Reporter::ERROR	field value missing (NTP::c$ntp)	/opt/bro/share/zeek/base/protocols/ntp/./main.zeek, line 100
Reporter::ERROR	field value missing (NTP::msg$std_msg)	/opt/bro/share/zeek/base/protocols/ntp/./main.zeek, line 70
Reporter::ERROR	field value missing (NTP::c$ntp)	/opt/bro/share/zeek/base/protocols/ntp/./main.zeek, line 100
```

I might be able to get a pcap if needed but if not I'd rather not spend time on that if not absolutely needed to address this.

Best,

-Drew

**Comment by sethhall** [comment]
Thanks for the report.  I'm looking at this now.

**Comment by jsiwek** [comment]
Likely fixed in `master` now, if not, getting a pcap will help.

**Comment by dwdixon** [comment]
@sethhall @jsiwek Thanks to you both, didn't spend much time looking at the code last night when I created the issue FWIW...just took a quick glance at the two lines in ```scripts/base/protocols/ntp/main.zeek``` that the reporter error was griping about : )

Will test this shortly and let you know how things are looking.

**Comment by dwdixon** [comment]
@sethhall @jsiwek  Hi Seth/Jon, this is looking great, the changes seem to have fixed the issue based on testing in my environment as well.
