### ISSUE TITLE
Please allow the caller  so specify the man directory

### ISSUE THREAD

**Issue by yurivict** [zeek/zeek#512]
Currently there are these lines which define man directories:
```
$ grep -r /share/man work/
work/zeek-2.6-727-g22e89bdc7/CMakeLists.txt:    set(ZEEK_MAN_INSTALL_PATH ${ZEEK_ROOT_DIR}/share/man)
work/zeek-2.6-727-g22e89bdc7/aux/bro-aux/CMakeLists.txt:    set(ZEEK_MAN_INSTALL_PATH ${CMAKE_INSTALL_PREFIX}/share/man)
work/zeek-2.6-727-g22e89bdc7/aux/broctl/CMakeLists.txt:    set(ZEEK_MAN_INSTALL_PATH ${CMAKE_INSTALL_PREFIX}/share/man)
work/zeek-2.6-727-g22e89bdc7/aux/broctl/aux/trace-summary/CMakeLists.txt:    set(BRO_MAN_INSTALL_PATH ${CMAKE_INSTALL_PREFIX}/share/man)
work/zeek-2.6-727-g22e89bdc7/aux/zeek-aux/CMakeLists.txt:    set(ZEEK_MAN_INSTALL_PATH ${CMAKE_INSTALL_PREFIX}/share/man)
work/zeek-2.6-727-g22e89bdc7/aux/zeekctl/CMakeLists.txt:    set(ZEEK_MAN_INSTALL_PATH ${CMAKE_INSTALL_PREFIX}/share/man)
work/zeek-2.6-727-g22e89bdc7/aux/zeekctl/aux/trace-summary/CMakeLists.txt:    set(BRO_MAN_INSTALL_PATH ${CMAKE_INSTALL_PREFIX}/share/man)
work/zeek-aux-9a7d124/CMakeLists.txt:    set(ZEEK_MAN_INSTALL_PATH ${CMAKE_INSTALL_PREFIX}/share/man)
work/zeekctl-b6642b8/CMakeLists.txt:    set(ZEEK_MAN_INSTALL_PATH ${CMAKE_INSTALL_PREFIX}/share/man)
work/zeekctl-b6642b8/aux/trace-summary/CMakeLists.txt:    set(BRO_MAN_INSTALL_PATH ${CMAKE_INSTALL_PREFIX}/share/man)
work/trace-summary-17062c9/CMakeLists.txt:    set(BRO_MAN_INSTALL_PATH ${CMAKE_INSTALL_PREFIX}/share/man)
```

I suggest that you:
1. Combine all these cmake variables into one, for example ZEEP_MAN_INSTALL_PATH, because man pages are normally installed into one directory.
2. Make this variable changeable to the user, because on FreeBSD, for example,  the sub-directory is ```/man```, not ```/share/man```.

**Comment by jsiwek** [comment]
> * Combine all these cmake variables into one, for example ZEEP_MAN_INSTALL_PATH, because man pages are normally installed into one directory.

In `master`, everything should now consistently be using `ZEEK_MAN_INSTALL_PATH`.

> * Make this variable changeable to the user, because on FreeBSD, for example,  the sub-directory is `/man`, not `/share/man`.

It should already be changeable via calling CMake directly with a `-D ZEEK_MAN_INSTALL_PATH:PATH=/custom/path` argument.  I also added a `--mandir=` configure option for consistency.  Let me know if there's something else missing.
