### ISSUE TITLE
Very frequent 'Bad IP address: 192.168.0.0/16' Reporter::ERROR reporter.log occurrences 

### ISSUE THREAD

**Issue by dwdixon** [zeek/zeek#514]
I'm running ```master``` and specifically at the moment ```zeek version 2.6-725``` I've been seeing this error nearly constantly in reporter.log since switching back to master and there's not really much to go on...oddly it looks like valid CIDR notation where maybe a single non-CIDR notation IP address is expected possibly?

```
Reporter::ERROR	Bad IP address: 192.168.0.0/16	(empty)
Reporter::ERROR	Bad IP address: 192.168.0.0/16	(empty)
Reporter::ERROR	Bad IP address: 192.168.0.0/16	(empty)
Reporter::ERROR	Bad IP address: 192.168.228.0/22	(empty)
Reporter::ERROR	Bad IP address: 192.168.228.0/22	(empty)
Reporter::ERROR	Bad IP address: 192.168.0.0/16	(empty)
Reporter::ERROR	Bad IP address: 192.168.0.0/16	(empty)
Reporter::ERROR	Bad IP address: 192.168.0.0/16	(empty)
Reporter::ERROR	Bad IP address: 192.168.0.0/16	(empty)
Reporter::ERROR	Bad IP address: 192.168.0.0/16	(empty)
Reporter::ERROR	Bad IP address: 192.168.0.0/14	(empty)
Reporter::ERROR	Bad IP address: 192.168.0.0/14	(empty)
```

**Comment by sethhall** [comment]
I have a suspicion that this problem is caused by an external script, but it does point to a larger problem we have.  Is it possible for us to determine the stack location for Bif errors?  It seems like we should be able to pull that off way or another.

**Comment by dwdixon** [comment]
@sethhall @jsiwek I just had a random hunch on where this might be coming from and after checking on that hunch I'm pretty certain that this is coming from our threat intel feed being imported into the Intel Framework.  I anonymized the CIDR blocks when I posted them here but I just spot checked the real CIDR blocks in reporter.log against what’s currently in our IPv4 feed that’s being imported into the Intel framework and every one of them is present.   We've regularly had CIDR blocks in our IPv4 feed and I've never had any issues with CIDR blocks in our IP4 feed until I recently switched back to ```master```.   I suspect it's possible/likely that one of these Intel framework related scripts is implicated with this as well?

```
@load frameworks/intel/do_notice
@load frameworks/intel/seen
@load frameworks/intel/do_expire
@load policy/integration/collective-intel
```

**Comment by sethhall** [comment]
Ah!  You should be able to try the branch that branch pushed a little while ago to see if it at least points to the right code (something in the intel framework).  Those error messages are way better with Jon's change.

**Comment by 0xxon** [comment]
The referred branch is in master now.

**Comment by dwdixon** [comment]
@sethhall @jsiwek @0xxon Here are the new error messages, much more useful ! : )

```
Reporter::ERROR	failed converting string to IP address (to_addr(Intel::item$indicator) and 192.168.32.0/20)	/opt/bro/share/zeek/base/frameworks/intel/./main.zeek, line 481
Reporter::ERROR	failed converting string to IP address (to_addr(Intel::item$indicator) and 192.168.32.0/20)	/opt/bro/share/zeek/base/frameworks/intel/./main.zeek, line 419
Reporter::ERROR	failed converting string to IP address (to_addr(Intel::item$indicator) and 192.168.64.0/19)	/opt/bro/share/zeek/base/frameworks/intel/./main.zeek, line 481
Reporter::ERROR	failed converting string to IP address (to_addr(Intel::item$indicator) and 192.168.64.0/19)	/opt/bro/share/zeek/base/frameworks/intel/./main.zeek, line 419
Reporter::ERROR	failed converting string to IP address (to_addr(Intel::item$indicator) and 192.168.224.0/20)	/opt/bro/share/zeek/base/frameworks/intel/./main.zeek, line 481
Reporter::ERROR	failed converting string to IP address (to_addr(Intel::item$indicator) and 192.168.224.0/20)	/opt/bro/share/zeek/base/frameworks/intel/./main.zeek, line 419
Reporter::ERROR	failed converting string to IP address (to_addr(Intel::item$indicator) and 192.168.222.0/24)	/opt/bro/share/zeek/base/frameworks/intel/./main.zeek, line 419
Reporter::ERROR	failed converting string to IP address (to_addr(Intel::item$indicator) and 192.168.16.0/20)	/opt/bro/share/zeek/base/frameworks/intel/./main.zeek, line 481
Reporter::ERROR	failed converting string to IP address (to_addr(Intel::item$indicator) and 192.168.16.0/20)	/opt/bro/share/zeek/base/frameworks/intel/./main.zeek, line 419
```

**Comment by jsiwek** [comment]
@dwdixon the errors probably still indicate someone else is generating an invalid `Intel::Item` and calling `Intel::insert` with it, like via a file in `Intel::read_files`.  So do the matching items you said you found in your feed actually use the right indicator type?  e.g. `Intel::SUBNET` versus `Intel::ADDR`.

**Comment by dwdixon** [comment]
@jsiwek @sethhall it does appear that these subnets are incorrectly being typed with and indicator_type of "Intel:ADDR" rather than "Intel:SUBNET"...this data is being generated by CIFv2's bro/zeek formatted feed generator.  I don't recall this being a problem until very recently when moving back to ```master```, did anything change on the zeek intel framework side that may have contributed to or started to more strictly enforce the indicator typing?   I need to look into this more on the CIF side but nothing has changed with our current CIF setup and how it generates this feed so it makes me think it was something on the zeek end that changed recently?

**Comment by jsiwek** [comment]
The previous implementation of `to_addr` didn't check for the pull string being consumed, so `to_addr("192.168.0.0/16")` would return `192.168.0.0` without any error.  That a bug, the new behavior is correct.

And it's also still a bug to set the incorrect indicator type for an intel item either way.

**Comment by sethhall** [comment]
I closed this because it seems like a less relevant issue now that the log messages are indicating where the problem is coming from and it turns out that it's a local data issue.

Please file a new ticket if there is more thinking to do with how intel item parsing happens.

**Comment by dwdixon** [comment]
@jsiwek @sethhall  Thanks, that helps clear things up a bit more- and yes totally agree Jon.  It looks like this is probably an issue with how CIFv2's  ```--format bro``` perl script is functioning...still need to make some time to look into it more to be certain but if anyone is curious, I believe this is is where the fix probably needs to be made:

https://github.com/csirtgadgets/p5-cif-sdk/blob/master/lib/CIF/SDK/Format/Bro.pm

**Comment by sfinlon** [comment]
Which version of the cifsdk are you running? The Perl version that you referenced hasn’t been updated in years (I think the last time was for your previous coworker). We switched over to the python version for anything recently updated/enhanced.

I believe that CIF currently handles single IP addresses the same as CIDR blocks, so it’s quite possible that the CIDRs are just being mapped to addr for seem. I’ll have to test that out and see what we can do to break them out for the zeek parser. 

You likely just started seeing issues running master because I pushed a PR to actually get the CIF metadata pushed to the intel.log.

I can follow up with you Drew and then report back here to the thread with the results.

**Comment by dwdixon** [comment]
@sfinlon Digging around re: CIFv2 SDK version...looks like ```p5-cif-sdk-2.00_37``` and regarding CIFv3 SDK version we are running ```3.0.5```.   In my testing it appears that CIDR blocks are being mapped to ```Intel::ADDR``` rather than ```Intel::SUBNET```, I also tested that out in CIFv3 using SDK ```3.0.5``` on Friday as well as confirming this behavior on CIFv2 even though we are moving away from that.

**Comment by sfinlon** [comment]
> @sfinlon Digging around re: CIFv2 SDK version...looks like `p5-cif-sdk-2.00_37` and regarding CIFv3 SDK version we are running `3.0.5`. In my testing it appears that CIDR blocks are being mapped to `Intel::ADDR` rather than `Intel::SUBNET`, I also tested that out in CIFv3 using SDK `3.0.5` on Friday as well as confirming this behavior on CIFv2 even though we are moving away from that.

Yea, this makes sense, and I'll have to fix it in the Zeek output parser for CIF.
I verified, but wasn't able to write the fix yet. CIF will put a single address or a CIDR block in the ipv4 indicator type, and currently it just outputs everything ipv4 to Intel::ADDR. I'll just have to write a little subparser that looks for the CIDR notation and switches the Zeek type to Intel::SUBNET. It's definitely on our end and not an issue with the Zeek project.

I had asked about the perl client, because we'll likely not make the change to that one, but all versions of the python client use the same csirtg-indicator.py library so as long as that gets updated it will push out the correct format.

**Comment by sfinlon** [comment]
@dwdixon if you run `pip install git+https://github.com/sfinlon/csirtg-indicator-py` on the machine where you have the python CIF client, and give that a shot, it should work for you.

I'll push a new release of the official csirtg-indicator shortly, but running that will let you test it until then.
