### ISSUE TITLE
Zeekctl reports non-crashed nodes as crashed

### ISSUE THREAD

**Issue by 0xxon** [zeek/zeek#518]
On a larger cluster, we have observed zeekctl marking nodes as crashed, even when they are not crashed.

Example zeekctl top output (running nodes pruned):
```
#  /srv/zeek/zeek/bin/zeekctl top
worker-1-18  worker  10.64.12.19      <not running>
worker-1-29  worker  10.64.12.19      <not running>
```

Zeekctl diag output shows that `zeekctl cron` tried to restart the nodes, resulting in a "port already in used" error (output pruned from non-important information):

```
# zeekctl diag worker-1-18
...
==== stderr.log
warning in /srv/zeek/zeek/spool/installed-scripts-do-not-touch/site/./ssl.bro, line 178: deprecated (bro_init): Remove in v3.1: use zeek_init
warning in /srv/zeek/zeek/spool/installed-scripts-do-not-touch/site/./ssl.bro, line 203: deprecated (bro_init): Remove in v3.1: use zeek_init
listening on enp134s0f0

error in /srv/zeek/zeek/share/bro/base/frameworks/cluster/./setup-connections.zeek, lines 93-95: Failed to listen on INADDR_ANY:47781 (Broker::listen(Broker::default_listen_address, Cluster::self$p, Broker::default_listen_retry))
fatal error: errors occurred while initializing
```

Running lsof on the port shows that zeek is still running:

```
# lsof -i -P -n | grep LISTEN | grep 47781
zeek      66364            root   12u  IPv6 69114304      0t0  TCP *:47781 (LISTEN)
```

Running ps shows the process running; attaching gdb shows normal output.
```
# ps -p 66364 -o %cpu,%mem,cmd
%CPU %MEM CMD
24.7  0.2 /srv/zeek/zeek/bin/zeek -i enp134s0f0 -U .status -p zeekctl -p zeekctl-live -p local -p worker-1-18 local.zeek zeekctl base/frameworks/cluster zeekctl/auto -b
```

Running check-pid shows the process as running

```
# ./share/zeekctl/scripts/helpers/check-pid 66364
running
```

Re-adjusting the pid in the zeekctl state.db makes the process show up again:
```
# sqlite3 state.db
sqlite> select * from state where key like 'worker-1-18%';
worker-1-18-port|47781
worker-1-18-host|"10.64.12.19"
worker-1-18-expect-running|true
worker-1-18-pid|null
worker-1-18-crashed|true

sqlite> update state set value="false" where key = "worker-1-18-crashed";
sqlite> update state set value="66364" where key = "worker-1-18-pid";
```

Afterwards, the process shows up as expected in zeekctl top:
```
worker-1-18  worker  10.64.12.19      66364     1G   608M  27%  zeek
```

Other zeekctl commands yield the expected resutlts:
```
[ZeekControl] > peerstatus worker-1-18
worker-1-18
1564770490.866680 peer=C06969910ECE20B21986080033386B93449DC500#65791 host=10.64.12.19 status=Broker::PEERED
1564770490.866680 peer=C06969910ECE20B21986080033386B93449DC500#65850 host=10.64.12.19 status=Broker::PEERED
1564770490.866680 peer=C06969910ECE20B21986080033386B93449DC500#65908 host=10.64.12.19 status=Broker::PEERED
1564770490.866680 peer=C06969910ECE20B21986080033386B93449DC503#64104 host=10.64.12.19 status=Broker::PEERED

[ZeekControl] > print Site::private_address_space worker-1-18
 worker-1-18   Site::private_address_space = {
	127.0.0.0/8,
	192.168.0.0/16,
	100.64.0.0/10,
	::1/128,
	10.0.0.0/8,
	fe80::/10,
	172.16.0.0/12
}
```

Since the processes are in fact still running, traffic should continue to be processed; this still seems like - at least - not nice failure mode at the moment, which is not completely trivial to debug.

**Comment by JustinAzoff** [comment]
My guess is something is wrong wrong in check-pid, and it thinks the node is not running beacuse there was some transient failure running check-pid.

798b42939f7832533a4a0602fadf3808481ab379 in topic/justin/check-pid-robustness has a potential fix for this.

**Comment by 0xxon** [comment]
I will apply that patch to the server, and enable zeekctl debugging

**Comment by jsiwek** [comment]
Can also generally look at the `check-pid` git history: there's some changes done there to improve Alpine support, possibly broke other platforms.

**Comment by 0xxon** [comment]
The same problem is still happening with your patch applied, @JustinAzoff.

After 2 days, the following nodes are reported as crashed:

```
worker-1-13  worker  10.64.12.19      crashed
worker-1-24  worker  10.64.12.19      crashed
worker-1-25  worker  10.64.12.19      crashed
worker-2-13  worker  10.64.12.19      crashed
```

The first output that is interesting in the zeekctl diag.log that I seem to be able to find is:

```
04 Aug 09:15:02 [zeekctl] starting worker ...
04 Aug 09:15:02 [zeekctl] creating crash report for previously crashed nodes: worker-1-13
04 Aug 09:15:02 [execute] 10.64.12.19: /srv/zeek/zeek/share/zeekctl/scripts/post-terminate worker /srv/zeek/zeek/spool/worker-1-13 crash
04 Aug 09:15:02 [execute] 10.64.12.19: exit code 0
04 Aug 09:15:02 [execute] /srv/zeek/zeek/share/zeekctl/scripts/send-mail 'Crash report from worker-1-13'
04 Aug 09:15:02 [execute] exit status: 0
04 Aug 09:15:03 [execute] 10.64.12.19: mkdir -p /srv/zeek/zeek/spool/worker-1-13
04 Aug 09:15:03 [execute] 10.64.12.19: exit code 0
04 Aug 09:15:03 [execute] 10.64.12.19: /srv/zeek/zeek/share/zeekctl/scripts/helpers/start -v CLUSTER_NODE=worker-1-13 -v PCAP_PF_RING_APPNAME=zeek-enp134s0f0 -v PCAP_PF_RING_CLUSTER_ID=21 -v PCAP_PF_RING_USE_CLUSTER_PER_FLOW_4_TUPLE=1 /srv/zeek/zeek/spool/worker-1-13 -1 -i 'enp134s0f0' -U .status -p zeekctl -p zeekctl-live -p local -p worker-1-13 local.zeek zeekctl base/frameworks/cluster zeekctl/auto -b
04 Aug 09:15:04 [execute] 10.64.12.19: exit code 0
04 Aug 09:15:04 [execute] 10.64.12.19: /srv/zeek/zeek/share/zeekctl/scripts/helpers/check-pid 41625
04 Aug 09:15:04 [execute] 10.64.12.19: exit code 0
04 Aug 09:15:04 [execute] 10.64.12.19: /srv/zeek/zeek/share/zeekctl/scripts/helpers/first-line /srv/zeek/zeek/spool/worker-1-13/.status
04 Aug 09:15:04 [execute] 10.64.12.19: exit code 0
04 Aug 09:15:04 [zeekctl] worker-1-13 terminated immediately after starting; check output with "diag"
```

Which is kind of boring - because it just shows that it failed restarting it.

On a first glance, the same is the case for the other workers. If you want the debug.log I can provide it to you. The entire debug.log never contains the new output you just added to zeekctl.

**Comment by 0xxon** [comment]
For further information - the system in question is running Ubuntu 18.04.1 LTS

**Comment by JustinAzoff** [comment]
ah, I didn't realize check-pid had changed recently, that certainly seems suspect now.

**Comment by 0xxon** [comment]
The changes to check-pid are https://github.com/zeek/zeekctl/commit/0991da26e6388e17feb3ecec68721bcdf785daa6#diff-59e91a4e95844174331090242301617a and https://github.com/zeek/zeekctl/commit/f72a0f6bcbf469e84d345f0056d7cd3e03e1116c#diff-59e91a4e95844174331090242301617a. Especially https://github.com/zeek/zeekctl/commit/0991da26e6388e17feb3ecec68721bcdf785daa6#diff-59e91a4e95844174331090242301617a looks suspicious (it changes the logic of the check-pid script significantly); it was created to fix https://github.com/zeek/zeekctl/pull/11.

**Comment by 0xxon** [comment]
@JustinAzoff wrote a check-pid script that contains the logic for both versions, and logs the difference. I am going to deploy that on the cluster in question.

**Comment by 0xxon** [comment]
I have further updates for this. After running a check-pid script, which runs the old code and the new code in parallel and outputs when there are divergences in status, the result is as follows:

at least on this system, the failure case is that the old code (using ps -p) returns that the process is running. The new code returns that the process is not running - because kill -0 returns an error.

I have ps outputs too that I can append here - but since it does not make it to this step, I don't see a big reason to paste it here.

I am unsure why kill fails from time to time - but the processes are pretty clearly still present. All parts of zeek are run as root - so permissions should not be a problem.

As Ubuntu LTS is a rather common distribution, I propose to roll back the changes to the check-pid script, and go with the much easier version that we had before. This will break support for systems that use busybox (and do not support ps -p) - but since these are not what I consider officially supported (we don't test against them, or run them), I would consider this acceptable for this release. Plus - I think it is possible to install coreutils on Alpine - which solves this issue for Alpine users.

If this sounds ok, I am happy to make a PR against zeekctl.

**Comment by 0xxon** [comment]
PR in https://github.com/zeek/zeekctl/pull/17

**Comment by jsiwek** [comment]
An alternative could be trying the previous `ps -p` logic *first* and if it fails, fallback to trying the newer, more complex logic, but it's still troubling to not know where/when/why `kill -0` may fail.  But we can just get rid of the `kill -0` check, too, since it's just there to avoid crawling the full `ps` output in cases where it's definitely dead.

People trying to use Alpine is not that rare, and while it's not hard to ask them to install the `procps` version, my guess is it's going to trip people up constantly, so worth adding the fallback logic to try to support it by default.

**Comment by 0xxon** [comment]
Hum. Could we maybe use pgrep instead? Busybox has it, it is part of procps, OS X has it, FreeBSD seems to have it too...

Another way might be to check if /proc/[pid]/cmdline contains "zeek" - should work on all Linux and FreeBSD systems. And for OS-X we already had a carveout. 

I think I actually like the last method best - it requires procps to be mounted to /proc, but that should be the case everywhere...

**Comment by jsiwek** [comment]
Yeah, looking in `/proc` (if we have it) sounds nice, but at this point I wonder if we just go with the something that's least-different from the known-stable-release version of `check-pid`, but has some additional fallback logic to sanity check the result of `ps -p` (and so will also happen to work on Alpine).  Maybe:

```
ps -p $1 -o args | grep -q zeek

if [ $? -eq 0 ]; then
    echo "running"
else
    if [ -f /proc/$1/cmdline ]; then
        grep -q zeek /proc/$1/cmdline

        if [ $? -eq 0 ]; then
            echo "running"
        else
            echo "not running"
        fi
    else
        echo "not running"
    fi
fi
```

**Comment by 0xxon** [comment]
I like this :)

**Comment by jsiwek** [comment]
PR for the latest idea at https://github.com/zeek/zeekctl/pull/18, worked for me on both Ubuntu and Alpine.

**Comment by 0xxon** [comment]
Looks like this is fixed with the patch of @jsiwek
