### ISSUE TITLE
Cluster documentation is outdated

### ISSUE THREAD

**Issue by rsmmr** [zeek/zeek#530]
https://docs.zeek.org/en/stable/cluster/ still talks about the old cluster/comm setup, in particular in the proxy section.

**Comment by jsiwek** [comment]
I updated the cluster architecture docs and it's now at https://docs.zeek.org/en/latest/cluster/
(note the link in OP is for the "stable" version of the docs and won't change until a release is made).

The specific suggestion for how much traffic a single worker can handle could probably use modernization, so will leave this issue open (or feel free to close / make another for that).

**Comment by rsmmr** [comment]
Let's remove the suggested number, it won't generalizer.

**Comment by delapsley** [comment]
I've been reading through these docs a bit lately. I came across a "bug" today:

From this page: https://docs.zeek.org/en/stable/frameworks/broker.html#brokercomm-framework the Broker Library link points to: https://docs.zeek.org/en/stable/components/broker/README.html which is missing. Is it supposed to point to something like this?

    https://docs.zeek.org/projects/broker/en/latest/

Let me know if you'd like me to log this as a separate issue.

**Comment by jsiwek** [comment]
@delapsley thanks, and yeah that's basically where the broken link should have been pointing.  Will be fixed shortly.  Feel free to make new issues for anything else you find broken.
