### ISSUE TITLE
libdir prefixes not unified in installation

### ISSUE THREAD

**Issue by 0xxon** [zeek/zeek#533]
On linux, it seems that some library files currently are installed to [prefix]/lib and some library files to [prefix]/lib64

To me more exact, on my installation lib has:

```
lrwxrwxrwx 1 johanna johanna    9 Aug  9 10:08 broctl -> ./zeekctl
lrwxrwxrwx 1 johanna johanna   14 Aug  9 10:08 libbroker.so -> libbroker.so.2
-rwxr-xr-x 1 johanna johanna  52M Aug  5 15:23 libbroker.so.1.1
lrwxrwxrwx 1 johanna johanna   16 Aug  9 10:08 libbroker.so.2 -> libbroker.so.1.1
-rw-r--r-- 1 johanna johanna 1.4M Jul  1 00:48 libparaglob.a
drwxrwxr-x 3 johanna johanna 4.0K Aug  9 10:08 zeek
drwxrwxr-x 6 johanna johanna 4.0K Aug  9 10:08 zeekctl
```

And lib64 has:
```
lrwxrwxrwx 1 johanna johanna   14 Aug  9 10:08 libbinpac.so -> libbinpac.so.0
lrwxrwxrwx 1 johanna johanna   20 Aug  9 10:08 libbinpac.so.0 -> libbinpac.so.0.51-27
-rwxr-xr-x 1 johanna johanna 128K Jul 11 13:36 libbinpac.so.0.51-27
```

We should probably unify this, so that all libraries are installed into the same directory by default.

**Comment by 0xxon** [comment]
Potentially important note - this happens on Fedora.

**Comment by rsmmr** [comment]
Changed milestone to 3.0.0, would be nice to fix if it's easy.

**Comment by jsiwek** [comment]
Sure can look into it, but does impact functionality at all or block a use-case ?  Generally wanted to avoid changing things that aren't clearly bugfixes during the RC.  The platform-dependent nature of it further degrades my excitement since regressions are more likely to go unnoticed.
