### ISSUE TITLE
Segfault in ntlm-analyzer.pac build_av_record()

### ISSUE THREAD

**Issue by PSChrisHinshaw** [zeek/zeek#541]
I have a PCAP from one of our customers that appears to expose a segfault in ntlm-analyzer.pac.  If needed, I can share this pcap after I sanitize it.  

My assumption is that the NTLM packet is not properly formed, and has no AV Pairs to cycle through.  The code provided below checks for an empty vector and returns if there is nothing to access.

Patch data below:
`diff -Naur --exclude .git --exclude .vscode --exclude build a/src/analyzer/protocol/ntlm/ntlm-analyzer.pac b/src/analyzer/protocol/ntlm/ntlm-analyzer.pac`
`--- a/src/analyzer/protocol/ntlm/ntlm-analyzer.pac	2019-06-20 11:30:03.000000000 -0700`
`+++ b/src/analyzer/protocol/ntlm/ntlm-analyzer.pac	2019-07-24 15:55:19.000000000 -0700`
`@@ -27,6 +27,10 @@`
` 	function build_av_record(val: NTLM_AV_Pair_Sequence): BroVal`
` 		%{`
` 		RecordVal* result = new RecordVal(BifType::Record::NTLM::AVs);`
`+		if ( ${val.pairs}->size() == 0 )`
`+		{`
`+			return result;`
`+		}`
` 		for ( uint i = 0; ${val.pairs[i].id} != 0; i++ )`
` 			{`
` 			switch ( ${val.pairs[i].id} )`

**Comment by jsiwek** [comment]
Thanks for the report and potential patch -- that particular loop does look suspicious.  If you can, please do send a pcap that can reproduce the segfault just so we can confirm the exact problem, but preferably follow up with that in separate email to security@zeek.org, optional pgp key found [here](https://www.zeek.org/contact/index.html#reporting-a-security-vulnerability).

**Comment by PSChrisHinshaw** [comment]
PCAP provided.  The updated patch provided by Jon Siwek was tested against the same pcap and does not crash.  I believe this fixes this issue.  Thank you for the quick turnaround (even if I didn't provide the crashing PCAP very quickly :) ).

I think this will need to be applied to both master and the 2.6 branch (though I leave it up to the Zeek owners to decide).
