### ISSUE TITLE
use `#pragma once` in headers

### ISSUE THREAD

**Issue by jsiwek** [zeek/zeek#543]
Our [style/convention guide](https://docs.zeek.org/en/latest/devel/style_guide.html#include-guards) now claims `#pragma once` should be used in headers, so for consistency, probably a simple enough change to just do that replacement for existing headers.

**Comment by Patil2099** [comment]
@jsiwek  Can I work on it?

**Comment by jsiwek** [comment]
@Patil2099 Fine by me, thanks.
