### ISSUE TITLE
After weird normalization, some weirds don't set addl field

### ISSUE THREAD

**Issue by grigorescu** [zeek/zeek#545]
In the 3.0 NEWS, we mention changing a number of weirds so that the number gets moved out of the weird name, and into the addl field.

One of the one we mentioned is [unknown_protocol](https://github.com/zeek/zeek/blob/master/NEWS#L337)

We're running 3.0 RC1, and seeing unknown_protocol weirds, but they have no field in addl. In fact, one of the Zeek btests has this same behavior:

> testing/btest/Baseline/core.disable-mobile-ipv6/weird.log:1333663011.602839     -       -       -       -       -       unknown_protocol        -       F       zeek

It looks like there are a few similar weirds that are mentioned in the NEWS file:

>     Weird("unknown_gre_version", ip_hdr, encapsulation);
>     Weird("unknown_gre_protocol", ip_hdr, encapsulation);
>     Weird("unknown_protocol", pkt, encapsulation);

Neither of the NetSessions::Weird functions seem to be able to take in the addl field, and pass it on to the reporter:

```
    void NetSessions::Weird(const char* name, const Packet* pkt,
                            const EncapsulationStack* encap)
            {
            if ( pkt )
                    dump_this_packet = 1;

            if ( encap && encap->LastType() != BifEnum::Tunnel::NONE )
                    reporter->Weird(fmt("%s_in_tunnel", name));
            else
                    reporter->Weird(name);
            }

    void NetSessions::Weird(const char* name, const IP_Hdr* ip,
                            const EncapsulationStack* encap)
            {
            if ( encap && encap->LastType() != BifEnum::Tunnel::NONE )
                    reporter->Weird(ip->SrcAddr(), ip->DstAddr(),
                                    fmt("%s_in_tunnel", name));
            else
                    reporter->Weird(ip->SrcAddr(), ip->DstAddr(), name);
            }
```
Ultimately, this needs to make it to script-land, but the `net_weird` event would need to be modified to take an `addl` parameter.

Looking through GitHub, I only found one user script that was handling that event, and it looks like it's a year-old project to develop a modified version of Bro, which hasn't progressed very far.

**Comment by jsiwek** [comment]
Thanks, I'm in favor of fixing this for 3.0 by way of just adding an "addl" parameter to the "net_weird" and "flow_weird" events (may break user code, but at least there's not any public packages which use them)
