### ISSUE TITLE
Bro Installation problem

### ISSUE THREAD

**Issue by mengzhisha** [zeek/zeek#561]
Hi all,

I am trying to install the latest version of bro by following the exact steps on the website. After executing the 'make' command, I get the following errors:
   
`[ 10%] Linking CXX executable ../bin/broker-stream-benchmark
CMakeFiles/broker-stream-benchmark.dir/benchmark/broker-stream-benchmark.cc.o: In function `main::{lambda()#1}::operator()() const':
/home/ubuntu/zeek/aux/broker/tests/benchmark/broker-stream-benchmark.cc:187: undefined reference to `broker::endpoint::peer(std::string const&, unsigned short, std::chrono::duration<long, std::ratio<1l, 1l> >)'
CMakeFiles/broker-stream-benchmark.dir/benchmark/broker-stream-benchmark.cc.o: In function `broker::to_string(broker::data const&)':
/home/ubuntu/zeek/aux/broker/broker/data.hh:182: undefined reference to `broker::convert(broker::data const&, std::string&)'
CMakeFiles/broker-stream-benchmark.dir/benchmark/broker-stream-benchmark.cc.o: In function `to_string':
/home/ubuntu/zeek/aux/broker/3rdparty/caf/libcaf_core/caf/actor.hpp:172: undefined reference to `caf::to_string(caf::intrusive_ptr<caf::actor_control_block> const&)'
CMakeFiles/broker-stream-benchmark.dir/benchmark/broker-stream-benchmark.cc.o: In function `to_string':
/home/ubuntu/zeek/aux/broker/broker/data.hh:182: undefined reference to `broker::convert(broker::data const&, std::string&)'
CMakeFiles/broker-stream-benchmark.dir/benchmark/broker-stream-benchmark.cc.o: In function `main':
/home/ubuntu/zeek/aux/broker/tests/benchmark/broker-stream-benchmark.cc:166: undefined reference to `broker::endpoint::peer(std::string const&, unsigned short, std::chrono::duration<long, std::ratio<1l, 1l> >)'
/home/ubuntu/zeek/aux/broker/tests/benchmark/broker-stream-benchmark.cc:176: undefined reference to `broker::endpoint::listen(std::string const&, unsigned short)'
/home/ubuntu/zeek/aux/broker/tests/benchmark/broker-stream-benchmark.cc:182: undefined reference to `broker::endpoint::listen(std::string const&, unsigned short)'
/home/ubuntu/zeek/aux/broker/tests/benchmark/broker-stream-benchmark.cc:162: undefined reference to `caf::to_string(caf::atom_value const&)'
CMakeFiles/broker-stream-benchmark.dir/benchmark/broker-stream-benchmark.cc.o:(.rodata+0x12c0): undefined reference to `caf::actor_system_config::make_help_text(std::vector<caf::message::cli_arg, std::allocator<caf::message::cli_arg> > const&)'
CMakeFiles/broker-stream-benchmark.dir/benchmark/broker-stream-benchmark.cc.o:(.rodata._ZTVN6broker13configurationE[_ZTVN6broker13configurationE]+0x20): undefined reference to `caf::actor_system_config::make_help_text(std::vector<caf::message::cli_arg, std::allocator<caf::message::cli_arg> > const&)'
CMakeFiles/broker-stream-benchmark.dir/benchmark/broker-stream-benchmark.cc.o:(.rodata._ZTVN3caf14stateful_actorIN6broker10core_stateENS_17event_based_actorEEE[_ZTVN3caf14stateful_actorIN6broker10core_stateENS_17event_based_actorEEE]+0x48): undefined reference to `caf::abstract_actor::message_types() const'
collect2: error: ld returned 1 exit status
aux/broker/tests/CMakeFiles/broker-stream-benchmark.dir/build.make:100: recipe for target 'aux/broker/bin/broker-stream-benchmark' failed
make[3]: *** [aux/broker/bin/broker-stream-benchmark] Error 1
make[3]: Leaving directory '/home/ubuntu/zeek/build'
CMakeFiles/Makefile2:580: recipe for target 'aux/broker/tests/CMakeFiles/broker-stream-benchmark.dir/all' failed
make[2]: *** [aux/broker/tests/CMakeFiles/broker-stream-benchmark.dir/all] Error 2
make[2]: Leaving directory '/home/ubuntu/zeek/build'
Makefile:149: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/ubuntu/zeek/build'
Makefile:15: recipe for target 'all' failed
make: *** [all] Error 2
`

OS: Ubuntu 16.04
GCC: 4.8.5
G++: 4.8.5

I really appreciate any help.

Thanks.

**Comment by jsiwek** [comment]
Can you please give more explicit explanation of what you are trying, including which Bro/Zeek version, how you're downloading it (git versus source code tarfile), and what commands were used to configure/build it ?

We do continuously run builds/tests on Ubuntu 16.04 (GCC 4.8.4) and it hasn't shown any problems lately, in case that's a helpful point of reference: https://travis-ci.com/zeek/zeek/jobs/229085728

If you were downloading Zeek/Bro from git and had been changing between release versions, forgetting to update git submodules can be a common source of error.  If that was the case, may be easiest to just start from scratch and try the latest development version.

```
git clone --recursive https://github.com/zeek/zeek
cd zeek
./configure
make
make install
```

**Comment by mengzhisha** [comment]
@jsiwek Thanks！I solved it.
