### ISSUE TITLE
Zeek rotation

### ISSUE THREAD

**Issue by Afonin17** [zeek/zeek#568]
Hi!
My bro version is 2.6.1.
I want bro not to rotate files at all and to do nothing with current logs dir.
I know about zero value for "LogRotationInterval" parameter, but this does not solve the problem entirely.

**Comment by jsiwek** [comment]
If you mean you want no rotation during operation and also for the logs to remain where they are when stopping/terminating, then you can probably get what you want like with a combination of adding/changing these options in `broctl.cfg`:

```
CompressLogs = 0
LogRotationInterval = 0
MakeArchiveName = /Users/jon/stop-log-rotation
```

Where you'd change `/Users/jon/stop-log-rotation` to point to a executable script of your own choosing, but with these same contents:

```
#! /usr/bin/env bash

echo "current/$1"
```

Then logs will remain in `$install_prefix/logs/current` when stopping, but be overwritten after restarting.

If that doesn't help do what you want, then please give more information including:

* contents of your `broctl.cfg`
* contents of your `node.cfg`
* more explanation of what you observe happening
* what you want to actually happen instead

**Comment by Olerdrive** [comment]
Hello! We have already tried the way you described, this almost solves the problem. But we also need existing logs not to be deleted/overwritten during restarts: we want logrotate to do all the job about rotating the logs.


BTW our primary goal is to rotate logs depending on their size, not only periodically. If there's a way to make bro rotate logs this way please help us find it out

**Comment by jsiwek** [comment]
@Olerdrive possibly by using an additional postprocessing script that you stick in `$install_prefix/share/zeekctl/scripts/postprocessors/`.

E.g. using the same `zeekctl.cfg` I described before with:

```
CompressLogs = 0
LogRotationInterval = 0
MakeArchiveName = /Users/jon/stop-log-rotation
```

And adding the following postprocessing script:

```
$ cat /usr/local/zeek/share/zeekctl/scripts/postprocessors/logrotate 
#!/bin/bash

if [ -f $1 ]; then
    logrotate --state /home/jon/tmp/zeek-logrotate-status.tmp /home/jon/tmp/zeek-logrotate.conf
fi
```

With the `logrotate` config file:

```
/usr/local/zeek/logs/current/*.log {
    compress
    rotate 3
    maxsize 1
    olddir /usr/local/zeek/logs/old
}
```

After starting/stopping the cluster a few times, I see the logs moved from `logs/current/` to `logs/old/` according to the `logrotate` config.

**Comment by Olerdrive** [comment]
That's nice, but i run logrotate periodically via cron, that's why i want log files not be overwritten any more during restarts

I have tried to comment out `rm -f $file_name` line in the archive-log script, but this hasn't helped
