### ISSUE TITLE
redef'ing a non-existent enum generates an Assertion failure

### ISSUE THREAD

**Issue by vpax** [zeek/zeek#570]
The following simple script:
`redef enum foo += { bar };` 
generates a reasonable error, but that's followed by an Assertion failure: 
> error in ./bug.bro, line 1: unknown identifier (foo)
> Assertion failed: (cur_enum_type), function yyparse, file parse.y, line 818.

The first is fine, the second is tacky :-P.

**Comment by jsiwek** [comment]
This is already fixed via #959 (in Zeek v3.2.0+).
