### ISSUE TITLE
bro-config.h isn't available to legacy plugins

### ISSUE THREAD

**Issue by dcode** [zeek/zeek#584]
I ran into a related issue (J-Gras/bro-af_packet-plugin#11) and have tracked it down that the current release/3.0 build install `bro-config.h` along with `zeek-config.h`, but the CMake scripts fail to add `/usr/include/bro` to the include path. I've dug through the CMake scripts a bit, but haven't figured out where this should be happening. Maybe it needs to happen some how in `zeek-config` binary? It's not really clear to me, but the compatibility layer isn't currently working without plugin authors manually prefixing all their includes with "bro".

**Comment by jsiwek** [comment]
I can't reproduce this, building the AF_Packet plugin works for me w/ 3.0.  Might help if you give more explicit directions to reproduce if the following details don't help you figure out what's going on.

There's a couple different ways to configure the plugin:

1. Using just `./configure` and relying on `bro-config` (`zeek-config`) to set the right include path.

Relevant code is here:

https://github.com/J-Gras/bro-af_packet-plugin/blob/5736d8a7d3bb98d4c6232f0607738026dbc050ec/configure#L124

So potential pitfall could be if it's picking up the `bro-config` in your `PATH` from a different installation and reporting the wrong path.  What's the output of your `bro-config --include_dir` ?

2. Using `./configure --bro-dist=/path/to/zeek-src`

Relevant code that sets the include path here:

https://github.com/zeek/cmake/blob/58e4eebe3aebd0cf608e51046805a9ab1ffa6c1b/ZeekPluginDynamic.cmake#L61

And the `bro-config.h` will get put at that location via:

https://github.com/zeek/zeek/blob/d4fc1fabc896d0f8bdafae2ed2b3490c744f2d3b/CMakeLists.txt#L299-L302

So seeing as either way seems to work from a clean install of `release/3.0` for me, I wonder if you're potentially running into a case where it's an upgrade from a previous version and/or there's some environment inconsistency picking up pieces from the wrong installation.

**Comment by dcode** [comment]
**EDIT**: I found my issue. I'm leaving below for context, but I was installing `bro-config.h` into `/usr/include/bro/`, which is incorrect. There's a typo in another patch that I'm working on for GNUInstallDIrs.

---

Admittedly, I'm not using the canonical build environment, I'm building RPMs to support EPEL7 and ultimately the upstream (from EPEL) Fedora packages.

`bro-config` is a symlink to `zeek-wrapper`, which ultimately calls `zeek-config`. When I run `bro-config --include_dir` I get the following:

```
Warning: Use of 'bro-config' is deprecated. It is linked to a wrapper that
         will be removed in the future. Please use 'zeek-config' instead.

include/zeek
```

But this doesn't provide `include/bro`, which is where `bro-config.h` is stored, and is the file that `AF_Packet.cc` is looking for. Now, I can inject that path in the spec file in the `CXX_FLAGS` var, but that's just a hack that moves me forward and doesn't help everyone else.

:point_up: 💡
