### ISSUE TITLE
How to analyze pcap file using zeek on windows

### ISSUE THREAD

**Issue by asif48** [zeek/zeek#587]
Very basic question...

How can I analyze the pcap files using zeek on windows...
I have downloaded the stable release from the github but during unzip it breaks. 
The setup I have downloaded 
1) https://www.zeek.org/download/index.html
2) Github
Both breaks during unzipped...

plz guide

**Comment by jsiwek** [comment]
Hi, we don't support native Windows, but you might consider using Linux in a virtual machine (e.g. VMware, Virtualbox, or Windows Subsystem for Linux) and run Zeek within.

(But also the other issue about just not being able to unzip sounds like maybe Windows can't unzip `.tar.gz` by default and you might need a separate application for it.  E.g. 7-Zip)

**Comment by asif48** [comment]
I have applied multiple 3rd party tools for unzipping but no one works...
Yes zeek works on Linux so I am going for Linux VM...

**Comment by timwoj** [comment]
The problem with unzipping is that we have some symlinks that are part of the distributions. If you try to unzip (or untar) the releases on Windows, it can't create those symlinks.

```
$ tar -xzf zeek-3.0.0.tar.gz
tar: zeek-3.0.0/INSTALL: Cannot create symlink to ‘doc/install/install.rst’: No such file or directory
tar: zeek-3.0.0/aux/broctl: Cannot create symlink to ‘zeekctl’: No such file or directory
tar: zeek-3.0.0/aux/zeekctl/README.rst: Cannot create symlink to ‘doc/zeekctl.rst’: No such file or directory
tar: zeek-3.0.0/aux/netcontrol-connectors/README.md: Cannot create symlink to ‘README’: No such file or directory
tar: zeek-3.0.0/doc/install/CHANGES-capstats.txt: Cannot create symlink to ‘../../aux/broctl/aux/capstats/CHANGES’: No such file or directory
tar: zeek-3.0.0/doc/install/CHANGES-broctl.txt: Cannot create symlink to ‘../../aux/broctl/CHANGES’: No such file or directory
tar: zeek-3.0.0/doc/install/CHANGES-pysubnettree.txt: Cannot create symlink to ‘../../aux/broctl/aux/pysubnettree/CHANGES’: No such file or directory
tar: zeek-3.0.0/doc/install/CHANGES-trace-summary.txt: Cannot create symlink to ‘../../aux/broctl/aux/trace-summary/CHANGES’: No such file or directory
tar: Exiting with failure status due to previous errors
```

Note that the above is running within a mingw shell so it knows what symlinks are. The source code zip file does roughly the same thing.
