### ISSUE TITLE
set[enum] options can't be set and lead to a segfault?

### ISSUE THREAD

**Issue by grigorescu** [zeek/zeek#591]
There are a few `option` variables that ship with Zeek which are of type `set[enum]`, namely:

* DPD::ignore_violations
* Notice::alarmed_types
* Notice::emailed_types
* Notice::ignored_types
* Notice::lookup_location_types
* Notice::not_suppressed_types
* SMB::logged_file_actions

From what I can tell, to set these without `redef` needs some really convoluted Zeek scripting. A sample btest, with 2 failures and 1 method that finally works is available at: https://gist.github.com/grigorescu/66b02bd47e5235f15ff231f560ced696

The situation is even worse when trying to set these values via the config input reader, as it generally causes a segfault. btests here: https://gist.github.com/grigorescu/3a02153e03896697a96178eac067b50c

Assigning an empty enum works, but trying to assign an actual enum causes a segfault.

**Comment by jsiwek** [comment]
Examples should be fixed via #617 now in `master` and `release/3.0` (except the ones using `{}`, which might be more along the lines of requiring a script-language enhancement rather than fixing a bug).
