### ISSUE TITLE
Possible JSON logging performance regression

### ISSUE THREAD

**Issue by jsiwek** [zeek/zeek#595]
Keith reported to me a possible loss of performance in the JSON logging of Zeek 3.0.0 versus Bro 2.6.4, so I did a quick benchmark using this `test.zeek`:

```zeek
option log_mult = 0;

event connection_state_remove(c: connection) &priority=-10
  {
  local n = log_mult;

  while ( n > 0 )
    {
    Log::write(Conn::LOG, c$conn);
    --n;
    }
  }
```

```
# Zeek 3.0.0 JSON logging
time -f "%e %M" zeek -G random.seed -r 2009-M57-day11-18.trace test.zeek log_mult=100 LogAscii::use_json=T
45.00 946668

# Bro 2.6.4 JSON logging
time -f "%e %M"  bro -G random.seed -r 2009-M57-day11-18.trace test.zeek log_mult=100 LogAscii::use_json=T
15.79 140820

# Zeek 3.0.0 ASCII logging
time -f "%e %M" zeek -G random.seed -r 2009-M57-day11-18.trace test.zeek log_mult=100 LogAscii::use_json=F
14.29 156476

# Bro 2.6.4 ASCII logging
time -f "%e %M"  bro -G random.seed -r 2009-M57-day11-18.trace test.zeek log_mult=100 LogAscii::use_json=F
15.77 149264

# Zeek 3.0.0 JSON logging, patched to use default nlohmann json object instead of fifo_map
time -f "%e %M" zeek -G random.seed -r 2009-M57-day11-18.trace test.zeek log_mult=100 LogAscii::use_json=T
21.96 615240
```

And some flamegraphs:

[bro-2.6.4-json.zip](https://github.com/zeek/zeek/files/3649495/bro-2.6.4-json.zip)

11.79% spent in `threading::formatter::JSON::Describe()`

[zeek-3.0.0-json-fifo-map.zip](https://github.com/zeek/zeek/files/3649498/zeek-3.0.0-json-fifo-map.zip)

63.52% spent in `threading::formatter::JSON::Describe()`

[zeek-3.0.0-json-default.zip](https://github.com/zeek/zeek/files/3649497/zeek-3.0.0-json-default.zip) (not using fifo_map)

44.72% spent in `threading::formatter::JSON::Describe()`

So at least a good portion of the time relates to the ordering of JSON output.  Maybe making that a Zeek configuration option would be something to partially help the loss of performance here.

@timwoj other ideas for things that could help here?  Is there anything related to "correctness" of the JSON output in Zeek 3.0.0 versus that of Bro 2.6.4 that helps justify some of the difference ?  Or is it clearly just a performance difference between two json-formatting implementations (ours vs. nlohmann) ?

it's also possible my test case is too contrived and hitting some new worst-case scenario we never really expect, but doubt it.

**Comment by timwoj** [comment]
My guess (without looking too closely) is that it's almost entirely the difference between our naive append-to-a-string implementation and the nlohmann library. There's time spent in the library creating the objects and then converting the into a string. I can look at whether there's faster ways to do that.

nlohmann's also isn't the fastest json library out there. It's in the middle-to-bottom of the pack when it comes to stringifying (https://github.com/miloyip/nativejson-benchmark#stringify-time).

**Comment by sethhall** [comment]
Thanks for doing the comparison Jon!  Unfortunately, this feels to me like one of those critical issues that we'll need to move on pretty quickly since under high logging volume it appears to cause so much overhead (I had been looking at this with Keith recently too)

**Comment by sethhall** [comment]
Oh, I also think we should target this as a fix to 3.0 (3.0.1) in addition to 3.1.0.

**Comment by jsiwek** [comment]
> I also think we should target this as a fix to 3.0 (3.0.1)

My thought too, I'll create a 3.0.1 project/milestone and add this.

**Comment by timwoj** [comment]
Part of this is that `fifo_map` can be very slow:

> Inserting a value (via operator[], insert) and removing a value (erase) rely on std::unordered_map::insert and std::unordered_map::erase which have O(1) average complexity and O(n) worst-case complexity.

We're forced to use `fifo_map` though to preserve the ordering of keys as they're inserted.

**Comment by timwoj** [comment]
Switching over to use `tsl/ordered_map` gives close to the same performance as without ordering:

no ordering:
```
real	0m51.466s
user	1m9.390s
sys	0m7.144s
```

`ordered_map`:
```
real	0m54.723s
user	1m12.826s
sys	0m7.293s
```

There's also some minor sub-second gains to be found using `emplace()` instead of `operator[]` for adding values, but `emplace` has the same issues as with any map where if the key already exists it won't overwrite it.

**Comment by jsiwek** [comment]
@timwoj Thanks for taking a look.  #600 does seem to help a lot.  In a release build, the test commands with `log_mult=100` I gave earlier are comparable between 3.0.0 and 2.6.4, but can still crank it to `log_mult=1000` and see 3.0.0 taking 1.4x longer than 2.6.4.

Not sure exactly what difference we ultimately want to accept.  Since the change to the tsl map is just better than fifo_map regardless, I'd be up for merging #600 (after my minor comments are addressed) and asking Keith to help test if it performs well enough and go from there.  Other ideas?

**Comment by timwoj** [comment]
> Not sure exactly what difference we ultimately want to accept. Since the change to the tsl map is just better than fifo_map regardless, I'd be up for merging #600 (after my minor comments are addressed) and asking Keith to help test if it performs well enough and go from there. Other ideas?

Right now the two major bottlenecks are:
1. Building JSON tree
2. Dumping the JSON tree to the ODesc object

Both of these happen a ton of times (~20k times on the `2009-M57-day11-18.trace` file). Unfortunately, it happens repeatedly just because of the way that we log values, and any change to that would obviously require a ton of changes. The speedups in the PR are mostly fixing the first part, since we were using a map object with potentially-slow insertion times. I don't think there's any way to speed up the second part since it's literally a single call to a method that turns the json object into a string.

Unless there's some magic juice somewhere in nlohmann/json, I don't think we can get much more out of it.

**Comment by jsiwek** [comment]
Just keeping this open until we get more feedback (e.g. from Keith) and then decide from there whether we want to look into more extreme changes to help performance.

**Comment by klehigh** [comment]
I ran the 3.0 release branch and tracked the lag between write_ts and current time.  It took 15 minutes to build up 15 minutes of lag time.  I tested with master (which has all the changes above) and it took 1 hour to build up 15 minutes of lag.  So there is definite improvement, but still not close to being able to keep up with our volume.

**Comment by timwoj** [comment]
I'm a little confused. The release branch and master should be nearly identical when it comes to JSON performance. Did you try the release branch or just a zip from the release?

**Comment by klehigh** [comment]
Oops.  Sorry, I meant the 3.0 release.  It was the official release.

**Comment by timwoj** [comment]
I switched over to use rapidjson on the `topic/timw/595-rapidjson` branch to test the performance difference between that and nlohmann json. Here are some updated numbers:

# Bro 2.6.4
```
tim$ gtime -f "%e %M"  bro -G projects/zeek/testing/btest/random.seed -r projects/2009-M57-day11-18.trace test.zeek log_mult=100 LogAscii::use_json=T
13.29 158572
```

# Zeek 3.0
```
tim$ gtime -f "%e %M" zeek -G projects/zeek/testing/btest/random.seed -r projects/2009-M57-day11-18.trace test.zeek log_mult=100 LogAscii::use_json=T
22.18 760040
```

# Zeek `master`
```
tim$ gtime -f "%e %M" zeek -G projects/zeek/testing/btest/random.seed -r projects/2009-M57-day11-18.trace test.zeek log_mult=100 LogAscii::use_json=T
14.44 467976
```

# Zeek `topic/timw/595-rapidjson`
```
tim$ gtime -f "%e %M" zeek -G projects/zeek/testing/btest/random.seed -r projects/2009-M57-day11-18.trace test.zeek log_mult=100 LogAscii::use_json=T
11.42 242644
```

@klehigh Can you give that branch a try and report back?

**Comment by rsmmr** [comment]
Interesting, that looks quite promising!

**Comment by klehigh** [comment]
using the rapidjson branch, it took about ~ 2 hours to build up 15 minutes of lag.  Memory usage for the logger process started to grow after a short bit.  i also noticed that file rotation was lagging w/i ~ 80 minutes (restarted @ 1638 UTC, log rotation at 1800 was off by 2 minutes).  Is there better data I could provide to help?

**Comment by timwoj** [comment]
> using the rapidjson branch, it took about ~ 2 hours to build up 15 minutes of lag. Memory usage for the logger process started to grow after a short bit. i also noticed that file rotation was lagging w/i ~ 80 minutes (restarted @ 1638 UTC, log rotation at 1800 was off by 2 minutes). Is there better data I could provide to help?

@klehigh Can you clarify this a bit more? Is the lag time a significant difference from 2.6.4? Is there no lag at all on 2.6.4? The rapidjson code doesn't appear to be leaking memory anywhere, so the increase in memory usage is likely just due to the backlog of data waiting to be written out.

For file rotation, that shouldn't be affected by these changes. It might be a separate bug.

**Comment by timwoj** [comment]
@klehigh Ping on the questions above

**Comment by timwoj** [comment]
I ran the `595-rapidjson` branch through the new leak testing using AddressSanitizer and it came back with no findings as well.

**Comment by klehigh** [comment]
@timwoj : With our current logging configuration, we don't see lag on 2.6.4.

**Comment by dougburks** [comment]
For folks logging in JSON, is there an official recommendation that they go ahead and deploy 3.0.1 OR wait for 3.1.0?

**Comment by jsiwek** [comment]
@dougburks I suggest trying 3.0.1 whenever and share experiences.  Unless there's a large amount of bad feedback, I prefer not porting into 3.0.x the proposed switch to rapidjson that's planned for 3.1.0.  There's also the fact that 3.0.x is essentially the LTS branch and 3.1.x will be a potentially-less-stable-feature branch that may help guide "upgrade now or wait" decisions.

**Comment by dougburks** [comment]
@jsiwek Thanks for the quick response and the clarification on LTS vs 3.1.x!  If we have feedback to share regarding 3.0.1 JSON performance, would you like that shared via this github issue?

**Comment by jsiwek** [comment]
@dougburks yeah, sharing feedback in this issue is fine

**Comment by klehigh** [comment]
Did some initial testing with the most recent change by @timwoj.  Not an apples to apples comparison to our previous work because we're using pooled loggers.  With two logger processes, we keep up fine, memory usage looks good and lag has stayed around 1 minute.
However, log rotation fired off once (we rotate every 15 minutes).  Then one logger process ran for an hour without rotating, the other logger process rotated logs after 38 minutes.
No errors in logs to point to an issue with the rotation.

**Comment by timwoj** [comment]
> Did some initial testing with the most recent change by @timwoj. Not an apples to apples comparison to our previous work because we're using pooled loggers. With two logger processes, we keep up fine, memory usage looks good and lag has stayed around 1 minute.

From your previous findings, that's great to hear. The last set of changes in the PR made a big difference in the performance and memory usage of the rapidjson branch so it should be as good or better than 2.6.4 at this point.

> However, log rotation fired off once (we rotate every 15 minutes). Then one logger process ran for an hour without rotating, the other logger process rotated logs after 38 minutes.

Like I said before there shouldn't be anything in these changes that affects file rotation so it's probably a separate bug. Can you write up a separate GHI for it and we'll track it down there?

**Comment by rsmmr** [comment]
RapidJSON has been merged.
