### ISSUE TITLE
zeek record the wrong mac address information

### ISSUE THREAD

**Issue by siemenslt123** [zeek/zeek#597]
when I use zeek (version: 2.5) to analyze the 5355udp.pcap in the attach file, I want to get the mac address information, 
In the pcap side:
                                         IP : 192.168.1.202----->00:1b:1b:82:89:ea
                                         IP:  192.168.1.203----->00:1b:1b:82:89:fb

After zeek analyzed, in the conn.log,
                                         IP : 192.168.1.202----->00:1b:1b:82:89:fb
                                         IP:  192.168.1.203----->00:1b:1b:82:89:ea

so I am confused,  anyone could help me ? Thanks so much!

[udp5355.zip](https://github.com/zeek/zeek/files/3650769/udp5355.zip)

**Comment by rsmmr** [comment]
I ran your trace with 2.6 and output is matching what the pcap side says:

```
# bro -v
bro version 2.6.4-debug
# bro -r udp5355.pcap protocols/conn/mac-logging
# cat conn.log | bro-cut id.orig_h orig_l2_addr
192.168.1.202	00:1b:1b:82:89:ea
192.168.1.202	00:1b:1b:82:89:ea
192.168.1.202	00:1b:1b:82:89:ea
192.168.1.202	00:1b:1b:82:89:ea
192.168.1.202	00:1b:1b:82:89:ea
192.168.1.202	00:1b:1b:82:89:ea
```

**Comment by siemenslt123** [comment]
> I ran your trace with 2.6 and output is matching what the pcap side says:
> 
> ```
> # bro -v
> bro version 2.6.4-debug
> # bro -r udp5355.pcap protocols/conn/mac-logging
> # cat conn.log | bro-cut id.orig_h orig_l2_addr
> 192.168.1.202	00:1b:1b:82:89:ea
> 192.168.1.202	00:1b:1b:82:89:ea
> 192.168.1.202	00:1b:1b:82:89:ea
> 192.168.1.202	00:1b:1b:82:89:ea
> 192.168.1.202	00:1b:1b:82:89:ea
> 192.168.1.202	00:1b:1b:82:89:ea
> ```

**Comment by siemenslt123** [comment]
so I should upgrade the zeek version to solve this problem? why does it run with 2.5 , the output is wrong ?

**Comment by rsmmr** [comment]
I don't recall if there was a problem with 2.5 in this regard, but yes, I would recommend upgrading. 2.5 is quite old at this point and no longer maintained.

**Comment by siemenslt123** [comment]
> I don't recall if there was a problem with 2.5 in this regard, but yes, I would recommend upgrading. 2.5 is quite old at this point and no longer maintained.

ok, got it , thank you so much!
