### ISSUE TITLE
to_json doesn't print sets with multiple index types correctly

### ISSUE THREAD

**Issue by grigorescu** [zeek/zeek#598]
`FTP::cmd_reply_code` is of type `set[string, count]`.

In 3.0, `to_json` only prints the string elements, i.e. `["STOU","PASS","RETR","STAT","REST","DELE","LIST","PASS","PASS","CLNT","ALLO","OPTS","ALLO","APPE","STOU"`

**Comment by jsiwek** [comment]
Thanks, yeah, looks like a bug in `set` with composite keys.  But `table` surprisingly seems to work.   Example test case / repro:

```zeek
local s: set[string, count] = set();

add s["one", 1];
add s["two", 2];
add s["three", 3];

print to_json(s);

local t: table[string, count] of string = table();

t["one", 1] = "a";
t["two", 2] = "b";
t["three", 3] = "c";

print to_json(t);
```

**Comment by timwoj** [comment]
Tables currently output multi-part keys as a formatting string. Should multi-part keys in sets output the same way or should it be an array of arrays?

**Comment by jsiwek** [comment]
While either should technically work, I'm leaning toward array-of-arrays.

If we were aiming for maximum consistency, then both `table` and `set` would be json-objects with stringified  json-values for keys.  Then for `set` we'd also use some empty-value like 0 or "".

For that format of `table`, upside is that it's a more natural/readable way to express the data (easier to see and operate with mappings), downside is that it requires stringifying json-values for the keys.

For that format of `set`, there's no mapping/association to care about anymore, so json-array starts to seem better than json-object (thus no requirement to stringify json-values for use as keys), plus the addition of empty-values seems wasteful/noisy.

**Comment by timwoj** [comment]
I opted for an array-of-arrays since it's more json-like.
