### ISSUE TITLE
Values are being created for unset Vector elements when output via JSON

### ISSUE THREAD

**Issue by philrz** [zeek/zeek#606]
Consider this Zeek script:

```
module VectorFun;

export {
    redef enum Log::ID += { LOG };

    type Info: record {
        ts:            time &log;
        vector_str:    vector of string &log;
        vector_int:    vector of int &log;
        };
    }
    
global gapper_str: vector of string;
global gapper_int: vector of int;

event bro_init()
    {
    Log::create_stream(VectorFun::LOG, [$columns=VectorFun::Info, $path="VectorFun"]);

    gapper_str[0] = "before";
    gapper_str[2] = "after";
    gapper_str[3] = "-";
    gapper_str[4] = "";
    
    gapper_int[0] = 123;
    gapper_int[2] = 456;
    
    Log::write(VectorFun::LOG, [$ts=network_time(),
                                $vector_str=gapper_str,
                                $vector_int=gapper_int]);
    }                           
```

When the log line is written with the default ASCII TSV format, it looks like:

```
#separator \x09
#set_separator	,
#empty_field	(empty)
#unset_field	-
#path	VectorFun
#open	2019-09-27-12-24-51
#fields	ts	vector_str	vector_int
#types	time	vector[string]	vector[int]
0.000000	before,-,after,\x2d,(empty)	123,-,456
#close	2019-09-27-12-25-11
```

Note how the gap for the unset element in both vectors is represented as the `unset` value. This is what I'd expect.

Now I `redef LogAscii::use_json = T;` and observe the generated log line:

```
{"ts":0.0,"vector_str":["before","","after","-",""],"vector_int":[123,0,456]}
```

Note how the gap for the unset element of the string vector has been represented as an empty string, and for the integer vector it's a `0`. These are not representative of (non-) values these had been inside Zeek. Note also how for the string case this means that we've lost the ability to differentiate between what had started inside Zeek as an empty string vs. an unset element.

For the JSON case, this feels like a bug, as I'd expected it to represent the unset values in JSON as `null`. Or maybe someone can rationalize the current behavior as desirable?

**Comment by timwoj** [comment]
I agree with using `null` to represent "empty" values in vectors.

As a secondary bug to this one, `print` doesn't event generate valid JSON in this case.

```
local v: vector of int;
v[0] = 1;
v[2] = 2;
print(v);
```

prints out `[1, , 2]`

**Comment by philrz** [comment]
@timwoj: What version of Bro/Zeek are you using? I initially ran into an issue like the one you just described, but then I thought to try Zeek v3.0.0 and found it worked ok there. I then saw the release note about the new JSON library in v3.0.0, so it looked to me like that behavior has already been fixed.

**Comment by timwoj** [comment]
That's on a branch very close to `master`.

**Comment by philrz** [comment]
Oh. On second though, I overlooked the fact you're using `print`. I was only concerned with output after it went through the JSON logger. I'm not familiar enough with `print` to know if one should even expect valid JSON. The [docs](https://docs.zeek.org/en/stable/script-reference/statements.html#keyword-print) look pretty brief.

**Comment by timwoj** [comment]
Actually, it helps if I call `to_json` along with print. In that case all it does is segfault. 🤦‍♂ 

I'll take a look at it.

**Comment by timwoj** [comment]
@philrz Can you see if the above commit fixes what you need?

**Comment by philrz** [comment]
@timwoj: Yes, that now does what I was expecting!

```
{"ts":0.0,"vector_str":["before",null,"after","-",""],"vector_int":[123,null,456]}
```

Thanks for the quick turnaround!
