### ISSUE TITLE
how to set the zc worker's number and pin cpus' number?some cpus can'not work now.

### ISSUE THREAD

**Issue by husterzlc** [zeek/zeek#608]
Hello,i have some problems now.Our server 's logitic cpu's number is 64,and memory is 256G.And my network interface is ixgre.It's10Git.I have bought a licence for it.
But when i set the node.cfg,some problems occured.Below is my node.cfg:
[logger] 
type=logger
host=localhost
[manager]
type=manager
host=localhost
[proxy-1]
type=proxy
host=localhost
[worker-1]
type=worker
host=localhost
lb_method=pf_ring
lb_procs=16
pin_cpus=0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
interfaces=zc:enps0f0
[worker-2]
type=worker
host=localhost
lb_method-pf_ring
lb_procs=16
pin_cpus=16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31

Only the worker1 workered.The worker2 didn't solve any packages at all.And when i set the 32 pin_cpus in the same worker, i got segment fault.
How to set the node's config? Please.

**Comment by rsmmr** [comment]
We don't use GitHub issues for support questions, please ask on the the mailing list.
