### ISSUE TITLE
Escaped characters in JSON log format changed with Zeek v3.0.0

### ISSUE THREAD

**Issue by philrz** [zeek/zeek#609]
Consider the following Zeek script that logs a string containing lots of unprintable characters:

```
module Escape;
 
export {
    redef enum Log::ID += { LOG };
 
    type Info: record {
        ts:            time &log;
        my_str:        string &log;
        };
    }
     
event bro_init()
    {
    local unprintables="before\xc3\xabj\xc3\xb0\xc3\xac\xe2\x80\xb0\xc2\xa0r\xc3\xb1\xc3\xb1co\\m2\xc3\xbf\xc2\xaab\x02\x1f\x1c\xc3\xb6h\xc2\xb9\xc3\xb2:g\xc3\xa6\xc3\xa49w\xc2after";

    Log::create_stream(Escape::LOG, [$columns=Escape::Info, $path="escape"]);
 
    Log::write( Escape::LOG, [$ts=network_time(),
                              $my_str=unprintables]);
    }
```

In both Zeek v2.6.4 and v3.0.0, these are represented in a TSV log file with the expected `\x` format for the escape characters.

```
#separator \x09
#set_separator	,
#empty_field	(empty)
#unset_field	-
#path	escape
#open	2019-09-30-10-39-35
#fields	ts	my_str
#types	time	string
0.000000	before\xc3\xabj\xc3\xb0\xc3\xac\xe2\x80\xb0\xc2\xa0r\xc3\xb1\xc3\xb1co\\m2\xc3\xbf\xc2\xaab\x02\x1f\x1c\xc3\xb6h\xc2\xb9\xc3\xb2:g\xc3\xa6\xc3\xa49w\xc2after
#close	2019-09-30-10-40-03
```

As for JSON format output (`redef LogAscii::use_json = T;`), in Zeek v2.6.4, these were printed with what I understand to be the standard `\u` notation for JSON escape characters:

```
{"ts":0.0,"my_str":"before\u00c3\u00abj\u00c3\u00b0\u00c3\u00ac\u00e2\u0080\u00b0\u00c2\u00a0r\u00c3\u00b1\u00c3\u00b1co\u005cm2\u00c3\u00bf\u00c2\u00aab\u0002\u001f\u001c\u00c3\u00b6h\u00c2\u00b9\u00c3\u00b2:g\u00c3\u00a6\u00c3\u00a49w\u00c2after"}
```

But it seems this has changed in Zeek v3.0.0 to something more like the `\x` format:

```
{"ts":0.0,"my_str":"beforeëjðì‰ rññco\\m2ÿªb\\x02\\x1f\\x1cöh¹ò:gæä9w\\xc2after"}
```

Is this behavior intentional? I saw mention in the v3.0.0 release notes about the move to the new JSON library and how `Log files now escape non-printable characters consistently as "\xXX"`, but it wasn't clear if the latter was meant to apply even to JSON format logs. Considering that I know many Zeek users use JSON output so they can ingest their logs into tools like Elasticsearch that are accustomed to standard JSON, I'd expect achange in how escaping is done could be disruptive for them.

**Comment by philrz** [comment]
As a follow-up to my last comment, I went ahead and ingested the JSON representations of the events into Elasticsearch, then brought them up in Kibana. In this screenshot, the top event is the Zeek v2.6.4 one and the bottom is from Zeek v3.0.0.

![image](https://user-images.githubusercontent.com/5934157/65912073-759d2f80-e382-11e9-8ec5-76448b666e6d.png)

Picking off a specific character, note how the first character after the "before" is rendered as Ã in the Zeek v2.6.4 event. [Docs](https://www.compart.com/en/unicode/U+00C3) say this character is U+00C3, so that seems to match up with the escaping being `\u00c3` in v2.6.4 event and `\xc3` in the TSV representation. Meanwhile the lower event shows other gobbletygook that I can't explain.

Finally, if I actually type a Ã into the Filter bar in Kibana, it matches only the top event.

Taken all together, this makes me further suspect the Zeek v3.0.0 behavior is buggy.

**Comment by timwoj** [comment]
JSON in 3.0.0 changed to output UTF-8 when such characters were found in the data, or `\x` escape any bytes that weren't recognized as valid chracters.

**Comment by sethhall** [comment]
Just to expand a bit on what Tim said, the way we were doing it before was technically not proper.  The problem we are encountering here is that there is technically no way according to any of the JSON specs to carry non-UTF8 data in JSON strings.  The specs actually say that even if you are doing the '\u' encoding that the resulting bytes need to be valid UTF-8 code points (at least that is the way I interpreted the specs).  Ignoring that, it's still difficult to determine if that's two bytes or one because it could easily be interpreted as a null by followed by the byte that we were actually encoding. We ended up chosign to use this weird self-defined escaping mechanism of having a literal backslash with the hex bytes because it puts it in your control to interpret the data however required.

So, now that I wrote all of that, I tried your test script and I'm seeing the same behavior as you and I'm a little surprised.  Those aren't valid UTF-8 code points in the test and they aren't being escaped correctly.

**Comment by timwoj** [comment]
The issue here is that 2.6.4 actually over-escapes the bytes in the input data. For example, it takes `\xc3\xab` which is a valid utf-8 character and turns it into `\u00c3\u00ab`. The changes in 3.0 assume that input data is utf-8 and if we detect UTF-8 characters in that input data, they'll just get passed along unmodified.

**Comment by jsiwek** [comment]
I think the JSON / UTF-8 formatting in Zeek 3.0.0 looks right.

Here's how Python decodes the same string:

```
# The literal string pasted from Zeek
>>> b"before\xc3\xabj\xc3\xb0\xc3\xac\xe2\x80\xb0\xc2\xa0r\xc3\xb1\xc3\xb1co\\m2\xc3\xbf\xc2\xaab\x02\x1f\x1c\xc3\xb6h\xc2\xb9\xc3\xb2:g\xc3\xa6\xc3\xa49w\xc2after".decode('utf-8')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 51: invalid continuation byte

# Fine, it's not entirely valid UTF-8 due to last \xc2, so escape that
>>> b"before\xc3\xabj\xc3\xb0\xc3\xac\xe2\x80\xb0\xc2\xa0r\xc3\xb1\xc3\xb1co\\m2\xc3\xbf\xc2\xaab\x02\x1f\x1c\xc3\xb6h\xc2\xb9\xc3\xb2:g\xc3\xa6\xc3\xa49w\xc2after".decode('utf-8', 'backslashreplace')
'beforeëjðì‰\xa0rññco\\m2ÿªb\x02\x1f\x1cöh¹ò:gæä9w\\xc2after'

# Here's the string just pasted from the Zeek JSON log for comparison
>>> 'beforeëjðì‰ rññco\\m2ÿªb\\x02\\x1f\\x1cöh¹ò:gæä9w\\xc2after'
'beforeëjðì‰\xa0rññco\\m2ÿªb\\x02\\x1f\\x1cöh¹ò:gæä9w\\xc2after'
```

So Python and Zeek seem to end up in a similar place.  The differences being:

* `\\x` versus `\x`.   For JSON output, `\x` is invalid and needs escaping.
* Python default behavior when running into invalid UTF-8 `\xc2` is an exception, but Zeek's is to just automatically escape it (and that's what we want)

**Comment by philrz** [comment]
Thanks for being so patient in explaining this one to me. I think I get it now, and I guess it looks like there's no bug here after all. I'll leave it up to you guys to decide if there's anything to come from this issue having been filed, e.g. if there's a more explicit release note justified.

**Comment by sethhall** [comment]
No worries!  We were just as confused as you at first and we had to chat a bit to figure out what was going on.

The reason your data coming from the "normal" TSV writer looks different is that the setting to enable UTF-8 TSV logs is disabled by default.  If you turn it on your TSV logs will look the same at the JSON (with possible escaping changes).
