### ISSUE TITLE
Read TCP option values 

### ISSUE THREAD

**Issue by phillipa** [zeek/zeek#618]
It would be nice if the tcp_options event (https://docs.zeek.org/en/stable/scripts/base/bif/plugins/Zeek_TCP.events.bif.zeek.html#id-tcp_option )
would allow the code to read the value of the given TCP option.

**Comment by jsiwek** [comment]
In #621, I added a new `tcp_options` event rather than alter the old one.  It contains the full list of TCP options along with their values.  Let me know if there's other things to include in the event that would be useful.
