### ISSUE TITLE
how can i config bro to let it only capture and analyze http packages?

### ISSUE THREAD

**Issue by husterzlc** [zeek/zeek#620]
Does it have this function? I just want to filter to only analyze http packages.And does it can reduce capture_loss rate via analyzing less packages? 
Thanks a lot.

**Comment by 0xxon** [comment]
Hi,

We don't use GitHub issues for support questions. Questions like this are best answered using our  mailing list, which is followed by Zeek developers and professional users. You can join here:

http://mailman.icsi.berkeley.edu/mailman/listinfo/zeek

Once you receive confirmation you’ve been added to the list, send this question there.
