### ISSUE TITLE
License fo OSFinger

### ISSUE THREAD

**Issue by pombredanne** [zeek/zeek#622]
In this file OSFinger.cc, https://github.com/zeek/zeek/blob/5d44735209b8285bd04e15847ff81f038e001a3a/src/OSFinger.cc we have this comment:
```
 Taken with permission from:
  p0f - passive OS fingerprinting (GNU LESSER GENERAL PUBLIC LICENSE)
...
(C) Copyright 2000-2003 by Michal Zalewski <lcamtuf@coredump.cx>
```
This was imported from SVN... @rsmmr do you recall what was the permission?
Does the LGPL apply or is this BSD-licensed like the rest of the codebase?

(Note this is likely gone in 3.x since I cannot see the file there anymore)

**Comment by timwoj** [comment]
I can't comment on the licensing, but OS fingerprinting was removed as part of #417 which was closed in 3.0.

**Comment by 0xxon** [comment]
This might actually be a question for @vpax. I think I remember that we have an ancient email about this somewhere...

**Comment by vpax** [comment]
Here's what I can quickly find from my email archives: 

> Date:  Mon, 20 Dec 2004 03:13:56 +0100 (CET)
> From:  Michal Zalewski <lcamtuf@coredump.cx>
> Subject:  Re: incorporating p0f into Bro
> To:  Vern Paxson <vern@icir.org>
> 
> On Sun, 19 Dec 2004, Vern Paxson wrote:
> 
> > Bro is distributed under a BSD-style license, as opposed to GPL.
> > Holger mentioned that he already discussed this with you and you were
> > fine with that (just as you were okay with the OpenBSD folks
> > incorporating it).  I just wanted to confirm that before we start
> > shipping the addition in the next Bro release.  Please let me know if
> > you have any problems with this.
> 
> Nope, that's fine :-)
> 
> /mz

**Comment by pombredanne** [comment]
@jsiwek Thank you ++ for this swift answer. You rock.
