### ISSUE TITLE
Whitespace at end of line in config reader

### ISSUE THREAD

**Issue by sethhall** [zeek/zeek#624]
Right now, if you have whitespace at the end of a line, the config reader will include it as part of the value (string) and I think it shouldn't do that.  An argument for changing the behavior is that this behavior is already inconsistent because you can't include whitespace at the beginning of a string.

**Comment by JustinAzoff** [comment]
Possibly relevant, a trailing comma also breaks sets:

    Site::local_nets	192.168.0.0/16,10.0.0.0/8,172.16.0.0/16,

triggers

    warning: bro.cfg/Input::READER_CONFIG: Could not convert line 'Site::local_nets	192.168.0.0/16,10.0.0.0/8,172.16.0.0/16,' to value. Ignoring line.

**Comment by sethhall** [comment]
For reference, Justin moved his comment into a separate ticket: https://github.com/zeek/zeek/issues/636
