### ISSUE TITLE
Container attributes are discarded on re-initialization 

### ISSUE THREAD

**Issue by jsbarber** [zeek/zeek#625]
I'm not completely sure this is a bug, but it was certainly hard to figure out. If it's not a bug, it seems like it's well worth having a big fat warning somewhere on the documentation page.

Essentially it's this. Given the table below:

```
global my_table: table[count] of string &create_expire=5sec;
...
event some_other_event()
{
    my_table[1] = "foo";
}

event bro_init()
{
    my_table = table();
}
```

The entry added in some_other_event will never expire. The re-initialization of `my_table` to an empty table discards all the attributes.

It's just counterintuitive to me that re-initializing a variable in effect changes its type.

**Comment by jsbarber** [comment]
Demonstration code that can be run on try.zeek.org with ssh.pcap (for example) as background.

```
redef table_expire_interval = 1sec;

function tt_expire(tt: table[count] of string, key: count): interval
{
    print "EXPIRE", key, tt[key];
    return 0sec;
}

global tt1: table[count] of string &create_expire=2sec &expire_func=tt_expire; 
global tt2: table[count] of string &create_expire=2sec &expire_func=tt_expire;

global serial: count = 0;

event fnext()
{
    serial += 1;
    tt1[serial] = "tt1";
    tt2[serial] = "tt2";
    schedule 1sec { fnext() };
}

event ffirst()
{
    schedule 1sec { fnext() };
}

event bro_init()
{
    tt2 = table();
    schedule 1sec { ffirst() };
}
```

**Comment by rsmmr** [comment]
Yeah, this is unfortunate. It's a known, broader issue with attributes. Fixing that has bested a few people over time already unfortunately, see https://github.com/zeek/zeek/issues/149.

Do you have a suggestion what a good place would be to document the behavior?

**Comment by jsbarber** [comment]
Even after looking at that other ticket, and reading the https://docs.zeek.org/en/stable/script-reference/attributes.html page again, I don't think I understand the issue well enough to give a great answer here. It appears that attributes are actually being applied to the initial _value_ of the container rather than the variable _holding_ the value? 

Anyway, I think a good first step would be a warning on the Attributes page, just below the initial attribute list. Because if a developer finds that the attributes are not working as expected, the first thing they're likely to try is to go back and re-read the documentation looking for behavioral hints. Possibly also a cross-reference in the Types page where the affected types are described.
