### ISSUE TITLE
add_clang_tidy_files not found

### ISSUE THREAD

**Issue by matthbr** [zeek/zeek#630]
Running configure on the version 3.0.0 leads to the error function add_clang_tidy_files not found and a subsequent failure of the configure script.
```
CMake Error at cmake/BifCl.cmake:39 (add_clang_tidy_files):
  Unknown CMake command "add_clang_tidy_files".
Call Stack (most recent call first):
  src/CMakeLists.txt:117 (bif_target)


-- Configuring incomplete, errors occurred!
```
Fixing it by copying the function in this file leads to the same error in the next file
```
CMake Error at cmake/BinPAC.cmake:47 (add_clang_tidy_files)
```

**Comment by matthbr** [comment]
Could solve this by adding
```
include(FindClangTidy)
```
to cmake/BifCl.cmake before the call to add_clang_tidy_files.
But am not sure if this is exactly what is intended.

**Comment by matthbr** [comment]
Seems to already be fixed in origin/master. But might still want to fix it also in the tag v3.0.0

**Comment by matthbr** [comment]
Seems to be working in the source package so probably not really an issue for most, so I am closing this issue

**Comment by jsiwek** [comment]
The `zeek` git repository uses a lot of submodules that aren't automatically updated when switching around to various branches/tags, so you have to remember to keep them in sync via `git submodule update --recursive --init` (or add an alias in `~.gitconfig` to make the command simpler and easier to remember).
