### ISSUE TITLE
Strange packet loss（bro-2.6.2）

### ISSUE THREAD

**Issue by AspirePig** [zeek/zeek#648]
My zeek is listening to two 10 Gigabit NICs at the same time, but the other NIC (small traffic) has a 50% packet loss rate, and both capture_loss and Dropped_Packets have alarms. I don't think it's a server performance reason. I tried to change the position of the two fibers, and the problem was transferred to another worker. I am not sure if there is a problem with the fiber or the mirrored traffic.
server configuration：32 core |64G|
![image](https://user-images.githubusercontent.com/25975164/67447102-63db3f00-f645-11e9-9d10-6f0d89edc123.png)
![image](https://user-images.githubusercontent.com/25975164/67447156-9127ed00-f645-11e9-9568-a7126db41dbc.png)
![image](https://user-images.githubusercontent.com/25975164/67447357-22975f00-f646-11e9-80ce-e236ae0f47eb.png)
![image](https://user-images.githubusercontent.com/25975164/67447407-56728480-f646-11e9-9b88-ed38bc0c8e77.png)
![image](https://user-images.githubusercontent.com/25975164/67447447-74d88000-f646-11e9-88f8-406960399f4c.png)

**Comment by AspirePig** [comment]
On the NIC that lost the packet, a lot of out-of-order was detected, but I don’t know why.
![image](https://user-images.githubusercontent.com/25975164/67649325-99e52f80-f973-11e9-9333-716989542049.png)

**Comment by 0xxon** [comment]
Hi,

this looks like it is a problem with your network infrastructure, and not with Zeek itself.

For problems like these - which are not bugs in Zeek itself - the bug tracker is not the right place. This is mostly read by the people working on the Zeek core, and less by users who are more familiar with this kind of problem. 

Questions like this are best answered using our  mailing list, which is followed by Zeek developers and professional users. You can join here:

http://mailman.icsi.berkeley.edu/mailman/listinfo/zeek

Once you receive confirmation you’ve been added to the list, send this question there.

 Johanna
