### ISSUE TITLE
Current logs directory

### ISSUE THREAD

**Issue by venki522** [zeek/zeek#657]
The current logs are in /opt/Zeek/spool/Zeek which is filling up the /opt directory..I have different directory which has space.

How do I change the current log directory To different one

**Comment by 0xxon** [comment]
Hi,

Generally, we don't use GitHub issues for support questions. Questions like this are best answered using our  mailing list, which is followed by Zeek developers and professional users. You can join here:

http://mailman.icsi.berkeley.edu/mailman/listinfo/zeek

In this case - just symlink opt/Zeek/spool to somewhere that has space.

 Johanna
