### ISSUE TITLE
Incorrect http::build_url function behavior 

### ISSUE THREAD

**Issue by Olerdrive** [zeek/zeek#658]
There is a function `build_url` in the `HTTP` module which is to actually build a HTTP url from the provided uri and other HTTP request information:

```
function build_url(rec: Info): string
	{
	local uri  = rec?$uri ? rec$uri : "/<missed_request>";
	local host = rec?$host ? rec$host : addr_to_uri(rec$id$resp_h);
	if ( rec$id$resp_p != 80/tcp )
		host = fmt("%s:%s", host, rec$id$resp_p);
	return fmt("%s%s", host, uri);
	}
```

But in fact it does some bad things instead of returning correctly built url:

- `host = fmt("%s:%s", host, rec$id$resp_p);` returns strings like `myhost.net:1344/tcp` instead of `myhost.net:1344`. (A simple [script](http://try.bro.org/#/tryzeek/saved/362523) to proof it)
- In case of proxied http request (in which `uri` will be an absolute url) it returns incorrect url:
`proxy.host:3128/tcphttp://proxied.host/some/document`. Probably it would make sense to return only the url being proxied: `http://proxied.host/some/document`

Pull request to fix it: [659](https://github.com/zeek/zeek/pull/659)

**Comment by jsiwek** [comment]
Thanks, fix in `master` now via #659
