### ISSUE TITLE
In cluster configuration, ftp-data connection is not properly tracked/synchronized across workers

### ISSUE THREAD

**Issue by jsbarber** [zeek/zeek#671]
When an FTP control session sets up a data transfer, there is a call to `schedule_analyzer` (see scripts/base/protocols/ftp/main.zeek) so that an ftp-data connection is associated with the correct analyzer. However, that call is only made in the one worker process that is observing the control connection. If the eventual ftp-data connection (which connects via a different 4-tuple) hits a different worker process -- which is likely in a cluster/af_packet environment, it will not be recognized as an ftp-data transfer.

**Comment by jsiwek** [comment]
Fixed via #672
