### ISSUE TITLE
recent breaking changes to Base64.h API

### ISSUE THREAD

**Issue by jsiwek** [zeek/zeek#676]
The following API changes from #616 may break plugins:

https://github.com/zeek/zeek/commit/705210a035d4128ecdf249c7db98607c570bfcd2#diff-3a1109e3073ae807aa802aba11a6d318L33-R37

For example:

https://github.com/corelight/bro-community-id/blob/f8a8ae62584fdc709f873489600d88dfaa1ccf26/src/communityid.bif#L191-L194

I'd opt to just revert the changes since it's questionable there's a legit use-case requiring the consumption of gigabytes of data here to warrant a switch from `int` to `size_t`.  True that `size_t` probably is more appropriate if we were just introducing these methods, but breaking the API now is worse.  Don't think changing the return type of `Decode()` is necessary either since one can check the error status via the `Errored()` method afterwards.  Generally doesn't seem worth the effort to deprecate and introduce new methods either.

Other thoughts?

**Comment by 0xxon** [comment]
Sounds good to me.

**Comment by 0xxon** [comment]
We should potentially do something to keep the part of the patch that changed https://github.com/zeek/zeek/commit/705210a035d4128ecdf249c7db98607c570bfcd2#diff-034115f86c2711c535dae54849cfc21bL233 - that if condition was never able to trigger before the patch.
