### ISSUE TITLE
compiling the source code

### ISSUE THREAD

**Issue by venki522** [zeek/zeek#688]
iam trying to compile the source code for zeek on centos 7 
 first error i got is 
[root@localhost ~]# cd zeek/
[root@localhost zeek]# ./configure
Build Directory : build
Source Directory: /root/zeek
CMake Error at CMakeLists.txt:3 (cmake_minimum_required):
  CMake 3.0 or higher is required.  You are running version 2.8.12.2

2. upgrade cmake to 3.6.2
3.Later it started complaining gcc  7.0 is required as i have gcc,gcc+ 4.8.5

4.i installed gcc 9.2.0
5 when i stared compiling zeek ,i still see zeek is picking 4.8.5 and it is failling even though i have 9.2.0
        [root@localhost zeek]# ./configure --cmake=/usr/local/bin/cmake  
Build Directory : build
Source Directory: /usr/src/zeek
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5

6.i tried number of times and different soultions and it is not working

could any one give me lead/blog/solution how to compile the source code on centos7 .Any help ie greatly appreciated.Thanks

**Comment by rsmmr** [comment]
Sounds like you're compiling from git master? Some of these
requirements were introduced pretty recently. See here for CentOS
instructions: https://docs.zeek.org/en/latest/install/install.html#required-dependencies

If you notice anything that is missing there, please reopen this
ticket.

On Fri, Nov 15, 2019 at 01:36 -0800, venki522 wrote:

> iam trying to compile the source code for zeek on centos 7 
>  first error i got is 
> [root@localhost ~]# cd zeek/
> [root@localhost zeek]# ./configure
> Build Directory : build
> Source Directory: /root/zeek
> CMake Error at CMakeLists.txt:3 (cmake_minimum_required):
>   CMake 3.0 or higher is required.  You are running version 2.8.12.2
> 
> 2. upgrade cmake to 3.6.2
> 3.Later it started complaining gcc  7.0 is required as i have gcc,gcc+ 4.8.5
> 
> 4.i installed gcc 9.2.0
> 5 when i stared compiling zeek ,i still see zeek is picking 4.8.5 and it is failling even though i have 9.2.0
>         [root@localhost zeek]# ./configure --cmake=/usr/local/bin/cmake  
> Build Directory : build
> Source Directory: /usr/src/zeek
> -- The C compiler identification is GNU 4.8.5
> -- The CXX compiler identification is GNU 4.8.5
> 
> 6.i tried number of times and different soultions and it is not working
> 
> 
> could any one give me lead/blog/solution how to compile the source code on centos7 .Any help ie greatly appreciated.Thanks
> 
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/zeek/zeek/issues/688


-- 
Robin Sommer * Corelight, Inc. * robin@corelight.com * www.corelight.com

**Comment by venki522** [comment]
i followed the same instructions as mentioned and that gave me the errors described above
