### ISSUE TITLE
zeek compiling 

### ISSUE THREAD

**Issue by venki522** [zeek/zeek#689]
i followed the same instructions as mentioned and that gave me the errors described above

_Originally posted by @venki522 in https://github.com/zeek/zeek/issues/688#issuecomment-554339152_

**Comment by venki522** [comment]
i cannot re-ope issue so i created a new one

**Comment by venki522** [comment]
yum install cmake make gcc gcc-c++ flex bison libpcap-devel openssl-devel python-devel swig zlib-devel

the above command on centos is not installing latest packages of cmake,gcc,gcc-c++ which is required to compile zeek on centos

**Comment by jsiwek** [comment]
From the [docs](https://docs.zeek.org/en/latest/install/install.html#required-dependencies), did you also read the part about installing cmake3 and the [devtoolset](https://developers.redhat.com/products/developertoolset/hello-world#fndtn-macos) ?  Example it shows:

```
sudo yum install cmake3 devtoolset-7
scl enable devtoolset-7 bash
```

Also remember to remove the build directory in between new `./configure` commands as CMake will cache any old/inadequate compiler information from the first run.

If you still can't get it work, please provide the full output from your `./configure` command.

**Comment by venki522** [comment]
Thank you @jsiwek  when i tried yum install cmake3,it says package not available.so i have download the tar file and install it

iam trying the steps.keep you posted

**Comment by jsiwek** [comment]
Please follow up via the mailing list if you've had further issues.
