### ISSUE TITLE
Does zeek currently support the dpdk driver?

### ISSUE THREAD

**Issue by shuaidonga** [zeek/zeek#691]

**Comment by 0xxon** [comment]
Hi,

We don't use GitHub issues for support questions. Questions like this are best answered using our  mailing list, which is followed by Zeek developers and professional users. You can join here:

http://mailman.icsi.berkeley.edu/mailman/listinfo/zeek

Please send questions like this there in the future. As a short answer - there is no DPDK plugin that I know of.

 Johanna
