### ISSUE TITLE
Pfring error

### ISSUE THREAD

**Issue by venki522** [zeek/zeek#694]
I compiled Zeek with pfring and when adding workers iam getting below error

Could you please help 

=== stderr.log
[PF_RING] Wrong RING version: kernel is 16, libpfring was compiled with 17
listening on eno49

PF_RING Version          : 7.0.0 (7.0.0-stable:aef22ec763b2541f8c0632ed86b242cf7cff88aa)
Total rings              : 4

Standard (non ZC) Options
Ring slots               : 4096
Slot version             : 16
Capture TX               : Yes [RX+TX]
IP Defragment            : No
Socket Mode              : Standard
Cluster Fragment Queue   : 0
Cluster Fragment Discard : 0

filename:       /lib/modules/3.10.0-957.27.2.el7.x86_64/kernel/net/pf_ring/pf_ring.ko
alias:          net-pf-27
version:        7.5.0
description:    Packet capture acceleration and analysis
author:         ntop.org
license:        GPL
retpoline:      Y
rhelversion:    7.6
srcversion:     F9BB397AFEEE9D5085C40BD
depends:        
vermagic:       3.10.0-957.27.2.el7.x86_64 SMP mod_unload modversions 
parm:           min_num_slots:Min number of ring slots (uint)
parm:           perfect_rules_hash_size:Perfect rules hash size (uint)
parm:           enable_tx_capture:Set to 1 to capture outgoing packets (uint)
parm:           enable_frag_coherence:Set to 1 to handle fragments (flow coherence) in clusters (uint)
parm:           enable_ip_defrag:Set to 1 to enable IP defragmentation(only rx traffic is defragmentead) (uint)
parm:           quick_mode:Set to 1 to run at full speed but with upto one socket per interface (uint)
parm:           force_ring_lock:Set to 1 to force ring locking (automatically enable with rss) (uint)
parm:           enable_debug:Set to 1 to enable PF_RING debug tracing into the syslog, 2 for more verbosity (uint)
parm:           transparent_mode:(deprecated) (uint)

**Comment by 0xxon** [comment]
Hi,

the message indicates that the kernel module and the libpfring you compiled do not match in version. You have to fix that in your system.

Apart from that - we don't use GitHub issues for support questions. Questions like this are best answered using our  mailing list, which is followed by Zeek developers and professional users. You can join here:

http://mailman.icsi.berkeley.edu/mailman/listinfo/zeek

Johanna
