### ISSUE TITLE
zeek 3.0.0 error occurred while trying to send mail 

### ISSUE THREAD

**Issue by siemenslt123** [zeek/zeek#698]
zeek version: 3.0.0
centos version: 7.0

when I use following command :
                 zeekctl deploy 

I get “Error occurred while trying to send mail: sendmail: fatal:  parameter inet_interfaces: no local interface found for ::1 ” information

but there is no error information in Bro 2.5.

should I set the zeekctl .cfg file to disable the send mail function?

**Comment by jsiwek** [comment]
If there's no other relevant output from `zeekctl deploy` or `zeekctl diag`, then that error is more related to your mail configuration than Zeek configuration -- seems to say you've got IPv6 enabled but no IPv6 loopback interface (e.g. check `ifconfig`).  So yeah, either look into fixing your mail config or you can set `SendMail` to an empty string in `zeekctl.cfg` if you don't need or want `zeekctl` to send mail.
