### ISSUE TITLE
Access command line parameters in zeek script

### ISSUE THREAD

**Issue by omnidepp** [zeek/zeek#700]
How can command line parameters like interface name or pcap file name be accessed from within a zeek script? I'm using `-r inputfile.pcap` to process individual files. Now, I'm trying to rename the conn.log to `inputfile_conn.log`.

**Comment by jsiwek** [comment]
I didn't notice any way to access that info currently, but see PRs #702 and #703.

**Comment by omnidepp** [comment]
I figured something out that works for me:

I run zeek like this: `zeek -r inputfile.pcap conf.bro 'connlogname=inputfile'`

In my bro.conf:
```
@load base/protocols/conn
global connlogname = "" &redef;

event zeek_init()
{
local f = Log::get_filter(Conn::LOG, "default");
f$path = connlogname + "_conn";
Log::add_filter(Conn::LOG, f);
}
```

**Comment by timwoj** [comment]
Fixed via the two PRs linked above.
