### ISSUE TITLE
function pcap_get_pfring_id exists failed

### ISSUE THREAD

**Issue by fadelkam** [zeek/zeek#701]
[CMakeError.log](https://github.com/zeek/zeek/files/3902626/CMakeError.log)

**Comment by jsiwek** [comment]
It's normal for that CMake Error log to show that as failing, so you'll have to give more context about what you are trying to do if you expect otherwise and also provide the full `./configure` command and output.

(You might also find the `--with-pcap=` option to `./configure` relevant).
