### ISSUE TITLE
Deal with Python 2 EOL

### ISSUE THREAD

**Issue by jsiwek** [zeek/zeek#706]
Since Python 2 EOL is January 1, 2020, I'd find it nice (but not critical) to address how we treat Python 2 support in the Zeek 3.1.0 release (similar timeframes).  Dropping support in all Zeek-related projects is my preference.  I didn't completely audit what needs to be done for that, but here's the tasks that come to mind:

* Change invocations of `python` to `python3` (e.g. in scripts/shebangs and in documentation)
* Update documentation related to requirements/dependencies (e.g. README / INSTALL files) to state Python 3 is needed and also remove any Python2-specific instructions
* Update CMake to enforce use of Python 3
* Update any CI that's still testing against Python 2 (e.g. on Travis, and Cirrus)
* The above tasks will apply to most git submodules used by Zeek (and don't forget `zkg`)

**Comment by jsiwek** [comment]
To clarify the reason for changing `python` usages to explicit `python3`, see https://www.python.org/dev/peps/pep-0394 -- distributions are recommended to keep `python` as meaning Python 2 and installing just Python 3 generally won't provide any binary named `python`.

**Comment by 0xxon** [comment]
From my point of view - I agree and we should just drop support for python 2.

**Comment by timwoj** [comment]
I agree. Python 2 is dead at this point and we should remove support for it.

**Comment by rsmmr** [comment]
Agree as well. And 3.1 is a good time for this our our end.

**Comment by rsmmr** [comment]
Getting this out for 4.0 would be helpful as then we won't need to support it during that LTS cycle.

**Comment by 0xxon** [comment]
Yup. This would also help with updating our binary packages - which currently has to use a patch file to update trace-summary/stats-to-csv/zeekctl to make our distribution work on python3 systems.

**Comment by jsiwek** [comment]
> Getting this out for 4.0 would be helpful as then we won't need to support it during that LTS cycle.

Still going to look at what makes sense to do for 4.0, but here's a general difference in view: I think the existing Python 2 "support" may be analogous to how platform support may be treated -- I'm sure there exists some Linux distro that has long fallen out of its own LTS, but on which Zeek happens to continue to work.  That doesn't mean Zeek has to keep ensuring it works on that EOL'd distro for the duration of an upcoming Zeek LTS just because it coincidentally works at the moment it will be released.  Same for Python 2: Zeek happens to work with it at the moment, but it may be more than sufficient to announce that no further compatibility/support is offered in future Zeek releases (e.g. a simple `NEWS` entry).

**Comment by rsmmr** [comment]
I'm fine going the "announcement route" (+ update docs) if we also ensure at least that everything is working as expected if somebody has only Python 3 installed.
