### ISSUE TITLE
Stats framework missing data in output

### ISSUE THREAD

**Issue by brittanydonowho** [zeek/zeek#713]
Whenever stats framework is run on pcap the output is missing data. I found that if I move 

if (zeek_is_terminating() )
                return;

in policy/misc/stats.zeek to the end of stats.zeek as follows:

Log::write(Stats::LOG, info);

if ( zeek_is_terminating() )
        return;

schedule report_interval { check_stats(nettime, ns, cs, ps, es, rs, ts, fs, ds) };

The numbers output are as expected. Can someone verify that this is correct?

**Comment by jsiwek** [comment]
I can't think of a reason why the original code returned so early and I'd also move it to return just before the `schedule` as you show.  Would you like to create a Pull Request with the change?

**Comment by brittanydonowho** [comment]
Great - yes will do!

**Comment by jsiwek** [comment]
Just checking if you still plan to make a Pull Request for this?  No problem if not; will just make the change directly.

**Comment by brittanydonowho** [comment]
Still waiting on approval from work but will do this asap. Thanks!

**Comment by jsiwek** [comment]
Thanks for the patch via #946, that's now in `master` and will plan to port to next patch releases, too.
