### ISSUE TITLE
installing zeek and im missing pcap

### ISSUE THREAD

**Issue by dafish7** [zeek/zeek#715]
pi@raspberrypi:~/zeek $ sudo ./configure && make && sudo make install
Build Directory : build
Source Directory: /home/pi/zeek
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found sed: /bin/sed
-- Found PythonInterp: /usr/bin/python (found version "2.7.16") 
-- Found FLEX: /usr/bin/flex (found version "2.6.4") 
-- Found BISON: /usr/bin/bison  
-- Could NOT find PCAP (missing: PCAP_LIBRARY PCAP_INCLUDE_DIR) 
-- Performing Test PCAP_LINKS_SOLO
-- Performing Test PCAP_LINKS_SOLO - Success
-- Looking for pcap_get_pfring_id
-- Looking for pcap_get_pfring_id - not found
-- Found OpenSSL: /usr/lib/arm-linux-gnueabihf/libcrypto.so (found version "1.1.1d")  
-- Performing Test ns_initparse_works_none
-- Performing Test ns_initparse_works_none - Failed
-- Performing Test res_mkquery_works_none
-- Performing Test res_mkquery_works_none - Failed
-- Performing Test ns_initparse_works_libresolv.a
-- Performing Test ns_initparse_works_libresolv.a - Success
-- Performing Test res_mkquery_works_libresolv.a
-- Performing Test res_mkquery_works_libresolv.a - Success
-- Found BIND: /usr/lib/arm-linux-gnueabihf/libresolv.a  
-- Found ZLIB: /usr/lib/arm-linux-gnueabihf/libz.so (found version "1.2.11") 
CMake Error at aux/binpac/CMakeLists.txt:35 (message):
   Could not find prerequisite package 'PCAP'

CMake Error at aux/binpac/CMakeLists.txt:37 (message):
  Configuration aborted due to missing prerequisites

-- Configuring incomplete, errors occurred!
See also "/home/pi/zeek/build/CMakeFiles/CMakeOutput.log".
See also "/home/pi/zeek/build/CMakeFiles/CMakeError.log".
Also, before re-running configure, consider cleaning the cache (removing the build directory) via `make distclean`

help where do i find pcap? ive tried apt install pcap and pip install, but no luck

**Comment by jsiwek** [comment]
Guessing you're missing the `libpcap-dev` package.

Looks like you're building Zeek's master branch on a Raspberry Pi?  Then check this page for the Debian-based Linux dependencies that you need to install:

https://docs.zeek.org/en/latest/install/install.html#required-dependencies
