### ISSUE TITLE
ZEEK running at 300% cpu in docker?

### ISSUE THREAD

**Issue by gnomefish** [zeek/zeek#716]
Is it normal that the container runs at almost 300% cpu (see screenshot from portainer). running it with this command line:

docker run -d --name zeek --cap-add=NET_RAW --net=host blacktop/zeek -i ens33 

<img width="982" alt="Screenshot 2019-12-27 at 15 08 50" src="https://user-images.githubusercontent.com/7964766/71620982-0cb99380-2bcd-11ea-997b-206498fce752.png">

I tried the same with the fixed/zeek container - same thing, running ar 300% cpu.

<img width="721" alt="image" src="https://user-images.githubusercontent.com/7964766/71621003-307cd980-2bcd-11ea-92c5-e13a7d4f0cf2.png">

**Comment by gnomefish** [comment]
Anyone?

**Comment by jsiwek** [comment]
FYI, a potential explanation/patch for at least one cause of high CPU load is incoming via https://github.com/zeek/broker/pull/97

**Comment by petiepooo** [comment]
What version of Zeek are you running?  If it's the 3.0 series, see #838

**Comment by jsiwek** [comment]
Looks like blacktop/zeek may have updated w/ images for Zeek 3.0.3 or 3.1.1 that include the previously mentioned patch.
