### ISSUE TITLE
Cannot download Maxmind database

### ISSUE THREAD

**Issue by PSChrisHinshaw** [zeek/zeek#717]
I know this isn't a zeek specific issue, but wanted to make you aware.  The link in the documentation for the Maxmind geoip database no longer works.

```
# wget http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz
--2019-12-31 11:43:39--  http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz
Resolving geolite.maxmind.com (geolite.maxmind.com)... failed: nodename nor servname provided, or not known.
wget: unable to resolve host address ‘geolite.maxmind.com’
```

I believe that Maxmind has changed their structure to require a user to create an account.

**Comment by PSChrisHinshaw** [comment]
Further info at this blog post:
`https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/`

**Comment by jsiwek** [comment]
Thanks for the heads-up, I updated the docs in `master`.
