### ISSUE TITLE
table_expire_interval limits fine-grained table expiration

### ISSUE THREAD

**Issue by vpax** [zeek/zeek#740]
It appears that the global `table_expire_interval` sets a global lower bound on the expiration timeouts for container elements.  I have a script that uses a short `create_expire` (e.g., 80 msec) but the expirations don't happen for 10+ seconds when running on a pcap (which has plenty of packets, so the problem isn't the packet-driven clock).  If I `redef table_expire_interval = 10 msec` then I get the behavior I'd expect.

As best as I can figure, `table_expire_interval` is vestigial from back-in-the-day (it was introduced in Bro 0.7!), likely for performance reasons.  I think at a minimum we should provide an attribute that can override it for a given table.  It also seems worth assessing whether there's any performance benefit these days, given all the refinements that have been made to table expiration.

**Comment by rsmmr** [comment]
Yeah, the semantics are "expire after at least X"--which in the case of ms vs secs isn't really great obviously. The exact time further affected by `table_incremental_step` as well.

The current behavior is so that we don't need install one timer per table entry. Making the interval a per-table attribute should work though.

**Comment by vpax** [comment]
FWIW, I did some measurements for my particular scenario.  For default processing, lowering the global timeout to 100 msec makes no discernible difference to run time.  Lowering it to 1 msec, however, is disaster (performance falls off by 5x).

**Comment by rsmmr** [comment]
An idea that came up in discussion with @awelzel: We could check the timestamp of an element on lookup (and iteration) and pretend that it's not in the table anymore once it has expired. We'd still leave the actual removal to the current scheme, including running any `expire_func` at that point. That would make semantics for membership tests pretty crisp, and turn eventual expiration into more like garbage collection thing happening when Zeek gets to it.

We could in addition also expire immediately on lookup/iteration if it finds the timestamp expired, although I'm not sure quite sure if that'd be the right semantics (because of `expire_func` now running in the middle of handler; and during iteration we'd be changing the current table).

**Comment by vpax** [comment]
I like this but then your last comment points out a semantic issue: without running the `expire_func` you don't know whether the element would have been deemed keep-in-the-table-after-all.  So skipping it even though apparently expired could be the wrong behavior.

**Comment by rsmmr** [comment]
We could apply the new scheme only to tables without `expire_func`. However, I'm not sure I like having different semantics for different tables, seems that could easily get confusing. 

So maybe the way to go here for now is just lowering the default value, assuming it doesn't show a performance impact. @Tim , can you measure if you see a noticeable difference at 100 msec ?

**Comment by timwoj** [comment]
This is a straight file read (with `-r`) of a 5 minute capture at 500Mbps of a data set representative of data center traffic:

`master`:
```
####### Testing reading the file directly from disk #######
Using CPU 22 for zeek
Time spent: 236.36 seconds
Max memory usage: 2236316 KB
####### Testing reading the file directly from disk #######
Using CPU 22 for zeek
Time spent: 236.06 seconds
Max memory usage: 2231880 KB
####### Testing reading the file directly from disk #######
Using CPU 22 for zeek
Time spent: 236.38 seconds
Max memory usage: 2231132 KB
```

`master` with 100ms change:
```
####### Testing reading the file directly from disk #######
Using CPU 22 for zeek
Time spent: 262.96 seconds
Max memory usage: 2235520 KB
####### Testing reading the file directly from disk #######
Using CPU 22 for zeek
Time spent: 262.38 seconds
Max memory usage: 2229308 KB
####### Testing reading the file directly from disk #######
Using CPU 22 for zeek
Time spent: 258.13 seconds
Max memory usage: 2234184 KB
```

The only change between those two is changing this to 100 msecs from 10 secs:
```
share/zeek/base/init-bare.zeek
1193:const table_expire_interval = 100 msecs &redef;
```

**Comment by rsmmr** [comment]
Yeah, this doesn't look encouraging. I propose we leave this as it is.

**Comment by jsiwek** [comment]
But adding a new, per-table attribute, say `&expire_poll_interval`, to help override the global `table_expire_interval` may still be worth looking into?

**Comment by JustinAzoff** [comment]
@vpax are you mostly using these 10msec table expiration timers for de-duplication?  There might be a more general way that sort of thing could be accomplished.

**Comment by vpax** [comment]
@JustinAzoff  No, I was using them because I wanted to find activity happening at the same time.  Using 100 msec works fine - even 1 sec works okay - but makes my analysis slower since it has to wade through some irrelevant table entries to find the ones of interest.  I think this is relatively moot now due to modifying the spin-through-the-table to delete old entries as it runs across them.  (A bit of a pain because they can't be immediately deleted without messing up the "for" range).

**Comment by rsmmr** [comment]
@jsiwek we could add the attribute but given that there's no immediate need anymore, not sure it's worth it. I'll go ahead and close.
