### ISSUE TITLE
JSON logger uses \x escape unnecessarily on valid unicode code points

### ISSUE THREAD

**Issue by aswan** [zeek/zeek#741]
Consider this script:
```
module LowEscape;
 
export {
    redef enum Log::ID += { LOG };
 
    type Info: record {
        my_str:        string &log;
        };
    }
     
event bro_init()
    {
    Log::create_stream(LowEscape::LOG, [$columns=LowEscape::Info, $path="hello"]);
    }

event file_new(f: fa_file)
    {
    Log::write(LowEscape::LOG, [$my_str="low\x01\escape"]);
    }
```

The string to be logged is properly represented in JSON as `"low\u0001escape"` but the Zeek JSON logger renders it as:
```
{"my_str":"low\\x01escape"}
```

**Comment by sethhall** [comment]
I'm not sure that `\u0001` is the correct representation.  According to all of the JSON specs I've read you can only encode valid utf-8 values in that encoding (which confuses me about why that escaping mechanism even exists).  There is even a question about if that encodes a single by or two bytes because you must encode two bytes in that output.

We chose the current encoding scheme to avoid any potential problems for invalid byte sequences.

**Comment by aswan** [comment]
Summarizing an offline discussion with @sethhall, he indicated to me that there have been instances in the past of consumers of Zeek json logs that don't correctly interpret \u sequence in json strings, so the solution has been to use the Zeek-specific \\x escapes in this case to avoid that problem.

However, there's still some confusion here.  Given the issue above with non-compliant json parsers, its probably irrelevant at this point, but nevertheless:

> I'm not sure that \u0001 is the correct representation. According to all of the JSON specs I've read you can only encode valid utf-8 values in that encoding (which confuses me about why that escaping mechanism even exists).

A \u escape represents a Unicode code point, regardless of how that code point is ultimately encoded (whether by UTF-8 or some other encoding).  As for why the mechanism exists, I presume it exists as an alternative way to represent characters that are otherwise illegal in string literals, as well as for convenience when the entity writing json either can't directly generate the encoded code point or finds it clearer to write out in escaped form.

> There is even a question about if that encodes a single by or two bytes because you must encode two bytes in that output.

I don't understand this comment?  \u0001 unambiguously represents the code point U+0001.  In UTF-8, that code point it encoded in one byte.

**Comment by rsmmr** [comment]
So if I'm following this correctly, Zeek is doing the intended thing here: only valid UTF-8 can be used in a JSON string, and `\u0001` is not UTF-8. While it's meant to be express a Unicode code point, JSON can't express that in that way.
