### ISSUE TITLE
Unify JSON conversion code

### ISSUE THREAD

**Issue by rsmmr** [zeek/zeek#743]
We have two implementations of turning `Val`s into JSON: `Val.cc` and `threading/formatters/JSON.cc` both have `BuildJSON()` functions/methods that share a lot of similar code, but produce slightly different output. We should refactor them into a single function that can be controlled with options to produce the desired output style.

**Comment by timwoj** [comment]
The issue with merging them was that they take two different value types as arguments. The `val` in `threading::Value` isn't exactly the same as the one in `Val` (which is a `BroValUnion`).

**Comment by rsmmr** [comment]
Yeah, true -- still, the code feels just  too similar to have two implementations (which also do the same things somewhat differently). However, I guess this mean it's not actually a "good first issue" as it's unclear *how* to actually merge them.

**Comment by rsmmr** [comment]
Closing this, as it seems quite tricky to merge and is low priority.
