### ISSUE TITLE
Deduplicate x509 analysis

### ISSUE THREAD

**Issue by JustinAzoff** [zeek/zeek#744]
Many certificates that are analyzed are duplicates - especially if monitoring east-west traffic, or north-south traffic where local servers are seen.

At the beginning of `file_analysis::X509::EndOfFile`, check to see if the certificate has been seen before, and if so, avoid re-parsing the certificate and extensions.  References to the already parsed data can still be attached to f$info$x509 so that existing scripts continue to work.  We may or may not want to raise the x509_* events on duplicate certificates.

We should only log a certificate in x509.log once (or however the cache expiry works) and then just reference the consistent sha1 of the certificate in the ssl log instead of relying on a fuid.

**Comment by JustinAzoff** [comment]
Here's a data point from my home network:

    490021 total certs in files.log
    1876 unique certs based on sha256.

**Comment by 0xxon** [comment]
This was fixed in #856.

I will open a new issue for the remaining log issue.
