### ISSUE TITLE
Writing to SQLite: Reporter::ERROR SQLite call failed - Unable to access database

### ISSUE THREAD

**Issue by CaptainMayotoast** [zeek/zeek#745]
Greetings.  I am new to Zeek, so I am probably missing something basic, but my issue is as follows:

As seen with [this ](https://docs.zeek.org/en/stable/frameworks/logging-input-sqlite.html)documentation page, I attempted to create a simple .zeek script in the /usr/local/zeek/share/zeek/site/ directory.  Within local.zeek, I added an "@load sqlite-conn-filter.zeek" statement.

My file is the following:
```
module Conn;

export {
    event zeek_init()
        {
        local filter: Log::Filter =
            [
            $name="sqlite",
            $path="/var/db/conn",
            $config=table(["tablename"] = "conn"),
            $writer=Log::WRITER_SQLITE
            ];

        Log::add_filter(Conn::LOG, filter);
        }
}
```

When running "zeekctl deploy" as either root or with sudo privileges, "zeekctl diag" produces the following result:

```
[zeek]

No core file found.

Zeek 3.1.0-dev.383
Linux 5.3.0-26-generic

Zeek plugins: (none found)

==== reporter.log
#separator \x09
#set_separator  ,
#empty_field    (empty)
#unset_field    -
#path   reporter
#open   2020-01-22-01-19-22
#fields ts      level   message location
#types  time    enum    string  string
1579673962.101962       Reporter::ERROR /var/db/conn/Log::WRITER_SQLITE: SQLite call failed: unable to open database file (empty)
1579673962.101962       Reporter::ERROR /var/db/conn/Log::WRITER_SQLITE: terminating thread     (empty)

==== stderr.log
listening on enp3s0


==== stdout.log
max memory size         (kbytes, -m) unlimited
data seg size           (kbytes, -d) unlimited
virtual memory          (kbytes, -v) unlimited
core file size          (blocks, -c) unlimited

==== .cmdline
-i enp3s0 -U .status -p zeekctl -p zeekctl-live -p standalone -p local -p zeek local.zeek zeekctl zeekctl/standalone zeekctl/auto

==== .env_vars
PATH=/usr/local/zeek/bin:/usr/local/zeek/share/zeekctl/scripts:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
ZEEKPATH=/usr/local/zeek/spool/installed-scripts-do-not-touch/site::/usr/local/zeek/spool/installed-scripts-do-not-touch/auto:/usr/local/zeek/share/zeek:/usr/local/zeek/share/zeek/policy:/usr/local/zeek/share/zeek/site
CLUSTER_NODE=

==== .status
RUNNING [net_run]

==== No prof.log

==== packet_filter.log
#separator \x09
#set_separator  ,
#empty_field    (empty)
#unset_field    -
#path   packet_filter
#open   2020-01-22-01-19-16
#fields ts      node    filter  init    success
#types  time    string  string  bool    bool
1579673956.895678       zeek    ip or not ip    T       T

==== loaded_scripts.log
#separator \x09
#set_separator  ,
#empty_field    (empty)
#unset_field    -
#path   loaded_scripts
#open   2020-01-22-01-19-16
#fields name
#types  string
```

A bunch of .zeek files are listed and my file is among them:
> /usr/local/zeek/spool/installed-scripts-do-not-touch/site/sqlite-conn-filter.zeek

I figured as root, creating a file in /var/ would not be a problem, yet the log states:

> 1579673962.101962       Reporter::ERROR /var/db/conn/Log::WRITER_SQLITE: SQLite call failed: unable to open database file (empty)
> 1579673962.101962       Reporter::ERROR /var/db/conn/Log::WRITER_SQLITE: terminating thread     (empty)

May I ask what I am missing?  Is my Zeek script incorrect?  Have I placed it in the wrong location?

For what it's worth, I am running Zeek "on-the-metal" using Ubuntu 18.04. 

Thank you for your help and time.

**Comment by JustinAzoff** [comment]
Does the /var/db/ directory exist?

You can get sqlite to raise that error if you try writing a db to a non existent directory:

```
$ sqlite3 /tmp/foo.db 'create table foo (foo text)';
$ sqlite3 /tmp/doesnotexist/foo.db 'create table foo (foo text)';
Error: unable to open database "/tmp/doesnotexist/foo.db": unable to open database file
```

**Comment by CaptainMayotoast** [comment]
@JustinAzoff thnak you for your quick reply!  I apologize, I assumed that Zeek would also create the /var/db/ directory if it didn't exist - it works now.  I can access conn.sqlite and see the schema just as the Zeek guide shows.

Thanks again!
