### ISSUE TITLE
Integrate CAF 0.17.4 when released

### ISSUE THREAD

**Issue by rsmmr** [zeek/zeek#751]
CAF 0.17.4 is scheduled to come out before 3.1.0.

**Comment by jsiwek** [comment]
Now using the current CAF 0.17.4 release *branch*, still would want to update to the *tag* when available.

**Comment by Neverlord** [comment]
> still would want to update to the tag when available.

Just released: https://github.com/actor-framework/actor-framework/releases/tag/0.17.4

**Comment by jsiwek** [comment]
Now using CAF 0.17.4 release tag, thanks Dominik.
