### ISSUE TITLE
Remove using statements from headers

### ISSUE THREAD

**Issue by timwoj** [zeek/zeek#776]
As part of merging https://github.com/zeek/zeek/pull/770 a number of `using` statements were added to headers to make things build correctly, but without causing a cascading number of changes to not need them.

This issue is just a reminder that we need to go back and remove those and fix the places that the build breaks.

**Comment by 0xxon** [comment]
This is done and merged in 876c803

**Comment by 0xxon** [comment]
Actually it was not, I can't read :)

**Comment by 0xxon** [comment]
Yes, it was. This is some rollercoaster.

Sorry :)
