### ISSUE TITLE
Signature framework and flow directions (aka 'tcp-state' for UDP)

### ISSUE THREAD

**Issue by l0x-c0d3z** [zeek/zeek#779]
Hi.
I'm working on a signature for a protocol that can use UDP or TCP.

For the TCP version of the protocol, I am simply using `tcp-state originator` to enforce the fact the packet should come from the client. I cannot find a way to do this for UDP.

I've been looking into how `RuleConditionTCPState::DoMatch()` works. I haven't been through all the layers, but after several layers of TCP-only code, we hit `RuleEndpointState::isOrig()` which does not seem to be TCP-specific.

Are there any technical restrictions that prevent us from having the flow direction available for non tcp-rules ?

**Comment by jsiwek** [comment]
I didn't see any existing way to condition a signature on UDP direction either, but can't think of any technical reason why it can't be done.  If you wanted to give a shot at implementing, that would be pretty cool.  As you saw, it should operate similar to `RuleConditionTCPState`, so you could mostly copy that logic with maybe some gentle refactoring of the `TCPState` enum so those values can be shared and/or the name doesn't imply TCP-specific usage.  You'd also just have to add a few bits to `rule-scan.l` and `rule-parse.y`.
