### ISSUE TITLE
Illegal downcasts in `BroType::AsTypeList()` and others

### ISSUE THREAD

**Issue by MaxKellermann** [zeek/zeek#786]
In `BroType`, all `AsX()` methods contain downcasts to derived classes:
https://github.com/zeek/zeek/blob/a394d2e0d709ff507859484ea862e9468cc8a5c8/src/Type.h#L130-L134
However, all f those classes are forward-declared, e.g.:
https://github.com/zeek/zeek/blob/a394d2e0d709ff507859484ea862e9468cc8a5c8/src/Type.h#L65
Casting in C++ may require offsetting the pointer, which in turn requires all involved types to be complete. This may currently work because the offset between those classes just happens to be zero, but this can fall apart any day and will then lead to strange crashes.

**Comment by timwoj** [comment]
Along the same lines, clang-tidy complains about quite a few uses of `static_cast` vs `dynamic_cast` when moving up and down the inheritance levels as part of the `cppcoreguidelines-pro-type-static-cast-downcast` checker. Unfortunately, a lot of them are in generated BIF/binpac code, so it'd be a matter of fixing those code generators.

**Comment by jsiwek** [comment]
Fixed via #1043 (there's similar casts also in Expr.h, Val.h, Stmt.h still, but I'll just go change those separately)
