### ISSUE TITLE
Use Sqlite import port lost protocol

### ISSUE THREAD

**Issue by haileiseatears** [zeek/zeek#801]
When I use Sqlite to import data:
```
172.17.229.48|8/tcp
39.106.72.194|5546/tcp
```

```
type Idx_authority: record {
        access_ip:addr;
};

type Val_authority: record {
       access_port:port;
};

global staff_authority: table[addr] of Val_authority = table();global staff_authority: table[addr] of Val_authority = table();

event zeek_init(){
    Input::add_table([$source="/var/db/staff",$name="staff",$idx=Idx_authority,$val=Val_authority,
    $destination=staff_authority,$reader=Input::READER_SQLITE,$config=table(["query"]="select * from staff_authority;")]);
    #Input::remove("users2");
}

event Input::end_of_data(name: string, source: string) {
        # now all data is in the table
        print staff_authority;
}
```

Zeek get the data as:
```
[172.17.229.48] = [access_port=8/unknown],
[39.106.72.194] = [access_port=5546/unknown]
```
It use unknown instead tcp.

**Comment by awelzel** [comment]
Hey @haileiseatears - for the port/proto pair an extra `&type_column` annotation is required on the field:

```
type Val_authority: record {
    access_port:port &type_column = "access_proto"; 
};
```

Your DB schema needs to reflect this as well. Note the new `access_proto` column.
```
CREATE TABLE staff_authority (access_ip TEXT, access_port INT, access_proto TEXT);
INSERT INTO staff_authority VALUES('39.106.72.194',5546,'udp');
INSERT INTO staff_authority VALUES('172.17.229.48',8,'tcp');
```

```
$ /opt/zeek/bin/zeek ./sqlite_reader.zeek
{
[172.17.229.48] = [access_port=8/tcp],
[39.106.72.194] = [access_port=5546/udp]
}
```

**Comment by haileiseatears** [comment]
> 嘿@haileiseatears-对于端口/协议对`&type_column`，在字段上需要额外的注释：
> 
> ```
> ...
> type Val_authority: record {
>     access_port:port &type_column = "access_proto"; 
> };
> ...
> ```
> 
> 您的数据库模式也需要反映这一点。注意新`access_proto`列。
> 
> ```
> CREATE TABLE staff_authority (access_ip TEXT, access_port INT, access_proto TEXT);
> INSERT INTO staff_authority VALUES('39.106.72.194',5546,'udp');
> INSERT INTO staff_authority VALUES('172.17.229.48',8,'tcp');
> ```
> 
> ```
> $ /opt/zeek/bin/zeek ./sqlite_reader.zeek
> {
> [172.17.229.48] = [access_port=8/tcp],
> [39.106.72.194] = [access_port=5546/udp]
> }
> ```



> Hey @haileiseatears - for the port/proto pair an extra `&type_column` annotation is required on the field:
> 
> ```
> ...
> type Val_authority: record {
>     access_port:port &type_column = "access_proto"; 
> };
> ...
> ```
> 
> Your DB schema needs to reflect this as well. Note the new `access_proto` column.
> 
> ```
> CREATE TABLE staff_authority (access_ip TEXT, access_port INT, access_proto TEXT);
> INSERT INTO staff_authority VALUES('39.106.72.194',5546,'udp');
> INSERT INTO staff_authority VALUES('172.17.229.48',8,'tcp');
> ```
> 
> ```
> $ /opt/zeek/bin/zeek ./sqlite_reader.zeek
> {
> [172.17.229.48] = [access_port=8/tcp],
> [39.106.72.194] = [access_port=5546/udp]
> }
> ```

Thank you very much！
