### ISSUE TITLE
can't load zeek base script with nix (packaging hardlinks duplicate scripts)

### ISSUE THREAD

**Issue by GTrunSec** [zeek/zeek#804]
this issue related to https://github.com/NixOS/nixpkgs/issues/79515

original Zeek's nix  https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/ids/zeek/default.nix

there are CMake flags following:

```
    "-DENABLE_PERFTOOLS=true"
    "-DINSTALL_AUX_TOOLS=true"
```
issue test output:
```
sudo zeek -i en0                                                            
error in /nix/store/dq63rmkjs9khg4p9gw9pqk4shxn4kpm1-zeek-3.0.1/share/zeek/base/protocols/dce-rpc/./main.zeek, line 51: "redef" used but not previously defined (DPD::ignore_violations)
```
Does anyone  give me some idea about the error output. that really help to debug the Zeek's nix . Thanks

**Comment by jsiwek** [comment]
`DPD::ignore_violations` is supposed to be defined in `$install_prefix/share/zeek/base/frameworks/dpd/main.zeek`

```
$ grep -R ignore_violations /usr/local/zeek/share/zeek
/usr/local/zeek/share/zeek/base/frameworks/dpd/main.zeek:	option ignore_violations: set[Analyzer::Tag] = set();
/usr/local/zeek/share/zeek/base/frameworks/dpd/main.zeek:	option ignore_violations_after = 10 * 1024;
/usr/local/zeek/share/zeek/base/frameworks/dpd/main.zeek:	if ( atype in ignore_violations )
/usr/local/zeek/share/zeek/base/frameworks/dpd/main.zeek:	if ( ignore_violations_after > 0 && size > ignore_violations_after )
/usr/local/zeek/share/zeek/base/protocols/dce-rpc/main.zeek:redef DPD::ignore_violations += { Analyzer::ANALYZER_DCE_RPC };
/usr/local/zeek/share/zeek/base/protocols/ntlm/main.zeek:redef DPD::ignore_violations += { Analyzer::ANALYZER_NTLM };
```

So you can check that file to see if it looks the same.  Generally you could compare the `$install_prefix/share/zeek` tree to see if it has all the same files as the source code distribution's `scripts/` directory.

You could also check if Zeek's search path for scripts are somehow messed up.  E.g. this is expected output for `/usr/local/zeek` prefix:

```
$ which zeek
/usr/local/zeek/bin/zeek
 $ zeek --help 2>&1 | grep ZEEKPATH
    $ZEEKPATH                      | file search path (.:/usr/local/zeek/share/zeek:/usr/local/zeek/share/zeek/policy:/usr/local/zeek/share/zeek/site)
```

But the general things I can imagine going wrong are (1) the installed scripts in `$install_prefix/share/zeek` don't match what is supposed to be installed (2) Zeek is somehow not finding the right scripts to load or loading things that don't properly define `DPD::ignore_violations`

**Comment by GTrunSec** [comment]
I have got all of the information correctly.
I guess caused by priority load script order?
```
 zeek --help 2>&1 | grep ZEEKPATH                                                                      : 18:55:47 
    $ZEEKPATH                      | file search path (.:/nix/store/76l7jsb5mgwr21db3q9qkpipbhlyka7b-zeek-3.0.1/share/zeek:/nix/store/76l7jsb5mgwr21db3q9qkpipbhlyka7b-zeek-3.0.1/share/zeek/policy:/nix/store/76l7jsb5mgwr21db3q9qkpipbhlyka7b-zeek-3.0.1/share/zeek/site)
```
```
 grep -R ignore_violations /nix/store/76l7jsb5mgwr21db3q9qkpipbhlyka7b-zeek-3.0.1/share/zeek/          : 18:56:00 
/nix/store/76l7jsb5mgwr21db3q9qkpipbhlyka7b-zeek-3.0.1/share/zeek/base/frameworks/dpd/main.zeek:        option ignore_violations: set[Analyzer::Tag] = set();
/nix/store/76l7jsb5mgwr21db3q9qkpipbhlyka7b-zeek-3.0.1/share/zeek/base/frameworks/dpd/main.zeek:        option ignore_violations_after = 10 * 1024;
/nix/store/76l7jsb5mgwr21db3q9qkpipbhlyka7b-zeek-3.0.1/share/zeek/base/frameworks/dpd/main.zeek:        if ( atype in ignore_violations )
/nix/store/76l7jsb5mgwr21db3q9qkpipbhlyka7b-zeek-3.0.1/share/zeek/base/frameworks/dpd/main.zeek:        if ( ignore_violations_after > 0 && size > ignore_violations_after )
/nix/store/76l7jsb5mgwr21db3q9qkpipbhlyka7b-zeek-3.0.1/share/zeek/base/protocols/dce-rpc/main.zeek:redef DPD::ignore_violations += { Analyzer::ANALYZER_DCE_RPC };
/nix/store/76l7jsb5mgwr21db3q9qkpipbhlyka7b-zeek-3.0.1/share/zeek/base/protocols/ntlm/main.zeek:redef DPD::ignore_violations += { Analyzer::ANALYZER_NTLM };
```

**Comment by jsiwek** [comment]
I don't have any other immediate ideas.  If it's possible to independently compile/install Zeek from source in the usual way (`./configure && make install`) and test whether that works or shows the same problem it could help narrow whether it's just an error in the packaging or possibly a fundamental bug in Zeek's script-loading mechanism that just hasn't been discovered because other OSs happen to do something or other differently.

**Comment by GTrunSec** [comment]
Thank you for replying to me.
I knew it what happened about this issue and did a test.

before dce-rpc to load dpd script. no error
```
sudo zeek -b -i eno1 base/frameworks/dpd/ base/protocols/dce-rpc/                                          : 20:45:32 
listening on eno1

```

>  it's just an error in the packaging or possibly a fundamental bug in Zeek's script-loading mechanism that just hasn't been discovered because other OSs happen to do something or other differently.


I don't know why the Zeek packing of nix changed script-loading mechanism.

So, I did a dirty modify that echo `@load ../../frameworks/dpd` to dce-rpc __load__.zeek.  just make sure before loading dce-rpc that have been loaded dpd __load__.zeek.

**Comment by GTrunSec** [comment]
more test about the script-loading mechanism and nix mechanism.

first, I located the Zeek's nix mkdirvration path to dce-rpc load.zeek.  Still can't not find dpd correctly.
```
sed -i '1i@load base/frameworks/dpd' $out/share/zeek/base/protocols/dce-rpc/__load__.zeek                                        
=  18   sed -i "1i@load $out/share/zeek/base/frameworks/dpd" $out/share/zeek/base/protocols/dce-rpc/__load__.zeek                        
```
So, I copied the dpd scirpt to my HOME paht. then sed to Zeek nix. fixed the first issue which can not find dpd correctly.
```
sed -i "1i@load /home/gtrun/src/zeek-3.0.1/scripts/base/frameworks/dpd
```
finally, I got new issue about the loading path.
```
sudo ./result/bin/zeek -i eno1                                                               : (*master+357) 22:47:16 
error in /nix/store/jfn4qgjbcp3rcqa41q0v1b3b6m7wgy98-zeek-3.0.1/share/zeek/base/protocols/ssl/./files.zeek, line 61: no such field in record (SSL::f$info?$x509)
error in /nix/store/jfn4qgjbcp3rcqa41q0v1b3b6m7wgy98-zeek-3.0.1/share/zeek/base/protocols/ssl/./files.zeek, line 61: no such field in record (SSL::f$info$x509)
error in /nix/store/jfn4qgjbcp3rcqa41q0v1b3b6m7wgy98-zeek-3.0.1/share/zeek/base/protocols/ssl/./files.zeek, line 77: no such field in record (SSL::f$info$x509)
error in /nix/store/jfn4qgjbcp3rcqa41
```

**Comment by JustinAzoff** [comment]
Oh!  I think I know what causes this.

Did nix deduplicate the __load__.zeek files that only contain `@load ./main`?  The clearlinux build tools do something similar and break things in a similar way.

Try this:

    find /nix/store/jfn4qgjbcp3rcqa41q0v1b3b6m7wgy98-zeek-3.0.1 -name __load__.zeek  | xargs ls -li|sort -n

Do a bunch of the files have the same inode?

**Comment by GTrunSec** [comment]
yeh, I got all of the files which could be running on nix

```
 find /nix/store/jfn4qgjbcp3rcqa41q0v1b3b6m7wgy98-zeek-3.0.1 -name __load__.zeek  | xargs ls -li|sort -n                 : 11:45:45 
                                                                                                                                         
  1408368 -r--r--r-- 73 root root   13 Dec 31  1969 /nix/store/jfn4qgjbcp3rcqa41q0v1b3b6m7wgy98-zeek-3.0.1/share/zeek/base/files/x509/__l
oad__.zeek                                                                                                                               
  1408368 -r--r--r-- 73 root root   13 Dec 31  1969 /nix/store/jfn4qgjbcp3rcqa41q0v1b3b6m7wgy98-zeek-3.0.1/share/zeek/base/frameworks/ana
lyzer/__load__.zeek                                                                                                                      
  1408368 -r--r--r-- 73 root root   13 Dec 31  1969 /nix/store/jfn4qgjbcp3rcqa41q0v1b3b6m7wgy98-zeek-3.0.1/share/zeek/base/frameworks/dpd
/__load__.zeek                                                                                                                           
  1408368 -r--r--r-- 73 root root   13 Dec 31  1969 /nix/store/jfn4qgjbcp3rcqa41q0v1b3b6m7wgy98-zeek-3.0.1/share/zeek/base/frameworks/rep
orter/__load__.zeek                                                                                                                      
  1408368 -r--r--r-- 73 root root   13 Dec 31  1969 /nix/store/jfn4qgjbcp3rcqa41q0v1b3b6m7wgy98-zeek-3.0.1/share/zeek/base/frameworks/tun
nels/__load__.zeek                                                                                                                       
  1408368 -r--r--r-- 73 root root   13 Dec 31  1969 /nix/store/jfn4qgjbcp3rcqa41q0v1b3b6m7wgy98-zeek-3.0.1/share/zeek/base/protocols/mysq
l/__load__.zeek                                                                                                                          
  1408368 -r--r--r-- 73 root root   13 Dec 31  1969 /nix/store/jfn4qgjbcp3rcqa41q0v1b3b6m7wgy98-zeek-3.0.1/share/zeek/base/protocols/radi
us/__load__.zeek                                                                                                                         
  1408368 -r--r--r-- 73 root root   13 Dec 31  1969 /nix/store/jfn4qgjbcp3rcqa41q0v1b3b6m7wgy98-zeek-3.0.1/share/zeek/base/protocols/snmp
/__load__.zeek                                                                                                                           
  1408368 -r--r--r-- 73 root root   13 Dec 31  1969 /nix/store/jfn4qgjbcp3rcqa41q0v1b3b6m7wgy98-zeek-3.0.1/share/zeek/policy/files/unifie
d2/__load__.zeek                                                                                                                         
  1408372 -r--r--r--  9 root root 1159 Dec 31  1969 /nix/store/jfn4qgjbcp3rcqa41q0v1b3b6m7wgy98-zeek-3.0.1/share/zeek/base/frameworks/clu
ster/__load__.zeek                                                        
```

**Comment by jsiwek** [comment]
Here's the previous mailing list thread w/ same issue:

http://mailman.icsi.berkeley.edu/pipermail/zeek/2019-March/014035.html

Where Justin suggested breaking the hardlinks like:

```
/usr/bin/rsync -aP /usr/share/bro/<whatever> /somewhere
/usr/bin/rsync -aP /somewhere /usr/share/bro/<whatever>
```

My suggestion is the same, too: the NixOS packaging process essentially caused the problem for itself by changing the intended filesystem layout that Zeek expects, so it would ideally have an option to disable hardlinking duplicate files.  However, changing upstream Zeek is an option, too, if we see this practice becoming more common or just if a patch came along that maintains the existing script-loading behavior (prevent loading a given script through alternate symlink/path) but doesn't rely on just inode to check uniqueness (e.g. maybe can use both inode and a normalized/real path).

**Comment by GTrunSec** [comment]
thank you for helping.  fixed by (https://github.com/GTrunSec/my-profile/blob/master/own-nixpkgs/zeek/shell.nix) modified echo __load__. I don't know that would be the right approach.

**Comment by GTrunSec** [comment]
there still has a problem that is Zeekctl. 
https://github.com/GTrunSec/my-profile/blob/master/own-nixpkgs/zeek/zeekctl1.patch

**nix store does not allow dynamic files and logs generated in the path**
Issue output:

<details>
sudo ./result/bin/zeekctl 
[sudo] password for gtrun: 
Error: failed to update symlink '/nix/store/clnpaq71a7rm672ds8clccz0s0ra16mr-zeek-3.0.3/share/zeekctl/scripts/zeekctl-config.sh' to point to '/var/db/zeek-3.0.3/zeekctl-config.sh': Read-only file system
Hint: Run the zeekctl "deploy" command to get started.

Welcome to ZeekControl 2.0.0

Type "help" for help.

[ZeekControl] > deploy
checking configurations ...
zeek scripts failed.
/nix/store/clnpaq71a7rm672ds8clccz0s0ra16mr-zeek-3.0.3/share/zeekctl/scripts/check-config: line 18: /nix/store/clnpaq71a7rm672ds8clccz0s0ra16mr-zeek-3.0.3/share/zeekctl/scripts/zeekctl-config.sh: No such file or directory
/nix/store/clnpaq71a7rm672ds8clccz0s0ra16mr-zeek-3.0.3/share/zeekctl/scripts/check-config: line 25: /set-zeek-path: No such file or directory
</details>


- CAKE option (replace the dynamic dir to /var path)
  "-DZEEK_SPOOL_DIR=${confdir}/spool"
    "-DZEEK_LOG_DIR=${confdir}/logs"

-  zeekctl-config.sh 
<details>
</details>

**Comment by jsiwek** [comment]
> there still has a problem that is Zeekctl.

For clarity, it helps to open separate issue for unrelated problems.

> https://github.com/GTrunSec/my-profile/blob/master/own-nixpkgs/zeek/zeekctl1.patch

Before patching that extremely, I would have suggested changing via configuration options -- there's some you can control through CMake like you found, but you can also change what's in `zeekctl.cfg` to alter various directories.  All the options are listed here: https://github.com/zeek/zeekctl#option-reference

> under zeek/share/zeekctl/scripts/: two files need to remove to /var/
> `set-zeek-path` `zeekctl-config.sh`

You can try changing the `ScriptsDir` option in `zeekctl.cfg` since that's where those files are located.

**Comment by philrz** [comment]
An update for anyone who might be watching this closed issue: The problem with hard links as described previously in this issue has been addressed in `master` of Zeek via https://github.com/zeek/zeek/pull/1051. See https://github.com/zeek/zeek/issues/928 for other details.
