### ISSUE TITLE
Add ZEEK_VERSION_NUMBER for conditional compilation

### ISSUE THREAD

**Issue by jsiwek** [zeek/zeek#808]
Didn't see any existing way for external plugins to do conditional compilation based on Zeek version number (e.g. to support multiple version where Zeek API differs).

The same semantic as used by the script-layer `VersionDescription$version_number` likely works.  E.g. `ABBCC = major * 10000 + minor * 100 + patchlevel`, assuming no more than 100 minor or patch releases.

Probably say just stick `ZEEK_VERSION_NUMBER` definition in `zeek-config.h` unless there's opinions that it would be better to start a separate `version.h`.

**Comment by rsmmr** [comment]
Yep, I think we're indeed missing that. I'm wondering if we should get that into 3.0.2 and 3.1 still, looks like an easy changer and the earlier that's accessible the better.

**Comment by rsmmr** [comment]
Well, maybe not 3.0.2. If 3.1 introduces it, one can assume that `#ifndef ZEEK_VERSION_NUMBER` it's < 3.1

**Comment by jsiwek** [comment]
Now in `master` and `release/3.1`
