### ISSUE TITLE
Run UBSan in CI (and possibly OSS-Fuzz)

### ISSUE THREAD

**Issue by jsiwek** [zeek/zeek#822]
Haven't looked at which sanitizers conflict with each other, but we should have a CI task that runs the full test suite through UndefinedBehaviorSanitizer (and fix anything reported beforehand).

**Comment by timwoj** [comment]
I'm not sure this can make it before 3.2. The last time I ran UBSan locally, fixing all of the output from it seemed like a fairly large task. There's a list of checks from that sanitizer that can be turned on and off. We might want to investigate which of them we actually need first: https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html#available-checks

**Comment by rsmmr** [comment]
I'll remove the milestone, this seems like a rather large task to get under control.

**Comment by jsiwek** [comment]
There's separate benefits to think about:
1. Fix existing code that is flagged as UB
2. Minimize introduction of UB in new code

If there's some checks we can disable as a first step of just getting UBSan running in CI, that helps in terms of (2) and we can always leave issues open to revisit what's still flagged for (1).  So I think there's still progress we can try to make here near-term and worth keeping this on the radar (maybe for 4.0, feel free to assign me to investigate further).

**Comment by rsmmr** [comment]
OOS Fuzz is running, UBSan still TODO.
