### ISSUE TITLE
Provide example systemd service file

### ISSUE THREAD

**Issue by jsiwek** [zeek/zeek#824]
Shipping with an example systemd service file can help demonstrate practices for running Zeek such as with sandboxing options shown here:

https://github.com/zeek/zeek/pull/754#issuecomment-580652275

**Comment by rsmmr** [comment]
Removing milestone, we aren't quite at this point yet.

**Comment by rsmmr** [comment]
I'll close in favor of #742, which will make it more natural to ship a prebuilt systemd configuration. I'll put a link to the sandboxing args into that ticket.
