### ISSUE TITLE
log rotation silently fails at random intervals

### ISSUE THREAD

**Issue by klehigh** [zeek/zeek#828]
I see logs get renamed to <log>-YYYY-MM-DD-HH-MM-SS.log , but they don't get compressed and moved to the archive directory.  This happens at random intervals and is reasonably well distributed across all the logs we're writing.  There are no log rotation related errors in reporter.log or std*.log .

I'm running on FreeBSD and this problem is present in 3.0.1.  It has, admittedly, been around for a very long time.

This issue was brought up in a Zeeksperts call recently, so it isn't specific to our site.  Pinging @sethhall as he and I have discussed this and he had some thoughts on a possible cause.

**Comment by JustinAzoff** [comment]
I think part of the reason there's  no errors logged is because they are ignored

`Log::run_rotation_postprocessor_cmd` does

```
    system(fmt("%s %s %s %s %s %d %s",
               pp_cmd, npath, info$path,
               strftime("%y-%m-%d_%H.%M.%S", info$open),
               strftime("%y-%m-%d_%H.%M.%S", info$close),
               info$terminating, writer));

    return T;
```

and throws away the result of `system`.

`LogAscii::default_rotation_postprocessor_func` does the same thing.

We should be able to replace

```
system(fmt("/bin/mv %s %s", info$fname, dst));
```
with

```
rename(info$fname, dst);
```

In general the approach https://github.com/ncsa/bro-atomic-rotate uses is the right one and fixes almost all of the log rotation issues, but if the `system()` call is failing it won't help there.  It would be possible to avoid the `system()` part entirely using a new `default_rotation_postprocessors`.

Integrating the atomic rotation ideas might be finally doable with the new supervisor framework.

**Comment by rsmmr** [comment]
There's now also https://github.com/zeek/zeek-archiver. That should be able to take over with ZeekControl as well, right (i.e., not just with the supervisor)? Can somebody provide a short tutorial on what changes to make to a ZeekControl deployment to switch to using zeek-archiver?

**Comment by jsiwek** [comment]
> There's now also https://github.com/zeek/zeek-archiver. That should be able to take over with ZeekControl as well, right (i.e., not just with the supervisor)? Can somebody provide a short tutorial on what changes to make to a ZeekControl deployment to switch to using zeek-archiver?

This can go in `local.zeek`:

```zeek
@if ( Cluster::local_node_type() == Cluster::LOGGER )

redef Log::default_rotation_dir = "/usr/local/zeek/logs/queue";

function my_rotation_format_func(ri: Log::RotationFmtInfo): Log::RotationPath
	{
	local open_str = strftime(Log::default_rotation_date_format, ri$open);
	local close_str = strftime(Log::default_rotation_date_format, ri$open);
	local base = fmt("%s__%s__%s__", ri$path, open_str, close_str);
	local rval = Log::RotationPath($file_basename=base);
	return rval;
	}

redef Log::rotation_format_func = my_rotation_format_func;
redef Log::default_rotation_postprocessor_cmd = "";

@endif
```

And run: `zeek-archiver /usr/local/zeek/logs/queue /usr/local/zeek/logs`

**Comment by rsmmr** [comment]
Excellent! That seems worth moving into the docs for the archiver, and then I propose we close this ticket as we have a better way of doing this going forward.

**Comment by jsiwek** [comment]
The `zeek-archiver` README now provides that as an example.
