### ISSUE TITLE
Bro link broken when using --binary-package

### ISSUE THREAD

**Issue by 0xxon** [zeek/zeek#831]
When configuring zeek with --binary-package, the bro symlink is broken and points to zeek-wrapper-in. Example:

```
$ ls -lh
total 353M
-rwxr-xr-x 1 johanna johanna  23K Feb 28 23:05 adtrace
-rwxr-xr-x 1 johanna johanna 444K Feb 28 23:04 bifcl
-rwxr-xr-x 1 johanna johanna 5.3M Feb 28 23:04 binpac
lrwxrwxrwx 1 johanna johanna   54 Feb 28 23:05 bro -> /home/johanna/zeek/master/build/src/../zeek-wrapper.in
lrwxrwxrwx 1 johanna johanna   35 Feb 28 23:05 bro-config -> /home/johanna/test/bin/zeek-wrapper
lrwxrwxrwx 1 johanna johanna   35 Feb 28 23:05 bro-cut -> /home/johanna/test/bin/zeek-wrapper
-rwxr-xr-x 1 johanna johanna 1.3M Feb 28 23:04 paraglob-test
-rwxr-xr-x 1 johanna johanna  38K Feb 28 23:05 rst
-rwxr-xr-x 1 johanna johanna 345M Feb 28 23:05 zeek
-rwxr-xr-x 1 johanna johanna 2.0K Feb 28 23:04 zeek-config
-rwxr-xr-x 1 johanna johanna  38K Feb 28 23:05 zeek-cut
-rwxr-xr-x 1 johanna johanna  708 Feb 28 23:04 zeek-wrapper
```

I assume this is caused by these lines in CMakelist.txt:

```
# Older plugins may still use `bro` in unit tests.
execute_process(COMMAND "${CMAKE_COMMAND}" -E create_symlink
                "${CMAKE_CURRENT_BINARY_DIR}/../zeek-wrapper.in"
                "${CMAKE_CURRENT_BINARY_DIR}/bro")
```

However I am a bit unsure what the best way to fix this is.

This was reported by Arne Welzel (@awelzel). It seems to apply to all 3.x builds, including 3.0.0. (And this currently is present in all of our binary builds - I can obviously fix it manually there, but it is not quite ideal).

**Comment by jsiwek** [comment]
> It seems to apply to all 3.x builds, including 3.0.0. (And this currently is present in all of our binary builds - I can obviously fix it manually there, but it is not quite ideal).

#832 should fix if you want to take a look.  Will schedule to patch in 3.0.3 and 3.1.1 (using `bro` in the later is essentially an error regardless), but guess you'll have to manually patch/fix in meantime.
