### ISSUE TITLE
Move libkqueue and rapidjson submodules from 3rdparty into Zeek

### ISSUE THREAD

**Issue by jsiwek** [zeek/zeek#836]
Anyone against moving these submodules up a level?  The extra indirection going through the 3rdparty repo just adds complexity (and unused duplicate in Broker) for no benefit I can tell.  Use of 3rdparty is probably best for large-ish code we want to pull in that doesn't already live in an external git repo.  The SQLite amalgamation definitely fits that.  doctest is a bit questionable (not too large, or possibly could have added entire repo as submodule instead of just taking the `.h`), but I say just leave it be for now.

**Comment by timwoj** [comment]
I don't see anything wrong with that. The 3rdparty repo seems to be getting a little large and those are definitely only used for zeek.

**Comment by rsmmr** [comment]
What's nice about having them in the 3rd party repo is that it makes it clear that those are pieces we don't control. That said, I agree that that alone isn't worth the trouble/complexity, so moving them up is fine with me.

**Comment by jsiwek** [comment]
Alright I'll take a look at moving them.

Other pedantry: the 3rdparty repo technically doesn't distinguish based on *control* since we do actually control whatever goes on in those forks/copies.  It also doesn't even help distinguish things that originated from external since there's already many smaller things outside it (siphash, getopt-long, inet_ntop, ConvertUTF etc.).  Though can use `COPYING.3rdparty` as source for that info.
