### ISSUE TITLE
Zeekctl deploy error

### ISSUE THREAD

**Issue by Wapiti08** [zeek/zeek#842]
No core file found.

Zeek 3.2.0-dev.192
Linux 4.4.0-18362-Microsoft

Zeek plugins: (none found)

==== No reporter.log

==== stderr.log
fatal error in /usr/local/zeek/share/zeek/base/init-bare.zeek, line 1: Failed to initialize kqueue: Invalid argument

==== stdout.log
max memory size         (kbytes, -m) unlimited
data seg size           (kbytes, -d) unlimited
virtual memory          (kbytes, -v) unlimited
core file size          (blocks, -c) unlimited

==== .cmdline
-i eth2 -U .status -p zeekctl -p zeekctl-live -p standalone -p local -p zeek local.zeek zeekctl zeekctl/standalone zeekctl/auto

==== .env_vars
PATH=/usr/local/zeek/bin:/usr/local/zeek/share/zeekctl/scripts:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
ZEEKPATH=/usr/local/zeek/spool/installed-scripts-do-not-touch/site::/usr/local/zeek/spool/installed-scripts-do-not-touch/auto:/usr/local/zeek/share/zeek:/usr/local/zeek/share/zeek/policy:/usr/local/zeek/share/zeek/site
CLUSTER_NODE=

==== .status
TERMINATED [fatal_error]

==== No prof.log

==== No packet_filter.log

==== No loaded_scripts.log

**Comment by Wapiti08** [comment]
The context of init-bare.zeek is:
```
@load base/bif/const.bif
@load base/bif/types.bif
```

**Comment by timwoj** [comment]
WSL isn’t really a supported platform. WSL2 should work given that it’s an actual Linux kernel running, but we don’t actively support or test against it. Zeek uses a library to abstract the OS IO queue mechanism called libkqueue. I’d be surprised it it supported WSL at all. I’ll ask the authors of that library whether they’ve ever tested it.

Tim

**Comment by Wapiti08** [comment]
> WSL isn’t really a supported platform. WSL2 should work given that it’s an actual Linux kernel running, but we don’t actively support or test against it. Zeek uses a library to abstract the OS IO queue mechanism called libkqueue. I’d be surprised it it supported WSL at all. I’ll ask the authors of that library whether they’ve ever tested it. Tim
> […](#)
> On Mar 3, 2020, at 8:28 PM, Wapiti08 ***@***.***> wrote: Linux 4.4.0-18362-Microsoft

Thank you so much. Waiting for your update.

**Comment by 0xxon** [comment]
libkqueue issue: https://github.com/mheily/libkqueue/issues/71

**Comment by a-czyrny** [comment]
I had a similar problem. Under WSL 2 (Insider Preview) zeek is running.

**Comment by timwoj** [comment]
@a-czyrny With Zeek 3.1? That's good to hear.

I set up WSL1 the other day and it definitely didn't work. I'll give WSL2 a try this week.

**Comment by a-czyrny** [comment]
Compiled the latest version.

**Comment by rsmmr** [comment]
Any update?

**Comment by rsmmr** [comment]
Not seeing a specific action item here, so closing. Please open a new ticket for any specific issues.
