### ISSUE TITLE
mysql analyzer binpac error

### ISSUE THREAD

**Issue by klsdfgi4l223** [zeek/zeek#843]
Hi all,
I noticed that the mysql analyzer does not work properly when large datasets are queried.
At some point the dpd.log shows an error like this: `Binpac exception: binpac exception: out_of_bound`. In these cases the flow is not classified as mysql, and mysql-events are not raised for it, resulting in an incomplete mysql.log.

I'm using zeek 3.0.2.

A sample pcap can be found [here](https://we.tl/t-aNLQ2QQwfD).

**Comment by grigorescu** [comment]
Thank you so much for providing a PCAP! That makes debugging this type of error significantly easier.

This uncovered a few issues (so far, one bug and one change to the protocol), and I'm working on fixing them.

**Comment by grigorescu** [comment]
topic/vladg/gh-843 has a handful of fixes that make the PCAP run cleanly.

**Comment by jsiwek** [comment]
Thanks for the patch, Vlad, it's now in `master` via 26af1f55af1fdd254427cb1af44c2c8bec9b9c78
