### ISSUE TITLE
"ts+duration" for TCP flow is missing more than just ACK

### ISSUE THREAD

**Issue by philrz** [zeek/zeek#846]
I've been recently doing some comparisons between how Zeek perceives flows (via `conn` records) vs. Wireshark. I first mentioned the issue described here on [Slack](https://zeekorg.slack.com/archives/CTGDG83B8/p1583347154008200).

Early in my studies, I came across the fine print in the [docs](https://docs.zeek.org/en/current/scripts/base/protocols/conn/main.zeek.html#type-Conn::Info) about Zeek's `duration`:

> For 3-way or 4-way connection tear-downs, this will not include the final ACK.

However, I've found some PCAPs where Wireshark/`tshark` identifies TCP flows that include packets timestamped out beyond `ts`+`duration`, and sometimes these "extras" are more than just mere ACKs.

The attached PCAP shows three such examples.

[after-close.pcap.gz](https://github.com/zeek/zeek/files/4294695/after-close.pcap.gz)

I first ran it through my "stock" Zeek v3.1.0 test environment (`zeek -C -r after-close.pcap local`). Here's the `conn` records for the three flows in JSON format for ease of viewing:

```
{
  "_path": "conn",
  "conn_state": "SF",
  "duration": "177.375569",
  "history": "ShADadgtgfFr",
  "id": {
    "orig_h": "192.168.0.51",
    "orig_p": 56370,
    "resp_h": "80.239.174.117",
    "resp_p": 443
  },
  "local_orig": null,
  "local_resp": null,
  "missed_bytes": 16656,
  "orig_bytes": 1354,
  "orig_ip_bytes": 3506,
  "orig_pkts": 41,
  "proto": "tcp",
  "resp_bytes": 35154,
  "resp_ip_bytes": 37126,
  "resp_pkts": 38,
  "service": "ssl",
  "ts": "1425567047.013408",
  "tunnel_parents": null,
  "uid": "Cjukde4hlTiXc7qm8"
}
{
  "_path": "conn",
  "conn_state": "SF",
  "duration": "177.557645",
  "history": "ShADadfFr",
  "id": {
    "orig_h": "192.168.0.51",
    "orig_p": 59552,
    "resp_h": "80.239.174.116",
    "resp_p": 443
  },
  "local_orig": null,
  "local_resp": null,
  "missed_bytes": 0,
  "orig_bytes": 7097,
  "orig_ip_bytes": 8521,
  "orig_pkts": 27,
  "proto": "tcp",
  "resp_bytes": 5887,
  "resp_ip_bytes": 7131,
  "resp_pkts": 24,
  "service": "ssl",
  "ts": "1425574220.361991",
  "tunnel_parents": null,
  "uid": "CPoo8b2dsaAPB7gtal"
}
{
  "_path": "conn",
  "conn_state": "SF",
  "duration": "7.33016",
  "history": "ShADadFft",
  "id": {
    "orig_h": "192.168.0.51",
    "orig_p": 33304,
    "resp_h": "46.246.28.85",
    "resp_p": 443
  },
  "local_orig": null,
  "local_resp": null,
  "missed_bytes": 0,
  "orig_bytes": 2595,
  "orig_ip_bytes": 3499,
  "orig_pkts": 17,
  "proto": "tcp",
  "resp_bytes": 5837,
  "resp_ip_bytes": 6708,
  "resp_pkts": 16,
  "service": "ssl",
  "ts": "1425628285.873552",
  "tunnel_parents": null,
  "uid": "C8XImM3LEkUfsOyHg4"
}
```

You can then bring up the flows for comparison in Wireshark by opening the PCAP file and using filters shown for each respective `conn` record:

* `tcp.stream eq 0`

`ts` + `duration` = `1425567224.388977`. Here we observe an additional packet timestamped `1425567224.428169` that's a pure RST. 

* `tcp.stream eq 1`

`ts` + `duration` = `1425574397.919636`. Here we observe _three_ additional packets: A FIN+ACK,  pure ACK, a pure RST.

* `tcp.stream eq 2`

`ts` + `duration` = `1425628293.203712`. Here we observe _four_ additional packets: Three pure ACKs and one PSH+ACK. Perhaps this one can be considered compliant with the doc since they're all ACKs of one form or another, though the docs seem to imply a single ACK might be all that would be missed.

**Conclusion**: Personally, I think it'd be great if Zeek's time fields could describe the span of the whole flow to the same extent Wireshark sees it, but the fact the `duration` docs include that disclaimer leads me assume there's technical reasons why it's not feasible to do so. Assuming that's still the case, then it seems the docs could benefit from more details about how Zeek perceives TCP closure and the additional classes of packets that may therefore be out beyond the `ts` + `duration`

**Comment by rsmmr** [comment]
@vpax do you have any thoughts in this?

**Comment by vpax** [comment]
Alas, I missed the original notification for this and only saw it now when @timwoj flagged it for me.

I looked into this and found what my vague memory recalled, namely that this is a conscious decision in the TCP analysis to consider a connection's "duration" to run up through the end of its productive (= data can be delivered) lifetime, not extending beyond that.  So once it's closed, packets seen subsequently (until the state-holding for the connection times out) get processed in terms of updating the associated `$history`, but not the duration.  This can include (unnecessarily) retransmitted data packets, like in one of the examples above.  An advantage of this definition of "duration" is it allows more accurate computation of connection data rates.

So I think the best resolution of this is to update the documentation as mentioned, but to not alter the semantics.
