### ISSUE TITLE
Design & implement sandboxing for Zeek processes

### ISSUE THREAD

**Issue by rsmmr** [zeek/zeek#852]
There are various ways to avoid running Zeek as root, including `setcap` and sandboxing through external tools (jails, systemd). However, with the new supervisor architecture we could now do more inside Zeek as well by sandboxing processes as we spawn them. As that's however OS-specific stuff, I propose we extend our plugin API so that such functionality can be provided externally; and then create a corresponding Linux plugin to implement it.

For reference, see the earlier discussion on this PR: #754.

**Comment by GTrunSec** [comment]
https://github.com/zeek/zeek/issues/939

**Comment by rsmmr** [comment]
There's a systemd sandboxing example here: https://github.com/zeek/zeek/pull/754#issuecomment-580652275
