### ISSUE TITLE
Make tcp is_partial flag optional

### ISSUE THREAD

**Issue by BilldePing** [zeek/zeek#858]
Occasionally sessions are missing SYN packets or do not have a proper handshake due to packet drop.

Making is_partial flag optional for the user in src/analyzer/protocol/tcp/TCP.cc, will make future analyzers produce events and records even if the tcp connection is considered partial.

This way, valuable information from the traffic will not be missed in case of packets drops.

**Comment by jsiwek** [comment]
Yes, it's likely not hard to add such an option, but it may not help as much as you'd like.  It would only help exactly the cases of a missing handshake (but all payload gets seen) or when the analyzer happens to start parsing the TCP stream at a point it expects and to which it can synchronize.  That is, if we miss the handshake, we don't know if we're starting to parse at an arbitrary point in the TCP stream and it's likely most parsers will currently generate Weird or ProtocolViolation events and fail out anyway if any amount of payload gets missed.  The long-term solution would be rewriting/redesigning protocol parsers to be able to synchronize to TCP streams from arbitrary points.

**Comment by rsmmr** [comment]
Yeah, doing this without preparing analyzers for dealing with it. would do more harm than good. I could certainly see adding the option we had analyzers that can handle it, but we don't currently, so nothing actionable for now I would say.
