### ISSUE TITLE
Repeated SYNs for unsuccessful connection attempt are seen as multiple flows

### ISSUE THREAD

**Issue by philrz** [zeek/zeek#863]
This is somewhat similar in nature to https://github.com/zeek/zeek/issues/846, but doesn't involve a connection close so I'm opening it separately.

In the attached PCAP-ng, the client is sending repeated SYNs over several seconds in an unsuccessful attempt to establish a connection. When I when I run it through my Zeek v3.1.0, it gets represented as if it were multiple `conn` records.

```
# zeek -C -r 92.pcapng 
1583768593.046597 warning in /usr/local/zeek-3.1.0-pristine/share/zeek/base/misc/find-filtered-trace.zeek, line 48: The analyzed trace file was determined to contain only TCP control packets, which may indicate it's been pre-filtered.  By default, Zeek reports the missing segments for this type of trace, but the 'detect_filtered_trace' option may be toggled if that's not desired.

# cat conn.log 
#separator \x09
#set_separator	,
#empty_field	(empty)
#unset_field	-
#path	conn
#open	2020-03-14-12-11-58
#fields	ts	uid	id.orig_h	id.orig_p	id.resp_h	id.resp_p	proto	service	duration	orig_bytes	resp_bytes	conn_state	local_orig	local_resp	missed_bytes	history	orig_pkts	orig_ip_bytes	resp_pkts	resp_ip_bytes	tunnel_parents
#types	time	string	addr	port	addr	port	enum	string	intervacount	count	string	bool	bool	count	string	count	count	count	count	set[string]
1583768586.020405	CwZo6T1pMP7DQuwrwc	192.168.10.120	62643	10.0.1.107	7000	tcp	-	4.013413	0	0	S0	-	320	0	0	-
1583768591.044151	CDDv2n3R4V3tol9D	192.168.10.120	62643	10.0.1.107	7000	tcp	-	2.002446	0	0	S0	-	128	0	0	-
#close	2020-03-14-12-11-58
```

Contrary to the warning, there was nothing "pre-filtered" about this capture. It was taken of my personal traffic on my own laptop.

Is 5 SYNs some kind of magic number after which Zeek's TCP state machine flushes state?

[92.pcapng.gz](https://github.com/zeek/zeek/files/4333229/92.pcapng.gz)

**Comment by jsiwek** [comment]
The magic number in this case is the default duration of [tcp_attempt_delay](https://docs.zeek.org/en/current/scripts/base/init-bare.zeek.html#id-tcp_attempt_delay) being 5 seconds (the SYNs in the pcap go for ~7 seconds).

Also the warning for filtered traces is just a hint/heuristic attempting to help w/ a potential pitfall that doesn't apply here.  Can be suppressed by setting `FilteredTraceDetection::enable=F`.

So together, you could run like this and get a single `conn` record logged (JSON for brevity):

```
$ zeek -C -r 92.pcapng FilteredTraceDetection::enable=F tcp_attempt_delay=10sec LogAscii::use_json=T
$ cat conn.log 
{"ts":1583768586.020405,"uid":"CmobKe4TweobSWGQQ5","id.orig_h":"192.168.10.120","id.orig_p":62643,"id.resp_h":"10.0.1.107","id.resp_p":7000,"proto":"tcp","duration":7.02619194984436,"orig_bytes":0,"resp_bytes":0,"conn_state":"S0","missed_bytes":0,"history":"S","orig_pkts":7,"orig_ip_bytes":448,"resp_pkts":0,"resp_ip_bytes":0}
```

**Comment by philrz** [comment]
Thanks for the info @jsiwek!
