### ISSUE TITLE
Multi-section pcapng with overlapping timestamps creates excess conn events

### ISSUE THREAD

**Issue by philrz** [zeek/zeek#864]
It looks like Zeek supports [pcapng](https://github.com/pcapng/pcapng). I'm not a super pro with the pcapng format, but it seems that one of its features is the concept of multiple ["sections"](http://xml2rfc.tools.ietf.org/cgi-bin/xml2rfc.cgi?url=https://raw.githubusercontent.com/pcapng/pcapng/master/draft-tuexen-opsawg-pcapng.xml&modeAsFormat=html/ascii&type=ascii#rfc.section.4.1), each of which purports to contain "(interfaces, packets) that are logically correlated". From what I've gathered, this makes it legal for a single pcapng file to consist of multiple pcapng files `cat`'ed together.

My Zeek testing where I only ever used a single-section pcapng file have all worked out fine. However, it seems like I've stumbled into a problem with multi-section files, and based on the symptoms, I think it happens when the timestamps in the different sections overlap.

Consider the two attached pcapng files. Each one contains two flows, and if opened up in Wireshark, it sees each one as two flows (i.e. `tcp.stream eq 0` and `tcp.stream eq 1` each bring up flows, but `tcp.stream eq 2` comes up empty, which is what I'd expect)

[non-overlap.pcapng.gz](https://github.com/zeek/zeek/files/4333319/non-overlap.pcapng.gz)
[overlap.pcapng.gz](https://github.com/zeek/zeek/files/4333320/overlap.pcapng.gz)

If I run the non-overlapping one through my Zeek v3.1.0, it gives me two `conn` records as I would expect.

```
# zeek -C -r non-overlap.pcapng 

# cat conn.log 
#separator \x09
#set_separator	,
#empty_field	(empty)
#unset_field	-
#path	conn
#open	2020-03-14-13-44-59
#fields	ts	uid	id.orig_h	id.orig_p	id.resp_h	id.resp_p	proto	service	duration	orig_bytes	resp_bytes	conn_state	local_orig	local_resp	missed_bytes	history	orig_pkts	orig_ip_bytes	resp_pkts	resp_ip_bytes	tunnel_parents
#types	time	string	addr	port	addr	port	enum	string	intervacount	count	string	bool	bool	count	string	count	count	count	count	set[string]
1583768523.826851	CpKdanKYRebMKeoJf	192.168.10.120	62576	104.123.204.164	443	tcp	-	0.000428	0	31	SF	-	^dfAFa	3	156	3	187	-
1583774873.399273	CaVtJg1kDLQjrBMdx8	192.168.10.120	63342	54.210.89.192	443	tcp	ssl	0.293493	2696	6387	S1	-	ShADad	12	3332	9	6863	-
#close	2020-03-14-13-44-59
```

However, if I do the same with the overlapping one, I get many excess records.

```
# zeek -C -r overlap.pcapng 

# cat conn.log 
#separator \x09
#set_separator	,
#empty_field	(empty)
#unset_field	-
#path	conn
#open	2020-03-14-13-46-24
#fields	ts	uid	id.orig_h	id.orig_p	id.resp_h	id.resp_p	proto	service	duration	orig_bytes	resp_bytes	conn_state	local_orig	local_resp	missed_bytes	history	orig_pkts	orig_ip_bytes	resp_pkts	resp_ip_bytes	tunnel_parents
#types	time	string	addr	port	addr	port	enum	string	intervacount	count	string	bool	bool	count	string	count	count	count	count	set[string]
1583768523.905549	CEBUBSWrY1ClX77m8	192.168.10.120	62552	23.203.208.145	443	tcp	-	-	-	-	OTH	-	-	^d	0	0	1	76	-
1583768523.905556	C2gUOB4MD7JmDjVGak	192.168.10.120	62552	23.203.208.145	443	tcp	-	-	-	-	SHR	-	-	^f	0	0	1	52	-
1583768523.905663	CfUCTF4i9z9BU9mYUc	192.168.10.120	62552	23.203.208.145	443	tcp	-	-	-	-	OTH	-	-	52	0	0	-
1583768523.905753	CPbxYA4VV990u1RiI8	192.168.10.120	62552	23.203.208.145	443	tcp	-	-	-	-	OTH	-	-	52	0	0	-
1583768523.905872	CzwiVC24bAo4ChEUY8	192.168.10.120	62552	23.203.208.145	443	tcp	-	-	-	-	SH	-	-	52	0	0	-
1583768523.914837	CsTJkA3T7cln7N8oHf	192.168.10.120	62552	23.203.208.145	443	tcp	-	-	-	-	OTH	-	-	^a	0	0	1	52	-
1583768523.869195	Chtobb4vfxdTXKt4re	192.168.10.120	59281	52.37.243.173	443	tcp	-	1268.534502	11071	18613	SF	-	DdAaTfF	340	28985	278	33117	-
#close	2020-03-14-13-46-24
```

Though if I use Wireshark to extract just that flow with port `62552` into its own independent pcapng file, Zeek outputs a single `conn` record for it.

I respect that out-of-order timestamps within a PCAP would cause problems for Zeek, but my interpretation of the pcapng spec's statement about "packets that are logically correlated" implies to me that each section should be treated independently. Would you say the behavior shown above is a bug?

**Comment by rsmmr** [comment]
Yeah, overlapping time ranges won't work currently, and supporting that is quite hard for Zeek as it has a basic assumption built-in that network time never goes backwards. We used to have a way to get around that by maintaining multiple independent timer queues; not immediately sure if it would work to apply that here (and we'd need to bring it back first anyways).

**Comment by rsmmr** [comment]
Closing this as I don't really see this being supported anytime soon.
