### ISSUE TITLE
smb2_negotiate_response doesn't handle unknown negotiate contexts 

### ISSUE THREAD

**Issue by benjeems** [zeek/zeek#865]
The smb2_negotiate_response event doesn't get raised when an unknown negotiate context is present in the Negotiation packets. 
For example if in the packet, the`context_type == 3` (Compression) then the current parser's CASE statement doesn't know about this, and doesn't have a default value, so the event isn't raised.

**Comment by jsiwek** [comment]
Thanks.  If there's a publicly shareable pcap to demonstrate this, it can be a bit quicker to start in on testing and patching in better behavior.

**Comment by benjeems** [comment]
Here is the pcap where I came across this bug. https://github.com/ollypwn/SMBGhost.

**Comment by jsiwek** [comment]
Thanks, candidate patch incoming via #869
