### ISSUE TITLE
Use {fmt}/libfmt/std::format for string formatting/printing

### ISSUE THREAD

**Issue by timwoj** [zeek/zeek#872]
This is a fairly large project that I've had in the back of my head for a while and I want to get opinions on it before I dive too far in.

This would entail the following:
- Remove the `fmt()` method from utils
- Replace all calls to `fmt()` with `fmt::format()`
- Replace all calls to `fprintf()` with `fmt::print()`
- While doing the above two, rework all of the format strings to use the system that fmt uses (more on this below).

Pros:
- Moving towards the `std::format` mechanism that will be in C++20, which is heavily based on libfmt.
- Potential performance improvements from libfmt. See https://github.com/fmtlib/fmt#speed-tests.
- More potential compile-time type-safety with print statements and string formatting, including not having to specify the width of an integer format. It also means we can stop having to call `c_str()` or `data()` for strings passed into format methods, since libfmt handles `std::string` directly.

Cons:
- Doing this work is really an all-or-nothing prospect. As soon as I add a `#include` for `fmt` to a header, it's going to kick off a cascade of conflicts between the `fmt` namespace and the `fmt()` method in utils. There's not an easy way to do it piece-meal.
- A forced move to the libfmt-style format strings. libfmt provides a `fmt::printf` and `fmt::fprintf` which support the standard printf-style `%` format strings, but the other format methods (including `fmt::format`) don't support that style. The new style heavily mimics python's format strings. This is actually what causes the most changes across the code, I think.  See https://fmt.dev/dev/syntax.html for more info.
- Libfmt is header-only with a single `#define`, but it also increases build times a little bit.
- Because we're changing the format strings internally, they also need to change in zeek scripts unless we include a translation layer somewhere.

**Comment by timwoj** [comment]
Digging into the `{fmt}` API a bit futher, it's possible that our existing `fmt()` method could stick around and just the implementation would change underneath. The `fmt::format_to` method could probably be used to continue to store data in a static buffer and avoid a realloc every time. On top of that, `fmt()` could call `FMT_STRING` on the format string, which gives better compile-time type-checking of the format strings and the arguments.

**Comment by jsiwek** [comment]
Good breakdown, thanks.  Generally sounds like a worthwhile project.

> * As soon as I add a `#include` for `fmt` to a header, it's going to kick off a cascade of conflicts between the `fmt` namespace and the `fmt()` method in utils.
> * Because we're changing the format strings internally, they also need to change in zeek scripts unless we include a translation layer somewhere.

Those points may warrant more planning out of an orderly migration path -- maybe not too satisfying if we have to do something like rename/deprecation shuffling and can't really start the project until after 4.0, but not breaking user code is a nice goal.

**Comment by timwoj** [comment]
> Because we're changing the format strings internally, they also need to change in zeek scripts unless we include a translation layer somewhere.

We apparently already do provide this translation layer in zeek.bif's `do_fmt` method, so we might be able to avoid that one at least.

> As soon as I add a #include for fmt to a header, it's going to kick off a cascade of conflicts between the fmt namespace and the fmt() method in utils.

This is a harder problem. One option would be to "fix" a custom clone of the {fmt} repo to rename their namespace. Then we could leave our existing `fmt()` method and reimplement it using the {fmt} methods. That would chop a big portion of the work out.

**Comment by timwoj** [comment]
With a change to {fmt} to turn it into `namespace fmtlib`, our `fmt()` method becomes this:

```
template <typename... Args>
extern const char* fmt(const char* format, Args&&... args)
	{
	static fmtlib::memory_buffer out;
	format_to(out, FMT_STRING(format), args...);
	return out.data();
	}
```

Wrapping the `format` passed to `format_to` in a call to `FMT_STRING` causes anywhere we're calling `fmt` with printf-style format strings to throw a compiler error. `memory_buffer` there is an automatically-growing buffer, similar to what we already have in `fmt()`.

**Comment by rsmmr** [comment]
I'm all for this. Some thoughts:

1. I'd rather not touch the scriptland view of format strings, but indeed: I don't think that's an issue anyways because the scriptland `fmt` does its own formatting, so we're good there.

2. If we could do this incrementally, that'd be good. If we don't want to patch `{fmt}`, is there some namespacing wrapper magic that we could do so that we import it in a way that makes it accessible (only) in a separate namespace, without conflicting with the current `fmt`? Then, once we have this in place, we can start migrating calls over bit by bit.

**Comment by jsiwek** [comment]
I only did a quick grep, but they possibly have `FMT_BEGIN_NAMESPACE` / `FMT_END_NAMESPACE` preprocessor definitions we could force to something else to avoid name conflicts.

**Comment by timwoj** [comment]
I think those are just short-cut macros to define the namespace within the library code, so if the namespace changes they only have to change it once. I can override it locally for the #include, but they hard-code use of the `fmt` namespace in other places (including in core.h, where that #define is) and that still causes the build to fail.

**Comment by timwoj** [comment]
After spending a bit of time on this, I don't think there's a good easy way to do this in a backward-compatible fashion. The three options I came up with:
1. Adding a second `fmt` method just creates a second method that we have to remove later if we want to rename it back to `fmt`. All of the `Reporter` and `DBG_LOG` methods can take format strings as well, which would require the same renaming.
2. Adding some sort of variable to the function signatures to denote what style you're using just leads to something else that needs to be removed later, and adds a lot of noise to the code. 
3. Checking for a style in the input string could be possible, but it would also potentially eat any gain in performance as it'd add a lot of extra string comparisons.

**Comment by timwoj** [comment]
For reference my starting point of changes is on `topic/timw/fmt`, if anyone wants to take a look at them. They currently pass all of the btests, but I haven't changed everything yet.

**Comment by jsiwek** [comment]
Maybe there's an option similar to (2), but instead of overloading/extending the existing function signatures to take a new "tag" that indicates old-style-fmt-string versus new-style-fmt-string, change the format string argument itself to be some "lightweight" wrapper class with an implicit conversion constructor (e.g. from `const char*`) that allows the old-style-fmt-strings to continue to just work, but then another constructor/class that one uses to explicitly signal use of new-style-fmt-string.  (maybe also some templating goop involved, e.g. potentially to avoid runtime overhead of conditionally branching between old vs. new styles)

The migration path ends up being similar to either (1) or (2), but it's maybe a bit less noisy since we're not adding functions to the API, we're just changing a single parameter's type.  Also, after the migration is done, might feel less obliged to remove the wrapper class since it doesn't hurt much and would mean a 2nd round of users updating their code.  In contrast, the other approaches introduce extra functions that make the API feel more crowded unless later removed.

**Comment by rsmmr** [comment]
This might be just a crazy idea but is there anyway we could have a way for a `.cc` file to say upfront "I'm using the new fmt", and then we could assume that for all `fmt()` in there. Maybe through a particular include, or a define, or something? We'd then migrate Zeek's code over time, and maybe even switch over at some point where a source code now needs to say "I'm using the old one, still!".

(*.h files might not fit this idea, but I suppose there aren't that many fmt() in there).

**Comment by timwoj** [comment]
> Maybe through a particular include, or a define, or something?

That could work. It's a lot of extra litter in the code, but it'd be easier to remove later. I wonder if it could be done via CMake, actually. It could define something in the src directory's CMake file and then it should only affect those files, right?

> (*.h files might not fit this idea, but I suppose there aren't that many fmt() in there).

A quick find-exec-ack says 13 files have the `%` character in them. That's probably over-counting but it's not many files at all.

**Comment by rsmmr** [comment]
> It could define something in the src directory's CMake file and then it should only affect those files, right?

I'd prefer it explicitly in the files actually, very easy to miss, or get confused, otherwise what's going on.

I'm not 100% sure yet if I'm going to like this idea, but if you can think of a way of giving it a try that's not a ton of work, that's worth a try I think, and we can all look at it and make a call.

**Comment by jsiwek** [comment]
Agree a per-file preprocessor definition to dictate format string style may be neat to try, but is it possibly more prone to style mismatches slipping in?  Say someone has a long-term pending branch/PR and adds many old-style `fmt` calls to a file, but in meantime that file got switched to new-style format strings, how vigilant do we have to be to catch those on merge, can we lean on type-system/compiler to help, and if not, how bad/visible a bug does a format mismatch cause?  Maybe other approaches need same questions evaluated.

**Comment by simonhf** [comment]
> 1. I'd rather not touch the scriptland view of format strings, but indeed: I don't think that's an issue anyways because the scriptland `fmt` does its own formatting, so we're good there.

So scriptland / Zeek script has different formatting than libfmt? That explains why I couldn't get commas in numbers from scriptland working using the syntax described here [1]. Is there any other way to get scriptland to output numbers with commas in them?

[1] https://github.com/fmtlib/fmt/issues/1020

**Comment by rsmmr** [comment]
No, our implementation isn't that flexible. It's here: https://github.com/zeek/zeek/blob/76e67ff239f2981121d15253bdf19fdf0f54df67/src/zeek.bif#L69

**Comment by timwoj** [comment]
Closing this for now. I started in on the work but `fmtlib` doesn't support generating format strings the same way we'd want to use them.
