### ISSUE TITLE
SSL cert intermediate cache means invalid cert chains can appear as valid base on first certificate alone

### ISSUE THREAD

**Issue by RCWellington** [zeek/zeek#875]
- Intermediate SSL certs are stored in the `SSL::intermediate_cache` under the first certificate seen in the relevant chain.  

If we see the situation:  
```
First : Chain 1 - [Base A | Intermediate Chain A | Root Cert A] which is valid

Then : Chain 2 - [Base A | Chain B (invalid) | Root Cert B] which is invalid
```
- When an "ok" result is seen for Chain 1, Intermediate Chain A will be stored under cert Base A in the `intermediate_cache`.  
- When chain 2 is seen, Intermediate Chain A will be extracted from `intermediate_cache` and then that chain will be verified again, rather than the new (invalid) chain. This will result in the same "ok" result being reported for the new chain.

There is a comment associated with the `ssl_cache_intermediate_ca` flag that enables the `intermediate_cache`,
```
## Use intermediate CA certificate caching when trying to validate
## certificates. When this is enabled, Zeek keeps track of all valid
## intermediate CA certificates that it has seen in the past. When
## encountering a host certificate that cannot be validated because
## of missing intermediate CA certificate, the cached list is used
## to try to validate the cert.
```

However the chain stored `intermediate_cache` seems to be used before checking the chain passed in the relevant packet.

This can be reproduced with `zeek -C -r tls1.2-valid-followed-by-invalid-same-base-cert.pcap local`

[tls1.2-valid-followed-by-invalid-same-base-cert.zip](https://github.com/zeek/zeek/files/4369425/tls1.2-valid-followed-by-invalid-same-base-cert.zip)
(Sorry github issues don't support uploading pcap files directly)

**Comment by 0xxon** [comment]
Hi,

this actually is desired behavior - which is indicated by the comment that you cite.

The reason for this is to bring the behavior of Zeek certificate validation in line with certificate validation in browsers. If you examine certificate validation in browsers you will notice that they have similar behavior. The last time I looked, Firefox has the exact same behavior as we do - it caches all valid encountered intermediate certificates and uses those for chain construction - completely ignoring the chain that was sent with a certificate. Chrome does the same, depending on OS + also respects the AIA extension (which allows downloads of missing intermediate CA certificates via http/https). Microsoft also use the AIA as far as I know.

As you noted this does indeed mean that certificates are shown as valid, even though the chain that is presented by a specific server does not allow validation of the certificate. We decided that this is desired behavior - browsers (typically) also would show such certificates as valid. This kind of server side misconfiguration is so common that it makes validation nearly useless if one does not have some kind of "fixing" chains.

As the comment also notes - if you do not want this behavior, feel free to set SSL::ssl_cache_intermediate_ca to false. This will completely disable caching and you are back to the behavior where only the presented chain will be validated.

If you have any concerns with this - feel free to comment here, reach out on the mailing list, or send me a mail directly.

Johanna

**Comment by 0xxon** [comment]
To slightly give a short version of the last comment - browser behavior (and Zeek behavior) basically is to see a server certificate as "valid" if the end-host certificate can be validated with any known chain. The chain that the server sends does not matter.
