### ISSUE TITLE
How user-defined events get raised?

### ISSUE THREAD

**Issue by QGrain** [zeek/zeek#877]
Hi, I am individual beginner of zeek, thanks for such a fantastic tool.

I am trying to define my own event handler, but I'm confused that whether the user-defined event will be triggered by the zeek engine?

As is suggested by the zeek documents, an event handler could be triggered by `schedule` or `event` **instructor**. But that is still somehow **manual-triggered** rather than **auto-triggered**.

Always be grateful for your kind explaination.

**Comment by jsiwek** [comment]
There's no generic way for the event engine to automatically trigger user-defined events at arbitrary points in the event stream (other than to `schedule` or invoke directly with `event` instructions).  There are a few specific APIs that allow registration of a user-defined event, one example being file analysis triggering user-defined events to access file data, but generally those use-cases are limited and if you want to insert logic at some point in the event stream you can do that with your own event handler for some pre-existing event rather than defining your own.

Can you give details of what you want to do?

**Comment by QGrain** [comment]
Thanks for your reply! 

Yes, I want to analyze some scanning behavior like `nmap` or `telnet`. So I have to know what kind of events they will trigger. 

After reading one relevant issue #169, I find a great tool named `misc/dump-events` to get those build-in events. However, I still have the following problems:
- Those dump-events seem **not to be complete in protocols**. In other words, what is the **total list of zeek build-in events**?
- Can zeek handle some **byte-level features** of the network packets? Such as some flags or segments of TCP/UDP.

Therefore, **if possible**, defining my own events would be more flexible for those **variable scenarios**. 

Always grateful for your kind reply.

**Comment by jsiwek** [comment]
> * Those dump-events seem **not to be complete in protocols**. In other words, what is the **total list of zeek build-in events**?

You'll find all built-in events documented somewhere in https://docs.zeek.org/en/current/script-reference/index.html, with the majority being these two locations:

* Protocol events: https://docs.zeek.org/en/current/script-reference/proto-analyzers.html
* File events: https://docs.zeek.org/en/current/script-reference/file-analyzers.html

i.e. for any particular analyzer, you can expand its entry in the sidebar and see it has an "Events" section

> * Can zeek handle some **byte-level features** of the network packets? Such as some flags or segments of TCP/UDP.

Yes, to some extent.  Such features often don't perform too well for live traffic analysis, but most usable for inspecting pcaps.  E.g. a few related events coming to mind are `new_packet`, `tcp_packet`, `tcp_options`, or `tcp_content`.

> Therefore, **if possible**, defining my own events would be more flexible for those **variable scenarios**.

If you find some aspect of a protocol/file you want to analyze, but the built-in events don't seem to cover it, there's a few ways to go:

* Extend the C++ parsing logic to add new events, or extend existing event parameters.  Patches are appreciated if you'd like to contribute them.
* If an analyzer doesn't even exist yet for what you need, you can write your own via a [plugin](https://docs.zeek.org/en/current/devel/plugins.html).
* See if someone else already did similar work and contributed a plugin for it in the [public package repository](https://github.com/zeek/packages)

See also https://zeek.org/connect for how to get involved with user/dev mailing list or Slack.  Those can be a bit better to get wider variety of guidance for non-bug-report questions.
