### ISSUE TITLE
ERSPAN with 802.1q in Payload

### ISSUE THREAD

**Issue by david-gurley** [zeek/zeek#887]
Packets captured on 802.1q trunks and shipped to Zeek over IP with ERSPAN fails to decode .  From looking at Sessions.cc, Zeek is looking for IPv4 and IPv6 after the Ethernet payload.  I would love to submit a PR for this but don't know the code base well enough.  I am attaching a sample PCAP that fails with Zeek but is successful with Wireshark.

Sessions.cc
```
if ( proto_typ == 0x0800 )
 proto = IPPROTO_IPV4;
else if ( proto_typ == 0x86dd )
  proto = IPPROTO_IPV6;
else
  {
  // Not IPv4/IPv6 payload.
  Weird("unknown_gre_protocol", ip_hdr, encapsulation, fmt("%d", proto_typ));
  return;
  

}
```
[dsc-ping01.pcap.zip](https://github.com/zeek/zeek/files/4394901/dsc-ping01.pcap.zip)
<img width="1160" alt="Screen Shot 2020-03-27 at 11 53 10 AM" src="https://user-images.githubusercontent.com/5266065/77780232-a86a6c80-7021-11ea-9f87-c2ad8bbc1f30.png">

```
more weird.log 
#separator \x09
#set_separator	,
#empty_field	(empty)
#unset_field	-
#path	weird
#open	2020-03-01-09-52-37
#fields	ts	uid	id.orig_h	id.orig_p	id.resp_h	id.resp_p	name	addl	notice	peer
#types	time	string	addr	port	addr	port	string	string	bool	string
1582807360.142640	-	172.31.1.23	0	172.31.1.135	0	unknown_gre_protocol	33024	F	zeek
#close	2020-03-01-09-52-37
```

**Comment by jsiwek** [comment]
Thanks for the report and example pcap.  Patch incoming via #889.
