### ISSUE TITLE
IntrusivePtr migration

### ISSUE THREAD

**Issue by jsiwek** [zeek/zeek#893]
Just thinking a more thorough move to `IntrusivePtr` is worth putting on the roadmap at least to decrease the frequency that people have to deal with the transitionary NewRef/AdoptRef constructor (gets a bit clunky and tiring to read/write those).

**Comment by vpax** [comment]
Agreed.  I'm in the midst of doing a lot of development in a mixed `IntrusivePtr`/traditional context, and not only is it clunky but I keep getting bitten on subtle issues like using `.get()` when I should have used `.release()`.

**Comment by rsmmr** [comment]
Closing the ticket, we'll  address remaining pieces as we get to them
