### ISSUE TITLE
Set of Pattern matches terms when it shouldn't

### ISSUE THREAD

**Issue by benjeems** [zeek/zeek#901]
When using a Set of pattern, things match which shouldn't match. Tables of patterns also have the same issue.
(zeek version 3.2.0-dev.277)

`event zeek_init() {
    local things_to_look_for: set[pattern] = {
        /a/,
    	/b/,
    	/o/};
    local value: string = "foo";
    for (thing in things_to_look_for) {
        print(thing);
        print(value);
        if (thing in value) {
            print"found match"; 
        }
    }
}
`

This Produces

`/^?(a)$?/
foo
found match
/^?(b)$?/
foo
found match
/^?(o)$?/
foo
found match`

**Comment by jsiwek** [comment]
Thanks for the report, patch incomvia via #902
