### ISSUE TITLE
Improper logging of vector/set

### ISSUE THREAD

**Issue by micrictor** [zeek/zeek#907]
I'm building a plugin to add four feature vectors to all SSL logs, but the vector that is built is improperly output to _ssl.log_.

I've tested in-line with the current master (4ee84b69f29aa5c192abcf7e6767abca7eb04183), built with no added options (./configure && make && make install), and with the current LTS package (3.0.3) on Ubuntu 18.04.

An example of the issue can be found by loading in my plugin (https://github.com/micrictor/spl-spt), enabling the debug print at https://github.com/micrictor/spl-spt/blob/master/spl-spt.zeek#L71, and running Zeek against any of the sample PCAPs included in my repository. Comparing the results of the debug output and the logs contained in _ssl.log_, there are a large number of elements that are not being output to the log.

The confusing part is that, as far as I can tell, `to_json` mirrors the way that the Ascii JSON formatter expands vectors. 

https://github.com/zeek/zeek/blob/a5d71ed2d2f16bb8c3ab5366ceaefc375be1524a/src/threading/formatters/JSON.cc#L174-L182

https://github.com/zeek/zeek/blob/876c803d75969c241cd964a3d6cdd862c1465be7/src/Val.cc#L614-L625

Further throwing a wrench into my understanding of the problem, the truncation doesn't always occur at a specific index. For example, when using _samples/google/google-webbrowse.pcap_, the below are the full vector and the logged vector for the last observed TLS session, respectively:
```
$ zeek -r /opt/zeek/site/zeek/local.zeek -r samples/google/google-webbrowse.pcap
...
[40,811]
```

```
$ jq -s '.[0].orig_spl' ssl.log
[40]
```

Note that only the first element is logged. But, with, the second observed TLS session, the first three elements are successfully logged.
```
$ zeek -r /opt/zeek/site/zeek/local.zeek -r samples/google/google-webbrowse.pcap
...
[40,82,2091,33,37,130,131,132,133,37,133,134,135,136,37,136,37,2098,138,37]
```

```
$ jq -s '.[1].orig_spl' ssl.log 
[
  40,
  82,
  2091
]
```

I'm unsure how to proceed. I've tried both methods of adding an element to a vector:
```
c$ssl$orig_spl += len; # Appending
c$ssl$orig_spl[|c$ssl$orig_spl|] = len; # Explicit indexing
```

**Comment by jsiwek** [comment]
Thanks for the detailed example.  Don't think it's a fundamental issue with the logging of such values, but more the expectation of when the `ssl.log` entry is written compared to the point in time at which you're modifying the fields.

Looks like the log entries are written in the `ssl_established` event, but you modify fields in the `ssl_encrypted_data` events that follow after it, so my suggestion would be to perhaps to just write out your own separate log file.

**Comment by micrictor** [comment]
You were correct, it was a time-of-use/time-of-write error. Thank you for your help!
