### ISSUE TITLE
Support for Non-IP protocols

### ISSUE THREAD

**Issue by timwoj** [zeek/zeek#910]
This is a very large task that has been on the Zeek roadmap for a very long time. I took a little bit of time and started digging into what would be required and where I still have questions that need to answered before any work can start. For reference, I started from the point of capturing a packet and worked upward into the analyzer framework from there.

`Packet`:
- This will require changes. 
- This could become a base class for different kinds of Packet objects for other link types
- `GetLinkHeaderSize()` and `ProcessLayer2()` will need modification to handle other link types.
- `Layer3Proto` in the current `Packet` class doesn’t make sense for other link types.
- All of this will likely be fixed by #248 , which adds pluggable support for other Layer 2 protocols.

`PktSrc`:
- Shouldn’t require any changes.
- Packet Sources just get data, create a Packet from it, and pass it on to net_packet_dispatch.
- For packet sources handling non-IP packets, they’ll likely need to override Opened() to use other link header sizes, etc.
- `Process()` can remain as is, since an overridden packet type would handle the uncommon parts
- Same as above, with #248 

`Net`:
- Shouldn’t require any changes. The Net methods don’t do any packet inspection, they just pass them along to Sessions.

`Sessions`:
- This will require changes.
- `Sessions` and everything that it calls are entirely based on the premise that it’s receiving IP packets.
- `NextPacket()` checks for IP Layer 3 protocols, but handles ARP separately than the standard analyzer flow (since ARP isn’t IP-based). For example, ARP doesn't create conn.log entries since there's no connection and because Conn can't handle that (see the next section below).
- `DoNextPacket()` takes an `IP_Hdr` object as an argument. This is called when `NextPacket()` discovers an IPv4/IPv6 layer 3 protocol.
- The `Session` code could become a base class for a sort of plugin-based system of `Session` handlers. The existing `Session` code could be a manager and individual `Session` plugins could register for processing based on the L3 protocols they support. The manager would handle packet dispatch based on what type of packet is being passed in, reported by the packets themselves. This is just an off-the-cuff idea, and I'm not sure it would work unless the lookup for types is fast enough.

`Conn`:
- This will require changes.
- Everything in Conn assumes that a connection is based on the existing 5-tuple key.
- The changes here are the focus of #284. The work to fix that can probably take place alongside anything done for this GHI.

`Analyzer`:
- These will all require changes in varying ways.
- Across the board, analyzers take an `IP_Hdr` object as an argument for a large number of methods. This is especially true of the `DeliverPacket()` method that all analyzers override from the base `Analyzer`. `IP_Hdr` could inherit from some sort of base class and `DeliverPacket()` could take that as the argument, but it would require a much deeper dive into the code to see what effects that would have.

Open Questions:
- Are there any protocols to look at first?
- Does anyone have any sample data anywhere of this stuff?
- Can any of this be done before #248 is done?

**Comment by vpax** [comment]
Can you remind us what's the impetus / sample use case behind this?

**Comment by klsdfgi4l223** [comment]
I can think of a use case for this: Analysis of wifi captures with 802.11 frames/events.

**Comment by vpax** [comment]
Why isn't Wireshark the right tool for this?
Or if you mean you want to be able to analyze the TCP/IP content of such frames, then that's adding another link layer to Zeek, not a non-IP protocol.

**Comment by timwoj** [comment]
There’s a drive for capturing IoT protocols and some industrial control protocols, which aren’t all necessarily IP-based. Some of them are thin wrappers around IP protocols, but we still need to unwrap that (and potentially have re-entrant session handling). As for link-layer protocols, that’s being worked on separately in #248.

**Comment by vpax** [comment]
Ah ok, thanks for the context.  Seems like this is going to take a lot of thought to architect it well!

**Comment by timwoj** [comment]
> Ah ok, thanks for the context. Seems like this is going to take a lot of thought to architect it well!

Very much so.

**Comment by rsmmr** [comment]
The plan is to integrate IP with the new packet analyzer framework (see #248)

**Comment by timwoj** [comment]
I'm going to close out this issue and open a separate one that covers just moving IP.
