### ISSUE TITLE
Internal error when mixing "return when" with a local of type "any"

### ISSUE THREAD

**Issue by vpax** [zeek/zeek#920]
If you have a local of type `any` that's assigned to a **type** value, in the same function that uses `return when`, Zeek crashes with `internal error: cloning illegal base type`.

(For some reason github isn't letting me attach the `.zeek` script, so here it is in its unindented glory.)

type c: count;
function foo(): count
        {
        local bar: any;
        bar = c;
        return when ( 5 > 3 )
                {
                return 9;
                }
        }

event zeek_init()
        {
        when ( local b = foo() )
                print b;
        }

**Comment by vpax** [comment]
Did I miss a UI for doing this that (1) allows me to attach scripts, and (2) allows me to say what version of Zeek this is against?  (It's `3.2.0-dev.332-debug`.)

**Comment by vpax** [comment]
Commit `676698c5f7077d6c8d7b866b1a7b2388b221bc50` in `topic/vern/script-opt` aims to fix this.

**Comment by jsiwek** [comment]
> Did I miss a UI for doing this that (1) allows me to attach scripts

No, likely just GitHub restriction on attachment file name extensions -- think naming as `.txt` works.  Or for short scripts like that, inserting in code block is ok.  Example GitHub MarkDown you can use:

````
```zeek
event zeek_init()
    { print "example"; }
```
````

> and (2) allows me to say what version of Zeek this is against? (It's `3.2.0-dev.332-debug`.)

Just leaving version details in comment is good.

> Commit [676698c](https://github.com/zeek/zeek/commit/676698c5f7077d6c8d7b866b1a7b2388b221bc50) in `topic/vern/script-opt` aims to fix this.

Thanks, would you mind putting that into separate branch, add a new btest derived from the example Zeek script you gave, and make a Pull Request for that?

**Comment by jsiwek** [comment]
Fix now in `master` via b776f17cea45ae67a2c110857b4a7aa4921c2a0c, thanks.
