### ISSUE TITLE
Loading script subdirectory fails under 3.1.x

### ISSUE THREAD

**Issue by PSChrisHinshaw** [zeek/zeek#921]
As posted to the Zeek development slack channel:
I'm porting some plugins from Zeek 3.0 to 3.1.1, and ran into an odd use case.  The plugin scripts directory has a subdirectory, but those scripts are failing to load:
```
[root@ip-172-30-0-245 ~]# zeekctl deploy
checking configurations ...
logger scripts failed.
fatal error in /usr/local/zeek/lib/zeek/plugins/Zeek_protocol/scripts/./init.zeek, line 1: can't find ./subdir
manager scripts failed.
fatal error in /usr/local/zeek/lib/zeek/plugins/Zeek_protocol/scripts/./init.zeek, line 1: can't find ./subdir
proxy-1 scripts failed.
fatal error in /usr/local/zeek/lib/zeek/plugins/Zeek_protocol/scripts/./init.zeek, line 1: can't find ./subdir
worker-1-1 scripts failed.
fatal error in /usr/local/zeek/lib/zeek/plugins/Zeek_protocol/scripts/./init.zeek, line 1: can't find ./subdir
[root@ip-172-30-0-245 ~]# ls /usr/local/zeek/lib/zeek/plugins/Zeek_protocol/scripts/
subdir  init.zeek  __load__.zeek  __preload__.zeek  types.zeek
[root@ip-172-30-0-245 ~]# cat /usr/local/zeek/lib/zeek/plugins/Zeek_protocol/scripts/./init.zeek
@load ./subdir
[root@ip-172-30-0-245 ~]# ls /usr/local/zeek/lib/zeek/plugins/Zeek_protocol/scripts/subdir/
files.zeek  __load__.zeek  main.zeek  utils.zeek
```
Please let me know if I have the syntax incorrect in the `init.zeek` file, or if anyone else is seeing this type of error. 

The problem turned out to be trying to `@load` a subfolder from a script file (i.e. `init.zeek`) instead of `__load__.zeek`.  If I moved the `@load ./subdir` into the `__load__.zeek` file, the plugin successfully loads.  

Per Jon Siwek, this is not an intentional change and warrants a bug report.  Please let me know if additional detail would be helpful.

**Comment by jsiwek** [comment]
Can you provide a self-contained example that can be used to reproduce that behavior?

**Comment by PSChrisHinshaw** [comment]
Apparently not.  I tried creating a new plugin with the `init-plugin` script, then a couple minor changes to exhibit the bug.  However, when I built the plugin and ran `zeekctl deploy`, there was no error.  I went back to the original plugin and changed it back to load the subdirectory from `init.zeek`, and it no longer failed.

Please close this bug, as I am not able to reproduce.  If I run into it again, I will make sure to provide a self-contained example.

**Comment by jsiwek** [comment]
Thanks, yes please followup if you figure out how to produce that behavior.  Possible guess is maybe something had gotten unintentionally soft/hard-linked in your filesystem.
