### ISSUE TITLE
"when" expressions lack order-of-evaluation guarantees

### ISSUE THREAD

**Issue by vpax** [zeek/zeek#927]
The following script generates `no such index (x[9])`:
```
global x: table[count] of count;
function buggy_func(): bool
        {
        when ( 9 in x && x[9] > 3 )
                print "yep";
        }

event zeek_init()
        {
        buggy_func();
        }
```
Personally, I'd be okay with tightening the definition of what's allowed in a "when" expression rather than trying to support the above (which IIRC would be a pain).  The documentation currently states just that the expression's type must be `bool`.

**Comment by rsmmr** [comment]
Hmm ... I'm actually surprised this is not working, the `9 in x` should be guarding the index lookup and that's working fine outside of a when expression (just tried it with a `print 9 in x ...`). Am I missing something? Why do you think it would be a pain to support?
