### ISSUE TITLE
Zeek not reading from a script file that's a link

### ISSUE THREAD

**Issue by philrz** [zeek/zeek#928]
# Repro

I've reproduced this issue using Zeek v3.1.2 compiled on an Ubuntu 18.04 LTS system.

The base a [standard Zeek install](https://docs.zeek.org/en/current/install/install.html):

```
# wget https://download.zeek.org/zeek-3.1.2.tar.gz
# tar xzvf zeek-3.1.2.tar.gz
# cd zeek-3.1.2/
# apt-get -y install cmake make gcc g++ flex bison libpcap-dev libssl-dev python-dev swig zlib1g-dev
# ./configure --prefix=/usr/local/zeek
# make -j8 install
```

At this point I can make Zeek logs from my pcaps just fine.

```
# wget -O - https://archive.wrccdc.org/pcaps/2018/wrccdc.2018-03-23.010014000000000.pcap.gz | gunzip -c > wrccdc.pcap
# /usr/local/zeek/bin/zeek -C -r wrccdc.pcap
# ls *.log
conn.log   http.log  packet_filter.log  ssh.log    x509.log
dns.log    ntlm.log  pe.log             ssl.log
files.log  ntp.log   smb_mapping.log    weird.log
```

So far so good. Now let's say I was obsessed with saving a few bytes of storage.

I notice that this file:

```
# cat /usr/local/zeek/share/zeek/base/frameworks/dpd/__load__.zeek
@load ./main
```

...is byte-for-byte the same as these other files:

```
# sha256sum /usr/local/zeek/share/zeek/base/frameworks/dpd/__load__.zeek
48093086dda744434d06738145eaed483e88d9a516063a827af4a8db79ae9030  /usr/local/zeek/share/zeek/base/frameworks/dpd/__load__.zeek
# sha256sum /usr/local/zeek/share/zeek/policy/files/unified2/__load__.zeek
48093086dda744434d06738145eaed483e88d9a516063a827af4a8db79ae9030  /usr/local/zeek/share/zeek/policy/files/unified2/__load__.zeek
# sha256sum /usr/local/zeek/share/zeek/base/files/x509/__load__.zeek
48093086dda744434d06738145eaed483e88d9a516063a827af4a8db79ae9030  /usr/local/zeek/share/zeek/base/files/x509/__load__.zeek
# sha256sum /usr/local/zeek/share/zeek/base/frameworks/reporter/__load__.zeek
48093086dda744434d06738145eaed483e88d9a516063a827af4a8db79ae9030  /usr/local/zeek/share/zeek/base/frameworks/reporter/__load__.zeek
```

So I decide to replace them all with links to a single set of bytes:

```
# mv /usr/local/zeek/share/zeek/base/frameworks/dpd/__load__.zeek /tmp/master
# ln /tmp/master /usr/local/zeek/share/zeek/base/frameworks/dpd/__load__.zeek
# rm /usr/local/zeek/share/zeek/policy/files/unified2/__load__.zeek
# ln /tmp/master /usr/local/zeek/share/zeek/policy/files/unified2/__load__.zeek
# rm /usr/local/zeek/share/zeek/base/files/x509/__load__.zeek
# ln /tmp/master /usr/local/zeek/share/zeek/base/files/x509/__load__.zeek
# rm /usr/local/zeek/share/zeek/base/frameworks/reporter/__load__.zeek
# ln /tmp/master /usr/local/zeek/share/zeek/base/frameworks/reporter/__load__.zeek
```

Now Zeek fails with an error:

```
# /usr/local/zeek/bin/zeek -C -r wrccdc.pcap 
error in /usr/local/zeek/share/zeek/base/protocols/dce-rpc/./main.zeek, line 51: "redef" used but not previously defined (DPD::ignore_violations)
```

...and yet the files still show themselves to be byte-for-byte the same as they were before:

```
# sha256sum /usr/local/zeek/share/zeek/base/frameworks/dpd/__load__.zeek
48093086dda744434d06738145eaed483e88d9a516063a827af4a8db79ae9030  /usr/local/zeek/share/zeek/base/frameworks/dpd/__load__.zeek
# sha256sum /usr/local/zeek/share/zeek/policy/files/unified2/__load__.zeek
48093086dda744434d06738145eaed483e88d9a516063a827af4a8db79ae9030  /usr/local/zeek/share/zeek/policy/files/unified2/__load__.zeek
# sha256sum /usr/local/zeek/share/zeek/base/files/x509/__load__.zeek
48093086dda744434d06738145eaed483e88d9a516063a827af4a8db79ae9030  /usr/local/zeek/share/zeek/base/files/x509/__load__.zeek
# sha256sum /usr/local/zeek/share/zeek/base/frameworks/reporter/__load__.zeek
48093086dda744434d06738145eaed483e88d9a516063a827af4a8db79ae9030  /usr/local/zeek/share/zeek/base/frameworks/reporter/__load__.zeek
```

I looked at `strace` to see how file access is different in the successful run vs. the failure case.

```
# strace /usr/local/zeek/bin/zeek -C -r wrccdc.pcap 2> strace.out
```

In the successful case:

```
access("/usr/local/zeek/share/zeek/base/frameworks/dpd/__load__.zeek", R_OK) = 0
openat(AT_FDCWD, "/usr/local/zeek/share/zeek/base/frameworks/dpd/__load__.zeek", O_RDONLY) = 9
...
fstat(9, {st_mode=S_IFREG|0644, st_size=13, ...}) = 0
read(9, "@load ./main\n", 8192)         = 13
```

Whereas in the failure case, it seems to close it immediately without reading anything:

```
access("/usr/local/zeek/share/zeek/base/frameworks/dpd/__load__.zeek", R_OK) = 0
openat(AT_FDCWD, "/usr/local/zeek/share/zeek/base/frameworks/dpd/__load__.zeek", O_RDONLY) = 9
fstat(9, {st_mode=S_IFREG|0644, st_size=13, ...}) = 0
close(9)                                = 0
```

I'm not a C++ developer, so I'm hoping someone here might know: Is there something unique about how Zeek opens/reads script files that would explain this? Any workaround?

# Why does this matter?

The [Brim](https://github.com/brimsec/brim) app that I work on includes an embedded Zeek artifact that's used for turning pcaps into Zeek events. We're [working on a Linux release](https://github.com/brimsec/brim/issues/586), and someone from our community made us aware of [Flatpak](https://flatpak.org/) as an option we could use to package an app for users that might not be running the most standard distros like Debian and RedHat.

The symptom described above surfaced for us when trying to get the Flatpak version working, and I narrowed it down to the root cause described above that seems to have to do with linked files rather than anything specific to Flatpak. As I only just learned, myself, the links come into play because Flatpak relies on a [deduplication scheme](https://blogs.gnome.org/alexl/2017/10/02/on-application-sizes-and-bloat-in-flatpak/) that attempts to minimize storage used by keeping one master copy of each unique set of file contents and then hard-linking to locations in each app that use those bytes. While I suppose we don't _have_ to pursue Flatpak, now that we've found the condition, I figured it's worth pointing out since maybe it's a problem in Zeek that might surface in other contexts (or if someone else decides to pick up and try to make a Flatpak version in the future).

**Comment by JustinAzoff** [comment]
yeah.. see this related issue: https://github.com/zeek/zeek/issues/804

Looks like this sort of filesystem deduplication is becoming more common.

**Comment by philrz** [comment]
Thanks @JustinAzoff. We're thinking of workarounds to get us past it. One of my colleagues thought of what seems like a decent hack: In the packaging step, we could put a unique comment at top of each file ending in `.zeek` / `.bro` to defeat the deduplication scheme.

Even assuming we get it working, per the comment from @jsiwek in https://github.com/zeek/zeek/issues/804, yeah, it sure would seem great if there were a way to make Zeek tolerant of this when some tool does it at the filesystem layer. I saw from the [mailing list post](http://mailman.icsi.berkeley.edu/pipermail/zeek/2019-March/014035.html) that you were instrumental in identifying this the first time it happened. Not sure how much sleuthing it took you, but not knowing the code, it certainly took me a while to realize links were the culprit. It's a bummer to think of future generations losing whole afternoons stumbling onto the same.

**Comment by rsmmr** [comment]
So our loading code indeed uses inodes to avoid pulling in the same file multiple times. That doesn't seem quite right, and we should probably go back to using pathnames, but then go through `realpath` stillto  avoid loading files multiple times that are symlinked. Does that sound right?

**Comment by jsiwek** [comment]
> should probably go back to using pathnames, but then go through `realpath` stillto avoid loading files multiple times that are symlinked. Does that sound right?

Yeah, normalized/realpath is what I'm imagining, too.

**Comment by philrz** [comment]
I've verified the fix using the original repro steps above on a compile of Zeek `master` as of commit `1fe822a`. After having put hard links in place, the logs now get generated without error. Thanks for the fix @jsiwek!
