### ISSUE TITLE
Validation of dhcp address in zeek_dhcp

### ISSUE THREAD

**Issue by ManofWax** [zeek/zeek#929]
Hello,
I'm seeing this logs:
```
{"_path":"dhcp","_write_ts":"2020-04-24T07:45:53.551066Z","ts":"2020-04-24T07:45:33.656837Z","uids":["CdQ0oS1tHIs97C6s5a"],"client_addr":"10.10.10.254","mac":"52:41:53:20:00:40:40:40","host_name":"foobar","client_fqdn":"foobar.example.com","requested_addr":"10.10.10.130","msg_types":["DISCOVER","DISCOVER","REQUEST","REQUEST"],"duration":1.0525152683258057}
```

The `mac` address is wrong (is longer than it should be). I think it could be due to a bug in vmware: https://communities.vmware.com/thread/563783

It looks like zeek truncate the mac address at an arbitrary lenght (that it is longer then the one defined in the RFC for mac addresses).

It may make sense to truncate the MAC address at the correct lenght or to no generate bro_dhcp logs at all if the mac address is longer than it should be?

**Comment by 0xxon** [comment]
Do you randomly have a pcap of this? That would make this way easier.

Generally - my feeling is that we should just display what actually is in the packet - even if the packet breaks specifications by putting in nonsensical values. So - I would actually opt to make this display the actual value send in the broken packets -  where the pcap would come in helpful :)

**Comment by jsiwek** [comment]
> Generally - my feeling is that we should just display what actually is in the packet

I also think that.

**Comment by rsmmr** [comment]
@ManofWax did you have  a trace for this?

**Comment by 0xxon** [comment]
I am going to close this since there is currently nothing to do.

If you have a pcap that shows this problem, please re-open this :)
