### ISSUE TITLE
Zeek doesn't extract exe or office files

### ISSUE THREAD

**Issue by hankjrad** [zeek/zeek#932]
I applied the attached script (named extract-myfiles) which i saved it in /usr/local/zeek/share/zeek/policy/frameworks/files/ folder and modified the main.zeek file accordingly which is located in /usr/local/zeek/share/zeek/zeekctl/main.bro by adding @load /frameworks/files/extract-myfiles and commenting the existing default one. I am not sure if these are the right steps. Then I run ./zeekctl deploy and things went fine.

The problem is that only zip and txt files are extracted but not exe or office files i.e. docx or xlsx. I couldn't identify the issue although I downloaded many exe and office files from SMB and http sites. Please help.
![zeek-script](https://user-images.githubusercontent.com/64302811/80274165-18334c00-86e1-11ea-8fa0-c97fdae201b4.png)

**Comment by 0xxon** [comment]
Hi,

This looks like more of a usage question than a bug in Zeek.

We don't use GitHub issues for support questions. Questions like this are best answered using our  mailing list, which is followed by Zeek developers and professional users - where your question is also seen by many more people. You can join here:

http://mailman.icsi.berkeley.edu/mailman/listinfo/zeek

Once you receive confirmation you’ve been added to the list, send this question there.

 Johanna
