### ISSUE TITLE
Testimony support

### ISSUE THREAD

**Issue by MalakhatkoVadym** [zeek/zeek#935]
Testimony is a single-machine, multi-process architecture for sharing AF_PACKET data across processes. Zeek multiprocess architecture is really good for using with testimony load balancing (PACKET_FANOUT_HASH type it's balancing packets depending on sessions). And it's much easier in configuration and testing than pf-ring.
 
https://github.com/google/testimony

**Comment by jsiwek** [comment]
I'm guessing this could be done entirely in a `PktSrc` plugin for Zeek and any decision to include that plugin in standard Zeek release for convenience would likely be based on popularity/demand.    You may want to first try asking around on the mailing list or slack if anyone already made such a plugin or would be interested in helping develop/maintain one.

**Comment by JustinAzoff** [comment]
If you're not already aware, there is a plugin: https://github.com/J-Gras/zeek-af_packet-plugin that uses af_packet and PACKET_FANOUT_HASH directly.

**Comment by MalakhatkoVadym** [comment]
@jsiwek 
I already have some working code I can show for now which can be used with lb_custom plugin (using environment variables). I will create pull request soon.

**Comment by MalakhatkoVadym** [comment]
Created first version of this plugin.

https://github.com/MalakhatkoVadym/zeek-testimony-plugin

**Comment by rsmmr** [comment]
Closing this since there's the plugin available now.
