### ISSUE TITLE
 I want to get the macaddress of the source host and the destination host in http.log

### ISSUE THREAD

**Issue by sssnsss** [zeek/zeek#940]
But there is no field about macaddress in http.log. I should add macaddress in http.log and get macaddress.

**Comment by 0xxon** [comment]
Hi,

We don't use GitHub issues for support questions. Questions like this are best answered using our  mailing list, which is followed by Zeek developers and professional users. You can join here:

http://mailman.icsi.berkeley.edu/mailman/listinfo/zeek

Once you receive confirmation you’ve been added to the list, send this question there.

 Johanna
