### ISSUE TITLE
Make issues/Errors . 

### ISSUE THREAD

**Issue by fouroctets** [zeek/zeek#941]
Good afternoon,

I have been using the Model 4 raspberry Pi with 4GB of ram. I was able to ./configure, make, and sudo make install up until yesterday when I started to encounter make issues/errors that I do not understand and could not find a related duplicate issue to try and work off of.  

OS:
Linux raspberrypi 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l GNU/Linux
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian

Below is the 94% mark where make fails every single time as of yesterday. 

` [ 94%] Building CXX object src/CMakeFiles/zeek.dir/Func.cc.o
In file included from /home/pi/zeek/src/Func.cc:739:
zeek.bif: In function ‘Val* mmdb_getvalue(MMDB_entry_data_s*, int, int)’:
zeek.bif:3863:47: error: cannot convert ‘IntrusivePtr<Val>’ to ‘Val*’ in return
In file included from /home/pi/zeek/src/Func.cc:739:
zeek.bif: In function ‘BifReturnVal BifFunc::bro_lookup_asn(Frame*, const Args*)’:
zeek.bif:4090:25: error: operands to ?: have different types ‘IntrusivePtr<Val>’ and ‘Val*’
make[3]: *** [src/CMakeFiles/zeek.dir/build.make:741: src/CMakeFiles/zeek.dir/Func.cc.o] Error 1
make[3]: Leaving directory '/home/pi/zeek/build'
make[2]: *** [CMakeFiles/Makefile2:2556: src/CMakeFiles/zeek.dir/all] Error 2
make[2]: Leaving directory '/home/pi/zeek/build'
make[1]: *** [Makefile:152: all] Error 2
make[1]: Leaving directory '/home/pi/zeek/build'
make: *** [Makefile:15: all] Error 2 `

**Comment by jsiwek** [comment]
Thanks for reporting that, should now be fixed in `master` via 4a76229.
