### ISSUE TITLE
 problem with interface wlan0 (pcap_error: socket: Operation not permitted (pcap_activate))

### ISSUE THREAD

**Issue by powerqueue** [zeek/zeek#945]
Hello team - exploring Zeek based on this Youtube talk by Travis Smith:
BSidesSF 110 Sweet Security Deploying a Defensive Raspberry Pi

https://www.youtube.com/watch?v=7DFg9Ez2sJE&t=589s

Also, brand new to Zeek. Got the latest version from here (3.4.2) and compiled it and configured according to your instructions. The only difference is that i'm trying to monitor my wlan0 interface. Just to learn. I also tried it with eth0 same error:
[zeek]
type=standalone
host=localhost
#interface=eth0
interface=wlan0

When i run "deploy" or "start" on zeekctl I get the following "diag" details:
[ZeekControl] > diag
[zeek]

No core file found.

Zeek 3.2.0-dev.443
Linux 4.19.75-v7l+

Zeek plugins: (none found)

==== No reporter.log

<b>==== stderr.log
fatal error: problem with interface wlan0 (pcap_error: socket: Operation not permitted (pcap_activate))
</b>

==== stdout.log
max memory size         (kbytes, -m) unlimited
data seg size           (kbytes, -d) unlimited
virtual memory          (kbytes, -v) unlimited
core file size          (blocks, -c) unlimited

==== .cmdline
-i wlan0 -U .status -p zeekctl -p zeekctl-live -p standalone -p local -p zeek local.zeek zeekctl zeekctl/standalone zeekctl/auto

==== .env_vars
PATH=/home/pi/zeek/zeek2/zeek/bin:/home/pi/zeek/zeek2/zeek/share/zeekctl/scripts:/home/pi/zeek/zeek2/zeek/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
ZEEKPATH=/home/pi/zeek/zeek2/zeek/spool/installed-scripts-do-not-touch/site::/home/pi/zeek/zeek2/zeek/spool/installed-scripts-do-not-touch/auto:/home/pi/zeek/zeek2/zeek/share/zeek:/home/pi/zeek/zeek2/zeek/share/zeek/policy:/home/pi/zeek/zeek2/zeek/share/zeek/site
CLUSTER_NODE=

==== .status
TERMINATED [fatal_error]

==== No prof.log

==== No packet_filter.log

==== No loaded_scripts.log

[ZeekControl] >

**Comment by powerqueue** [comment]
I have a very straightforward config - just getting started as I was mentioning.
networkd.cfg:
# List of local networks in CIDR notation, optionally followed by a
# descriptive tag.
# For example, "10.0.0.0/8" or "fe80::/64" are valid prefixes.

10.0.0.0/8          Private IP space
172.16.0.0/12       Private IP space
192.168.0.0/16      Private IP space
192.168.x.x/24          Private IP space

zeekctl.cfg:
## Global ZeekControl configuration file.

###############################################
# Mail Options

# Recipient address for all emails sent out by Zeek and ZeekControl.
#MailTo = root@localhost
MailTo = **my email address**

# Mail connection summary reports each log rotation interval.  A value of 1
# means mail connection summaries, and a value of 0 means do not mail
# connection summaries.  This option has no effect if the trace-summary
# script is not available.
MailConnectionSummary = 1

# Lower threshold (in percentage of disk space) for space available on the
# disk that holds SpoolDir. If l

**Comment by jsiwek** [comment]
Unprivileged users aren't allowed to capture network traffic, a typical suggestion is to set the necessary capabilities on the zeek binary like `sudo setcap cap_net_raw+eip <path_to_zeek>/bin/zeek`.  Alternatively, running as `root` user works.

As you're starting out, I'd also suggest posing questions to either the mailing list or slack (see https://zeek.org/connect/) rather than GitHub to get quicker and wider variety of feedback.

**Comment by powerqueue** [comment]
Yep - that worked. Thank you for your help @jsiwek

**Comment by awelzel** [comment]
> will this "sudo setcap cap_net_raw+eip <path_to_zeek>/bin/zeek" settings get removed after reboot

It will not get removed after a reboot.

**Comment by gokul656** [comment]
Actually if you see [pcap crates](https://crates.io/crates/pcap) the've mentioned to provide certain permission for the build file.

Note: If not running as root, you need to set capabilities like so:
```
 sudo setcap cap_net_raw,cap_net_admin=eip path/to/bin
```
