### ISSUE TITLE
Add DCE-RPC endpoints and methods ID from the bzar project

### ISSUE THREAD

**Issue by l0x-c0d3z** [zeek/zeek#953]
Hi.
The BZAR project from MITRE ATT&CK has a script (https://github.com/mitre-attack/bzar/blob/master/scripts/bzar_dce-rpc_consts.bro ) that adds a lot of DCE-RPC endpoints and methods. It would be really great to see those merged into upstream Zeek.

They even have an issue [here](https://github.com/mitre-attack/bzar/issues/6)

**Comment by l0x-c0d3z** [comment]
I've created a pull request: https://github.com/zeek/zeek/pull/954

**Comment by neu5ron** [comment]
this is amazing! thank you!

**Comment by 0xxon** [comment]
I wonder if we should get permission to redistribute this under the Zeek BSD license, before merging it.

(In the package it is Apache2 - which we could do, but it would need another mention in our third-party-license text. Which would be neat to avoid for a script).

**Comment by mfrndz** [comment]
Permission granted.  I changed the BZAR license from Apache to BSD.

**Comment by l0x-c0d3z** [comment]
Awesome !
