### ISSUE TITLE
"fallthrough" should not be permitted for type-based switches

### ISSUE THREAD

**Issue by vpax** [zeek/zeek#955]
In type-based switches, `fallthrough` has poor semantics since the type changes across cases.  The following generates a fatal `value used but not set`:
> function buggy_switch(x: any)
        {
        switch ( x )
                {
                case type int as i:
                        print "int", i;
                        fallthrough;
                case type double as d:
                        print "double", d;
                        break;
                }
        }
>
> event zeek_init()
        {
        buggy_switch(+3);
        }

**Comment by jsiwek** [comment]
Think it's not generally `fallthrough` + type-based switch, but specifically when the type-based switch auto-casts via `as`.  E.g. this could at least be a valid/logical usage:

```zeek
local x: any = +3;

switch ( x ) {
case type int:
	print "special handling for 'int' types";
	fallthrough;
case type count:
	print "common handling for integral types";
	break;
}

```

**Comment by vpax** [comment]
I agree in principle ... though it also seems like a recipe for disaster even if there is no auto-casting.  Personally, I'd rather be forced to refactor my code in the rare chance when it makes sense.  But in any case, the `as` instance should be addressed.

**Comment by rsmmr** [comment]
how about just forbidding `fallthrough` with `as`, seems an obscure enough combination that no harm would be done there.

**Comment by 0xxon** [comment]
I am re-opening this as a documentation issue - since I assume we should mention this behavior in documentation somewhere.

(If people think that we do not need to mention this - feel free to close).
