### ISSUE TITLE
Kafka plugin broken by  #897 (Mark leaf classes as final)

### ISSUE THREAD

**Issue by l0x-c0d3z** [zeek/zeek#957]
Hi.
4035ec77 broke the kafka writer plugin:

```
/home/v/cts/dev/vendor/metron-bro-plugin-kafka/src/TaggedJSON.h:40:7: error: cannot derive from ‘final’ base ‘threading::formatter::JSON’ in derived type ‘threading::formatter::TaggedJSON’
 class TaggedJSON : public JSON {
       ^~~~~~~~~~
```

Basically, `threading::formatter::JSON` is inherited by a `TaggedJSON` class in the plugin. Marking it as final prevents this, causing build to fail.

I'm guessing there might be other cases of plugins broken by this API change.

**Comment by l0x-c0d3z** [comment]
Also #661 seems to have broken some stuff but is probably easier to figure out.

**Comment by timwoj** [comment]
The JSON one is easy enough to revert. We were fairly sure no one would extend from an existing formatter and instead prefer to write their own.

The `IntrusivePtr` changes are pretty much guaranteed to be "break" things, but they should be reporting deprecation warnings instead of outright causing builds to fail.

**Comment by l0x-c0d3z** [comment]
Haven't dug into it yet, but this is the error I'm getting:
```
/home/v/cts/dev/vendor/metron-bro-plugin-kafka/src/KafkaWriter.cc:62:57: error: cannot convert ‘IntrusivePtr<ListVal>’ to ‘ListVal*’ in initialization
       ListVal* index = val->AsTableVal()->RecoverIndex(k);
```

**Comment by timwoj** [comment]
I reverted the `final` change in https://github.com/zeek/zeek/commit/8ac591c9f58e1098b2cc9c6a2d217aebba30d78a.

**Comment by jsiwek** [comment]
> /home/v/cts/dev/vendor/metron-bro-plugin-kafka/src/KafkaWriter.cc:62:57: error: cannot convert ‘IntrusivePtr<ListVal>’ to ‘ListVal*’ in initialization
>        ListVal* index = val->AsTableVal()->RecoverIndex(k);

Some changes in return value type are going ahead without a deprecation route -- for plugins that want to support multiple Zeek versions, don't think that will ultimately help avoid the need for version-dependent code anyway, maybe like:

```c++
auto index = val->AsTableVal()->RecoverIndex(k);
...
#if !defined(ZEEK_VERSION_NUMBER) || ZEEK_VERSION_NUMBER < 30200
Unref(index);
#endif
```
