### ISSUE TITLE
Kafka plugin installation fails due to missing LibRDKafkaConfig.cmake & librdkafka-config.cmake

### ISSUE THREAD

**Issue by ttrading** [zeek/zeek#961]
Following the official link to install the Kafka plugin on Zeek (3.0.6 LTS) (https://packages.zeek.org/packages/view/0f67010d-f435-11e9-9321-0a645a3f3086) but getting the following error:

[root@target1 ~]# cat /root/.zkg/logs/metron-bro-plugin-kafka-build.log
=== STDERR ===
CMake Error at CMakeLists.txt:20 (include):
  include could not find load file:

    ZeekPlugin

CMake Warning at CMakeLists.txt:21 (find_package):
  By not providing "FindLibRDKafka.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "LibRDKafka", but CMake did not find one.

  Could not find a package configuration file provided by "LibRDKafka" with
  any of the following names:

    LibRDKafkaConfig.cmake
    librdkafka-config.cmake

  Add the installation prefix of "LibRDKafka" to CMAKE_PREFIX_PATH or set
  "LibRDKafka_DIR" to a directory containing one of the above files.  If
  "LibRDKafka" provides a separate development package or SDK, be sure it has
  been installed.

CMake Error at CMakeLists.txt:39 (message):
  LibRDKafka not found.

=== STDOUT ===
Build Directory        : build
Zeek Source Directory   :
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenSSL: /usr/lib64/libcrypto.so (found version "1.0.2k")
-- Configuring incomplete, errors occurred!
See also "/root/.zkg/clones/package/metron-bro-plugin-kafka/build/CMakeFiles/CMakeOutput.log".

Am I missing a dependency here?

Thanks

**Comment by 0xxon** [comment]
Solved on Slack - development headers for Zeek were not installed.
