### ISSUE TITLE
Use CIFuzz

### ISSUE THREAD

**Issue by jsiwek** [zeek/zeek#971]
Now that first steps of integration with OSS-Fuzz are done (#931, #915), can look into extending our CI to fuzz new pull requests: https://google.github.io/oss-fuzz/getting-started/continuous-integration/

Though may not be too worthwhile until we get more fuzz targets added.

**Comment by rsmmr** [comment]
I'll go ahead and close this, not sure it's much of a priority as anything merged will be fuzzed then.
