### ISSUE TITLE
topk_get_top returns a weird type

### ISSUE THREAD

**Issue by vpax** [zeek/zeek#973]
The documentation for `topk_get_top` indicates it returns 

> vector of the first k elements

but if the elements are of type `string`, say, what's returned has type `vector of list of string` rather than `vector of string`. Here's a script that demonstrates this:

    event zeek_init()
        {
        local k1: opaque of topk = topk_init(4);
        topk_add(k1, "c");
        local foo = topk_get_top(k1, 5);
        print type_name(foo);
        }

Indeed, if you try to use the elements directly, such as here:

     event zeek_init()
        {
        local k1: opaque of topk = topk_init(4);
        topk_add(k1, "c");

        local foo = topk_get_top(k1, 5);
        print type_name(foo);
 
        local bar: vector of string;
        local c = foo[0];
        bar += c;
        print bar;
        }

you get a run-time error, `incompatible vector append: string and any (bar += c)`.

If folks agree this is a bug I'll go ahead and fix it, as I believe it's just a simple tweak to correct.

**Comment by vpax** [comment]
BTW, if folks agree this is a bug I'll go ahead and fix it, as I believe it's just a simple tweak to correct.

**Comment by vpax** [comment]
Actually that run-time error is due to `foo` being implicitly typed as `any`. If `foo` is explicitly typed, then the code works.  However, it doesn't change the weirdness.  For example, if rather than appending to `bar`, the script executes `bar = foo;` then `bar`'s type _changes_ from `vector of string` to `vector of list of string`.

**Comment by jsiwek** [comment]
Agree it looks like a bug w/ simple fix.  I'd also expect it to return `vector of string` rather than `vector of list of string`, so if you want to help patch + extend the btest, please go for it.
