### ISSUE TITLE
Bro upgrade

### ISSUE THREAD

**Issue by ysrp4a4** [zeek/zeek#976]
How can I upgrade my bro 2.6 to latest zeek version

**Comment by jsiwek** [comment]
There's a general overview of how to upgrade here:

https://docs.zeek.org/en/lts/install/guidelines.html

I'd suggest following the "Using a New Install Prefix" method.

You may also want to read through the release notes (particularly for 3.1.0 and 3.0.0, where most disruptive changes would have occurred) to see if you'll need to adapt anything

https://github.com/zeek/zeek/blob/v3.1.3/NEWS

The mailing list or slack are also good resources to ask for further help:

https://zeek.org/connect/

**Comment by jsiwek** [comment]
Also remembered this blog which was particularly related to the Bro -> Zeek renaming for 3.0.0 and details some common issues when upgrading:

https://zeek.org/2019/09/23/zeek-3-0-0/
