### ISSUE TITLE
fatal error: Failed to register nb_dns file descriptor with iosource_mgr

### ISSUE THREAD

**Issue by WqyJh** [zeek/zeek#979]
What cause the problem?

OS: CentOS release 6.8 (Final)

```bash
$ sudo zeekctl

Welcome to ZeekControl 2.1.0

Type "help" for help.

[ZeekControl] > install
removing old policies in /usr/local/zeek/spool/installed-scripts-do-not-touch/site ...
removing old policies in /usr/local/zeek/spool/installed-scripts-do-not-touch/auto ...
creating policy directories ...
installing site policies ...
generating standalone-layout.zeek ...
generating local-networks.zeek ...
generating zeekctl-config.zeek ...
generating zeekctl-config.sh ...
[ZeekControl] > start
starting zeek ...
Error: zeek terminated immediately after starting; check output with "diag"
[ZeekControl] > diag
[zeek]

No core file found.

Zeek 3.1.2
Linux 2.6.32-642.15.1.el6.x86_64

Zeek plugins: (none found)

==== No reporter.log

==== stderr.log
error: Failed to register fd 17 from DNS_Mgr: Bad address
fatal error: Failed to register nb_dns file descriptor with iosource_mgr

==== stdout.log
max memory size         (kbytes, -m) unlimited
data seg size           (kbytes, -d) unlimited
virtual memory          (kbytes, -v) unlimited
core file size          (blocks, -c) unlimited

==== .cmdline
-i eth3 -U .status -p zeekctl -p zeekctl-live -p standalone -p local -p zeek local.zeek zeekctl zeekctl/standalone zeekctl/auto

==== .env_vars
PATH=/usr/local/zeek/bin:/usr/local/zeek/share/zeekctl/scripts:/opt/rh/devtoolset-7/root/usr/bin:/usr/local/zeek/bin:/opt/rh/sclo-git212/root/usr/bin:/opt/rh/rh-python36/root/usr/bin:/opt/rh/devtoolset-7/root/usr/bin:/opt/rh/devtoolset-2/root/usr/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/home/vagrant/bin
ZEEKPATH=/usr/local/zeek/spool/installed-scripts-do-not-touch/site::/usr/local/zeek/spool/installed-scripts-do-not-touch/auto:/usr/local/zeek/share/zeek:/usr/local/zeek/share/zeek/policy:/usr/local/zeek/share/zeek/site
CLUSTER_NODE=

==== .status
TERMINATED [fatal_error]

==== No prof.log

==== No packet_filter.log

==== No loaded_scripts.log

```

**Comment by jsiwek** [comment]
Not sure, it works for me on a fresh CentOS 6.8, so anything peculiar about your DNS config or other info you can provide to reproduce it?  Or else these are some instructions to build libkqueue with debugging output which might help point to a cause:

```
git clone --recursive --branch=release/3.1 https://github.com/zeek/zeek
cd zeek
( cd src/3rdparty/libkqueue/ && sed -i 's/RelWithDebInfo/Debug/g' CMakeLists.txt && mkdir build && cd build && cmake3 -DCMAKE_INSTALL_PREFIX=./root -DSTATIC_KQUEUE=yes .. && make install && mv root/lib6464 root/lib && mv root/lib/libkqueued.a root/lib/libkqueue.a )
./configure --with-libkqueue=$(pwd)/src/3rdparty/libkqueue/build/root
cd build
make -j $(nproc)
. zeek-path-dev.sh 
KQUEUE_DEBUG=1 zeek -C -i eth0
```

**Comment by jsiwek** [comment]
You could also compare what the default behavior of Zeek 3.0.x is against Zeek 3.1.x since only the later uses libkqueue (e.g. maybe there's a more useful error message or no error at all).

**Comment by QGrain** [comment]
I have the same error output in a **fresh CentOS 6.8** while running `zeekctl` like:
```bash
$ sudo zeekctl

> install

> start

> diag
```
And I got the same error output like @WqyJh . 

Does zeek-3.1.x really works well on the "CentOS 6.8"? (Giving that the kernel version is  **2.6.32-642.el6.x86_64**)

However, when I change to **zeek-3.0.6**, everything is going well.  XD


> You could also compare what the default behavior of Zeek 3.0.x is against Zeek 3.1.x since only the later uses libkqueue (e.g. maybe there's a more useful error message or no error at all).

**Comment by JustinAzoff** [comment]
Why are you using Centos 6, let alone 6.8 that hasn't had any security updates in 4 years?  Centos 6 becomes completely EOL in 6 months.

plus, af_packet hashing is completely broken on centos 6.

**Comment by WqyJh** [comment]
This problem is caused by libkqueue. I've submit a patch to fix this problem, which should be available on later release of libkqueue. mheily/libkqueue#72

**Comment by WqyJh** [comment]
> Why are you using Centos 6, let alone 6.8 that hasn't had any security updates in 4 years? Centos 6 becomes completely EOL in 6 months.


Well, I also want to ask this question. :) Just to meet the partner's demand.

**Comment by jsiwek** [comment]
@WqyJh thanks for looking into it, Zeek `master` now includes the patched libkqueue and I've also noted to include it in the next Zeek 3.1.x.
