### ISSUE TITLE
Input::end_of_data event not raised from inside the event

### ISSUE THREAD

**Issue by Spartan-F117** [zeek/zeek#990]
Inside zeek_init() I read data from file and when the data is ready the event Input::end_of_data is rightly raised. However, if I try to read another file inside this event (Input::end_of_data), this event is no longer raised.
Briefly: the Input::end_of_data event is raised only if a file is read outside the event itself. But what if I only needed to read a file when I finished reading the previous files?

**Comment by JustinAzoff** [comment]
Do you have a script that shows this behavior?

**Comment by Spartan-F117** [comment]
Yes sure! Sorry if I haven't posted it before.

#configuration_file.log is a _file_ containing a list of paths

for completeness, I also report the _export_ block
`export{
#Type configuration_file
	type Idx: record {
		path: string;
	};
#-----------------------------
#Type Table AnalaysisBot

	type Idx_Bot: record{
		address: addr;
	};

	type Val_Bot: record{
		Average_Bot: double;
		distinct_server_dns: double; 		
		distinct_sld: double;				
		number_query_dns: double;			
		uniqueness_ratio: double;			
		distinct_tld:	double;				
		distinct_query: double;				
		highest_number_of_request: double; 
		number_failed_query: double;		
		highest_query_per_minute: double; 	
		number_ptr_query: double; 			
		number_mx_query: double;			
		average_query_minute: double; 		
	};
#----------------------------
	global path_tab: set[string] = set();
	global config_file: string;
	global tab_prov_analysisbot: table[addr] of Val_Bot = table();
	global p_path: string;
	global table_bot: table[addr] of double = table();
	global list_table_to_read: set[string] = set();

}`

`event zeek_init(){
	config_file="configuration_file.log";
	Input::add_table([$source=config_file, 
					  $name=config_file,
					  $idx=Idx,
					  $destination=path_tab
					  ]);
	Input::remove(config_file);
}
`
`event Input::end_of_data(name: string, source: string){
	if (name==config_file){
		for (i in path_tab){
			p_path=i+"AnalysisBot.log";
			add list_table_to_read[p_path];
			read_table(p_path,Idx_Bot,Val_Bot,tab_prov_analysisbot);
		}	
	}

	if(name in list_table_to_read){
	**#I NEVER REACH THIS POINT**
		delete list_table_to_read[name];
		for(j in tab_prov_analysisbot)
			if(j in table_bot){
				update_table(j,tab_prov_analysisbot); #OP in a table
			}else{
				add_to_table(j,tab_prov_analysisbot); #OP in a table
			}
	}
}`
where _read_table_ is:

`function read_table(src: string, index: any, values: any, dest: any): bool{
	Input::add_table([$source=src, 
					  $name=src,
					  $idx=index,
					  $val=values,
					  $destination=dest
					 ]);
	return Input::remove(src);
}`

**Comment by JustinAzoff** [comment]
That seemed to work when I ran it...  how exactly are  you reproducing this?

I cut your example down to

```
        type Idx_Bot: record{
                address: addr;
        };

        type Val_Bot: record{
                Average_Bot: double;
        };
```

and made a few files and added some prints, and it worked fine.  the output is a  little weird, since it's re-using the table.. you probably  want to use this feature https://docs.zeek.org/en/current/frameworks/input.html#reading-data-to-events

```
justin@mbp:/tmp/b$ cat configuration_file.log
#fields	path
one
two
justin@mbp:/tmp/b$ cat oneAnalysisBot.log
#fields	address	Average_Bot
1.1.1.1	1.1
2.2.2.2	2.2
justin@mbp:/tmp/b$ cat twoAnalysisBot.log
#fields	address	Average_Bot
3.3.3.3	3.3
4.4.4.4	4.4
justin@mbp:/tmp/b$ zeek  ./tables.zeek
end_of_data [configuration_file.log] [configuration_file.log]
Read file twoAnalysisBot.log
Read file oneAnalysisBot.log
end_of_data [oneAnalysisBot.log] [oneAnalysisBot.log]
Got line from oneAnalysisBot.log: 2.2.2.2
Got line from oneAnalysisBot.log: 3.3.3.3
Got line from oneAnalysisBot.log: 4.4.4.4
Got line from oneAnalysisBot.log: 1.1.1.1
end_of_data [twoAnalysisBot.log] [twoAnalysisBot.log]
Got line from twoAnalysisBot.log: 2.2.2.2
Got line from twoAnalysisBot.log: 3.3.3.3
Got line from twoAnalysisBot.log: 4.4.4.4
Got line from twoAnalysisBot.log: 1.1.1.1
```

**Comment by Spartan-F117** [comment]
Sorry in the written code I made a transcription error:
it is not "AnalysisBot.log" but "/Analysisbot.log". It's about taking the file from folders. I hope it doesn't change the result it should return.
I have tried with both _add_event_ and _add_table_.

[workspace.tar.gz](https://github.com/zeek/zeek/files/4712875/workspace.tar.gz)

I am attaching the archive with all the files to execute the code

**Comment by JustinAzoff** [comment]
ah ok.. you just need to set `exit_only_after_terminate=T;` at the top  otherwise it will exit  before it  has a chance to finish. Then you can do something like

```
    if(|list_table_to_read| == 0) {
        print table_bot;
        terminate();
    }
``` in your `Input::end_of_data` to exit once the last file has been read.

**Comment by Spartan-F117** [comment]
Ok now it works, thank you very much!
I thought that `Input::remove` acted as a blocker and therefore the main thread could not end.
