### ISSUE TITLE
zeek-cut leaves tabs where absent fields would have been

### ISSUE THREAD

**Issue by philrz** [zeek/zeek#997]
I ran into this behavior of `zeek-cut` and I think I see what's going on. It feels buggy, though perhaps it could be defended as behavior that Zeek readers would have to conform to, so I'm floating the symptom to see what folks make of it.

Consider the two attached logs I generated in my Zeek v3.1.3 by processing a pcap:

[dns.log](https://github.com/zeek/zeek/files/4724715/dns.log)
[http.log](https://github.com/zeek/zeek/files/4724716/http.log)

Now I run them through `zeek-cut` to generate the attached output (also pasted here for convenience):

```
$ cat dns.log http.log | /usr/local/zeek-3.1.3/bin/zeek-cut -C ts uid uri query > union_cuts.log
$ cat union_cuts.log
#separator \x09
#set_separator	,
#empty_field	(empty)
#unset_field	-
#path	dns
#open	2020-06-03-09-19-23
#fields	ts	uid		query
#types	time	string		string
1521835139.673219	CVqCsY292hwFcxw65e		ocsp.pki.goog
1521835139.673223	CVqCsY292hwFcxw65e		ocsp.pki.goog
#close	2020-06-03-09-19-23
#separator \x09
#set_separator	,
#empty_field	(empty)
#unset_field	-
#path	http
#open	2020-06-03-09-19-23
#fields	ts	uid	uri	
#types	time	string	string	
1521835103.652957	CylHzP24emZcodFVq9	/GTSGIAG3	
1521835105.177261	CylHzP24emZcodFVq9	/GTSGIAG3	
1521835105.567982	CLMRhD2esJWtVdbQO9	/GTSGIAG3	
1521835139.718680	CRstHmFG9jxJ1jjrg	/GTSGIAG3	
#close	2020-06-03-09-19-23
```

[union_cuts.log](https://github.com/zeek/zeek/files/4724722/union_cuts.log)

Close examination of the output shows that in the top results for the `dns` events, there's tabs in the `fields`/`types` headers as well as the event records in the column between `uid` and `query`, i.e. the slot where the not-present-in-`dns`-events `uri` field was referenced on the command line. Likewise, for the `http` events, there's tabs all along the right side of the output corresponding to where `query` was referenced on the command line.

Since this Zeek output contains no explicit indication of how it was generated, it seems like these tabs are not benefitting a user/client and hence I would make the case that they should be trimmed such that each format header block & record sequence only include the named fields relevant to the printed events.

**Comment by JustinAzoff** [comment]
Always trimming it would somewhat break the output.  You're right that it's a bit weird, but right now if you do something like `cat *.log | zeek-cut  ts uid uri query` you can guarantee that each output line will contain 4 fields.  zeek-cut output is often piped to awk and friends, so the columns can't move around.

Adding an option that trims this output and removes the blank columns could be reasonable, but only in combination with the -C option.

**Comment by 0xxon** [comment]
Yup, I agree. Especially given that one of the default use-cases is to forward to awk/tools that expect fixed columns - this seems basically as good as one can do.

**Comment by philrz** [comment]
Ok, thanks @JustinAzoff & @0xxon. It helps that I now understand why it behaves the way it currently does.

In case it's not obvious, the reason I'm asking is because our [`zq`](https://github.com/brimsec/zq) tool didn't know to expect tabs in those locations, so it was choking on the output of `zeek-cut`. The only Zeek outputs we'd tested with previously always had non-tab values in headers & columns. It'd probably not be difficult for us to add code that just skips over the excess tabs when it sees them, so I'll discuss that with the Brim dev team. I get the impression we're the only ones to have ever floated this subject, so as for this issue, feel free to close it as a "Won't Do" or keep it open as guidance for anyone else who stumbles onto it... whatever works best for you.

**Comment by 0xxon** [comment]
I am going to close this - since there is nothing to do on our side.
