### ISSUE TITLE
Reporter::conn_weird segfaults on non existent connections

### ISSUE THREAD

**Issue by julien-piet** [zeek/zeek#998]
Hi,

@anthonykasza and I encountered a segfault while running a script on a RDP pcap. We were able to trace it back to the Reporter::conn_weird call, we believe the reporter is trying to access an undefined (or deleted) member of the connection record. 

Here's a pcap that triggers the behavior : https://github.com/zeek/zeek/blob/master/testing/btest/Traces/rdp/rdp-to-ssl.pcap

The bug is triggered by this script : 
```
module Foo;
export {
  global my_event: event(c: connection);
}
event new_connection(c: connection) {
  schedule 10sec {  Foo::my_event(c) };
}
event Foo::my_event(c: connection) {
  Reporter::conn_weird("test!", c, "test2");
}
```

Thanks !
Julien

**Comment by JustinAzoff** [comment]
This reproduces it even simpler on any pcap:

```
event my_event(c: connection) {
  Reporter::conn_weird("test!", c, "test2");
}
event connection_state_remove(c: connection) {
  schedule 1sec {  my_event(c) };
}
```

looks like just calling conn_weird on a connection that has ended is what crashes.

**Comment by julien-piet** [comment]
We tried adding `print c;` right before calling conn_weird, it works fine and prints the connection record, so it seems like the c RecordVal is still intact when the call to conn_weird happens

**Comment by jsiwek** [comment]
> We tried adding `print c;` right before calling conn_weird, it works fine and prints the connection record, so it seems like the c RecordVal is still intact when the call to conn_weird happens

The `connection` (script-layer name) as a `RecordVal` and the actual `Connection` 
 (c++-layer name) object are currently treated as separate objects.  There's a way to map the `RecordVal` to the `Connection` which BIFs use, but there's not any reference counting being done for the mapped `Connection`.  That's explains the `RecordVal` being valid at the time of call, but the associated `Connection` has already been deleted.

I'm not sure there's good reason to really have these two objects disconnected with different lifetimes.  `Connection` objects would use more memory, but if a user desires to keep that object around longer for purposes like this, I think that could be fine to just allow it.

Don't quite know what the implementation of extending the `Connection` lifetime looks like though.  If we add reference counting between the separate `RecordVal` and `Connection` objects to allow extending the life of the later, that's going to be an annoying reference cycle to deal with, so wonder if `Connection` can instead be a subclass of `RecordVal` and simply follow the usual reference counting process to determine its lifetime.

**Comment by jsiwek** [comment]
Also, an alternative that may be acceptable in the meantime is to use `Weird::weird()` directly:

```zeek
local i = Weird::Info($ts=network_time(), $name="myweird", $conn=c, $identifier=id_string(c$id));
Weird::weird(i);
```

That won't go through the internal weird sampling mechanisms that can help performance issues with some weirds that occur very frequently, but if that's not a concern you have, it may work out about the same in terms of just getting that data into `weird.log`.

**Comment by julien-piet** [comment]
Thanks for the explanation, and for the alternative ! The inner workings of scriptland values are quite fascinating, I don't know if I can be of any help but let me know if there's anything I can do
