### ISSUE TITLE
DHCP Option 61 H/W Type 0

### ISSUE THREAD

**Issue by ahgit1** [zeek/zeek#999]
In the DHCP Analyzer, option 61 does not take account of the possibility of the client identifier having a value which is not a H/W address as specified in the RFC 2132 para 9.14 (Hardware type 0) . Could this be added ?

**Comment by jsiwek** [comment]
Would this work for you: https://github.com/zeek/zeek/commit/20876f51e4072292737cfe02f73a123c5a7f42ed ?

If you have or can point to a sample pcap to use as test case that may also help.

**Comment by ahgit1** [comment]
That looks great thanks - I’ll give it a go on my data

**Comment by ahgit1** [comment]
This pcap from cloudshark appears to have option 61 with h/w type 0. 
https://www.cloudshark.org/captures/b55357ca2b09

**Comment by ahgit1** [comment]
Tried the updated code with the pcap from cloudshark and it works fine - thanks
